### ISSUE TITLE
airflow worker - ModuleNotFoundError: No module named 'sqla'

### ISSUE THREAD

**Issue by vittico** [apache/airflow#10036]
**Apache Airflow version**: 1.10.11

**Environment**:

- **OS** (e.g. from /etc/os-release): Ubuntu 18LTS

**What happened**:
When starting airflow worker exits with 

```
[2020-07-28 14:17:07,677: CRITICAL/MainProcess] Unrecoverable error: ModuleNotFoundError("No module named 'sqla'",)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/kombu/utils/objects.py", line 42, in __get__
    return obj.__dict__[self.__name__]
KeyError: 'backend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/celery/worker/worker.py", line 208, in start
    self.blueprint.start(self)
  File "/usr/local/lib/python3.6/dist-packages/celery/bootsteps.py", line 115, in start
    self.on_start()
  File "/usr/local/lib/python3.6/dist-packages/celery/apps/worker.py", line 139, in on_start
    self.emit_banner()
  File "/usr/local/lib/python3.6/dist-packages/celery/apps/worker.py", line 154, in emit_banner
    ' \n', self.startup_info(artlines=not use_image))),
  File "/usr/local/lib/python3.6/dist-packages/celery/apps/worker.py", line 217, in startup_info
    results=self.app.backend.as_uri(),
  File "/usr/local/lib/python3.6/dist-packages/kombu/utils/objects.py", line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/usr/local/lib/python3.6/dist-packages/celery/app/base.py", line 1232, in backend
    return self._get_backend()
  File "/usr/local/lib/python3.6/dist-packages/celery/app/base.py", line 949, in _get_backend
    self.loader)
  File "/usr/local/lib/python3.6/dist-packages/celery/app/backends.py", line 74, in by_url
    return by_name(backend, loader), url
  File "/usr/local/lib/python3.6/dist-packages/celery/app/backends.py", line 54, in by_name
    cls = symbol_by_name(backend, aliases)
  File "/usr/local/lib/python3.6/dist-packages/kombu/utils/imports.py", line 57, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'sqla'
```

Config:

```
[core]

# Connection string to the local Postgres database
sql_alchemy_conn = postgresql://airflow:12345678@localhost:5432/airflow

# Class name of the executor
executor = CeleryExecutor

dags_folder = /opt/airflow/dags
base_log_folder = /opt/airflow/logs
#remote_logging
#remote_log_conn_id
#remote_base_log_folder
#encrypt_s3_logs
#logging_level

default_timezone = Americas/Bogota

load_examples = false

[webserver]

web_server_host = 0.0.0.0
access_logfile = /opt/airflow/logs/access.log
error_logfile = /opt/airflow/logs/error.log

default_ui_timezone = Americas/Bogota

expose_config = true

# Run a single gunicorn process for handling requests.
workers = 1

# Require password authentication to the webserver
# authenticate = True
# rbac = True


[celery]

flower_host = 0.0.0.0
broker_url = redis://localhost:6379/0
result_backend = sqla+postgres://airflow:12345678@localhost:5432/airflow
```

**Comment by rootcss** [comment]
@vittico can you tried this:
```
sql_alchemy_conn = postgresql+psycopg2://airflow:12345678@localhost:5432/airflow
result_backend = db+postgresql://airflow:12345678@localhost:5432/airflow
```
The backend alias for database backend in celery is `db`. ([ref](https://github.com/celery/celery/blob/master/celery/app/backends.py#L27))

**Comment by vittico** [comment]
sure! will try! thanks

**Comment by vittico** [comment]
This actually worked, thanks!

Sin mas a que hacer referencia,

Victor Medina
