### ISSUE TITLE
Pickling DAGs fail to run

### ISSUE THREAD

**Issue by kivismik** [apache/airflow#1004]
When we run the scheduler with -p (pickle) option, the celery tasks fail with the following message:
(venv)[airflow@ip-10-0-70-111 ~]$ airflow run load_marketo_enrichments load_daily_emailmap 2016-02-11T00:00:00 --pickle 732946 --local
Traceback (most recent call last):
  File "/mnt/home/airflow/venv/bin/airflow", line 4, in <module>
    **import**('pkg_resources').run_script('airflow==1.6.1', 'airflow')
  File "/mnt/home/airflow/venv/local/lib/python2.7/site-packages/pkg_resources/**init**.py", line 696, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/mnt/home/airflow/venv/local/lib/python2.7/site-packages/pkg_resources/**init**.py", line 1614, in run_script
    exec(code, namespace, namespace)
  File "/mnt/home/airflow/venv/lib/python2.7/site-packages/airflow-1.6.1-py2.7.egg/EGG-INFO/scripts/airflow", line 17, in <module>
    args.func(args)
  File "/mnt/home/airflow/venv/lib/python2.7/site-packages/airflow-1.6.1-py2.7.egg/airflow/bin/cli.py", line 150, in run
    DagPickle).filter(DagPickle.id == args.pickle).first()
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/query.py", line 2634, in first
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/query.py", line 2457, in **getitem**
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/loading.py", line 86, in instances
  File "build/bdist.linux-x86_64/egg/sqlalchemy/util/compat.py", line 200, in raise_from_cause
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/loading.py", line 71, in instances
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/loading.py", line 428, in _instance
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/loading.py", line 486, in _populate_full
  File "build/bdist.linux-x86_64/egg/sqlalchemy/sql/sqltypes.py", line 1258, in process
  File "/mnt/home/airflow/venv/lib/python2.7/site-packages/dill-0.2.5-py2.7.egg/dill/dill.py", line 260, in loads
    return load(file)
  File "/mnt/home/airflow/venv/lib/python2.7/site-packages/dill-0.2.5-py2.7.egg/dill/dill.py", line 250, in load
    obj = pik.load()
  File "/usr/lib64/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/usr/lib64/python2.7/pickle.py", line 1090, in load_global
    klass = self.find_class(module, name)
  File "/mnt/home/airflow/venv/lib/python2.7/site-packages/dill-0.2.5-py2.7.egg/dill/dill.py", line 406, in find_class
    return StockUnpickler.find_class(self, module, name)
  File "/usr/lib64/python2.7/pickle.py", line 1124, in find_class
    __import__(module)
ImportError: No module named unusual_prefix_<DAG_NAME>

**Comment by slvwolf** [comment]
The error is quite misleading but most likely the DAG contains something that can not be pickled.
- https://docs.python.org/2/library/pickle.html#what-can-be-pickled-and-unpickled
