### ISSUE TITLE
Can not started scheduler when use command "airflow scheduler -D"

### ISSUE THREAD

**Issue by wxm245** [apache/airflow#10055]
when i use command "airflow scheduler -D", I found process can not started.
And in files airflow-scheduler.err, airflow-scheduler.out have error info.
airflow-scheduler.err
Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 37, in <module>
    args.func(args)
  File "/usr/local/lib/python3.6/site-packages/airflow/utils/cli.py", line 76, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/airflow/bin/cli.py", line 1213, in scheduler
    job.run()
  File "/usr/local/lib/python3.6/site-packages/airflow/jobs/base_job.py", line 212, in run
    session.commit()
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 1042, in commit
    self.transaction.commit()
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 504, in commit
    self._prepare_impl()
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 483, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 2523, in flush
    self._flush(objects)
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 2664, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 2624, in _flush
    flush_context.execute()
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 213, in save_obj
    ) in _organize_states_for_save(base_mapper, states, uowtransaction):
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 374, in _organize_states_for_save
    base_mapper, uowtransaction, states
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 1602, in _connections_for_states
    connection = uowtransaction.transaction.connection(base_mapper)
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 314, in connection
    return self._connection_for_bind(bind, execution_options)
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 421, in _connection_for_bind
    conn = self._parent._connection_for_bind(bind, execution_options)
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 433, in _connection_for_bind
    conn = bind._contextual_connect()
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 2305, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 2339, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/pool/base.py", line 809, in _checkout
    result = pool._dialect.do_ping(fairy.connection)
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 138, in do_ping
    dbapi_connection.ping(False)
  File "/usr/local/lib64/python3.6/site-packages/pymysql/connections.py", line 534, in ping
    self._execute_command(COMMAND.COM_PING, "")
  File "/usr/local/lib64/python3.6/site-packages/pymysql/connections.py", line 763, in _execute_command
    self._write_bytes(packet)
  File "/usr/local/lib64/python3.6/site-packages/pymysql/connections.py", line 703, in _write_bytes
    self._sock.settimeout(self._write_timeout)
OSError: [Errno 9] Bad file descriptor
Exception ignored in: <function _ConnectionRecord.checkout.<locals>.<lambda> at 0x7f4c393a6ea0>
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/pool/base.py", line 506, in <lambda>
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/pool/base.py", line 706, in _finalize_fairy
  File "/usr/lib64/python3.6/logging/__init__.py", line 1337, in error
  File "/usr/lib64/python3.6/logging/__init__.py", line 1444, in _log
  File "/usr/lib64/python3.6/logging/__init__.py", line 1454, in handle
  File "/usr/lib64/python3.6/logging/__init__.py", line 1516, in callHandlers
  File "/usr/lib64/python3.6/logging/__init__.py", line 865, in handle
  File "/usr/lib64/python3.6/logging/__init__.py", line 1071, in emit
  File "/usr/lib64/python3.6/logging/__init__.py", line 1061, in _open
NameError: name 'open' is not defined

airflow-scheduler.out
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/pool/base.py", line 697, in _finalize_fairy
    fairy._reset(pool)
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/pool/base.py", line 893, in _reset
    pool._dialect.do_rollback(self)
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/dialects/mysql/base.py", line 2374, in do_rollback
    dbapi_connection.rollback()
  File "/usr/local/lib64/python3.6/site-packages/pymysql/connections.py", line 431, in rollback
    self._execute_command(COMMAND.COM_QUERY, "ROLLBACK")
  File "/usr/local/lib64/python3.6/site-packages/pymysql/connections.py", line 763, in _execute_command
    self._write_bytes(packet)
  File "/usr/local/lib64/python3.6/site-packages/pymysql/connections.py", line 703, in _write_bytes
    self._sock.settimeout(self._write_timeout)
OSError: [Errno 9] Bad file descriptor

**Comment by jyoti-dhiman** [comment]
Hi, I have a similar issue, did you find a solution for this?

**Comment by carb1** [comment]
> Hi, I have a similar issue, did you find a solution for this?

i meet this issus today，ten days pass, have you solve this problem?

**Comment by c-hui** [comment]
I have the same err:
```
Traceback (most recent call last):
  File "/home/datastem/pyenv/airflow/bin/airflow", line 37, in <module>
    args.func(args)
  File "/home/datastem/pyenv/airflow/lib/python3.8/site-packages/airflow/utils/cli.py", line 80, in wrapper
    return f(*args, **kwargs)
  File "/home/datastem/pyenv/airflow/lib/python3.8/site-packages/airflow/bin/cli.py", line 1214, in scheduler
    job.run()
  File "/home/datastem/pyenv/airflow/lib/python3.8/site-packages/airflow/jobs/base_job.py", line 212, in run
    session.commit()
  File "/home/datastem/pyenv/airflow/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1036, in commit
    self.transaction.commit()
  File "/home/datastem/pyenv/airflow/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 503, in commit
    self._prepare_impl()
  File "/home/datastem/pyenv/airflow/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 482, in _prepare_impl
    self.session.flush()
  File "/home/datastem/pyenv/airflow/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2496, in flush
    self._flush(objects)
  File "/home/datastem/pyenv/airflow/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2637, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/datastem/pyenv/airflow/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/home/datastem/pyenv/airflow/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/datastem/pyenv/airflow/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2597, in _flush
    flush_context.execute()
  File "/home/datastem/pyenv/airflow/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/home/datastem/pyenv/airflow/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 586, in execute
    persistence.save_obj(
  File "/home/datastem/pyenv/airflow/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 205, in save_obj
    for (
  File "/home/datastem/pyenv/airflow/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 373, in _organize_states_for_save
    for state, dict_, mapper, connection in _connections_for_states(
  File "/home/datastem/pyenv/airflow/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 1602, in _connections_for_states
    connection = uowtransaction.transaction.connection(base_mapper)
  File "/home/datastem/pyenv/airflow/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 313, in connection
    return self._connection_for_bind(bind, execution_options)
  File "/home/datastem/pyenv/airflow/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 420, in _connection_for_bind
    conn = self._parent._connection_for_bind(bind, execution_options)
  File "/home/datastem/pyenv/airflow/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 432, in _connection_for_bind
    conn = bind._contextual_connect()
  File "/home/datastem/pyenv/airflow/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2251, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/home/datastem/pyenv/airflow/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2285, in _wrap_pool_connect
    return fn()
  File "/home/datastem/pyenv/airflow/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 363, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/datastem/pyenv/airflow/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 804, in _checkout
    result = pool._dialect.do_ping(fairy.connection)
  File "/home/datastem/pyenv/airflow/lib/python3.8/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 138, in do_ping
    dbapi_connection.ping(False)
  File "/home/datastem/pyenv/airflow/lib/python3.8/site-packages/pymysql/connections.py", line 546, in ping
    self._execute_command(COMMAND.COM_PING, "")
  File "/home/datastem/pyenv/airflow/lib/python3.8/site-packages/pymysql/connections.py", line 771, in _execute_command
    self._write_bytes(packet)
  File "/home/datastem/pyenv/airflow/lib/python3.8/site-packages/pymysql/connections.py", line 711, in _write_bytes
    self._sock.settimeout(self._write_timeout)
OSError: [Errno 9] Bad file descriptor
Exception ignored in: <function _ConnectionRecord.checkout.<locals>.<lambda> at 0x7fde26ffa1f0>
Traceback (most recent call last):
  File "/home/datastem/pyenv/airflow/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 503, in <lambda>
  File "/home/datastem/pyenv/airflow/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 701, in _finalize_fairy
  File "/usr/local/python38/lib/python3.8/logging/__init__.py", line 1463, in error
  File "/usr/local/python38/lib/python3.8/logging/__init__.py", line 1577, in _log
  File "/usr/local/python38/lib/python3.8/logging/__init__.py", line 1587, in handle
  File "/usr/local/python38/lib/python3.8/logging/__init__.py", line 1649, in callHandlers
  File "/usr/local/python38/lib/python3.8/logging/__init__.py", line 950, in handle
  File "/usr/local/python38/lib/python3.8/logging/__init__.py", line 1182, in emit
  File "/usr/local/python38/lib/python3.8/logging/__init__.py", line 1172, in _open
NameError: name 'open' is not defined
```
apache-airflow         1.10.13
Python 3.8.6
Centos 7

**Comment by dongle94** [comment]
```
Traceback (most recent call last):
  File "/home/smarteye/anaconda3/envs/workflow/bin/airflow", line 37, in <module>
    args.func(args)
  File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/site-packages/airflow/utils/cli.py", line 81, in wrapper
    return f(*args, **kwargs)
  File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/site-packages/airflow/bin/cli.py", line 1316, in scheduler
    job.run()
  File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/site-packages/airflow/jobs/base_job.py", line 212, in run
    session.commit()
  File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1042, in commit
    self.transaction.commit()
  File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 504, in commit
    self._prepare_impl()
  File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 483, in _prepare_impl
    self.session.flush()
  File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2536, in flush
    self._flush(objects)
  File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2678, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2638, in _flush
    flush_context.execute()
  File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 213, in save_obj
    ) in _organize_states_for_save(base_mapper, states, uowtransaction):
  File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 374, in _organize_states_for_save
    base_mapper, uowtransaction, states
  File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 1602, in _connections_for_states
    connection = uowtransaction.transaction.connection(base_mapper)
File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 314, in connection
    return self._connection_for_bind(bind, execution_options)
  File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 421, in _connection_for_bind
    conn = self._parent._connection_for_bind(bind, execution_options)
  File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 433, in _connection_for_bind
    conn = bind._contextual_connect()
  File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2302, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
    return fn()
  File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 809, in _checkout
    result = pool._dialect.do_ping(fairy.connection)
  File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 138, in do_ping
    dbapi_connection.ping(False)
  File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/site-packages/pymysql/connections.py", line 534, in ping
    self._execute_command(COMMAND.COM_PING, "")
  File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/site-packages/pymysql/connections.py", line 763, in _execute_command
    self._write_bytes(packet)
  File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/site-packages/pymysql/connections.py", line 703, in _write_bytes
    self._sock.settimeout(self._write_timeout)
OSError: [Errno 9] Bad file descriptor
Exception ignored in: <function _ConnectionRecord.checkout.<locals>.<lambda> at 0x7f6bff0fd950>
Traceback (most recent call last):
  File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 506, in <lambda>
  File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 706, in _finalize_fairy
  File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/logging/__init__.py", line 1337, in error
  File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/logging/__init__.py", line 1444, in _log
  File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/logging/__init__.py", line 1454, in handle
  File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/logging/__init__.py", line 1516, in callHandlers
  File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/logging/__init__.py", line 865, in handle
  File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/logging/__init__.py", line 1071, in emit
  File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/logging/__init__.py", line 1061, in _open
NameError: name 'open' is not defined
```
Hello. I have same issue when use comman "airflow scheduler -D". 
who can solve this problem...?

**Comment by carb1** [comment]
> ```
> Traceback (most recent call last):
>   File "/home/smarteye/anaconda3/envs/workflow/bin/airflow", line 37, in <module>
>     args.func(args)
>   File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/site-packages/airflow/utils/cli.py", line 81, in wrapper
>     return f(*args, **kwargs)
>   File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/site-packages/airflow/bin/cli.py", line 1316, in scheduler
>     job.run()
>   File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/site-packages/airflow/jobs/base_job.py", line 212, in run
>     session.commit()
>   File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1042, in commit
>     self.transaction.commit()
>   File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 504, in commit
>     self._prepare_impl()
>   File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 483, in _prepare_impl
>     self.session.flush()
>   File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2536, in flush
>     self._flush(objects)
>   File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2678, in _flush
>     transaction.rollback(_capture_exception=True)
>   File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
>     with_traceback=exc_tb,
>   File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
>     raise exception
>   File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2638, in _flush
>     flush_context.execute()
>   File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
>     rec.execute(self)
>   File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
>     uow,
>   File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 213, in save_obj
>     ) in _organize_states_for_save(base_mapper, states, uowtransaction):
>   File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 374, in _organize_states_for_save
>     base_mapper, uowtransaction, states
>   File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 1602, in _connections_for_states
>     connection = uowtransaction.transaction.connection(base_mapper)
> File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 314, in connection
>     return self._connection_for_bind(bind, execution_options)
>   File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 421, in _connection_for_bind
>     conn = self._parent._connection_for_bind(bind, execution_options)
>   File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 433, in _connection_for_bind
>     conn = bind._contextual_connect()
>   File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2302, in _contextual_connect
>     self._wrap_pool_connect(self.pool.connect, None),
>   File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
>     return fn()
>   File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 364, in connect
>     return _ConnectionFairy._checkout(self)
>   File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 809, in _checkout
>     result = pool._dialect.do_ping(fairy.connection)
>   File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 138, in do_ping
>     dbapi_connection.ping(False)
>   File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/site-packages/pymysql/connections.py", line 534, in ping
>     self._execute_command(COMMAND.COM_PING, "")
>   File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/site-packages/pymysql/connections.py", line 763, in _execute_command
>     self._write_bytes(packet)
>   File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/site-packages/pymysql/connections.py", line 703, in _write_bytes
>     self._sock.settimeout(self._write_timeout)
> OSError: [Errno 9] Bad file descriptor
> Exception ignored in: <function _ConnectionRecord.checkout.<locals>.<lambda> at 0x7f6bff0fd950>
> Traceback (most recent call last):
>   File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 506, in <lambda>
>   File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 706, in _finalize_fairy
>   File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/logging/__init__.py", line 1337, in error
>   File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/logging/__init__.py", line 1444, in _log
>   File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/logging/__init__.py", line 1454, in handle
>   File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/logging/__init__.py", line 1516, in callHandlers
>   File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/logging/__init__.py", line 865, in handle
>   File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/logging/__init__.py", line 1071, in emit
>   File "/home/smarteye/anaconda3/envs/workflow/lib/python3.6/logging/__init__.py", line 1061, in _open
> NameError: name 'open' is not defined
> ```
> 
> Hello. I have same issue when use command "airflow scheduler -D".
> who can solve this problem...?

i dont solve this problem too.i use docker now,and it doesnt need 'airflow scheduler',if you only want to set a simple dag, you can try to use docker too

**Comment by c-hui** [comment]
@dongle94 don't use pymysql to connect db backend

**Comment by eldernewborn** [comment]
I'm experiencing this issue, and it seems to stem from "pooling" behavior .
I was able to circumvent it by disabling connection pools : 
`sql_alchemy_pool_enabled = False`
Maybe someone more familiar can help understand why pools break pymysql.

**Comment by Junnplus** [comment]
It seems that the `daemonContext` will close the socket of statsd.
```py
    return self.statsd.incr(stat, count, rate)
  File "/usr/local/lib/python3.8/site-packages/statsd/client/base.py", line 35, in incr
    self._send_stat(stat, '%s|c' % count, rate)
  File "/usr/local/lib/python3.8/site-packages/statsd/client/base.py", line 59, in _send_stat
    self._after(self._prepare(stat, value, rate))
  File "/usr/local/lib/python3.8/site-packages/statsd/client/base.py", line 74, in _after
    self._send(data)
  File "/opt/airflow/airflow/stats.py", line 40, in _send
    self._sock.sendto(data.encode('ascii'), self._addr)
OSError: [Errno 9] Bad file descriptor
```

**Comment by ashb** [comment]
Unable to reproduce this problem on Airflow 2.0.
