### ISSUE TITLE
Mark Failed with Future Downstream fails in fresh airflow install

### ISSUE THREAD

**Issue by reverse-engineer** [apache/airflow#10112]
**Apache Airflow version**: 1.10.11

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): no kubernetes

**Environment**:

- **Cloud provider or hardware configuration**: Intel x86_64
- **OS** (e.g. from /etc/os-release): Debian 10
- **Kernel** (e.g. `uname -a`): 4.19.118-2+deb10u1 (2020-06-07)
- **Install tools**: pip with Python 3.7.7
- **Others**:

**What happened**:

Airflow Web UI fails with `IndexError: list index out of range`.

**What you expected to happen**:

Airflow should show a 'Wait a minute' list with the tasks to mark as failed.

**How to reproduce it**:
Install a fresh airflow in a python 3.7.7 environment: `pip install apache-airflow`
Simply init the sqlite db: `airflow initdb`
Run airflow webserver and scheduler to see the example DAGs: `airflow webserver` and `airflow scheduler`
Enable the first example DAG (`example_bash_operator`) and wait for it to complete (it should have run successfully on two dates).
Click the DAG to see the tasks and then click the left- uppermost task, then highlight 'Future', 'Downstream' buttons under 'Mark Failed', then click 'Mark Failed'.
This should generate the mentioned error (which is a pendulum error).

**Anything else we need to know**:

This error seems to have been reported before here: https://issues.apache.org/jira/browse/AIRFLOW-5452?page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel&focusedCommentId=16926725#comment-16926725
But seems never to have been fixed. It mentions some bug in pendulum here: https://github.com/sdispater/pendulum/issues/160.

The same issue occurs with 'Mark Success'.

I'm a bit surprised by this bug in quite basic functionality, hope I didn't miss anything stupid...

Full log here:
<details><summary>Airflow UI log</summary>

                              ____/ (  (    )   )  \___
                             /( (  (  )   _    ))  )   )\
                           ((     (   )(    )  )   (   )  )
                         ((/  ( _(   )   (   _) ) (  () )  )
                        ( (  ( (_)   ((    (   )  .((_ ) .  )_
                       ( (  )    (      (  )    )   ) . ) (   )
                      (  (   (  (   ) (  _  ( _) ).  ) . ) ) ( )
                      ( (  (   ) (  )   (  ))     ) _)(   )  )  )
                     ( (  ( \ ) (    (_  ( ) ( )  )   ) )  )) ( )
                      (  (   (  (   (_ ( ) ( _    )  ) (  )  )   )
                     ( (  ( (  (  )     (_  )  ) )  _)   ) _( ( )
                      ((  (   )(    (     _    )   _) _(_ (  (_ )
                       (_((__(_(__(( ( ( |  ) ) ) )_))__))_)___)
                       ((__)        \\||lll|l||///          \_))
                                (   /(/ (  )  ) )\   )
                              (    ( ( ( | | ) ) )\   )
                               (   /(| / ( )) ) ) )) )
                             (     ( ((((_(|)_)))))     )
                              (      ||\(|(|)|/||     )
                            (        |(||(||)||||        )
                              (     //|/l|||)|\\ \     )
                            (/ / //  /|//||||\\  \ \  \ _)
    -------------------------------------------------------------------------------
    Node: A-laptop.home
    -------------------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/auser/.conda/envs/airflow_test/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
        response = self.full_dispatch_request()
      File "/home/auser/.conda/envs/airflow_test/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
        rv = self.handle_user_exception(e)
      File "/home/auser/.conda/envs/airflow_test/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
        reraise(exc_type, exc_value, tb)
      File "/home/auser/.conda/envs/airflow_test/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
        raise value
      File "/home/auser/.conda/envs/airflow_test/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
        rv = self.dispatch_request()
      File "/home/auser/.conda/envs/airflow_test/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
      File "/home/auser/.conda/envs/airflow_test/lib/python3.7/site-packages/flask_admin/base.py", line 69, in inner
        return self._run_view(f, *args, **kwargs)
      File "/home/auser/.conda/envs/airflow_test/lib/python3.7/site-packages/flask_admin/base.py", line 368, in _run_view
        return fn(self, *args, **kwargs)
      File "/home/auser/.conda/envs/airflow_test/lib/python3.7/site-packages/flask_login/utils.py", line 258, in decorated_view
        return func(*args, **kwargs)
      File "/home/auser/.conda/envs/airflow_test/lib/python3.7/site-packages/airflow/www/utils.py", line 286, in wrapper
        return f(*args, **kwargs)
      File "/home/auser/.conda/envs/airflow_test/lib/python3.7/site-packages/airflow/www/utils.py", line 333, in wrapper
        return f(*args, **kwargs)
      File "/home/auser/.conda/envs/airflow_test/lib/python3.7/site-packages/airflow/www/views.py", line 1525, in failed
        future, past, State.FAILED)
      File "/home/auser/.conda/envs/airflow_test/lib/python3.7/site-packages/airflow/www/views.py", line 1496, in _mark_task_instance_state
        commit=False)
      File "/home/auser/.conda/envs/airflow_test/lib/python3.7/site-packages/airflow/utils/db.py", line 74, in wrapper
        return func(*args, **kwargs)
      File "/home/auser/.conda/envs/airflow_test/lib/python3.7/site-packages/airflow/api/common/experimental/mark_tasks.py", line 105, in set_state
        dates = get_execution_dates(dag, execution_date, future, past)
      File "/home/auser/.conda/envs/airflow_test/lib/python3.7/site-packages/airflow/api/common/experimental/mark_tasks.py", line 262, in get_execution_dates
        dates = dag.date_range(start_date=start_date, end_date=end_date)
      File "/home/auser/.conda/envs/airflow_test/lib/python3.7/site-packages/airflow/models/dag.py", line 390, in date_range
        num=num, delta=self.normalized_schedule_interval)
      File "/home/auser/.conda/envs/airflow_test/lib/python3.7/site-packages/airflow/utils/dates.py", line 89, in date_range
        end_date = timezone.make_naive(end_date, tz)
      File "/home/auser/.conda/envs/airflow_test/lib/python3.7/site-packages/airflow/utils/timezone.py", line 148, in make_naive
        o = value.astimezone(timezone)
      File "/home/auser/.conda/envs/airflow_test/lib/python3.7/site-packages/pendulum/tz/timezone_info.py", line 99, in fromutc
        tzinfo = self._tz._tzinfos[self._tz._transitions[idx]._tzinfo_index]
    IndexError: list index out of range

</details>

**Comment by reverse-engineer** [comment]
Upon further investigation, this seems to be due to the fact that the `execution_date` is a `Pendulum` object, while other DAG dates in the code (`start_date`, `end_date`, etc.) are `datetime.datetime` objects. [Here](https://github.com/apache/airflow/blob/1.10.11/airflow/www/views.py#L1472), the execution date is parsed as a pendulum object.

The bug occurs then because when selecting 'Future' to mark failed, `start_date` is [replaced](https://github.com/apache/airflow/blob/1.10.11/airflow/api/common/experimental/mark_tasks.py#L253) by `execution_date`, and later on, that `start_date`'s timezone (at that point it has become a pendulum TimezoneInfo object) is [used](https://github.com/apache/airflow/blob/1.10.11/airflow/utils/dates.py#L79) in `make_naive` for `end_date` [here](https://github.com/apache/airflow/blob/1.10.11/airflow/utils/dates.py#L89), which seems to cause the bug.

Maybe when `start_date` is replaced by `execution_date`, it should be converted to a `datetime.datetime`?
Replacing this:

```
    start_date = execution_date if not past else start_date
```
with:

```
    start_date = datetime.datetime(execution_date.year,
                                   execution_date.month,
                                   execution_date.day,
                                   execution_date.hour,
                                   execution_date.minute,
                                   execution_date.second,
                                   execution_date.microsecond,
                                   tzinfo=execution_date.tz) if not past else start_date
```
in https://github.com/apache/airflow/blob/1.10.11/airflow/api/common/experimental/mark_tasks.py#L253 seems to work for me locally, but I didn't run all the tests etc. (I don't have a development environment), so I don't know if a airflow dev could have a look at this?

**Comment by eladkal** [comment]
Can you please check if the issue still present in latest Airflow version?

**Comment by reverse-engineer** [comment]
@eladkal 
Airflow 2.2.1 gives me an error while doing a fresh `db init`...

    alembic.util.exc.CommandError: Migration "upgrade 127d2bf2dfa7 -> cc1e65623dc7, add max tries column to task instance" has left an uncommitted transaction opened; transactional_ddl is False so Alembic is not committing transactions

Will test at the next released version, I guess..`

**Comment by reverse-engineer** [comment]
@eladkal Yes this is fixed now!
