### ISSUE TITLE
Deadlock Exception with MSSQL as backend DB

### ISSUE THREAD

**Issue by mattinbits** [apache/airflow#10221]
**Apache Airflow version**: 1.10.9

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**: On premise infrastructure. Scheduler is a CENTOS 7 docker image running on a RHEL 7 server. Database is SQL Server 2016
- **OS** (e.g. from /etc/os-release): CentOS Linux 7 (Core)
- **Kernel** (e.g. `uname -a`): 3.10.0-1127.13.1.el7.x86_64
- **Install tools**:
- **Others**:

**What happened**:

We have a DAG where several file sensors wait for similar files in parallel, using "reschedule" mode. Periodically, one or more of these tasks fail. The logs show a deadlock reported from the Database:

```
sqlalchemy.exc.DBAPIError: (pyodbc.Error) ('40001', '[40001] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Transaction (Process ID 111) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction. (1205) (SQLExecDirectW)')
[SQL: SELECT count(*) AS count_1
FROM task_instance
WHERE task_instance.pool = ? AND task_instance.state IN (?, ?)]
[parameters: ('default_pool', 'running', 'queued')]
(Background on this error at: http://sqlalche.me/e/dbapi)
```
Checking this query directly using SSMS, I can see it executes immediately and uses the ti_pool index.

And the associated stack trace:

```
Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 37, in <module>
    args.func(args)
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/cli.py", line 75, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/bin/cli.py", line 545, in run
    _run(args, dag, ti)
  File "/usr/local/lib/python3.7/site-packages/airflow/bin/cli.py", line 460, in _run
    run_job.run()
  File "/usr/local/lib/python3.7/site-packages/airflow/jobs/base_job.py", line 221, in run
    self._execute()
  File "/usr/local/lib/python3.7/site-packages/airflow/jobs/local_task_job.py", line 90, in _execute
    pool=self.pool):
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/db.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 851, in _check_and_change_state_before_execution
    verbose=True):
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/db.py", line 70, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 644, in are_dependencies_met
    session=session):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 668, in get_failed_dep_statuses
    dep_context):
  File "/usr/local/lib/python3.7/site-packages/airflow/ti_deps/deps/base_ti_dep.py", line 106, in get_dep_statuses
    for dep_status in self._get_dep_statuses(ti, session, dep_context):
  File "/usr/local/lib/python3.7/site-packages/airflow/ti_deps/deps/pool_slots_available_dep.py", line 62, in _get_dep_statuses
    open_slots = pools[0].open_slots()
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/db.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/pool.py", line 113, in open_slots
    return self.slots - self.occupied_slots(session)
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/db.py", line 70, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/pool.py", line 70, in occupied_slots
    .filter(TaskInstance.state.in_(STATES_TO_COUNT_AS_RUNNING))
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3469, in scalar
    ret = self.one()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3436, in one
    ret = self.one_or_none()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3405, in one_or_none
    ret = list(self)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3481, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3506, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1020, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_clauseelement
    distilled_params,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1324, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1518, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1284, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
```

**What you expected to happen**:
The tasks succeed/reschedule as expected.

**How to reproduce it**:

I have struggled to reproduce this locally away from our production environment. I suspect it is related to the size of the task_instance table and therefore hard to reproduce locally on a clean instance of airflow. 

**Anything else we need to know**:

**Comment by mik-laj** [comment]
MSSQL is not official supported by Airflow. See: https://github.com/apache/airflow/issues/10713
