### ISSUE TITLE
PostgresOperator does not support sql files outside of dags folder.

### ISSUE THREAD

**Issue by lenguyenthedat** [apache/airflow#1027]
```
t1 = PostgresOperator(
    task_id='test',
    postgres_conn_id='test',
    sql='sqls/test/test.sql',
    dag=dag
)

t2 = PostgresOperator(
    task_id='test-outside',
    postgres_conn_id='test',
    sql='/path/to/test-outside.sql',
    dag=dag
)
```

t1 will work but t2 won't work with neither relative nor absolute path. Error looks like this:

```
[2016-02-18 15:55:51,996] {models.py:1670} ERROR - /path/to/test-outside.sql
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/airflow/models.py", line 1668, in resolve_template_files
    setattr(self, attr, env.loader.get_source(env, content)[0])
  File "/usr/local/lib/python2.7/site-packages/jinja2/loaders.py", line 187, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: /path/to/test-outside.sql
```

**Comment by mistercrunch** [comment]
Check out the `template_searchpath` attribute of the DAG object.
http://pythonhosted.org/airflow/code.html#airflow.models.DAG

You can also pass sql as a string to the operator.

Another shortcut option is `airflow.utils.readfile` which doesn't do much but is a clean shortcut that will take a fullpath.
https://github.com/airbnb/airflow/blob/master/airflow/utils.py#L414
