### ISSUE TITLE
FILES_FOR_REBUILD_CHECK[@]: unbound variable

### ISSUE THREAD

**Issue by turbaszek** [apache/airflow#10425]
**Apache Airflow version**:

Current master

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **OS** (e.g. from /etc/os-release): MacOS

**What happened**:

```
➜ ./breeze prepare-backport-packages 2020.07.27 cncf
/Users/tomaszurbaszek/airflow/scripts/ci/libraries/_md5sum.sh: line 86: FILES_FOR_REBUILD_CHECK[@]: unbound variable
```

**What you expected to happen**:

I would love to build packages

**How to reproduce it**:

Just run
```
./breeze prepare-backport-packages 2020.07.27 cncf
```

**Anything else we need to know**:

N/A

**Comment by turbaszek** [comment]
@potiuk any ideas?

**Comment by turbaszek** [comment]
When I move back to 5739ba28a Fix broken breeze script (#10418) everything seems to be ok.

**Comment by potiuk** [comment]
Mac issue

**Comment by potiuk** [comment]
You need to run `./breeze prepare-backport-packages 2020.07.27 cncf.kubernetes` (and there you get another issue - with missing README.md that you have to add). But I have different (correct) output in Linux so I have to double check it. The output I have:

```
Building backport package: cncf.kubernetes
Traceback (most recent call last):
  File "setup_backport_packages.py", line 1233, in <module>
    do_setup_package_providers(provider_package_id=provider_package,
  File "setup_backport_packages.py", line 269, in do_setup_package_providers
    long_description=get_long_description(provider_package_id),
  File "setup_backport_packages.py", line 218, in get_long_description
    with open(os.path.join(package_folder, "README.md"), encoding='utf-8') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/backport_packages/airflow/providers/cncf/kubernetes/README.md'
###########################################################################################
  [IN CONTAINER]   EXITING /opt/airflow/scripts/ci/in_container/run_prepare_backport_packages.sh WITH STATUS CODE 1
###########################################################################################

```

**Comment by potiuk** [comment]
And this is the output I have on Linux if I run your command:


```
===================================================================================
 Preparing backport package 2020.07.27
-----------------------------------------------------------------------------------

ERROR! Wrong first param: 2020.07.27


You should provide PACKAGE as first of the setup.py arguments
Available packages: 

amazon apache.cassandra apache.druid apache.hdfs apache.hive apache.kylin
apache.livy apache.pig apache.pinot apache.spark apache.sqoop celery cloudant
cncf.kubernetes databricks datadog dingding discord docker elasticsearch exasol
facebook ftp google grpc hashicorp http imap jdbc jenkins jira microsoft.azure
microsoft.mssql microsoft.winrm mongo mysql odbc openfaas opsgenie oracle
pagerduty papermill postgres presto qubole redis salesforce samba segment sftp
singularity slack snowflake sqlite ssh vertica yandex zendesk

Additional commands:

  list-providers-packages       - lists all provider packages
  list-backportable-packages    - lists all packages that are backportable
  update-package-release-notes [YYYY.MM.DD] [PACKAGES] - updates package release notes
  --version-suffix <SUFFIX>     - adds version suffix to version of the packages.
```

**Comment by potiuk** [comment]
I will double check it on mac and see where the undefined variable comes from

**Comment by turbaszek** [comment]
> (and there you get another issue - with missing README.md that you have to add

I solved this with changing mode to `w+`
