### ISSUE TITLE
Installing apache-airflow==1.9.0: gitpython not found: Cannot compute the git version.

### ISSUE THREAD

**Issue by megancooper** [apache/airflow#10679]
**Error while installing apache-airflow==1.9.0**

Currently have been installing this package during deployment in a circleci job. Installing the package has just stopped working (we've made no changes on our end...)

The circle ci job uses a python virtual environment, that is setup as follows:

```
python3 -m venv venv
. venv/bin/activate
pip install --upgrade pip
pip install --upgrade setuptools
```
And then we run `pip install -r requirements.txt` which starts installing packages (apache-airflow==1.9.0)

```
Collecting apache-airflow==1.9.0
  Downloading apache-airflow-1.9.0.tar.gz (2.4 MB)
     |███████████                     | 808 kB 54.0 MB/s eta 0:00:01
     |█�███████████████████▊          | 1.6 MB 54.0 MB/s eta 0:00:01
     |█████████████�████████████████▊ | 2.3 MB 54.0 MB/s eta 0:00:01
     |████████████████████████████████| 2.4 MB 54.0 MB/s eta 0:00:01
    ERROR: Command errored out with exit status 1:
     command: /home/circleci/repo/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-67mghsfe/apache-airflow/setup.py'"'"'; __file__='"'"'/tmp/pip-install-67mghsfe/apache-airflow/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-9ihurkg_
         cwd: /tmp/pip-install-67mghsfe/apache-airflow/
    Complete output (20 lines):
    /home/circleci/repo/venv/lib/python3.6/site-packages/_distutils_hack/__init__.py:30: UserWarning: Setuptools is replacing distutils.
      warnings.warn("Setuptools is replacing distutils.")
    gitpython not found: Cannot compute the git version.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-67mghsfe/apache-airflow/setup.py", line 308, in <module>
        do_setup()
      File "/tmp/pip-install-67mghsfe/apache-airflow/setup.py", line 302, in do_setup
        'extra_clean': CleanCommand,
      File "/home/circleci/repo/venv/lib/python3.6/site-packages/setuptools/__init__.py", line 152, in setup
        _install_setup_requires(attrs)
      File "/home/circleci/repo/venv/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in _install_setup_requires
        dist.parse_config_files(ignore_option_errors=True)
      File "/home/circleci/repo/venv/lib/python3.6/site-packages/setuptools/dist.py", line 665, in parse_config_files
        self._parse_config_files(filenames=filenames)
      File "/home/circleci/repo/venv/lib/python3.6/site-packages/setuptools/dist.py", line 572, in _parse_config_files
        filenames = self.find_config_files()
      File "/home/circleci/repo/venv/lib/python3.6/site-packages/setuptools/_distutils/dist.py", line 353, in find_config_files
        sys_dir = os.path.dirname(sys.modules['distutils'].__file__)
    KeyError: 'distutils'
    ----------------------------------------
```

**Comment by megancooper** [comment]
Resolved by setting:
`export SETUPTOOLS_USE_DISTUTILS=1`

See this issue here:
https://github.com/pypa/setuptools/issues/2351
