### ISSUE TITLE
SQLite delete task instance, TypeError datetime

### ISSUE THREAD

**Issue by audubon** [apache/airflow#1069]
trying to delete a task instance causes error
StatementError: (exceptions.TypeError) SQLite DateTime type only accepts Python datetime and date objects as input

**Comment by mistercrunch** [comment]
Stack trace please. I think this is fixed on master.

**Comment by audubon** [comment]
stacktrace:

Traceback (most recent call last):
  File "/python/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/python/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/python/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/python/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/python/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/python/lib/python2.7/site-packages/flask_admin/base.py", line 68, in inner
    return self._run_view(f, _args, *_kwargs)
  File "/python/lib/python2.7/site-packages/flask_admin/base.py", line 359, in _run_view
    return fn(self, _args, *_kwargs)
  File "/python/lib/python2.7/site-packages/flask_admin/model/base.py", line 1668, in delete_view
    model = self.get_one(id)
  File "/python/lib/python2.7/site-packages/flask_admin/contrib/sqla/view.py", line 959, in get_one
    return self.session.query(self.model).get(tools.iterdecode(id))
  File "/python/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 818, in get
    return self._get_impl(ident, loading.load_on_ident)
  File "/python/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 851, in _get_impl
    return fallback_fn(self, key)
  File "/python/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 217, in load_on_ident
    return q.one()
  File "/python/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2472, in one
    ret = list(self)
  File "/python/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2515, in __iter__
    return self._execute_and_instances(context)
  File "/python/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2530, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/python/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/python/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/python/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/python/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1078, in _execute_context
    None, None)
  File "/python/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/python/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/python/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1073, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "/python/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 582, in _init_compiled
    param.append(processors[key](compiled_params[key]))
  File "/python/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/base.py", line 601, in process
    raise TypeError("SQLite DateTime type only accepts Python "
StatementError: (exceptions.TypeError) SQLite DateTime type only accepts Python datetime and date objects as input. [SQL: u'SELECT task_instance.task_id AS task_instance_task_id, task_instance.dag_id AS task_instance_dag_id, task_instance.execution_date AS task_instance_execution_date, task_instance.start_date AS task_instance_start_date, task_instance.end_date AS task_instance_end_date, task_instance.duration AS task_instance_duration, task_instance.state AS task_instance_state, task_instance.try_number AS task_instance_try_number, task_instance.hostname AS task_instance_hostname, task_instance.unixname AS task_instance_unixname, task_instance.job_id AS task_instance_job_id, task_instance.pool AS task_instance_pool, task_instance.queue AS task_instance_queue, task_instance.priority_weight AS task_instance_priority_weight, task_instance.operator AS task_instance_operator, task_instance.queued_dttm AS task_instance_queued_dttm \nFROM task_instance \nWHERE task_instance.task_id = ? AND task_instance.dag_id = ? AND task_instance.execution_date = ?'] [parameters: [{'%(139904250194576 param)s': u'uid_dag', '%(139904250195536 param)s': u'2016-01-04 22:00:00', '%(139904250194640 param)s': u'import_ui'}]]

**Comment by mistercrunch** [comment]
Oh yeah, I remember this one. That's a `flask_admin` bug. It's related to having a date field in a model's pk, and specific to sqlite since it doesn't auto-cast.

As far as Airflow goes, it seems somewhat low-pri since no-one should be using sqlite in production...
