### ISSUE TITLE
Running individual task from WEB UI leaks worker thread 

### ISSUE THREAD

**Issue by djerraballi** [apache/airflow#10978]
**Apache Airflow version**:
1.10.12

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):
N/A

**Environment**:

- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): Debian Stretch
- **Kernel** (e.g. `uname -a`): Linux amzn2.x86_64
- **Install tools**:
- **Others**:
relevant configurations for webserver: 
```
web_server_master_timeout = 120
web_server_worker_timeout = 120
worker_refresh_batch_size = 1
worker_refresh_interval = 30
worker_class = eventlet
```

**What happened**:

Running an individual task (After clearing state) from the WebUI succesfully adds the task to the worker queue, but the webserver worker responsible for handling the request is leaked (until worker timeout is hit). 

Successful queue addition: 
```
[2020-09-15 16:30:34,215] {{base_executor.py:58}} INFO - Adding to queue: ['airflow', 'run', 'hello_world', 'hello_task', '2020-09-15T09:37:37.147779+00:00', '--local', '--pool', 'default_pool', '-sd', 'DAGS_FOLDER/hello_world_dag.py']
```

Airflow timeout: 
```
[2020-09-15 16:35:30 +0000] [2420] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/geventlet.py", line 99, in init_process
    super().init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 140, in init_process
    self.run()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/geventlet.py", line 131, in run
    eventlet.sleep(1.0)
  File "/usr/local/lib/python3.6/site-packages/eventlet/greenthread.py", line 36, in sleep
    hub.switch()
  File "/usr/local/lib/python3.6/site-packages/eventlet/hubs/hub.py", line 298, in switch
    return self.greenlet.switch()
  File "/usr/local/lib/python3.6/site-packages/eventlet/hubs/hub.py", line 350, in run
    self.wait(sleep_time)
  File "/usr/local/lib/python3.6/site-packages/eventlet/hubs/poll.py", line 80, in wait
    presult = self.do_poll(seconds)
  File "/usr/local/lib/python3.6/site-packages/eventlet/hubs/epolls.py", line 31, in do_poll
    return self.poll.poll(seconds)
  File "/usr/local/src/apache-airflow/airflow/utils/timeout.py", line 43, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: Timeout, PID: 2420
```

**What you expected to happen**:

Expect the webserver worker to not timeout after succesfully adding the task to the queue. 

Unsure here on where to start looking could use some pointers. 

**How to reproduce it**:

**Anything else we need to know**:

- this occurs every time that we hit run from the webserver UI, no matter which individual task is rerun. 
- If more than two tasks are run (or even if the run button is simply double pressed, this effectively starves our webserver of workers. Once all the workers are leaked, even healthchecks to the webserver will fail. This will cause any liveness probe to reploy the task/pod. (In our case its a task since we are running on ECS). 

-->

**Comment by eladkal** [comment]
Is this still an issue in latest Airflow version?
