### ISSUE TITLE
Can't get login to work after upgrades to flask.

### ISSUE THREAD

**Issue by planenutz** [apache/airflow#1107]
We recently upgraded several components in our python disto and now get failures when connecting to the web server. 

Traceback (most recent call last):
  File "/home/vccorp/apps/python/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vccorp/apps/python/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vccorp/apps/python/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vccorp/apps/python/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vccorp/apps/python/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vccorp/apps/python/lib/python2.7/site-packages/flask_admin/base.py", line 68, in inner
    return self._run_view(f, _args, *_kwargs)
  File "/home/vccorp/apps/python/lib/python2.7/site-packages/flask_admin/base.py", line 367, in _run_view
    return fn(self, _args, *_kwargs)
  File "/home/vccorp/apps/airflow/lib/python2.7/site-packages/airflow/www/views.py", line 673, in login
    return airflow.login.login(self, request)
  File "/home/vccorp/apps/airflow/lib/python2.7/site-packages/airflow/contrib/auth/backends/cnvr_ldap_auth.py", line 103, in login
    if current_user.is_authenticated():
TypeError: 'bool' object is not callable

Does anyone know if later version of flask are incompatible with airflow 1.6.2?

**Comment by artwr** [comment]
At some point in the past year, Flask-login changed the `is_authenticated()` to an `is_authenticated` property on the user class.

There is a workaround suggested in the stackoverflow question below that might work if implemented in your custom ldap_backend.
http://stackoverflow.com/questions/33274337/how-to-call-is-authenticated-in-flask-login

**Comment by artwr** [comment]
For the reference on the Flask-login change:
https://github.com/maxcountryman/flask-login/blob/master/CHANGES#L43

**Comment by planenutz** [comment]
Downgraded flask_admin to 0.2.11 and we're good. This isn't the ideal solution but workable for now. 

Thanks for the help.
