### ISSUE TITLE
Nuclear cloud when accessing task details that has no dag runs

### ISSUE THREAD

**Issue by turbaszek** [apache/airflow#11328]
**Apache Airflow version**:
1.1010, 1.10.12 and probably previous ones. On master it doesn't occur.

**Environment**:

Tested with breeze and 1.1010 and 1.10.12 versions.

**What happened**:

```

                          ____/ (  (    )   )  \___
                         /( (  (  )   _    ))  )   )\
                       ((     (   )(    )  )   (   )  )
                     ((/  ( _(   )   (   _) ) (  () )  )
                    ( (  ( (_)   ((    (   )  .((_ ) .  )_
                   ( (  )    (      (  )    )   ) . ) (   )
                  (  (   (  (   ) (  _  ( _) ).  ) . ) ) ( )
                  ( (  (   ) (  )   (  ))     ) _)(   )  )  )
                 ( (  ( \ ) (    (_  ( ) ( )  )   ) )  )) ( )
                  (  (   (  (   (_ ( ) ( _    )  ) (  )  )   )
                 ( (  ( (  (  )     (_  )  ) )  _)   ) _( ( )
                  ((  (   )(    (     _    )   _) _(_ (  (_ )
                   (_((__(_(__(( ( ( |  ) ) ) )_))__))_)___)
                   ((__)        \\||lll|l||///          \_))
                            (   /(/ (  )  ) )\   )
                          (    ( ( ( | | ) ) )\   )
                           (   /(| / ( )) ) ) )) )
                         (     ( ((((_(|)_)))))     )
                          (      ||\(|(|)|/||     )
                        (        |(||(||)||||        )
                          (     //|/l|||)|\\ \     )
                        (/ / //  /|//||||\\  \ \  \ _)
-------------------------------------------------------------------------------
Node: 72e5af4b0b01
-------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/flask_admin/base.py", line 69, in inner
    return self._run_view(f, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask_admin/base.py", line 368, in _run_view
    return fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask_login/utils.py", line 258, in decorated_view
    return func(*args, **kwargs)
  File "/opt/airflow/airflow/www/utils.py", line 290, in wrapper
    return f(*args, **kwargs)
  File "/opt/airflow/airflow/www/views.py", line 1064, in task
    dep_context=dep_context)]
  File "/opt/airflow/airflow/www/views.py", line 1062, in <listcomp>
    failed_dep_reasons = [(dep.dep_name, dep.reason) for dep in
  File "/opt/airflow/airflow/models/taskinstance.py", line 683, in get_failed_dep_statuses
    dep_context):
  File "/opt/airflow/airflow/ti_deps/deps/base_ti_dep.py", line 106, in get_dep_statuses
    for dep_status in self._get_dep_statuses(ti, session, dep_context):
  File "/opt/airflow/airflow/ti_deps/deps/dagrun_id_dep.py", line 51, in _get_dep_statuses
    if not dagrun.run_id or not match(BackfillJob.ID_PREFIX + '.*', dagrun.run_id):
AttributeError: 'NoneType' object has no attribute 'run_id'
```

**What you expected to happen**:

There's no error.

**How to reproduce it**:

Follow those steps
```
airflow resetdb -y
airflow webserver -w 1 -D
```
go to the webserver address (`https://0.0.0.0:28080/` in case o breeze).
Click any DAG from the list (for example `example_bash_operator`). Go to graph view and click on any task (for example 'runme_1') and then click on "Task Instance Details" you should see the error from above.

In case of breeze just go to:
http://0.0.0.0:28080/admin/airflow/task?task_id=runme_1&dag_id=example_bash_operator&execution_date=2020-10-07T12%3A52%3A03.694478%2B00%3A00

**Comment by mik-laj** [comment]
See: https://github.com/apache/airflow/pull/8389

**Comment by turbaszek** [comment]
Thanks @mik-laj, I'm just wondering if we want to cherry-pick this to 1.10 as it's simple and may help in some cases

**Comment by mik-laj** [comment]
@turbaszek 
![image](https://user-images.githubusercontent.com/12058428/95392222-ac444900-08f8-11eb-81f8-3025cb33bb60.png)

**Comment by kaxil** [comment]
https://github.com/apache/airflow/pull/11343 -- merged
