### ISSUE TITLE
Clearing Tasks throws TypeError: can't pickle thread.lock objects

### ISSUE THREAD

**Issue by adambom** [apache/airflow#1152]
There's an issue we're seeing fairly frequently when attempting to clear a task using the UI. It doesn't happen 100% of the time, and sometimes killing and restarting all airflow processes eliminates the issue. If this happens, it's pretty much impossible to clear the task state without a hard reboot at least. Here is the stack trace we're seeing:

```
Traceback (most recent call last):
  File "/home/y/share/airflow_venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/y/share/airflow_venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/y/share/airflow_venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/y/share/airflow_venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/y/share/airflow_venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/y/share/airflow_venv/lib/python2.7/site-packages/flask_admin/base.py", line 68, in inner
    return self._run_view(f, *args, **kwargs)
  File "/home/y/share/airflow_venv/lib/python2.7/site-packages/flask_admin/base.py", line 359, in _run_view
    return fn(self, *args, **kwargs)
  File "/home/y/share/airflow_venv/lib/python2.7/site-packages/flask_login.py", line 755, in decorated_view
    return func(*args, **kwargs)
  File "/home/y/share/airflow_venv/lib/python2.7/site-packages/airflow/www/utils.py", line 103, in wrapper
    return f(*args, **kwargs)
  File "/home/y/share/airflow_venv/lib/python2.7/site-packages/airflow/www/utils.py", line 152, in wrapper
    return f(*args, **kwargs)
  File "/home/y/share/airflow_venv/lib/python2.7/site-packages/airflow/www/views.py", line 901, in clear
    include_upstream=upstream)
  File "/home/y/share/airflow_venv/lib/python2.7/site-packages/airflow/models.py", line 2345, in sub_dag
    dag = copy.deepcopy(self)
  File "/home/y/lib/python2.7/copy.py", line 174, in deepcopy
    y = copier(memo)
  File "/home/y/share/airflow_venv/lib/python2.7/site-packages/airflow/models.py", line 2331, in __deepcopy__
    setattr(result, k, copy.deepcopy(v, memo))
  File "/home/y/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/home/y/lib/python2.7/copy.py", line 230, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/home/y/lib/python2.7/copy.py", line 174, in deepcopy
    y = copier(memo)
  File "/home/y/share/airflow_venv/lib/python2.7/site-packages/airflow/models.py", line 1607, in __deepcopy__
    setattr(result, k, copy.deepcopy(v, memo))
  File "/home/y/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/home/y/lib/python2.7/copy.py", line 230, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/home/y/lib/python2.7/copy.py", line 174, in deepcopy
    y = copier(memo)
  File "/home/y/share/airflow_venv/lib/python2.7/site-packages/airflow/models.py", line 1607, in __deepcopy__
    setattr(result, k, copy.deepcopy(v, memo))
  File "/home/y/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/home/y/lib/python2.7/copy.py", line 230, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/home/y/lib/python2.7/copy.py", line 174, in deepcopy
    y = copier(memo)
  File "/home/y/share/airflow_venv/lib/python2.7/site-packages/airflow/models.py", line 1607, in __deepcopy__
    setattr(result, k, copy.deepcopy(v, memo))
  File "/home/y/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/home/y/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/y/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/home/y/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/y/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/home/y/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/y/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/home/y/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/y/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/home/y/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/y/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/home/y/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/y/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/home/y/lib/python2.7/copy.py", line 230, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/home/y/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/home/y/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/y/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/home/y/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/y/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/home/y/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/y/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/home/y/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/y/lib/python2.7/copy.py", line 182, in deepcopy
    rv = reductor(2)
TypeError: can't pickle thread.lock objects
```

**Comment by adambom** [comment]
I should add that we're using CeleryExecutor with Redis.

**Comment by adambom** [comment]
This has something to do with subdags. When I removed the subdag this issue disappeared. The two dags had different schedule intervals (hourly and daily), which may have had something to do with it.

I'll leave it open for now in case someone else runs into the same problem, but for the time being I got around this by splitting the subdag out into its own dag.

**Comment by syvineckruyk** [comment]
@adambom this seems similar to what I am seeing ... we use subdags extensively. I have yet to find the root cause. Issue happens on all recent versions i have used (1.6.2.10 currently). Often times refreshing multiple times will resolve. Worst case restart webserver.

#1091

**Comment by mistercrunch** [comment]
Looks like you have a reference to something that is not deep-copyable in your DAG... I usually use PDB and go up the stack until I find which object causes the issue

**Comment by syvineckruyk** [comment]
@mistercrunch any idea why the behavior would not be consistent ? ie. refreshing the screen solves the issue ?

**Comment by syvineckruyk** [comment]
The only "dag" reference i can see in the stack trace is to subdag. hmmm... maybe callbacks ... or the subdag operator itself ?? I'll do some tests with vanilla subdags.

```
Traceback (most recent call last):
  File "/home/airflow/.pyenv/versions/2.7.10/envs/airflow/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/airflow/.pyenv/versions/2.7.10/envs/airflow/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/airflow/.pyenv/versions/2.7.10/envs/airflow/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/airflow/.pyenv/versions/2.7.10/envs/airflow/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/airflow/.pyenv/versions/2.7.10/envs/airflow/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/airflow/.pyenv/versions/2.7.10/envs/airflow/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/airflow/.pyenv/versions/2.7.10/envs/airflow/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/airflow/.pyenv/versions/2.7.10/envs/airflow/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/airflow/.pyenv/versions/2.7.10/envs/airflow/lib/python2.7/site-packages/Flask_Admin-1.4.0-py2.7.egg/flask_admin/base.py", line 68, in inner
    return self._run_view(f, *args, **kwargs)
  File "/home/airflow/.pyenv/versions/2.7.10/envs/airflow/lib/python2.7/site-packages/Flask_Admin-1.4.0-py2.7.egg/flask_admin/base.py", line 367, in _run_view
    return fn(self, *args, **kwargs)
  File "/home/airflow/.pyenv/versions/2.7.10/envs/airflow/lib/python2.7/site-packages/Flask_Login-0.2.11-py2.7.egg/flask_login.py", line 755, in decorated_view
    return func(*args, **kwargs)
  File "/home/airflow/.pyenv/versions/2.7.10/envs/airflow/lib/python2.7/site-packages/airflow-1.6.2-py2.7.egg/airflow/www/utils.py", line 198, in view_func
    return f(*args, **kwargs)
  File "/home/airflow/.pyenv/versions/2.7.10/envs/airflow/lib/python2.7/site-packages/airflow-1.6.2-py2.7.egg/airflow/www/utils.py", line 103, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.pyenv/versions/2.7.10/envs/airflow/lib/python2.7/site-packages/airflow-1.6.2-py2.7.egg/airflow/www/views.py", line 1204, in graph
    include_downstream=False)
  File "/home/airflow/.pyenv/versions/2.7.10/envs/airflow/lib/python2.7/site-packages/airflow-1.6.2-py2.7.egg/airflow/models.py", line 2345, in sub_dag
    dag = copy.deepcopy(self)
  File "/home/airflow/.pyenv/versions/2.7.10/lib/python2.7/copy.py", line 174, in deepcopy
    y = copier(memo)
  File "/home/airflow/.pyenv/versions/2.7.10/envs/airflow/lib/python2.7/site-packages/airflow-1.6.2-py2.7.egg/airflow/models.py", line 2331, in __deepcopy__
    setattr(result, k, copy.deepcopy(v, memo))
  File "/home/airflow/.pyenv/versions/2.7.10/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/home/airflow/.pyenv/versions/2.7.10/lib/python2.7/copy.py", line 230, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/home/airflow/.pyenv/versions/2.7.10/lib/python2.7/copy.py", line 174, in deepcopy
    y = copier(memo)
  File "/home/airflow/.pyenv/versions/2.7.10/envs/airflow/lib/python2.7/site-packages/airflow-1.6.2-py2.7.egg/airflow/models.py", line 1607, in __deepcopy__
    setattr(result, k, copy.deepcopy(v, memo))
  File "/home/airflow/.pyenv/versions/2.7.10/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/home/airflow/.pyenv/versions/2.7.10/lib/python2.7/copy.py", line 230, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/home/airflow/.pyenv/versions/2.7.10/lib/python2.7/copy.py", line 174, in deepcopy
    y = copier(memo)
  File "/home/airflow/.pyenv/versions/2.7.10/envs/airflow/lib/python2.7/site-packages/airflow-1.6.2-py2.7.egg/airflow/models.py", line 1607, in __deepcopy__
    setattr(result, k, copy.deepcopy(v, memo))
  File "/home/airflow/.pyenv/versions/2.7.10/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/home/airflow/.pyenv/versions/2.7.10/lib/python2.7/copy.py", line 230, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/home/airflow/.pyenv/versions/2.7.10/lib/python2.7/copy.py", line 174, in deepcopy
    y = copier(memo)
  File "/home/airflow/.pyenv/versions/2.7.10/envs/airflow/lib/python2.7/site-packages/airflow-1.6.2-py2.7.egg/airflow/models.py", line 1607, in __deepcopy__
    setattr(result, k, copy.deepcopy(v, memo))
  File "/home/airflow/.pyenv/versions/2.7.10/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/home/airflow/.pyenv/versions/2.7.10/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/airflow/.pyenv/versions/2.7.10/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/home/airflow/.pyenv/versions/2.7.10/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/airflow/.pyenv/versions/2.7.10/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/home/airflow/.pyenv/versions/2.7.10/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/airflow/.pyenv/versions/2.7.10/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/home/airflow/.pyenv/versions/2.7.10/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/airflow/.pyenv/versions/2.7.10/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/home/airflow/.pyenv/versions/2.7.10/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/airflow/.pyenv/versions/2.7.10/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/home/airflow/.pyenv/versions/2.7.10/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/airflow/.pyenv/versions/2.7.10/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/home/airflow/.pyenv/versions/2.7.10/lib/python2.7/copy.py", line 230, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/home/airflow/.pyenv/versions/2.7.10/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/home/airflow/.pyenv/versions/2.7.10/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/airflow/.pyenv/versions/2.7.10/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/home/airflow/.pyenv/versions/2.7.10/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/airflow/.pyenv/versions/2.7.10/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/home/airflow/.pyenv/versions/2.7.10/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/airflow/.pyenv/versions/2.7.10/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/home/airflow/.pyenv/versions/2.7.10/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/airflow/.pyenv/versions/2.7.10/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/home/airflow/.pyenv/versions/2.7.10/lib/python2.7/copy.py", line 329, in _reconstruct
    y = callable(*args)
  File "/home/airflow/.pyenv/versions/2.7.10/lib/python2.7/copy_reg.py", line 93, in __newobj__
    return cls.__new__(cls, *args)
TypeError: object.__new__(thread.lock) is not safe, use thread.lock.__new__()
```

**Comment by mistercrunch** [comment]
Could be the threadpool in the `LocalExecutor` within the DagBag. We tend to use `SequentialExecutor` for subdag to avoid over subscribing worker. If a worker has 32 slots and each one uses a LocalExecutor you can end up with more threads than you signed up for...

Something that may help would be to override the `__deepcopy__` of BaseOperator and do some explicit logging on what fails there.

**Comment by muscovitebob** [comment]
We are still hitting this issue with clearing tasks on a DAG containing a SubDAG in airflow-1.10.6, in it's Cloud Composer incarnation.

**Comment by axelet** [comment]
Yeah, we are still experiencing the same issue when trying to clear a subdag within the on_retry_callback function.

**Comment by david30907d** [comment]
me too

**Comment by kaxil** [comment]
@axelet @david30907d Can one of you create a separate Github issue for it please
