### ISSUE TITLE
ERRORS when executing dags in "start-airflow"

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#11554]
**Description**

When HA Scheduler is enabled and sqlite DB is used you get "Database Locked" problem.

We should probably disable HA Scheduler always when sqlite is used. This is easily reproduced when sqlite is on and you enter Breeze. 

More info: https://apache-airflow.slack.com/archives/CCQ7EGB1P/p1602834272205500

```
hi, I’m trying to get breeze to work running dags and i’m facing some issues:
when using default SequentialExecutor I’m hitting problems where there is locking going on and this based on @Jarek Potiuk guess may be problem with HA Scheduler that simply can’t run with sqllite/seq-executor - does anyone know how to disable HA through setting or is that a default/non-changeable and it is not possible to go down to single scheduler process running?
when using LocalExecutor I’m hitting pretty odd exception with very plain DAG - single task, not much work going on that shows as following trace in scheduler log:
[2020-10-15 22:14:19,875] {scheduler_job.py:1097} INFO - Setting the following tasks to queued state:                  
<TaskInstance: example_http_operator.post_op 2020-10-08 00:00:00+00:00 [scheduled]>                            
[2020-10-15 22:14:19,888] {scheduler_job.py:1144} INFO - Sending TaskInstanceKey(dag_id='example_http_operator', task_i
d='post_op', execution_date=datetime.datetime(2020, 10, 8, 0, 0, tzinfo=Timezone('UTC')), try_number=1) to executor wit
h priority 1 and queue default                                                                                         
[2020-10-15 22:14:19,888] {base_executor.py:82} INFO - Adding to queue: ['airflow', 'tasks', 'run', 'example_http_opera
tor', 'post_op', '2020-10-08T00:00:00+00:00', '--local', '--pool', 'default_pool', '--subdir', '/files/dags/test_http_o
p.py']                                                                                                                 
[2020-10-15 22:14:19,896] {debug_executor.py:89} ERROR - Failed to execute task: 'TaskInstance' object has no attribute
'task'.                                                                                                               
Traceback (most recent call last):                                                                                     
File "/opt/airflow/airflow/executors/debug_executor.py", line 83, in _run_task                                       
job_id=ti.job_id, **params                                                                                         
File "/opt/airflow/airflow/utils/session.py", line 65, in wrapper                                                    
return func(*args, **kwargs)                                                                                       
File "/opt/airflow/airflow/models/taskinstance.py", line 1074, in _run_raw_task                                      
task = self.task                                                                                                   
AttributeError: 'TaskInstance' object has no attribute 'task'                                                          
[2020-10-15 22:14:19,900] {scheduler_job.py:1240} INFO - Executor reports execution of example_http_operator.post_op ex
ecution_date=2020-10-08 00:00:00+00:00 exited with status failed for try_number 1                                      
I noticed there was some old bug in JIRA/GitHub, but it’s meant to be closed/fixed back in 2019, so I’m not sure about origin story of that?
Does anyone know if this is a problem with latest breeze build / airflow version or if that is down to some potential setup issue?
I’m using ./breeze start-airflow --db-reset --backend postgres --python 3.6 to kick things off - all components seem to be running: scheduler, webserver, database (can log into shell), but above exception spams the log at v high frequency
```

**Comment by potiuk** [comment]
cc: @ashb

**Comment by ashb** [comment]
Just checking, this is just when more than one scheduler at the same time, not always?

**Comment by potiuk** [comment]
This happened today during the workshops when running start-airflow with breeze by one of the attendees. Not sure exactly how, I will try to reproduce it.

**Comment by potiuk** [comment]
@turbaszek, I believe we need to fix Debug Executor :)

**Comment by potiuk** [comment]
@ashb -> any quess why self.task might be missing in task instance in this case? I do not see an obvious one but maybe you will know by heart

**Comment by ashb** [comment]
Nothing obvious jumps out to me - self.task is set in various places in the code, about the only way I could see this happening is with a dynamic dag and the task not existing on the day anymore. Seems unlikely though

**Comment by potiuk** [comment]
Right. Thanks @ashb  - we'll have to take a deeper look then :)

**Comment by potiuk** [comment]
It works fine now. Closing
