### ISSUE TITLE
airflow webserver has broken dependencies?

### ISSUE THREAD

**Issue by stevenhurwitt** [apache/airflow#11567]
**Apache Airflow version**: 1.10.5

**Environment**:

- **Cloud provider or hardware configuration**: local ubuntu
- **OS** (e.g. from /etc/os-release): ubuntu 20.04
- **Kernel** (e.g. `uname -a`): linux 5.4.0-51-generic
- **Install tools**: anaconda
- **Others**: Python 3.7.9

**What happened**:

all `airflow` commands fail because of a broken dependency. this is the error message:

```
Traceback (most recent call last):
  File "/home/steven/miniconda3/envs/reliant/bin/airflow", line 22, in <module>
    from airflow.bin.cli import CLIFactory
  File "/home/steven/miniconda3/envs/reliant/lib/python3.7/site-packages/airflow/bin/cli.py", line 67, in <module>
    from airflow.www.app import (cached_app, create_app)
  File "/home/steven/miniconda3/envs/reliant/lib/python3.7/site-packages/airflow/www/app.py", line 37, in <module>
    from airflow.www.blueprints import routes
  File "/home/steven/miniconda3/envs/reliant/lib/python3.7/site-packages/airflow/www/blueprints.py", line 25, in <module>
    from airflow.www import utils as wwwutils
  File "/home/steven/miniconda3/envs/reliant/lib/python3.7/site-packages/airflow/www/utils.py", line 39, in <module>
    from flask_admin.model import filters
  File "/home/steven/miniconda3/envs/reliant/lib/python3.7/site-packages/flask_admin/model/__init__.py", line 2, in <module>
    from .base import BaseModelView
  File "/home/steven/miniconda3/envs/reliant/lib/python3.7/site-packages/flask_admin/model/base.py", line 8, in <module>
    from werkzeug import secure_filename
ImportError: cannot import name 'secure_filename' from 'werkzeug' (/home/steven/miniconda3/envs/reliant/lib/python3.7/site-packages/werkzeug/__init__.py)
```

**What you expected to happen**: run `airflow webserver` or `airflow --version`

The werkzeug package has a different location for secure_filename. should i just downgrade from werkzeug 1.0.1?

**How to reproduce it**:
```
conda create -n airflow-error-env
conda activate airflow-error-env
conda install python=3.7.9
conda install -c conda-forge airflow==1.10.5
airflow webserver
```

**Anything else we need to know**:

This is currently breaking my airflow installation. I'll try downgrading the werkzeug package

**Comment by stevenhurwitt** [comment]
nevermind, downgrading to werkzeug 0.16.1 brought me to a google-able sqlalchemy error that involved downgrading sqlalchemy as well and it works now.
