### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by tannaalok** [apache/airflow#1165]
I am getting below error when I am trying to install airflow

Command "/usr/bin/python2.7 -u -c "import setuptools, tokenize;**file**='/tmp/pip-build-xNqGCx/pandas/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-EVsFXi-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-xNqGCx/pandas/

**Comment by artwr** [comment]
Hi @tannaalok,

Could you provide the output of `pip --version`?
 If your pip version is < 8.1, I would also suggest you run `pip install --upgrade pip`.

**Comment by tannaalok** [comment]
This is the output of pip version 
[root@ip-XXX-XXX-XXX /]# /usr/local/bin/pip --version
pip 8.1.1 from /usr/local/lib/python2.7/site-packages (python 2.7)

**Comment by tannaalok** [comment]
Also I have tried a fresh install 
 python -V
Python 2.7.10

Error 
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-buil                                                                                        d-uB6FpS/pandas

I am trying to install airflow on AWS ec2 linux  instance

**Comment by artwr** [comment]
It seems it is failing at the pandas install. Usually if you go back in the log a few lines, you might be able to spot the actual error message. Feel free to paste it below, and I will see if I can spot the issue.

**Comment by tannaalok** [comment]
[root@ip- ec2-user]# python -V
Python 2.7.10
[root@ip- ec2-user]# pip -V
pip 8.1.1 from /usr/local/lib/python2.7/site-packages (python 2.7)
[root@ip- ec2-user]#pip install airflow

[root@ip-172-31-16-131 ec2-user]# pip install airflow
Collecting airflow
  Using cached airflow-1.6.2.tar.gz
Collecting alembic<0.9,>=0.8.3 (from airflow)
  Using cached alembic-0.8.5.tar.gz
Collecting chartkick<0.5,>=0.4.2 (from airflow)
  Using cached chartkick-0.4.2.tar.gz
Collecting croniter<0.4,>=0.3.8 (from airflow)
  Using cached croniter-0.3.12.tar.gz
Collecting dill<0.3,>=0.2.2 (from airflow)
  Using cached dill-0.2.5.tgz
Collecting flask<0.11,>=0.10.1 (from airflow)
  Using cached Flask-0.10.1.tar.gz
Collecting flask-admin==1.2.0 (from airflow)
  Using cached Flask-Admin-1.2.0.tar.gz
Collecting flask-cache<0.14,>=0.13.1 (from airflow)
  Using cached Flask-Cache-0.13.1.tar.gz
Collecting flask-login==0.2.11 (from airflow)
  Using cached Flask-Login-0.2.11.tar.gz
Collecting future<0.16,>=0.15.0 (from airflow)
  Using cached future-0.15.2.tar.gz
Collecting gunicorn<20.0,>=19.3.0 (from airflow)
  Using cached gunicorn-19.4.5-py2.py3-none-any.whl
Collecting jinja2<3.0,>=2.7.3 (from airflow)
  Using cached Jinja2-2.8-py2.py3-none-any.whl
Collecting markdown<3.0,>=2.5.2 (from airflow)
  Using cached Markdown-2.6.5.tar.gz
Collecting pandas<1.0.0,>=0.15.2 (from airflow)
  Using cached pandas-0.18.0.tar.gz
    Complete output from command python setup.py egg_info:
    Running from numpy source directory.
    /tmp/easy_install-0VDW3H/numpy-1.11.0rc1/setup.py:327: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      warnings.warn("Unrecognized setuptools command, proceeding with "
    /tmp/easy_install-0VDW3H/numpy-1.11.0rc1/numpy/distutils/system_info.py:1640: UserWarning:
        Atlas (http://math-atlas.sourceforge.net/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [atlas]) or by setting
        the ATLAS environment variable.
      warnings.warn(AtlasNotFoundError.**doc**)
    /tmp/easy_install-0VDW3H/numpy-1.11.0rc1/numpy/distutils/system_info.py:1649: UserWarning:
        Blas (http://www.netlib.org/blas/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [blas]) or by setting
        the BLAS environment variable.
      warnings.warn(BlasNotFoundError.**doc**)
    /tmp/easy_install-0VDW3H/numpy-1.11.0rc1/numpy/distutils/system_info.py:1652: UserWarning:
        Blas (http://www.netlib.org/blas/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [blas_src]) or by setting
        the BLAS_SRC environment variable.
      warnings.warn(BlasSrcNotFoundError.**doc**)
    /bin/sh: svnversion: command not found
    /bin/sh: svnversion: command not found
    /tmp/easy_install-0VDW3H/numpy-1.11.0rc1/numpy/distutils/system_info.py:1542: UserWarning:
        Atlas (http://math-atlas.sourceforge.net/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [atlas]) or by setting
        the ATLAS environment variable.
      warnings.warn(AtlasNotFoundError.**doc**)
    /tmp/easy_install-0VDW3H/numpy-1.11.0rc1/numpy/distutils/system_info.py:1553: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      warnings.warn(LapackNotFoundError.**doc**)
    /tmp/easy_install-0VDW3H/numpy-1.11.0rc1/numpy/distutils/system_info.py:1556: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      warnings.warn(LapackSrcNotFoundError.**doc**)
    /usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'define_macros'
      warnings.warn(msg)
    non-existing path in 'numpy/distutils': 'site.cfg'
    Could not locate executable gfortran
    Could not locate executable f95
    Could not locate executable ifort
    Could not locate executable ifc
    Could not locate executable lf95
    Could not locate executable pgfortran
    Could not locate executable f90
    Could not locate executable f77
    Could not locate executable fort
    Could not locate executable efort
    Could not locate executable efc
    Could not locate executable g77
    Could not locate executable g95
    Could not locate executable pathf95
    don't know how to compile Fortran code on platform 'posix'
    sh: gcc: command not found
    sh: gcc: command not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-HD73tS/pandas/setup.py", line 604, in <module>
        **setuptools_kwargs)
      File "/usr/lib64/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 265, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 310, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 799, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 1049, in best_match
        return self.obtain(req, installer)
      File "/usr/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 1061, in obtain
        return installer(requirement)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 377, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 642, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 672, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 857, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1085, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1071, in run_setup
        run_setup(setup_script, args)
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 240, in run_setup
        raise
      File "/usr/lib64/python2.7/contextlib.py", line 35, in **exit**
        self.gen.throw(type, value, traceback)
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 193, in setup_context
        yield
      File "/usr/lib64/python2.7/contextlib.py", line 35, in **exit**
        self.gen.throw(type, value, traceback)
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 164, in save_modules
        saved_exc.resume()
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 139, in resume
        compat.reraise(type, exc, self._tb)
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 152, in save_modules
        yield saved
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 193, in setup_context
        yield
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 237, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 267, in run
        return func()
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 236, in runner
        _execfile(setup_script, ns)
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 46, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-0VDW3H/numpy-1.11.0rc1/setup.py", line 386, in <module>

```
  File "/tmp/easy_install-0VDW3H/numpy-1.11.0rc1/setup.py", line 378, in setup_package
    lib_depends = []
  File "/tmp/easy_install-0VDW3H/numpy-1.11.0rc1/numpy/distutils/core.py", line 169, in setup
  File "/usr/lib64/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/bdist_egg.py", line 152, in run
    self.run_command("egg_info")
  File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/tmp/easy_install-0VDW3H/numpy-1.11.0rc1/numpy/distutils/command/egg_info.py", line 18, in run
  File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/tmp/easy_install-0VDW3H/numpy-1.11.0rc1/numpy/distutils/command/build_src.py", line 147, in run
  File "/tmp/easy_install-0VDW3H/numpy-1.11.0rc1/numpy/distutils/command/build_src.py", line 158, in build_sources
  File "/tmp/easy_install-0VDW3H/numpy-1.11.0rc1/numpy/distutils/command/build_src.py", line 293, in build_library_sources
  File "/tmp/easy_install-0VDW3H/numpy-1.11.0rc1/numpy/distutils/command/build_src.py", line 376, in generate_sources
  File "numpy/core/setup.py", line 654, in get_mathlib_info

RuntimeError: Broken toolchain: cannot link a simple C program

----------------------------------------
```

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-HD73tS/pandas/

**Comment by artwr** [comment]
You are missing a compiler. `sudo apt-get install build-essentials` should help get you gcc.

**Comment by artwr** [comment]
You might also need to install the `g77` and `gfortran` packages.

**Comment by tannaalok** [comment]
Thank you that helped a lot. 
Now when I am trying to run this command sudo /usr/local/bin/airflow webserver -p 8080 I am getting below error . I am trying to install this on a redhat AWS Ec2 linux server. 

[root@ip- ec2-user]# sudo /usr/local/bin/airflow webserver -p 8080
[2016-03-17 23:28:25,265] {**init**.py:36} INFO - Using executor SequentialExecu                                                                                        tor

---

 ____    |**( )_______**  **/**  /________      __
____  /| |_  /__  **_/_  /_ __  /_  __ _ | /| / /
___  ___ |  / _  /   _  **/ _  / / /_/ /_ |/ |/ /
 _/_/  |_/_/  /_/    /_/    /_/  \****/____/|__/

[2016-03-17 23:28:25,424] {models.py:124} INFO - Filling up the DagBag from /roo                                                                                        t/airflow/dags
[2016-03-17 23:28:25,424] {models.py:197} INFO - Importing /usr/local/lib/python                                                                                        2.7/site-packages/airflow/example_dags/example_branch_operator.py
[2016-03-17 23:28:25,426] {models.py:284} INFO - Loaded DAG <DAG: example_branch                                                                                        _operator>
[2016-03-17 23:28:25,426] {models.py:197} INFO - Importing /usr/local/lib/python                                                                                        2.7/site-packages/airflow/example_dags/example_python_operator.py
[2016-03-17 23:28:25,427] {models.py:284} INFO - Loaded DAG <DAG: example_python                                                                                        _operator>
[2016-03-17 23:28:25,427] {models.py:197} INFO - Importing /usr/local/lib/python                                                                                        2.7/site-packages/airflow/example_dags/example_short_circuit_operator.py
[2016-03-17 23:28:25,428] {models.py:284} INFO - Loaded DAG <DAG: example_short_                                                                                        circuit_operator>
[2016-03-17 23:28:25,428] {models.py:197} INFO - Importing /usr/local/lib/python                                                                                        2.7/site-packages/airflow/example_dags/example_xcom.py
[2016-03-17 23:28:25,429] {models.py:284} INFO - Loaded DAG <DAG: example_xcom>
[2016-03-17 23:28:25,429] {models.py:197} INFO - Importing /usr/local/lib/python                                                                                        2.7/site-packages/airflow/example_dags/example_http_operator.py
[2016-03-17 23:28:25,430] {models.py:284} INFO - Loaded DAG <DAG: example_http_o                                                                                        perator>
[2016-03-17 23:28:25,430] {models.py:197} INFO - Importing /usr/local/lib/python                                                                                        2.7/site-packages/airflow/example_dags/example_bash_operator.py
[2016-03-17 23:28:25,431] {models.py:284} INFO - Loaded DAG <DAG: example_bash_o                                                                                        perator>
[2016-03-17 23:28:25,431] {models.py:197} INFO - Importing /usr/local/lib/python                                                                                        2.7/site-packages/airflow/example_dags/tutorial.py
[2016-03-17 23:28:25,431] {models.py:284} INFO - Loaded DAG <DAG: tutorial>
Running the Gunicorn server with 4 syncworkers on host 0.0.0.0 and port 8080...
Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 15, in <module>
    args.func(args)
  File "/usr/local/lib/python2.7/site-packages/airflow/bin/cli.py", line 329, in                                                                                         webserver
    'airflow.www.app:cached_app()'])
  File "/usr/lib64/python2.7/subprocess.py", line 710, in **init**
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
[root@ip- ec2-user]#

**Comment by artwr** [comment]
If I remember correctly, this final error is related to an issue with one of the executables not being on the PATH.
I see /usr/lib64 as well as /usr/lib being used. Maybe that could be the issue?

**Comment by tannaalok** [comment]
Thank you artwr , finally got it working .
