### ISSUE TITLE
OSError: [Errno 12] Cannot allocate memory

### ISSUE THREAD

**Issue by dll02** [apache/airflow#11711]
**Apache Airflow version**:

1.10.12
**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): no

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):  centos 7
- **Kernel** (e.g. `uname -a`):3.10.0-862.el7.x86_64
- **Install tools**: python3 install airflow
- **Others**:

**What happened**:

OSError: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/data//.local/bin/airflow", line 37, in <module>
    args.func(args)
  File "/data//.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 76, in wrapper
    return f(*args, **kwargs)
  File "/data//.local/lib/python3.7/site-packages/airflow/bin/cli.py", line 579, in run
    _run(args, dag, ti)
  File "/data//.local/lib/python3.7/site-packages/airflow/bin/cli.py", line 475, in _run
    run_job.run()
  File "/data//.local/lib/python3.7/site-packages/airflow/jobs/base_job.py", line 218, in run
    self._execute()
  File "/data//.local/lib/python3.7/site-packages/airflow/jobs/local_task_job.py", line 94, in _execute
    self.task_runner.start()
  File "/data//.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 43, in start
    self.process = self._start_by_fork()
  File "/data//.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 52, in _start_by_fork
    pid = os.fork()
OSError: [Errno 12] Cannot allocate memory

**What you expected to happen**:

It may don't have enough swap.so 
I try to fix like this page:https://www.digitalocean.com/community/tutorials/how-to-add-swap-on-centos-7 
add swap to 4g;
but it don't work . this issue always appear .

**Comment by ashb** [comment]
This is not a problem in airflow -- this is a system call that is failing, so it is something to do with your environment. It could also be some kind of limit on the number of process etc.

Either way, not any Airflow bug I'm afraid.

**Comment by rahulsinha07** [comment]
still facing the issue ..any solution?

**Comment by potiuk** [comment]
> still facing the issue ..any solution?

get more memory ?
