### ISSUE TITLE
File "<frozen importlib._bootstrap>", line 682, in _load_unlocked

### ISSUE THREAD

**Issue by tooptoop4** [apache/airflow#11716]
airflow 1.10.12, mysql 5.7 metastore, rbac, no serialized dags

webserver log shows

[2020-10-21 12:17:47,419] {dagbag.py:259} ERROR - Failed to import: /home/user/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/user/venv/lib/python3.7/site-packages/airflow/models/dagbag.py", line 256, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/lib64/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 682, in _load_unlocked
KeyError: 'unusual_prefix_de83ba53e22052571ad1c3d6f591d46a775b2a8c_mydag'

**Comment by michael-kotliar** [comment]
Have similar issue when trying to trigger several DAG-runs of the same DAG in a very short period of time.

**Comment by eladkal** [comment]
`imp.load_source` was removed from master in https://github.com/apache/airflow/pull/7099
@kaxil should the PR cherry picked to 1.10.13?

**Comment by kaxil** [comment]
The error itself won't be fixed by that change @eladkal .

Do we have steps to reproduce this error?

**Comment by ashb** [comment]
Closing until someone can give us concrete reproduction steps.
