### ISSUE TITLE
Airflow 2.0.0alpha2 - Webserver Fails because of werkzeug

### ISSUE THREAD

**Issue by kaxil** [apache/airflow#11871]
With alpha2 without using the constraints https://github.com/apache/airflow/blob/constraints-master/constraints-3.6.txt , when accessing Webserver it fails with

```
Something bad has happened.
Please consider letting us know by creating a bug report using GitHub.

Python version: 3.6.12
Airflow version: 2.0.0a2
Node: 599861bd62ac
-------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1970, in finalize_request
    response = self.process_response(response)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2269, in process_response
    self.session_interface.save_session(self, ctx.session, response)
  File "/usr/local/lib/python3.6/site-packages/flask/sessions.py", line 387, in save_session
    samesite=samesite,
  File "/usr/local/lib/python3.6/site-packages/werkzeug/wrappers/base_response.py", line 479, in set_cookie
    samesite=samesite,
  File "/usr/local/lib/python3.6/site-packages/werkzeug/http.py", line 1217, in dump_cookie
    raise ValueError("SameSite must be 'Strict', 'Lax', or 'None'.")
ValueError: SameSite must be 'Strict', 'Lax', or 'None'.
```

**Comment by kaxil** [comment]
This is caused by https://github.com/apache/airflow/pull/11610

**Comment by kurtqq** [comment]
@kaxil @potiuk i still see this error when opening the webserver using  breeze with master if I select SQLite as database.
I don't see this for MySQL / PostgreSql
