### ISSUE TITLE
can't clear task SubDagOperator with executor=KubernetesExecutor()

### ISSUE THREAD

**Issue by edenGlu** [apache/airflow#11882]
Hey, 
I use 
Apache Airflow version: 1.10.12
Kubernetes version: v1.17.0
executor: KubernetesExecutor

I create a task - SubDagOperator with executor=KubernetesExecutor()
I run this task and it work, but I can't clear the task , not from the UI and not from the command .
the error that I get is:
```
    'Pickling an AuthenticationString object is '
TypeError: Pickling an AuthenticationString object is disallowed for security reasons

```
any ideas?

**Comment by tylermichael** [comment]
We are also seeing this. Here is the full stack trace I get when I hit clear. We are running version 1.10.12

```
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/airflow/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/airflow/.local/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/airflow/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/airflow/.local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/airflow/.local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/airflow/.local/lib/python3.6/site-packages/flask_admin/base.py", line 69, in inner
    return self._run_view(f, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/flask_admin/base.py", line 368, in _run_view
    return fn(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/flask_login/utils.py", line 258, in decorated_view
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/www/utils.py", line 290, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/www/utils.py", line 337, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/www/views.py", line 1341, in clear
    include_upstream=upstream)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 1244, in sub_dag
    for t in regex_match + also_include}
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 1244, in <dictcomp>
    for t in regex_match + also_include}
  File "/usr/local/lib/python3.6/copy.py", line 161, in deepcopy
    y = copier(memo)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 690, in __deepcopy__
    setattr(result, k, copy.deepcopy(v, memo))
  File "/usr/local/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/local/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/local/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/local/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/local/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/lib/python3.6/copy.py", line 169, in deepcopy
    rv = reductor(4)
  File "/usr/local/lib/python3.6/multiprocessing/process.py", line 290, in __reduce__
    'Pickling an AuthenticationString object is '
TypeError: Pickling an AuthenticationString object is disallowed for security reasons
```

**Comment by tylermichael** [comment]
I found this error in the logs for my subdag task. I'm not sure if they are linked but I thought I'd put it here anyway.

```
ERROR - can't compare offset-naive and offset-aware datetimes
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/subdag_operator.py", line 102, in execute
    executor=self.executor)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 1432, in run
    job.run()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/jobs/base_job.py", line 218, in run
    self._execute()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/db.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/jobs/backfill_job.py", line 787, in _execute
    session=session)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/db.py", line 70, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/jobs/backfill_job.py", line 703, in _execute_for_run_dates
    dag_run = self._get_dag_run(next_run_date, session=session)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/db.py", line 70, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/jobs/backfill_job.py", line 322, in _get_dag_run
    run.verify_integrity(session=session)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/db.py", line 70, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagrun.py", line 394, in verify_integrity
    if task.start_date > self.execution_date and not self.is_backfill:
TypeError: can't compare offset-naive and offset-aware datetimes
```

**Comment by eladkal** [comment]
This issue is reported against old version of Airflow.
Please check if the issue is still present in latest version.

**Comment by tylermichael** [comment]
We upgraded to the latest version a while ago and migrated to task groups. Haven't had any issues since then.

**Comment by michaelosthege** [comment]
We're seeing this with Airflow 2.2.5 on Ubuntu 22.04 running with the CeleryExecutor.
Also [this StackOverflow post ](https://stackoverflow.com/questions/67735179/airflow-2-0-celery-dask) reported it for Airflow >2.0 with Celery.

For us it happens in a Celery worker that's trying to run a task involving `pygmo` (https://esa.github.io/pygmo2/) which uses a lot of multiprocessing.

Our worker has `PYTHONOPTIMIZE=1` and `OMP_NUM_THREADS=1` set but otherwise it's pretty standard I would say.

Relevant part of the log is here:

<details><summary>Worker log</summary>

```
[2022-04-28 10:49:58,097] {logging_mixin.py:109} INFO - Creating archipelago with 4 islands. May take some time...
[2022-04-28 10:49:58,098] {warnings.py:109} WARNING - /opt/conda/lib/python3.9/site-packages/joblib/parallel.py:735: UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
  n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,
[2022-04-28 10:49:58,098] {logging_mixin.py:109} WARNING - [Parallel(n_jobs=4)]: Using backend SequentialBackend with 1 concurrent workers.
[2022-04-28 10:51:35,329] {logging_mixin.py:109} WARNING - [Parallel(n_jobs=4)]: Done   4 out of   4 | elapsed:  1.6min finished
[2022-04-28 10:51:35,348] {taskinstance.py:1774} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/opt/conda/lib/python3.9/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/usr/local/airflow/dags/flow.py", line 95, in _run
    result = self.callable(context=context, **kwargs)
  File "/usr/local/airflow/dags/flow.py", line 43, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/airflow/dags/dag_pyFOOMB_ParamEst.py", line 48, in pipeline_call
    result = fun(wd=data, **callable_kwargs)
  File "/repos/pyfoomb_paramest/pipeline.py", line 155, in estimate_parameters
    estimates, est_info = caretaker.estimate_parallel(
  File "/opt/conda/lib/python3.9/site-packages/pyfoomb/caretaker.py", line 634, in estimate_parallel
    archipelago = ArchipelagoHelpers.create_archipelago(
  File "/opt/conda/lib/python3.9/site-packages/pyfoomb/generalized_islands.py", line 522, in create_archipelago
    _island = pygmo.island(algo=_algo, pop=_pop, udi=pygmo.mp_island())
  File "/opt/conda/lib/python3.9/site-packages/pygmo/_py_islands.py", line 119, in __init__
    self._init(use_pool)
  File "/opt/conda/lib/python3.9/site-packages/pygmo/_py_islands.py", line 130, in _init
    mp_island.init_pool()
  File "/opt/conda/lib/python3.9/site-packages/pygmo/_py_islands.py", line 338, in init_pool
    mp_island._init_pool_impl(processes)
  File "/opt/conda/lib/python3.9/site-packages/pygmo/_py_islands.py", line 315, in _init_pool_impl
    mp_island._pool, mp_island._pool_size = _make_pool(processes)
  File "/opt/conda/lib/python3.9/site-packages/pygmo/_mp_utils.py", line 62, in _make_pool
    pool = mp_ctx.Pool(processes=processes)
  File "/opt/conda/lib/python3.9/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/opt/conda/lib/python3.9/multiprocessing/pool.py", line 212, in __init__
    self._repopulate_pool()
  File "/opt/conda/lib/python3.9/multiprocessing/pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/opt/conda/lib/python3.9/multiprocessing/pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "/opt/conda/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/opt/conda/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/opt/conda/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/opt/conda/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/opt/conda/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 46, in _launch
    reduction.dump(prep_data, fp)
  File "/opt/conda/lib/python3.9/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "/opt/conda/lib/python3.9/site-packages/billiard/process.py", line 365, in __reduce__
    raise TypeError(
TypeError: Pickling an AuthenticationString object is disallowed for security reasons
```

</details>

Any ideas?

**Comment by michaelosthege** [comment]
> > Any ideas?
> Switch to TaskGroup. SubDag is deprecated and it's unlikely that issues related to it will be investigated.

I should have be clearer: We're not using the SubDagOperator, just the PythonOperator.

**Comment by Nihhaar** [comment]
@michaelosthege I think I made it work by setting EXECUTE_TASKS_NEW_PYTHON_INTERPRETER in airflow.cfg. I don't know if its the solution here.
