### ISSUE TITLE
[QUARANTINE]  test_serve_logs test is failing randomly on MySQL

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#11962]
The test_serve_logs fails randomly with database reset

Example here:  https://github.com/apache/airflow/pull/11948/checks?check_run_id=1329323444#step:6:1047

```

[2020-10-29 22:44:48,491] {base.py:706} ERROR - Exception during reset or similar
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 697, in _finalize_fairy
    fairy._reset(pool)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 893, in _reset
    pool._dialect.do_rollback(self)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/dialects/mysql/base.py", line 2475, in do_rollback
    dbapi_connection.rollback()
_mysql_exceptions.OperationalError: (2013, 'Lost connection to MySQL server during query')
--------------------------- Captured stdout teardown ---------------------------
Starting flask
 * Serving Flask app "airflow.utils.serve_logs" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
[2020-10-29 22:44:49,109] {_internal.py:113} INFO -  * Running on http://0.0.0.0:8793/ (Press CTRL+C to quit)
=============================== warnings summary ===============================
/usr/local/lib/python3.6/site-packages/_pytest/junitxml.py:446
  /usr/local/lib/python3.6/site-packages/_pytest/junitxml.py:446: PytestDeprecationWarning: The 'junit_family' default value will change to 'xunit2' in pytest 6.0. See:
    https://docs.pytest.org/en/stable/deprecations.html#junit-family-default-value-change-to-xunit2
  for more information.

```

**Comment by potiuk** [comment]
[error.txt](https://github.com/apache/airflow/files/5463820/error.txt)

**Comment by eladkal** [comment]
@potiuk the quarantine was removed in https://github.com/apache/airflow/pull/16754
can we close the issue?

**Comment by potiuk** [comment]
Yep
