### ISSUE TITLE
Problem with Jinja Template in EmailOperator

### ISSUE THREAD

**Issue by r39132** [apache/airflow#121]
The sample code below is inspired by @artwr solution in #112 

```
from airflow import DAG
from airflow.operators import PythonOperator, PostgresOperator, BashOperator, EmailOperator
from datetime import date, datetime, time, timedelta
from pprint import pprint

import base64
import boto.sqs
import boto.sns
import json
import logging
import psycopg2
import sys
import time

from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

default_args = {
    'owner': 'airflow',
    'depends_on_past': False,
    'start_date': datetime(2015, 6, 30),
    'email': ['airflow@airflow.com'],
    'email_on_failure': True,
    'email_on_retry': True,
    'retries': 3,
    'retry_interval': timedelta(seconds=5)
}
dag = DAG('test_email', default_args=default_args)

def foo(end_date):
    print "got here!"

params = {
    'foo': foo
}


send_email_notification_flow_successful = EmailOperator(
    task_id='send_email_notification_flow_successful',
    to="sanand@agari.com",
    subject='custom email from airflow',
    html_content="{{ params['foo'](execution_date) }}",
    dag=dag)
```

Unfortunately, it does not work with jinja. 

```
Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 4, in <module>
    __import__('pkg_resources').run_script('airflow==1.1.1', 'airflow')
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1652, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/site-packages/airflow-1.1.1-py2.7.egg/EGG-INFO/scripts/airflow", line 10, in <module>
    args.func(args)
  File "/usr/local/lib/python2.7/site-packages/airflow-1.1.1-py2.7.egg/airflow/bin/cli.py", line 127, in run
    job_id=args.job_id,
  File "/usr/local/lib/python2.7/site-packages/airflow-1.1.1-py2.7.egg/airflow/models.py", line 825, in run
    raise e
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'foo'
```

**Comment by mistercrunch** [comment]
You need to pass your params dict to either the DAG or the task constructor. As in:

```
dag = DAG('test_email', default_args=default_args, params=params)
```

or in

```
send_email_notification_flow_successful = EmailOperator(
    task_id='send_email_notification_flow_successful',
    to="sanand@agari.com",
    subject='custom email from airflow',
    html_content="{{ params['foo'](execution_date) }}",
    params=params,
    dag=dag)
```

Note that the DAG level params get passed to all tasks, and that when keys are common task level params take precedence as over the DAG level params.

**Comment by r39132** [comment]
Cool. Thanks.
-s
