### ISSUE TITLE
2.0.0a2 webserver fails when connection "extra" field is None (NULL in DB)

### ISSUE THREAD

**Issue by XD-DENG** [apache/airflow#12148]
This issue can be reproduced by clicking "Edit" any connection whose `extra` is `NULL` in DB, for example, "airflow_db", or "databricks_default"

I have already found the reason, will raise a PR shortly.

1. How to Reproduce

![Airflow](https://user-images.githubusercontent.com/11539188/98437154-61c51080-20e0-11eb-9e59-a9a628fa1f41.png)

2. Error

```
Python version: 3.6.10
Airflow version: 2.0.0a2
Node: a1c5c0c0026a
-------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/flask_appbuilder/security/decorators.py", line 109, in wraps
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_appbuilder/views.py", line 602, in edit
    widgets = self._edit(pk)
  File "/usr/local/lib/python3.6/site-packages/flask_appbuilder/baseviews.py", line 1228, in _edit
    self.prefill_form(form, pk)
  File "/usr/local/lib/python3.6/site-packages/airflow/www/views.py", line 2546, in prefill_form
    extra_dictionary = json.loads(form.data.get('extra', '{}'))
  File "/usr/local/lib/python3.6/json/__init__.py", line 348, in loads
    'not {!r}'.format(s.__class__.__name__))
TypeError: the JSON object must be str, bytes or bytearray, not 'NoneType'
```

**Apache Airflow version**:

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know**:

**Comment by potiuk** [comment]
Cool!
