### ISSUE TITLE
Looks like a regression to slack operator in 1.7.0rc1

### ISSUE THREAD

**Issue by syvineckruyk** [apache/airflow#1215]
Looks like it was introduced by PR. 
#792

CC: @abridgett 

Traceback (most recent call last):
  File "/home/airflow/.pyenv/versions/airflow/bin/airflow", line 4, in <module>
    **import**('pkg_resources').run_script('airflow==1.6.2', 'airflow')
  File "/home/airflow/.pyenv/versions/airflow/lib/python2.7/site-packages/pkg_resources/**init**.py", line 726, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/airflow/.pyenv/versions/airflow/lib/python2.7/site-packages/pkg_resources/**init**.py", line 1484, in run_script
    exec(code, namespace, namespace)
  File "/home/airflow/.pyenv/versions/2.7.10/envs/airflow/lib/python2.7/site-packages/airflow-1.6.2-py2.7.egg/EGG-INFO/scripts/airflow", line 15, in <module>
    args.func(args)
  File "/home/airflow/.pyenv/versions/airflow/lib/python2.7/site-packages/airflow-1.6.2-py2.7.egg/airflow/bin/cli.py", line 203, in run
    pool=args.pool,
  File "/home/airflow/.pyenv/versions/airflow/lib/python2.7/site-packages/airflow-1.6.2-py2.7.egg/airflow/models.py", line 1067, in run
    result = task_copy.execute(context=context)
  File "/home/airflow/.pyenv/versions/2.7.10/envs/airflow/lib/python2.7/site-packages/airflow-1.6.2-py2.7.egg/airflow/operators/slack_operator.py", line 52, in execute
    rc = json.loads(sc.api_call(self.method, **self.api_params).decode('utf-8'))
AttributeError: 'dict' object has no attribute 'decode'

**Comment by abridgett** [comment]
It looks like the slackclient's API changed in v1.0:
https://github.com/slackhq/python-slackclient/blob/master/CHANGELOG.md

So using v0.18.0 should work for now, alternatively I'm just prepping a little patch.

**Comment by syvineckruyk** [comment]
:+1:  Awesome ... @abridgett apologies for not catching the the slack client change in airflow.

**Comment by abridgett** [comment]
No worries at all! Never a problem to ask :-)

**Comment by bolkedebruin** [comment]
@mistercrunch was this imported to 1.7.0?
