### ISSUE TITLE
Solved Issues for trouble with SSH Operator

### ISSUE THREAD

**Issue by ekhtiar** [apache/airflow#1239]
Before the Easter weekend, I posted the following issue on google groups with using the SSH Operator:

Hey guys, I am trying to get a simple SSH task to run using SSHExecuteOperator, and I instantiate it with the following:

```
sshHook = SSHHook()

test_ssh= SSHExecuteOperator(task_id="test_ssh", ssh_hook = sshHook,
                             bash_command = "ls",
                             dag=dag)
```

in my connection, ssh_default is set with the correct ip, port, and password.
However I get the following error:

[2016-03-23 16:04:52,792] {models.py:974} INFO - Executing <Task(SSHExecuteOperator): get_data> on 2016-03-22 00:00:00
[2016-03-23 16:04:52,804] {models.py:1041} ERROR - execv() arg 2 must contain only strings
Traceback (most recent call last):
File "/usr/local/lib/python2.7/site-packages/airflow/models.py", line 1000, in run
result = task_copy.execute(context=context)
File "/usr/local/lib/python2.7/site-packages/airflow/operators/ssh_execute_operator.py", line 109, in execute
self.task_id) as remote_file_path:
File "/usr/local/lib/python2.7/site-packages/airflow/operators/sshexecuteoperator.py", line 42, in __enter
stderr=STDOUT)
File "/usr/local/lib/python2.7/site-packages/airflow/hooks/ssh_hook.py", line 102, in Popen
return subprocess.Popen(prefixed_cmd, **kwargs)
File "/usr/local/lib/python2.7/subprocess.py", line 709, in init
errread, errwrite)
File "/usr/local/lib/python2.7/subprocess.py", line 1326, in _execute_child
raise child_exception
TypeError: execv() arg 2 must contain only strings
[2016-03-23 16:04:52,810] {models.py:1077} ERROR - execv() arg 2 must contain only strings
Can someone help, and show me the correct way to do a simple SSH command using the SSHExecuteOperator

I solved it within a few hours of posting it, but was too caught up to post the fix. And also I am not sure if this is something I am only facing, or if this is something for everyone.

For me, the issue was with SSH Hook. In the _prepare_command method I just needed to convert the port and the key_file as string. After changing my code the following way the SSH Operator worked:

I would also like to point out that at first I tried using this with a password. However, the password stored in my database wasn't being passed to the SSH Hook.

```
   def _prepare_command(self, cmd):
        connection_cmd = ["ssh", self._host_ref(), "-o", "ControlMaster=no"]
        if self.sshpass:
            connection_cmd = ["sshpass", "-e"] + connection_cmd
        else:
            connection_cmd += ["-o", "BatchMode=yes"] # no password prompts

        if self.conn.port:
            connection_cmd += ["-p", str(self.conn.port)]

        if self.connect_timeout:
            connection_cmd += ["-o", "ConnectionTimeout={}".format(self.connect_timeout)]

        if self.no_host_key_check:
            connection_cmd += ["-o", "UserKnownHostsFile=/dev/null",
                               "-o", "StrictHostKeyChecking=no"]

        if self.key_file:
            connection_cmd += ["-i", str(self.key_file)]

        if self.tty:
            connection_cmd += ["-t"]

       connection_cmd += cmd
            logging.debug("SSH cmd: {} ".format(connection_cmd))
            print ("SSH cmd: {} ".format(connection_cmd))
            return connection_cmd

```
# Environment
- Version of Airflow: 1.6.2
- Operating System: Centos 6
- Python Version: 2.7.6

**Comment by ekhtiar** [comment]
Update: I upgraded my airflow version from 1.6.2 to 1.7 as suggested by @bolkedebruin up front at work, and that resolved the issue without any modification to ssh_hook.py
