### ISSUE TITLE
ImportError: cannot import name '_Union' from 'typing' (/usr/lib/python3.9/typing.py)

### ISSUE THREAD

**Issue by Zat42** [apache/airflow#12877]
**Apache Airflow version**: 1.10.3

**Environment**:

- **OS** (e.g. from /etc/os-release): Arch Linux
- **Kernel** (e.g. `uname -a`): Linux 5.9.11-arch2-1 #1 SMP PREEMPT Sat, 28 Nov 2020 02:07:22 +0000 x86_64 GNU/Linux
- **Install tools**: pip 2.3.1 (with  _--use-deprecated legacy-resolver_)
- **Others**: python 3.9

**What happened**:
```
(env) ➜  project-airflow git:(feature-implementation) ✗ ./env/bin/airflow webserver
Traceback (most recent call last):
  File "/home/user/dev/project-airflow/./env/bin/airflow", line 26, in <module>
    from airflow.bin.cli import CLIFactory
  File "/home/user/dev/project-airflow/env/lib/python3.9/site-packages/airflow/bin/cli.py", line 95, in <module>
    api_module = import_module(conf.get('cli', 'api_client'))  # type: Any
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/user/dev/project-airflow/env/lib/python3.9/site-packages/airflow/api/client/local_client.py", line 24, in <module>
    from airflow.api.common.experimental import delete_dag
  File "/home/user/dev/project-airflow/env/lib/python3.9/site-packages/airflow/api/common/experimental/delete_dag.py", line 26, in <module>
    from airflow.models.serialized_dag import SerializedDagModel
  File "/home/user/dev/project-airflow/env/lib/python3.9/site-packages/airflow/models/serialized_dag.py", line 35, in <module>
    from airflow.serialization.serialized_objects import SerializedDAG
  File "/home/user/dev/project-airflow/env/lib/python3.9/site-packages/airflow/serialization/serialized_objects.py", line 28, in <module>
    import cattr
  File "/home/user/dev/project-airflow/env/lib/python3.9/site-packages/cattr/__init__.py", line 2, in <module>
    from .converters import Converter, UnstructureStrategy
  File "/home/user/dev/project-airflow/env/lib/python3.9/site-packages/cattr/converters.py", line 15, in <module>
    from ._compat import (
  File "/home/user/dev/project-airflow/env/lib/python3.9/site-packages/cattr/_compat.py", line 87, in <module>
    from typing import _Union
ImportError: cannot import name '_Union' from 'typing' (/usr/lib/python3.9/typing.py)
```
**How to reproduce it**:

Try launch airflow webserver with python **3.9**

**Anything else we need to know**:

--

**Comment by tirkarthi** [comment]
This seems to have been fixed : https://github.com/Tinche/cattrs/issues/100
