### ISSUE TITLE
running task fails with `sudo: a password is required`

### ISSUE THREAD

**Issue by dstandish** [apache/airflow#12997]
**Apache Airflow version**: 2.0.0rc1

**Environment**:

- **Cloud provider or hardware configuration**: mac
- **OS** (e.g. from /etc/os-release): macOS catalina
- **Kernel** (e.g. `uname -a`): Darwin TFGELSOS3516375 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64 i386 MacBookPro16,1 Darwin
- **Install tools**: pip
- **Others**: SequentialExecutor / sqlite

**What happened**:

Let some test dags run for a while in the background, seemed to be running fine, then got this error.

**What you expected to happen**:

no error

**How to reproduce it**:

Not sure.  Just let it run for a while using mssql operator and odbc hook.  Not sure why it is calling "sudo"

**Other note**

After letting scheduler run for 2-3 more hours, error appeared 2 more times.

**Log**

```
[2020-12-10 11:50:08,693] {sequential_executor.py:59} INFO - Executing command: ['airflow', 'tasks', 'run', 'test_dag', 'mssqltask', '2020-12-10T19:45:00+00:00', '--local', '--pool', 'default_pool', '--subdir', '/Users/dstandish/code/abctest/dags/testing.py']
[2020-12-10 11:50:09,600] {dagbag.py:440} INFO - Filling up the DagBag from /Users/dstandish/code/abctest/dags/testing.py
Running <TaskInstance: test_dag.mssqltask 2020-12-10T19:45:00+00:00 [queued]> on host TFGELSOS3516375
sudo: a password is required
Traceback (most recent call last):
  File "/Users/dstandish/.virtualenvs/abctest/lib/python3.7/site-packages/airflow/utils/process_utils.py", line 66, in signal_procs
    os.killpg(pgid, sig)
PermissionError: [Errno 1] Operation not permitted

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dstandish/.virtualenvs/abctest/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/Users/dstandish/.virtualenvs/abctest/lib/python3.7/site-packages/airflow/__main__.py", line 40, in main
    args.func(args)
  File "/Users/dstandish/.virtualenvs/abctest/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/Users/dstandish/.virtualenvs/abctest/lib/python3.7/site-packages/airflow/utils/cli.py", line 89, in wrapper
    return f(*args, **kwargs)
  File "/Users/dstandish/.virtualenvs/abctest/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 229, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/Users/dstandish/.virtualenvs/abctest/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 64, in _run_task_by_selected_method
    _run_task_by_local_task_job(args, ti)
  File "/Users/dstandish/.virtualenvs/abctest/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 119, in _run_task_by_local_task_job
    run_job.run()
  File "/Users/dstandish/.virtualenvs/abctest/lib/python3.7/site-packages/airflow/jobs/base_job.py", line 237, in run
    self._execute()
  File "/Users/dstandish/.virtualenvs/abctest/lib/python3.7/site-packages/airflow/jobs/local_task_job.py", line 121, in _execute
    self.heartbeat()
  File "/Users/dstandish/.virtualenvs/abctest/lib/python3.7/site-packages/airflow/jobs/base_job.py", line 218, in heartbeat
    self.heartbeat_callback(session=session)
  File "/Users/dstandish/.virtualenvs/abctest/lib/python3.7/site-packages/airflow/utils/session.py", line 62, in wrapper
    return func(*args, **kwargs)
  File "/Users/dstandish/.virtualenvs/abctest/lib/python3.7/site-packages/airflow/jobs/local_task_job.py", line 178, in heartbeat_callback
    self.task_runner.terminate()
  File "/Users/dstandish/.virtualenvs/abctest/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 113, in terminate
    rcs = reap_process_group(self.process.pid, self.log)
  File "/Users/dstandish/.virtualenvs/abctest/lib/python3.7/site-packages/airflow/utils/process_utils.py", line 97, in reap_process_group
    signal_procs(sig)
  File "/Users/dstandish/.virtualenvs/abctest/lib/python3.7/site-packages/airflow/utils/process_utils.py", line 72, in signal_procs
    ["sudo", "-n", "kill", "-" + str(int(sig))] + [str(p.pid) for p in children]
  File "/Users/dstandish/.pyenv/versions/3.7.5/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['sudo', '-n', 'kill', '-15', '15878']' returned non-zero exit status 1.
[2020-12-10 11:50:12,356] {sequential_executor.py:66} ERROR - Failed to execute task Command '['airflow', 'tasks', 'run', 'test_dag', 'mssqltask', '2020-12-10T19:45:00+00:00', '--local', '--pool', 'default_pool', '--subdir', '/Users/dstandish/code/abctest/dags/testing.py']' returned non-zero exit status 1..
```

**Comment by dstandish** [comment]
note, during time scheduler was running, i was upgrading docker to 3.0 

i don't _think_ there is any relationship here but i just want to mention it in case

one thing i _did_ just find just now is that docker 3.0 listens on port 8080 which is interfering with webserver but that is unrelated

**Comment by dstandish** [comment]
after letting it continue to run for another 2 hours, this error did appear again 2 more times, at `2020-12-10 13:00:02,622` and `2020-12-10 13:25:12,988`

**Comment by vikramkoka** [comment]
@dstandish Does this error show up with Airflow 2.0.1? 
I realize this was originally reported on a release candidate, not sure if you have seen it with the released build?

**Comment by dstandish** [comment]
have not, will close
