### ISSUE TITLE
No such file or directory: '/usr/local/lib/python3.9/site-packages/airflow/customized_form_field_behaviours.schema.json'

### ISSUE THREAD

**Issue by tooptoop4** [apache/airflow#13027]
v2.0.0rc1

```
airflow db init
DB: sqlite:////Users/red/airflow/airflow.db
[2020-12-12 00:33:02,036] {db.py:678} INFO - Creating tables
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/airflow/__main__.py", line 40, in main
    args.func(args)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/commands/db_command.py", line 31, in initdb
    db.initdb()
  File "/usr/local/lib/python3.9/site-packages/airflow/utils/db.py", line 549, in initdb
    upgradedb()
  File "/usr/local/lib/python3.9/site-packages/airflow/utils/db.py", line 688, in upgradedb
    command.upgrade(config, 'heads')
  File "/usr/local/lib/python3.9/site-packages/alembic/command.py", line 298, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.9/site-packages/alembic/script/base.py", line 489, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 98, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.9/site-packages/alembic/util/compat.py", line 184, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/site-packages/airflow/migrations/env.py", line 108, in <module>
    run_migrations_online()
  File "/usr/local/lib/python3.9/site-packages/airflow/migrations/env.py", line 102, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/local/lib/python3.9/site-packages/alembic/runtime/environment.py", line 846, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/lib/python3.9/site-packages/alembic/runtime/migration.py", line 511, in run_migrations
    for step in self._migrations_fn(heads, self):
  File "/usr/local/lib/python3.9/site-packages/alembic/command.py", line 287, in upgrade
    return script._upgrade_revs(revision, rev)
  File "/usr/local/lib/python3.9/site-packages/alembic/script/base.py", line 364, in _upgrade_revs
    revs = list(revs)
  File "/usr/local/lib/python3.9/site-packages/alembic/script/revision.py", line 777, in _iterate_revisions
    uppers = util.dedupe_tuple(self.get_revisions(upper))
  File "/usr/local/lib/python3.9/site-packages/alembic/script/revision.py", line 321, in get_revisions
    resolved_id, branch_label = self._resolve_revision_number(id_)
  File "/usr/local/lib/python3.9/site-packages/alembic/script/revision.py", line 501, in _resolve_revision_number
    self._revision_map
  File "/usr/local/lib/python3.9/site-packages/alembic/util/langhelpers.py", line 230, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/usr/local/lib/python3.9/site-packages/alembic/script/revision.py", line 123, in _revision_map
    for revision in self._generator():
  File "/usr/local/lib/python3.9/site-packages/alembic/script/base.py", line 112, in _load_revisions
    script = Script._from_filename(self, vers, file_)
  File "/usr/local/lib/python3.9/site-packages/alembic/script/base.py", line 906, in _from_filename
    module = util.load_python_file(dir_, filename)
  File "/usr/local/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 98, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.9/site-packages/alembic/util/compat.py", line 184, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/site-packages/airflow/migrations/versions/2c6edca13270_resource_based_permissions.py", line 27, in <module>
    from airflow.www.app import create_app
  File "/usr/local/lib/python3.9/site-packages/airflow/www/app.py", line 38, in <module>
    from airflow.www.extensions.init_views import (
  File "/usr/local/lib/python3.9/site-packages/airflow/www/extensions/init_views.py", line 29, in <module>
    from airflow.www.views import lazy_add_provider_discovered_options_to_connection_form
  File "/usr/local/lib/python3.9/site-packages/airflow/www/views.py", line 2836, in <module>
    class ConnectionFormWidget(FormWidget):
  File "/usr/local/lib/python3.9/site-packages/airflow/www/views.py", line 2839, in ConnectionFormWidget
    field_behaviours = json.dumps(ProvidersManager().field_behaviours)
  File "/usr/local/lib/python3.9/site-packages/airflow/providers_manager.py", line 111, in __init__
    _create_customized_form_field_behaviours_schema_validator()
  File "/usr/local/lib/python3.9/site-packages/airflow/providers_manager.py", line 53, in _create_customized_form_field_behaviours_schema_validator
    importlib_resources.read_text('airflow', 'customized_form_field_behaviours.schema.json')
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/resources.py", line 139, in read_text
    with open_text(package, resource, encoding, errors) as fp:
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/resources.py", line 121, in open_text
    open_binary(package, resource), encoding=encoding, errors=errors)
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/resources.py", line 91, in open_binary
    return reader.open_resource(resource)
  File "<frozen importlib._bootstrap_external>", line 995, in open_resource
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.9/site-packages/airflow/customized_form_field_behaviours.schema.json'
```

**Comment by potiuk** [comment]
First of all - python 3.9 is not officially supported yet. But I think I need more information. 

Did you install airlfow with sdist package?

@ashb @kaxil - I just checked and it looks like unlike .whl package, the .tar.gz does not contain `customized_form_field_behaviours.schema.json`. I looked at it and seems that while it is in setup.cfg, it is missing in MANIFEST.in. I will fix it now, but I think this might be a reason to call for rc2

**Comment by potiuk** [comment]
Thanks @tooptoop4 for raising - can you please tell us why you have used sdist not wheel ? What was the reason ?

**Comment by tooptoop4** [comment]
@potiuk I just did python3 -m pip install https://dist.apache.org/repos/dist/dev/airflow/2.0.0rc1/apache-airflow-2.0.0rc1-bin.tar.gz.  I am using MacOs BigSur 11.0.1

**Comment by tooptoop4** [comment]
@potiuk is it expected that docs link from airflow ui is broken? maybe expected if v2 not released

**Comment by ashb** [comment]
> @potiuk is it expected that docs link from airflow ui is broken? maybe expected if v2 not released

Yeah, that's expected until 2.0.0 is released and we publish the docs

**Comment by ashb** [comment]
Ahhh - it's not using the wheel because you gave it an explicit URL :)

**Comment by potiuk** [comment]
Yeah!  So this is not a common thing :)

**Comment by tooptoop4** [comment]
@ashb are 'dynamic dags' (ie https://bigdata-etl.com/apache-airflow-create-dynamic-dag/ but with a single .py creating many different dagids) supported with fully serialized dags (ie scheduler reading from the db instead of parsing the .py)?

**Comment by ashb** [comment]
I haven't explicilty tested _that_ case, but yes should be -- the scheduler loop never touches DAG files itself; it only uses the database.
