### ISSUE TITLE
Broken example introduced

### ISSUE THREAD

**Issue by cognalog** [apache/airflow#1313]
Dear Airflow Maintainers,

Before I tell you about my issue, let me describe my environment:
### Environment
- Version of Airflow (e.g. a release version, running your own fork, running off master -- provide a git log snippet): **master branch, commit** 4865ee66ba6d53e4a0b809ccbb60a65b5ede1915
- Screen shots of your DAG's graph and tree views: ![broken dag](http://i.imgur.com/gHhSO7R.png)
- Stack trace if applicable:

```
[2016-04-06 19:19:09,361] {models.py:233} ERROR - Failed to import: /usr/local/lib/python2.7/dist-packages/airflow-1.7.0-py2.7.egg/airflow/example_dags/example_skip_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/airflow-1.7.0-py2.7.egg/airflow/models.py", line 231, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python2.7/dist-packages/airflow-1.7.0-py2.7.egg/airflow/example_dags/example_skip_dag.py", line 60, in <module>
    create_test_pipeline('1', 'all_success', dag)
  File "/usr/local/lib/python2.7/dist-packages/airflow-1.7.0-py2.7.egg/airflow/example_dags/example_skip_dag.py", line 48, in create_test_pipeline
    op = MyEmrOperator(task_id='my_task_id', dag=dag,
NameError: global name 'MyEmrOperator' is not defined
```
- Operating System: (Windows Version or `$ uname -a`) **Ubuntu 14.04**
- Python Version: `$ python --version` **2.7.6**
### Description of Issue
- What did you expect to happen? **All examples are loaded properly**
- What happened instead? **One example can't be loaded**
### Reproduction Steps
1. `airflow webserver`

@withnale, you may know what's going on?

**Comment by r39132** [comment]
Thx for reporting. @jlowin is working on a PR to address this.

**Comment by jlowin** [comment]
Sorry about that @ty707 -- an extra operator related to a discussion we were having offline snuck into the PR -- @r39132 fixed it in #1316 and I discovered that not all example dags are being unit tested, #1317.

**Comment by cognalog** [comment]
No sweat, glad some unit tests came out of it 😁

**Comment by withnale** [comment]
<holds hand up>

My bad. Sorry this got through. I fixed it an hour later in the PR branch when I noticed it, but it had been merged by them.
