### ISSUE TITLE
having problems to start the weserver

### ISSUE THREAD

**Issue by paulobuch** [apache/airflow#13188]
**Apache Airflow version**:
Apache Airflow: 2.0.0

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:
python_version  | 3.8.6
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):Mac OS
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
running the command `airflow webserver --port 8080`  I am receiving the follow msg : 
[2020-12-19 21:27:35,593] {webserver_command.py:217} ERROR - No response from gunicorn master within 120 seconds
[2020-12-19 21:27:35,593] {webserver_command.py:218} ERROR - Shutting down webserver

and in the localhost on the browser I received :
Something bad has happened.
Please consider letting us know by creating a bug report using GitHub.

Python version: 2.0.0
Airflow version: 3.8.6
Node: 
-------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/paulobuchsenspaner/Documents/python_virtual_env/Tutorial_Airflow/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/paulobuchsenspaner/Documents/python_virtual_env/Tutorial_Airflow/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/paulobuchsenspaner/Documents/python_virtual_env/Tutorial_Airflow/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/paulobuchsenspaner/Documents/python_virtual_env/Tutorial_Airflow/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/paulobuchsenspaner/Documents/python_virtual_env/Tutorial_Airflow/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/paulobuchsenspaner/Documents/python_virtual_env/Tutorial_Airflow/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/paulobuchsenspaner/Documents/python_virtual_env/Tutorial_Airflow/lib/python3.8/site-packages/flask_admin/base.py", line 69, in inner
    return self._run_view(f, *args, **kwargs)
  File "/Users/paulobuchsenspaner/Documents/python_virtual_env/Tutorial_Airflow/lib/python3.8/site-packages/flask_admin/base.py", line 368, in _run_view
    return fn(self, *args, **kwargs)
  File "/Users/paulobuchsenspaner/Documents/python_virtual_env/Tutorial_Airflow/lib/python3.8/site-packages/flask_login/utils.py", line 258, in decorated_view
    return func(*args, **kwargs)
  File "/Users/paulobuchsenspaner/Documents/python_virtual_env/Tutorial_Airflow/lib/python3.8/site-packages/airflow/utils/db.py", line 74, in wrapper
    pool=Pool.DEFAULT_POOL_NAME,
  File "/Users/paulobuchsenspaner/Documents/python_virtual_env/Tutorial_Airflow/lib/python3.8/site-packages/airflow/www/views.py", line 2341, in index
    for task in dag.tasks:
  File "/Users/paulobuchsenspaner/Documents/python_virtual_env/Tutorial_Airflow/lib/python3.8/site-packages/airflow/www/views.py", line 411, in render
    including metadatabase and scheduler.
  File "/Users/paulobuchsenspaner/Documents/python_virtual_env/Tutorial_Airflow/lib/python3.8/site-packages/flask_admin/base.py", line 308, in render
    return render_template(template, **kwargs)
  File "/Users/paulobuchsenspaner/Documents/python_virtual_env/Tutorial_Airflow/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/Users/paulobuchsenspaner/Documents/python_virtual_env/Tutorial_Airflow/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/paulobuchsenspaner/Documents/python_virtual_env/Tutorial_Airflow/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/paulobuchsenspaner/Documents/python_virtual_env/Tutorial_Airflow/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/paulobuchsenspaner/Documents/python_virtual_env/Tutorial_Airflow/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/paulobuchsenspaner/Documents/python_virtual_env/Tutorial_Airflow/lib/python3.8/site-packages/airflow/www/templates/airflow/dags.html", line 20, in top-level template code
    {% extends base_template %}
  File "/Users/paulobuchsenspaner/Documents/python_virtual_env/Tutorial_Airflow/lib/python3.8/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/paulobuchsenspaner/Documents/python_virtual_env/Tutorial_Airflow/lib/python3.8/site-packages/flask/templating.py", line 86, in _get_source_fast
    return loader.get_source(environment, template)
  File "/Users/paulobuchsenspaner/Documents/python_virtual_env/Tutorial_Airflow/lib/python3.8/site-packages/jinja2/loaders.py", line 177, in get_source
    pieces = split_template_path(template)
  File "/Users/paulobuchsenspaner/Documents/python_virtual_env/Tutorial_Airflow/lib/python3.8/site-packages/jinja2/loaders.py", line 26, in split_template_path
    for piece in template.split("/"):
jinja2.exceptions.UndefinedError: 'base_template' is undefined

**Comment by vikramkoka** [comment]
@paulobuch Apologies for the belated response. 
Can you please let us know if there is any other information you can add here to reproduce this? 

I tried this with Airflow 2.0.1 and it comes up as expected.
