### ISSUE TITLE
airflow.contrib.executors module missing in airflow 1.10.14

### ISSUE THREAD

**Issue by ephraimbuddy** [apache/airflow#13252]
MesosExecutor and KubernetesExecutor can no longer be imported from `airflow.contrib.executors` in the released 1.10.14

**Apache Airflow version**:1.10.14

**What happened**:

MesosExecutor cannot be used because `airflow.contrib.executors` is missing

**What you expected to happen**:

I expected to use MesosExecutor without issues

**How to reproduce it**:
1. Install apache-airflow 1.10.14
2. Use postgres or MySQL backend
3. Set executor to MesosExecutor
4. Start airflow and see this error:
```
Traceback (most recent call last):
  File "/home/ephraimbuddy/anaconda3/envs/airflow2/bin/airflow", line 37, in <module>
    args.func(args)
  File "/home/ephraimbuddy/anaconda3/envs/airflow2/lib/python3.7/site-packages/airflow/utils/cli.py", line 233, in wrapper
    func(args)
  File "/home/ephraimbuddy/anaconda3/envs/airflow2/lib/python3.7/site-packages/airflow/bin/cli.py", line 1626, in initdb
    db.initdb(settings.RBAC)
  File "/home/ephraimbuddy/anaconda3/envs/airflow2/lib/python3.7/site-packages/airflow/utils/db.py", line 323, in initdb
    upgradedb()
  File "/home/ephraimbuddy/anaconda3/envs/airflow2/lib/python3.7/site-packages/airflow/utils/db.py", line 386, in upgradedb
    command.upgrade(config, 'heads')
  File "/home/ephraimbuddy/anaconda3/envs/airflow2/lib/python3.7/site-packages/alembic/command.py", line 298, in upgrade
    script.run_env()
  File "/home/ephraimbuddy/anaconda3/envs/airflow2/lib/python3.7/site-packages/alembic/script/base.py", line 489, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/home/ephraimbuddy/anaconda3/envs/airflow2/lib/python3.7/site-packages/alembic/util/pyfiles.py", line 98, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/ephraimbuddy/anaconda3/envs/airflow2/lib/python3.7/site-packages/alembic/util/compat.py", line 184, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ephraimbuddy/anaconda3/envs/airflow2/lib/python3.7/site-packages/airflow/migrations/env.py", line 97, in <module>
    run_migrations_online()
  File "/home/ephraimbuddy/anaconda3/envs/airflow2/lib/python3.7/site-packages/airflow/migrations/env.py", line 91, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/home/ephraimbuddy/anaconda3/envs/airflow2/lib/python3.7/site-packages/alembic/runtime/environment.py", line 846, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/home/ephraimbuddy/anaconda3/envs/airflow2/lib/python3.7/site-packages/alembic/runtime/migration.py", line 522, in run_migrations
    step.migration_fn(**kw)
  File "/home/ephraimbuddy/anaconda3/envs/airflow2/lib/python3.7/site-packages/airflow/migrations/versions/cc1e65623dc7_add_max_tries_column_to_task_instance.py", line 70, in upgrade
    dagbag = DagBag(settings.DAGS_FOLDER)
  File "/home/ephraimbuddy/anaconda3/envs/airflow2/lib/python3.7/site-packages/airflow/models/dagbag.py", line 95, in __init__
    executor = get_default_executor()
  File "/home/ephraimbuddy/anaconda3/envs/airflow2/lib/python3.7/site-packages/airflow/executors/__init__.py", line 48, in get_default_executor
    DEFAULT_EXECUTOR = _get_executor(executor_name)
  File "/home/ephraimbuddy/anaconda3/envs/airflow2/lib/python3.7/site-packages/airflow/executors/__init__.py", line 82, in _get_executor
    from airflow.contrib.executors.mesos_executor import MesosExecutor
ModuleNotFoundError: No module named 'airflow.contrib.executors'
```

If you check the 1.10.14 tag, you will see the module: https://github.com/apache/airflow/tree/1.10.14/airflow/contrib/executors

**Comment by potiuk** [comment]
Confirmed. Seems like __init__.py has been accidentally moved out from contrib.executors module in https://github.com/apache/airflow/commit/3437663676f287b84e9c3fa05ed404e4adf34739

**Comment by kaxil** [comment]
Closed by https://github.com/apache/airflow/commit/cc768576a8df3a1dbdb9e22de087b020b598f124
