### ISSUE TITLE
ValueError: unsupported pickle protocol: 5

### ISSUE THREAD

**Issue by trustfuture** [apache/airflow#13317]
Python version: 3.7.7
Airflow version: 2.0.0
-------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/han/opt/anaconda3/envs/py37/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/han/opt/anaconda3/envs/py37/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/han/opt/anaconda3/envs/py37/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/han/opt/anaconda3/envs/py37/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/han/opt/anaconda3/envs/py37/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/han/opt/anaconda3/envs/py37/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/han/opt/anaconda3/envs/py37/lib/python3.7/site-packages/airflow/www/auth.py", line 34, in decorated
    return func(*args, **kwargs)
  File "/Users/han/opt/anaconda3/envs/py37/lib/python3.7/site-packages/airflow/www/decorators.py", line 97, in view_func
    return f(*args, **kwargs)
  File "/Users/han/opt/anaconda3/envs/py37/lib/python3.7/site-packages/airflow/www/decorators.py", line 60, in wrapper
    return f(*args, **kwargs)
  File "/Users/han/opt/anaconda3/envs/py37/lib/python3.7/site-packages/airflow/utils/session.py", line 65, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/han/opt/anaconda3/envs/py37/lib/python3.7/site-packages/airflow/www/views.py", line 2042, in graph
    dt_nr_dr_data = get_date_time_num_runs_dag_runs_form_data(request, session, dag)
  File "/Users/han/opt/anaconda3/envs/py37/lib/python3.7/site-packages/airflow/www/views.py", line 156, in get_date_time_num_runs_dag_runs_form_data
    .limit(num_runs)
  File "/Users/han/opt/anaconda3/envs/py37/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3373, in all
    return list(self)
  File "/Users/han/opt/anaconda3/envs/py37/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 100, in instances
    cursor.close()
  File "/Users/han/opt/anaconda3/envs/py37/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "/Users/han/opt/anaconda3/envs/py37/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/Users/han/opt/anaconda3/envs/py37/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 80, in instances
    rows = [proc(row) for row in fetch]
  File "/Users/han/opt/anaconda3/envs/py37/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 80, in <listcomp>
    rows = [proc(row) for row in fetch]
  File "/Users/han/opt/anaconda3/envs/py37/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 588, in _instance
    populators,
  File "/Users/han/opt/anaconda3/envs/py37/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 725, in _populate_full
    dict_[key] = getter(row)
  File "/Users/han/opt/anaconda3/envs/py37/lib/python3.7/site-packages/sqlalchemy/sql/sqltypes.py", line 1723, in process
    return loads(value)
ValueError: unsupported pickle protocol: 5

**Comment by potiuk** [comment]
Did you try to clean cookies? That seems like you connected to a new version of Airflow (with different python version) using the same address/session stored in the browser. cleaning cookies or running in incognito mode should fix it. Can you try it and let us know if this solves the issue?

**Comment by trustfuture** [comment]
> Did you try to clean cookies? That seems like you connected to a new version of Airflow (with different python version) using the same address/session stored in the browser. cleaning cookies or running in incognito mode should fix it. Can you try it and let us know if this solves the issue?

yes, you are right! I have a 3.8 version python on my mac, and a 3.7 version python in anaconda environment, it works when I open airflow in 3.8 version, but still can not open in 3.7 version even I cleaned cookies.

**Comment by GreenGrassBlueOcean** [comment]
This issue does also occur when running airflow with multiple nodes and airflow (1.10.11) has one of its nodes run in at higher python version in my case one node is running at 3.8.5. and another at 3.7.7.
As indicated here: [(https://stackoverflow.com/questions/23582489/python-pickle-protocol-choice)]
pickle protocol: 5 Protocol can only be used in python > 3.8.

The remarkable thing however is that some dags run fine (even on the 3.8.5. node), and others have suddenly a problem and do not run at all any more.

**Comment by ashb** [comment]
Fairly sure this one is going to be a "can't fix - don't run multiple different python versions in parallel" --if you need to do that use the VirtualEnv operator.

**Comment by ferruzzi** [comment]
I ran into this today while running Breeze.  In addition to making sure you are in the pyenv, I also had to run breeze with the `--db-reset` flag.  Figured I'd note that here in case anyone runs into this in the future.

**Comment by potiuk** [comment]
Yeah. This might happen if you change airflow version or python for breeze as the database remains running between the invocations.to speed up the startup. Also the volumes for the db are preserved even if the db is restarted. That's why you needed to reset the db. 

Another way to handle it is to run `breeze stop` which shuts down all the  databases and removes volumes. 

PR to automatically reset the DB when Python or airflow version changes would be most welcome ;).

**Comment by dcardinha** [comment]
@trustfuture Did you find a way to solve this? I am facing exactly the same problem

**Comment by ferruzzi** [comment]
@dcardinha The answer is in the discussion.

**Comment by assem-ch** [comment]
> In airflow 2.3.4, running airflow db reset solved the issue.
This solves the issue, but be aware that it will delete anything in database.
