### ISSUE TITLE
Upgrade from 1.10.14 to 2.0.0 fails with MySQL DROP CONSTRAINT

### ISSUE THREAD

**Issue by Dundo777** [apache/airflow#13491]
**Apache Airflow version**: 2.0.0

**Environment**:

- **Cloud provider or hardware configuration**: X
- **OS** (e.g. from /etc/os-release): CentOS 7
- **Kernel** (e.g. `uname -a`): x86_64
- **Install tools**: yum, pip
- **Others**:

**What happened**:

airflow db upgrade fails after upgrade from 1.10.14 to 2.0.0
Full log message:

<details>
<summary>
 DB: mysql://....
[2021-01-05 17:03:54,693] {db.py:678} INFO - Creating tables
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
WARNI [airflow.providers_manager] The provider for package 'apache-airflow-providers-jdbc' could not be registered from because providers for that package name have already been registered
WARNI [airflow.providers_manager] The provider for package 'apache-airflow-providers-sqlite' could not be registered from because providers for that package name have already been registered
WARNI [airflow.providers_manager] The provider for package 'apache-airflow-providers-imap' could not be registered from because providers for that package name have already been registered
WARNI [airflow.providers_manager] The provider for package 'apache-airflow-providers-http' could not be registered from because providers for that package name have already been registered
WARNI [airflow.providers_manager] The provider for package 'apache-airflow-providers-ftp' could not be registered from because providers for that package name have already been registered
WARNI [airflow.providers_manager] The provider for package 'apache-airflow-providers-mysql' could not be registered from because providers for that package name have already been registered
WARNI [airflow.providers_manager] The provider for package 'apache-airflow-providers-apache-hdfs' could not be registered from because providers for that package name have already been registered
WARNI [airflow.providers_manager] The provider for package 'apache-airflow-providers-postgres' could not be registered from because providers for that package name have already been registered
WARNI [airflow.providers_manager] The provider for package 'apache-airflow-providers-jdbc' could not be registered from because providers for that package name have already been registered
WARNI [airflow.providers_manager] The provider for package 'apache-airflow-providers-sqlite' could not be registered from because providers for that package name have already been registered
WARNI [airflow.providers_manager] The provider for package 'apache-airflow-providers-imap' could not be registered from because providers for that package name have already been registered
WARNI [airflow.providers_manager] The provider for package 'apache-airflow-providers-http' could not be registered from because providers for that package name have already been registered
WARNI [airflow.providers_manager] The provider for package 'apache-airflow-providers-ftp' could not be registered from because providers for that package name have already been registered
WARNI [airflow.providers_manager] The provider for package 'apache-airflow-providers-mysql' could not be registered from because providers for that package name have already been registered
WARNI [airflow.providers_manager] The provider for package 'apache-airflow-providers-apache-hdfs' could not be registered from because providers for that package name have already been registered
WARNI [airflow.providers_manager] The provider for package 'apache-airflow-providers-postgres' could not be registered from because providers for that package name have already been registered
INFO  [alembic.runtime.migration] Running upgrade 03afc6b6f902 -> cf5dc11e79ad, drop_user_and_chart
Traceback (most recent call last):
  File "/usr/local/airflow_env/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/usr/local/airflow_env/lib64/python3.6/site-packages/airflow/__main__.py", line 40, in main
    args.func(args)
  File "/usr/local/airflow_env/lib64/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/usr/local/airflow_env/lib64/python3.6/site-packages/airflow/utils/cli.py", line 89, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/airflow_env/lib64/python3.6/site-packages/airflow/cli/commands/db_command.py", line 48, in upgradedb
    db.upgradedb()
  File "/usr/local/airflow_env/lib64/python3.6/site-packages/airflow/utils/db.py", line 688, in upgradedb
    command.upgrade(config, 'heads')
  File "/usr/local/airflow_env/lib64/python3.6/site-packages/alembic/command.py", line 298, in upgrade
    script.run_env()
  File "/usr/local/airflow_env/lib64/python3.6/site-packages/alembic/script/base.py", line 489, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/airflow_env/lib64/python3.6/site-packages/alembic/util/pyfiles.py", line 98, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/airflow_env/lib64/python3.6/site-packages/alembic/util/compat.py", line 184, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow_env/lib64/python3.6/site-packages/airflow/migrations/env.py", line 108, in <module>
    run_migrations_online()
  File "/usr/local/airflow_env/lib64/python3.6/site-packages/airflow/migrations/env.py", line 102, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/local/airflow_env/lib64/python3.6/site-packages/alembic/runtime/environment.py", line 846, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/airflow_env/lib64/python3.6/site-packages/alembic/runtime/migration.py", line 522, in run_migrations
    step.migration_fn(**kw)
  File "/usr/local/airflow_env/lib64/python3.6/site-packages/airflow/migrations/versions/cf5dc11e79ad_drop_user_and_chart.py", line 49, in upgrade
    op.drop_constraint('known_event_user_id_fkey', 'known_event')
  File "<string>", line 8, in drop_constraint
  File "<string>", line 3, in drop_constraint
  File "/usr/local/airflow_env/lib64/python3.6/site-packages/alembic/operations/ops.py", line 159, in drop_constraint
    return operations.invoke(op)
  File "/usr/local/airflow_env/lib64/python3.6/site-packages/alembic/operations/base.py", line 373, in invoke
    return fn(self, operation)
  File "/usr/local/airflow_env/lib64/python3.6/site-packages/alembic/operations/toimpl.py", line 163, in drop_constraint
    schema=operation.schema,
  File "/usr/local/airflow_env/lib64/python3.6/site-packages/alembic/ddl/mysql.py", line 113, in drop_constraint
    super(MySQLImpl, self).drop_constraint(const)
  File "/usr/local/airflow_env/lib64/python3.6/site-packages/alembic/ddl/impl.py", line 248, in drop_constraint
    self._exec(schema.DropConstraint(const))
  File "/usr/local/airflow_env/lib64/python3.6/site-packages/alembic/ddl/impl.py", line 141, in _exec
    return conn.execute(construct, *multiparams, **params)
  File "/usr/local/airflow_env/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/usr/local/airflow_env/lib64/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/local/airflow_env/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1066, in _execute_ddl
    else None,
  File "<string>", line 1, in <lambda>
  File "/usr/local/airflow_env/lib64/python3.6/site-packages/sqlalchemy/sql/elements.py", line 481, in compile
    return self._compiler(dialect, bind=bind, **kw)
  File "/usr/local/airflow_env/lib64/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 29, in _compiler
    return dialect.ddl_compiler(dialect, self, **kw)
  File "/usr/local/airflow_env/lib64/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 322, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/usr/local/airflow_env/lib64/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 352, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/usr/local/airflow_env/lib64/python3.6/site-packages/sqlalchemy/ext/compiler.py", line 441, in <lambda>
    lambda *arg, **kw: existing(*arg, **kw),
  File "/usr/local/airflow_env/lib64/python3.6/site-packages/sqlalchemy/ext/compiler.py", line 486, in __call__
    return fn(element, compiler, **kw)
  File "/usr/local/airflow_env/lib64/python3.6/site-packages/alembic/ddl/mysql.py", line 394, in _mysql_drop_constraint
    "No generic 'DROP CONSTRAINT' in MySQL - "
NotImplementedError: No generic 'DROP CONSTRAINT' in MySQL - please specify constraint type
</summary>
</details>

**What you expected to happen**:

I started doing upgrade from 1.10.14 to 2.0.0 with MySQL 5.6 installed. Then I upgraded to MySQL 5.7 but still got the same error. Finally upgraded to MariaDB 10.2 and still getting the same error.
I expected the problem is in MySQL database version but upgrading it didn't solve the problem.

**How to reproduce it**:
Using MySQL 5.6 or MySQL 5.7 or MariaDB 10.2, upgrade Airflow binaries from 1.10.14 to 2.0.0 and then run airflow db upgrade.

**Anything else we need to know**:
Versions:
- Python 3.6.8
- alembic 1.4.3

**Comment by Dundo777** [comment]
solved it with fix in this issue 
#13222 https://github.com/apache/airflow/issues/13222#issuecomment-749184968
