### ISSUE TITLE
DAGs don't open in the UI using MSSQL as the backend 

### ISSUE THREAD

**Issue by iansuvak** [apache/airflow#1369]
#### Environment
- Airflow master HEAD 96891596f9c392a9a477e5e564ea08a84095386b 
- CentOS 6.5
- Python 2.7.3
- pymssql 2.1.0
  Fresh install of airflow with a brand new DB migration 
#### Issue

The same general issue as   #340 but in utils.py instead of models.py
To replicate just run `airflow webserver` and navigate to any DAG but I assume that more actions might be affected.
Removing the `from builtins import str` line fixes it again. 

Do you recommend removing it if I don't care about Python 3 support or is there an effort to solve this issue at a deeper level?
#### Stacktrace

```
Traceback (most recent call last):
  File "/home/pkg/python2.7/Python-2.7.3/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pkg/python2.7/Python-2.7.3/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pkg/python2.7/Python-2.7.3/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pkg/python2.7/Python-2.7.3/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pkg/python2.7/Python-2.7.3/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pkg/python2.7/Python-2.7.3/lib/python2.7/site-packages/Flask_Admin-1.4.0-py2.7.egg/flask_admin/base.py", line 68, in inner
    return self._run_view(f, *args, **kwargs)
  File "/home/pkg/python2.7/Python-2.7.3/lib/python2.7/site-packages/Flask_Admin-1.4.0-py2.7.egg/flask_admin/base.py", line 367, in _run_view
    return fn(self, *args, **kwargs)
  File "/home/pkg/python2.7/Python-2.7.3/lib/python2.7/site-packages/flask_login.py", line 755, in decorated_view
    return func(*args, **kwargs)
  File "/home/pkg/python2.7/Python-2.7.3/lib/python2.7/site-packages/airflow-1.7.0-py2.7.egg/airflow/www/utils.py", line 199, in view_func
    return f(*args, **kwargs)
  File "/home/pkg/python2.7/Python-2.7.3/lib/python2.7/site-packages/airflow-1.7.0-py2.7.egg/airflow/www/utils.py", line 102, in wrapper
    session.commit()
  File "/home/pkg/python2.7/Python-2.7.3/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 801, in commit
    self.transaction.commit()
  File "/home/pkg/python2.7/Python-2.7.3/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 392, in commit
    self._prepare_impl()
  File "/home/pkg/python2.7/Python-2.7.3/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 372, in _prepare_impl
    self.session.flush()
  File "/home/pkg/python2.7/Python-2.7.3/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2019, in flush
    self._flush(objects)
  File "/home/pkg/python2.7/Python-2.7.3/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2137, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/pkg/python2.7/Python-2.7.3/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/pkg/python2.7/Python-2.7.3/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2101, in _flush
    flush_context.execute()
  File "/home/pkg/python2.7/Python-2.7.3/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
    rec.execute(self)
  File "/home/pkg/python2.7/Python-2.7.3/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
    uow
  File "/home/pkg/python2.7/Python-2.7.3/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 174, in save_obj
    mapper, table, insert)
  File "/home/pkg/python2.7/Python-2.7.3/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 800, in _emit_insert_statements
    execute(statement, params)
  File "/home/pkg/python2.7/Python-2.7.3/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/home/pkg/python2.7/Python-2.7.3/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/pkg/python2.7/Python-2.7.3/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/pkg/python2.7/Python-2.7.3/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/home/pkg/python2.7/Python-2.7.3/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1344, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "/home/pkg/python2.7/Python-2.7.3/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/home/pkg/python2.7/Python-2.7.3/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
  File "pymssql.pyx", line 417, in pymssql.Cursor.execute (pymssql.c:6057)
  File "_mssql.pyx", line 943, in _mssql.MSSQLConnection.execute_query (_mssql.c:9858)
  File "_mssql.pyx", line 974, in _mssql.MSSQLConnection.execute_query (_mssql.c:9734)
  File "_mssql.pyx", line 1091, in _mssql.MSSQLConnection.format_and_run_query (_mssql.c:10814)
  File "_mssql.pyx", line 1113, in _mssql.MSSQLConnection.format_sql_command (_mssql.c:11042)
  File "_mssql.pyx", line 1779, in _mssql._substitute_params (_mssql.c:18463)
  File "_mssql.pyx", line 195, in _mssql.ensure_bytes (_mssql.c:2671)
TypeError: Expected bytes, got newbytes
```

**Comment by r39132** [comment]
@jlowin ?

**Comment by jlowin** [comment]
@iansuvak I think you're right, this is the same as #340 and has to do with an explicit type check in pymssql. Unfortunately I don't have an mssql backend so I can't test this myself, though it does appear that removing the line has no impact on (a limited set of) actions I took in a Python3 webserver, so that's good. Would you please submit a PR to remove it?

**Comment by iansuvak** [comment]
Thanks for confirming.

I'll make sure that it passes all of the tests and nothing else is broken with the webserver in my environment before submitting a PR.

**Comment by iansuvak** [comment]
Did further testing and although it did fix UI more issues cropped up essentially any DB interactions through pymssql will fail if you do `from builtins import str`. They all fail at this line https://github.com/pymssql/pymssql/blob/master/src/_mssql.pyx#L198 in pymssql which is Cython and expects bytes but airflow provided strings encode to newbytes.

I've hacked it to work by calling `__native__.()` on the return inside pymssql but that's not a viable solution.

If no one has a solution to this can we note this issue and remove the MSSQL compatibility claim from the README?
