### ISSUE TITLE
Trigger a DAG Run via the Stable REST API fails with FORBIDDEN

### ISSUE THREAD

**Issue by seybi87** [apache/airflow#13739]
**Apache Airflow version**:

2.0.0

**Environment**:

- **Cloud provider or hardware configuration**: OpenStack -> VM -> Docker container 
- **OS** (e.g. from /etc/os-release): Debian GNU/Linux 10 (buster)
- **Kernel** (e.g. `uname -a`): Linux 77f8efd77516 4.4.0-193-generic #224-Ubuntu

**What happened**:

I am trying to trigger a DAG run via the new stable REST-API `1.0.0` by using a Java-based client. The Java client is generated from the Airflow OpenAPI specification with OpenAPI generator version `5.0.0` . 

Custom configurations in my `airflow.cfg`:
 ```
web_server_host = 0.0.0.0
web_server_port = 8080
auth_backend = airflow.api.auth.backend.default

```
In addition I have created one admin user:
```
airflow users create \
    --username admin \
    --password secret \
    --firstname john \
    --lastname doe \
    --role Admin \
    --email john.doe@example.com
```

In Airflow  I have one active DAG `demo`

I trigger the DAG execution via the java client with the following code snippet:

```
ApiClient defaultClient = Configuration.getDefaultApiClient();
defaultClient.setBasePath("http://1.2.3.4:8080/api/v1);
DagRunApi dagRunApi = new DagRunApi(defaultClient);
DAGRun dagRun = new DAGRun();
try {
      DAGRun result = dagRunApi.postDagRun("demo", dagRun);

      LOGGER.debug(result);

    } catch (ApiException e) {
      e.printStackTrace();
    }

```

However, I receive the following exception: 

```
org.openapitools.client.ApiException: FORBIDDEN
	at org.openapitools.client.ApiClient.handleResponse(ApiClient.java:1012)
	at org.openapitools.client.ApiClient.execute(ApiClient.java:925)
	at org.openapitools.client.api.DagRunApi.postDagRunWithHttpInfo(DagRunApi.java:740)
	at org.openapitools.client.api.DagRunApi.postDagRun(DagRunApi.java:715)
	at de.baas.evaluation.scheduler.airflow.ExternalTrigger.triggerDAGRun(ExternalTrigger.java:46)
	at de.baas.evaluation.scheduler.service.BaaSScheduler$1.message(BaaSScheduler.java:60)
	at de.baas.evaluation.scheduler.service.BaaSScheduler$1.message(BaaSScheduler.java:53)
	at io.lettuce.core.pubsub.PubSubEndpoint.notifyListeners(PubSubEndpoint.java:217)
	at io.lettuce.core.pubsub.PubSubEndpoint.notifyMessage(PubSubEndpoint.java:206)
	at io.lettuce.core.pubsub.PubSubCommandHandler.doNotifyMessage(PubSubCommandHandler.java:292)
	at io.lettuce.core.pubsub.PubSubCommandHandler.notifyPushListeners(PubSubCommandHandler.java:223)
	at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:606)
	at io.lettuce.core.pubsub.PubSubCommandHandler.decode(PubSubCommandHandler.java:112)
	at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:560)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

The Airflow logs do not show any error message. 

**What you expected to happen**:

Previously, I also the outdated experimental REST-API to trigger tasks externally (without a client but using custom REST calls) and it worked without issues. 

With the new stable API it seems that my client does not have sufficient permissions even if the authentication is deactivated via `airflow.api.auth.backend.default` 

But also adding username and password to the client creation via 
```
defaultClient.setUsername("admin");
defaultClient.setPassword("secret");
```
results in the same error: `FORBIDDEN`

Do I need to create a dedicated REST-API user and if yes is there any documentation on this topic?

**How to reproduce it**:

Create the Java client (probably any client will produce this error) via OpenAPI generator: 

1. `java -jar codegen/openapi-generator-cli-5.0.0.jar generate -i openapi.yaml -g java  -o .`
2. create a simple java class and apply the code snippets from above

**Anything else we need to know**:

 Apply   the suggested fix of  issue #13740 before reproducing this issue.

**Comment by mik-laj** [comment]
> auth_backend = airflow.api.auth.backend.default

This auth backend does not work for resources that are associated with a DAG.

> You can only disable authentication for experimental API, not the stable REST API.

http://apache-airflow-docs.s3-website.eu-central-1.amazonaws.com/docs/apache-airflow/latest/security/api.html
https://github.com/apache/airflow/commits/master/docs/apache-airflow

**Comment by seybi87** [comment]
@mik-laj thanks a lot for pointing that out, I overlook this in the docs.

I changed the auth backend to 
`auth_backend = airflow.api.auth.backend.basic_auth`

and added the following code snippet to the java code 

```
defaultClient.setUsername("admin");
defaultClient.setPassword("secret");
```
This user has admin rights and is also used to log into the web interface.

But when executing the java code, I receive  a `UNAUTHORIZED` exception: 

``` 
org.openapitools.client.ApiException: UNAUTHORIZED
	at org.openapitools.client.ApiClient.handleResponse(ApiClient.java:1012)
	at org.openapitools.client.ApiClient.execute(ApiClient.java:925)
	at org.openapitools.client.api.DagRunApi.postDagRunWithHttpInfo(DagRunApi.java:740)
	at org.openapitools.client.api.DagRunApi.postDagRun(DagRunApi.java:715)
	at de.baas.evaluation.scheduler.airflow.ExternalTrigger.triggerDAGRun(ExternalTrigger.java:46)
	at de.baas.evaluation.scheduler.service.BaaSScheduler$1.message(BaaSScheduler.java:60)
	at de.baas.evaluation.scheduler.service.BaaSScheduler$1.message(BaaSScheduler.java:53)
	at io.lettuce.core.pubsub.PubSubEndpoint.notifyListeners(PubSubEndpoint.java:217)
	at io.lettuce.core.pubsub.PubSubEndpoint.notifyMessage(PubSubEndpoint.java:206)
	at io.lettuce.core.pubsub.PubSubCommandHandler.doNotifyMessage(PubSubCommandHandler.java:292)
	at io.lettuce.core.pubsub.PubSubCommandHandler.notifyPushListeners(PubSubCommandHandler.java:223)
	at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:606)
	at io.lettuce.core.pubsub.PubSubCommandHandler.decode(PubSubCommandHandler.java:112)
	at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:560)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```
Do I need to set the credentials in a differnt way for basic auth?

**Comment by mik-laj** [comment]
@seybi87  Have you tried to use CURL to send the request to the API?
```
ENDPOINT_URL="http://localhost:8080/"
curl -X GET  \
    --user "username:password" \
    "${ENDPOINT_URL}/api/v1/pools"
```
Overall, we haven't created an official Java client yet, so it's hard for us to support it. We previously had a long discussion that Java clients can be problematic in some cases. See: https://lists.apache.org/thread.html/r88f5f57b4586f75eda382ce2c7309bd32b58cd9cfa1b01f681b6c8d1%40%3Cdev.airflow.apache.org%3E

**Comment by seybi87** [comment]
@mik-laj  thanks for the pointer.

Yes have tried the CURL call and it works as expected.

So the issue relates to not Airflow but to the generated java code based on the OpenAPI generator.
Well, I hoped that the OpenApi code generation is already stable enough to support the code generation for valid OpenApi specs but  it looks like I need to find some time to dig into this issue by myself.

Are there any plans (or even open issues) by Airflow to release a java client at some point in the near future?

**Comment by mik-laj** [comment]
Yes, but no one is working on a Java client yet.
https://github.com/apache/airflow/issues/9080

**Comment by seybi87** [comment]
@mik-laj thanks for the pointer.

Meanwhile I was able to resolve the issue by applying a minor update to the Airflow `openapi.yaml`

Currently, the security scopes are not set correctly for the client code generation but by adding a dedicated security scope for the basic auth as follows, resolves the issue and username/password are transmitted correctly by the java client:

```
# The API will provide support for plugins to support various authorization mechanisms.
# Detailed information will be available in the plugin specification.
security:
  - Basic: []
```  

This also changes the autogenerated docs for how to use the java client with basic auth: 

```
// Configure HTTP basic authorization: Basic
    HttpBasicAuth Basic = (HttpBasicAuth) defaultClient.getAuthentication("Basic");
    Basic.setUsername("admin");
    Basic.setPassword("secret");
```

I have successfully tested the java client with basic auth for triggering DAG runs. 

In case these changes would help you with future releases and the client code generation please let me know and I will compose a pull request.

**Comment by mik-laj** [comment]
Wouldn't you be interested in contributing java client to community? We already have a client for Go, so adding a client for Java shouldn't be a big challenge.
https://github.com/apache/airflow/tree/master/clients

**Comment by seybi87** [comment]
Sure, I can provide a similar script to generate the java client and create a PR. 

However, to have the client working properly this will require also changes to the openapi.yaml (see also #13740 )

Are there any specific contribution guidelines?

**Comment by mik-laj** [comment]
> However, to have the client working properly this will require also changes to the openapi.yaml 

If the change is needed for all customers then we can make changes to the specification, but if it is a change that requires to get around the limitations of the current generator then we can make those changes during the client generation.
For examples,see
https://github.com/apache/airflow/blob/29730d720066a4c16d524e905de8cdf07e8cd129/clients/gen/go.sh#L66-L77
https://github.com/kubernetes-client/python/tree/master/scripts

> Are there any specific contribution guidelines?

Here is the contributor guide:
https://github.com/apache/airflow/blob/master/CONTRIBUTORS_QUICK_START.rst
https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst

But you can just contribute and ask on Slack: #airflow-how-to-pr ([![Slack Status](https://img.shields.io/badge/slack-join_chat-white.svg?logo=slack&style=social)](https://s.apache.org/airflow-slack)) when you have problems
