### ISSUE TITLE
SQLALCHEMY_DATABASE_URI multiple hosts support 

### ISSUE THREAD

**Issue by ghost** [apache/airflow#13764]
**Apache Airflow version**: 2.0
**Environment**: conda
- **OS** (e.g. from /etc/os-release): debian buster
- **Kernel** (e.g. `uname -a`):  5.4.19
**What happened**:
I have master-slave postgres cluster.
I try to configure multiple connection to Postgres. 
I use  sql_alchemy_conn = postgresql+psycopg2://airflow:airflow@/airflow?host=host1&host=host2
When I run airflow db init I have next error:
Traceback (most recent call last):
  File "/usr/local/conda/envs/airflow/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
    return fn()
  File "/usr/local/conda/envs/airflow/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 304, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/usr/local/conda/envs/airflow/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/conda/envs/airflow/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/usr/local/conda/envs/airflow/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
    self._dec_overflow()
  File "/usr/local/conda/envs/airflow/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "/usr/local/conda/envs/airflow/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/conda/envs/airflow/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
    return self._create_connection()
  File "/usr/local/conda/envs/airflow/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/conda/envs/airflow/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/local/conda/envs/airflow/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/local/conda/envs/airflow/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "/usr/local/conda/envs/airflow/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/conda/envs/airflow/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/local/conda/envs/airflow/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/conda/envs/airflow/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 509, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/local/conda/envs/airflow/lib/python3.6/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "?host=host1&host=host2" to address: Name or service not known
**What you expected to happen**:

Maybe flask-sqlalchemy doesn't support multiple connection?

**How to reproduce it**:
Set up multiple connection string:
 sql_alchemy_conn = postgresql+psycopg2://airflow:airflow@?host=host1&host=host2/airflow
and run airflow db init

**Comment by ururu-fy** [comment]
Sorry, it was my mistake in config  file

**Comment by mik-laj** [comment]
Is it still valid?

**Comment by ururu-fy** [comment]
done
