### ISSUE TITLE
[QUARANTINED] test_cli_webserver_foreground_with_pid 

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#13846]
This test fails often:

Example: https://github.com/apache/airflow/pull/13830/checks?check_run_id=1748612606#step:6:2333

```
=================================== FAILURES ===================================
___________ TestCliWebServer.test_cli_webserver_foreground_with_pid ____________

self = <tests.cli.commands.test_webserver_command.TestCliWebServer testMethod=test_cli_webserver_foreground_with_pid>

    def test_cli_webserver_foreground_with_pid(self):
        with tempfile.TemporaryDirectory(prefix='tmp-pid') as tmpdir:
            pidfile = f"{tmpdir}/pidfile"
            with mock.patch.dict(
                "os.environ",
                AIRFLOW__CORE__DAGS_FOLDER="/dev/null",
                AIRFLOW__CORE__LOAD_EXAMPLES="False",
                AIRFLOW__WEBSERVER__WORKERS="1",
            ):
                proc = subprocess.Popen(["airflow", "webserver", "--pid", pidfile])
                assert proc.poll() is None
    
            # Check the file specified by --pid option exists
            self._wait_pidfile(pidfile)
    
            # Terminate webserver
            proc.terminate()
>           assert 0 == proc.wait(60)
E           AssertionError: assert 0 == 1
E            +  where 1 = <bound method Popen.wait of <subprocess.Popen object at 0x7f4b3fd0a160>>(60)
E            +    where <bound method Popen.wait of <subprocess.Popen object at 0x7f4b3fd0a160>> = <subprocess.Popen object at 0x7f4b3fd0a160>.wait

tests/cli/commands/test_webserver_command.py:319: AssertionError
----------------------------- Captured stdout call -----------------------------
0
0
  ____________       _____________
 ____    |__( )_________  __/__  /________      __
____  /| |_  /__  ___/_  /_ __  /_  __ \_ | /| / /
___  ___ |  / _  /   _  __/ _  / / /_/ /_ |/ |/ /
 _/_/  |_/_/  /_/    /_/    /_/  \____/____/|__/
[2021-01-22 12:59:01,376] {dagbag.py:440} INFO - Filling up the DagBag from /dev/null
Running the Gunicorn Server with:
Workers: 1 sync
Host: 0.0.0.0:8080
Timeout: 120
Logfiles: - -
Access Logformat: 
=================================================================            
[2021-01-22 12:59:08,352] {webserver_command.py:431} INFO - Received signal: 15. Closing gunicorn.
0
0
----------------------------- Captured stderr call -----------------------------
[2021-01-22 12:59:08 +0000] [1089] [INFO] Starting gunicorn 19.10.0
[2021-01-22 12:59:08 +0000] [1089] [INFO] Listening at: http://0.0.0.0:8080 (1089)
[2021-01-22 12:59:08 +0000] [1089] [INFO] Using worker: sync
[2021-01-22 12:59:08 +0000] [1092] [INFO] Booting worker with pid: 1092
[2021-01-22 12:59:08 +0000] [1089] [INFO] Handling signal: term
[2021-01-22 12:59:38 +0000] [1089] [INFO] Shutting down: Master
Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 33, in <module>
    sys.exit(load_entry_point('apache-airflow', 'console_scripts', 'airflow')())
  File "/opt/airflow/airflow/__main__.py", line 40, in main
    args.func(args)
  File "/opt/airflow/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/opt/airflow/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/opt/airflow/airflow/cli/commands/webserver_command.py", line 484, in webserver
    monitor_gunicorn(gunicorn_master_proc.pid)
  File "/opt/airflow/airflow/cli/commands/webserver_command.py", line 452, in monitor_gunicorn
    'webserver', 'reload_on_plugin_change', fallback=False
  File "/opt/airflow/airflow/cli/commands/webserver_command.py", line 207, in start
    timeout=self.master_timeout,
  File "/opt/airflow/airflow/cli/commands/webserver_command.py", line 156, in _wait_until_true
    sleep(0.1)
  File "/opt/airflow/airflow/cli/commands/webserver_command.py", line 434, in kill_proc
    gunicorn_master_proc.wait(timeout=30)
  File "/usr/local/lib/python3.6/subprocess.py", line 1469, in wait
    raise TimeoutExpired(self.args, timeout)
subprocess.TimeoutExpired: Command '['gunicorn', '--workers', '1', '--worker-class', 'sync', '--timeout', '120', '--bind', '0.0.0.0:8080', '--name', 'airflow-webserver', '--pid', '/tmp/tmp-pidpnh20wni/pidfile', '--config', 'python:airflow.www.gunicorn_config', '--access-logfile', '-', '--error-logfile', '-', 'airflow.www.app:cached_app()']' timed out after 30 seconds

```

**Comment by chenglongyan** [comment]
this test has been removed from #19712
