### ISSUE TITLE
Airflow Webserver 

### ISSUE THREAD

**Issue by alexsegarra** [apache/airflow#14038]
**Apache Airflow version**:
2.0.0

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):
N/A

**Environment**:
virtualenv

- **Cloud provider or hardware configuration**: N/A - Localhost:8080
- **OS** (e.g. from /etc/os-release): MacOS Cataline 10.15.7
- **Kernel** (e.g. `uname -a`): Kernel Version 19.6.0
- **Install tools**: pip
- **Others**:

**What happened**:
Could not fire up 'airflow webserver.'  Error Message as follows:

Python version: 3.8.3
Airflow version: 2.0.0
Node: CHAAZML-T3CAMD6
-------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Me/projects/git_stuff/pols_analytics_general/airflow/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/Me/projects/git_stuff/pols_analytics_general/airflow/lib/python3.8/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/Users/Me/projects/git_stuff/pols_analytics_general/airflow/lib/python3.8/site-packages/flask/app.py", line 1970, in finalize_request
    response = self.process_response(response)
  File "/Users/Me/projects/git_stuff/pols_analytics_general/airflow/lib/python3.8/site-packages/flask/app.py", line 2269, in process_response
    self.session_interface.save_session(self, ctx.session, response)
  File "/Users/Me/projects/git_stuff/pols_analytics_general/airflow/lib/python3.8/site-packages/flask/sessions.py", line 379, in save_session
    response.set_cookie(
  File "/Users/Me/projects/git_stuff/pols_analytics_general/airflow/lib/python3.8/site-packages/werkzeug/wrappers/base_response.py", line 468, in set_cookie
    dump_cookie(
  File "/Users/Me/projects/git_stuff/pols_analytics_general/airflow/lib/python3.8/site-packages/werkzeug/http.py", line 1217, in dump_cookie
    raise ValueError("SameSite must be 'Strict', 'Lax', or 'None'.")
ValueError: SameSite must be 'Strict', 'Lax', or 'None'.

**What you expected to happen**:
Webserver start.

Uknown

**How to reproduce it**:

**Anything else we need to know**:

Log in Terminal says:

/Users/me/projects/git_stuff/pols_analytics_general/airflow/lib/python3.8/site-packages/airflow/configuration.py:324 DeprecationWarning: The statsd_on option in [scheduler] has been moved to the statsd_on option in [metrics] - the old setting has been used, but please update your config.
/Users/me/projects/git_stuff/pols_analytics_general/airflow/lib/python3.8/site-packages/airflow/configuration.py:324 DeprecationWarning: The logging_config_class option in [core] has been moved to the logging_config_class option in [logging] - the old setting has been used, but please update your config.
/Users/me/projects/git_stuff/pols_analytics_general/airflow/lib/python3.8/site-packages/airflow/configuration.py:324 DeprecationWarning: The task_log_reader option in [core] has been moved to the task_log_reader option in [logging] - the old setting has been used, but please update your config.

**Comment by mik-laj** [comment]
Duplicate: https://github.com/apache/airflow/issues/13971 https://github.com/apache/airflow/issues/10781
