### ISSUE TITLE
'airflow tasks clear' cli command gives error when using --yes or --no_confirm

### ISSUE THREAD

**Issue by tooptoop4** [apache/airflow#14171]
v1.10.14

attempt 1:

```
airflow tasks clear --no_confirm -s 20210210 -e 20210210 mydag
```
```
usage: airflow [-h] GROUP_OR_COMMAND ...

positional arguments:
  GROUP_OR_COMMAND

    Groups:
      celery            Celery components
      config            View configuration
      connections       Manage connections
      dags              Manage DAGs
      db                Database operations
      kubernetes        Tools to help run the KubernetesExecutor
      pools             Manage pools
      tasks             Manage tasks
      users             Manage users
      variables         Manage variables

    Commands:
      kerberos          Start a kerberos ticket renewer
      rotate-fernet-key
                        Rotate encrypted connection credentials and variables
      sync-perm         Update permissions for existing roles and DAGs
      backfill          Run subsections of a DAG for a specified date range.
                        If reset_dag_run option is used, backfill will first
                        prompt users whether airflow should clear all the
                        previous dag_run and task_instances within the
                        backfill date range. If rerun_failed_tasks is used,
                        backfill will auto re-run the previous failed task
                        instances within the backfill date range.
      generate_pod_template
                        Reads your airflow.cfg and migrates your
                        configurations into a airflow_template.yaml file. From
                        this point a user can linkthis file to airflow using
                        the `pod_template_file` argumentand modify using the
                        Kubernetes API
      serve_logs        Serve logs generate by worker
      scheduler         Start a scheduler instance
      webserver         Start a Airflow webserver instance
      version           Show the version
      info              Show information about current Airflow and environment

optional arguments:
  -h, --help            show this help message and exit

airflow command error: unrecognized arguments: --no_confirm, see help above.

```

attempt 2:

```
airflow tasks clear --yes -s 20210210 -e 20210210 mydag
```
```
Traceback (most recent call last):
  File "/home/ec2-user/venv/bin/airflow", line 37, in <module>
    args.func(args)
  File "/home/ec2-user/venv/lib/python3.7/site-packages/airflow/utils/cli.py", line 233, in wrapper
    func(args)
  File "/home/ec2-user/venv/lib/python3.7/site-packages/airflow/utils/cli.py", line 81, in wrapper
    return f(*args, **kwargs)
  File "/home/ec2-user/venv/lib/python3.7/site-packages/airflow/bin/cli.py", line 867, in clear
    confirm_prompt=not args.no_confirm,
AttributeError: 'Namespace' object has no attribute 'no_confirm'

```

**Comment by tooptoop4** [comment]
command with --yes works after changing line 867 to confirm_prompt=not args.yes,

**Comment by ephraimbuddy** [comment]
Yeah, no_confirm is no longer in the command list for tasks clear. Do you want to contribute a fix that would make both `no_confirm` and `yes` to work or should I do it?

**Comment by tooptoop4** [comment]
can u pls @ephraimbuddy

**Comment by kaxil** [comment]
Closed by https://github.com/apache/airflow/pull/14188
