### ISSUE TITLE
S3PrefixSensor' object has no attribute 'bucket_key'

### ISSUE THREAD

**Issue by rcompton** [apache/airflow#142]
I'm testing to ensure that a directory exists. Whenever I try to use the S3PrefixSensor I get:

```
Traceback (most recent call last):
  File "/Users/rycpt/.virtualenvs/airflow0/bin/airflow", line 10, in <module>
    args.func(args)
  File "/Users/rycpt/.virtualenvs/airflow0/lib/python2.7/site-packages/airflow/bin/cli.py", line 87, in run
    dagbag = DagBag(subdir)
  File "/Users/rycpt/.virtualenvs/airflow0/lib/python2.7/site-packages/airflow/models.py", line 95, in __init__
    self.collect_dags(dag_folder)
  File "/Users/rycpt/.virtualenvs/airflow0/lib/python2.7/site-packages/airflow/models.py", line 219, in collect_dags
    self.process_file(dag_folder, only_if_updated=only_if_updated)
  File "/Users/rycpt/.virtualenvs/airflow0/lib/python2.7/site-packages/airflow/models.py", line 170, in process_file
   self.bag_dag(dag, parent_dag=dag, root_dag=dag)
  File  "/Users/rycpt/.virtualenvs/airflow0/lib/python2.7/site-packages/airflow/models.py", line 180, in bag_dag
dag.resolve_template_files()
  File "/Users/rycpt/.virtualenvs/airflow0/lib/python2.7/site-packages/airflow/models.py", line 1519, in resolve_template_files
t.resolve_template_files()
  File "/Users/rycpt/.virtualenvs/airflow0/lib/python2.7/site-packages/airflow/models.py", line 1195, in resolve_template_files
content = getattr(self, attr)
AttributeError: 'S3PrefixSensor' object has no attribute 'bucket_key'
```

Any ideas?

**Comment by mistercrunch** [comment]
@artwr ^^^^

**Comment by artwr** [comment]
@rcompton My bad, it was a copypasta issue. It should be fixed with https://github.com/airbnb/airflow/pull/143 once merged.

**Comment by rcompton** [comment]
Ok thanks. Closing this now that #143 exists.
