### ISSUE TITLE
scheduler fails at `line 1382, in _run_scheduler_loop`

### ISSUE THREAD

**Issue by dstandish** [apache/airflow#14324]
after upgrading to airflow 2.0, scheduler fails after 30 seconds (every time) without helpful traceback:

```
2021-02-19 13:53:06 Traceback (most recent call last):
2021-02-19 13:53:06 File "/home/airflow/.local/lib/python3.7/site-packages/airflow/jobs/scheduler_job.py", line 1280, in _execute
2021-02-19 13:53:06 self._run_scheduler_loop()
2021-02-19 13:53:06 File "/home/airflow/.local/lib/python3.7/site-packages/airflow/jobs/scheduler_job.py", line 1382, in _run_scheduler_loop
```

Interestingly this line should only be accessed when using sqlite but I am using mysql and I have verified the scheme is specified correctly.

did not have any issues in staging environments

**Comment by dstandish** [comment]
i think this might having something to do with bad choice of collation / encoding 

i was getting a lot of crashing of the scheduler ... it was pretty confusing...

but eventually i found that the server was using latin1 ... i converted all tables in db to use utf8mb4 and things have been a lot smoother

**Comment by vikramkoka** [comment]
Thank you @dstandish, should this be closed then based on your update?

**Comment by dstandish** [comment]
Yes will close, sorry.
