### ISSUE TITLE
error:instance detail  

### ISSUE THREAD

**Issue by wszxw233** [apache/airflow#14378]
Something bad has happened.
Please consider letting us know by creating a bug report using GitHub.

Python version: 3.6.8
Airflow version: 2.0.0
Node: cdh-node5.maycur.cc
-------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib64/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/airflow/www/auth.py", line 34, in decorated
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/airflow/www/decorators.py", line 60, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/airflow/www/views.py", line 1193, in task
    attr = getattr(ti, attr_name)
  File "/usr/local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 792, in previous_start_date_success
    return self.get_previous_start_date(state=State.SUCCESS)
  File "/usr/local/lib/python3.6/site-packages/airflow/utils/session.py", line 65, in wrapper
    return func(*args, session=session, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 776, in get_previous_start_date
    return prev_ti and pendulum.instance(prev_ti.start_date)
  File "/usr/local/lib64/python3.6/site-packages/pendulum/__init__.py", line 174, in instance
    raise ValueError("instance() only accepts datetime objects.")
ValueError: instance() only accepts datetime objects.

**Comment by SamWheating** [comment]
I believe this is fixed by https://github.com/apache/airflow/pull/14416

**Comment by kaxil** [comment]
Fixed by https://github.com/apache/airflow/pull/14416
