### ISSUE TITLE
what is registry_conn_id and from where I can get it in case of Azure container Registry.

### ISSUE THREAD

**Issue by ayushri05** [apache/airflow#14382]
Hi, My requirement is to run the Azure container Instance in my Azure Instance and run the container Image.
I user the AzureContainerInstanceOperator and the doccumentation from Astronomer for the same.
I created the Airflow connection with the type `Azure Container Instance` , client Id, Client secret, Tenant Id and subscription Id as given in the doc.
I have also added the parameter values in the DAG task 'run_container' like registry_conn_id = <registry Id>
resource_group= <Resource group Name>,
        name=<Container Insance Name>,
        image=<registry login server/image name>,
        region=<Resource group location from Azure>
        fail_if_exists=False

I refreshed the airflow, triggered the DAG. But my DAG is still showing as running. Nothing changed since triggered. I also don't see any task logs in Airflow.
Please suggest what can be the issue. If I did something wrong?

**Comment by ayushri05** [comment]
Hi, After sometime the task ran but failed due to ‘registry_conn_id’ isn’t defined.
Does anyone know, From where i can get the ‘registry_conn_id’ value for Azure container registry?

**Comment by ayushri05** [comment]
I got the Azure container registry Id with below cmd-
> az acr show -n <registry name> --query id

and put that in 'registry_conn_id' but it is giving below error and DAG failed -

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1284, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1314, in _execute_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/providers/microsoft/azure/operators/azure_container_instances.py", line 212, in execute
    registry_hook = AzureContainerRegistryHook(self.registry_conn_id)
  File "/usr/local/lib/python3.7/site-packages/airflow/providers/microsoft/azure/hooks/azure_container_registry.py", line 37, in __init__
    self.connection = self.get_conn()
  File "/usr/local/lib/python3.7/site-packages/airflow/providers/microsoft/azure/hooks/azure_container_registry.py", line 40, in get_conn
    conn = self.get_connection(self.conn_id)
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/base.py", line 63, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/connection.py", line 354, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")

**Comment by taffazzel** [comment]
Hi All, Unable to find out "registry_conn_id" on azure. Can anyone please help me ?

**Comment by eladkal** [comment]
`registry_conn_id` is the reference to the Airflow Connection that associates with `AzureContainerInstancesOperator`.
If you need additional troubleshooting help please open a [Stackoverflow question ](https://stackoverflow.com/)or ask in [GitHub Discussions](https://github.com/apache/airflow/discussions).
