### ISSUE TITLE
ValueError: Invalid timezone

### ISSUE THREAD

**Issue by ConstantinoSchillebeeckx** [apache/airflow#14419]
**Apache Airflow version**: 2.0.1

**Environment**:

- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): Debian
- **Kernel** (e.g. `uname -a`): Linux dd42f4ba1a9c 4.19.121-linuxkit #1 SMP Tue Dec 1 17:50:32 UTC 2020 x86_64 GNU/Linux
- **Install tools**: pip

**What happened**:

When I visit the webserver, after logging in I'm seeing:
```Ooops!
Something bad has happened.
Please consider letting us know by creating a bug report using GitHub.

Python version: 3.7.10
Airflow version: 2.0.1
Node: 0a5a9d14fa9f
-------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/airflow/www/auth.py", line 34, in decorated
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/www/views.py", line 600, in index
    tags_filter=arg_tags_filter,
  File "/usr/local/lib/python3.7/site-packages/airflow/www/views.py", line 400, in render_template
    **kwargs,
  File "/usr/local/lib/python3.7/site-packages/flask_appbuilder/baseviews.py", line 281, in render_template
    template, **dict(list(kwargs.items()) + list(self.extra_args.items()))
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/airflow/www/templates/airflow/dags.html", line 21, in top-level template code
    {% from 'appbuilder/loading_dots.html' import loading_dots %}
  File "/usr/local/lib/python3.7/site-packages/airflow/www/templates/airflow/main.html", line 20, in top-level template code
    {% extends 'appbuilder/baselayout.html' %}
  File "/usr/local/lib/python3.7/site-packages/flask_appbuilder/templates/appbuilder/baselayout.html", line 2, in top-level template code
    {% import 'appbuilder/baselib.html' as baselib %}
  File "/usr/local/lib/python3.7/site-packages/flask_appbuilder/templates/appbuilder/init.html", line 46, in top-level template code
    {% block body %}
  File "/usr/local/lib/python3.7/site-packages/flask_appbuilder/templates/appbuilder/baselayout.html", line 16, in block "body"
    {% block messages %}
  File "/usr/local/lib/python3.7/site-packages/airflow/www/templates/airflow/main.html", line 54, in block "messages"
    >{{ macros.datetime_diff_for_humans(scheduler_job.latest_heartbeat) }}</time>.
  File "/usr/local/lib/python3.7/site-packages/airflow/macros/__init__.py", line 83, in datetime_diff_for_humans
    return pendulum.instance(dt).diff_for_humans(since)
  File "/usr/local/lib/python3.7/site-packages/pendulum/datetime.py", line 824, in diff_for_humans
    other = self.now()
  File "/usr/local/lib/python3.7/site-packages/pendulum/datetime.py", line 106, in now
    return pendulum.now(tz)
  File "/usr/local/lib/python3.7/site-packages/pendulum/__init__.py", line 211, in now
    dt = _datetime.datetime.now(local_timezone())
  File "/usr/local/lib/python3.7/site-packages/pendulum/tz/__init__.py", line 60, in local_timezone
    return get_local_timezone()
  File "/usr/local/lib/python3.7/site-packages/pendulum/tz/local_timezone.py", line 35, in get_local_timezone
    tz = _get_system_timezone()
  File "/usr/local/lib/python3.7/site-packages/pendulum/tz/local_timezone.py", line 63, in _get_system_timezone
    return _get_unix_timezone()
  File "/usr/local/lib/python3.7/site-packages/pendulum/tz/local_timezone.py", line 178, in _get_unix_timezone
    return Timezone(etctz.replace(" ", "_"))
  File "/usr/local/lib/python3.7/site-packages/pendulum/tz/timezone.py", line 40, in __init__
    tz = read(name, extend=extended)
  File "/usr/local/lib/python3.7/site-packages/pendulum/tz/zoneinfo/__init__.py", line 9, in read
    return Reader(extend=extend).read_for(name)
  File "/usr/local/lib/python3.7/site-packages/pendulum/tz/zoneinfo/reader.py", line 50, in read_for
    file_path = pytzdata.tz_path(timezone)
  File "/usr/local/lib/python3.7/site-packages/pytzdata/__init__.py", line 63, in tz_path
    raise ValueError('Invalid timezone')
ValueError: Invalid timezone
```

**What you expected to happen**:

**How to reproduce it**:
 
ariflow.cfg
```
[core]

load_examples = False
load_default_connections = False
executor = CeleryExecutor

[scheduler]

min_file_process_interval = 60

[logging]

colored_console_log = False

[webserver]

expose_config = True
dag_default_view = graph
enable_proxy_fix = True

[celery]

worker_autoscale=6,6
```
pip freeze:
```
adal==1.2.6
aiohttp==3.7.3
alembic==1.5.5
amqp==2.6.1
ansiwrap==0.8.4
apache-airflow==2.0.1
apache-airflow-providers-amazon==1.1.0
apache-airflow-providers-celery==1.0.1
apache-airflow-providers-databricks==1.0.1
apache-airflow-providers-ftp==1.0.1
apache-airflow-providers-google==1.0.0
apache-airflow-providers-http==1.1.0
apache-airflow-providers-imap==1.0.1
apache-airflow-providers-jdbc==1.0.1
apache-airflow-providers-mongo==1.0.1
apache-airflow-providers-mysql==1.0.1
apache-airflow-providers-papermill==1.0.1
apache-airflow-providers-redis==1.0.1
apache-airflow-providers-salesforce==1.0.1
apache-airflow-providers-sftp==1.1.0
apache-airflow-providers-slack==2.0.0
apache-airflow-providers-snowflake==1.1.0
apache-airflow-providers-sqlite==1.0.1
apache-airflow-providers-ssh==1.1.0
apache-airflow-providers-zendesk==1.0.1
apispec==3.3.2
appdirs==1.4.4
argcomplete==1.12.2
asn1crypto==1.4.0
async-generator==1.10
async-timeout==3.0.1
attrs==20.3.0
Authlib==0.15.3
avro-python3==1.10.0
azure-common==1.1.26
azure-core==1.11.0
azure-datalake-store==0.0.51
azure-storage-blob==12.7.1
azure-storage-common==2.1.0
Babel==2.9.0
backcall==0.2.0
bcrypt==3.2.0
billiard==3.6.3.0
black==20.8b1
boto3==1.15.18
botocore==1.18.18
cached-property==1.5.2
cachetools==4.2.1
cattrs==1.2.0
celery==4.4.7
certifi==2020.12.5
cffi==1.14.5
chardet==3.0.4
click==7.1.2
clickclick==20.10.2
colorama==0.4.4
colorlog==4.7.2
commonmark==0.9.1
connexion==2.7.0
croniter==0.3.37
cryptography==3.4.6
cycler==0.10.0
databricks-connect==7.3.8
decorator==4.4.2
defusedxml==0.6.0
dill==0.3.3
dnspython==1.16.0
docutils==0.16
email-validator==1.1.2
entrypoints==0.3
Flask==1.1.2
Flask-AppBuilder==3.1.1
Flask-Babel==1.0.0
Flask-Bcrypt==0.7.1
Flask-Caching==1.9.0
Flask-JWT-Extended==3.25.1
Flask-Login==0.4.1
Flask-OpenID==1.2.5
Flask-SQLAlchemy==2.4.4
Flask-WTF==0.14.3
flower==0.9.7
fsspec==0.8.5
gcsfs==0.7.2
google-ads==7.0.0
google-api-core==1.26.0
google-api-python-client==1.12.8
google-auth==1.27.0
google-auth-httplib2==0.0.4
google-auth-oauthlib==0.4.2
google-cloud-automl==1.0.1
google-cloud-bigquery==1.27.2
google-cloud-bigquery-datatransfer==1.1.1
google-cloud-bigquery-storage==1.1.0
google-cloud-bigtable==1.7.0
google-cloud-container==1.0.1
google-cloud-core==1.6.0
google-cloud-datacatalog==0.7.0
google-cloud-dataproc==1.1.1
google-cloud-dlp==1.0.0
google-cloud-kms==1.4.0
google-cloud-language==1.3.0
google-cloud-logging==1.15.1
google-cloud-memcache==0.3.0
google-cloud-monitoring==1.1.0
google-cloud-os-login==1.0.0
google-cloud-pubsub==1.7.0
google-cloud-redis==1.0.0
google-cloud-secret-manager==1.0.0
google-cloud-spanner==1.19.1
google-cloud-speech==1.3.2
google-cloud-storage==1.36.0
google-cloud-tasks==1.5.0
google-cloud-texttospeech==1.0.1
google-cloud-translate==1.7.0
google-cloud-videointelligence==1.16.1
google-cloud-vision==1.0.0
google-crc32c==1.1.2
google-resumable-media==1.2.0
googleapis-common-protos==1.52.0
graphviz==0.16
grpc-google-iam-v1==0.12.3
grpcio==1.35.0
grpcio-gcp==0.2.2
gunicorn==19.10.0
httplib2==0.19.0
humanize==3.2.0
idna==2.10
importlib-metadata==1.7.0
importlib-resources==1.5.0
inflection==0.5.1
iniconfig==1.1.1
ipykernel==5.4.3
ipython==7.20.0
ipython-genutils==0.2.0
iso8601==0.1.14
isodate==0.6.0
itsdangerous==1.1.0
JayDeBeApi==1.2.3
jedi==0.18.0
Jinja2==2.11.3
jmespath==0.10.0
joblib==1.0.1
JPype1==1.2.1
json-merge-patch==0.2
jsonschema==3.2.0
jupyter-client==6.1.11
jupyter-core==4.7.1
kiwisolver==1.3.1
kombu==4.6.11
lazy-object-proxy==1.5.2
lockfile==0.12.2
Mako==1.1.4
Markdown==3.3.3
MarkupSafe==1.1.1
marshmallow==3.10.0
marshmallow-enum==1.5.1
marshmallow-oneofschema==2.1.0
marshmallow-sqlalchemy==0.23.1
matplotlib==3.3.4
msrest==0.6.21
multidict==5.1.0
mypy-extensions==0.4.3
mysql-connector-python==8.0.22
mysqlclient==1.3.14
natsort==7.1.1
nbclient==0.5.2
nbformat==5.1.2
nest-asyncio==1.5.1
nteract-scrapbook==0.4.2
numpy==1.20.1
oauthlib==3.1.0
openapi-spec-validator==0.2.9
oscrypto==1.2.1
packaging==20.9
pandas==1.2.2
pandas-gbq==0.14.1
papermill==2.3.2
paramiko==2.7.2
parso==0.8.1
pathspec==0.8.1
pendulum==2.1.2
pexpect==4.8.0
pickleshare==0.7.5
Pillow==8.1.0
prison==0.1.3
prometheus-client==0.8.0
prompt-toolkit==3.0.16
proto-plus==1.13.0
protobuf==3.15.1
psutil==5.8.0
ptyprocess==0.7.0
py4j==0.10.9
pyarrow==0.17.1
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.20
pycryptodomex==3.10.1
pydata-google-auth==1.1.0
Pygments==2.8.0
PyJWT==1.7.1
pymongo==3.11.3
PyNaCl==1.4.0
pyOpenSSL==19.1.0
pyparsing==2.4.7
pyrsistent==0.17.3
pysftp==0.2.9
python-daemon==2.3.0
python-dateutil==2.8.1
python-editor==1.0.4
python-nvd3==0.15.0
python-slugify==4.0.1
python3-openid==3.2.0
pytz==2020.5
pytzdata==2020.1
PyYAML==5.4.1
pyzmq==22.0.3
redis==3.5.3
regex==2020.11.13
requests==2.25.1
requests-oauthlib==1.3.0
rich==9.2.0
rsa==4.7.1
s3transfer==0.3.4
scikit-learn==0.24.1
scipy==1.6.1
setproctitle==1.2.2
simple-salesforce==1.10.1
six==1.15.0
slack-sdk==3.4.0
slackclient==2.9.3
snowflake-connector-python==2.3.10
snowflake-sqlalchemy==1.2.4
SQLAlchemy==1.3.23
SQLAlchemy-JSONField==1.0.0
SQLAlchemy-Utils==0.36.8
sqlparse==0.4.1
sshtunnel==0.1.5
swagger-ui-bundle==0.0.8
tableauserverclient==0.15.0
tabulate==0.8.9
tenacity==6.2.0
termcolor==1.1.0
text-unidecode==1.3
textwrap3==0.9.2
threadpoolctl==2.1.0
toml==0.10.2
tornado==6.1
tqdm==4.57.0
traitlets==5.0.5
typed-ast==1.4.2
typing-extensions==3.7.4.3
unicodecsv==0.14.1
uritemplate==3.0.1
urllib3==1.25.11
vine==1.3.0
watchtower==0.7.3
wcwidth==0.2.5
Werkzeug==1.0.1
WTForms==2.3.3
yarl==1.6.3
zdesk==2.7.1
zipp==3.4.0
```

**Comment by ConstantinoSchillebeeckx** [comment]
The issue was in my Dockerfile, adding the following resolved the issue:
```
ENV TZ=America/Los_Angeles
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
```
