### ISSUE TITLE
AttributeError: 'DatabaseBackend' object has no attribute 'task_cls'

### ISSUE THREAD

**Issue by nicolasdonoso** [apache/airflow#14586]
**Apache Airflow version**: 2.0.1

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): 1.18.15

**Environment**:

- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): ubuntu 18.04
- **Kernel** (e.g. `uname -a`): Linux mlb-airflow-infra-workers-75f589bcd9-wtls8 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1 (2019-04-12) x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**:
- **Others**:

**What happened**:

Scheduler is constantly restarting due to this error:
```
[2021-03-03 17:31:19,393] {scheduler_job.py:1298} ERROR - Exception when executing SchedulerJob._run_scheduler_loop
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/airflow/jobs/scheduler_job.py", line 1280, in _execute
    self._run_scheduler_loop()
  File "/usr/local/lib/python3.6/dist-packages/airflow/jobs/scheduler_job.py", line 1384, in _run_scheduler_loop
    self.executor.heartbeat()
  File "/usr/local/lib/python3.6/dist-packages/airflow/executors/base_executor.py", line 162, in heartbeat
    self.sync()
  File "/usr/local/lib/python3.6/dist-packages/airflow/executors/celery_executor.py", line 340, in sync
    self.update_all_task_states()
  File "/usr/local/lib/python3.6/dist-packages/airflow/executors/celery_executor.py", line 399, in update_all_task_states
    state_and_info_by_celery_task_id = self.bulk_state_fetcher.get_many(self.tasks.values())
  File "/usr/local/lib/python3.6/dist-packages/airflow/executors/celery_executor.py", line 552, in get_many
    result = self._get_many_from_db_backend(async_results)
  File "/usr/local/lib/python3.6/dist-packages/airflow/executors/celery_executor.py", line 570, in _get_many_from_db_backend
    task_cls = app.backend.task_cls
AttributeError: 'DatabaseBackend' object has no attribute 'task_cls'
[2021-03-03 17:31:20,396] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 3852
[2021-03-03 17:31:20,529] {process_utils.py:66} INFO - Process psutil.Process(pid=3996, status='terminated', started='17:31:19') (3996) terminated with exit code None
[2021-03-03 17:31:20,533] {process_utils.py:66} INFO - Process psutil.Process(pid=3997, status='terminated', started='17:31:19') (3997) terminated with exit code None
[2021-03-03 17:31:20,533] {process_utils.py:206} INFO - Waiting up to 5 seconds for processes to exit...
[2021-03-03 17:31:20,540] {process_utils.py:66} INFO - Process psutil.Process(pid=3852, status='terminated', exitcode=0, started='17:31:13') (3852) terminated with exit code 0
[2021-03-03 17:31:20,540] {scheduler_job.py:1301} INFO - Exited execute loop
```

**What you expected to happen**: Scheduler running

**How to reproduce it**:

Install airflow  2.0.1 in an ubuntu 18.04 instance:

`pip install apache-airflow[celery,postgres,s3,crypto,jdbc,google_auth,redis,slack,ssh,sentry,kubernetes,statsd]==2.0.1`

Use the following variables:
```
AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:<pwd>@<DB>:<port>/airflow
AIRFLOW__CORE__DEFAULT_TIMEZONE=<TZ>
AIRFLOW__CORE__LOAD_DEFAULTS=false
AIRFLOW__CELERY__BROKER_URL=sqs://
AIRFLOW__CELERY__DEFAULT_QUEUE=<queue>
AIRFLOW__CORE__REMOTE_BASE_LOG_FOLDER=s3://<bucket>/<prefix>/
AIRFLOW__CORE__LOAD_EXAMPLES=false
AIRFLOW__CORE__REMOTE_LOGGING=True
AIRFLOW__CORE__FERNET_KEY=<fernet_key>
AIRFLOW__CORE__EXECUTOR=CeleryExecutor
AIRFLOW__CELERY__BROKER_TRANSPORT_OPTIONS__REGION=<region>
AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://airflow:<pwd>@<DB>:<port>/airflow
```

Start airflow components (webserver, celery workers, scheduler). With no DAGs running everything is stable and not failing but once a DAGs start running the scheduler starts getting the error and from then it constantly reboots until crash.

**Anything else we need to know**:

This happens every time and the scheduler keeps restarting

**Comment by mik-laj** [comment]
Can you provide the output of the commands below?
```
python -c "from airflow.executors.celery_executor import app; print(type(app.backend))"
<class 'celery.backends.database.DatabaseBackend'>
```
```
pip freeze
```

I suspect you are using an unsupported version of Celery. See: https://github.com/apache/airflow/issues/11301

I recommend that you use constraints during installation. See: http://airflow.apache.org/docs/apache-airflow/stable/installation.html#constraints-files
