### ISSUE TITLE
Recent release of Flask-SQLAlchemy==2.5.0 breaks py27 compatibility

### ISSUE THREAD

**Issue by POD666** [apache/airflow#14884]
The recent release of Flask-SQLAlchemy==2.5.0 breaks py27 compatibility.
It will be fixed but It's suggested to pin Flask-SQLAlchemy version by the maintainer.
**Apache Airflow version**: 1.10.9

**What happened**:

```
Traceback (most recent call last):
  ...
  from airflow.bin.cli import CLIFactory
  File "..py27/lib/python2.7/site-packages/airflow/bin/cli.py", line 71, in <module>
    from airflow.www_rbac.app import cached_app as cached_app_rbac
  File "../py27/lib/python2.7/site-packages/airflow/www_rbac/app.py", line 27, in <module>
    from flask_appbuilder import AppBuilder, SQLA
  File "../py27/lib/python2.7/site-packages/flask_appbuilder/__init__.py", line 4, in <module>
    from .models.sqla import Model, Base, SQLA
  File "../py27/lib/python2.7/site-packages/flask_appbuilder/models/sqla/__init__.py", line 5, in <module>
    from flask_sqlalchemy import SQLAlchemy, DefaultMeta, _QueryProperty
  File "../py27/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 39, in <module>
    from threading import get_ident as _ident_func
ImportError: cannot import name get_ident
```

**Anything else we need to know**:

https://github.com/pallets/flask-sqlalchemy/issues/936

**Comment by potiuk** [comment]
We are not pinning our dependencies. Reasons are explained in http://airflow.apache.org/docs/apache-airflow/stable/installation.html#constraints-files

Instead of pinning, you should use constraints to install Airflow; http://airflow.apache.org/docs/apache-airflow/stable/installation.html#installation-script . This is the only recommended way of installing Airflow that is guaranteed to work without manualle

In https://raw.githubusercontent.com/apache/airflow/constraints-1.10.9/constraints-2.7.txt you can see"

`Flask-SQLAlchemy==2.4.1`

So all is good.
