### ISSUE TITLE
Execution failed on sql ' SELECT * FROM ( SELECT * FROM experiments ) qry LIMIT 100000 ': (0, '')

### ISSUE THREAD

**Issue by griffinqiu** [apache/airflow#150]
I got the following error when I exec a mysql_hook.

```
[2015-07-17 17:20:10,410] {models.py:839} ERROR - (0, '')
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/airflow/models.py", line 821, in run
    task_copy.execute(context=context)
  File "/usr/local/lib/python2.7/site-packages/airflow/operators/python_operator.py", line 50, in execute
    return_value = self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/kpiserv/airflow/dags/calculate_abtesting.py", line 209, in bayesian_data_import
    ''')
  File "/usr/local/lib/python2.7/site-packages/airflow/hooks/mysql_hook.py", line 37, in get_records
    cur.execute(sql)
  File "/usr/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 209, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
InterfaceError: (0, '')
```

I tried the Ad Hoc Query with this sql  'SELECT \* FROM experiments '. but I got the error
Execution failed on sql ' SELECT \* FROM ( SELECT \* FROM experiments ) qry LIMIT 100000 ': (0, '')

strange

**Comment by mistercrunch** [comment]
The "Ad Hoc Query" tool wraps your query as a subquery with a 100k row limit to avoid taking down your browser. But it seems like your stack trace show an `InterfaceError` which seem related to how you connect to MySql. 

The hook does very standard things using the normal dbapi calls. I'd review your connection settings, default schema, ...
