### ISSUE TITLE
Running "upgrade_check" command from gcloud fails

### ISSUE THREAD

**Issue by kosteev** [apache/airflow#15003]
**Apache Airflow version**: 1.10.15

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}

**Environment**: GCP Composer environment with Airflow 1.10.15

**What happened**:
Running gcloud command to execute "airflow upgrade_check" fails.
```
gcloud alpha composer environments run af15-mar-24 upgrade_check --location us-central1
```

```
[2021-03-25 10:59:21,168] {configuration.py:732} INFO - Reading the config from /etc/airflow/airflow.cfg
[2021-03-25 10:59:21,315] {configuration.py:732} INFO - Reading the config from /etc/airflow/airflow.cfg

 STATUS 

Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/usr/local/lib/airflow/airflow/bin/airflow", line 37, in <module>
    args.func(args)
  File "/usr/local/lib/airflow/airflow/upgrade/checker.py", line 118, in run
    all_rule_statuses = check_upgrade(formatter, rules)
  File "/usr/local/lib/airflow/airflow/upgrade/checker.py", line 40, in check_upgrade
    formatter.on_next_rule_status(rule_status)
  File "/usr/local/lib/airflow/airflow/upgrade/formatters.py", line 109, in on_next_rule_status
    print(status_line_fmt.format(rule_status.rule.title, status))
ValueError: Sign not allowed in string format specifier
```

**Comment by eladkal** [comment]
fixed in https://github.com/apache/airflow/pull/14977
