### ISSUE TITLE
Executing VACUUM with PostgresOperator

### ISSUE THREAD

**Issue by rrbarbosa** [apache/airflow#1501]
Dear Airflow Maintainers,
### Environment
- Airflow version: _v1.7.0_
- Airflow components: _PostgresOperator_
- Python Version: _Python 3.5.1_
- Operating System: _15.4.0 Darwin_
### Description of Issue

I am trying to execute a `VACUUM` command as part of DAG with the `PostgresOperator`, which fails with the following error:

```
[2016-05-14 16:14:01,849] {__init__.py:36} INFO - Using executor SequentialExecutor
Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 15, in <module>
    args.func(args)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/airflow/bin/cli.py", line 203, in run
    pool=args.pool,
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/airflow/models.py", line 1067, in run
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.5/site-packages/airflow/operators/postgres_operator.py", line 39, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/airflow/hooks/dbapi_hook.py", line 109, in run
    cur.execute(s)
psycopg2.InternalError: VACUUM cannot run inside a transaction block
```

I could create a small python script that performs the operation, as explained in [this stackoverflow entry](http://stackoverflow.com/questions/1017463/postgresql-how-to-run-vacuum-from-code-outside-transaction-block). However, I would like to know first if the `VACUUM` command should be supported by the `PostgresOperator`.
### Reproducing the Issue

The operator can be declared as follows:

```
conn = ('postgres_default')
t4 = PostgresOperator(
    task_id='vacuum',
    postgres_conn_id=conn,
    sql=("VACUUM public.table"),
    dag=dag
    )
```

**Comment by slvwolf** [comment]
Using `autocommit=True` should solve the issue

**Comment by r39132** [comment]
@slvwolf That's correct... and good catch. 

@rrbarbosa If you haven't already, please create a JIRA for this -- we don't use Github Issues anymore .. refer to https://github.com/apache/incubator-airflow/issues/1445

Once you create the JIRA, you can ping me (to write a fix for this) or either you or @slvwolf can submit a PR for it.

**Comment by rrbarbosa** [comment]
@r39132 https://issues.apache.org/jira/browse/AIRFLOW-139

I don't see what the PR would look like though. If I understand @slvwolf correctly, I should only add a new argument when creating the operator.
