### ISSUE TITLE
 lazy load operation of attribute 'view_menu' cannot proceed

### ISSUE THREAD

**Issue by yacine-del** [apache/airflow#15058]
Hello !

I encountered the problem below when connecting airflow

sqlalchemy.orm.exc.DetachedInstanceError: Parent instance <PermissionView at 0x7fd24506e630> is not bound to a Session; lazy load operation of attribute 'view_menu' cannot proceed (Background on this error at: http://sqlalche.me/e/14/bhk3)

I need for help Tank you

**Comment by yacine-del** [comment]
-------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/dist-packages/airflow/www/auth.py", line 34, in decorated
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/airflow/www/views.py", line 532, in index
    user_permissions = current_app.appbuilder.sm.get_current_user_permissions()
  File "/usr/local/lib/python3.6/dist-packages/airflow/www/security.py", line 229, in get_current_user_permissions
    {(perm_view.permission.name, perm_view.view_menu.name) for perm_view in role.permissions}
  File "/usr/local/lib/python3.6/dist-packages/airflow/www/security.py", line 229, in <setcomp>
    {(perm_view.permission.name, perm_view.view_menu.name) for perm_view in role.permissions}
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/attributes.py", line 449, in __get__
    return self.impl.get(state, dict_)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/attributes.py", line 893, in get
    value = self.callable_(state, passive)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/strategies.py", line 831, in _load_for_state
    % (orm_util.state_str(state), self.key)
sqlalchemy.orm.exc.DetachedInstanceError: Parent instance <PermissionView at 0x7fd24506e630> is not bound to a Session; lazy load operation of attribute 'view_menu' cannot proceed (Background on this error at: http://sqlalche.me/e/14/bhk3)

**Comment by mik-laj** [comment]
Do you use constraints files to install Airflow?

**Comment by parkyo** [comment]
I found this issue on ovio.org and would love to contribute!

**Comment by mik-laj** [comment]
@yacine-del  Can you tell a little more about this error? What are the steps to reproduce this error? what version of Airflow do you have? What version of SQLAlchemy do you have?

@parkyo Welcome!
