### ISSUE TITLE
airflow scheduler -p command not working in airflow 2.0.1

### ISSUE THREAD

**Issue by Vineet-Sharma29** [apache/airflow#15131]
**Apache Airflow version**:
2.0.1

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**: 4GB RAM, Processor - Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
- **OS** (e.g. from /etc/os-release): 18.04.5 LTS (Bionic Beaver)
- **Kernel** (e.g. `uname -a`): Linux 4.15.0-136-generic
- **Install tools**: bare metal installation as per commands given [here](https://airflow.apache.org/docs/apache-airflow/stable/installation.html)

**What happened**:

On running `airflow scheduler -p` got following error:-
```
Traceback (most recent call last):
  File "/home/vineet/Documents/projects/venv/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/home/vineet/Documents/projects/venv/lib/python3.6/site-packages/airflow/__main__.py", line 40, in main
    args.func(args)
  File "/home/vineet/Documents/projects/venv/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/vineet/Documents/projects/venv/lib/python3.6/site-packages/airflow/utils/cli.py", line 86, in wrapper
    metrics = _build_metrics(f.__name__, args[0])
  File "/home/vineet/Documents/projects/venv/lib/python3.6/site-packages/airflow/utils/cli.py", line 118, in _build_metrics
    full_command[idx + 1] = "*" * 8
IndexError: list assignment index out of range
```
As per docs, `-p` flag is a valid flag and gives correct result for `airflow scheduler --do-pickle`

**How to reproduce it**:
Install `airflow` 2.0.1 and run `airflow scheduler -p`

**Comment by XD-DENG** [comment]
I can confirm this issue.

That's because `_build_metrics()` checks the arg, and tries to mask value for password. When it sees `-p`, it assumes there is another value following, which is password (that's why there is `idx + 1`).

This assumption fails in `scheduler` scenario though, because it can simply be `airflow scheduler -p`.
