### ISSUE TITLE
Crash when looking at the individually triggered tasks

### ISSUE THREAD

**Issue by fortworthrisk** [apache/airflow#15244]
Browse->DAG Runs-> Select a task that was triggered individually, not as one DAG.

Instead of showing the tree of the dag that it was part of -> getting this error.

Something bad has happened.
Please consider letting us know by creating a bug report using GitHub.

Python version: 3.8.0
Airflow version: 2.0.1
Node: airflow2-master
-------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/airflow/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/airflow/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/airflow/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/airflow/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/airflow/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/airflow/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/airflow/venv/lib/python3.8/site-packages/airflow/www/auth.py", line 34, in decorated
    return func(*args, **kwargs)
  File "/home/airflow/venv/lib/python3.8/site-packages/airflow/www/decorators.py", line 97, in view_func
    return f(*args, **kwargs)
  File "/home/airflow/venv/lib/python3.8/site-packages/airflow/www/decorators.py", line 60, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/venv/lib/python3.8/site-packages/airflow/utils/session.py", line 65, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/venv/lib/python3.8/site-packages/airflow/www/views.py", line 2026, in graph
    dag = current_app.dag_bag.get_dag(dag_id)
  File "/home/airflow/venv/lib/python3.8/site-packages/airflow/utils/session.py", line 65, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 178, in get_dag
    self._add_dag_from_db(dag_id=dag_id, session=session)
  File "/home/airflow/venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 234, in _add_dag_from_db
    raise SerializedDagNotFound(f"DAG '{dag_id}' not found in serialized_dag table")
airflow.exceptions.SerializedDagNotFound: DAG 'None' not found in serialized_dag table

**Comment by eladkal** [comment]
>Browse->DAG Runs-> Select a task that was triggered individually, not as one DAG.

Can you please explain further? An actual example with DAG code and maybe a gif showing the issue might help here.
