### ISSUE TITLE
Cannot delete DAG

### ISSUE THREAD

**Issue by maxcountryman** [apache/airflow#15709]
I see this exception when trying to delete a removed DAG:

```
Python version: 3.9.5
Airflow version: 2.0.1
Node: ip-10-0-10-118.us-west-2.compute.internal
-------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.9/site-packages/airflow/www/auth.py", line 34, in decorated
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/www/decorators.py", line 60, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/www/views.py", line 1393, in delete
    delete_dag.delete_dag(dag_id)
  File "/usr/local/lib/python3.9/site-packages/airflow/utils/session.py", line 65, in wrapper
    return func(*args, session=session, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/api/common/experimental/delete_dag.py", line 54, in delete_dag
    for model in models.base.Base._decl_class_registry.values():  # noqa pylint: disable=protected-access
AttributeError: type object 'Base' has no attribute '_decl_class_registry'
```

**Comment by SamWheating** [comment]
Could you confirm which version of SQLAlchemy you're using? I believe a bunch of things were changed with declarative classes in the 1.4 release of SQLAlchemy. The latest version of Airflow should be installed with `sqlalchemy>=1.3.18, <1.4` [(source)](https://github.com/apache/airflow/blob/master/setup.cfg#L142)

This restriction was only added after the 2.0.1 release so I can totally see how Airflow 2.0.1 might install a bad version by default. 

However, it looks like this has been fixed in the constraints. Could you please try installing with constraints? [Instructions here](https://airflow.apache.org/docs/apache-airflow/stable/installation.html#constraints-files)
