### ISSUE TITLE
`$ airflow connections import` fails with `AttributeError`

### ISSUE THREAD

**Issue by MatrixManAtYrService** [apache/airflow#15931]
Apache Airflow version

6f8c204

Environment

OS (e.g. from /etc/os-release): Mac OS 11.3
Kernel: Darwin Kernel Version 20.4.0
Install tools: pip install -e .

**What happened**:

Tried to import valid connection json via the cli.  Got an error:

```
❯ echo '{"sqlite_conn_id": {
    "conn_type": "sqlite",
    "description": "",
    "host": "localhost",
    "login": "",
    "password": null,
    "schema": "/usr/local/airflow/test.db",
    "port": null,
    "extra": ""
  }}' | jq . > connections.json

❯ airflow connections import connections.json
Traceback (most recent call last):
  File "/Users/matt/src/airflow/venv/bin/airflow", line 33, in <module>
    sys.exit(load_entry_point('apache-airflow', 'console_scripts', 'airflow')())
  File "/Users/matt/src/airflow/airflow/__main__.py", line 40, in main
    args.func(args)
  File "/Users/matt/src/airflow/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/Users/matt/src/airflow/airflow/utils/cli.py", line 91, in wrapper
    return f(*args, **kwargs)
  File "/Users/matt/src/airflow/airflow/cli/commands/connection_command.py", line 244, in connections_import
    _import_helper(args.file)
  File "/Users/matt/src/airflow/airflow/cli/commands/connection_command.py", line 272, in _import_helper
    key: value for key, value in conn_values.items() if key in allowed_fields
AttributeError: 'Connection' object has no attribute 'items'
```

Several of the tests assume that `load_connections_dict` returns a dict of dicts
https://github.com/apache/airflow/blob/6f8c204b21d6c01a192bda524db72517d41bf6e9/tests/cli/commands/test_connection_command.py#L790

Actually, `load_connections_dict` returns a dict of `Connection`s
https://github.com/apache/airflow/blob/6f8c204b21d6c01a192bda524db72517d41bf6e9/airflow/secrets/local_filesystem.py#L278

When we call `.items()` on the `Connection`, it fails.

**What you expected to happen**:

The import is sucessful.

**How to reproduce it**:

See commands above.

**Anything else we need to know**:

This commit fixes it (I think): https://github.com/MatrixManAtYrService/airflow/commit/51590596f96f079f166d6949a520c1b0a53f475a

I started making a PR, but while trying to make the tests pass I started to worry that I was on the wrong path, so I made an issue instead.

**Comment by ephraimbuddy** [comment]
I was not able to reproduce this. Can you check the content inside the connections.json? I'm suspecting that it has errors.

This worked for me:

```zsh
echo '{"sqlite_conn_id": {
    "conn_type": "sqlite",
    "description": "",
    "host": "localhost",
    "login": "",
    "password": null,
    "schema": "/usr/local/airflow/test.db",
    "port": null,
    "extra": ""
  }}'  > connections.json

airflow connections import connections.json

```

**Comment by MatrixManAtYrService** [comment]
Hmm, maybe there's something different about our environments.  I can indeed replicate it with that json.

To protect against environmental differences, here's a session that does it in docker:
```
$ docker run -it --entrypoint bash "apache/airflow@sha256:305f237eb0ce38ed4f707ba1d08353111d0f36c36fab24661483cd365af1278d"
airflow@7b338db5bd06:/opt/airflow$ airflow version
2.1.0
airflow@7b338db5bd06:/opt/airflow$ airflow db init
...
Initialization done
airflow@7b338db5bd06:/opt/airflow$ echo '{"sqlite_conn_id": {
>     "conn_type": "sqlite",
>     "description": "",
>     "host": "localhost",
>     "login": "",
>     "password": null,
>     "schema": "/usr/local/airflow/test.db",
>     "port": null,
>     "extra": ""
>   }}'  > connections.json
airflow@7b338db5bd06:/opt/airflow$ cat connections.json
{"sqlite_conn_id": {
    "conn_type": "sqlite",
    "description": "",
    "host": "localhost",
    "login": "",
    "password": null,
    "schema": "/usr/local/airflow/test.db",
    "port": null,
    "extra": ""
  }}
airflow@7b338db5bd06:/opt/airflow$ airflow connections import connections.json
Traceback (most recent call last):
  File "/home/airflow/.local/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/__main__.py", line 40, in main
    args.func(args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/cli.py", line 91, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/connection_command.py", line 244, in connections_import
    _import_helper(args.file)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/connection_command.py", line 272, in _import_helper
    key: value for key, value in conn_values.items() if key in allowed_fields
AttributeError: 'Connection' object has no attribute 'items'
```

And an asciicast: https://asciinema.org/a/86Y40kiOwPXcF4jKw3n59FA3Z?theme=solarized-dark&speed=1.5

(I used `305f...` because it's the current digest of `apache/airflow:latest-python3.8`).

@ephraimbuddy  Do you get something different when you run it in docker like that?

**Comment by MatrixManAtYrService** [comment]
This was a duplicate of https://github.com/apache/airflow/pull/15425

It's fixed now.
