### ISSUE TITLE
Spark submit operator now broken

### ISSUE THREAD

**Issue by motherhubbard** [apache/airflow#16140]
**Apache Airflow version**:
2.1.0

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):
N/A

**Environment**:

3.10.0-1062.1.2.el7.x86_64 #1 SMP Mon Sep 30 14:19:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**What happened**:

Nasty stack trace:

```[ESC[34m2021-05-28 14:30:03,379ESC[0m] {ESC[34mdagbag.py:ESC[0m320} ERRORESC[0m - Failed to import: /airflow/dags/dag1.pyESC[0m
Traceback (most recent call last):
  File "/airflow_venv/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/airflow/dags/dag1.py", line 3, in <module>
    from airflow.contrib.operators.spark_submit_operator import SparkSubmitOperator
  File "/airflow_venv/lib/python3.6/site-packages/airflow/contrib/operators/spark_submit_operator.py", line 23, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator  # noqa
  File "/airflow_venv/lib/python3.6/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 28, in <module>
    class SparkSubmitOperator(BaseOperator):
  File "/airflow_venv/lib/python3.6/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 149, in SparkSubmitOperator
    ) -> None:
  File "/airflow_venv/lib/python3.6/site-packages/airflow/utils/decorators.py", line 44, in apply_defaults
    stacklevel=3,
  File "/python-3.6.4/lib/python3.6/warnings.py", line 99, in _showwarnmsg
    msg.file, msg.line)
  File "/airflow_venv/lib/python3.6/site-packages/airflow/settings.py", line 115, in custom_show_warning
    write_console.print(msg, soft_wrap=True)
  File "/airflow_venv/lib/python3.6/site-packages/rich/console.py", line 1130, in print
    self._buffer.extend(new_segments)
  File "/airflow_venv/lib/python3.6/site-packages/rich/console.py", line 553, in __exit__
    self._exit_buffer()
  File "/airflow_venv/lib/python3.6/site-packages/rich/console.py", line 531, in _exit_buffer
    self._check_buffer()
  File "/airflow_venv/lib/python3.6/site-packages/rich/console.py", line 1262, in _check_buffer
    self.file.flush()
OSError: [Errno 5] Input/output error
````

**What you expected to happen**:

SparkSubmitOperator worked in 2.0.2 but not in 2.1.0. I suspect its related to the deprecation of apply_defaults.

```
from datetime import datetime, timedelta
from airflow import DAG
from airflow.contrib.operators.spark_submit_operator import SparkSubmitOperator
from airflow.models import Variable

from airflow.hooks.base_hook import BaseHook

default_args = {
    'owner': 'me',
    'depends_on_past': False,
    'start_date': datetime(2021, 5, 25),
    'email': ['me@a.com'],
    'email_on_failure': False,
    'email_on_retry': False,
    'retries': 0,
    'retry_delay': timedelta(minutes=5)
}

dag = DAG(dag_id='pi',
          concurrency=1,
          default_args=default_args,
          catchup=True,
          schedule_interval="*/5 * * * *")

rollup_jobby=  SparkSubmitOperator(task_id='pi_task',
conn_id='spark',
application=f'/home/me/pi.py',
executor_cores=4,
num_executors=4,
executor_memory='1g',
driver_memory='1g',
name='pi',
execution_timeout=timedelta(minutes=60),
dag=dag
)
```

**Comment by motherhubbard** [comment]
commenting out     @apply_defaults on line 118 of /airflow/providers/apache/spark/operators/spark_submit.py fixes this but i i wouldt not expect this to have broken

**Comment by motherhubbard** [comment]
This same issue happens in the slack-operator also.

**Comment by mik-laj** [comment]
CC: @turbaszek

**Comment by mik-laj** [comment]
The show_warnings function should ignore OSError errors, but our implementation does not.
Original implementation:
https://github.com/python/cpython/blob/9bcb76c24f6d3f01e596a439c1521f9099e3fe80/Lib/warnings.py#L20-L33
Our implementation:
https://github.com/apache/airflow/blob/231d104e37da57aa097e5f726fe6d3031ad04c52/airflow/settings.py#L107-L115

**Comment by yathit** [comment]
I tested in Airflow 2.3.0.dev0 using `airflow.providers.apache.spark.operators.spark_submit.SparkSubmitOperator` and no longer reproduced the issue. 

```python

import datetime
import unittest
from airflow.models.dag import DAG
from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
from airflow.utils import timezone
from tests.test_utils.config import conf_vars

DEFAULT_DATE = timezone.datetime(2016, 1, 1)
END_DATE = timezone.datetime(2016, 1, 2)
INTERVAL = datetime.timedelta(minutes=5)
FROZEN_NOW = timezone.datetime(2016, 1, 2, 12, 1, 1)


class TestSparkSubmitOperator(unittest.TestCase):
    def setUp(self):
        super().setUp()
        default_args = {
            'owner': 'me',
            'depends_on_past': False,
            'start_date': DEFAULT_DATE,
            'email': ['me@a.com'],
            'email_on_failure': False,
            'email_on_retry': False,
            'retries': 0,
            'retry_delay': datetime.timedelta(minutes=5)
        }
        self.dag = DAG(
            dag_id='pi',
            concurrency=1,
            default_args=default_args,
            catchup=True,
            schedule_interval=INTERVAL
        )
        self.addCleanup(self.dag.clear)

    def _run_as_operator(self, **kwargs):
        task = SparkSubmitOperator(
            task_id='pi_task',
            conn_id='spark',
            application=f'/home/me/pi.py',
            executor_cores=4,
            num_executors=4,
            executor_memory='1g',
            driver_memory='1g',
            name='pi',
            execution_timeout=datetime.timedelta(minutes=60),
            dag=self.dag
        )
 
    def test_execute(self):
        with conf_vars({}):
            self._run_as_operator()


```

**Comment by potiuk** [comment]
Should we close the issue then?
