### ISSUE TITLE
celery.exceptions.ImproperlyConfigured: You need to install the elasticsearch library to use the Elasticsearch result backend.

### ISSUE THREAD

**Issue by enddering** [apache/airflow#16213]
**Apache Airflow version**:
> 2.0.2
- **OS** (e.g. from /etc/os-release):
> mac big sur 11.4
- **Kernel** (e.g. `uname -a`):
> Darwin bogon 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64

**What happened**:
```
[2021-06-02 14:54:21,789] {scheduler_job.py:1302} ERROR - Exception when executing SchedulerJob._run_scheduler_loop
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/kombu/utils/objects.py", line 42, in __get__
    return obj.__dict__[self.__name__]
KeyError: 'backend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/jobs/scheduler_job.py", line 1284, in _execute
    self._run_scheduler_loop()
  File "/usr/local/lib/python3.9/site-packages/airflow/jobs/scheduler_job.py", line 1358, in _run_scheduler_loop
    self.adopt_or_reset_orphaned_tasks()
  File "/usr/local/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/jobs/scheduler_job.py", line 1857, in adopt_or_reset_orphaned_tasks
    for attempt in run_with_db_retries(logger=self.log):
  File "/usr/local/lib/python3.9/site-packages/tenacity/__init__.py", line 390, in __iter__
    do = self.iter(retry_state=retry_state)
  File "/usr/local/lib/python3.9/site-packages/tenacity/__init__.py", line 356, in iter
    return fut.result()
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 438, in result
    return self.__get_result()
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.9/site-packages/airflow/jobs/scheduler_job.py", line 1902, in adopt_or_reset_orphaned_tasks
    to_reset = self.executor.try_adopt_task_instances(tis_to_reset_or_adopt)
  File "/usr/local/lib/python3.9/site-packages/airflow/executors/celery_executor.py", line 470, in try_adopt_task_instances
    celery_tasks[ti.external_executor_id] = (AsyncResult(ti.external_executor_id), ti)
  File "/usr/local/lib/python3.9/site-packages/celery/result.py", line 102, in __init__
    self.backend = backend or self.app.backend
  File "/usr/local/lib/python3.9/site-packages/kombu/utils/objects.py", line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/usr/local/lib/python3.9/site-packages/celery/app/base.py", line 1193, in backend
    return self._get_backend()
  File "/usr/local/lib/python3.9/site-packages/celery/app/base.py", line 911, in _get_backend
    return backend(app=self, url=url)
  File "/usr/local/lib/python3.9/site-packages/celery/backends/elasticsearch.py", line 54, in __init__
    raise ImproperlyConfigured(E_LIB_MISSING)
celery.exceptions.ImproperlyConfigured: You need to install the elasticsearch library to use the Elasticsearch result backend.
```
> installed elasticsearch-7.5.1 library

**What you expected to happen**:
> Use Elasticsearch for celery result backed.

**How to reproduce it**:
> airflow.cfg
> ```
> result_backend = elasticsearch://127.0.0.1:9200/airflow_celery_result_backend/_doc
> ```

**Libs Info**
```
Name: apache-airflow-providers-elasticsearch
Version: 1.0.4
Summary: Provider package apache-airflow-providers-elasticsearch for Apache Airflow
Home-page: https://airflow.apache.org/
Author: Apache Software Foundation
Author-email: dev@airflow.apache.org
License: Apache License 2.0
Location: /usr/local/lib/python3.9/site-packages
Requires: elasticsearch, apache-airflow, elasticsearch-dbapi, elasticsearch-dsl
Required-by:

Name: elasticsearch
Version: 7.5.1
Summary: Python client for Elasticsearch
Home-page: https://github.com/elastic/elasticsearch-py
Author: Honza Král, Nick Lang
Author-email: honza.kral@gmail.com, nick@nicklang.com
License: Apache License, Version 2.0
Location: /usr/local/lib/python3.9/site-packages
Requires: urllib3
Required-by: elasticsearch-dsl, elasticsearch-dbapi, apache-airflow-providers-elasticsearch
```

**Comment by potiuk** [comment]
There are a couple of things you might try:

* Python 3.9. is not yet officially supported by Airflow so you can use different python 

* Elasticsearch backend is not officially supported by Airflow ( Redis and RabbitMQ are). You can use those.

* Eventually it *might* work if celery is configured properly but it seems it is not. but this is more a question about celery configuration with elasticsearch (which we don't support) so you have much higher chance to get help if you ask in celery project Not here. My guess is that this might be a problem with MacOS library configurations (the usual problem when you install *nix tools on Mac where you have to configure additional library paths etc. But this is just a wild guess.
