### ISSUE TITLE
CeleryKubernetesExecutor error: Could not get scheduler_job_id

### ISSUE THREAD

**Issue by dstandish** [apache/airflow#16211]
Tried out CeleryKubernetesExecutor in apache chart 1.0.0 running on EKS

Official airflow image, python 3.8

Got this error in scheduler pod shortly after startup:

```
[2021-06-02 02:33:07,905] {kubernetes_executor.py:471} INFO - Start Kubernetes executor
[2021-06-02 02:33:07,905] {scheduler_job.py:1302} ERROR - Exception when executing SchedulerJob._run_scheduler_loop
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/jobs/scheduler_job.py", line 1276, in _execute
    self.executor.start()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/executors/celery_kubernetes_executor.py", line 60, in start
    self.kubernetes_executor.start()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/executors/kubernetes_executor.py", line 473, in start
    raise AirflowException("Could not get scheduler_job_id")
airflow.exceptions.AirflowException: Could not get scheduler_job_id
```

**Comment by jedcunningham** [comment]
@dstandish, can we close this in favor of #16326? I assume this was with 2.0.2, and this specific problem doesn't happen in 2.1.0.
