### ISSUE TITLE
Documentation building fails if helm-chart is not being built

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#16533]
When you've never built `helm-chart` documentation package locally. the intersphinx repository is missing for it and it cannot be downloaded as the helm-chart package is never published as package (I guess) . 

This fails for example our command to build provider's documentation when you release providers:

```
cd "${AIRFLOW_REPO_ROOT}"
./breeze build-docs -- \
  --for-production \
  --package-filter apache-airflow-providers \
  --package-filter 'apache-airflow-providers-*'
```

Adding `--package-filter 'helm-chart'` helps, but it also builds the helm-chart documentation which is undesired in this case (and it causes the docs-building for most providers to fail the first pass, until the `helm-chart` documentation is built

Possibly there is a way to get rid of that dependency ? 

The error you get:

```
apache-airflow-providers                                     Traceback (most recent call last):
apache-airflow-providers                                       File "/usr/local/lib/python3.6/site-packages/sphinx/cmd/build.py", line 279, in build_main
apache-airflow-providers                                         args.tags, args.verbosity, args.jobs, args.keep_going)
apache-airflow-providers                                       File "/usr/local/lib/python3.6/site-packages/sphinx/application.py", line 278, in __init__
apache-airflow-providers                                         self._init_builder()
apache-airflow-providers                                       File "/usr/local/lib/python3.6/site-packages/sphinx/application.py", line 337, in _init_builder
apache-airflow-providers                                         self.events.emit('builder-inited')
apache-airflow-providers                                       File "/usr/local/lib/python3.6/site-packages/sphinx/events.py", line 110, in emit
apache-airflow-providers                                         results.append(listener.handler(self.app, *args))
apache-airflow-providers                                       File "/usr/local/lib/python3.6/site-packages/sphinx/ext/intersphinx.py", line 238, in load_mappings
apache-airflow-providers                                         updated = 
apache-airflow-providers                                       File "/usr/local/lib/python3.6/site-packages/sphinx/ext/intersphinx.py", line 238, in <listcomp>
apache-airflow-providers                                         updated = 
apache-airflow-providers                                       File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 425, in result
apache-airflow-providers                                         return self.__get_result()
apache-airflow-providers                                       File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
apache-airflow-providers                                         raise self._exception
apache-airflow-providers                                       File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
apache-airflow-providers                                         result = self.fn(*self.args, **self.kwargs)
apache-airflow-providers                                       File "/usr/local/lib/python3.6/site-packages/sphinx/ext/intersphinx.py", line 224, in fetch_inventory_group
apache-airflow-providers                                         "with the following issues:") + "\n" + issues)
apache-airflow-providers                                       File "/usr/local/lib/python3.6/logging/__init__.py", line 1642, in warning
apache-airflow-providers                                         self.log(WARNING, msg, *args, **kwargs)
apache-airflow-providers                                       File "/usr/local/lib/python3.6/site-packages/sphinx/util/logging.py", line 126, in log
apache-airflow-providers                                         super().log(level, msg, *args, **kwargs)
apache-airflow-providers                                       File "/usr/local/lib/python3.6/logging/__init__.py", line 1674, in log
apache-airflow-providers                                         self.logger.log(level, msg, *args, **kwargs)
apache-airflow-providers                                       File "/usr/local/lib/python3.6/logging/__init__.py", line 1374, in log
apache-airflow-providers                                         self._log(level, msg, args, **kwargs)
apache-airflow-providers                                       File "/usr/local/lib/python3.6/logging/__init__.py", line 1444, in _log
apache-airflow-providers                                         self.handle(record)
apache-airflow-providers                                       File "/usr/local/lib/python3.6/logging/__init__.py", line 1454, in handle
apache-airflow-providers                                         self.callHandlers(record)
apache-airflow-providers                                       File "/usr/local/lib/python3.6/logging/__init__.py", line 1516, in callHandlers
apache-airflow-providers                                         hdlr.handle(record)
apache-airflow-providers                                       File "/usr/local/lib/python3.6/logging/__init__.py", line 861, in handle
apache-airflow-providers                                         rv = self.filter(record)
apache-airflow-providers                                       File "/usr/local/lib/python3.6/logging/__init__.py", line 720, in filter
apache-airflow-providers                                         result = f.filter(record)
apache-airflow-providers                                       File "/usr/local/lib/python3.6/site-packages/sphinx/util/logging.py", line 422, in filter
apache-airflow-providers                                         raise exc
apache-airflow-providers                                     sphinx.errors.SphinxWarning: failed to reach any of the inventories with the following issues:
apache-airflow-providers                                     intersphinx inventory '/opt/airflow/docs/_inventory_cache/helm-chart/objects.inv' not fetchable due to <class 
'FileNotFoundError'>: [Errno 2] No such file or directory: '/opt/airflow/docs/_inventory_cache/helm-chart/objects.inv'
apache-airflow-providers                                     
apache-airflow-providers                                     [91mWarning, treated as error:[39;49;00m
apache-airflow-providers                                     failed to reach any of the inventories with the following issues:
apache-airflow-providers                                     intersphinx inventory '/opt/airflow/docs/_inventory_cache/helm-chart/objects.inv' not fetchable due to <class 
'FileNotFoundError'>: [Errno 2] No such file or directory: '/opt/airflow/docs/_inventory_cache/helm-chart/objects.inv'

```

**Comment by potiuk** [comment]
cc: @mik-laj ?
