### ISSUE TITLE
Problem runing it locally once uninstalled and then re-installed

### ISSUE THREAD

**Issue by ebuitragod** [apache/airflow#16598]
**Apache Airflow version**:

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know**:

**Comment by ebuitragod** [comment]
pache Airflow version:

Kubernetes version (if you are using kubernetes) (use kubectl version):

Environment:

Cloud provider or hardware configuration:
OS (e.g. from /etc/os-release):
Kernel (e.g. uname -a):
Install tools:
Others:
What happened:
I uninstalled airflow and then reinstalled accordingly with thte documentations.
What you expected to happen:
Once I ran the the server it broke 
How to reproduce it:

Anything else we need to know:

here the error:

127.0.0.1 - - [22/Jun/2021:19:14:08 +0200] "GET / HTTP/1.1" 302 217 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36"
[2021-06-22 19:14:08,528] {app.py:1892} ERROR - Exception on /home [GET]
Traceback (most recent call last):
  File "/Users/espe/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/Users/espe/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: dag

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/espe/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/espe/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/espe/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/espe/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/espe/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/espe/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/espe/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/www/auth.py", line 34, in decorated
    return func(*args, **kwargs)
  File "/Users/espe/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/www/views.py", line 547, in index
    filter_dag_ids = current_app.appbuilder.sm.get_accessible_dag_ids(g.user)
  File "/Users/espe/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/www/security.py", line 298, in get_accessible_dag_ids
    return {dag.dag_id for dag in accessible_dags}
  File "/Users/espe/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3535, in __iter__
    return self._execute_and_instances(context)
  File "/Users/espe/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3560, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/Users/espe/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/Users/espe/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/espe/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement
    distilled_params,
  File "/Users/espe/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "/Users/espe/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/Users/espe/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/Users/espe/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/Users/espe/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: dag
[SQL: SELECT dag.dag_id AS dag_dag_id, dag.root_dag_id AS dag_root_dag_id, dag.is_paused AS dag_is_paused, dag.is_subdag AS dag_is_subdag, dag.is_active AS dag_is_active, dag.last_parsed_time AS dag_last_parsed_time, dag.last_pickled AS dag_last_pickled, dag.last_expired AS dag_last_expired, dag.scheduler_lock AS dag_scheduler_lock, dag.pickle_id AS dag_pickle_id, dag.fileloc AS dag_fileloc, dag.owners AS dag_owners, dag.description AS dag_description, dag.default_view AS dag_default_view, dag.schedule_interval AS dag_schedule_interval, dag.concurrency AS dag_concurrency, dag.has_task_concurrency_limits AS dag_has_task_concurrency_limits, dag.next_dagrun AS dag_next_dagrun, dag.next_dagrun_create_after AS dag_next_dagrun_create_after 
FROM dag]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
127.0.0.1 - - [22/Jun/2021:19:14:13 +0200] "GET /home HTTP/1.1" 500 5513 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36"

**Comment by jedcunningham** [comment]
Have you run [airflow db init](https://airflow.apache.org/docs/apache-airflow/stable/cli-and-env-variables-ref.html#init) or (since you are reinstalling) [airflow db reset](https://airflow.apache.org/docs/apache-airflow/stable/cli-and-env-variables-ref.html#reset)?

**Comment by ebuitragod** [comment]
Yes I did, but found a way to make it run in other ways.
