### ISSUE TITLE
TypeError: cannot serialize '_io.TextIOWrapper' object

### ISSUE THREAD

**Issue by baaj2109** [apache/airflow#16903]
Hi, I tried to run airflow tutorial code on windows subsystem ubuntu, but when I run backfill always got this error, is there something I miss?
and below is my command
`airflow dags backfill tutorial -s 2019-10-01 -e 2019-10-05
`

**Apache Airflow version**: 2.1.0

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):11.0.0

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): WSL
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

```

/usr/lib/python3/dist-packages/requests/__init__.py:80 RequestsDependencyWarning: urllib3 (1.26.6) or chardet (3.0.4) doesn't match a supported version!
/home/baaj2109/.local/lib/python3.6/site-packages/airflow/cli/commands/dag_command.py:62 PendingDeprecationWarning: --ignore-first-depends-on-past is deprecated as the value is always set to True
[2021-07-09 11:53:48,160] {dagbag.py:487} INFO - Filling up the DagBag from /home/baaj2109/airflow/dags
[2021-07-09 11:53:48,357] {default_celery.py:100} WARNING - You have configured a result_backend of amqp://guest:guest@localhost:5672//, it is highly recommended to use an alternative result_backend (i.e. a database).
[2021-07-09 11:53:48,867] {backfill_job.py:903} INFO - Reset the following 3 TaskInstances:
        <TaskInstance: tutorial.print_date 2019-10-01 00:00:00+00:00 [None]>
        <TaskInstance: tutorial.templated 2019-10-01 00:00:00+00:00 [None]>
        <TaskInstance: tutorial.sleep 2019-10-01 00:00:00+00:00 [None]>
[2021-07-09 11:53:48,944] {backfill_job.py:903} INFO - Reset the following 3 TaskInstances:
        <TaskInstance: tutorial.print_date 2019-10-02 00:00:00+00:00 [None]>
        <TaskInstance: tutorial.templated 2019-10-02 00:00:00+00:00 [None]>
        <TaskInstance: tutorial.sleep 2019-10-02 00:00:00+00:00 [None]>
[2021-07-09 11:53:49,020] {backfill_job.py:903} INFO - Reset the following 3 TaskInstances:
        <TaskInstance: tutorial.print_date 2019-10-03 00:00:00+00:00 [None]>
        <TaskInstance: tutorial.templated 2019-10-03 00:00:00+00:00 [None]>
        <TaskInstance: tutorial.sleep 2019-10-03 00:00:00+00:00 [None]>
[2021-07-09 11:53:49,100] {backfill_job.py:903} INFO - Reset the following 3 TaskInstances:
        <TaskInstance: tutorial.print_date 2019-10-04 00:00:00+00:00 [None]>
        <TaskInstance: tutorial.templated 2019-10-04 00:00:00+00:00 [None]>
        <TaskInstance: tutorial.sleep 2019-10-04 00:00:00+00:00 [None]>
[2021-07-09 11:53:49,209] {backfill_job.py:903} INFO - Reset the following 3 TaskInstances:
        <TaskInstance: tutorial.print_date 2019-10-05 00:00:00+00:00 [None]>
        <TaskInstance: tutorial.templated 2019-10-05 00:00:00+00:00 [None]>
        <TaskInstance: tutorial.sleep 2019-10-05 00:00:00+00:00 [None]>
[2021-07-09 11:53:49,273] {base_executor.py:82} INFO - Adding to queue: ['airflow', 'tasks', 'run', 'tutorial', 'print_date', '2019-10-01T00:00:00+00:00', '--ignore-depends-on-past', '--local', '--pool', 'default_pool', '--subdir', 'DAGS_FOLDER/test.py']
[2021-07-09 11:53:49,318] {base_executor.py:82} INFO - Adding to queue: ['airflow', 'tasks', 'run', 'tutorial', 'print_date', '2019-10-02T00:00:00+00:00', '--local', '--pool', 'default_pool', '--subdir', 'DAGS_FOLDER/test.py']
[2021-07-09 11:53:49,359] {base_executor.py:82} INFO - Adding to queue: ['airflow', 'tasks', 'run', 'tutorial', 'print_date', '2019-10-03T00:00:00+00:00', '--local', '--pool', 'default_pool', '--subdir', 'DAGS_FOLDER/test.py']
[2021-07-09 11:53:49,404] {base_executor.py:82} INFO - Adding to queue: ['airflow', 'tasks', 'run', 'tutorial', 'print_date', '2019-10-04T00:00:00+00:00', '--local', '--pool', 'default_pool', '--subdir', 'DAGS_FOLDER/test.py']
[2021-07-09 11:53:49,448] {base_executor.py:82} INFO - Adding to queue: ['airflow', 'tasks', 'run', 'tutorial', 'print_date', '2019-10-05T00:00:00+00:00', '--local', '--pool', 'default_pool', '--subdir', 'DAGS_FOLDER/test.py']
Traceback (most recent call last):
  File "/home/baaj2109/.local/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/home/baaj2109/.local/lib/python3.6/site-packages/airflow/__main__.py", line 40, in main
    args.func(args)
  File "/home/baaj2109/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/baaj2109/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 91, in wrapper
    return f(*args, **kwargs)
  File "/home/baaj2109/.local/lib/python3.6/site-packages/airflow/cli/commands/dag_command.py", line 116, in dag_backfill
    run_backwards=args.run_backwards,
  File "/home/baaj2109/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 1720, in run
    job.run()
  File "/home/baaj2109/.local/lib/python3.6/site-packages/airflow/jobs/base_job.py", line 237, in run
    self._execute()
  File "/home/baaj2109/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/baaj2109/.local/lib/python3.6/site-packages/airflow/jobs/backfill_job.py", line 806, in _execute
    session=session,
  File "/home/baaj2109/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 67, in wrapper
    return func(*args, **kwargs)
  File "/home/baaj2109/.local/lib/python3.6/site-packages/airflow/jobs/backfill_job.py", line 727, in _execute_for_run_dates
    session=session,
  File "/home/baaj2109/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 67, in wrapper
    return func(*args, **kwargs)
  File "/home/baaj2109/.local/lib/python3.6/site-packages/airflow/jobs/backfill_job.py", line 602, in _process_backfill_task_instances
    executor.heartbeat()
  File "/home/baaj2109/.local/lib/python3.6/site-packages/airflow/executors/base_executor.py", line 158, in heartbeat
    self.trigger_tasks(open_slots)
  File "/home/baaj2109/.local/lib/python3.6/site-packages/airflow/executors/celery_executor.py", line 263, in trigger_tasks
    self._process_tasks(task_tuples_to_send)
  File "/home/baaj2109/.local/lib/python3.6/site-packages/airflow/executors/celery_executor.py", line 272, in _process_tasks
    key_and_async_results = self._send_tasks_to_celery(task_tuples_to_send)
  File "/home/baaj2109/.local/lib/python3.6/site-packages/airflow/executors/celery_executor.py", line 332, in _send_tasks_to_celery
    send_task_to_executor, task_tuples_to_send, chunksize=chunksize
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 424, in _handle_tasks
    put(task)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/usr/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: cannot serialize '_io.TextIOWrapper' object
```

**Comment by uranusjr** [comment]
See #14379. 2.1.1 contains a fix to this.

**Comment by uranusjr** [comment]
Oh you are running a supported kunernetes version. Hmm, so this is not the same I guess.

**Comment by uranusjr** [comment]
#14379 looks more similar, but that issue was already resolved before 2.1.0.

**Comment by baaj2109** [comment]
I update airflow from 2.1.0 to 2.1.1, got new error message
```

/usr/lib/python3/dist-packages/requests/__init__.py:80 RequestsDependencyWarning: urllib3 (1.26.6) or chardet (3.0.4) doesn't match a supported version!
/home/baaj2109/.local/lib/python3.6/site-packages/airflow/cli/commands/dag_command.py:62 PendingDeprecationWarning: --ignore-first-depends-on-past is deprecated as the value is always set to True
[2021-07-09 13:40:54,845] {dagbag.py:496} INFO - Filling up the DagBag from /home/baaj2109/airflow/dags
[2021-07-09 13:40:59,404] {default_celery.py:100} WARNING - You have configured a result_backend of amqp://guest:guest@localhost:5672//, it is highly recommended to use an alternative result_backend (i.e. a database).
[2021-07-09 13:41:00,062] {backfill_job.py:903} INFO - Reset the following 3 TaskInstances:
        <TaskInstance: tutorial.print_date 2019-10-01 00:00:00+00:00 [None]>
        <TaskInstance: tutorial.templated 2019-10-01 00:00:00+00:00 [None]>
        <TaskInstance: tutorial.sleep 2019-10-01 00:00:00+00:00 [None]>
[2021-07-09 13:41:00,206] {backfill_job.py:903} INFO - Reset the following 3 TaskInstances:
        <TaskInstance: tutorial.print_date 2019-10-02 00:00:00+00:00 [None]>
        <TaskInstance: tutorial.templated 2019-10-02 00:00:00+00:00 [None]>
        <TaskInstance: tutorial.sleep 2019-10-02 00:00:00+00:00 [None]>
[2021-07-09 13:41:00,449] {backfill_job.py:903} INFO - Reset the following 3 TaskInstances:
        <TaskInstance: tutorial.print_date 2019-10-03 00:00:00+00:00 [None]>
        <TaskInstance: tutorial.templated 2019-10-03 00:00:00+00:00 [None]>
        <TaskInstance: tutorial.sleep 2019-10-03 00:00:00+00:00 [None]>
[2021-07-09 13:41:00,584] {backfill_job.py:903} INFO - Reset the following 3 TaskInstances:
        <TaskInstance: tutorial.print_date 2019-10-04 00:00:00+00:00 [None]>
        <TaskInstance: tutorial.templated 2019-10-04 00:00:00+00:00 [None]>
        <TaskInstance: tutorial.sleep 2019-10-04 00:00:00+00:00 [None]>
[2021-07-09 13:41:00,838] {backfill_job.py:903} INFO - Reset the following 3 TaskInstances:
        <TaskInstance: tutorial.print_date 2019-10-05 00:00:00+00:00 [None]>
        <TaskInstance: tutorial.templated 2019-10-05 00:00:00+00:00 [None]>
        <TaskInstance: tutorial.sleep 2019-10-05 00:00:00+00:00 [None]>
[2021-07-09 13:41:00,998] {base_executor.py:82} INFO - Adding to queue: ['airflow', 'tasks', 'run', 'tutorial', 'print_date', '2019-10-01T00:00:00+00:00', '--ignore-depends-on-past', '--local', '--pool', 'default_pool', '--subdir', 'DAGS_FOLDER/test.py']
[2021-07-09 13:41:01,083] {base_executor.py:82} INFO - Adding to queue: ['airflow', 'tasks', 'run', 'tutorial', 'print_date', '2019-10-02T00:00:00+00:00', '--local', '--pool', 'default_pool', '--subdir', 'DAGS_FOLDER/test.py']
[2021-07-09 13:41:01,184] {base_executor.py:82} INFO - Adding to queue: ['airflow', 'tasks', 'run', 'tutorial', 'print_date', '2019-10-03T00:00:00+00:00', '--local', '--pool', 'default_pool', '--subdir', 'DAGS_FOLDER/test.py']
[2021-07-09 13:41:01,340] {base_executor.py:82} INFO - Adding to queue: ['airflow', 'tasks', 'run', 'tutorial', 'print_date', '2019-10-04T00:00:00+00:00', '--local', '--pool', 'default_pool', '--subdir', 'DAGS_FOLDER/test.py']
[2021-07-09 13:41:01,395] {base_executor.py:82} INFO - Adding to queue: ['airflow', 'tasks', 'run', 'tutorial', 'print_date', '2019-10-05T00:00:00+00:00', '--local', '--pool', 'default_pool', '--subdir', 'DAGS_FOLDER/test.py']
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 234, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/usr/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: cannot serialize '_io.TextIOWrapper' object
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 234, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/usr/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: cannot serialize '_io.TextIOWrapper' object
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 234, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/usr/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: cannot serialize '_io.TextIOWrapper' object
```
and after I type ctrl+c, show another message
```

^CProcess Process-1:
Process Process-3:
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/concurrent/futures/process.py", line 169, in _process_worker
    call_item = call_queue.get(block=True)
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 94, in get
    res = self._recv_bytes()
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/concurrent/futures/process.py", line 295, in _queue_management_worker
    shutdown_worker()
  File "/usr/lib/python3.6/concurrent/futures/process.py", line 253, in shutdown_worker
    call_queue.put_nowait(None)
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 129, in put_nowait
    return self.put(obj, False)
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 83, in put
    raise Full
queue.Full

[2021-07-09 13:44:05,129] {backfill_job.py:822} WARNING - Backfill terminated by user.
[2021-07-09 13:44:05,559] {backfill_job.py:831} INFO - Backfill done. Exiting.
```

**Comment by potiuk** [comment]
How did you install Airflow? Was it with the Official Helm Chart? Or following instructions from https://airflow.apache.org/docs/apache-airflow/stable/installation.html ? Any other way? I have a feeling (looking at some warning messages) that a number of dependencies you have especially Celery) is no in the version that is supported.

Can you please describe your installation method (or better - try to reinstall airflow using one of the methods described above and try again?)

**Comment by baaj2109** [comment]
thank you for your help, actually I followed instructions from https://medium.com/@ryanroline/installing-apache-airflow-on-windows-10-5247aa1249ef, I will reinstall airflow again with official instructions.

**Comment by potiuk** [comment]
Cool Please do and report it here, I made a comment in the article and asked the author to update the article and put the link to the official installation page. I will close the issue for now, please report if you have further problems after reinstalling - both when it suceed or fails.
