### ISSUE TITLE
"Mark Success" breaks

### ISSUE THREAD

**Issue by NilsJPWerner** [apache/airflow#16957]
**Apache Airflow version**:  2.1.1+astro.1

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**: Astronomer
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

Anytime I try to mark a task as success in the web ui I get the following error: 
```
Python version: 3.7.10
Airflow version: 2.1.1+astro.1
Node: elementary-mass-2343-webserver-5dbf54454c-cj426
-------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/airflow/www/auth.py", line 34, in decorated
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/www/decorators.py", line 60, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/www/views.py", line 2000, in success
    State.SUCCESS,
  File "/usr/local/lib/python3.7/site-packages/airflow/www/views.py", line 1856, in _mark_task_instance_state
    exclude_task_ids={task_id},
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/session.py", line 67, in wrapper
    return func(*args, **kwargs)
TypeError: clear() got an unexpected keyword argument 'exclude_task_ids'
```

**What you expected to happen**:

The task to be marked as success.

It happens for all my dags.

**How to reproduce it**:

**Comment by msumit** [comment]
@NilsJPWerner the issue has been resolved with the latest release of Astronomer certified Airflow. Try upgrading to 2.1.1+astro.2 or later.
