### ISSUE TITLE
MSSQL-2019 tests are failing

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#17088]
While the recent lock problems have been solved, it seems the MSSQL-2019 tests are failling as containers are not healthy

See for example https://github.com/apache/airflow/runs/3106807172?check_suite_focus=true

CC: @aneesh-joseph

**Comment by uranusjr** [comment]
Other MSSQL jobs are failing as well

```
  INFO  [airflow.models.dag] Setting next_dagrun for example_subdag_operator.section-2 to None
  Traceback (most recent call last):
    File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
      cursor, statement, parameters, context
    File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
      cursor.execute(statement, parameters)
  pyodbc.ProgrammingError: ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot release the application lock (Database Principal: 'public', Resource: 'init') because it is not currently held. (1223) (SQLExecDirectW)")
  
  The above exception was the direct cause of the following exception:
  
  Traceback (most recent call last):
    File "/usr/local/bin/airflow", line 33, in <module>
      sys.exit(load_entry_point('apache-airflow', 'console_scripts', 'airflow')())
    File "/opt/airflow/airflow/__main__.py", line 40, in main
      args.func(args)
    File "/opt/airflow/airflow/cli/cli_parser.py", line 48, in command
      return func(*args, **kwargs)
    File "/opt/airflow/airflow/cli/commands/db_command.py", line 39, in resetdb
      db.resetdb()
    File "/opt/airflow/airflow/utils/session.py", line 70, in wrapper
      return func(*args, session=session, **kwargs)
    File "/opt/airflow/airflow/utils/db.py", line 736, in resetdb
      initdb(session=session)
    File "/opt/airflow/airflow/utils/session.py", line 67, in wrapper
      return func(*args, **kwargs)
    File "/opt/airflow/airflow/utils/db.py", line 594, in initdb
      Base.metadata.create_all(settings.engine)
    File "/usr/local/lib/python3.7/contextlib.py", line 119, in __exit__
      next(self.gen)
    File "/opt/airflow/airflow/utils/session.py", line 108, in create_global_lock
      f"sp_releaseapplock @Resource = '{lock_name}', @LockOwner = 'Session';"
    File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1003, in execute
      return self._execute_text(object_, multiparams, params)
    File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1178, in _execute_text
      parameters,
    File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
      e, statement, parameters, cursor, context
    File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
      sqlalchemy_exception, with_traceback=exc_info[2], from_=e
    File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
      raise exception
    File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
      cursor, statement, parameters, context
    File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
      cursor.execute(statement, parameters)
  sqlalchemy.exc.ProgrammingError: (pyodbc.ProgrammingError) ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot release the application lock (Database Principal: 'public', Resource: 'init') because it is not currently held. (1223) (SQLExecDirectW)")
  [SQL: sp_releaseapplock @Resource = 'init', @LockOwner = 'Session';]
```
