### ISSUE TITLE
ERROR - No module named 'motor'

### ISSUE THREAD

**Issue by angelorobo** [apache/airflow#17199]
**Apache Airflow version**:
apache-airflow==1.10.9
motor>=1.2.1

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

```
$ kubectl version

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T20:58:09Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.17-eks-c5067d", GitCommit:"c5067dd1eb324e934de1f5bd4c593b3cddc19d88", GitTreeState:"clean", BuildDate:"2021-03-06T00:25:44Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

```
[2021-07-24 06:21:04,189] {plugins_manager.py:188} ERROR - No module named 'motor'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/plugins_manager.py", line 182, in <module>
    m = imp.load_source(namespace, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/robo/airflow/plugins/motor_plugin.py", line 2, in <module>
    from flows.plugins.hooks.motor_hook import MotorHook
  File "/robo/flows/__init__.py", line 14, in <module>
    from serving import mongo
  File "/robo/serving/mongo/__init__.py", line 20, in <module>
    from .utils import motor_db_for_tornado
  File "/robo/serving/mongo/utils.py", line 1, in <module>
    import motor
ModuleNotFoundError: No module named 'motor'
[2021-07-24 06:21:04,190] {plugins_manager.py:189} ERROR - Failed to import plugin /robo/airflow/plugins/motor_plugin.py
[2021-07-24 06:21:04,192] {plugins_manager.py:188} ERROR - No module named 'motor'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/plugins_manager.py", line 182, in <module>
    m = imp.load_source(namespace, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/robo/airflow/plugins/hooks/motor_hook.py", line 4, in <module>
    import motor
ModuleNotFoundError: No module named 'motor'
```

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know**:

**Comment by angelorobo** [comment]
It is a coding issue. We rolled back to an older version of our backend service and It works. So we have to figure out what is missing between the older version and the new deployment. It is a false alarm and not related to Airflow.
