### ISSUE TITLE
Unexpected apache-airflow webserver error without any known

### ISSUE THREAD

**Issue by rdiazg14** [apache/airflow#17517]
<details><summary>Unexpected apache-airflow webserver error without any known </summary> Something bad has happened.
Please consider letting us know by creating a bug report using GitHub.

Python version: 3.8.10
Airflow version: 2.1.2
Node: SERVER.user.corp
-------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/user/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/.local/lib/python3.8/site-packages/airflow/www/auth.py", line 34, in decorated
    return func(*args, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/airflow/www/views.py", line 645, in index
    return self.render_template(
  File "/home/user/.local/lib/python3.8/site-packages/airflow/www/views.py", line 438, in render_template
    return super().render_template(
  File "/home/user/.local/lib/python3.8/site-packages/flask_appbuilder/baseviews.py", line 287, in render_template
    return render_template(
  File "/home/user/.local/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/user/.local/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/usr/lib/python3/dist-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/user/.local/lib/python3.8/site-packages/airflow/www/templates/airflow/dags.html", line 21, in <module>
    {% from 'appbuilder/loading_dots.html' import loading_dots %}
  File "/home/user/.local/lib/python3.8/site-packages/airflow/www/templates/airflow/main.html", line 20, in <module>
    {% extends 'appbuilder/baselayout.html' %}
  File "/home/user/.local/lib/python3.8/site-packages/flask_appbuilder/templates/appbuilder/baselayout.html", line 2, in <module>
    {% import 'appbuilder/baselib.html' as baselib %}
  File "/home/user/.local/lib/python3.8/site-packages/flask_appbuilder/templates/appbuilder/init.html", line 37, in <module>
    {% block body %}
  File "/home/user/.local/lib/python3.8/site-packages/flask_appbuilder/templates/appbuilder/baselayout.html", line 16, in <module>
    {% block messages %}
  File "/home/user/.local/lib/python3.8/site-packages/airflow/www/templates/airflow/main.html", line 62, in <module>
    >{{ macros.datetime_diff_for_humans(scheduler_job.latest_heartbeat) }}</time>.
  File "/home/user/.local/lib/python3.8/site-packages/airflow/macros/__init__.py", line 83, in datetime_diff_for_humans
    return pendulum.instance(dt).diff_for_humans(since)
  File "/home/user/.local/lib/python3.8/site-packages/pendulum/datetime.py", line 824, in diff_for_humans
    other = self.now()
  File "/home/user/.local/lib/python3.8/site-packages/pendulum/datetime.py", line 106, in now
    return pendulum.now(tz)
  File "/home/user/.local/lib/python3.8/site-packages/pendulum/__init__.py", line 211, in now
    dt = _datetime.datetime.now(local_timezone())
  File "/home/user/.local/lib/python3.8/site-packages/pendulum/tz/__init__.py", line 60, in local_timezone
    return get_local_timezone()
  File "/home/user/.local/lib/python3.8/site-packages/pendulum/tz/local_timezone.py", line 35, in get_local_timezone
    tz = _get_system_timezone()
  File "/home/user/.local/lib/python3.8/site-packages/pendulum/tz/local_timezone.py", line 63, in _get_system_timezone
    return _get_unix_timezone()
  File "/home/user/.local/lib/python3.8/site-packages/pendulum/tz/local_timezone.py", line 240, in _get_unix_timezone
    return TimezoneFile(tzpath)
  File "/home/user/.local/lib/python3.8/site-packages/pendulum/tz/timezone.py", line 370, in __init__
    tz = read_file(path)
  File "/home/user/.local/lib/python3.8/site-packages/pendulum/tz/zoneinfo/__init__.py", line 16, in read_file
    return Reader(extend=extend).read(path)
  File "/home/user/.local/lib/python3.8/site-packages/pendulum/tz/zoneinfo/reader.py", line 66, in read
    return self._parse(fd)
  File "/home/user/.local/lib/python3.8/site-packages/pendulum/tz/zoneinfo/reader.py", line 145, in _parse
    return Timezone(transitions, posix_rule=trule, extended=self._extend)
  File "/home/user/.local/lib/python3.8/site-packages/pendulum/tz/zoneinfo/timezone.py", line 28, in __init__
    self._extends()
  File "/home/user/.local/lib/python3.8/site-packages/pendulum/tz/zoneinfo/timezone.py", line 49, in _extends
    raise ValueError("Posix spec does not match last transition")
ValueError: Posix spec does not match last transition </details>

print of error:
https://imgur.com/I5J1b4U

package and version install of apache-airflow
pip freeze | grep apache-airflow-providers
apache-airflow-providers-ftp==2.0.0
apache-airflow-providers-google==5.0.0
apache-airflow-providers-imap==2.0.0
apache-airflow-providers-sqlite==2.0.0

**Comment by rdiazg14** [comment]
Help me please!

**Comment by potiuk** [comment]
Apparently you run Airlfow in WSL (Windows) and Windows in some combination does not support POSIX time properly https://camcops.readthedocs.io/en/latest/administrator/server_troubleshooting.html#problems-starting-camcops

Airlfow is not supposed to work for producion on Windows (even in WSL it's only for development and testing). The suggested solution is to run Airflow on Linux, or in proper Virtual Machine setup.

**Comment by rdiazg14** [comment]
Thank You man, I'll attend your advice.
