### ISSUE TITLE
Unexpected Error when trying to start airflow

### ISSUE THREAD

**Issue by meeraanntom** [apache/airflow#17620]
**Apache Airflow version**:  2.0.1

**OS**: MAC OS big SUR ( 11.4 (20F71)) 

**Apache Airflow Provider versions**:

**Deployment**:

**What happened**:
Something bad has happened.
Please consider letting us know by creating a bug report using GitHub.

Python version: 3.7.1
Airflow version: 2.0.1
Node: MB28696.local
-------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/wireless-analytics-setup/env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/wireless-analytics-setup/env/lib/python3.7/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/Users/analytics-setup/env/lib/python3.7/site-packages/flask/app.py", line 1970, in finalize_request
    response = self.process_response(response)
  File "/Users/wireless-analytics-setup/env/lib/python3.7/site-packages/flask/app.py", line 2269, in process_response
    self.session_interface.save_session(self, ctx.session, response)
  File "/Users/wireless-analytics-setup/env/lib/python3.7/site-packages/flask/sessions.py", line 387, in save_session
    samesite=samesite,
  File "/Users/wireless-analytics-setup/env/lib/python3.7/site-packages/werkzeug/wrappers/base_response.py", line 479, in set_cookie
    samesite=samesite,
  File "/Users/wireless-analytics-setup/env/lib/python3.7/site-packages/werkzeug/http.py", line 1217, in dump_cookie
    raise ValueError("SameSite must be 'Strict', 'Lax', or 'None'.")
ValueError: SameSite must be 'Strict', 'Lax', or 'None'.

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know**:

**Are you willing to submit a PR?**

**Comment by potiuk** [comment]
You likely did not follow the installation instructions and did not use constraints: https://airflow.apache.org/docs/apache-airflow/stable/installation.html#installation-script
