### ISSUE TITLE
Neo4j can't connect 

### ISSUE THREAD

**Issue by dsubhasis** [apache/airflow#18178]
### Apache Airflow Provider(s)

neo4j

### Versions of Apache Airflow Providers

apache-airflow-providers-celery==1.0.1
apache-airflow-providers-cncf-kubernetes==1.0.2
apache-airflow-providers-ftp==2.0.0
apache-airflow-providers-google==5.0.0
apache-airflow-providers-http==2.0.0
apache-airflow-providers-imap==2.0.0
apache-airflow-providers-jdbc==2.0.1
apache-airflow-providers-neo4j==2.0.0
apache-airflow-providers-postgres==2.0.0
apache-airflow-providers-sqlite==2.0.0

### Apache Airflow version

2.1.3 (latest released)

### Operating System

Ubuntu 18

### Deployment

Other

### Deployment details

Standard Linux installation with python 3.6 

### What happened

Neo4j access problem 

Traceback (most recent call last):
  File "/home/sudasgupta/tools/airflow/env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1164, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/sudasgupta/tools/airflow/env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1282, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/sudasgupta/tools/airflow/env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1312, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/sudasgupta/tools/airflow/env/lib/python3.6/site-packages/airflow/providers/neo4j/operators/neo4j.py", line 60, in execute
    self.hook.run(self.sql)
  File "/home/sudasgupta/tools/airflow/env/lib/python3.6/site-packages/airflow/providers/neo4j/hooks/neo4j.py", line 113, in run
    driver = self.get_conn()
  File "/home/sudasgupta/tools/airflow/env/lib/python3.6/site-packages/airflow/providers/neo4j/hooks/neo4j.py", line 67, in get_conn
    self.uri, auth=(self.connection.login, self.connection.password), encrypted=is_encrypted
  File "/home/sudasgupta/tools/airflow/env/lib/python3.6/site-packages/neo4j/__init__.py", line 183, in driver
    return cls.bolt_driver(parsed.netloc, auth=auth, **config)
  File "/home/sudasgupta/tools/airflow/env/lib/python3.6/site-packages/neo4j/__init__.py", line 193, in bolt_driver
    from neo4j._exceptions import BoltHandshakeError, BoltSecurityError
ModuleNotFoundError: No module named 'neo4j._exceptions'; 'neo4j' is not a package

### What you expected to happen

Linux Driver problem 

### How to reproduce

Just by running the DAG

### Anything else

No

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by mik-laj** [comment]
Do you use constraints files to install Airflow? http://airflow.apache.org/docs/apache-airflow/stable/installation.html#constraints-files

**Comment by dsubhasis** [comment]
My installation is as follows:

CONSTRAINT_URL="
https://raw.githubusercontent.com/apache/airflow/constraints-2.1.3/constraints-3.6.txt
"
AIRFLOW_VERSION=2.1.3

pip install "apache-airflow[postgres,neo4j]==${AIRFLOW_VERSION}"
--constraint "${CONSTRAINT_URL}"

**Comment by potiuk** [comment]
For me it looks like if you had a  `neo4j.py` file in your PYTHONPATH (maybe your dag is named like that? Seems that Python interpreter sees `neo4j` as module rather than package.
