### ISSUE TITLE
[Webserver] AttributeError: '_UnboundLoad' object has no attribute 'options'

### ISSUE THREAD

**Issue by menthamin** [apache/airflow#18186]
### Apache Airflow version

2.1.3 (latest released)

### Operating System

Ubuntu 18.04.5 LTS

### Deployment

Virtualenv installation

### What happened

```
Something bad has happened.
Please consider letting us know by creating a bug report using GitHub.

Python version: 3.8.8
Airflow version: 2.1.3
Node: dev-airflow1.asia-northeast3-a.c.tidal-cipher-322910.internal
-------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dev-user/airflow/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dev-user/airflow/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dev-user/airflow/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dev-user/airflow/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/dev-user/airflow/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dev-user/airflow/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/dev-user/airflow/lib/python3.8/site-packages/airflow/www/auth.py", line 34, in decorated
    return func(*args, **kwargs)
  File "/home/dev-user/airflow/lib/python3.8/site-packages/airflow/www/views.py", line 551, in index
    filter_dag_ids = current_app.appbuilder.sm.get_accessible_dag_ids(g.user)
  File "/home/dev-user/airflow/lib/python3.8/site-packages/airflow/www/security.py", line 295, in get_accessible_dag_ids
    accessible_dags = self.get_accessible_dags(
  File "/home/dev-user/airflow/lib/python3.8/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/dev-user/airflow/lib/python3.8/site-packages/airflow/www/security.py", line 309, in get_accessible_dags
    joinedload(User.roles)
AttributeError: '_UnboundLoad' object has no attribute 'options'
```

I am getting the above error when logging in from the webserver.

OS : Ubuntu 18.04.5 LTS
Python : 3.8.8(virtualenv)
Airflow : 2.1.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by menthamin** [comment]
I solved the problem by reinstalling airflow-related packages with the following command.

```
pip install apache-airflow
```

It seems to be a SQLAlchemy dependency problem

```
Requirement already satisfied: apache-airflow in ./airflow/lib/python3.8/site-packages (2.1.3)
Requirement already satisfied: gunicorn>=19.5.0 in ./airflow/lib/python3.8/site-packages (from apache-airflow) (20.1.0)
...
Installing collected packages: sqlalchemy
  Attempting uninstall: sqlalchemy
    Found existing installation: SQLAlchemy 1.3.2
    Uninstalling SQLAlchemy-1.3.2:
      Successfully uninstalled SQLAlchemy-1.3.2
Successfully installed sqlalchemy-1.3.24
```
