### ISSUE TITLE
Error when running dag & something to do with parsing the start date

### ISSUE THREAD

**Issue by t4n1o** [apache/airflow#18541]
### Apache Airflow version

2.1.3

### Operating System

Ubuntu server 20.04 lTS 

### Deployment

Virtualenv installation

### Deployment details

It's deployed according to this ansible role:
https://github.com/idealista/airflow-role

### What happened

```
 26 15:21:37 avantry01 airflow[62557]: [2021-09-26 15:21:37,284] {app.py:1891} ERROR - Exception on /last_dagruns [POST]
Sep 26 15:21:37 avantry01 airflow[62557]: Traceback (most recent call last):
Sep 26 15:21:37 avantry01 airflow[62557]:   File "/opt/airflow/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
Sep 26 15:21:37 avantry01 airflow[62557]:     response = self.full_dispatch_request()
Sep 26 15:21:37 avantry01 airflow[62557]:   File "/opt/airflow/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
Sep 26 15:21:37 avantry01 airflow[62557]:     rv = self.handle_user_exception(e)
Sep 26 15:21:37 avantry01 airflow[62557]:   File "/opt/airflow/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
Sep 26 15:21:37 avantry01 airflow[62557]:     reraise(exc_type, exc_value, tb)
Sep 26 15:21:37 avantry01 airflow[62557]:   File "/opt/airflow/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
Sep 26 15:21:37 avantry01 airflow[62557]:     raise value
Sep 26 15:21:37 avantry01 airflow[62557]:   File "/opt/airflow/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
Sep 26 15:21:37 avantry01 airflow[62557]:     rv = self.dispatch_request()
Sep 26 15:21:37 avantry01 airflow[62557]:   File "/opt/airflow/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
Sep 26 15:21:37 avantry01 airflow[62557]:     return self.view_functions[rule.endpoint](**req.view_args)
Sep 26 15:21:37 avantry01 airflow[62557]:   File "/opt/airflow/lib/python3.9/site-packages/airflow/www/auth.py", line 34, in decorated
Sep 26 15:21:37 avantry01 airflow[62557]:     return func(*args, **kwargs)
Sep 26 15:21:37 avantry01 airflow[62557]:   File "/opt/airflow/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
Sep 26 15:21:37 avantry01 airflow[62557]:     return func(*args, session=session, **kwargs)
Sep 26 15:21:37 avantry01 airflow[62557]:   File "/opt/airflow/lib/python3.9/site-packages/airflow/www/views.py", line 852, in last_dagruns
Sep 26 15:21:37 avantry01 airflow[62557]:     resp = {
Sep 26 15:21:37 avantry01 airflow[62557]:   File "/opt/airflow/lib/python3.9/site-packages/airflow/www/views.py", line 856, in <dictcomp>
Sep 26 15:21:37 avantry01 airflow[62557]:     'start_date': r.start_date.isoformat(),
Sep 26 15:21:37 avantry01 airflow[62557]: AttributeError: 'NoneType' object has no attribute 'isoformat'
```

### What you expected to happen

It's hard to say what this error is about - it seems to be related to the webserver displaying what's happening, but the dag doesn't manage to exit (continues on indefinitely) because of it.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bbovenzi** [comment]
@uranusjr Shouldn't this be caught here? https://github.com/apache/airflow/blob/main/airflow/www/views.py#L917

**Comment by bhavaniravi** [comment]
@bbovenzi That check is not available in 2.1.3 codebase 
https://github.com/apache/airflow/blob/2.1.3/airflow/www/views.py#L856

In what case would `start_date` be `None`? We usually find them in DAG parsing and report it as an error

**Comment by uranusjr** [comment]
Yup, that one is unfortunately not backported to 2.1, see #18315.

**Comment by t4n1o** [comment]
Even this ulta-simple dag fails:
```
"""Test the smtp send email feature with airflow."""
from datetime import timedelta
from textwrap import dedent

from airflow import DAG

from airflow.operators.bash import BashOperator
from airflow.utils.dates import days_ago

# These args will get passed on to each operator
# You can override them on a per-task basis during operator initialization
default_args = {
    'owner': 'airflow',
    'depends_on_past': False,
    'email': ['34a34@gmail.com'],
    'email_on_failure': True,
    'email_on_retry': True,
    'retries': 1,
    'retry_delay': timedelta(seconds=8),
}
with DAG(
    'Succeed_test',
    default_args=default_args,
    description='Test suceeding!',
    schedule_interval=timedelta(days=1),
    start_date=days_ago(2),
    tags=['debug'],
) as dag:

    t1 = BashOperator(
        task_id='succeed_every_time',
        bash_command='echo 0',
    )

    t1
```
