### ISSUE TITLE
dagrun_time doesn't trigger on_failure_callback

### ISSUE THREAD

**Issue by Mavtti** [apache/airflow#18746]
### Apache Airflow version

2.0.2

### Operating System

Debian

### Deployment

MWAA

### What happened

When calling the dag with a dagrun_timeout, if it reaches the limit, a SIGTERM is sent but the function used for on_failure_callback is not called.

### How to reproduce
```
import logging
from datetime import datetime
from datetime import timedelta

from airflow import DAG
from airflow.operators.python import PythonOperator
from macros.utils import job_config
from operators.slack import SlackOperator


# Handling naming and environment logic - do not change
config = job_config(__name__)
logging.getLogger().setLevel(logging.INFO)


# These args are passed on to each operator, and can be overriden on a per-task basis during operator initialization.
def sleep_timeout(**kwargs):
    raise Exception("test")


def fail_callback(context):
    logging.info("FAILED test")
    logging.info(context)


default_args = {
    "owner": "test",
    "start_date": datetime(2021, 7, 6),
    "on_failure_callback": fail_callback,
}


with DAG(
    dag_id=config["name"],
    default_args=default_args,
    dagrun_timeout=timedelta(seconds=5),
    schedule_interval="@daily",
    catchup=False,
    tags=[config["type"], config["env"]],
) as dag:

    crawl_task = PythonOperator(task_id="sleep_timeout", python_callable=sleep_timeout, dag=dag, provide_context=True)

```

### Anything else

Here is the log output of the DAG

```

[2021-10-05 13:46:18,913] {{logging_mixin.py:104}} INFO - [2021-10-05 13:46:18,912] {{local_task_job.py:188}} WARNING - State of this instance has been externally set to skipped. Terminating instance.
[2021-10-05 13:46:18,961] {{process_utils.py:100}} INFO - Sending Signals.SIGTERM to GPID 5739
[2021-10-05 13:46:19,006] {{taskinstance.py:1265}} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-10-05 13:46:19,066] {{taskinstance.py:1482}} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/usr/local/airflow/dags/etl_test2_staging.py", line 19, in sleep_timeout
    time.sleep(10)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1267, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2021-10-05 13:46:19,118] {{taskinstance.py:1532}} INFO - Marking task as FAILED. dag_id=test2-staging, task_id=sleep_timeout, execution_date=20211005T134610, start_date=20211005T134613, end_date=20211005T134619
[2021-10-05 13:46:19,218] {{process_utils.py:66}} INFO - Process psutil.Process(pid=5739, status='terminated', exitcode=1, started='13:46:13') (5739) terminated with exit code 1
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
I thin you should pass it directly as constructor parameter of DAG. See also #18721

**Comment by potiuk** [comment]
Ah yeah. Just see it now. Actually timeout cancels running task and on_failure_callback is not called.  You can open a new feature request - maybe it would make sense to have on_timeout_calback().
