### ISSUE TITLE
Migrate from 2.1.4 to 2.2.0

### ISSUE THREAD

**Issue by sbialkowski-pixel** [apache/airflow#18894]
### Apache Airflow version

2.2.0

### Operating System

Linux

### Versions of Apache Airflow Providers

default.

### Deployment

Docker-Compose

### Deployment details

Using airflow-2.2.0python3.7

### What happened

Upgrading image from apache/airflow:2.1.4-python3.7
to apache/airflow:2.2.0-python3.7
Cause this inside scheduler, which is not starting:

```
Python version: 3.7.12
Airflow version: 2.2.0
Node: 6dd55b0a5dd7
-------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedColumn: column dag.max_active_tasks does not exist
LINE 1: ..., dag.schedule_interval AS dag_schedule_interval, dag.max_ac...
                                                             ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/airflow/.local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/airflow/.local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/airflow/.local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/airflow/.local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/airflow/.local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/www/auth.py", line 51, in decorated
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/www/views.py", line 588, in index
    filter_dag_ids = current_app.appbuilder.sm.get_accessible_dag_ids(g.user)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/www/security.py", line 377, in get_accessible_dag_ids
    return {dag.dag_id for dag in accessible_dags}
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3535, in __iter__
    return self._execute_and_instances(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3560, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement
    distilled_params,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column dag.max_active_tasks does not exist
LINE 1: ..., dag.schedule_interval AS dag_schedule_interval, dag.max_ac...
                                                             ^

[SQL: SELECT dag.dag_id AS dag_dag_id, dag.root_dag_id AS dag_root_dag_id, dag.is_paused AS dag_is_paused, dag.is_subdag AS dag_is_subdag, dag.is_active AS dag_is_active, dag.last_parsed_time AS dag_last_parsed_time, dag.last_pickled AS dag_last_pickled, dag.last_expired AS dag_last_expired, dag.scheduler_lock AS dag_scheduler_lock, dag.pickle_id AS dag_pickle_id, dag.fileloc AS dag_fileloc, dag.owners AS dag_owners, dag.description AS dag_description, dag.default_view AS dag_default_view, dag.schedule_interval AS dag_schedule_interval, dag.max_active_tasks AS dag_max_active_tasks, dag.max_active_runs AS dag_max_active_runs, dag.has_task_concurrency_limits AS dag_has_task_concurrency_limits, dag.next_dagrun AS dag_next_dagrun, dag.next_dagrun_data_interval_start AS dag_next_dagrun_data_interval_start, dag.next_dagrun_data_interval_end AS dag_next_dagrun_data_interval_end, dag.next_dagrun_create_after AS dag_next_dagrun_create_after 
FROM dag]
(Background on this error at: http://sqlalche.me/e/13/f405)
```

### What you expected to happen

Automatic database migration and properly working scheduler.

### How to reproduce

Ugrade from 2.1.4 to 2.2.0 with some dags history.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by sbialkowski-pixel** [comment]
After deleting wrong rows airflow is working.
Thank you for help.
Can be closed.

**Comment by potiuk** [comment]
Seems other people have similar issue https://github.com/apache/airflow/discussions/18912 so for me it looks highly unlikely this was manually added. 

I think the number of reports we have in such short time (I saw 3 reports already) indicate that those rows can appear frequently as result of normal opertions by Airflow, and many users might hve similar issues soon. 

If this is realy result of "regular" airflow behaviour, for me it calls for a very quick 2.2.1 with improved migration to handle that case (cc: @kaxil @jedcunningham)

**Comment by zachliu** [comment]
just ran this in my prod db
```sql
SELECT task_instance.execution_date,
       task_instance.task_id,
       task_instance.dag_id
FROM task_instance
LEFT JOIN dag_run ON task_instance.dag_id = dag_run.dag_id
AND task_instance.execution_date = dag_run.execution_date
WHERE dag_run.run_id IS NULL;
```
my `execution_date` column is all scheduled runs i think

```
2020-01-12 00:00:00+00
2020-09-09 18:00:00+00
2020-09-09 18:00:00+00
2020-09-09 18:00:00+00
2020-09-09 18:00:00+00
2020-09-09 18:00:00+00
2020-09-09 18:00:00+00
2020-01-15 13:30:00+00
2020-01-15 13:30:00+00
2020-01-15 13:30:00+00
2020-01-15 13:30:00+00
```

**Comment by konfusator** [comment]
>  …
>   LEFT JOIN 
>     dag_run ON 
>     dag_run.dag_id = task_fail.dag_id 
>     AND dr.execution_date = task_fail.execution_date
> …

This should read »dag_run.execution_date«

**Comment by MM-Lehmann** [comment]
This becomes a bit neater with `... JOIN ... using (dag_id, execution_date)`
  

  

  

  
  
  
  
  
>

**Comment by jedcunningham** [comment]
@ldacey, yep, deleting dagruns via the UI turns out to be a common way to hit this (it's been a bug for a while it seems: #15986).

**Comment by jasonoberme** [comment]
For anyone experiencing this when testing standlone and using SQLite, delete these ids:
```

select fail_id from (
(select id as fail_id,dag_id,execution_date from task_fail ) as fail
left join
(
select dag_id,execution_date from dag_run 
) as run
on run.dag_id=fail.dag_id and fail.execution_date=run.execution_date
) where run.dag_id is null
```

**Comment by aprettyloner** [comment]
> SQL we used from our deployment playbook to clean up these tables
> 
> Obviously a disclaimer on running this blindly. Validate its rows you can safely remove first by just executing the CTEs
> 
> ```sql
> BEGIN;
> 
> -- Remove dag runs without a valid run_id
> DELETE FROM dag_run WHERE run_id is NULL;
> 
> -- Remove task fails without a run_id
> WITH task_fails_to_remove AS (
>   SELECT 
>     task_fail.dag_id,
>     task_fail.task_id,
>     task_fail.execution_date
>   FROM
>     task_fail
>   LEFT JOIN 
>     dag_run ON 
>     dag_run.dag_id = task_fail.dag_id 
>     AND dag_run.execution_date = task_fail.execution_date
>   WHERE
>     dag_run.run_id IS NULL
> )
> DELETE FROM
>     task_fail
> USING 
>     task_fails_to_remove
> WHERE (
>     task_fail.dag_id = task_fails_to_remove.dag_id
>     AND task_fail.task_id = task_fails_to_remove.task_id
>     AND task_fail.execution_date = task_fails_to_remove.execution_date
> );
> 
> -- Remove task instances without a run_id
> WITH task_instances_to_remove AS (
>   SELECT
>     task_instance.dag_id,
>     task_instance.task_id,
>     task_instance.execution_date
>   FROM
>     task_instance
>   LEFT JOIN 
>     dag_run 
>     ON dag_run.dag_id = task_instance.dag_id
>     AND dag_run.execution_date = task_instance.execution_date
>   WHERE 
>     dag_run.run_id is NULL
> )
> DELETE FROM 
>     task_instance
> USING
>     task_instances_to_remove
> WHERE (
>     task_instance.dag_id = task_instances_to_remove.dag_id
>     AND task_instance.task_id = task_instances_to_remove.task_id
>     AND task_instance.execution_date = task_instances_to_remove.execution_date
> );
> 
> COMMIT;
> ```

Thank you for this @leonsmith ! Made our team's upgrade from v2.1.4 to v2.2.3 very clean and simple! 🚀 🚀 🚀 🚀
