### ISSUE TITLE
`None` values no longer accepted in `params`

### ISSUE THREAD

**Issue by nathadfield** [apache/airflow#18909]
### Apache Airflow version

2.2.0 (latest released)

### Operating System

- PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
- NAME="Debian GNU/Linux" VERSION_ID="11"
- VERSION="11 (bullseye)"
- VERSION_CODENAME=bullseye
- ID=debian

### Deployment

Astronomer

### What happened

When providing a dict to `params`, `None` is no longer accepted as a value and the DAG fails to parse.

```
Broken DAG: [/usr/local/airflow/dags/test.py] Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/models/dag.py", line 481, in __init__
    self.validate_schedule_and_params()
  File "/usr/local/lib/python3.9/site-packages/airflow/models/dag.py", line 2636, in validate_schedule_and_params
    raise AirflowException(
airflow.exceptions.AirflowException: DAG Schedule must be None, if there are any required params without default values
```

### What you expected to happen

This is a change in behaviour from 2.1.x

### How to reproduce

The following DAG code will reproduce the error.

```
from datetime import datetime, timedelta
from airflow import models
from airflow.operators.dummy import DummyOperator

params = {
    'key': None
}

default_args = {
    'owner': 'airflow',
    'retries': 2,
    'retry_delay': timedelta(minutes=5)
}

with models.DAG(
    'my_dag',
    default_args=default_args,
    start_date=datetime(2021, 10, 1),
    schedule_interval='0 0 * * *',
    params=params
) as dag:

    test = DummyOperator(
        task_id='test'
    )
```

### Anything else

The issue is a result of the work involved in #17100; specifically the method `validate_schedule_and_params`

https://github.com/apache/airflow/blob/main/airflow/models/dag.py#L2625

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by NilsJPWerner** [comment]
I think I am running into this issue with the upgrade to 2.2.0: 

```
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/airflow/jobs/scheduler_job.py", line 587, in _execute self._run_scheduler_loop()
File "/usr/local/lib/python3.9/site-packages/astronomer/airflow/version_check/plugin.py", line 29, in run_before fn(*args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/airflow/jobs/scheduler_job.py", line 668, in _run_scheduler_loop num_queued_tis = self._do_scheduling(session)
File "/usr/local/lib/python3.9/site-packages/airflow/jobs/scheduler_job.py", line 751, in _do_scheduling callback_to_run = self._schedule_dag_run(dag_run, session)
File "/usr/local/lib/python3.9/site-packages/airflow/jobs/scheduler_job.py", line 949, in _schedule_dag_run dag = dag_run.dag = self.dagbag.get_dag(dag_run.dag_id, session=session)
File "/usr/local/lib/python3.9/site-packages/airflow/utils/session.py", line 67, in wrapper return func(*args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 186, in get_dag self._add_dag_from_db(dag_id=dag_id, session=session)
File "/usr/local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 261, in _add_dag_from_db dag = row.dag
File "/usr/local/lib/python3.9/site-packages/airflow/models/serialized_dag.py", line 180, in dag dag = SerializedDAG.from_dict(self.data) # type: Any
File "/usr/local/lib/python3.9/site-packages/airflow/serialization/serialized_objects.py", line 916, in from_dict return cls.deserialize_dag(serialized_obj['dag'])
File "/usr/local/lib/python3.9/site-packages/airflow/serialization/serialized_objects.py", line 846, in deserialize_dag v = cls._deserialize_dag_params(v)
File "/usr/local/lib/python3.9/site-packages/airflow/serialization/serialized_objects.py", line 935, in _deserialize_dag_params param_class = import_string(v['__class']) TypeError: string indices must be integers
```
