### ISSUE TITLE
SmartSensor not working when pass execution_date_fn and execution_delta to the sensor task

### ISSUE THREAD

**Issue by MartinKChen** [apache/airflow#18970]
### Apache Airflow version

2.0.2

### Operating System

Linux (AWS MWAA)

### Versions of Apache Airflow Providers

MWAA with Apache Airflow 2.0.2

### Deployment

MWAA

### What happened

Airflow raises exception when register sensor tasks if execution_date_fn/execution_delta is passed. Since function and timedelta could not be serialized when execute json.dumps at [airflow/models/sensorinstance, FUNCTION register](https://github.com/apache/airflow/blob/e6c56c4ae475605636f4a1b5ab3884383884a8cf/airflow/models/sensorinstance.py#L94)

- Exception when execution_date_fn is passed
```
[2021-10-14 03:27:05,754] {{taskinstance.py:1303}} ERROR - Object of type function is not JSON serializable
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1298, in _prepare_and_execute_task_with_callbacks
    registered = task_copy.register_in_sensor_service(self, context)
  File "/usr/local/lib/python3.7/site-packages/airflow/sensors/base.py", line 163, in register_in_sensor_service
    return SensorInstance.register(ti, poke_context, execution_context)
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/sensorinstance.py", line 114, in register
    encoded_poke = json.dumps(poke_context)
  File "/usr/lib64/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib64/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib64/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type function is not JSON serializable
```

- Exception when execution_delta is passed
```
[2021-10-14 05:54:58,526] {{taskinstance.py:1303}} ERROR - Object of type timedelta is not JSON serializable
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1298, in _prepare_and_execute_task_with_callbacks
    registered = task_copy.register_in_sensor_service(self, context)
  File "/usr/local/lib/python3.7/site-packages/airflow/sensors/base.py", line 163, in register_in_sensor_service
    return SensorInstance.register(ti, poke_context, execution_context)
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/sensorinstance.py", line 114, in register
    encoded_poke = json.dumps(poke_context)
  File "/usr/lib64/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib64/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib64/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type timedelta is not JSON serializable
```

### What you expected to happen

Smart Sensor should work fine as it does in base sensor.

### How to reproduce

1. Enable SmartSensor
2. Pass execution_date_fn or execution_delta to the sensor task.

### Anything else

Should extend the JSON serialize to support objects serialization.

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
SmartSensor is deprecated you should migrate to Deferrable Operators
https://airflow.apache.org/docs/apache-airflow/stable/concepts/smart-sensors.html#migrating-to-deferrable-operators
