### ISSUE TITLE
Shard of SmartSensor keep terminating itself

### ISSUE THREAD

**Issue by MartinKChen** [apache/airflow#19043]
### Apache Airflow version

2.0.2

### Operating System

Linux (AWS MWAA)

### Versions of Apache Airflow Providers

MWAA with Apache Airflow 2.0.2

### Deployment

MWAA

### What happened

Shard tasks of SmartSensor keep terminated randomly and with no logs.

**Case 1: Shard been terminated after tasks sensed without any log.**
[2021-10-18 07:10:15,580] {{smart_sensor.py:358}} INFO - Performance query 0 tis, time: 0.008
[2021-10-18 07:10:15,605] {{smart_sensor.py:373}} INFO - 0 tasks detected.
[2021-10-18 07:10:15,633] {{smart_sensor.py:739}} INFO - Loaded 0 sensor_works
[2021-10-18 07:10:15,666] {{smart_sensor.py:747}} INFO - Taking 0.09376 to execute 0 tasks.
[2021-10-18 07:13:15,671] {{smart_sensor.py:358}} INFO - Performance query 0 tis, time: 0.014
[2021-10-18 07:13:15,736] {{smart_sensor.py:373}} INFO - 0 tasks detected.
[2021-10-18 07:13:15,768] {{smart_sensor.py:739}} INFO - Loaded 0 sensor_works
[2021-10-18 07:13:15,844] {{smart_sensor.py:747}} INFO - Taking 0.186399 to execute 0 tasks.
[2021-10-18 07:16:15,794] {{smart_sensor.py:358}} INFO - Performance query 4 tis, time: 0.008
[2021-10-18 07:35:25,736] {{process_utils.py:100}} INFO - Sending Signals.SIGTERM to GPID 13284
[2021-10-18 07:35:25,996] {{process_utils.py:66}} INFO - Process psutil.Process(pid=13284, status='terminated', exitcode=1, started='07:10:13') (13284) terminated with exit code 1

**Case 2: Shard been terminated after 1 day with 0 task sensed within the cycle (last for around 24 hours). And the log is unclear to what cause the termination**
[2021-10-13 07:27:28,922] {{smart_sensor.py:358}} INFO - Performance query 0 tis, time: 0.013
[2021-10-13 07:27:28,989] {{smart_sensor.py:373}} INFO - 0 tasks detected.
[2021-10-13 07:27:29,021] {{smart_sensor.py:739}} INFO - Loaded 0 sensor_works
[2021-10-13 07:27:29,044] {{smart_sensor.py:747}} INFO - Taking 0.135416 to execute 0 tasks.
[2021-10-13 07:30:29,065] {{smart_sensor.py:358}} INFO - Performance query 0 tis, time: 0.012
[2021-10-13 07:30:29,114] {{smart_sensor.py:373}} INFO - 0 tasks detected.
[2021-10-13 07:30:29,141] {{smart_sensor.py:739}} INFO - Loaded 0 sensor_works
[2021-10-13 07:30:29,163] {{smart_sensor.py:747}} INFO - Taking 0.11131 to execute 0 tasks.
[2021-10-13 07:33:29,155] {{smart_sensor.py:358}} INFO - Performance query 0 tis, time: 0.006
[2021-10-13 07:33:29,201] {{smart_sensor.py:373}} INFO - 0 tasks detected.
.......
[2021-10-14 07:25:25,821] {{smart_sensor.py:358}} INFO - Performance query 0 tis, time: 0.006
[2021-10-14 07:25:25,870] {{smart_sensor.py:373}} INFO - 0 tasks detected.
[2021-10-14 07:25:25,896] {{smart_sensor.py:739}} INFO - Loaded 0 sensor_works
[2021-10-14 07:25:25,922] {{smart_sensor.py:747}} INFO - Taking 0.10663 to execute 0 tasks.
[2021-10-14 07:27:30,839] {{process_utils.py:100}} INFO - Sending Signals.SIGTERM to GPID 25285
[2021-10-14 07:27:30,933] {{taskinstance.py:1265}} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-10-14 07:27:31,028] {{taskinstance.py:1482}} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/sensors/smart_sensor.py", line 754, in execute
    sleep(self.poke_interval - duration)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1267, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2021-10-14 07:27:31,060] {{taskinstance.py:1532}} INFO - Marking task as UP_FOR_RETRY. dag_id=smart_sensor_group_shard_1, task_id=smart_sensor_task, execution_date=20211013T072226, start_date=20211013T072728, end_date=20211014T072731
[2021-10-14 07:27:31,146] {{process_utils.py:66}} INFO - Process psutil.Process(pid=25285, status='terminated', exitcode=1, started='2021-10-13 07:27:28') (25285) terminated with exit code 1

### What you expected to happen

1. Shards of SmartSensor should not be terminated unless there is an error occured
2. If Shards are terminated due to any errors, there should have corresponding logs when we check task log of the Shard.

### How to reproduce

1. Enable SmartSensor
2. Schedule DAGs with SmartSensor enabled operators.
3. Let the DAG run for couple hours/days.

### Anything else

The error/termination occurs every couple seconds/hours with no pattern. Which cause us hard to monitor as most of them are just false alarm due to the self-termination.

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by xiaochong2dai** [comment]
Hi @MartinKChen did you find a way to fix the issue? I'm on airflow 2.0.2 and having the same issue. I wonder if there is a way to at least reset the timeout for smart_sensor_group_shard.

**Comment by MartinKChen** [comment]
@xiaochong2dai I did not fix the issue by modifying Airflow's source code as we are using MWAA (Amazon Managed Workflow for Apache Airflow), which make it impossible to reach the code.

Alternatively, a workaround for the issue is create our own operator and DAGs for shard group.

1. Create an operator that inherit from SmartSensorOperator, which used by Shards, and overwrite the "execute" function by comment out the code causes Shard fail. Following the sample code:
```
# import base class
# Airflow
from airflow.sensors.smart_sensor import SmartSensorOperator
from airflow.stats import Stats
from airflow.utils import timezone
from airflow.utils.net import get_hostname
from airflow.utils.decorators import apply_defaults

# (General) import modules/classes for processing
from time import sleep

class MySmartSensorOperator(SmartSensorOperator):
    @apply_defaults
    def __init__(
        self,
        poke_interval=60, # overwrite the poke interval by our own requirement, which was not allowed by default
        smart_sensor_timeout=60 * 60 * 24 * 7,
        soft_fail=False,
        shard_min=0,
        shard_max=100000,
        poke_timeout=6.0,
        *args,
        **kwargs,
    ):
        super().__init__(*args, **kwargs)
        
        self.poke_interval = poke_interval
        self.soft_fail = soft_fail
        self.timeout = smart_sensor_timeout
        self._validate_input_values()
        self.hostname = ''

        self.sensor_works = []
        self.cached_dedup_works = {}
        self.cached_sensor_exceptions = {}

        self.max_tis_per_query = 50
        self.shard_min = shard_min
        self.shard_max = shard_max
        self.poke_timeout = poke_timeout

    def execute(self, context):
        # started_at = timezone.utcnow()

        self.hostname = get_hostname()
        
        while True:
            poke_start_time = timezone.utcnow()

            self.flush_cached_sensor_poke_results()

            self._load_sensor_works()
            self.log.info('Loaded %s sensor_works', len(self.sensor_works))
            Stats.gauge('smart_sensor_operator.loaded_tasks', len(self.sensor_works))

            for sensor_work in self.sensor_works:
                self._execute_sensor_work(sensor_work)

            duration = (timezone.utcnow() - poke_start_time).total_seconds()

            self.log.info('Taking %s to execute %s tasks.', duration, len(self.sensor_works))

            Stats.timing('smart_sensor_operator.loop_duration', duration)
            Stats.gauge('smart_sensor_operator.executed_tasks', len(self.sensor_works))
            self._emit_loop_stats()

            if duration < self.poke_interval:
                sleep(self.poke_interval - duration)
            
            # comment out the code that causes shard fail
            # if (timezone.utcnow() - started_at).total_seconds() > self.timeout:
            #     self.log.info('Time is out for smart sensor.')
            #     return
```
2. Create Shard DAGs that uses the operator above. Which copied from "airflow-2.0.2\airflow\smart_sensor_dags\smart_sensor_group.py" with different Operator.
```
"""Smart sensor DAGs managing all smart sensor tasks."""
from datetime import timedelta

from airflow.configuration import conf
from airflow.models import DAG
from airflow.utils.dates import days_ago


from operators.mec_smartsensor_operator import MySmartSensorOperator

default_args = {
    'owner': 'admin',
    'depends_on_past': False,
    'email_on_failure': False,
    'email_on_retry': False,
    'retries': 0,
    'start_date': days_ago(1),
    'catchup': False,
}

schedule_interval = timedelta(minutes=5)

num_smart_sensor_shard = conf.getint('smart_sensor', 'shards')
shard_code_upper_limit = conf.getint('smart_sensor', 'shard_code_upper_limit')

for i in range(num_smart_sensor_shard):
    shard_min = (i * shard_code_upper_limit) / num_smart_sensor_shard
    shard_max = ((i + 1) * shard_code_upper_limit) / num_smart_sensor_shard
    
    dag_id=f'admin_my_smartsensor_{i}'
    
    dag = DAG(
        dag_id=dag_id,
        default_args=default_args,
        schedule_interval=schedule_interval,
        concurrency=1,
        max_active_runs=1,
        dagrun_timeout=timedelta(hours=24),
    )
    
    MySmartSensorOperator(
        task_id='smart_sensor_task',
        dag=dag,
        retries=100,
        retry_delay=timedelta(seconds=10),
        priority_weight=999,
        shard_min=shard_min,
        shard_max=shard_max,
        poke_timeout=10,
        smart_sensor_timeout=timedelta(hours=1).total_seconds(),
    )

    globals()[dag_id] = dag
```


There is a downside for the solution that smart_sensor_group_shard_* created by Airflow sill been created automatically as they are generated by Airflow itself, we just keep it suspended, and enable our own DAGs instead, which may cause confusion when operating.

**Comment by xiaochong2dai** [comment]
Thank you so much @MartinKChen for the detailed explanation!

**Comment by eladkal** [comment]
It's unlikely that this bug/problem will be explored as SmarSensor is a deprecated feature
I suggest that you will move to deferrable operators.
https://airflow.apache.org/docs/apache-airflow/stable/concepts/deferring.html#smart-sensors

I'm moving this issue to Github Discussions
