### ISSUE TITLE
airflow db reset throws error while initialising breeze with python version 3.8 and mysql as backend

### ISSUE THREAD

**Issue by Bowrna** [apache/airflow#19104]
### Apache Airflow version

main (development)

### Operating System

macOS

### Deployment

Other Docker-based deployment

### Deployment details

https://github.com/apache/airflow/blob/main/CONTRIBUTORS_QUICK_START.rst#id1
Following the instructions on the above page to set up the development environment for Apache Airflow. Breeze environment is initialized and I am inside the docker container. On running `airflow db reset`, to create db/tables, i get error.

### What happened

Got the below logs when running `airflow db reset`:

```INFO  [alembic.runtime.migration] Running upgrade d2ae31099d61 -> 0e2a74e0fc9f, Add time zone awareness
Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 33, in <module>
    sys.exit(load_entry_point('apache-airflow', 'console_scripts', 'airflow')())
  File "/opt/airflow/airflow/__main__.py", line 40, in main
    args.func(args)
  File "/opt/airflow/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/opt/airflow/airflow/cli/commands/db_command.py", line 39, in resetdb
    db.resetdb()
  File "/opt/airflow/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/opt/airflow/airflow/utils/db.py", line 883, in resetdb
    initdb(session=session)
  File "/opt/airflow/airflow/utils/session.py", line 67, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/airflow/utils/db.py", line 591, in initdb
    upgradedb(session=session)
  File "/opt/airflow/airflow/utils/session.py", line 67, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/airflow/utils/db.py", line 868, in upgradedb
    command.upgrade(config, 'heads')
  File "/usr/local/lib/python3.8/site-packages/alembic/command.py", line 320, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.8/site-packages/alembic/script/base.py", line 563, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 92, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 108, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/airflow/migrations/env.py", line 107, in <module>
    run_migrations_online()
  File "/opt/airflow/airflow/migrations/env.py", line 101, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/local/lib/python3.8/site-packages/alembic/runtime/environment.py", line 851, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/lib/python3.8/site-packages/alembic/runtime/migration.py", line 620, in run_migrations
    step.migration_fn(**kw)
  File "/opt/airflow/airflow/migrations/versions/0e2a74e0fc9f_add_time_zone_awareness.py", line 44, in upgrade
    raise Exception("Global variable explicit_defaults_for_timestamp needs to be on (1) for mysql")
Exception: Global variable explicit_defaults_for_timestamp needs to be on (1) for mysql
```

### What you expected to happen

Expected behaviour to run db reset without error and create db/ table required to start airflow in development mode. i have rebased the code recently with apache/airflow and running the code in `main` branch

### How to reproduce

https://github.com/apache/airflow/blob/main/CONTRIBUTORS_QUICK_START.rst#id1

Following the instructions in above docs, python version 3.8 and backend as mysql. on trying the steps mentioned in docs, i get the issues

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
That would be strange- maybe you connect to a different schema and it needs to be set 'per schema' ?

**Comment by Bowrna** [comment]
On further verification,

I connected to the mysql that starts up as docker container via docker-compose as part of airflow installation and found `airflow` database created there. 

I verified `explicit_defaults_for_timestamp` key and found out it is OFF. Attaching the screenshots for more clarification,
<img width="1259" alt="Screenshot 2021-10-21 at 12 13 03 PM" src="https://user-images.githubusercontent.com/10162465/138225382-76acc9d5-61e9-4bf8-bef2-de2949d2de8f.png">
<img width="1024" alt="Screenshot 2021-10-21 at 12 14 22 PM" src="https://user-images.githubusercontent.com/10162465/138225416-be7c6de6-1968-450b-ad6d-5f77412fb0ee.png">

I connected to the mysql running in port 23306 via tcp to check this. That mysql(version 5.7) has started as part of airflow installation. Is it expected to have `explicit_defaults_for_timestamp ` key set ON by default.

**Comment by potiuk** [comment]
I guess it can be closed now.

**Comment by Bowrna** [comment]
yes sure. thank you @potiuk

**Comment by lrbsantos** [comment]
Hi @Bowrna, did you find the reason and a fix for this issue? I am facing the same problem right now. I checked the files as @potiuk recommended and each one of them seems to be ok.

**Comment by Bowrna** [comment]
Hi, @lrbsantos Currently I am using SQLite as the backend as I got other issues when working with MySQL. But I tried setting `explicit_defaults_for_timestamp` key set as ON and tried again. May be you could try that too?

**Comment by potiuk** [comment]
> Hi @Bowrna, did you find the reason and a fix for this issue? I am facing the same problem right now. I checked the files as @potiuk recommended and each one of them seems to be ok.

Just run `./breeze stop` first. And restart ./breeze after. It shoudl help

**Comment by lrbsantos** [comment]
> Hi, @lrbsantos Currently I am using SQLite as the backend as I got other issues when working with MySQL. But I tried setting `explicit_defaults_for_timestamp` key set as ON and tried again. May be you could try that too?

Hi @Bowrna thank you for your reply. I switched to SQLite, as you commented, and now it's working fine. @potiuk thank you for your support too, I tried all alternatives that you recommended about this issue, but I didn't get MySQL to work as the backend.
