### ISSUE TITLE
ERROR - No module named 'celery_config' when triggering a separate task in Airflow on Docker

### ISSUE THREAD

**Issue by alexey-rio** [apache/airflow#19146]
### Apache Airflow version

2.2.0 (latest released)

### Operating System

public.ecr.aws/amazonlinux/amazonlinux (Docker)

### Versions of Apache Airflow Providers

apache-airflow-providers-amazon==1.3.0
apache-airflow-providers-celery==1.0.1
apache-airflow-providers-databricks==1.0.1
apache-airflow-providers-docker==1.2.0
apache-airflow-providers-ftp==1.0.1
apache-airflow-providers-http==1.1.1
apache-airflow-providers-imap==1.0.1
apache-airflow-providers-oracle==1.1.0
apache-airflow-providers-postgres==1.0.2
apache-airflow-providers-presto==1.0.2
apache-airflow-providers-sftp==1.2.0
apache-airflow-providers-sqlite==1.0.2
apache-airflow-providers-ssh==1.3.0
apache-airflow-providers-tableau==1.0.0

### Deployment

Other Docker-based deployment

### Deployment details

Running deployment on Docker for Local MWAA 
aws-mwaa-local-runner:
https://github.com/aws/aws-mwaa-local-runner

Python version: 3.7.10
Airflow version: 2.2.0
Node: redact

### What happened

When triggering a single task instance through the UI (on demand), as soon as I click Run I get an error "Ooops!
Something bad has happened."

Here is the stack trace: 

```
local-runner_1  | /usr/local/lib/python3.7/site-packages/airflow/configuration.py:361 DeprecationWarning: The default_queue option in [celery] has been moved to the default_queue option in [operators] - the old setting has been used, but please update your config.
local-runner_1  | [2021-10-22 05:21:40,118] {{configuration.py:484}} ERROR - No module named 'celery_config'
local-runner_1  | [2021-10-22 05:21:40,124] {{app.py:1892}} ERROR - Exception on /run [POST]
local-runner_1  | Traceback (most recent call last):
local-runner_1  |   File "/usr/local/lib/python3.7/site-packages/airflow/configuration.py", line 482, in getimport
local-runner_1  |     return import_string(full_qualified_path)
local-runner_1  |   File "/usr/local/lib/python3.7/site-packages/airflow/utils/module_loading.py", line 32, in import_string
local-runner_1  |     module = import_module(module_path)
local-runner_1  |   File "/usr/lib64/python3.7/importlib/__init__.py", line 127, in import_module
local-runner_1  |     return _bootstrap._gcd_import(name[level:], package, level)
local-runner_1  |   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
local-runner_1  |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
local-runner_1  |   File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
local-runner_1  | ModuleNotFoundError: No module named 'celery_config'
local-runner_1  | 
local-runner_1  | During handling of the above exception, another exception occurred:
local-runner_1  | 
local-runner_1  | Traceback (most recent call last):
local-runner_1  |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
local-runner_1  |     response = self.full_dispatch_request()
local-runner_1  |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
local-runner_1  |     rv = self.handle_user_exception(e)
local-runner_1  |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
local-runner_1  |     reraise(exc_type, exc_value, tb)
local-runner_1  |   File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
local-runner_1  |     raise value
local-runner_1  |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
local-runner_1  |     rv = self.dispatch_request()
local-runner_1  |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
local-runner_1  |     return self.view_functions[rule.endpoint](**req.view_args)
local-runner_1  |   File "/usr/local/lib/python3.7/site-packages/airflow/www/auth.py", line 51, in decorated
local-runner_1  |     return func(*args, **kwargs)
local-runner_1  |   File "/usr/local/lib/python3.7/site-packages/airflow/www/decorators.py", line 72, in wrapper
local-runner_1  |     return f(*args, **kwargs)
local-runner_1  |   File "/usr/local/lib/python3.7/site-packages/airflow/www/views.py", line 1525, in run
local-runner_1  |     from airflow.executors.celery_executor import CeleryExecutor
local-runner_1  |   File "/usr/local/lib/python3.7/site-packages/airflow/executors/celery_executor.py", line 72, in <module>
local-runner_1  |     celery_configuration = conf.getimport('celery', 'celery_config_options')
local-runner_1  |   File "/usr/local/lib/python3.7/site-packages/airflow/configuration.py", line 486, in getimport
local-runner_1  |     f'The object could not be loaded. Please check "{key}" key in "{section}" section. '
local-runner_1  | airflow.exceptions.AirflowConfigException: The object could not be loaded. Please check "celery_config_options" key in "celery" section. Current value: "celery_config.CUSTOM_CELERY_CONFIG".
```

### What you expected to happen

single task is triggered on-demand and running 

### How to reproduce

1.  Start Apache airflow locally in docker environment 
2. Create a sample DAG
3. Go into Graph View
4. Click on the Task Instance
5. Click Run

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by rafidka** [comment]
@alexmolodchikov , did you end up reaching out? Is there an issue?

**Comment by alordthorsen** [comment]
I have also hit this issue and I've requested help from AWS support. Though in my case I hit this in MWAA 2.2.2.
