### ISSUE TITLE
EMRContainerOperator with timeout after 1 hour

### ISSUE THREAD

**Issue by luissantanacontato** [apache/airflow#19171]
### Apache Airflow Provider(s)

amazon

### Versions of Apache Airflow Providers

apache-airflow-providers-amazon==2.2.0

### Apache Airflow version

2.1.0

### Operating System

Ubuntu 20.04.3 LTS

### Deployment

Docker-Compose

### What happened

After 1 hour using EMRContainerOperator:

`    start_job_run = EMRContainerOperator(
        task_id='motor_{}'.format(table.lower()),
        name='motor_{}'.format(table.lower()),
        virtual_cluster_id=emr_virtual_cluster_id,
        execution_role_arn=emr_execution_role_arn,
        release_label='emr-6.3.0-latest',
        job_driver=JOB_DRIVER,
        configuration_overrides=CONFIGURATION_OVERRIDES,
        aws_conn_id='aws_default',
        pool='jdbc'
    )`

I recevied the follow message:

`[2021-10-22 19:06:52,687] {emr_containers.py:184} INFO - Try 1: Query execution completed. Final state is CANCEL_PENDING
[2021-10-22 19:06:52,710] {taskinstance.py:1481} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1137, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1336, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/amazon/aws/operators/emr_containers.py", line 111, in execute
    query_status = self.hook.poll_query_status(self.job_id, self.max_tries, self.poll_interval)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/amazon/aws/hooks/emr_containers.py", line 191, in poll_query_status
    sleep(poll_interval)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/timeout.py", line 37, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: Timeout, PID: 677619`

In documentation I did not find about timeout parameter in Operator. 

Thank you. 

### What you expected to happen

The Operator continues executing.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eskarimov** [comment]
Hello @luissantanacontato ,
just wanted to ping you about the issue, if you could have a look on the previous comment, please?

**Comment by eskarimov** [comment]
Not sure how we should proceed with the issue - I've checked what I could, haven't found an issue in code so far and couldn't reproduce the issue either. The author of the issue hasn't replied on request for additional info yet
