### ISSUE TITLE
Checking roles and users list in Web UI, give me an error

### ISSUE THREAD

**Issue by nediGit** [apache/airflow#19556]
### Apache Airflow version

2.1.2

### Operating System

Centos 7

### Versions of Apache Airflow Providers

apache-airflow-providers-ftp==2.0.0
apache-airflow-providers-http==2.0.1
apache-airflow-providers-imap==2.0.0
apache-airflow-providers-microsoft-mssql==2.0.0
apache-airflow-providers-odbc==2.0.0
apache-airflow-providers-postgres==2.2.0
apache-airflow-providers-sqlite==2.0.0

### Deployment

Composer

### Deployment details

Follow the installation steps in the documentation, nothing more, nothing less

### What happened

I try to check the users list, or roles, from the webIU, and give me these error

### What you expected to happen

See the list of the users or roles

### How to reproduce

Install Apache Airflow 2.1.2, using SQLite, no changes at all

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bbovenzi** [comment]
Can you please include the error message or screenshots?

**Comment by nediGit** [comment]
Sure, selecting List Users
![image](https://user-images.githubusercontent.com/29753976/141512709-2790d0f4-da48-403f-b19e-777ba5ae7df7.png)

And the error:

Something bad has happened.
Please consider letting us know by creating a bug report using GitHub.

Python version: 3.6.8
Airflow version: 2.1.2
Node: robots-kube003.nosis.interno
-------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dlabrador@nosis.interno/.local/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dlabrador@nosis.interno/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dlabrador@nosis.interno/.local/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dlabrador@nosis.interno/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/dlabrador@nosis.interno/.local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dlabrador@nosis.interno/.local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/dlabrador@nosis.interno/.local/lib/python3.6/site-packages/flask_appbuilder/security/decorators.py", line 109, in wraps
    return f(self, *args, **kwargs)
  File "/home/dlabrador@nosis.interno/.local/lib/python3.6/site-packages/flask_appbuilder/views.py", line 551, in list
    widgets = self._list()
  File "/home/dlabrador@nosis.interno/.local/lib/python3.6/site-packages/flask_appbuilder/baseviews.py", line 1136, in _list
    form = self.search_form.refresh()
  File "/home/dlabrador@nosis.interno/.local/lib/python3.6/site-packages/flask_appbuilder/forms.py", line 329, in refresh
    form = self(obj=obj)
  File "/usr/local/lib/python3.6/site-packages/wtforms/form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/home/dlabrador@nosis.interno/.local/lib/python3.6/site-packages/flask_wtf/form.py", line 87, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/wtforms/form.py", line 268, in __init__
    super(Form, self).__init__(self._unbound_fields, meta=meta_obj, prefix=prefix)
  File "/usr/local/lib/python3.6/site-packages/wtforms/form.py", line 51, in __init__
    field = meta.bind_field(self, unbound_field, options)
  File "/usr/local/lib/python3.6/site-packages/wtforms/meta.py", line 27, in bind_field
    return unbound_field.bind(form=form, **options)
  File "/usr/local/lib/python3.6/site-packages/wtforms/fields/core.py", line 376, in bind
    return self.field_class(*self.args, **kw)
  File "/home/dlabrador@nosis.interno/.local/lib/python3.6/site-packages/flask_appbuilder/fields.py", line 182, in __init__
    "allow_blank=True does not do anything for QuerySelectMultipleField."
  File "/usr/lib64/python3.6/warnings.py", line 99, in _showwarnmsg
    msg.file, msg.line)
  File "/home/dlabrador@nosis.interno/.local/lib/python3.6/site-packages/airflow/settings.py", line 114, in custom_show_warning
    write_console.print(msg, soft_wrap=True)
  File "/home/dlabrador@nosis.interno/.local/lib/python3.6/site-packages/rich/console.py", line 1601, in print
    self._buffer.extend(new_segments)
  File "/home/dlabrador@nosis.interno/.local/lib/python3.6/site-packages/rich/console.py", line 815, in __exit__
    self._exit_buffer()
  File "/home/dlabrador@nosis.interno/.local/lib/python3.6/site-packages/rich/console.py", line 774, in _exit_buffer
    self._check_buffer()
  File "/home/dlabrador@nosis.interno/.local/lib/python3.6/site-packages/rich/console.py", line 1824, in _check_buffer
    self.file.write(text)
OSError: [Errno 5] Input/output error

**Comment by uranusjr** [comment]
Hmm, this very much looks like a Flask-Appbuilder bug. Unfortunately the last four stacks (the `rich` part) is masking the real error here, it raises an exception when trying to write the actual error. Not sure if there’s a way to disable Rich so we can get the actual problem.

**Comment by uranusjr** [comment]
@willmcgugan Do you happen to know what would cause the `OSError: [Errno 5] Input/output error` exception to be reached so maybe we can fix that first?

**Comment by eladkal** [comment]
Is this still happens in main version? We upgraded flask versions.
@nediGit can you please check?
