### ISSUE TITLE
Unable to create a WinRM Connection with apache-airflow-providers-microsoft-winrm installed

### ISSUE THREAD

**Issue by abouquet** [apache/airflow#19739]
### Apache Airflow Provider(s)

microsoft-winrm

### Versions of Apache Airflow Providers

![2021-11-22_11h00_15](https://user-images.githubusercontent.com/2518542/142842528-a984d294-fad4-46c5-b773-57915ae58fc4.png)

### Apache Airflow version

2.2.2 (latest released)

### Operating System

Windows Docker WSL2

### Deployment

Docker-Compose

### Deployment details

[airflow.zip](https://github.com/apache/airflow/files/7579975/airflow.zip)

### What happened

Unable to create a WinRM Connection
Provider is installed and viewable on dashboard
![2021-11-22_11h00_15](https://user-images.githubusercontent.com/2518542/142842055-3ade8a0e-61be-4d5f-8317-f41b77de4136.png)

### What you expected to happen

We should be able to create a WinRM Connection on "Admin -> Connections"

![image](https://user-images.githubusercontent.com/2518542/142842196-4a8a77ca-cdf7-4071-98bc-93cebe9c77d9.png)

### How to reproduce

1) Unzip the sample provided on deployment detail part
2) Run `docker-compose up airflow-init`
3) Run `docker-compose up`
4) Go on http://localhost:8080/connection/add => There isn't WinRM connection available on connection template

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
It's not a bug - simply WinRM connection does not have custom connection type defined (which is perfectly fine - you can use any type of connection for that - for example HTTP (it only uses host/login/password) - but if you think it's a good idea and you miss it, you can make a PR and add one - you could add custom connection configuration for it: https://airflow.apache.org/docs/apache-airflow/stable/howto/connection.html#custom-connection-types

**Comment by abouquet** [comment]
Ok thanks for your answer ! 

In that case why don't we  name a new connection called "generic connection".
Maybe it could improve understanding on when we can use it (and improve documentation of providers that don't need custom conenction

**Comment by potiuk** [comment]
> In that case why don't we name a new connection called "generic connection". Maybe it could improve understanding on when we can use it (and improve documentation of providers that don't need custom conenction

That's a good feature to add. Can you add another feature request for it please ? Or maybe even straight add PR - for that - that's a simple feature to add, no need to raise an issue for it.

**Comment by abouquet** [comment]
I'm not a python developer ;-).

But will check it out if I can got for it !

**Comment by potiuk** [comment]
It should be basically as easy as adding new connection type here (and possibly adding/fixing some tests). https://github.com/apache/airflow/blob/56bdfe7a840c25360d596ca94fd11d2ccfadb4ba/airflow/www/views.py#L3290

**Comment by abouquet** [comment]
Have tried to connect on the server using "HTTP" connection type.

It seems test button doesnt pass.

I'm using AD connexion that's why there is a domain in the credential with `SIM\a.bouquet` 

```
airflow-airflow-webserver-1  | [2021-11-22 14:09:17,951] {base.py:79} INFO - Using connection to: id: iCl986EL. Host: 192.168.68.43, Port: 5985, Schema: , Login: SIM\a.bouquet, Password: <redacted>, 
extra: {}
airflow-airflow-webserver-1  | [2021-11-22 14:09:17,951] {http.py:140} INFO - Sending 'POST' to url: http://192.168.68.43:5985
airflow-airflow-webserver-1  | [2021-11-22 14:09:18,011] {http.py:154} ERROR - HTTP error: Not Found
airflow-airflow-webserver-1  | [2021-11-22 14:09:18,011] {http.py:155} ERROR - <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
airflow-airflow-webserver-1  | <HTML><HEAD><TITLE>Not Found</TITLE>
airflow-airflow-webserver-1  | <META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
airflow-airflow-webserver-1  | <BODY><h2>Not Found</h2>
airflow-airflow-webserver-1  | <hr><p>HTTP Error 404. The requested resource is not found.</p>
airflow-airflow-webserver-1  | </BODY></HTML>
airflow-airflow-webserver-1  |
```

Has anyone succeed into configuring a WinRM Provider ? 

WinRM is activated and UP on server side

![image](https://user-images.githubusercontent.com/2518542/142876854-21d90af9-6143-4e28-a228-26a06c34eac3.png)

**Comment by eladkal** [comment]
@phanikumv maybe you'll be interested in adding test connection functionality here?

**Comment by phanikumv** [comment]
sure @eladkal I can take it up

**Comment by eladkal** [comment]
@phanikumv are you working on this issue?

**Comment by phanikumv** [comment]
i am analyzing this and will create a PR once done

**Comment by phanikumv** [comment]
I didnt manage to get the WinRM connection working from Airflow. I spun up a Windows machine on AWS and tried to connect to it from my local Airflow instance. But i am getting a bunch of network connection issues. 

Need more time to investigate it  or if any one has more expertise on WinRM they can pick it up. Hence unassigning myself.

cc @eladkal

**Comment by potiuk** [comment]
@malthe had been mostly working on it. Maybe he can help?

**Comment by malthe** [comment]
There is no support for connection testing as @potiuk mentions, but +1 on getting it. It should be easy enough to implement.

@arjunanan6 – might be something for you?

**Comment by arjunanan6** [comment]
Sure, I could take this one up - but I cannot promise when it will be done. If that's okay, please feel free to assign it to me.

**Comment by arjunanan6** [comment]
@potiuk Please assign it to me, I can work on this.

**Comment by eladkal** [comment]
@arjunanan6 are you still working on this issue?

**Comment by arjunanan6** [comment]
@eladkal Yes, I still plan to work on this. I just have not had time to start yet due to various circumstances. :(
But if someone else wants to work on it, please feel free to re-assign.

**Comment by eladkal** [comment]
No rush just wanted to make sure it wasn't forgotten

**Comment by arjunanan6** [comment]
Alright, so I've just gotten back to this and I am wondering if I can get some help. I think I have the `test_connection()` part ready, but I cannot seem to define the new connection type of PSRP. For this, I've added the following to `airflow.providers.microsoft.psrp.hooks.psrp`:

```
conn_type = "psrp"
hook_name = "PSRP"
```

However, this does not show up in the Connection Type dropdown menu. Any pointer on what I am missing would be appreciated.

**Comment by arjunanan6** [comment]
I think I've read the documentation properly to add a new connection type, but I can't seem to get it to show up. I've pushed my changes in #34766. @eladkal @phanikumv could you maybe give a pointer as to what I am missing here?

**Comment by sksirajbasha** [comment]
Not sure if this is the right thread. The winrm connection with this provider always fails. IT works via Rundeck when used with same credentials. Errs out with airflow for the same server and creds. Error: 

enterprise-airflow-worker-567cd9f6d8-8ptn2
*** Found local files:
***   * /opt/airflow/logs/dag_id=winrm_connection_test/run_id=manual__2023-11-24T10:04:01.385245+00:00/task_id=wintask3/attempt=1.log
[2023-11-24, 10:04:03 UTC] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: winrm_connection_test.wintask3 manual__2023-11-24T10:04:01.385245+00:00 [queued]>
[2023-11-24, 10:04:03 UTC] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: winrm_connection_test.wintask3 manual__2023-11-24T10:04:01.385245+00:00 [queued]>
[2023-11-24, 10:04:03 UTC] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-11-24, 10:04:03 UTC] {taskinstance.py:1327} INFO - Executing <Task(WinRMOperator): wintask3> on 2023-11-24 10:04:01.385245+00:00
[2023-11-24, 10:04:03 UTC] {standard_task_runner.py:57} INFO - Started process 11745 to run task
[2023-11-24, 10:04:03 UTC] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'winrm_connection_test', 'wintask3', 'manual__2023-11-24T10:04:01.385245+00:00', '--job-id', '1455343', '--raw', '--subdir', 'DAGS_FOLDER/winrm_connect_cmd.py', '--cfg-path', '/tmp/tmp5aafbaf1']
[2023-11-24, 10:04:03 UTC] {standard_task_runner.py:85} INFO - Job 1455343: Subtask wintask3
[2023-11-24, 10:04:03 UTC] {task_command.py:410} INFO - Running <TaskInstance: winrm_connection_test.wintask3 manual__2023-11-24T10:04:01.385245+00:00 [running]> on host enterprise-airflow-worker-567cd9f6d8-8ptn2
[2023-11-24, 10:04:03 UTC] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='winrm_connection_test' AIRFLOW_CTX_TASK_ID='wintask3' AIRFLOW_CTX_EXECUTION_DATE='2023-11-24T10:04:01.385245+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-24T10:04:01.385245+00:00'
[2023-11-24, 10:04:03 UTC] {base.py:73} INFO - Using connection ID 'windows_<hostname>' for task execution.
[2023-11-24, 10:04:03 UTC] {winrm.py:211} INFO - Establishing WinRM connection to host: <hostname>
[2023-11-24, 10:04:03 UTC] {winrm.py:216} ERROR - Error connecting to host: <hostname>, error: the specified credentials were rejected by the server
[2023-11-24, 10:04:04 UTC] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/winrm/transport.py", line 328, in _send_message_request
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error:  for url: http://<hostname>:5985/wsman
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/microsoft/winrm/hooks/winrm.py", line 212, in get_conn
    self.client = self.winrm_protocol.open_shell()
  File "/home/airflow/.local/lib/python3.10/site-packages/winrm/protocol.py", line 166, in open_shell
    res = self.send_message(xmltodict.unparse(req))
  File "/home/airflow/.local/lib/python3.10/site-packages/winrm/protocol.py", line 243, in send_message
    resp = self.transport.send_message(message)
  File "/home/airflow/.local/lib/python3.10/site-packages/winrm/transport.py", line 322, in send_message
    response = self._send_message_request(prepared_request, message)
  File "/home/airflow/.local/lib/python3.10/site-packages/winrm/transport.py", line 332, in _send_message_request
    raise InvalidCredentialsError("the specified credentials were rejected by the server")
winrm.exceptions.InvalidCredentialsError: the specified credentials were rejected by the server
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/microsoft/winrm/operators/winrm.py", line 93, in execute
    winrm_client = self.winrm_hook.get_conn()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/microsoft/winrm/hooks/winrm.py", line 217, in get_conn
    raise AirflowException(error_msg)
airflow.exceptions.AirflowException: Error connecting to host: <hostname>, error: the specified credentials were rejected by the server
[2023-11-24, 10:04:04 UTC] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=winrm_connection_test, task_id=wintask3, execution_date=20231124T100401, start_date=20231124T100403, end_date=20231124T100404
[2023-11-24, 10:04:04 UTC] {standard_task_runner.py:104} ERROR - Failed to execute job 1455343 for task wintask3 (Error connecting to host: <hostname>, error: the specified credentials were rejected by the server; 11745)
[2023-11-24, 10:04:04 UTC] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-11-24, 10:04:04 UTC] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
Version: [v2.6.2](https://pypi.python.org/pypi/apache-airflow/2.6.2)
Git Version: .release:d2f0d100dac4a95d664309d7b04a6a6110367446

**Comment by malthe** [comment]
@sksirajbasha "401 Client Error: for url: http://:5985/wsman" looks suspicious.

Do you have the host set alright? You need to go through the error log carefully to see what might be configured wrong.

**Comment by sksirajbasha** [comment]
the connection looks like this 
<img width="1388" alt="Screenshot 2023-11-24 at 3 42 15 PM" src="https://github.com/apache/airflow/assets/23027743/54d2f8f8-ddf3-404c-9443-7043ec36f30c">

**Comment by sksirajbasha** [comment]
> @sksirajbasha "401 Client Error: for url: http://:5985/wsman" looks suspicious.
> 
> Do you have the host set alright? You need to go through the error log carefully to see what might be configured wrong.

the host name is the fully qualified domain name
 no additional ":" added

**Comment by sksirajbasha** [comment]
> @sksirajbasha "401 Client Error: for url: http://:5985/wsman" looks suspicious.
> 
> Do you have the host set alright? You need to go through the error log carefully to see what might be configured wrong.

I think I truncated the host name. it looks like this "http://<our_hostname>:5985/wsman

**Comment by malthe** [comment]
The host should be simply "<out_hostname>" – the rest is added automatically.

**Comment by sksirajbasha** [comment]
> The host should be simply "<out_hostname>" – the rest is added automatically.

Yep.. I put just the host name in the connection. The one I pasted above is the error log with hostname in it

**Comment by sksirajbasha** [comment]
is there a tutorial or a know errata for winrm connections via airflow ?

**Comment by sksirajbasha** [comment]
Was anyone able to successfully connect and trigger a windows command or a batch file. Would like to follow along and replicate. This never worked for us.

**Comment by malthe** [comment]
@sksirajbasha I haven't used Rundeck personally, but perhaps you can try first to use the built-in remoting command from Windows.

Something like this:

```powershell
$ Invoke-Command -ComputerName 10.0.0.22 -ScriptBlock { Get-ChildItem C:\ } -credential batman
```

I'm assuming that your system is Windows system running the default setup. You're then supposed to be able to log into an administrator account using a username/password combination.

For some more background information, see https://www.maltheborch.com/2022/02/powershell-remoting-on-windows-using-airflow.html.

But rest assured, lots of people have been successfully using this operator – and of course the underlying Python package, https://pypi.org/project/pypsrp/.

If you have further questions, perhaps open a new issue with a complete bug report because this issue right here is about something else.
