### ISSUE TITLE
Clicked on a task with an error, then clear the task (with downstream and recursive on) and got this exception

### ISSUE THREAD

**Issue by stablum** [apache/airflow#19764]
### Apache Airflow version

2.1.4

### Operating System

Ubuntu 21.04

### Versions of Apache Airflow Providers

2.1.4

### Deployment

Other

### Deployment details

airflow 2.1.4
python 3.9.5

### What happened

Clicked on a task with an error, then clear the task (with downstream and recursive on) and got this exception

Something bad has happened.
Please consider letting us know by creating a bug report using GitHub.

Python version: 3.9.5
Airflow version: 2.1.4
Node: AI-Research

-------------------------------------------------------------------------------

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.9/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.9/dist-packages/airflow/www/auth.py", line 49, in decorated
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/airflow/www/decorators.py", line 60, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/airflow/www/views.py", line 1613, in clear
    dag = dag.sub_dag(
  File "/usr/local/lib/python3.9/dist-packages/airflow/models/dag.py", line 1439, in sub_dag
    warnings.warn(
  File "/usr/lib/python3.9/warnings.py", line 109, in _showwarnmsg
    sw(msg.message, msg.category, msg.filename, msg.lineno,
  File "/usr/local/lib/python3.9/dist-packages/airflow/settings.py", line 114, in custom_show_warning
    write_console.print(msg, soft_wrap=True)
  File "/usr/local/lib/python3.9/dist-packages/rich/console.py", line 1615, in print
    self._buffer.extend(new_segments)
  File "/usr/local/lib/python3.9/dist-packages/rich/console.py", line 825, in __exit__
    self._exit_buffer()
  File "/usr/local/lib/python3.9/dist-packages/rich/console.py", line 784, in _exit_buffer
    self._check_buffer()
  File "/usr/local/lib/python3.9/dist-packages/rich/console.py", line 1872, in _check_buffer
    self.file.write(text)
OSError: [Errno 5] Input/output error
```

### What you expected to happen

cleared task

### How to reproduce

Clicked on a task with an error, then clear the task (with downstream and recursive on) and got this exception

### Anything else

no

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by MadDenker** [comment]
I get a similar error when trying to trigger a DAG.  I have not been able to trigger a DAG in weeks.

**Comment by potiuk** [comment]
This is not Airflow problem . This is a problem with your deployment. For some reason when writing a log Python gets input/output error.this can happen when you have no disk space or you have no permissions or similar - none of which anyone but yourself can diagnose and fix in your deployment
