### ISSUE TITLE
airflow oracle providers v2.0.1 ORA-12154 ERROR

### ISSUE THREAD

**Issue by sunny760408** [apache/airflow#19958]
### Apache Airflow Provider(s)

oracle

### Versions of Apache Airflow Providers

apache-airflow-providers-amazon==2.4.0
apache-airflow-providers-celery==2.1.0
apache-airflow-providers-cncf-kubernetes==2.1.0
apache-airflow-providers-docker==2.3.0
apache-airflow-providers-elasticsearch==2.1.0
apache-airflow-providers-ftp==2.0.1
apache-airflow-providers-google==6.1.0
apache-airflow-providers-grpc==2.0.1
apache-airflow-providers-hashicorp==2.1.1
apache-airflow-providers-http==2.0.1
apache-airflow-providers-imap==2.0.1
apache-airflow-providers-microsoft-azure==3.3.0
apache-airflow-providers-microsoft-mssql==2.0.1
apache-airflow-providers-mysql==2.1.1
apache-airflow-providers-odbc==2.0.1
**apache-airflow-providers-oracle==2.0.1**
apache-airflow-providers-postgres==2.3.0
apache-airflow-providers-redis==2.0.1
apache-airflow-providers-sendgrid==2.0.1
apache-airflow-providers-sftp==2.2.0
apache-airflow-providers-slack==4.1.0
apache-airflow-providers-sqlite==2.0.1
apache-airflow-providers-ssh==2.3.0

### Apache Airflow version

2.2.2 (latest released)

### Operating System

PRETTY_NAME="Debian GNU/Linux 10 (buster)" NAME="Debian GNU/Linux" VERSION_ID="10" VERSION="10 (buster)" VERSION_CODENAME=buster ID=debian

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

Deployment Airflow v2.2.2 on Kubernetes v1.20

### What happened

When use airflow-oracle-provider v2.0.1 to select data from Oracle, it show an ora error.
'cx_Oracle.DatabaseError: ORA-12154: TNS:could not resolve the connect identifier specified'

I try the other airflow environment: Airflow v2.1.0, airflow-oracle-provider v2.0.0 is OK,
and after upgrade airflow-oracle-provider v2.0.1 is not ok.

My DAG
```
from airflow import DAG
from airflow.operators.python import PythonOperator
from airflow.utils.dates import days_ago
from airflow.providers.oracle.hooks.oracle import OracleHook


default_args = {
    'owner':'airflow', 
}

dag = DAG(
    dag_id="airflow", 
    description="this is test oracle connection",
    schedule_interval=None,
    start_date = days_ago(1),
    catchup = False,
    default_args=default_args,
    tags=['airflow'],
    access_control={
        'airflow': {'can_read', 'can_edit'} 
    }
)

def test_oracle_hook():
  hook = OracleHook(oracle_conn_id="xxxxx")
  value=hook.get_first(sql="SELECT xxxx")

oc = PythonOperator(
    task_id='oc',
    python_callable=test_oracle_hook,
    op_kwargs={'task_name': 'oc'},
    dag=dag,
)

again = PythonOperator(
    task_id='again',
    python_callable=test_oracle_hook,
    op_kwargs={'task_name': 'again'},
    dag=dag,
)

oc >> again
```

Error log:
```
*** Reading local file: /opt/airflow/logs/airflow_oracle_plm/oc/2021-12-02T05:10:30.770530+00:00/1.log
[2021-12-02, 05:10:44 UTC] {base_task_runner.py:63} DEBUG - Planning to run as the  user
[2021-12-02, 05:10:44 UTC] {taskinstance.py:720} DEBUG - Refreshing TaskInstance <TaskInstance: airflow_oracle_plm.oc manual__2021-12-02T05:10:30.770530+00:00 [queued]> from DB
[2021-12-02, 05:10:44 UTC] {taskinstance.py:761} DEBUG - Refreshed TaskInstance <TaskInstance: airflow_oracle_plm.oc manual__2021-12-02T05:10:30.770530+00:00 [queued]>
[2021-12-02, 05:10:44 UTC] {taskinstance.py:1045} DEBUG - <TaskInstance: airflow_oracle_plm.oc manual__2021-12-02T05:10:30.770530+00:00 [queued]> dependency 'Trigger Rule' PASSED: True, The task instance did not have any upstream tasks.
[2021-12-02, 05:10:44 UTC] {taskinstance.py:1045} DEBUG - <TaskInstance: airflow_oracle_plm.oc manual__2021-12-02T05:10:30.770530+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2021-12-02, 05:10:44 UTC] {taskinstance.py:1045} DEBUG - <TaskInstance: airflow_oracle_plm.oc manual__2021-12-02T05:10:30.770530+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2021-12-02, 05:10:44 UTC] {taskinstance.py:1045} DEBUG - <TaskInstance: airflow_oracle_plm.oc manual__2021-12-02T05:10:30.770530+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2021-12-02, 05:10:44 UTC] {taskinstance.py:1045} DEBUG - <TaskInstance: airflow_oracle_plm.oc manual__2021-12-02T05:10:30.770530+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2021-12-02, 05:10:44 UTC] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: airflow_oracle_plm.oc manual__2021-12-02T05:10:30.770530+00:00 [queued]>
[2021-12-02, 05:10:44 UTC] {taskinstance.py:1045} DEBUG - <TaskInstance: airflow_oracle_plm.oc manual__2021-12-02T05:10:30.770530+00:00 [queued]> dependency 'Trigger Rule' PASSED: True, The task instance did not have any upstream tasks.
[2021-12-02, 05:10:44 UTC] {taskinstance.py:1045} DEBUG - <TaskInstance: airflow_oracle_plm.oc manual__2021-12-02T05:10:30.770530+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2021-12-02, 05:10:44 UTC] {taskinstance.py:1045} DEBUG - <TaskInstance: airflow_oracle_plm.oc manual__2021-12-02T05:10:30.770530+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2021-12-02, 05:10:44 UTC] {taskinstance.py:1045} DEBUG - <TaskInstance: airflow_oracle_plm.oc manual__2021-12-02T05:10:30.770530+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2021-12-02, 05:10:45 UTC] {taskinstance.py:1045} DEBUG - <TaskInstance: airflow_oracle_plm.oc manual__2021-12-02T05:10:30.770530+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, ('There are enough open slots in %s to execute the task', 'default_pool')
[2021-12-02, 05:10:45 UTC] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: airflow_oracle_plm.oc manual__2021-12-02T05:10:30.770530+00:00 [queued]>
[2021-12-02, 05:10:45 UTC] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-02, 05:10:45 UTC] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-12-02, 05:10:45 UTC] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-02, 05:10:45 UTC] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): oc> on 2021-12-02 05:10:30.770530+00:00
[2021-12-02, 05:10:45 UTC] {standard_task_runner.py:52} INFO - Started process 105 to run task
[2021-12-02, 05:10:45 UTC] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'airflow_oracle_plm', 'oc', 'manual__2021-12-02T05:10:30.770530+00:00', '--job-id', '24268', '--raw', '--subdir', 'DAGS_FOLDER/airflow_oracle_plm.py', '--cfg-path', '/tmp/tmpf8weia3u', '--error-file', '/tmp/tmp5kpmvf4x']
[2021-12-02, 05:10:45 UTC] {standard_task_runner.py:77} INFO - Job 24268: Subtask oc
[2021-12-02, 05:10:45 UTC] {cli_action_loggers.py:66} DEBUG - Calling callbacks: [<function default_action_log at 0x7f3967468040>]
[2021-12-02, 05:10:45 UTC] {settings.py:210} DEBUG - Setting up DB connection pool (PID 105)
[2021-12-02, 05:10:45 UTC] {settings.py:267} DEBUG - settings.prepare_engine_args(): Using NullPool
[2021-12-02, 05:10:45 UTC] {logging_mixin.py:109} INFO - Running <TaskInstance: airflow_oracle_plm.oc manual__2021-12-02T05:10:30.770530+00:00 [running]> on host airfloworacleplmoc.52320077d2e743c3a7d17f286754a449
[2021-12-02, 05:10:45 UTC] {taskinstance.py:720} DEBUG - Refreshing TaskInstance <TaskInstance: airflow_oracle_plm.oc manual__2021-12-02T05:10:30.770530+00:00 [running]> from DB
[2021-12-02, 05:10:46 UTC] {taskinstance.py:761} DEBUG - Refreshed TaskInstance <TaskInstance: airflow_oracle_plm.oc manual__2021-12-02T05:10:30.770530+00:00 [running]>
[2021-12-02, 05:10:46 UTC] {taskinstance.py:790} DEBUG - Clearing XCom data
[2021-12-02, 05:10:46 UTC] {taskinstance.py:797} DEBUG - XCom data cleared
[2021-12-02, 05:10:46 UTC] {taskinstance.py:1427} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=airflow_oracle_plm
AIRFLOW_CTX_TASK_ID=oc
AIRFLOW_CTX_EXECUTION_DATE=2021-12-02T05:10:30.770530+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-12-02T05:10:30.770530+00:00
[2021-12-02, 05:10:46 UTC] {__init__.py:146} DEBUG - Preparing lineage inlets and outlets
[2021-12-02, 05:10:46 UTC] {__init__.py:190} DEBUG - inlets: [], outlets: []
[2021-12-02, 05:10:46 UTC] {base.py:70} INFO - Using connection to: id: airflow_oracle_plm. Host: (DESCRIPTION = (ADDRESS_LIST = (ADDRESS = (COMMUNITY = tcp)(PROTOCOL = TCP)(Host = 10.x.x.x)(Port = xxx)))(CONNECT_DATA = (SID = xxxx)(SERVER=xxx))), Port: ****, Schema: ***, Login: ***, Password: ***, extra: {}
[2021-12-02, 05:10:46 UTC] {taskinstance.py:1703} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 151, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 162, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/airflow_oracle_plm.py", line 42, in test_oracle_hook
    value=hook.get_first(sql="SELECT xxxxxx")
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/dbapi.py", line 168, in get_first
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/oracle/hooks/oracle.py", line 135, in get_conn
    conn = cx_Oracle.connect(**conn_config)
cx_Oracle.DatabaseError: ORA-12154: TNS:could not resolve the connect identifier specified
[2021-12-02, 05:10:46 UTC] {taskinstance.py:720} DEBUG - Refreshing TaskInstance <TaskInstance: airflow_oracle_plm.oc manual__2021-12-02T05:10:30.770530+00:00 [running]> from DB
[2021-12-02, 05:10:46 UTC] {taskinstance.py:761} DEBUG - Refreshed TaskInstance <TaskInstance: airflow_oracle_plm.oc manual__2021-12-02T05:10:30.770530+00:00 [running]>
[2021-12-02, 05:10:46 UTC] {taskinstance.py:2224} DEBUG - Task Duration set to 1.988342
[2021-12-02, 05:10:46 UTC] {taskinstance.py:1286} DEBUG - Clearing next_method and next_kwargs.
[2021-12-02, 05:10:46 UTC] {taskinstance.py:1270} INFO - Marking task as FAILED. dag_id=airflow_oracle_plm, task_id=oc, execution_date=20211202T051030, start_date=20211202T051044, end_date=20211202T051046
[2021-12-02, 05:10:47 UTC] {cli_action_loggers.py:84} DEBUG - Calling callbacks: []
[2021-12-02, 05:10:47 UTC] {standard_task_runner.py:88} ERROR - Failed to execute job 24268 for task oc
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 151, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 162, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/airflow_oracle_plm.py", line 42, in test_oracle_hook
    value=hook.get_first(sql="SELECT xxxxx")
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/dbapi.py", line 168, in get_first
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/oracle/hooks/oracle.py", line 135, in get_conn
    conn = cx_Oracle.connect(**conn_config)
cx_Oracle.DatabaseError: ORA-12154: TNS:could not resolve the connect identifier specified
[2021-12-02, 05:10:47 UTC] {local_task_job.py:154} INFO - Task exited with return code 1
[2021-12-02, 05:10:47 UTC] {taskinstance.py:720} DEBUG - Refreshing TaskInstance <TaskInstance: airflow_oracle_plm.oc manual__2021-12-02T05:10:30.770530+00:00 [running]> from DB
[2021-12-02, 05:10:47 UTC] {taskinstance.py:761} DEBUG - Refreshed TaskInstance <TaskInstance: airflow_oracle_plm.oc manual__2021-12-02T05:10:30.770530+00:00 [failed]>
[2021-12-02, 05:10:47 UTC] {dagrun.py:619} DEBUG - number of tis tasks for <DagRun airflow_oracle_plm @ 2021-12-02 05:10:30.770530+00:00: manual__2021-12-02T05:10:30.770530+00:00, externally triggered: True>: 2 task(s)
[2021-12-02, 05:10:47 UTC] {dagrun.py:634} DEBUG - number of scheduleable tasks for <DagRun airflow_oracle_plm @ 2021-12-02 05:10:30.770530+00:00: manual__2021-12-02T05:10:30.770530+00:00, externally triggered: True>: 1 task(s)
[2021-12-02, 05:10:47 UTC] {taskinstance.py:1045} DEBUG - <TaskInstance: airflow_oracle_plm.again manual__2021-12-02T05:10:30.770530+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2021-12-02, 05:10:47 UTC] {taskinstance.py:815} DEBUG - Setting task state for <TaskInstance: airflow_oracle_plm.again manual__2021-12-02T05:10:30.770530+00:00 [None]> to upstream_failed
[2021-12-02, 05:10:47 UTC] {taskinstance.py:1045} DEBUG - <TaskInstance: airflow_oracle_plm.again manual__2021-12-02T05:10:30.770530+00:00 [upstream_failed]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_tasks_state={'total': 1, 'successes': 0, 'skipped': 0, 'failed': 1, 'upstream_failed': 0, 'done': 1}, upstream_task_ids={'oc'}
[2021-12-02, 05:10:47 UTC] {taskinstance.py:1025} DEBUG - Dependencies not met for <TaskInstance: airflow_oracle_plm.again manual__2021-12-02T05:10:30.770530+00:00 [upstream_failed]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_tasks_state={'total': 1, 'successes': 0, 'skipped': 0, 'failed': 1, 'upstream_failed': 0, 'done': 1}, upstream_task_ids={'oc'}
[2021-12-02, 05:10:47 UTC] {taskinstance.py:1045} DEBUG - <TaskInstance: airflow_oracle_plm.again manual__2021-12-02T05:10:30.770530+00:00 [upstream_failed]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2021-12-02, 05:10:47 UTC] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
```

### How to reproduce

To write a DAG and connection to OracleDB by use airflow-oracle-provider v2.0.1.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
This is likely bad configuration of your new environment, not airflow problem https://www.xtivia.com/blog/ora-12154-tnscould-not-resolve-connect-identifier-specified/
