### ISSUE TITLE
ssl_cert_reqs has been deprecated in pymongo 3.9

### ISSUE THREAD

**Issue by ckljohn** [apache/airflow#20155]
### Apache Airflow Provider(s)

mongo

### Versions of Apache Airflow Providers

2.2.0

### Apache Airflow version

2.2.2 (latest released)

### Operating System

Debian GNU/Linux 10 (buster)

### Deployment

Official Apache Airflow Helm Chart

### What happened

`ssl_cert_reqs` has been deprecated in pymongo 3.9
https://github.com/apache/airflow/blob/providers-mongo/2.2.0/airflow/providers/mongo/hooks/mongo.py#L94

```
{taskinstance.py:1703} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1509, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/transfers/mongo_to_s3.py", line 123, in execute
    mongo_db=self.mongo_db,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mongo/hooks/mongo.py", line 145, in find
    collection = self.get_collection(mongo_collection, mongo_db=mongo_db)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mongo/hooks/mongo.py", line 116, in get_collection
    mongo_conn: MongoClient = self.get_conn()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mongo/hooks/mongo.py", line 96, in get_conn
    self.client = MongoClient(self.uri, **options)
  File "/home/airflow/.local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 707, in __init__
    keyword_opts.cased_key(k), v) for k, v in keyword_opts.items()))
  File "/home/airflow/.local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 707, in <genexpr>
    keyword_opts.cased_key(k), v) for k, v in keyword_opts.items()))
  File "/home/airflow/.local/lib/python3.7/site-packages/pymongo/common.py", line 740, in validate
    value = validator(option, value)
  File "/home/airflow/.local/lib/python3.7/site-packages/pymongo/common.py", line 144, in raise_config_error
    raise ConfigurationError("Unknown option %s" % (key,))
pymongo.errors.ConfigurationError: Unknown option ssl_cert_reqs
```

Ref:
https://pymongo.readthedocs.io/en/stable/changelog.html#changes-in-version-3-9-0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
Feel free to open PR
