### ISSUE TITLE
Not able to use custom security manager getting AttributeError: type object 'AirflowSecurityManager' has no attribute 'get_app'

### ISSUE THREAD

**Issue by BalaChan97** [apache/airflow#20449]
### Apache Airflow version

2.2.2 (latest released)

### What happened

```
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/www/fab_security/sqla/manager.py", line 69, in __init__     super().__init__(appbuilder)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/www/fab_security/manager.py", line 178, in __init__
    app = self.appbuilder.get_app
AttributeError: type object 'AirflowSecurityManager' has no attribute 'get_app'
```

### Operating System

linux

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
I'm able to reproduce it with basic auth on 2.2.3:


In `/login` when clicking `Register`:
```

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/flask_appbuilder/views.py", line 127, in this_form_get
    self.form_get(form)
  File "/usr/local/lib/python3.7/site-packages/flask_appbuilder/security/registerviews.py", line 175, in form_get
    self.add_form_unique_validations(form)
  File "/usr/local/lib/python3.7/site-packages/flask_appbuilder/security/registerviews.py", line 155, in add_form_unique_validations
    datamodel_user = self.appbuilder.sm.get_user_datamodel
AttributeError: 'AirflowSecurityManager' object has no attribute 'get_user_datamodel'
```

**Comment by uranusjr** [comment]
What is the version of Flask-Appbuilder in your environment? It seems like there are some incompatible changes between it and our own security manager implementation.

**Comment by eladkal** [comment]
> What is the version of Flask-Appbuilder in your environment? It seems like there are some incompatible changes between it and our own security manager implementation.

For me it's
`Flask-AppBuilder==3.4.4`

**Comment by eladkal** [comment]
Another user report this bug: https://github.com/apache/airflow/discussions/20866

**Comment by aa3pankaj** [comment]
@eladkal AttributeError: 'AirflowSecurityManager' object has no attribute 'get_user_datamodel' seems to be different from the issue reported here i.e AttributeError: type object 'AirflowSecurityManager' has no attribute 'get_app'

issues related to missing methods (including 'get_user_datamodel') in AirflowSecurityManager would be fixed via https://github.com/apache/airflow/pull/21294

For this issue ('get_app'), @BalaChan97 please share your usecase? can you share full stack trace?
