### ISSUE TITLE
JSONDecodeError caused by incomplete JSON created by cat /airflow/xcom/return.json when using KubernetePodOperator

### ISSUE THREAD

**Issue by saisujith2** [apache/airflow#20884]
### Apache Airflow Provider(s)

cncf-kubernetes

### Apache Airflow version

2.1.2

### Operating System

RHEL 7.6

### Deployment

Other 3rd-party Helm chart

### What happened

We are facing an issue similar to https://github.com/apache/airflow/pull/6799 with Airflow Version 2.1.2

A program that we run using the KubernetesPodOperator has a very large JSON object that should be inserted as an XCOM.  But, When the sidecar container attempts to load the XCOM , `cat /airflow/xcom/return.json ` is incompletely emitting the object which then caused the below error

**Error**

> [2022-01-14 07:28:30,540] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/cncf/kubernetes/operators/kubernetes_pod.py", line 366, in execute
    final_state, remote_pod, result = self.create_new_pod_for_operator(labels, launcher)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/cncf/kubernetes/operators/kubernetes_pod.py", line 520, in create_new_pod_for_operator
    final_state, remote_pod, result = launcher.monitor_pod(pod=self.pod, get_logs=self.get_logs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/cncf/kubernetes/utils/pod_launcher.py", line 169, in monitor_pod
    result = json.loads(result)
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 287 column 22 (char 8192)

Can something be done to avoid this from happening?

### How To Reproduce?

The issue is happening intermittently while the KuberentesPodExecutor tries to create an XCOM that is very large in size.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by ddelange** [comment]
ref https://github.com/kubernetes-client/python-base/issues/190

**Comment by uranusjr** [comment]
Sounds like this is something Airflow can’t fix and need to wait for a patch in the Kubernetes dependency?

**Comment by ddelange** [comment]
would agree this is upstream. nevertheless, here is a potential hotfix on airflow side (unconfirmed): https://github.com/kubernetes-client/python-base/issues/190#issuecomment-805073981

**Comment by ddelange** [comment]
FYI, the upstream issue has been closed, as the repo was archived

**Comment by uranusjr** [comment]
They say you need to file to https://github.com/kubernetes-client/python instead.

**Comment by ddelange** [comment]
@saisujith2 do you have time to write a new issue that reflects their current codebase?

**Comment by paramjeet01** [comment]
@saisujith2 , were you able to solve this issue ?

**Comment by ddelange** [comment]
I think https://github.com/kubernetes-client/python-base/issues/190 needs to be recreated against https://github.com/kubernetes-client/python

**Comment by paramjeet01** [comment]
Ack , I'll create the issue in python repo. Thank for reverting back early.
