### ISSUE TITLE
AirflowException: decoding with 'utf-16le' codec failed (AirflowException: Task received SIGTERM signal)

### ISSUE THREAD

**Issue by andre-ricardo-moraes** [apache/airflow#21027]
### Apache Airflow version

2.0.1

### What happened

Hi!
I have a error on Airflow when use connector pyodbc to get data from mssql. running the same commands on terminal there isn't any error.

this is the message:

```
[2022-01-21 22:52:35,309] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 517
[2022-01-21 22:52:35,310] {taskinstance.py:1239} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-01-21 22:52:35,311] {taskinstance.py:1455} ERROR - <class 'pyodbc.Error'> returned a result with an error set
Traceback (most recent call last):
  File "/usr/lib/python3.7/encodings/utf_16_le.py", line 15, in decode
    def decode(input, errors='strict'):
  File "/usr/local/lib/python3.7/dist-packages/airflow/models/taskinstance.py", line 1241, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal

The above exception was the direct cause of the following exception:

airflow.exceptions.AirflowException: decoding with 'utf-16le' codec failed (AirflowException: Task received SIGTERM signal)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/usr/local/lib/python3.7/dist-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/usr/local/lib/python3.7/dist-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/airflow/plugins/mssql_utils.py", line 64, in execute
    cur.execute(self.sql)
SystemError: <class 'pyodbc.Error'> returned a result with an error set
[2022-01-21 22:52:35,313] {taskinstance.py:1862} DEBUG - Task Duration set to 121.980616
```

### What you expected to happen

the message of error doesn't show the exactly the point of failure. there are a mode to enable a debug in log level to trace the error or to show the string with error on decode?

### Operating System

ubuntu 18.04.6 lts

### Deployment

Docker-Compose

### Deployment details

the enviorement is on GCP / kubernets

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
> the message of error doesn't show the exactly the point of failure. there are a mode to enable a debug in log level to trace the error or to show the string with error on decode?

Not really. The error is clearly generated here:

```
 File "/airflow/plugins/mssql_utils.py", line 64, in execute
```

It's an error generated by your own plugin (mssql_utils.py), so this is not an airflow problem, you should diagnose and improve your plugin's code.
