### ISSUE TITLE
Scheduler crashes after dag processing timeout

### ISSUE THREAD

**Issue by dcardinha** [apache/airflow#21265]
### Apache Airflow version

2.2.3 (latest released)

### What happened

We are seeing some scheduler crashes after it times out processing a dag. 

An example: 

```

2022-02-01T07:28:12.991+00:00 | ts="2022-02-01 07:28:12,991" class="airflow.dag_processing.manager.DagFileProcessorAgent" level="INFO" msg="Launched DagFileProcessorManager with pid: 297433"
-- | --

  | 2022-02-01T07:28:12.988+00:00 | ts="2022-02-01 07:28:12,988" class="airflow.dag_processing.manager.DagFileProcessorAgent" level="WARNING" msg="DagFileProcessorManager (PID=285072) exited with exit code 1 - re-launching"

  | 2022-02-01T07:28:12.778+00:00 | Process ForkProcess-40:

  | 2022-02-01T07:28:12.778+00:00 | Traceback (most recent call last):

  | 2022-02-01T07:28:12.778+00:00 | File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap

  | 2022-02-01T07:28:12.778+00:00 | self.run()

  | 2022-02-01T07:28:12.778+00:00 | File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run

  | 2022-02-01T07:28:12.778+00:00 | self._target(*self._args, **self._kwargs)

  | 2022-02-01T07:28:12.778+00:00 | File "/usr/local/lib/python3.7/dist-packages/airflow/dag_processing/manager.py", line 287, in _run_processor_manager

  | 2022-02-01T07:28:12.778+00:00 | processor_manager.start()

  | 2022-02-01T07:28:12.778+00:00 | File "/usr/local/lib/python3.7/dist-packages/airflow/dag_processing/manager.py", line 520, in start

  | 2022-02-01T07:28:12.778+00:00 | return self._run_parsing_loop()

  | 2022-02-01T07:28:12.778+00:00 | File "/usr/local/lib/python3.7/dist-packages/airflow/dag_processing/manager.py", line 580, in _run_parsing_loop

  | 2022-02-01T07:28:12.778+00:00 | self._collect_results_from_processor(processor)

  | 2022-02-01T07:28:12.778+00:00 | File "/usr/local/lib/python3.7/dist-packages/airflow/dag_processing/manager.py", line 904, in _collect_results_from_processor

  | 2022-02-01T07:28:12.778+00:00 | if processor.result is not None:

  | 2022-02-01T07:28:12.778+00:00 | File "/usr/local/lib/python3.7/dist-packages/airflow/dag_processing/processor.py", line 322, in result

  | 2022-02-01T07:28:12.778+00:00 | if not self.done:

  | 2022-02-01T07:28:12.778+00:00 | File "/usr/local/lib/python3.7/dist-packages/airflow/dag_processing/processor.py", line 287, in done

  | 2022-02-01T07:28:12.778+00:00 | if self._parent_channel.poll():

  | 2022-02-01T07:28:12.778+00:00 | File "/usr/lib/python3.7/multiprocessing/connection.py", line 255, in poll

  | 2022-02-01T07:28:12.778+00:00 | self._check_closed()

  | 2022-02-01T07:28:12.778+00:00 | File "/usr/lib/python3.7/multiprocessing/connection.py", line 136, in _check_closed

  | 2022-02-01T07:28:12.778+00:00 | raise OSError("handle is closed")

  | 2022-02-01T07:28:12.778+00:00 | OSError: handle is closed

  | 2022-02-01T07:28:10.985+00:00 | ts="2022-02-01 07:28:10,985" class="airflow.dag_processing.processor.DagFileProcessorProcess" level="WARNING" msg="Killing DAGFileProcessorProcess (PID=296516)"

  | 2022-02-01T07:28:10.979+00:00 | ts="2022-02-01 07:28:10,979" class="airflow.processor_manager" level="ERROR" msg="Processor for /srv/app/dags/bi_lookml/dag.py with PID 296516 started at 2022-02-01T07:26:10.857693+00:00 has timed out, killing it

```

We use airflow 2.2.3 and this is happening a couple of times per day. We are trying to increase the dagbag timeout seconds but it has not cleared all the crashes. Could you please advise?

### What you expected to happen

Scheduler should not exit if a timeout happens.

### Operating System

18.04.6 LTS (Bionic Beaver)

### Deployment

Other

### Deployment details

Kubernetes

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by WattsInABox** [comment]
👍  seeing this as well

**Comment by mtraynham** [comment]
We are seeing similar issues after an upgrade from 2.1.4 to 2.2.3.  On our scheduler, this has been somewhat mitigated as we increased `AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL` and `AIRFLOW__SCHEDULER__MIN_FILE_PROCESS_INTERVAL` both to 10 minutes from 5 seconds.

However I am still seeing it in our Celery Worker and it effectively blocks tasks from running for 80+ seconds, before it times out.

I suspect our error is related to `Initializing Providers Manager[import_all_hooks]` which is something new with 2.2.X and it largely seems to always fail with `Exception when importing 'airflow.providers.docker.hooks.docker.DockerHook' from 'apache-airflow-providers-docker' package.  Our log is below.

@dcardinha @WattsInABox , do either of you have the option to turn on DEBUG logging, possibly to see something similar?

```
2022-02-04T08:14:30.745502939Z [2022-02-04 08:14:30,745: INFO/ForkPoolWorker-15] Filling up the DagBag from /home/airflow/.local/lib/python3.8/site-packages/foobar/runner/__init__.py
2022-02-04T08:14:30.746292606Z [2022-02-04 08:14:30,746: DEBUG/ForkPoolWorker-15] Importing /home/airflow/.local/lib/python3.8/site-packages/foobar/runner/__init__.py
2022-02-04T08:14:31.084507410Z [2022-02-04 08:14:31,084: DEBUG/ForkPoolWorker-15] Initializing Providers Manager[hooks]
2022-02-04T08:14:31.084556312Z [2022-02-04 08:14:31,084: DEBUG/ForkPoolWorker-15] Initializing Providers Manager[list]
2022-02-04T08:14:31.095732961Z [2022-02-04 08:14:31,095: DEBUG/ForkPoolWorker-15] Loading EntryPoint(name='provider_info', value='airflow.providers.grpc.get_provider_info:get_provider_info', group='apache_airflow_provider') from package apache-airflow-providers-grpc
2022-02-04T08:14:31.097942644Z [2022-02-04 08:14:31,097: DEBUG/ForkPoolWorker-15] Loading EntryPoint(name='provider_info', value='airflow.providers.docker.get_provider_info:get_provider_info', group='apache_airflow_provider') from package apache-airflow-providers-docker
2022-02-04T08:14:31.100267595Z [2022-02-04 08:14:31,100: DEBUG/ForkPoolWorker-15] Loading EntryPoint(name='provider_info', value='airflow.providers.google.get_provider_info:get_provider_info', group='apache_airflow_provider') from package apache-airflow-providers-google
2022-02-04T08:14:31.104712785Z [2022-02-04 08:14:31,104: DEBUG/ForkPoolWorker-15] Loading EntryPoint(name='provider_info', value='airflow.providers.cncf.kubernetes.get_provider_info:get_provider_info', group='apache_airflow_provider') from package apache-airflow-providers-cncf-kubernetes
2022-02-04T08:14:31.106863937Z [2022-02-04 08:14:31,106: DEBUG/ForkPoolWorker-15] Loading EntryPoint(name='provider_info', value='airflow.providers.http.get_provider_info:get_provider_info', group='apache_airflow_provider') from package apache-airflow-providers-http
2022-02-04T08:14:31.109014206Z [2022-02-04 08:14:31,108: DEBUG/ForkPoolWorker-15] Loading EntryPoint(name='provider_info', value='airflow.providers.redis.get_provider_info:get_provider_info', group='apache_airflow_provider') from package apache-airflow-providers-redis
2022-02-04T08:14:31.111201541Z [2022-02-04 08:14:31,110: DEBUG/ForkPoolWorker-15] Loading EntryPoint(name='provider_info', value='airflow.providers.mysql.get_provider_info:get_provider_info', group='apache_airflow_provider') from package apache-airflow-providers-mysql
2022-02-04T08:14:31.113902110Z [2022-02-04 08:14:31,113: DEBUG/ForkPoolWorker-15] Loading EntryPoint(name='provider_info', value='airflow.providers.amazon.get_provider_info:get_provider_info', group='apache_airflow_provider') from package apache-airflow-providers-amazon
2022-02-04T08:14:31.116398514Z [2022-02-04 08:14:31,116: DEBUG/ForkPoolWorker-15] Loading EntryPoint(name='provider_info', value='airflow.providers.elasticsearch.get_provider_info:get_provider_info', group='apache_airflow_provider') from package apache-airflow-providers-elasticsearch
2022-02-04T08:14:31.118252974Z [2022-02-04 08:14:31,118: DEBUG/ForkPoolWorker-15] Loading EntryPoint(name='provider_info', value='airflow.providers.ftp.get_provider_info:get_provider_info', group='apache_airflow_provider') from package apache-airflow-providers-ftp
2022-02-04T08:14:31.119932342Z [2022-02-04 08:14:31,119: DEBUG/ForkPoolWorker-15] Loading EntryPoint(name='provider_info', value='airflow.providers.sftp.get_provider_info:get_provider_info', group='apache_airflow_provider') from package apache-airflow-providers-sftp
2022-02-04T08:14:31.121772776Z [2022-02-04 08:14:31,121: DEBUG/ForkPoolWorker-15] Loading EntryPoint(name='provider_info', value='airflow.providers.ssh.get_provider_info:get_provider_info', group='apache_airflow_provider') from package apache-airflow-providers-ssh
2022-02-04T08:14:31.123516831Z [2022-02-04 08:14:31,123: DEBUG/ForkPoolWorker-15] Loading EntryPoint(name='provider_info', value='airflow.providers.sendgrid.get_provider_info:get_provider_info', group='apache_airflow_provider') from package apache-airflow-providers-sendgrid
2022-02-04T08:14:31.125036267Z [2022-02-04 08:14:31,124: DEBUG/ForkPoolWorker-15] Loading EntryPoint(name='provider_info', value='airflow.providers.hashicorp.get_provider_info:get_provider_info', group='apache_airflow_provider') from package apache-airflow-providers-hashicorp
2022-02-04T08:14:31.127102702Z [2022-02-04 08:14:31,126: DEBUG/ForkPoolWorker-15] Loading EntryPoint(name='provider_info', value='airflow.providers.microsoft.azure.get_provider_info:get_provider_info', group='apache_airflow_provider') from package apache-airflow-providers-microsoft-azure
2022-02-04T08:14:31.131129199Z [2022-02-04 08:14:31,130: DEBUG/ForkPoolWorker-15] Loading EntryPoint(name='provider_info', value='airflow.providers.slack.get_provider_info:get_provider_info', group='apache_airflow_provider') from package apache-airflow-providers-slack
2022-02-04T08:14:31.135302807Z [2022-02-04 08:14:31,135: DEBUG/ForkPoolWorker-15] Loading EntryPoint(name='provider_info', value='airflow.providers.celery.get_provider_info:get_provider_info', group='apache_airflow_provider') from package apache-airflow-providers-celery
2022-02-04T08:14:31.136855733Z [2022-02-04 08:14:31,136: DEBUG/ForkPoolWorker-15] Loading EntryPoint(name='provider_info', value='airflow.providers.imap.get_provider_info:get_provider_info', group='apache_airflow_provider') from package apache-airflow-providers-imap
2022-02-04T08:14:31.138380123Z [2022-02-04 08:14:31,138: DEBUG/ForkPoolWorker-15] Loading EntryPoint(name='provider_info', value='airflow.providers.sqlite.get_provider_info:get_provider_info', group='apache_airflow_provider') from package apache-airflow-providers-sqlite
2022-02-04T08:14:31.140693159Z [2022-02-04 08:14:31,140: DEBUG/ForkPoolWorker-15] Loading EntryPoint(name='provider_info', value='airflow.providers.odbc.get_provider_info:get_provider_info', group='apache_airflow_provider') from package apache-airflow-providers-odbc
2022-02-04T08:14:31.142356555Z [2022-02-04 08:14:31,142: DEBUG/ForkPoolWorker-15] Loading EntryPoint(name='provider_info', value='airflow.providers.postgres.get_provider_info:get_provider_info', group='apache_airflow_provider') from package apache-airflow-providers-postgres
2022-02-04T08:14:31.146554304Z [2022-02-04 08:14:31,146: DEBUG/ForkPoolWorker-15] Initialization of Providers Manager[list] took 0.06 seconds
2022-02-04T08:14:31.146788306Z [2022-02-04 08:14:31,146: DEBUG/ForkPoolWorker-15] Initialization of Providers Manager[hooks] took 0.06 seconds
2022-02-04T08:14:31.146835613Z [2022-02-04 08:14:31,146: DEBUG/ForkPoolWorker-15] Initializing Providers Manager[import_all_hooks]
2022-02-04T08:16:06.682682831Z [2022-02-04 08:16:06,681: ERROR/ForkPoolWorker-15] Process timed out, PID: 9579
2022-02-04T08:16:06.683022858Z [2022-02-04 08:16:06,682: WARNING/ForkPoolWorker-15] Exception when importing 'airflow.providers.docker.hooks.docker.DockerHook' from 'apache-airflow-providers-docker' package: DagBag import timeout for /home/airflow/.local/lib/python3.8/site-packages/foobar/runner/__init__.py after 30.0s.
2022-02-04T08:16:06.683046483Z Please take a look at these docs to improve your DAG import time:
2022-02-04T08:16:06.683052855Z * https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#top-level-python-code
2022-02-04T08:16:06.683058750Z * https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#reducing-dag-complexity, PID: 9579
2022-02-04T08:16:07.332734255Z [2022-02-04 08:16:07,332: DEBUG/ForkPoolWorker-15] Exception when importing 'airflow.providers.google.leveldb.hooks.leveldb.LevelDBHook' from 'apache-airflow-providers-google' package: No module named 'plyvel'
2022-02-04T08:16:07.761798052Z [2022-02-04 08:16:07,761: DEBUG/ForkPoolWorker-15] Initialization of Providers Manager[import_all_hooks] took 96.61 seconds
```

**Comment by potiuk** [comment]
The problem is that your dag parsing takes too much time. You apparently missed this advice from the log:

Please take a look at these docs to improve your DAG import time:
2022-02-04T08:16:06.683052855Z * https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#top-level-python-code
2022-02-04T08:16:06.683058750Z * https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#reducing-dag-complexity

Can you please follow up ALL the best practices there and report your findings after addressing them?

Converting it into a discussion, awaiting the results of review of your DAGS (parsing of which takes far too much time).
