### ISSUE TITLE
Get tasks for DAG API call returns 500 INTERNAL SERVER ERROR

### ISSUE THREAD

**Issue by Alex-mstrg** [apache/airflow#21883]
### Apache Airflow version

2.2.3

### What happened

GET /dags/{dag_id}/tasks returns 500 status code for some DAGs:

```
Python version: 3.7.10
Airflow version: 2.2.3
Node: 12efab2491d4
-------------------------------------------------------------------------------
ERROR - Exception on /api/v1/dags/<dag_id here>/tasks [GET]

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/airflow/_vendor/connexion/decorators/decorator.py", line 48, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.7/site-packages/airflow/_vendor/connexion/decorators/uri_parsing.py", line 144, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.7/site-packages/airflow/_vendor/connexion/decorators/validation.py", line 384, in wrapper
    return function(request)
  File "/usr/local/lib/python3.7/site-packages/airflow/_vendor/connexion/decorators/response.py", line 103, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.7/site-packages/airflow/_vendor/connexion/decorators/parameter.py", line 121, in wrapper
    return function(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/api_connexion/security.py", line 47, in decorated
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/api_connexion/endpoints/task_endpoint.py", line 66, in get_tasks
    return task_collection_schema.dump(task_collection)
  File "/usr/local/lib/python3.7/site-packages/marshmallow/schema.py", line 552, in dump
    result = self._serialize(processed_obj, many=many)
  File "/usr/local/lib/python3.7/site-packages/marshmallow/schema.py", line 520, in _serialize
    value = field_obj.serialize(attr_name, obj, accessor=self.get_attribute)
  File "/usr/local/lib/python3.7/site-packages/marshmallow/fields.py", line 339, in serialize
    return self._serialize(value, attr, obj, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/marshmallow/fields.py", line 758, in _serialize
    return [self.inner._serialize(each, attr, obj, **kwargs) for each in value]
  File "/usr/local/lib/python3.7/site-packages/marshmallow/fields.py", line 758, in &lt;listcomp&gt;
    return [self.inner._serialize(each, attr, obj, **kwargs) for each in value]
  File "/usr/local/lib/python3.7/site-packages/marshmallow/fields.py", line 625, in _serialize
    return schema.dump(nested_obj, many=many)
  File "/usr/local/lib/python3.7/site-packages/marshmallow/schema.py", line 552, in dump
    result = self._serialize(processed_obj, many=many)
  File "/usr/local/lib/python3.7/site-packages/marshmallow/schema.py", line 520, in _serialize
    value = field_obj.serialize(attr_name, obj, accessor=self.get_attribute)
  File "/usr/local/lib/python3.7/site-packages/marshmallow/fields.py", line 339, in serialize
    return self._serialize(value, attr, obj, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/marshmallow/fields.py", line 1867, in _serialize
    return self._serialize_method(obj)
  File "/usr/local/lib/python3.7/site-packages/airflow/api_connexion/schemas/task_schema.py", line 70, in get_params
    return {k: v.dump() for k, v in params.items()}
  File "/usr/local/lib/python3.7/site-packages/airflow/api_connexion/schemas/task_schema.py", line 70, in &lt;dictcomp&gt;
    return {k: v.dump() for k, v in params.items()}
AttributeError: 'dict' object has no attribute 'dump'

```

### What you expected to happen

A response with 200 status code and tasks info

### How to reproduce

curl -u user:password GET 'http://localhost:8080/api/v1/dags/<dag_id>/tasks'

### Operating System

macOS Bir Sur, Version 11.6.2, Darwin alex-0530.local 20.6.0 Darwin Kernel Version 20.6.0: Wed Nov 10 22:23:07 PST 2021; root:xnu-7195.141.14~1/RELEASE_X86_64 x86_64

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by aa3pankaj** [comment]
Can you share a sample [params](https://airflow.apache.org/docs/apache-airflow/2.2.1/concepts/params.html#params) dictionary where you can reproduce this issue?

**Comment by Alex-mstrg** [comment]
A task with params example:
```
dag = DAG(
    "task_params_test",
    catchup=False,
    default_args=DEFAULT_DAG_ARGS,
    schedule_interval=None,
)

init_task = DummyOperator(task_id="init", dag=dag)

import_data = SqlFileOperator(
    task_id="import_test_data",
    transform_file=TRANSFORM_DIR / "imports/test.sql",
    params={"table": Param("test_table_" + "{{ ds_nodash }}")},
    dag=dag,
)

init_task >> import_data

```

**Comment by uranusjr** [comment]
What is this `SqlFileOperator`?
