### ISSUE TITLE
TemplateNotFound error when trying to run the 'touch' command in the BashOperator

### ISSUE THREAD

**Issue by rustikk** [apache/airflow#21918]
### Apache Airflow version

2.2.4 (latest released)

### What happened

When trying to run the touch command in the bash operator with the template_searchpath dag parameter set to a certain destination an error of TemplateNotFound is given to the user.

### What you expected to happen

I expected to be able to create a file with the touch bash command.

### How to reproduce

```
from airflow.models import DAG
from airflow.operators.bash import BashOperator
from airflow.operators.python import PythonOperator
from airflow.utils.log.log_reader import TaskLogReader
from airflow.utils.dates import days_ago


with DAG(
    dag_id="template_searchpath_dag",
    schedule_interval=None,
    start_date=days_ago(1),
    template_searchpath=["/usr/local/airflow"],
) as dag:

    t1 = BashOperator(
        task_id="run_templated_command",
        bash_command="touch template_searchpath.sh",
    )

```

### Operating System

Docker (debian:buster)

### Deployment

Astronomer

### Deployment details

Astro CLI with this image:
quay.io/astronomer/ap-airflow-dev:2.2.4-1-onbuild

### Anything else

This issue occurs everytime.

This is the traceback I get:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/usr/local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/usr/local/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1423, in _execute_task_with_callbacks
    self.render_templates(context=context)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2011, in render_templates
    self.task.render_template_fields(context)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1061, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/usr/local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1074, in _do_render_template_fields
    rendered_content = self.render_template(content, context, jinja_env, seen_oids)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1108, in render_template
    template = jinja_env.get_template(content)
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/usr/local/lib/python3.9/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python3.9/site-packages/jinja2/loaders.py", line 214, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: touch template_searchpath.sh

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by SamWheating** [comment]
This is because anything in the `bash_command` argument ending with `.sh` or `.bash` is treated as a file to be loaded and rendered as a template:

https://github.com/apache/airflow/blob/602abe8394fafe7de54df7e73af56de848cdf617/airflow/operators/bash.py#L127-L130

Some more info in here:
https://airflow.apache.org/docs/apache-airflow/stable/howto/custom-operator.html#templating

As a quick workaround could you just change it to something which is functionally the same but doesn't end in `.sh`? for example:

- `bash_command="touch 'template_searchpath.sh'",`
- `bash_command="touch template_searchpath.sh && echo done",`

**Comment by rustikk** [comment]
Hey @SamWheating thanks for getting back to me on this. I can definitely use one of the workarounds you mentioned. I'm closing this issue as it's a user error not an airflow error.
