### ISSUE TITLE
In 'list users', clicking 'show record' button returns an error page

### ISSUE THREAD

**Issue by NirmalSharmaRaj** [apache/airflow#22035]
### Apache Airflow version

2.2.2

### What happened

Under Security Tab> List users, when show record button for an user is clicked, an error page with some exception - "KeyError: 'userinfoedit'" is returned. 

![image](https://user-images.githubusercontent.com/95294875/156978032-459254a2-988f-448b-84a4-d228baf834d5.png)

![image](https://user-images.githubusercontent.com/95294875/156977666-309d1252-5a77-409e-8c56-cdc650050ccb.png)

### What you expected to happen

Expected page to show the User Info on clicking the show records icon.

### How to reproduce

Click on show records for any user under list users in security tab. 

### Operating System

Ubuntu 20 LTS

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by rgdev** [comment]
Error occurs on both 2.2.3 and 2.2.4 (python 3.9) running in Docker containers. I've made the same observations as @SangwanP, it works once then a few minutes need to pass by to access it again. In this test case the users are handled using google oauth.

```
Python version: 3.9.10
Airflow version: 2.2.4
Node: 8ae1c307a746
-------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/airflow/.local/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/airflow/.local/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/airflow/.local/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/airflow/.local/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/airflow/.local/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/flask_appbuilder/security/decorators.py", line 148, in wraps
    return f(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/www/views.py", line 4699, in show
    widgets['show'].template_args['actions'].pop('userinfoedit')
KeyError: 'userinfoedit'
```

**Comment by rgdev** [comment]
Still broken in 2.3.0

**Comment by zaibacu** [comment]
Still broken in 2.4.3

**Comment by potiuk** [comment]
Yep. Reopened. And hopefully someone will pick it up.
