### ISSUE TITLE
Mapped task is not expanded when mapped against a literal

### ISSUE THREAD

**Issue by MatrixManAtYrService** [apache/airflow#22561]
### Apache Airflow version

main (development)

### What happened

Here's a DAG:

```python3
@task
def mynameis(arg, **context):

    ti: TaskInstance = context["ti"]
    print(ti.task_id)
    print(arg)


with DAG(
    dag_id="my_name_is",
    start_date=datetime(1970, 1, 1),
    schedule_interval=timedelta(days=30 * 365),
) as dag:
    mynameis.expand(arg=["slim", "shady"])
```

<details>
<summary>Outdated report here; no longer relevant</summary>

When I unpause it, the scheduler crashes like so:
```
    ____________       _____________
 ____    |__( )_________  __/__  /________      __
____  /| |_  /__  ___/_  /_ __  /_  __ \_ | /| / /
___  ___ |  / _  /   _  __/ _  / / /_/ /_ |/ |/ /
 _/_/  |_/_/  /_/    /_/    /_/  \____/____/|__/
[2022-03-27 21:48:45,682] {scheduler_job.py:712} INFO - Starting the scheduler
[2022-03-27 21:48:45,683] {scheduler_job.py:717} INFO - Processing each file at most -1 times
[2022-03-27 21:48:45,686] {executor_loader.py:106} INFO - Loaded executor: SequentialExecutor
[2022-03-27 21:48:45,692] {manager.py:156} INFO - Launched DagFileProcessorManager with pid: 36986
[2022-03-27 21:48:45,694] {scheduler_job.py:1242} INFO - Resetting orphaned tasks for active dag runs
[2022-03-27 21:48:46,269] {settings.py:55} INFO - Configured default timezone Timezone('UTC')
[2022-03-27 21:48:46,276] {manager.py:398} WARNING - Because we cannot use more than 1 thread (parsing_processes = 2) when using sqlite. So we set parallelism to 1.
[2022-03-27 21:48:56,576] {dag.py:2931} INFO - Setting next_dagrun for my_name_is to 1999-12-25T00:00:00+00:00, run_after=2029-12-17T00:00:00+00:00
[2022-03-27 21:48:56,618] {scheduler_job.py:354} INFO - 1 tasks up for execution:
	<TaskInstance: my_name_is.mynameis scheduled__1970-01-01T00:00:00+00:00 [scheduled]>
[2022-03-27 21:48:56,618] {scheduler_job.py:376} INFO - Figuring out tasks to run in Pool(name=default_pool) with 128 open slots and 1 task instances ready to be queued
[2022-03-27 21:48:56,619] {scheduler_job.py:434} INFO - DAG my_name_is has 0/16 running and queued tasks
[2022-03-27 21:48:56,619] {scheduler_job.py:520} INFO - Setting the following tasks to queued state:
	<TaskInstance: my_name_is.mynameis scheduled__1970-01-01T00:00:00+00:00 [scheduled]>
[2022-03-27 21:48:56,621] {scheduler_job.py:562} INFO - Sending TaskInstanceKey(dag_id='my_name_is', task_id='mynameis', run_id='scheduled__1970-01-01T00:00:00+00:00', try_number=1, map_index=-1) to executor with priority 1 and queue default
[2022-03-27 21:48:56,622] {base_executor.py:88} INFO - Adding to queue: ['airflow', 'tasks', 'run', 'my_name_is', 'mynameis', 'scheduled__1970-01-01T00:00:00+00:00', '--local', '--subdir', 'DAGS_FOLDER/my_name_is.py']
[2022-03-27 21:48:56,623] {sequential_executor.py:59} INFO - Executing command: ['airflow', 'tasks', 'run', 'my_name_is', 'mynameis', 'scheduled__1970-01-01T00:00:00+00:00', '--local', '--subdir', 'DAGS_FOLDER/my_name_is.py']
[2022-03-27 21:48:57,229] {dagbag.py:506} INFO - Filling up the DagBag from /Users/matt/2022/03/27/dags/my_name_is.py
[2022-03-27 21:48:57,405] {sequential_executor.py:66} ERROR - Failed to execute task Command '['airflow', 'tasks', 'run', 'my_name_is', 'mynameis', 'scheduled__1970-01-01T00:00:00+00:00', '--local', '--subdir', 'DAGS_FOLDER/my_name_is.py']' returned non-zero exit status 1..
[2022-03-27 21:48:57,407] {scheduler_job.py:615} INFO - Executor reports execution of my_name_is.mynameis run_id=scheduled__1970-01-01T00:00:00+00:00 exited with status failed for try_number 1
[2022-03-27 21:48:57,420] {scheduler_job.py:659} INFO - TaskInstance Finished: dag_id=my_name_is, task_id=mynameis, run_id=scheduled__1970-01-01T00:00:00+00:00, map_index=-1, run_start_date=None, run_end_date=None, run_duration=None, state=queued, executor_state=failed, try_number=1, max_tries=0, job_id=None, pool=default_pool, queue=default, priority_weight=1, operator=_PythonDecoratedOperator, queued_dttm=2022-03-28 03:48:56.619831+00:00, queued_by_job_id=1, pid=None
[2022-03-27 21:48:57,420] {scheduler_job.py:688} ERROR - Executor reports task instance <TaskInstance: my_name_is.mynameis scheduled__1970-01-01T00:00:00+00:00 [queued]> finished (failed) although the task says its queued. (Info: None) Was the task killed externally?
[2022-03-27 21:48:57,421] {taskinstance.py:1785} ERROR - Executor reports task instance <TaskInstance: my_name_is.mynameis scheduled__1970-01-01T00:00:00+00:00 [queued]> finished (failed) although the task says its queued. (Info: None) Was the task killed externally?
[2022-03-27 21:48:57,428] {scheduler_job.py:769} ERROR - Exception when executing SchedulerJob._run_scheduler_loop
Traceback (most recent call last):
  File "/Users/matt/2022/03/27/venv/lib/python3.10/site-packages/airflow/jobs/scheduler_job.py", line 753, in _execute
    self._run_scheduler_loop()
  File "/Users/matt/2022/03/27/venv/lib/python3.10/site-packages/airflow/jobs/scheduler_job.py", line 843, in _run_scheduler_loop
    num_finished_events = self._process_executor_events(session=session)
  File "/Users/matt/2022/03/27/venv/lib/python3.10/site-packages/airflow/utils/session.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/Users/matt/2022/03/27/venv/lib/python3.10/site-packages/airflow/jobs/scheduler_job.py", line 707, in _process_executor_events
    ti.handle_failure(error=msg % (ti, state, ti.state, info), session=session)
  File "/Users/matt/2022/03/27/venv/lib/python3.10/site-packages/airflow/utils/session.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/Users/matt/2022/03/27/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1793, in handle_failure
    task = self.task.unmap()
  File "/Users/matt/2022/03/27/venv/lib/python3.10/site-packages/airflow/models/mappedoperator.py", line 456, in unmap
    raise RuntimeError("Cannot unmap a deserialized operator")
RuntimeError: Cannot unmap a deserialized operator
[2022-03-27 21:48:58,450] {process_utils.py:125} INFO - Sending Signals.SIGTERM to group 36986. PIDs of all processes in the group: [36986]
[2022-03-27 21:48:58,450] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 36986
[2022-03-27 21:48:58,683] {process_utils.py:75} INFO - Process psutil.Process(pid=36986, status='terminated', exitcode=0, started='21:48:45') (36986) terminated with exit code 0
[2022-03-27 21:48:58,684] {scheduler_job.py:780} INFO - Exited execute loop
```

</details>

After some updates, this now fails with the following scheduler logs:

```
  ____________       _____________
 ____    |__( )_________  __/__  /________      __
____  /| |_  /__  ___/_  /_ __  /_  __ \_ | /| / /
___  ___ |  / _  /   _  __/ _  / / /_/ /_ |/ |/ /
 _/_/  |_/_/  /_/    /_/    /_/  \____/____/|__/
[2022-03-28 08:40:44,195] {scheduler_job.py:712} INFO - Starting the scheduler
[2022-03-28 08:40:44,196] {scheduler_job.py:717} INFO - Processing each file at most -1 times
[2022-03-28 08:40:44,199] {executor_loader.py:106} INFO - Loaded executor: SequentialExecutor
[2022-03-28 08:40:44,204] {manager.py:156} INFO - Launched DagFileProcessorManager with pid: 47735
[2022-03-28 08:40:44,206] {scheduler_job.py:1242} INFO - Resetting orphaned tasks for active dag runs
[2022-03-28 08:40:44,769] {settings.py:55} INFO - Configured default timezone Timezone('UTC')
[2022-03-28 08:40:44,774] {manager.py:398} WARNING - Because we cannot use more than 1 thread (parsing_processes = 2)
when using sqlite. So we set parallelism to 1.
[2022-03-28 08:40:45 -0600] [47734] [INFO] Starting gunicorn 20.1.0
[2022-03-28 08:40:45 -0600] [47734] [INFO] Listening at: http://0.0.0.0:8793 (47734)
[2022-03-28 08:40:45 -0600] [47734] [INFO] Using worker: sync
[2022-03-28 08:40:45 -0600] [47740] [INFO] Booting worker with pid: 47740
[2022-03-28 08:40:45 -0600] [47741] [INFO] Booting worker with pid: 47741
[2022-03-28 08:40:53,363] {dag.py:2930} INFO - Setting next_dagrun for my_name_is to 1999-12-25T00:00:00+00:00, run_af
ter=2029-12-17T00:00:00+00:00
[2022-03-28 08:40:53,397] {scheduler_job.py:354} INFO - 1 tasks up for execution:
        <TaskInstance: my_name_is.mynameis scheduled__1970-01-01T00:00:00+00:00 [scheduled]>
[2022-03-28 08:40:53,397] {scheduler_job.py:376} INFO - Figuring out tasks to run in Pool(name=default_pool) with 128
open slots and 1 task instances ready to be queued
[2022-03-28 08:40:53,397] {scheduler_job.py:434} INFO - DAG my_name_is has 0/16 running and queued tasks
[2022-03-28 08:40:53,398] {scheduler_job.py:520} INFO - Setting the following tasks to queued state:
        <TaskInstance: my_name_is.mynameis scheduled__1970-01-01T00:00:00+00:00 [scheduled]>
[2022-03-28 08:40:53,400] {scheduler_job.py:562} INFO - Sending TaskInstanceKey(dag_id='my_name_is', task_id='mynameis
', run_id='scheduled__1970-01-01T00:00:00+00:00', try_number=1, map_index=-1) to executor with priority 1 and queue de
fault
[2022-03-28 08:40:53,401] {base_executor.py:88} INFO - Adding to queue: ['airflow', 'tasks', 'run', 'my_name_is', 'myn
ameis', 'scheduled__1970-01-01T00:00:00+00:00', '--local', '--subdir', 'DAGS_FOLDER/my_name_is.py']
[2022-03-28 08:40:53,403] {sequential_executor.py:59} INFO - Executing command: ['airflow', 'tasks', 'run', 'my_name_i
s', 'mynameis', 'scheduled__1970-01-01T00:00:00+00:00', '--local', '--subdir', 'DAGS_FOLDER/my_name_is.py']
[2022-03-28 08:40:54,061] {dagbag.py:506} INFO - Filling up the DagBag from /Users/matt/2022/03/27/dags/my_name_is.py
Traceback (most recent call last):
  File "/Users/matt/2022/03/27/venv2/bin/airflow", line 33, in <module>
    sys.exit(load_entry_point('apache-airflow', 'console_scripts', 'airflow')())
  File "/Users/matt/src/astronomer-airflow/airflow/__main__.py", line 38, in main
    args.func(args)
  File "/Users/matt/src/astronomer-airflow/airflow/cli/cli_parser.py", line 51, in command
    return func(*args, **kwargs)
  File "/Users/matt/src/astronomer-airflow/airflow/utils/cli.py", line 99, in wrapper
    return f(*args, **kwargs)
  File "/Users/matt/src/astronomer-airflow/airflow/cli/commands/task_command.py", line 362, in task_run
    ti, _ = _get_ti(task, args.execution_date_or_run_id, args.map_index)
  File "/Users/matt/src/astronomer-airflow/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/matt/src/astronomer-airflow/airflow/cli/commands/task_command.py", line 144, in _get_ti
    raise RuntimeError("No map_index passed to mapped task")
RuntimeError: No map_index passed to mapped task
[2022-03-28 08:40:54,233] {sequential_executor.py:66} ERROR - Failed to execute task Command '['airflow', 'tasks', 'ru
n', 'my_name_is', 'mynameis', 'scheduled__1970-01-01T00:00:00+00:00', '--local', '--subdir', 'DAGS_FOLDER/my_name_is.p
y']' returned non-zero exit status 1..
[2022-03-28 08:40:54,235] {scheduler_job.py:615} INFO - Executor reports execution of my_name_is.mynameis run_id=sched
uled__1970-01-01T00:00:00+00:00 exited with status failed for try_number 1
[2022-03-28 08:40:54,245] {scheduler_job.py:659} INFO - TaskInstance Finished: dag_id=my_name_is, task_id=mynameis, ru
n_id=scheduled__1970-01-01T00:00:00+00:00, map_index=-1, run_start_date=None, run_end_date=None, run_duration=None, st
ate=queued, executor_state=failed, try_number=1, max_tries=0, job_id=None, pool=default_pool, queue=default, priority_
weight=1, operator=_PythonDecoratedOperator, queued_dttm=2022-03-28 14:40:53.398693+00:00, queued_by_job_id=1, pid=Non
e
[2022-03-28 08:40:54,246] {scheduler_job.py:688} ERROR - Executor reports task instance <TaskInstance: my_name_is.myna
meis scheduled__1970-01-01T00:00:00+00:00 [queued]> finished (failed) although the task says its queued. (Info: None)
Was the task killed externally?
[2022-03-28 08:40:54,247] {taskinstance.py:1785} ERROR - Executor reports task instance <TaskInstance: my_name_is.myna
meis scheduled__1970-01-01T00:00:00+00:00 [queued]> finished (failed) although the task says its queued. (Info: None)
Was the task killed externally?
[2022-03-28 08:40:54,255] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=my_name_is, task_id=mynameis, e
xecution_date=19700101T000000, start_date=, end_date=20220328T144054
[2022-03-28 08:40:54,322] {dagrun.py:534} ERROR - Marking run <DagRun my_name_is @ 1970-01-01 00:00:00+00:00: schedule
d__1970-01-01T00:00:00+00:00, externally triggered: False> failed
[2022-03-28 08:40:54,323] {dagrun.py:594} INFO - DagRun Finished: dag_id=my_name_is, execution_date=1970-01-01 00:00:0
0+00:00, run_id=scheduled__1970-01-01T00:00:00+00:00, run_start_date=2022-03-28 14:40:53.370452+00:00, run_end_date=20
22-03-28 14:40:54.323434+00:00, run_duration=0.952982, state=failed, external_trigger=False, run_type=scheduled, data_
interval_start=1970-01-01 00:00:00+00:00, data_interval_end=1999-12-25 00:00:00+00:00, dag_hash=fb9f4777fcb737e19d3401
99f9950b05
[2022-03-28 08:40:54,325] {dagrun.py:774} WARNING - Failed to record first_task_scheduling_delay metric:
list index out of range
[2022-03-28 08:40:54,326] {dag.py:2930} INFO - Setting next_dagrun for my_name_is to 1999-12-25T00:00:00+00:00, run_af
ter=2029-12-17T00:00:00+00:00
```

**Comment by uranusjr** [comment]
Can you try if #22396 fixes this?

**Comment by MatrixManAtYrService** [comment]
@uranusjr  it does prevent the scheduler from crashing, but the task fails and I don't get any task logs from it (`./logs/dag_id=my_name_is` doesn't appear).

Here are the scheduler logs:

```
  ____________       _____________
 ____    |__( )_________  __/__  /________      __
____  /| |_  /__  ___/_  /_ __  /_  __ \_ | /| / /
___  ___ |  / _  /   _  __/ _  / / /_/ /_ |/ |/ /
 _/_/  |_/_/  /_/    /_/    /_/  \____/____/|__/
[2022-03-28 08:40:44,195] {scheduler_job.py:712} INFO - Starting the scheduler
[2022-03-28 08:40:44,196] {scheduler_job.py:717} INFO - Processing each file at most -1 times
[2022-03-28 08:40:44,199] {executor_loader.py:106} INFO - Loaded executor: SequentialExecutor
[2022-03-28 08:40:44,204] {manager.py:156} INFO - Launched DagFileProcessorManager with pid: 47735
[2022-03-28 08:40:44,206] {scheduler_job.py:1242} INFO - Resetting orphaned tasks for active dag runs
[2022-03-28 08:40:44,769] {settings.py:55} INFO - Configured default timezone Timezone('UTC')
[2022-03-28 08:40:44,774] {manager.py:398} WARNING - Because we cannot use more than 1 thread (parsing_processes = 2)
when using sqlite. So we set parallelism to 1.
[2022-03-28 08:40:45 -0600] [47734] [INFO] Starting gunicorn 20.1.0
[2022-03-28 08:40:45 -0600] [47734] [INFO] Listening at: http://0.0.0.0:8793 (47734)
[2022-03-28 08:40:45 -0600] [47734] [INFO] Using worker: sync
[2022-03-28 08:40:45 -0600] [47740] [INFO] Booting worker with pid: 47740
[2022-03-28 08:40:45 -0600] [47741] [INFO] Booting worker with pid: 47741
[2022-03-28 08:40:53,363] {dag.py:2930} INFO - Setting next_dagrun for my_name_is to 1999-12-25T00:00:00+00:00, run_af
ter=2029-12-17T00:00:00+00:00
[2022-03-28 08:40:53,397] {scheduler_job.py:354} INFO - 1 tasks up for execution:
        <TaskInstance: my_name_is.mynameis scheduled__1970-01-01T00:00:00+00:00 [scheduled]>
[2022-03-28 08:40:53,397] {scheduler_job.py:376} INFO - Figuring out tasks to run in Pool(name=default_pool) with 128
open slots and 1 task instances ready to be queued
[2022-03-28 08:40:53,397] {scheduler_job.py:434} INFO - DAG my_name_is has 0/16 running and queued tasks
[2022-03-28 08:40:53,398] {scheduler_job.py:520} INFO - Setting the following tasks to queued state:
        <TaskInstance: my_name_is.mynameis scheduled__1970-01-01T00:00:00+00:00 [scheduled]>
[2022-03-28 08:40:53,400] {scheduler_job.py:562} INFO - Sending TaskInstanceKey(dag_id='my_name_is', task_id='mynameis
', run_id='scheduled__1970-01-01T00:00:00+00:00', try_number=1, map_index=-1) to executor with priority 1 and queue de
fault
[2022-03-28 08:40:53,401] {base_executor.py:88} INFO - Adding to queue: ['airflow', 'tasks', 'run', 'my_name_is', 'myn
ameis', 'scheduled__1970-01-01T00:00:00+00:00', '--local', '--subdir', 'DAGS_FOLDER/my_name_is.py']
[2022-03-28 08:40:53,403] {sequential_executor.py:59} INFO - Executing command: ['airflow', 'tasks', 'run', 'my_name_i
s', 'mynameis', 'scheduled__1970-01-01T00:00:00+00:00', '--local', '--subdir', 'DAGS_FOLDER/my_name_is.py']
[2022-03-28 08:40:54,061] {dagbag.py:506} INFO - Filling up the DagBag from /Users/matt/2022/03/27/dags/my_name_is.py
Traceback (most recent call last):
  File "/Users/matt/2022/03/27/venv2/bin/airflow", line 33, in <module>
    sys.exit(load_entry_point('apache-airflow', 'console_scripts', 'airflow')())
  File "/Users/matt/src/astronomer-airflow/airflow/__main__.py", line 38, in main
    args.func(args)
  File "/Users/matt/src/astronomer-airflow/airflow/cli/cli_parser.py", line 51, in command
    return func(*args, **kwargs)
  File "/Users/matt/src/astronomer-airflow/airflow/utils/cli.py", line 99, in wrapper
    return f(*args, **kwargs)
  File "/Users/matt/src/astronomer-airflow/airflow/cli/commands/task_command.py", line 362, in task_run
    ti, _ = _get_ti(task, args.execution_date_or_run_id, args.map_index)
  File "/Users/matt/src/astronomer-airflow/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/matt/src/astronomer-airflow/airflow/cli/commands/task_command.py", line 144, in _get_ti
    raise RuntimeError("No map_index passed to mapped task")
RuntimeError: No map_index passed to mapped task
[2022-03-28 08:40:54,233] {sequential_executor.py:66} ERROR - Failed to execute task Command '['airflow', 'tasks', 'ru
n', 'my_name_is', 'mynameis', 'scheduled__1970-01-01T00:00:00+00:00', '--local', '--subdir', 'DAGS_FOLDER/my_name_is.p
y']' returned non-zero exit status 1..
[2022-03-28 08:40:54,235] {scheduler_job.py:615} INFO - Executor reports execution of my_name_is.mynameis run_id=sched
uled__1970-01-01T00:00:00+00:00 exited with status failed for try_number 1
[2022-03-28 08:40:54,245] {scheduler_job.py:659} INFO - TaskInstance Finished: dag_id=my_name_is, task_id=mynameis, ru
n_id=scheduled__1970-01-01T00:00:00+00:00, map_index=-1, run_start_date=None, run_end_date=None, run_duration=None, st
ate=queued, executor_state=failed, try_number=1, max_tries=0, job_id=None, pool=default_pool, queue=default, priority_
weight=1, operator=_PythonDecoratedOperator, queued_dttm=2022-03-28 14:40:53.398693+00:00, queued_by_job_id=1, pid=Non
e
[2022-03-28 08:40:54,246] {scheduler_job.py:688} ERROR - Executor reports task instance <TaskInstance: my_name_is.myna
meis scheduled__1970-01-01T00:00:00+00:00 [queued]> finished (failed) although the task says its queued. (Info: None)
Was the task killed externally?
[2022-03-28 08:40:54,247] {taskinstance.py:1785} ERROR - Executor reports task instance <TaskInstance: my_name_is.myna
meis scheduled__1970-01-01T00:00:00+00:00 [queued]> finished (failed) although the task says its queued. (Info: None)
Was the task killed externally?
[2022-03-28 08:40:54,255] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=my_name_is, task_id=mynameis, e
xecution_date=19700101T000000, start_date=, end_date=20220328T144054
[2022-03-28 08:40:54,322] {dagrun.py:534} ERROR - Marking run <DagRun my_name_is @ 1970-01-01 00:00:00+00:00: schedule
d__1970-01-01T00:00:00+00:00, externally triggered: False> failed
[2022-03-28 08:40:54,323] {dagrun.py:594} INFO - DagRun Finished: dag_id=my_name_is, execution_date=1970-01-01 00:00:0
0+00:00, run_id=scheduled__1970-01-01T00:00:00+00:00, run_start_date=2022-03-28 14:40:53.370452+00:00, run_end_date=20
22-03-28 14:40:54.323434+00:00, run_duration=0.952982, state=failed, external_trigger=False, run_type=scheduled, data_
interval_start=1970-01-01 00:00:00+00:00, data_interval_end=1999-12-25 00:00:00+00:00, dag_hash=fb9f4777fcb737e19d3401
99f9950b05
[2022-03-28 08:40:54,325] {dagrun.py:774} WARNING - Failed to record first_task_scheduling_delay metric:
list index out of range
[2022-03-28 08:40:54,326] {dag.py:2930} INFO - Setting next_dagrun for my_name_is to 1999-12-25T00:00:00+00:00, run_af
ter=2029-12-17T00:00:00+00:00
```

**Comment by uranusjr** [comment]
Ah currently we only expand when a task’s upstreams all finish. But this fails since `mynameis` here does not have any upstreams! We’ll need to rethink where we expand.

**Comment by uranusjr** [comment]
Hmm, in DagRun we currently have this block of code

https://github.com/apache/airflow/blob/55ee62e28a0209349bf3e49a25565e7719324500/airflow/models/dagrun.py#L687-L701

But I can’t find expansion code in LocalTaskJob at all. Maybe we never actually implemented it? @ashb

And even if we are to do expansion in LocalTaskJob, I think the comment here is still not right? It should be the other way around: Since code in DagRun is run when a task instance is scheduled, it happens _before_ that task instance reaches LocalTaskJob. In other words, DagRun would be the primary place where expansions happen, and LocalTaskJob only if expansion did not happen in DagRun.

**Comment by ephraimbuddy** [comment]
> Ah currently we only expand when a task’s upstreams all finish. But this fails since `mynameis` here does not have any upstreams! We’ll need to rethink where we expand.

Yeah. That worked. Another behaviour was that the task logs was not available on the filesystem and the UI

**Comment by ashb** [comment]
LocalTaskJob calls this inside `_run_mini_scheduler_on_child_tasks` https://github.com/apache/airflow/blob/9798c8cad1c2fe7e674f8518cbe5151e91f1ca7e/airflow/jobs/local_task_job.py#L266 

https://github.com/apache/airflow/blob/9798c8cad1c2fe7e674f8518cbe5151e91f1ca7e/airflow/models/dagrun.py#L640-L645

which goes to 
https://github.com/apache/airflow/blob/9798c8cad1c2fe7e674f8518cbe5151e91f1ca7e/airflow/models/dagrun.py#L687-L701

So that "expansion of last resort" comment is wrong, as that is not last resort but primary place when it's called from LTJ.

**Comment by ashb** [comment]
That is, at the end of LocalTaskJob, when a task finishes we make scheduling decisions for the downstream tasks, including expanding them if we can.

We don't explicitly test this, we probably should.

**Comment by uranusjr** [comment]
This takes us back to the original issue here though, where should we expand if a task does not have upstreams? Maybe during `DagRun.verify_integrity`?

**Comment by ashb** [comment]
https://github.com/apache/airflow/blob/25b62a72f4470186e33ad6a6c160da2e31a90668/tests/models/test_dagrun.py#L910-L924 you mean? 😁

**Comment by ashb** [comment]
I'll start making that pass.

**Comment by MatrixManAtYrService** [comment]
I ran into this a second time, except this time I was also getting:
```
    sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) FOREIGN KEY constraint failed
```

[Here's the full story](https://gist.github.com/MatrixManAtYrService/8f678c46d8e5dc065388db49ededc69d).  I assume that the extra error is just a consequence of the first, but it might be worth trying both as part of testing this fix.
