### ISSUE TITLE
Click on Show record on List Users page gives error

### ISSUE THREAD

**Issue by h5chauhan** [apache/airflow#22847]
### Apache Airflow version

2.2.4

### What happened

Click Security -> List Users -> Click on Show Record (Magnifying Glass icon) gives the following error

```
Python version: 3.7.9
Airflow version: 2.2.4
Node: efbf8d12bb39
-------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/flask_appbuilder/security/decorators.py", line 148, in wraps
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/www/views.py", line 4699, in show
    widgets['show'].template_args['actions'].pop('userinfoedit')
KeyError: 'userinfoedit'
```

### Operating System

Dedian Docker

### Deployment

Other Docker-based deployment

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by hankehly** [comment]
I am also experiencing this on [v2.2.4](https://pypi.python.org/pypi/apache-airflow/2.2.4) / ee9049c0566b2539a247687de05f9cffa008f871. Will take a look.

**Comment by tirkarthi** [comment]
possible duplicate of https://github.com/apache/airflow/issues/22035

**Comment by uranusjr** [comment]
Duplicate of #22035
