### ISSUE TITLE
Upgrade from 2.2.4 to 2.2.5 failed

### ISSUE THREAD

**Issue by AlekseiSaff** [apache/airflow#22889]
### Apache Airflow version

2.2.5 (latest released)

### What happened

update from 2.2.4 to 2.2.5 was succeeded, but failure on "airflow db upgrade" has failed

### What you think should happen instead

after updating 2.2.4 to 2.2.5 with
pip3.6 install apache-airflow[all]==2.2.5 --upgrade --constraint https://raw.githubusercontent.com/apache/airflow/constraints-2.2.5/constraints-3.6.txt

and making "airflow db upgrade" receiving

[lt@lt-hkg1-avm04 experiments]$ airflow db upgrade
DB: mysql://airflow:***@localhost/airflow
[2022-04-11 00:34:11,685] {db.py:919} INFO - Creating tables
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/airflow/__main__.py", line 48, in main
    args.func(args)
  File "/usr/local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/airflow/cli/commands/db_command.py", line 48, in upgradedb
    db.upgradedb()
  File "/usr/local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/airflow/utils/db.py", line 920, in upgradedb
    command.upgrade(config, 'heads')
  File "/usr/local/lib/python3.6/site-packages/alembic/command.py", line 320, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.6/site-packages/alembic/script/base.py", line 563, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.6/site-packages/alembic/util/pyfiles.py", line 92, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.6/site-packages/alembic/util/pyfiles.py", line 108, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.6/site-packages/airflow/migrations/env.py", line 107, in <module>
    run_migrations_online()
  File "/usr/local/lib/python3.6/site-packages/airflow/migrations/env.py", line 101, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/local/lib/python3.6/site-packages/alembic/runtime/environment.py", line 851, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/lib/python3.6/site-packages/alembic/runtime/migration.py", line 608, in run_migrations
    for step in self._migrations_fn(heads, self):
  File "/usr/local/lib/python3.6/site-packages/alembic/command.py", line 309, in upgrade
    return script._upgrade_revs(revision, rev)
  File "/usr/local/lib/python3.6/site-packages/alembic/script/base.py", line 439, in _upgrade_revs
    for script in reversed(list(revs))
  File "/usr/local/lib/python3.6/site-packages/alembic/script/revision.py", line 794, in iterate_revisions
    assert_relative_length=assert_relative_length,
  File "/usr/local/lib/python3.6/site-packages/alembic/script/revision.py", line 1392, in _collect_upgrade_revisions
    assert_relative_length=assert_relative_length,
  File "/usr/local/lib/python3.6/site-packages/alembic/script/revision.py", line 1189, in _parse_upgrade_target
    return self.get_revisions(target)
  File "/usr/local/lib/python3.6/site-packages/alembic/script/revision.py", line 528, in get_revisions
    id_  # type:ignore [arg-type]
  File "/usr/local/lib/python3.6/site-packages/alembic/script/revision.py", line 743, in _resolve_revision_number
    self._revision_map
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 893, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/usr/local/lib/python3.6/site-packages/alembic/script/revision.py", line 189, in _revision_map
    for revision in self._generator():
  File "/usr/local/lib/python3.6/site-packages/alembic/script/base.py", line 136, in _load_revisions
    script = Script._from_filename(self, vers, file_)
  File "/usr/local/lib/python3.6/site-packages/alembic/script/base.py", line 999, in _from_filename
    module = util.load_python_file(dir_, filename)
  File "/usr/local/lib/python3.6/site-packages/alembic/util/pyfiles.py", line 92, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.6/site-packages/alembic/util/pyfiles.py", line 108, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.6/site-packages/airflow/migrations/versions/82b7c48c147f_remove_can_read_permission_on_config_.py", line 29, in <module>
    from airflow.www.app import create_app
  File "/usr/local/lib/python3.6/site-packages/airflow/www/app.py", line 42, in <module>
    from airflow.www.extensions.init_views import (
  File "/usr/local/lib/python3.6/site-packages/airflow/www/extensions/init_views.py", line 28, in <module>
    from airflow.www.views import lazy_add_provider_discovered_options_to_connection_form
  File "/usr/local/lib/python3.6/site-packages/airflow/www/views.py", line 123, in <module>
    from airflow.www import auth, utils as wwwutils
  File "/usr/local/lib/python3.6/site-packages/airflow/www/utils.py", line 24, in <module>
    import markdown
  File "/usr/local/lib/python3.6/site-packages/markdown/__init__.py", line 29, in <module>
    from .core import Markdown, markdown, markdownFromFile  # noqa: E402
  File "/usr/local/lib/python3.6/site-packages/markdown/core.py", line 26, in <module>
    from . import util
  File "/usr/local/lib/python3.6/site-packages/markdown/util.py", line 88, in <module>
    INSTALLED_EXTENSIONS = metadata.entry_points(group='markdown.extensions')
TypeError: entry_points() got an unexpected keyword argument 'group'

### How to reproduce

update from 2.2.4 to 2.2.5 and execute "airflow db upgrade" command

### Operating System

CentOS 7.9

### Deployment

Other

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
You likely did not follow the only supported way of installing/upgrading airflow - i.e. using constraints (https://airflow.apache.org/docs/apache-airflow/stable/installation/installing-from-pypi.html)
