### ISSUE TITLE
A task's returned object should not be checked for mappability if the dag doesn't use it in an expansion.

### ISSUE THREAD

**Issue by MatrixManAtYrService** [apache/airflow#23018]
### Apache Airflow version

main (development)

### What happened

Here's a dag:

```python3
with DAG(...) as dag:

    @dag.task
    def foo():
        return "foo"

    @dag.task
    def identity(thing):
        return thing

    foo() >> identity.expand(thing=[1, 2, 3])
```

`foo` fails with these task logs:
```
[2022-04-14, 14:15:26 UTC] {python.py:173} INFO - Done. Returned value was: foo
[2022-04-14, 14:15:26 UTC] {taskinstance.py:1837} WARNING - We expected to get frame set in local storage but it was not. Please report this as an issue with full logs at https://github.com/apache/airflow/issues/new
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1417, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1564, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1634, in _execute_task
    self._record_task_map_for_downstreams(task_orig, result, session=session)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2314, in _record_task_map_for_downstreams
    raise UnmappableXComTypePushed(value)
airflow.exceptions.UnmappableXComTypePushed: unmappable return type 'str'
```

### What you think should happen instead

Airflow shouldn't bother checking `foo`'s return type for mappability because its return value is never used in an expansion.

### How to reproduce

Run the dag, notice the failure

### Operating System

debian (docker)

### Versions of Apache Airflow Providers

n/a

### Deployment

Astronomer

### Deployment details

using image with ref: e5dd6fdcfd2f53ed90e29070711c121de447b404

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by ashb** [comment]
Marking this to 2.3.0, but we _might_ push it to 2.3.1

**Comment by uranusjr** [comment]
Assigning myself, but it’s Friday, so feel free to work on this if you think you can tackle it during the weekend.

**Comment by appassionate** [comment]
same problem when I was trying airflow 2.3.0b1, but more complex python object in "foo" return_value with  xcom_pickling ON.

hope ".expand" method will not reject "picklable" object.  :P
