### ISSUE TITLE
Airflow ecs fail to fetch logs from cloudwatch

### ISSUE THREAD

**Issue by thinhnd2104** [apache/airflow#23469]
### Apache Airflow Provider(s)

amazon

### Apache Airflow version

2.3.0 (latest released)

### Operating System

Linux

### Deployment

Docker-Compose

### What happened

botocore.exceptions.ConnectionClosedError: Connection was closed before we received a valid response from endpoint URL: "https://logs.ap-southeast-1.amazonaws.com//".
`Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/airflow/providers/amazon/aws/operators/ecs.py", line 119, in run
    for log_event in log_events:
  File "/home/ubuntu/.local/lib/python3.6/site-packages/airflow/providers/amazon/aws/operators/ecs.py", line 126, in _get_log_events
    yield from self.hook.get_log_events(self.log_group, self.log_stream_name, skip=skip)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/airflow/providers/amazon/aws/hooks/logs.py", line 80, in get_log_events
    **token_arg,
  File "/home/ubuntu/.local/lib/python3.6/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/botocore/client.py", line 692, in _make_api_call
    operation_model, request_dict, request_context)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/botocore/client.py", line 711, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/botocore/endpoint.py", line 137, in _send_request
    success_response, exception):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/botocore/endpoint.py", line 256, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/botocore/retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
  File "/home/ubuntu/.local/lib/python3.6/site-packages/botocore/endpoint.py", line 200, in _do_get_response
    http_response = self._send(request)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/botocore/endpoint.py", line 269, in _send
    return self.http_session.send(request)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/botocore/httpsession.py", line 363, in send
    endpoint_url=request.url
botocore.exceptions.ConnectionClosedError: Connection was closed before we received a valid response from endpoint URL: "https://logs.ap-southeast-1.amazonaws.com//".
[2022-04-30, 02:05:03 +07] {logging_mixin.py:109} WARNING -`

### What you think should happen instead

return empty like `ClientError` exception

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
@thinhnd2104 - do you think the issue is closed by #23470 ?

**Comment by thinhnd2104** [comment]
@potiuk yes. Thank you!
