### ISSUE TITLE
`BigQueryCheckOperator` not working with `EXTERNAL_QUERY`

### ISSUE THREAD

**Issue by sp1thas** [apache/airflow#23619]
### Apache Airflow version

2.2.5

### What happened

When trying to validate an external query using the `BigQueryCheckOperator`, a `googleapiclient.errors.HttpError` is raised:

```
[2022-05-10, 10:33:54 UTC] {taskinstance.py:1774} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/sql.py", line 121, in execute
    records = self.get_db_hook().get_first(self.sql)
  File "/usr/local/lib/python3.9/site-packages/airflow/hooks/dbapi.py", line 174, in get_first
    return cur.fetchone()
  File "/usr/local/lib/python3.9/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 2645, in fetchone
    return self.next()
  File "/usr/local/lib/python3.9/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 2661, in next
    self.service.jobs()
  File "/usr/local/lib/python3.9/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/googleapiclient/http.py", line 915, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://bigquery.googleapis.com/bigquery/v2/projects/**********:airflow_1652178832396736_7175dd2c8ed25541380ac477abcfbc4a". Details: "Not found: Job **********:airflow_1652178832396736_7175dd2c8ed25541380ac477abcfbc4a">
```

### What you think should happen instead

Execute the task successfully. 

### How to reproduce

Firstly, you have to configure the necessary GCP connection on the airflow, and create an external connection on the GCP (In my case, the external query is executed in a CloudSQL Postgres instance). The following DAG will raise an `googleapiclient.errors.HttpError`.

```python
from datetime import datetime

from airflow.providers.google.cloud.operators.bigquery import BigQueryCheckOperator

from airflow import DAG

CONNECTION_ID = 'projects/************/locations/us-east1/connections/mgmt-nav-account'


dag = DAG(
    'foo',
    schedule_interval=None,
    start_date=datetime(2022, 4, 8),
    description='',
    catchup=False,
)

with dag:
    query = f'SELECT * FROM EXTERNAL_QUERY("{CONNECTION_ID}", "select true;");'

    table_schema_validation = BigQueryCheckOperator(
       task_id=f'validate_external_schema',
       sql=query,
       use_legacy_sql=False,
       gcp_conn_id='google_cloud_default'
    )
```

### Operating System

Pop!_OS 22.04 LTS

### Versions of Apache Airflow Providers

```
apache-airflow-providers-amazon==3.2.0
apache-airflow-providers-celery==2.1.3
apache-airflow-providers-cncf-kubernetes==3.0.0
apache-airflow-providers-databricks==2.5.0
apache-airflow-providers-elasticsearch==2.2.0
apache-airflow-providers-ftp==2.1.2
apache-airflow-providers-google==6.7.0
apache-airflow-providers-http==2.1.2
apache-airflow-providers-imap==2.2.3
apache-airflow-providers-postgres==4.1.0
apache-airflow-providers-redis==2.0.4
apache-airflow-providers-slack==4.2.3
apache-airflow-providers-snowflake==2.6.0
apache-airflow-providers-sqlite==2.1.3
```

### Deployment

Astronomer

### Deployment details

```
Docker version 20.10.14, build a224086
docker-compose version 1.29.2, build 5becea4c
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by sp1thas** [comment]
After explicitly specifying the `location` parameter, `BigQueryCheckOperator` seems to work as expected.
