### ISSUE TITLE
Dbt Operators no longer working after migrating to Airflow 2.3.0

### ISSUE THREAD

**Issue by cyoung43** [apache/airflow#23652]
### Apache Airflow version

2.3.0 (latest released)

### What happened

Since migrating to Airflow 2.3.0, `DbtRunOperator` -- and any DBT related operator, are no longer working in production. `DBT` is not recognized as a command, even with dependency packages installed. I have a dbt project already initialized, and am also specifying the path to the dbt directory.

```
[2022-05-11, 13:13:37 MDT] {dbt_hook.py:117} INFO - dbt run --profiles-dir /usr/local/airflow/dags/dbt/
[2022-05-11, 13:13:37 MDT] {taskinstance.py:1888} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/astro/.local/lib/python3.9/site-packages/airflow_dbt/operators/dbt_operator.py", line 98, in execute
    self.create_hook().run_cli('run')
  File "/home/astro/.local/lib/python3.9/site-packages/airflow_dbt/hooks/dbt_hook.py", line 119, in run_cli
    sp = subprocess.Popen(
  File "/usr/local/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'dbt'
[2022-05-11, 13:13:37 MDT] {taskinstance.py:1394} INFO - Marking task as UP_FOR_RETRY. dag_id=dags_to_use, task_id=dbt_run, execution_date=20220511T191332, start_date=20220511T191337, end_date=20220511T191337
[2022-05-11, 13:13:37 MDT] {standard_task_runner.py:92} ERROR - Failed to execute job 47 for task dbt_run ([Errno 2] No such file or directory: 'dbt'; 9219)
```

I have also tried using a `BashOperator` to run dbt commands, but am getting the same error.

### What you think should happen instead

Expected behavior: The `DbtRunOperator` runs the models currently in the dbt directory. 

Sample dbt operator. This was working fine in previous Airflow releases
```python
dbt_run = DbtRunOperator(
        task_id="dbt_run",
        dir="/usr/local/airflow/dags/dbt/",
        profiles_dir='/usr/local/airflow/dags/dbt/',
    )
```

### How to reproduce

1. Install [astronomer cli](https://docs.astronomer.io/astro/install-cli)
2. `astrocloud dev init`
3. Initialize dbt project inside `/dags` directory
    - `pip install dbt-snowflake`
    - `dbt init`
4. Add following to airflow `requirements.txt`
```
dbt-snowflake==1.0.0
airflow-dbt==0.4.0
```
5. `astrocloud dev start`
6. Add `DbtRunOperator` code block to DAG file
```python
dbt_run = DbtRunOperator(
        task_id="dbt_run",
        dir="/usr/local/airflow/dags/dbt/",
        profiles_dir='/usr/local/airflow/dags/dbt/',
    )
```
7. Trigger dag from UI

### Operating System

OS: Microsoft Windows 10 Enterprise; Version: 10.0.19042 Build 19042

### Versions of Apache Airflow Providers

```
airflow-dbt==0.4.0
```

### Deployment

Astronomer

### Deployment details

Local Astronomer deployment via Docker

```dockerfile
FROM quay.io/astronomer/ap-airflow:2.3.0
```

### Anything else

This occurs every time on dag run

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by tirkarthi** [comment]
Can you try passing "dbt_bin" with full path to dbt binary? Just to add the operator is not part of the core airflow codebase and comes from https://github.com/gocardless/airflow-dbt

**Comment by potiuk** [comment]
Yeah. Please raise it to DBT team. This is issue witht their provider, not Airflow.
