### ISSUE TITLE
s3 connection missing from models.py

### ISSUE THREAD

**Issue by kmmats** [apache/airflow#240]
I'm trying to use the S3KeySensor operator but there doesn't seem to be a way to pass the s3 connection information -- I get this error: 

```
2015-08-09 04:33:46,282 - root - ERROR - Type not supported for templating
Traceback (most recent call last):
  File "/home/ubuntu/anaconda/envs/papertrailpull/lib/python2.7/site-packages/airflow/models.py", line 830, in run
    self.render_templates()
  File "/home/ubuntu/anaconda/envs/papertrailpull/lib/python2.7/site-packages/airflow/models.py", line 965, in render_templates
    raise AirflowException("Type not supported for templating")
AirflowException: Type not supported for templating
2015-08-09 04:33:46,283 - root - ERROR - Type not supported for templating
Traceback (most recent call last):
  File "/home/ubuntu/anaconda/envs/papertrailpull/bin/airflow", line 10, in <module>
    args.func(args)
  File "/home/ubuntu/anaconda/envs/papertrailpull/lib/python2.7/site-packages/airflow/bin/cli.py", line 201, in test
    ti.run(force=True, ignore_dependencies=True, test_mode=True)
  File "/home/ubuntu/anaconda/envs/papertrailpull/lib/python2.7/site-packages/airflow/models.py", line 830, in run
    self.render_templates()
  File "/home/ubuntu/anaconda/envs/papertrailpull/lib/python2.7/site-packages/airflow/models.py", line 965, in render_templates
    raise AirflowException("Type not supported for templating")
airflow.utils.AirflowException: Type not supported for templating
```

**Comment by mistercrunch** [comment]
Are you passing an object to either `bucket_key` or `bucket_name`? Both of these should be a string as documented here:
http://pythonhosted.org/airflow/code.html#airflow.operators.S3KeySensor

**Comment by mistercrunch** [comment]
I improved the message so that it will look something like this in the future:

```
Type '<type 'datetime.datetime'>' used for parameter 'bash_command' is not supported for templating
```

Related commit: https://github.com/airbnb/airflow/commit/25d5300bc959d4ae7b86e44dbc56012deca9eefd

**Comment by kmmats** [comment]
Those details in the message would be very helpful. I was thinking it was referring to my attempt to specify a s3_conn_id.  Does it just pick up the credentials for s3 from my local  ~/.aws/config so s3_conn_id is unnecessary? Now that I understand the context, I think my issue was because the key was a python function that returned a string.

**Comment by artwr** [comment]
Hi @kmmats, the sensor is probably due for a refactor. For various reasons we have had to be able to specify connections from different files than just ~/.aws/config. In the connection definition, you can specify the config file you want to use and its type in "extras" as json :
`{"s3_config_file": "/home/kmmats/.aws/config", "s3_config_format": "aws"}`

See [here](https://github.com/airbnb/airflow/blob/master/airflow/hooks/S3_hook.py#L83-L98) for more details. I hope this helps.

**Comment by kmmats** [comment]
@artwr @mistercrunch - super helpful thanks!
