### ISSUE TITLE
Grid view broken for DAG

### ISSUE THREAD

**Issue by voltcode** [apache/airflow#24345]
### Apache Airflow version

2.3.1

### What happened

1. minor changes to the dag (task name was changed)
2. after rerunning the dag (manual trigger), grid view is broken - it does not show up, there is a js error in browser console

console stack trace:

```
grid.7837d330ccbe38f7d60a.js:2 TypeError: Cannot read properties of null (reading 'runId')
    at grid.7837d330ccbe38f7d60a.js:2:745520
    at Array.find (<anonymous>)
    at grid.7837d330ccbe38f7d60a.js:2:745509
    at Array.map (<anonymous>)
    at lC (grid.7837d330ccbe38f7d60a.js:2:745480)
    at ui (grid.7837d330ccbe38f7d60a.js:2:228868)
    at Qu (grid.7837d330ccbe38f7d60a.js:2:280949)
    at Pl (grid.7837d330ccbe38f7d60a.js:2:268222)
    at jl (grid.7837d330ccbe38f7d60a.js:2:268150)
    at Cl (grid.7837d330ccbe38f7d60a.js:2:268013)
```

when I created a copy of the dag with new names, the new dag renders fine in grid view

### What you think should happen instead

not sure what the cause of the problem is, but it would be a good idea to guard against invalid data coming out of the server, perhaps show an error message in the UI + advise on creating new dag.

### How to reproduce

I'm not sure if it is reproducible easily, something must've happened to the dag that broke it, I don't know if renameing the task did it.

### Operating System

airflow in official image, browser - chrome on windows.

### Deployment

Docker-Compose

### Anything else

the grid view for the dag is permanently broken

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by voltcode** [comment]
Thanks a lot for the suggestion! The grid view works fine in 2.3.2.
