### ISSUE TITLE
Airflow db upgrade fails to insert rows in log_template table

### ISSUE THREAD

**Issue by dcardinha** [apache/airflow#24400]
### Apache Airflow version

2.3.2 (latest released)

### What happened

When trying to run airflow db upgrade I get the following errors:
```
ts="2022-06-12 12:24:15,722" class="airflow.utils.db" level="INFO" msg="Creating tables"
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/base.py", line 1706, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/default.py", line 716, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.NotNullViolation: null value in column "task_prefix" violates not-null constraint
DETAIL:  Failing row contains (250, dag_id={{ ti.dag_id }}/run_id={{ ti.run_id }}/task_id={{ ti.task..., null, {dag_id}-{task_id}-{run_id}-{map_index}-{try_number}, 2022-06-12 12:24:17.204742+00).

...

sqlalchemy.exc.IntegrityError: (psycopg2.errors.NotNullViolation) null value in column "task_prefix" violates not-null constraint
DETAIL:  Failing row contains (250, dag_id={{ ti.dag_id }}/run_id={{ ti.run_id }}/task_id={{ ti.task..., null, {dag_id}-{task_id}-{run_id}-{map_index}-{try_number}, 2022-06-12 12:24:17.204742+00).

[SQL: INSERT INTO log_template (filename, elasticsearch_id, created_at) VALUES (%(filename)s, %(elasticsearch_id)s, %(created_at)s) RETURNING log_template.id]
[parameters: {'filename': 'dag_id={{ ti.dag_id }}/run_id={{ ti.run_id }}/task_id={{ ti.task_id }}/{% if ti.map_index >= 0 %}map_index={{ ti.map_index }}/{% endif %}attempt={{ try_number }}.log', 'elasticsearch_id': '{dag_id}-{task_id}-{run_id}-{map_index}-{try_number}', 'created_at': datetime.datetime(2022, 6, 12, 12, 24, 17, 204742, tzinfo=Timezone('UTC'))}]



```

### Operating System

ubuntu 16.04

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by uranusjr** [comment]
What version are you upgrading from? `task_prefix` was a field that only existed in some in-development version of Airflow, and upgrading from such versions is not supported. You should downgrade back to a 2.2.x version from the in-development version, and upgrade from there instead.

**Comment by dcardinha** [comment]
Hi, I m upgrading from version 2.2.3, but I am using docker and pruned the postgres volumes so it should be like installing from scratch.
