### ISSUE TITLE
Error when using connector in airflow snowflake hook: module 'snowflake' has no attribute 'connector'

### ISSUE THREAD

**Issue by dollschasingmen** [apache/airflow#24586]
### Apache Airflow Provider(s)

snowflake

### Versions of Apache Airflow Providers

apache-airflow==2.2.2
apache-airflow-providers-amazon==2.4.0
apache-airflow-providers-apache-hive==2.0.3
apache-airflow-providers-celery==2.1.0
apache-airflow-providers-databricks==2.0.2
apache-airflow-providers-ftp==2.0.1
apache-airflow-providers-http==2.0.1
apache-airflow-providers-imap==2.0.1
apache-airflow-providers-jdbc==2.0.1
apache-airflow-providers-mysql==2.1.1
apache-airflow-providers-postgres==2.3.0
apache-airflow-providers-slack==4.1.0
apache-airflow-providers-snowflake==2.3.0
apache-airflow-providers-sqlite==2.0.1
apache-airflow-providers-ssh==2.3.0

### Other relevant library versions

snowflake-connector-python==2.7.0
snowflake-sqlalchemy==1.2.4

### Apache Airflow version

2.2.2

### Operating System

Linux-5.10.25-linuxkit-x86_64-with-debian-10.12

### Deployment

MWAA

### Deployment details

Nothing special, we just upload the dags code, plugins (as a zip), and requirement.txt file to a s3 folder.

### What happened

We tried to use the snowflake hook to run sql in snowflake -- it failed with this error:

```
AttributeError: module 'snowflake' has no attribute 'connector'
```

### What you think should happen instead

It should have run sql on snowflake properly.

### How to reproduce

```
from airflow.providers.snowflake.hooks.snowflake import SnowflakeHook

hook = SnowflakeHook(
    snowflake_conn_id=self.snowflake_conn_id,
    warehouse=self.warehouse,
    database=self.database,
    role=self.role,
    schema=self.schema,
    authenticator=self.authenticator,
    session_parameters=self.session_parameters,
)

hook.run("SELECT * FROM some_test_able")
```
### Anything else

Here is the full stacktrace:

```[2022-06-21, 00:01:08 UTC] {{standard_task_runner.py:91}} ERROR - Failed to execute job 65 for task run_snowflake_sql
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/usr/local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/usr/local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/usr/local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/usr/local/airflow/plugins/snowflake_ingest_plugin/operators/snowflake_sql_operator.py", line 108, in execute
    parameters=full_parameters
  File "/usr/local/airflow/.local/lib/python3.7/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 271, in run
    with self.get_conn() as conn:
  File "/usr/local/airflow/.local/lib/python3.7/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 223, in get_conn
    conn = connector.connect(**conn_config)
  File "/usr/local/airflow/.local/lib/python3.7/site-packages/snowflake/connector/__init__.py", line 50, in Connect
    return SnowflakeConnection(**kwargs)
  File "/usr/local/airflow/.local/lib/python3.7/site-packages/snowflake/connector/connection.py", line 286, in __init__
    self.connect(**kwargs)
  File "/usr/local/airflow/.local/lib/python3.7/site-packages/snowflake/connector/connection.py", line 503, in connect
    self.__config(**kwargs)
  File "/usr/local/airflow/.local/lib/python3.7/site-packages/snowflake/connector/connection.py", line 825, in __config
    self._paramstyle = snowflake.connector.paramstyle
AttributeError: module 'snowflake' has no attribute 'connector'
````

Also I have a similar issue open in the snowflake-python-connector project:

https://github.com/snowflakedb/snowflake-connector-python/issues/1167

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by mik-laj** [comment]
Do you use self-managed Airflow or do you use any service? Can you create a DAG with a BashOperator that will execute a `pip  freeze` command to check if the environment used by Airlfow has the `snowflake-connector-pythonz library installed?

**Comment by tarper24** [comment]
I ran into a similar issue today. We had a file in one of our plugin folders named `snowflake.py` and after renaming that and restarting Airflow, the snowflake connector was working again.

**Comment by LukeHong** [comment]
This should be closed
