### ISSUE TITLE
Allow back script_location in Glue to be None *again*

### ISSUE THREAD

**Issue by jbvsmo** [apache/airflow#24753]
### Apache Airflow version

2.3.2 (latest released)

### What happened

On this commit someone broke the AWS Glue provider by enforcing the script_location to be a string:
https://github.com/apache/airflow/commit/27b77d37a9b2e63e95a123c31085e580fc82b16c

Then someone realized that (see comment thread [there](https://github.com/apache/airflow/commit/27b77d37a9b2e63e95a123c31085e580fc82b16c#r72466413)) and created a new PR to allow None to be parsed again here: https://github.com/apache/airflow/pull/23357

But the parameters no longer have the `Optional[str]` typing and now the error persists with this traceback:

```Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/operators/glue.py", line 163, in __init__
    super().__init__(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'script_location'
```

### What you think should happen instead

Please revert the change and add `Optional[str]` here: https://github.com/apache/airflow/blob/main/airflow/providers/amazon/aws/operators/glue.py#L69

### How to reproduce

Use the class without a script_location

### Operating System

Linux

### Versions of Apache Airflow Providers

Apache airflow 2.3.2

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jbvsmo** [comment]
Proposed fix: https://github.com/apache/airflow/pull/24754
