### ISSUE TITLE
"sql_alchemy_conn" core vs database

### ISSUE THREAD

**Issue by AlekseiSaff** [apache/airflow#24944]
### Apache Airflow version

2.3.2 (latest released)

### What happened

Starting from 2.3.2 and 2.3.3 getting a warning

`Jul 10 10:34:15 lt-hkg1-avm04 airflow: /usr/local/lib/python3.9/site-packages/airflow/configuration.py:532 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.`

but after moving that parameter to database, airflow is not starting. Raising an exception

```
Jul 10 10:32:58 lt-hkg1-avm04 airflow: raise AirflowConfigException(f"section/key [{section}/{key}] not found in config")
Jul 10 10:32:58 lt-hkg1-avm04 airflow: airflow.exceptions.AirflowConfigException: section/key [core/sql_alchemy_conn] not found in config
Jul 10 10:32:58 lt-hkg1-avm04 airflow: [2022-07-10 10:32:58 +0800] [28261] [INFO] Worker exiting (pid: 28261)
Jul 10 10:32:58 lt-hkg1-avm04 airflow: [#033[34m2022-07-10 10:32:58,877#033[0m] {#033[34mconfiguration.py:#033[0m552} WARNING#033[0m - sec
tion/key [core/sql_alchemy_conn] not found in config#033[0m
Jul 10 10:32:58 lt-hkg1-avm04 airflow: [2022-07-10 10:32:58 +0800] [28263] [ERROR] Exception in worker process
Jul 10 10:32:58 lt-hkg1-avm04 airflow: Traceback (most recent call last):
Jul 10 10:32:58 lt-hkg1-avm04 airflow: File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
Jul 10 10:32:58 lt-hkg1-avm04 airflow: worker.init_process()
Jul 10 10:32:58 lt-hkg1-avm04 airflow: File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
Jul 10 10:32:58 lt-hkg1-avm04 airflow: self.load_wsgi()
Jul 10 10:32:58 lt-hkg1-avm04 airflow: File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
Jul 10 10:32:58 lt-hkg1-avm04 airflow: self.wsgi = self.app.wsgi()
Jul 10 10:32:58 lt-hkg1-avm04 airflow: File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
Jul 10 10:32:58 lt-hkg1-avm04 airflow: self.callable = self.load()
Jul 10 10:32:58 lt-hkg1-avm04 airflow: File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
Jul 10 10:32:58 lt-hkg1-avm04 airflow: return self.load_wsgiapp()
Jul 10 10:32:58 lt-hkg1-avm04 airflow: File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
Jul 10 10:32:58 lt-hkg1-avm04 airflow: return util.import_app(self.app_uri)
Jul 10 10:32:58 lt-hkg1-avm04 airflow: File "/usr/local/lib/python3.9/site-packages/gunicorn/util.py", line 412, in import_app
Jul 10 10:32:58 lt-hkg1-avm04 airflow: app = app(*args, **kwargs)
Jul 10 10:32:58 lt-hkg1-avm04 airflow: File "/usr/local/lib/python3.9/site-packages/airflow/www/app.py", line 158, in cached_app
Jul 10 10:32:58 lt-hkg1-avm04 airflow: app = create_app(config=config, testing=testing)
Jul 10 10:32:58 lt-hkg1-avm04 airflow: File "/usr/local/lib/python3.9/site-packages/airflow/www/app.py", line 77, in create_app
Jul 10 10:32:58 lt-hkg1-avm04 airflow: flask_app.config.from_pyfile(settings.WEBSERVER_CONFIG, silent=True)
Jul 10 10:32:58 lt-hkg1-avm04 airflow: File "/usr/local/lib/python3.9/site-packages/flask/config.py", line 185, in from_pyfile
Jul 10 10:32:58 lt-hkg1-avm04 airflow: exec(compile(config_file.read(), filename, "exec"), d.__dict__)
Jul 10 10:32:58 lt-hkg1-avm04 airflow: File "/home/lt/airflow/webserver_config.py", line 32, in <module>
Jul 10 10:32:58 lt-hkg1-avm04 airflow: SQLALCHEMY_DATABASE_URI = conf.get('core', 'SQL_ALCHEMY_CONN')
Jul 10 10:32:58 lt-hkg1-avm04 airflow: File "/usr/local/lib/python3.9/site-packages/airflow/configuration.py", line 544, in get
Jul 10 10:32:58 lt-hkg1-avm04 airflow: return self._get_option_from_default_config(section, key, **kwargs)
Jul 10 10:32:58 lt-hkg1-avm04 airflow: File "/usr/local/lib/python3.9/site-packages/airflow/configuration.py", line 554, in _get_option_fr
om_default_config
```

### What you think should happen instead

Airflow should start with sql_alchemy_conn in [database] section

### How to reproduce

move sql_alchemy_conn from [core] to [database]

### Operating System

CentOS 7.9

### Deployment

Other

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
You likely have not upgraded your webserver - it is apparently running an older version of airlfow.  The new version of airlflow should also (in the webserver) raise a deprecation warning.
