### ISSUE TITLE
Server throws Error5 input/output error when I leave ssh session.

### ISSUE THREAD

**Issue by SteveScott** [apache/airflow#25025]
### Apache Airflow version

2.2.3

### What happened

When I ssh into the server and start the server, no problem. Then I need to exit the server. I use 
```
ctl+z
bg
disown
```
and exit the web server.
When I refresh I get the error Ooops something bad has happened.

```
Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ec2-user/.local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ec2-user/.local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ec2-user/.local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/airflow/www/auth.py", line 51, in decorated
    return func(*args, **kwargs)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/airflow/www/views.py", line 723, in index
    tags=arg_tags_filter if arg_tags_filter else None,
  File "/home/ec2-user/.local/lib/python3.7/site-packages/airflow/www/utils.py", line 110, in generate_pages
    </li>"""
  File "/home/ec2-user/.local/lib/python3.7/site-packages/jinja2/utils.py", line 842, in __new__
    stacklevel=2,
  File "/usr/lib64/python3.7/warnings.py", line 110, in _showwarnmsg
    msg.file, msg.line)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/airflow/settings.py", line 117, in custom_show_warning
    write_console.print(msg, soft_wrap=True)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/rich/console.py", line 1642, in print
    self._buffer.extend(new_segments)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/rich/console.py", line 842, in __exit__
    self._exit_buffer()
  File "/home/ec2-user/.local/lib/python3.7/site-packages/rich/console.py", line 800, in _exit_buffer
    self._check_buffer()
  File "/home/ec2-user/.local/lib/python3.7/site-packages/rich/console.py", line 1934, in _check_buffer
    self.file.write(text)
OSError: [Errno 5] Input/output error
```
To try to resolved this, I granted permission 777 to the airflow directory. This was unsuccessful. 

The project is located in the home folder of 'ec2-user'. 

I was unsuccessful at booting at startup with Systemd. 

### What you think should happen instead

I would like to have the program running after I exit my shell session.

### How to reproduce

start webserver.
check site in webrowser
```
ctl+z
bg
disown
exit
```
check web browser again

### Operating System

Amazon Linux 2

### Versions of Apache Airflow Providers

apache-airflow-providers-ftp==2.0.1
apache-airflow-providers-http==2.0.1
apache-airflow-providers-imap==2.0.1
apache-airflow-providers-sqlite==2.0.1

### Deployment

Other

### Deployment details

I was originally doing it in SQL Lite. I tried switching to PostgreSQL, failed, and switched back.

### Anything else

This happens every time I exit.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
This is NOT how you should run webserver. This is completely and utterly wrong way of starting a long running program. you should never, ever do that this way witth any other software, and if you do it now you shoudl immediately stop.

You have the `-D` flag to run webserver as daemon for that purpose.

**Comment by potiuk** [comment]
Read this to understand how terribly wrong approach of yours was and what you had been missing if you did it the way you did it. http://www.netzmafia.de/skripten/unix/linux-daemon-howto.html
