### ISSUE TITLE
Getting error- "'NoneType' object has no attribute 'refresh_from_task' " while clicking on Rendered template for mapped task

### ISSUE THREAD

**Issue by jyotsa09** [apache/airflow#25662]
### Apache Airflow version

main (development)

### What happened

Getting error- 
```
Traceback (most recent call last):
  File "/Users/jyotsananamdev/10-aug/env/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/jyotsananamdev/10-aug/env/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/jyotsananamdev/10-aug/env/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jyotsananamdev/10-aug/env/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/jyotsananamdev/main_airflow/airflow/airflow/www/auth.py", line 46, in decorated
    return func(*args, **kwargs)
  File "/Users/jyotsananamdev/main_airflow/airflow/airflow/www/decorators.py", line 80, in wrapper
    return f(*args, **kwargs)
  File "/Users/jyotsananamdev/main_airflow/airflow/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/jyotsananamdev/main_airflow/airflow/airflow/www/views.py", line 1402, in rendered_templates
    ti.refresh_from_task(raw_task)
AttributeError: 'NoneType' object has no attribute 'refresh_from_task'
```

### What you think should happen instead

It should open rendered template page

### How to reproduce

open rendered template for mapped task.
 url - http://localhost:8080/rendered-templates?dag_id=dynamic_map2&dag_id=dynamic_map2&task_id=output&execution_date=2022-08-10T13%3A32%3A39.070211%2B00%3A00&map_index=-1

### Operating System

mac os

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by uranusjr** [comment]
This looks like the same issue as #25616

**Comment by bbovenzi** [comment]
This is fixed in https://github.com/apache/airflow/pull/25610
