### ISSUE TITLE
'ExasolHook' object has no attribute 'strip_sql_string'

### ISSUE THREAD

**Issue by thenaturalist** [apache/airflow#25740]
### Apache Airflow version

Other Airflow 2 version

### What happened

Calling the ExasolOperator/Hook in the latest 4.0.0 version results in the above error for any query. 

Example task trace:

```
[2022-08-16, 10:26:35 UTC] {{exasol.py:64}} INFO - Executing: SELECT * FROM FOO
[2022-08-16, 10:26:35 UTC] {{taskinstance.py:1703}} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/usr/local/airflow/.local/lib/python3.7/site-packages/airflow/providers/exasol/operators/exasol.py", line 66, in execute
    hook.run(self.sql, autocommit=self.autocommit, parameters=self.parameters)
  File "/usr/local/airflow/.local/lib/python3.7/site-packages/airflow/providers/exasol/hooks/exasol.py", line 165, in run
    sql = [self.strip_sql_string(sql)]
AttributeError: 'ExasolHook' object has no attribute 'strip_sql_string'
```

### What you think should happen instead

The SQL is executed correctly, no errors in the DB API Hook. 

### How to reproduce

Run a query with an instance of the DBAPIHook class against a data store

### Operating System

Linux

### Versions of Apache Airflow Providers

4.0.0

### Deployment

MWAA

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by thenaturalist** [comment]
@potiuk I can confirm that your suggestion for installing 1.1.0rc4 solved the issue. I can use Hook & Operator in the latest 4.0.0 version!

Thanks a lot for the quick response! :) 
Closing
