### ISSUE TITLE
XComs from another task group fail to populate dynamic task mapping metadata

### ISSUE THREAD

**Issue by ejmockler** [apache/airflow#25775]
### Apache Airflow version

2.3.3

### What happened

When a task returns a mappable Xcom within a task group, the dynamic task mapping feature (via `.expand`) causes the Airflow Scheduler to infinitely loop with a runtime error:

```
Traceback (most recent call last):

  File "/home/airflow/.local/bin/airflow", line 8, in <module>

    sys.exit(main())

  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/__main__.py", line 38, in main

    args.func(args)

  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 51, in command

    return func(*args, **kwargs)

  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 99, in wrapper

    return f(*args, **kwargs)

  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/scheduler_command.py", line 75, in scheduler

    _run_scheduler_job(args=args)

  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/scheduler_command.py", line 46, in _run_scheduler_job

    job.run()

  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/jobs/base_job.py", line 244, in run

    self._execute()

  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/jobs/scheduler_job.py", line 751, in _execute

    self._run_scheduler_loop()

  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/jobs/scheduler_job.py", line 839, in _run_scheduler_loop

    num_queued_tis = self._do_scheduling(session)

  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/jobs/scheduler_job.py", line 921, in _do_scheduling

    callback_to_run = self._schedule_dag_run(dag_run, session)

  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/jobs/scheduler_job.py", line 1163, in _schedule_dag_run

    schedulable_tis, callback_to_run = dag_run.update_state(session=session, execute_callbacks=False)

  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 68, in wrapper

    return func(*args, **kwargs)

  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagrun.py", line 524, in update_state

    info = self.task_instance_scheduling_decisions(session)

  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 68, in wrapper

    return func(*args, **kwargs)

  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagrun.py", line 654, in task_instance_scheduling_decisions

    schedulable_tis, changed_tis, expansion_happened = self._get_ready_tis(

  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagrun.py", line 710, in _get_ready_tis

    expanded_tis, _ = schedulable.task.expand_mapped_task(self.run_id, session=session)

  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/mappedoperator.py", line 614, in expand_mapped_task

    operator.mul, self._resolve_map_lengths(run_id, session=session).values()

  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/mappedoperator.py", line 600, in _resolve_map_lengths

    raise RuntimeError(f"Failed to populate all mapping metadata; missing: {keys}")

RuntimeError: Failed to populate all mapping metadata; missing: 'x'
```

### What you think should happen instead

Xcoms from different task groups should be mappable within other group scopes.

### How to reproduce

```
from airflow import DAG
from airflow.decorators import task
from airflow.utils.task_group import TaskGroup

import pendulum

@task
def enumerate(x):
    return [i for i in range(x)]

@task 
def addOne(x):
    return x+1

with DAG(
    dag_id="TaskGroupMappingBug",
    schedule_interval=None,
    start_date=pendulum.now().subtract(days=1),
) as dag:
    
    with TaskGroup(group_id="enumerateNine"):
        y = enumerate(9)
        
    with TaskGroup(group_id="add"):
        # airflow scheduler throws error here so this is never reached
        z = addOne.expand(x=y)
    

```

### Operating System

linux/amd64 via Docker (apache/airflow:2.3.3-python3.9)

### Deployment

Docker-Compose

### Deployment details

docker-compose version 1.29.2, build 5becea4c

Docker Engine v20.10.14

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by uranusjr** [comment]
Ah, this is caused by a bug in `iter_mapped_dependants`. This function does not correctly prefix group IDs when looking up tasks.
