### ISSUE TITLE
dynamic dataset ref breaks when viewed in UI or when triggered (dagbag.py:_add_dag_from_db)

### ISSUE THREAD

**Issue by MatrixManAtYrService** [apache/airflow#26360]
### Apache Airflow version

2.4.0b1

### What happened

Here's a file which defines three dags.  "source" uses `Operator.partial` to reference either "sink".  I'm not sure if it's supported to do so, but airlflow should at least fail more gracefully than it does.

```python3
from datetime import datetime, timedelta
from time import sleep

from airflow import Dataset
from airflow.decorators import dag
from airflow.operators.dummy import DummyOperator
from airflow.operators.python import PythonOperator

ps = Dataset("partial_static")
p1 = Dataset("partial_dynamic_1")
p2 = Dataset("partial_dynamic_2")
p3 = Dataset("partial_dynamic_3")

def sleep_n(n):
    sleep(n)

@dag(start_date=datetime(1970, 1, 1), schedule=timedelta(days=365 * 30))
def two_kinds_dynamic_source():

    # dataset ref is not dynamic
    PythonOperator.partial(
        task_id="partial_static", python_callable=sleep_n, outlets=[ps]
    ).expand(op_args=[[1], [20], [40]])

    # dataset ref is dynamic
    PythonOperator.partial(
        task_id="partial_dynamic", python_callable=sleep_n
    ).expand_kwargs(
        [
            {"op_args": [1], "outlets": [p1]},
            {"op_args": [20], "outlets": [p2]},
            {"op_args": [40], "outlets": [p3]},
        ]
    )

two_kinds_dynamic_source()


@dag(schedule=[ps], start_date=datetime(1970, 1, 1))
def two_kinds_static_sink():
    DummyOperator(task_id="dummy")

two_kinds_static_sink()


@dag(schedule=[p1, p2, p3], start_date=datetime(1970, 1, 1))
def two_kinds_dynamic_sink():
    DummyOperator(task_id="dummy")

two_kinds_dynamic_sink()

```

Tried to trigger the dag in the browser, saw this traceback instead:

```
Python version: 3.9.13
Airflow version: 2.4.0.dev1640+astro.1
Node: airflow-webserver-6b969cbd87-4q5kh
-------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.9/site-packages/airflow/www/auth.py", line 46, in decorated
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/www/decorators.py", line 117, in view_func
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/www/decorators.py", line 80, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/utils/session.py", line 73, in wrapper
    return func(*args, session=session, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/www/views.py", line 2532, in grid
    dag = get_airflow_app().dag_bag.get_dag(dag_id, session=session)
  File "/usr/local/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 176, in get_dag
    self._add_dag_from_db(dag_id=dag_id, session=session)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 251, in _add_dag_from_db
    dag = row.dag
  File "/usr/local/lib/python3.9/site-packages/airflow/models/serialized_dag.py", line 223, in dag
    dag = SerializedDAG.from_dict(self.data)  # type: Any
  File "/usr/local/lib/python3.9/site-packages/airflow/serialization/serialized_objects.py", line 1220, in from_dict
    return cls.deserialize_dag(serialized_obj['dag'])
  File "/usr/local/lib/python3.9/site-packages/airflow/serialization/serialized_objects.py", line 1197, in deserialize_dag
    setattr(task, k, kwargs_ref.deref(dag))
  File "/usr/local/lib/python3.9/site-packages/airflow/serialization/serialized_objects.py", line 224, in deref
    value = {k: v.deref(dag) if isinstance(v, _XComRef) else v for k, v in self.value.items()}
AttributeError: 'list' object has no attribute 'items'
```

I can also summon a similar traceback by just trying to view the dag in the grid view, or when running `airflow dags trigger`

### What you think should happen instead

If there's something invalid about this dag, it should fail to parse--rather than successfully parsing and then breaking the UI.

I'm a bit uncertain about what should happen in the dag dependency graph when the source dag runs.  The dynamic outlets are not known until runtime, so it's reasonable that they don't show up in the graph.  But what about after the dag runs?
- do they still trigger the "sink" dag even though we didn't know about the dependency up front?
- do we update the dependency graph now that we know about the dynamic dependency?

Because of this error, we don't get far enough to find out.

### How to reproduce

Include the dag above, try to display it in the grid view.

### Operating System

kubernetes-in-docker on MacOS via helm

### Versions of Apache Airflow Providers

n/a

### Deployment

Other 3rd-party Helm chart

### Deployment details

Deployed using [the astronomer helm chart ](https://github.com/astronomer/airflow-chart)and these values:
```yaml
airflow:
  airflowHome: /usr/local/airflow
  airflowVersion: $VERSION
  defaultAirflowRepository: img
  defaultAirflowTag: $TAG
  executor: KubernetesExecutor
  gid: 50000
  images:
    airflow:
      repository: img
  logs:
    persistence:
      enabled: true
      size: 2Gi
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by MatrixManAtYrService** [comment]
https://github.com/apache/airflow/pull/26369 fixes the problem that was preventing me from even running the DAG.   Now I'm getting task failures:

```
{taskinstance.py:1168} INFO - Dependencies all met for <TaskInstance: two_kinds_dynamic_source.partial_dynamic scheduled__1970-01-01T00:00:00+00:00 map_index=0 [queued]>
{taskinstance.py:1168} INFO - Dependencies all met for <TaskInstance: two_kinds_dynamic_source.partial_dynamic scheduled__1970-01-01T00:00:00+00:00 map_index=0 [queued]>
{taskinstance.py:1367} INFO -
-------------------------------------------------
{taskinstance.py:1368} INFO - Starting attempt 1 of 1
{taskinstance.py:1369} INFO -
-------------------------------------------------
{taskinstance.py:1388} INFO - Executing <Mapped(PythonOperator): partial_dynamic> on 1970-01-01 00:00:00+00:00
{standard_task_runner.py:53} INFO - Started process 24193 to run task
{standard_task_runner.py:81} INFO - Running: ['airflow', 'tasks', 'run', 'two_kinds_dynamic_source', 'partial_dynamic', 'scheduled__1970-01-01T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/dynamic_dataset.py', '--cfg-path', '/var/folders/5m/nvs9yfcs6mlfm_63gnk6__3r0000gn/T/tmpmaqqw3sp', '--map-index', '0']
{standard_task_runner.py:82} INFO - Job 9: Subtask partial_dynamic
{dagbag.py:522} INFO - Filling up the DagBag from /Users/matt/2022/09/13/dags/dynamic_dataset.py
{task_command.py:382} INFO - Running <TaskInstance: two_kinds_dynamic_source.partial_dynamic scheduled__1970-01-01T00:00:00+00:00 map_index=0 [running]> on host LIGO.local
{taskinstance.py:1856} ERROR - Task failed with exception
Traceback (most recent call last):
  File "...site-packages/airflow/models/taskinstance.py", line 1462, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "...site-packages/airflow/models/taskinstance.py", line 1581, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "...site-packages/airflow/models/taskinstance.py", line 2198, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "...site-packages/airflow/models/mappedoperator.py", line 779, in render_template_fields
    unmapped_task = self.unmap(mapped_kwargs)
  File "...site-packages/airflow/models/mappedoperator.py", line 602, in unmap
    kwargs = self._get_unmap_kwargs(kwargs, strict=self._disallow_kwargs_override)
  File "...site-packages/airflow/models/mappedoperator.py", line 563, in _get_unmap_kwargs
    prevent_duplicates(
  File "...site-packages/airflow/models/mappedoperator.py", line 133, in prevent_duplicates
    raise TypeError(f"{fail_reason} argument: {duplicated_keys.pop()}")
TypeError: unmappable or already specified argument: outlets
{taskinstance.py:1898} ERROR - Unable to unmap task to determine if we need to send an alert email
{taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=two_kinds_dynamic_source, task_id=partial_dynamic, map_index=0, execution_date=19700101T000000, start_date=20220913T183429, end_date=20220913T183429
{standard_task_runner.py:101} ERROR - Failed to execute job 9 for task partial_dynamic (unmappable or already specified argument: outlets; 24193)
{local_task_job.py:163} INFO - Task exited with return code 1
```

If specifying outlets in this way is not supported, then `TypeError: unmappable or already specified argument: outlets` is a reasonable way to fail.  So I guess the question now is: Is this a bug or a feature?
