### ISSUE TITLE
Unable to run dags via CeleryExecutor

### ISSUE THREAD

**Issue by martingrayson** [apache/airflow#282]
I've just setup the CeleryExecutor (with Redis). I'm able to run single task instances via the front end but have trouble running a full backfill via command line.

If I issue the following command:
`airflow backfill -s 2015-08-20 -e 2015-08-20 example_python_operator`

I can see this gets dispatched fine and I can trace it in Celery Flower - the following command is being issued:
`airflow run example_python_operator print_the_context 2015-08-20T00:00:00 --pickle 10 --local -s 2015-08-20T00:00:00`

This seems to be hitting an import error:
`ImportError: No module named unusual_prefix_example_python_operator`

Have I misconfigured something? It seems as if airflow is failing to load the pickle?

**Comment by mistercrunch** [comment]
The way I would troubleshoot this is by ssh-ing into the worker while making sure to recreate the environmental conditions of the worker (same machine, user, env vars, ...), and run the command in the message, you'll get a local log and some stdout detailing the failure.

There also may be shortcomings around the examples and CeleryExecutor as examples are loaded into the "DagBag" in a different way. I'll try do dig in if you find out that is the case.

**Comment by martingrayson** [comment]
I'm actually running everything on the same machine. Executing the command in the message gives the same error as if it were run via celery.

I'm not sure its something special to do with the examples either, as my own dags hit the same error. I'll grab a full stack trace to help the problem.

**Comment by martingrayson** [comment]
I ran this command:
`airflow backfill -s 2015-08-20 -e 2015-08-20 example_python_operator`

Heres the stack-trace from my worker:

```
Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 10, in <module>
    args.func(args)
  File "/usr/local/lib/python2.7/dist-packages/airflow/bin/cli.py", line 100, in run
    DagPickle).filter(DagPickle.id == args.pickle).first()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2445, in first
    ret = list(self[0:1])
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2281, in __getitem__
    return list(res)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/loading.py", line 86, in instances
    util.raise_from_cause(err)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/loading.py", line 71, in instances
    rows = [proc(row) for row in fetch]
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/loading.py", line 428, in _instance
    loaded_instance, populate_existing, populators)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/loading.py", line 486, in _populate_full
    dict_[key] = getter(row)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/sqltypes.py", line 1261, in process
    return loads(value)
  File "/usr/local/lib/python2.7/dist-packages/dill/dill.py", line 209, in loads
    return load(file)
  File "/usr/local/lib/python2.7/dist-packages/dill/dill.py", line 199, in load
    obj = pik.load()
  File "/usr/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 1090, in load_global
    klass = self.find_class(module, name)
  File "/usr/local/lib/python2.7/dist-packages/dill/dill.py", line 353, in find_class
    return StockUnpickler.find_class(self, module, name)
  File "/usr/lib/python2.7/pickle.py", line 1124, in find_class
    __import__(module)
ImportError: No module named unusual_prefix_example_python_operator
[2015-08-21 15:45:47,522: ERROR/Worker-7] 1
[2015-08-21 15:45:47,529: ERROR/MainProcess] Task airflow.executors.celery_executor.execute_command[b238bc67-217e-48ab-8246-c5459a84c981] raised unexpected: AirflowException('Celery command failed',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/airflow/executors/celery_executor.py", line 43, in execute_command
    raise AirflowException('Celery command failed')
AirflowException: Celery command failed
```

This is a result of a vanilla mysql backend with the celery executor using redis. The worker, webserver and celery flower are all running on the same machine.

Whats the deal with the `unusual_prefix_` string that gets prepended ?

**Comment by martingrayson** [comment]
Is there anything special I need to do to get celery working? I was under the impression it should work out of the box.. I'm running a fresh install here.

Is it possible to have some more documentation around this? The documentation helps with getting started, but doesnt really hint at what a production configuration should look like.

**Comment by martingrayson** [comment]
This seems to be the same issue as #208

**Comment by mistercrunch** [comment]
Long shot here, are you running the airflow worker as root?

**Comment by martingrayson** [comment]
Nope, I'm using a fresh Ubuntu box with all the airflow daemons (web, scheduler and worker) running as ubuntu.

**Comment by mistercrunch** [comment]
Still an issue?

**Comment by martingrayson** [comment]
Sorry for the delay. Yep its still an issue, however I have a workaround as I noticed in #479 there is a boolean value to disable pickling. This seems to work for me in the short term.

**Comment by bolkedebruin** [comment]
@martingrayson Please create a Jira issue if this issue still persists for you. Closing now.
