### ISSUE TITLE
Fail read remote logs from Azure Blog Storage

### ISSUE THREAD

**Issue by aresabalo** [apache/airflow#28366]
### Apache Airflow version

2.5.0

### What happened

[2022-12-14 21:18:55,708] {wasb_task_handler.py:162} ERROR - Could not read logs from wasb-airflow-logs/dag_id=airflow-log-cleanup/run_id=scheduled__2022-12-13T00:00:00+00:00/task_id=log_cleanup_worker_num_1_dir_0/attempt=1.log
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/microsoft/azure/log/wasb_task_handler.py", line 159, in wasb_read
    return self.hook.read_file(self.wasb_container, remote_log_location)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 356, in read_file
    return self.download(container_name, blob_name, **kwargs).content_as_text()
TypeError: download() missing 2 required positional arguments: 'offset' and 'length'

### What you think should happen instead

Missing arguments in function call (download)

I resolved it patching file /home/airflow/.local/lib/python3.9/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py

**line 388 orig**
self, container_name, blob_name, offset: int, length: int, **kwargs

**line 388 patched**
self, container_name, blob_name, offset: int | None = None, length: int | None = None, **kwargs

### How to reproduce

Upgrading version from 2.4.3 to 2.5.0 and remote logs on Azure Blog Storage service 

### Operating System

AKS (Kubernetes)

### Deployment

Other Docker-based deployment

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
Please check RC version:
https://github.com/apache/airflow/issues/28349
It will be released in a few days in the meantime you can verify it resolves the issue
