### ISSUE TITLE
Airflow UI not showing mapped tasks

### ISSUE THREAD

**Issue by anneadb** [apache/airflow#29102]
### Apache Airflow version

2.5.1

### What happened

I am using dynamic task mapping to process a list of files in the same way.
The tasks are generated but I cannot see them listed in the UI tab "Mapped Tasks".
When I go to the graph view I can look at the logs for the last run with all mapped instances.

<img width="1147" alt="Screenshot 2023-01-23 at 13 07 59" src="https://user-images.githubusercontent.com/46241952/214037237-82381300-11c1-43ce-a4b9-b8f16294a74c.png">

<img width="975" alt="Screenshot 2023-01-23 at 13 08 07" src="https://user-images.githubusercontent.com/46241952/214037258-026d4074-40c5-40a1-96de-74c2bd11173f.png">

### What you think should happen instead

On the tab "Mapped Tasks" I expect to see a list of the generated tasks with links to their logs.

### How to reproduce

* Use a docker-compose with apache/airflow:2.5.1-python3.8 as the base image.
* Expand a python operator based on a list of file names from another task

Dag code:

```
def prep_args(file_name):
    return {"file_name": file_name}

with DAG(
    "imparted_orders_lascana",
    default_args=default_args,
    schedule="19 */3 * * *",
) as dag:

    t0 = PythonOperator(
        task_id="get_file_list",
        python_callable=get_file_list,
    )

    t1 = PythonOperator.partial(
        task_id="transfer_data",
        python_callable=transfer_data,
    ).expand(op_kwargs=t0.output.map(prep_args))

```

### Operating System

CentOS 7.9

### Deployment

Docker-Compose

### Deployment details

We're creating our own docker image based on the provided image to add a few additional packages.

The Dockerfile looks like this:

```
FROM apache/airflow:2.5.1-python3.8 AS base

USER root

# install git
RUN apt update \
    && apt install -y --no-install-recommends git \
    && apt autoremove -yqq --purge \
    && apt clean \
    && rm -rf /var/lib/apt/lists/*

# install gcloud
RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg  add - && apt-get update -y && apt-get install google-cloud-cli -y
USER airflow

# install additional requirements
RUN pip install pipenv
COPY Pipfile .
COPY Pipfile.lock .
RUN pipenv install --system --deploy

# customize standard configurations
COPY webserver_config.py ${AIRFLOW_HOME}/webserver_config.py
COPY airflow.cfg ${AIRFLOW_HOME}/airflow.cfg
```

The webserver config looks like this:

```
from __future__ import annotations

import os

from airflow.www.fab_security.manager import AUTH_DB

basedir = os.path.abspath(os.path.dirname(__file__))

# Flask-WTF flag for CSRF
WTF_CSRF_ENABLED = True

# The authentication type
# AUTH_DB : Is for database
AUTH_TYPE = AUTH_DB

# Uncomment and set to desired role to enable access without authentication
AUTH_ROLE_PUBLIC = "Admin"
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
CC: @bbovenzi @pierrejeambrun @ephraimbuddy - if that one is confirmed, we might have a need for 2.5.2 rather quickly

**Comment by josh-fell** [comment]
FWIW I cannot reproduce this with Breeze `breeze start-airflow --use-airflow-version 2.5.1 --python 3.8`.

A little bit of a toy example since we don't know what's going on with the `get_file_list()` and `transform_data()` functions:
```python
from pendulum import datetime

from airflow import DAG
from airflow.operators.python import PythonOperator


def get_file_list():
    return ["file1", "file2", "file3"]


def prep_args(file_name):
    return {"file_name": file_name}


def transfer_data(file_name):
    print(file_name)


with DAG(
    "imparted_orders_lascana",
    start_date=datetime(2023, 1, 1),
    schedule=None
) as dag:

    t0 = PythonOperator(
        task_id="get_file_list",
        python_callable=get_file_list,
    )

    t1 = PythonOperator.partial(
        task_id="transfer_data",
        python_callable=transfer_data,
    ).expand(op_kwargs=t0.output.map(prep_args))
```
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/48934154/214106200-b0e9ba04-980b-4013-8d62-60cd0cbc2a8e.png">

**Comment by bbovenzi** [comment]
@anneadb Are there any console or network errors if you open up inspect element? We have a separate API request to populate the mapped instances list. Depending on network/console, we could figure out if its an API or UI issue.

**Comment by anneadb** [comment]
Thanks for looking into this!
When I open Inspect and then switch between the tabs (details and mapped tasks) the following appears:

```
/api/v1/dags/imparted_orders_lascana/dagRuns/scheduled__2023-01-24T09:19:00+00:00/taskInstances/transfer_data/listMapped?offset=0&limit=25:1          
Failed to load resource: the server responded with a status of 401 ()
/api/v1/dags/imparted_orders_lascana/dagRuns/scheduled__2023-01-24T09:19:00+00:00/taskInstances/transfer_data/listMapped?offset=0&limit=25:1          
Failed to load resource: the server responded with a status of 401 ()
grid.eb016d432dd8f7bf3ec6.js:2 Error: Request failed with status code 401
    at e.exports (grid.eb016d432dd8f7bf3ec6.js:2:6429)
    at e.exports (grid.eb016d432dd8f7bf3ec6.js:2:8845)
    at XMLHttpRequest.A (grid.eb016d432dd8f7bf3ec6.js:2:1079)
onError @ grid.eb016d432dd8f7bf3ec6.js:2
DevTools failed to load source map: Could not load content for https://bi-airflow.s24.com/static/appbuilder/css/bootstrap.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
grid.eb016d432dd8f7bf3ec6.js:2         
GET https://bi-airflow.s24.com/api/v1/dags/imparted_orders_lascana/dagRuns/scheduled__2023-01-24T09:19:00+00:00/taskInstances/transfer_data/listMapped?offset=0&limit=25 401
(anonymous) @ grid.eb016d432dd8f7bf3ec6.js:2
e.exports @ grid.eb016d432dd8f7bf3ec6.js:2
e.exports @ grid.eb016d432dd8f7bf3ec6.js:2
l.request @ grid.eb016d432dd8f7bf3ec6.js:2
r.forEach.l.<computed> @ grid.eb016d432dd8f7bf3ec6.js:2
(anonymous) @ grid.eb016d432dd8f7bf3ec6.js:2
S_.keepPreviousData @ grid.eb016d432dd8f7bf3ec6.js:2
fetchFn @ grid.eb016d432dd8f7bf3ec6.js:2
s @ grid.eb016d432dd8f7bf3ec6.js:2
l @ grid.eb016d432dd8f7bf3ec6.js:2
n.fetch @ grid.eb016d432dd8f7bf3ec6.js:2
t.executeFetch @ grid.eb016d432dd8f7bf3ec6.js:2
t.onSubscribe @ grid.eb016d432dd8f7bf3ec6.js:2
n.subscribe @ grid.eb016d432dd8f7bf3ec6.js:2
(anonymous) @ grid.eb016d432dd8f7bf3ec6.js:2
eu @ grid.eb016d432dd8f7bf3ec6.js:2
Ms @ grid.eb016d432dd8f7bf3ec6.js:2
(anonymous) @ grid.eb016d432dd8f7bf3ec6.js:2
ys @ grid.eb016d432dd8f7bf3ec6.js:2
cs @ grid.eb016d432dd8f7bf3ec6.js:2
Fi @ grid.eb016d432dd8f7bf3ec6.js:2
(anonymous) @ grid.eb016d432dd8f7bf3ec6.js:2
grid.eb016d432dd8f7bf3ec6.js:2          
GET https://bi-airflow.s24.com/api/v1/dags/imparted_orders_lascana/dagRuns/scheduled__2023-01-24T09:19:00+00:00/taskInstances/transfer_data/listMapped?offset=0&limit=25 401
(anonymous) @ grid.eb016d432dd8f7bf3ec6.js:2
e.exports @ grid.eb016d432dd8f7bf3ec6.js:2
e.exports @ grid.eb016d432dd8f7bf3ec6.js:2
l.request @ grid.eb016d432dd8f7bf3ec6.js:2
r.forEach.l.<computed> @ grid.eb016d432dd8f7bf3ec6.js:2
(anonymous) @ grid.eb016d432dd8f7bf3ec6.js:2
S_.keepPreviousData @ grid.eb016d432dd8f7bf3ec6.js:2
fetchFn @ grid.eb016d432dd8f7bf3ec6.js:2
s @ grid.eb016d432dd8f7bf3ec6.js:2
(anonymous) @ grid.eb016d432dd8f7bf3ec6.js:2
Promise.then (async)
(anonymous) @ grid.eb016d432dd8f7bf3ec6.js:2
Promise.catch (async)
s @ grid.eb016d432dd8f7bf3ec6.js:2
l @ grid.eb016d432dd8f7bf3ec6.js:2
n.fetch @ grid.eb016d432dd8f7bf3ec6.js:2
t.executeFetch @ grid.eb016d432dd8f7bf3ec6.js:2
t.onSubscribe @ grid.eb016d432dd8f7bf3ec6.js:2
n.subscribe @ grid.eb016d432dd8f7bf3ec6.js:2
(anonymous) @ grid.eb016d432dd8f7bf3ec6.js:2
eu @ grid.eb016d432dd8f7bf3ec6.js:2
Ms @ grid.eb016d432dd8f7bf3ec6.js:2
(anonymous) @ grid.eb016d432dd8f7bf3ec6.js:2
ys @ grid.eb016d432dd8f7bf3ec6.js:2
cs @ grid.eb016d432dd8f7bf3ec6.js:2
Fi @ grid.eb016d432dd8f7bf3ec6.js:2
(anonymous) @ grid.eb016d432dd8f7bf3ec6.js:2
grid.eb016d432dd8f7bf3ec6.js:2 Error: Request failed with status code 401
    at e.exports (grid.eb016d432dd8f7bf3ec6.js:2:6429)
    at e.exports (grid.eb016d432dd8f7bf3ec6.js:2:8845)
    at XMLHttpRequest.A (grid.eb016d432dd8f7bf3ec6.js:2:1079)
onError @ grid.eb016d432dd8f7bf3ec6.js:2
b @ grid.eb016d432dd8f7bf3ec6.js:2
(anonymous) @ grid.eb016d432dd8f7bf3ec6.js:2
Promise.catch (async)
s @ grid.eb016d432dd8f7bf3ec6.js:2
(anonymous) @ grid.eb016d432dd8f7bf3ec6.js:2
Promise.then (async)
(anonymous) @ grid.eb016d432dd8f7bf3ec6.js:2
Promise.catch (async)
s @ grid.eb016d432dd8f7bf3ec6.js:2
l @ grid.eb016d432dd8f7bf3ec6.js:2
n.fetch @ grid.eb016d432dd8f7bf3ec6.js:2
t.executeFetch @ grid.eb016d432dd8f7bf3ec6.js:2
t.onSubscribe @ grid.eb016d432dd8f7bf3ec6.js:2
n.subscribe @ grid.eb016d432dd8f7bf3ec6.js:2
(anonymous) @ grid.eb016d432dd8f7bf3ec6.js:2
eu @ grid.eb016d432dd8f7bf3ec6.js:2
Ms @ grid.eb016d432dd8f7bf3ec6.js:2
(anonymous) @ grid.eb016d432dd8f7bf3ec6.js:2
ys @ grid.eb016d432dd8f7bf3ec6.js:2
cs @ grid.eb016d432dd8f7bf3ec6.js:2
Fi @ grid.eb016d432dd8f7bf3ec6.js:2
(anonymous) @ grid.eb016d432dd8f7bf3ec6.js:2
``` 

At the same time it also asks me to log in again repeatedly. Our ops team put an nginx with LDAP authentication in front of our Airflow - if this could be the source of the error I'd have to ask them about the exact implementation.

**Comment by bbovenzi** [comment]
Yeah, sounds like there is an auth issue with accessing the rest API. I'd imagine a few other parts of the grid view and datasets pages are also failing then?

**Comment by anneadb** [comment]
Thanks for the insights. I'll ask for help from our ops team.
