### ISSUE TITLE
Airflow v2.4.2 - Scheduler fails with BrokenPIPE error (Exiting gracefully upon receiving signal 15)

### ISSUE THREAD

**Issue by tanuj241088** [apache/airflow#29131]
### Apache Airflow version

Airflow v2.4.2

### What happened

I have recently upgraded to Airflow v2.4.2 with python v3.9.15
Previous Airflow v2.1 with python v3.8 (this was working perfectly fine) and there is no change in environment.
After the upgrade,  Airflow scheduler keeps restarting every 5-10 min. 

Dockerfile:
```dockerfile
FROM ******/library/airflow:2.4.2-python3.9
```
Base container image from dockerhub:
https://hub.docker.com/layers/apache/airflow/2.4.2-python3.9/images/sha256-ee8194858c12cceded59bfdc36ccf7c9fcdfa684a17f168c7f23599ebc53864f?context=explore

**Complete logs:**

```console

[2023-01-24 05:21:21,375] {scheduler_job.py:173} INFO - Exiting gracefully upon receiving signal 15
--
[2023-01-24 05:21:22,382] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 494. PIDs of all processes in the group: [494]
[2023-01-24 05:21:22,382] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 494
[2023-01-24 05:21:22,716] {process_utils.py:79} INFO - Process psutil.Process(pid=494, status='terminated', exitcode=0, started='05:16:37') (494) terminated with exit code 0
[2023-01-24 05:21:22,717] {local_executor.py:390} INFO - Shutting down LocalExecutor; waiting for running tasks to finish. Signal again if you don't want to wait.
[2023-01-24 05:21:22,717] {scheduler_job.py:769} ERROR - Exception when executing Executor.end
Traceback (most recent call last):
File "/home/airflow/.local/lib/python3.9/site-packages/airflow/jobs/scheduler_job.py", line 746, in _execute
self._run_scheduler_loop()
File "/home/airflow/.local/lib/python3.9/site-packages/airflow/jobs/scheduler_job.py", line 887, in _run_scheduler_loop
time.sleep(min(self._scheduler_idle_sleep_time, next_event if next_event else 0))
File "/home/airflow/.local/lib/python3.9/site-packages/airflow/jobs/scheduler_job.py", line 176, in _exit_gracefully
sys.exit(os.EX_OK)
SystemExit: 0
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
File "/home/airflow/.local/lib/python3.9/site-packages/airflow/jobs/scheduler_job.py", line 767, in _execute
self.executor.end()
File "/home/airflow/.local/lib/python3.9/site-packages/airflow/executors/local_kubernetes_executor.py", line 180, in end
self.local_executor.end()
File "/home/airflow/.local/lib/python3.9/site-packages/airflow/executors/local_executor.py", line 394, in end
self.impl.end()
File "/home/airflow/.local/lib/python3.9/site-packages/airflow/executors/local_executor.py", line 336, in end
self.queue.put((None, None))
File "<string>", line 2, in put
File "/usr/local/lib/python3.9/multiprocessing/managers.py", line 809, in _callmethod
conn.send((self._id, methodname, args, kwds))
File "/usr/local/lib/python3.9/multiprocessing/connection.py", line 211, in send
self._send_bytes(_ForkingPickler.dumps(obj))
File "/usr/local/lib/python3.9/multiprocessing/connection.py", line 416, in _send_bytes
self._send(header + buf)
File "/usr/local/lib/python3.9/multiprocessing/connection.py", line 373, in _send
n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
[2023-01-24 05:21:22,726] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 494. PIDs of all processes in the group: []
[2023-01-24 05:21:22,726] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 494
[2023-01-24 05:21:22,727] {process_utils.py:98} INFO - Sending the signal Signals.SIGTERM to process 494 as process group is missing.
[2023-01-24 05:21:22,727] {scheduler_job.py:775} INFO - Exited execute loop

```

### How to reproduce
Upgraded Airflow from v 2.1.2 to 2.4.2
and python version from 3.8 to 3.9.15

Airflow configs changes:
Executor: LocalKubernetesExecutor

### Operating System

Ubuntu 18.04

### Versions of Apache Airflow Providers

apache-airflow-providers-amazon==6.0.0
apache-airflow-providers-celery==3.0.0
apache-airflow-providers-cncf-kubernetes==4.4.0
apache-airflow-providers-common-sql==1.2.0
apache-airflow-providers-docker==3.2.0
apache-airflow-providers-elasticsearch==4.2.1
apache-airflow-providers-ftp==3.1.0
apache-airflow-providers-google==8.4.0
apache-airflow-providers-grpc==3.0.0
apache-airflow-providers-hashicorp==3.1.0
apache-airflow-providers-http==4.0.0
apache-airflow-providers-imap==3.0.0
apache-airflow-providers-microsoft-azure==4.3.0
apache-airflow-providers-mongo==3.0.0
apache-airflow-providers-mysql==3.2.1
apache-airflow-providers-odbc==3.1.2
apache-airflow-providers-postgres==5.2.2
apache-airflow-providers-redis==3.0.0
apache-airflow-providers-sendgrid==3.0.0
apache-airflow-providers-sftp==4.1.0
apache-airflow-providers-slack==6.0.0
apache-airflow-providers-sqlite==3.2.1
apache-airflow-providers-ssh==3.2.0

### Deployment

Other Docker-based deployment

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by tanuj241088** [comment]
@Taragolis ... i was also investigating in the same direction. Here is the update:

i dont think this is related to Airflow version upgrade.
We do have liveliness probe that checks scheduler heartbeat every 5 min. and looks like liveliness probe is failing.

Then i found out that our kubernetest team has upgrade k8s version from 1.9 to 1.21 (today).

but still i wonder why liveliness probe will fail with new version of k8s (1.21)??

Here is my liveliness probe script:
        # If the scheduler stops heartbeating for 5 minutes (10*30s) kill the
        # scheduler and let Kubernetes restart it
        livenessProbe:
          failureThreshold: 10
          periodSeconds: 30
          exec:
            command:
            - python
            - -Wignore
            - -c
            - |
              import os
              os.environ['AIRFLOW__CORE__LOGGING_LEVEL'] = 'ERROR'
              os.environ['AIRFLOW__LOGGING__LOGGING_LEVEL'] = 'ERROR'
              from airflow.jobs.scheduler_job import SchedulerJob
              from airflow.utils.db import create_session
              from airflow.utils.net import get_hostname
              import sys
              #job = SchedulerJob.most_recent_job()
              #sys.exit(0 if job.is_alive() and job.hostname == get_hostname() else 1)
              
              ##Commenting out above lines as it is causing scheduler to send SIGTERM to longer running tasks
              with create_session() as session:
                  job = session.query(SchedulerJob).filter_by(hostname=get_hostname()).order_by(
                      SchedulerJob.latest_heartbeat.desc()).limit(1).first()
              sys.exit(0 if job.is_alive() else 1)

**Comment by Taragolis** [comment]
You could try to check by new [Scheduler Health Check Endpoint](https://airflow.apache.org/docs/apache-airflow/2.4.2/logging-monitoring/check-health.html#scheduler-health-check-server)
Even if it use almost the same query, you do not require for each health check import Airflow libraries.
