### ISSUE TITLE
`'NoneType' object has no attribute 'sign'` error on the webserver when deploying the helm chart for the first time

### ISSUE THREAD

**Issue by Startouf** [apache/airflow#29530]
### Official Helm Chart version

1.8.0 (latest released)

### Apache Airflow version

2.5.1

### Kubernetes Version

1.23.1 BuildDate:"2021-12-16T11:34:54Z"

### Helm Chart configuration

Here is my values file. I also deployed airflow in a "dev" namespace with reckoner and generated weberver secrets with
```
kubectl -n dev create secret generic airflow-webserver-secrets --from-literal="webserver-secret-key=$(python3 -c 'import secrets; print(secrets.token_hex(16))')"
```

```
# airflow-values.yaml
ingress:
  web:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod-http01
    hosts:
      - name: airflow.example.com
        tls:
          enabled: true
          secretName: airflow-tls-secret
  flower:
    enabled: false
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod-http01
    hosts:
      - name: airflow-flower.example.com
        tls:
          enabled: true
          secretName: airflow-flower-tls-secret
webserverSecretKeySecretName: airflow-webserver-secrets

# kubectl -n dev create secret generic airflow-webserver-secrets --from-literal="webserver-secret-key=$(python3 -c 'import secrets; print(secrets.token_hex(16))')"
```

### Docker Image customizations

None

### What happened

I deployed airflow to my kubernetes cluster on 3DS Outscale.
The first deployment crashed the nodes (probably ran OOM because), so I rebooted the nodes and after waiting a bit all airflow related services seem to be up
But when I connect to the web ingress, I have the "problem" screen, and when tailing the logs of the webserver I see this

```
    response = self.process_response(response)
  File "/home/airflow/.local/lib/python3.7/site-packages/flask/app.py", line 2340, in process_response
    self.session_interface.save_session(self, ctx.session, response)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/www/session.py", line 33, in save_session
    return super().save_session(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/flask_session/sessions.py", line 580, in save_session
    session_id = self._get_signer(app).sign(want_bytes(session.sid))
AttributeError: 'NoneType' object has no attribute 'sign'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/flask/app.py", line 1844, in finalize_request
    response = self.process_response(response)
  File "/home/airflow/.local/lib/python3.7/site-packages/flask/app.py", line 2340, in process_response
    self.session_interface.save_session(self, ctx.session, response)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/www/session.py", line 33, in save_session
    return super().save_session(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/flask_session/sessions.py", line 580, in save_session
    session_id = self._get_signer(app).sign(want_bytes(session.sid))
AttributeError: 'NoneType' object has no attribute 'sign'
```

Note that healthchecks are reported as successful

10.233.64.1 - - [14/Feb/2023:11:27:46 +0000] "GET /health HTTP/1.1" 200 141 "-" "kube-probe/1.23"

### What you think should happen instead

I should reach the login or first setup interface ?

### How to reproduce

Simply by installing the chart. Maybe when the node crashed on initial deploy, some migrations/one-time run scripts did not run successfully and caused irreversible problems ?

### Anything else

I edited some values and made a second release (to add the webserverSecretKeySecretName since I saw a warning in the INFOs) and successfully deployed a new version. The output of my info file is

```
Release "airflow" has been upgraded. Happy Helming!
NAME: airflow
LAST DEPLOYED: Tue Feb 14 11:59:29 2023
NAMESPACE: dev
STATUS: deployed
REVISION: 2
TEST SUITE: None
NOTES:
Thank you for installing Apache Airflow 2.5.1!

Your release is named airflow.
You can now access your service(s) by following defined Ingress urls:

DEPRECATION WARNING:
   `ingress.web.tls` has been renamed to `ingress.web.hosts[*].tls` and can be set per host.
   Please change your values as support for the old name will be dropped in a future release.

DEPRECATION WARNING:
   `ingress.flower.tls` has been renamed to `ingress.flower.hosts[*].tls` and can be set per host.
   Please change your values as support for the old name will be dropped in a future release.
Airflow Webserver:
      https://airflow.example.com//
Default Webserver (Airflow UI) Login credentials:
    username: admin
    password: admin
Default Postgres connection credentials:
    username: postgres
    password: postgres
    port: 5432

You can get Fernet Key value by running the following:

    echo Fernet Key: $(kubectl get secret --namespace dev airflow-fernet-key -o jsonpath="{.data.fernet-key}" | base64 --decode)

```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Startouf** [comment]
Additional logs from my kubernetes pods

Worker : it seems to have started successfully
triggerer : I see logs like this

```
[2023-02-14T11:42:55.556+0000] {triggerer_job.py:348} ERROR - Triggerer's async thread was blocked for 1.41 seconds, likely by a badly-written trigger. Set PYTHONASYNCIODEBUG=1 to get more information on overrunning coroutines.
```
statsd: OK
scheduler : last log lines are like this, not sur if it is OKay or not

```
[2023-02-14T11:34:31.109+0000] {settings.py:548} INFO - Loaded airflow_local_settings from /opt/airflow/config/airflow_local_settings.py .
[2023-02-14T11:34:31.156+0000] {scheduler_job.py:1431} INFO - Marked 1 SchedulerJob instances as failed
[2023-02-14T11:39:31.232+0000] {scheduler_job.py:1408} INFO - Resetting orphaned tasks for active dag runs
[2023-02-14T11:44:31.283+0000] {scheduler_job.py:1408} INFO - Resetting orphaned tasks for active dag runs
```
redis OK
PostgreSQL : Not sure but I see problems that could be related to my initial startup failure

```
postgresql 10:47:27.73 INFO  ==> ** Starting PostgreSQL setup **
postgresql 10:47:27.75 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 10:47:27.76 INFO  ==> Cleaning stale /bitnami/postgresql/data/postmaster.pid file
postgresql 10:47:27.77 INFO  ==> Loading custom pre-init scripts...
postgresql 10:47:27.78 INFO  ==> Initializing PostgreSQL database...
postgresql 10:47:27.80 INFO  ==> pg_hba.conf file not detected. Generating it...
postgresql 10:47:27.81 INFO  ==> Generating local authentication configuration
postgresql 10:47:27.83 INFO  ==> Deploying PostgreSQL with persisted data...
postgresql 10:47:27.84 INFO  ==> Configuring replication parameters
postgresql 10:47:27.88 INFO  ==> Configuring fsync
postgresql 10:47:27.89 INFO  ==> Configuring synchronous_replication
postgresql 10:47:27.95 INFO  ==> Loading custom scripts...
postgresql 10:47:27.96 INFO  ==> Enabling remote connections
postgresql 10:47:27.97 INFO  ==> ** PostgreSQL setup finished! **

postgresql 10:47:27.99 INFO  ==> ** Starting PostgreSQL **
2023-02-14 10:47:28.080 GMT [1] LOG:  pgaudit extension initialized
2023-02-14 10:47:28.085 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2023-02-14 10:47:28.087 GMT [1] LOG:  could not create IPv6 socket for address "::": Address family not supported by protocol
2023-02-14 10:47:28.092 GMT [1] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2023-02-14 10:47:28.129 GMT [94] LOG:  database system was interrupted; last known up at 2023-02-14 10:45:55 GMT
2023-02-14 10:47:28.219 GMT [94] LOG:  database system was not properly shut down; automatic recovery in progress
2023-02-14 10:47:28.222 GMT [94] LOG:  redo starts at 0/1661948
2023-02-14 10:47:28.222 GMT [94] LOG:  invalid record length at 0/1661980: wanted 24, got 0
2023-02-14 10:47:28.222 GMT [94] LOG:  redo done at 0/1661948
2023-02-14 10:47:28.242 GMT [1] LOG:  database system is ready to accept connections
2023-02-14 10:47:38.442 GMT [108] ERROR:  relation "log" does not exist at character 13
2023-02-14 10:47:38.442 GMT [108] STATEMENT:  INSERT INTO log (dttm, event, owner, extra) VALUES ('2023-02-14T10:47:36.919125+00:00'::timestamptz, 'cli_check', 'airflow', '{"host_name": "airflow-worker-0", "full_command": "[''/home/airflow/.local/bin/airflow'', ''db'', ''check'']"}') RETURNING log.id
2023-02-14 10:47:38.442 GMT [109] ERROR:  relation "log" does not exist at character 13
2023-02-14 10:47:38.442 GMT [109] STATEMENT:  INSERT INTO log (dttm, event, owner, extra) VALUES ('2023-02-14T10:47:37.186626+00:00'::timestamptz, 'cli_check', 'airflow', '{"host_name": "airflow-run-airflow-migrations-cnkx8", "full_command": "[''/home/airflow/.local/bin/airflow'', ''db'', ''check'']"}') RETURNING log.id
2023-02-14 10:47:42.280 GMT [110] ERROR:  relation "log" does not exist at character 13
2023-02-14 10:47:42.280 GMT [110] STATEMENT:  INSERT INTO log (dttm, event, owner, extra) VALUES ('2023-02-14T10:47:42.243064+00:00'::timestamptz, 'cli_check', 'airflow', '{"host_name": "airflow-scheduler-774877b6b-n4r6d", "full_command": "[''/home/airflow/.local/bin/airflow'', ''db'', ''check'']"}') RETURNING log.id
2023-02-14 10:47:42.995 GMT [111] ERROR:  relation "log" does not exist at character 13
2023-02-14 10:47:42.995 GMT [111] STATEMENT:  INSERT INTO log (dttm, event, owner, extra) VALUES ('2023-02-14T10:47:42.947552+00:00'::timestamptz, 'cli_upgradedb', 'airflow', '{"host_name": "airflow-run-airflow-migrations-cnkx8", "full_command": "[''/home/airflow/.local/bin/airflow'', ''db'', ''upgrade'']"}') RETURNING log.id
2023-02-14 10:47:43.122 GMT [112] ERROR:  relation "log" does not exist at character 13
2023-02-14 10:47:43.122 GMT [112] STATEMENT:  INSERT INTO log (dttm, event, owner, extra) VALUES ('2023-02-14T10:47:43.102700+00:00'::timestamptz, 'cli_check', 'airflow', '{"host_name": "airflow-triggerer-84888d74bc-mvt2c", "full_command": "[''/home/airflow/.local/bin/airflow'', ''db'', ''check'']"}') RETURNING log.id
2023-02-14 10:47:43.744 GMT [113] ERROR:  relation "log" does not exist at character 13
2023-02-14 10:47:43.744 GMT [113] STATEMENT:  INSERT INTO log (dttm, event, owner, extra) VALUES ('2023-02-14T10:47:43.630938+00:00'::timestamptz, 'cli_check', 'airflow', '{"host_name": "airflow-webserver-86b6bddf7c-vkv7c", "full_command": "[''/home/airflow/.local/bin/airflow'', ''db'', ''check'']"}') RETURNING log.id
2023-02-14 10:47:47.294 GMT [111] ERROR:  relation "connection" does not exist at character 55
2023-02-14 10:47:47.294 GMT [111] STATEMENT:  SELECT connection.conn_id AS connection_conn_id 
  FROM connection GROUP BY connection.conn_id 
  HAVING count(*) > 1
2023-02-14 10:47:47.298 GMT [111] ERROR:  relation "connection" does not exist at character 55
2023-02-14 10:47:47.298 GMT [111] STATEMENT:  SELECT connection.conn_id AS connection_conn_id 
  FROM connection 
  WHERE connection.conn_type IS NULL
2023-02-14 10:47:47.441 GMT [111] ERROR:  relation "ab_user" does not exist at character 51
2023-02-14 10:47:47.441 GMT [111] STATEMENT:  SELECT ab_user.username AS ab_user_username 
  FROM ab_user GROUP BY ab_user.username 
  HAVING count(*) > 1
2023-02-14 10:47:47.445 GMT [111] ERROR:  relation "ab_register_user" does not exist at character 69
2023-02-14 10:47:47.445 GMT [111] STATEMENT:  SELECT ab_register_user.username AS ab_register_user_username 
  FROM ab_register_user GROUP BY ab_register_user.username 
  HAVING count(*) > 1
2023-02-14 10:54:26.167 GMT [709] ERROR:  canceling statement due to lock timeout
2023-02-14 10:54:26.167 GMT [709] STATEMENT:  SELECT pg_advisory_lock(1)
2023-02-14 10:54:26.171 GMT [709] WARNING:  you don't own a lock of type ExclusiveLock
2023-02-14 10:54:48.416 GMT [740] ERROR:  canceling statement due to lock timeout
2023-02-14 10:54:48.416 GMT [740] STATEMENT:  SELECT pg_advisory_lock(1)
2023-02-14 10:54:48.419 GMT [740] WARNING:  you don't own a lock of type ExclusiveLock
2023-02-14 10:56:24.621 GMT [895] ERROR:  canceling statement due to lock timeout
2023-02-14 10:56:24.621 GMT [895] STATEMENT:  SELECT pg_advisory_lock(1)
2023-02-14 10:56:24.624 GMT [895] WARNING:  you don't own a lock of type ExclusiveLock
2023-02-14 10:57:12.739 GMT [972] ERROR:  canceling statement due to lock timeout
2023-02-14 10:57:12.739 GMT [972] STATEMENT:  SELECT pg_advisory_lock(1)
2023-02-14 10:57:12.743 GMT [972] WARNING:  you don't own a lock of type ExclusiveLock
2023-02-14 10:59:24.413 GMT [1166] ERROR:  canceling statement due to lock timeout
2023-02-14 10:59:24.413 GMT [1166] STATEMENT:  SELECT pg_advisory_lock(1)
2023-02-14 10:59:24.418 GMT [1166] WARNING:  you don't own a lock of type ExclusiveLock
2023-02-14 11:01:33.334 GMT [1367] ERROR:  canceling statement due to lock timeout
2023-02-14 11:01:33.334 GMT [1367] STATEMENT:  SELECT pg_advisory_lock(1)
2023-02-14 11:01:33.338 GMT [1367] WARNING:  you don't own a lock of type ExclusiveLock
2023-02-14 11:14:22.714 GMT [98] LOG:  using stale statistics instead of current ones because stats collector is not responding
```

**Comment by potiuk** [comment]
All those errors indicate that you allocated far too little memory to your cluster or other resources (networking DB, CPU, you name it). All those logs indicate tha that some swapping or very,very, very limited resources that are hamparing the system from running, swapping it out to disk conitinuously and the like. 

Take 4 time bigger machine and try again.

Converting it it into discussion, as this is most likely deployment issue, not Airflow one.
