### ISSUE TITLE
CeleryKubernetesExecutor @task(queue="kubernetes")  not work

### ISSUE THREAD

**Issue by takersk** [apache/airflow#29561]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

value.yaml
```
config:
  celery_kubernetes_executor:
    kubernetes_queue: 'kubernetes'
...
executor: "CeleryKubernetesExecutor"
```

tasks (example.dag)
- case01 (Expect to be run is CeleryExecutor) => ok!!
def example_task_celery(_dag): 
```
[2023-02-15 02:43:20,253: INFO/ForkPoolWorker-15] Task airflow.executors.celery_executor.execute_command[93ae0ee5-b390-4bda-b3d7-0782ccab5059] succeeded in 5.488538254052401s: None
```

- case02 (Expect to be run is CeleryExecutor) => queue stuck => not ok!!
@task(queue="test")
def example_task_celery(_dag):
```
[2023-02-15T04:28:23.494+0000] {base_executor.py:215} ERROR - could not queue task TaskInstanceKey(dag_id='example_dag', task_id='example_task_celery', run_id='manual__2023-02-15T02:41:33.585720+00:00', try_number=3, map_index=-1) (still running after 4 attempts)
[2023-02-15T04:29:11.345+0000] {scheduler_job.py:1231} INFO - Resetting orphaned tasks for active dag runs
```

- case03 (Expect to be run is KubernetesExecutor) => not ok!!
@task(queue="kubernetes")
def example_task_kubernetes(_dag):

The worker runs and immediately throws an error
```
[2023-02-15, 15:14:58 KST] {taskinstance.py:1581} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=cdpde
AIRFLOW_CTX_DAG_ID=example_dag
AIRFLOW_CTX_TASK_ID=example_task_kubernetes
AIRFLOW_CTX_EXECUTION_DATE=2023-02-15T06:09:54.463674+00:00
AIRFLOW_CTX_TRY_NUMBER=5
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-15T06:09:54.463674+00:00
[2023-02-15, 15:14:58 KST] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/repo/dags/example_dag.py", line 23, in example_task_kubernetes
    exec_trino_query_string_task = exec_trino_query_pod(
  File "/opt/airflow/dags/repo/dags/common/utils/pod.py", line 10, in exec_trino_query_pod
    return get_k8s_operator(
  File "/opt/airflow/dags/repo/dags/common/operator/operator.py", line 50, in get_k8s_operator
    return KubernetesPodOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/cncf/kubernetes/operators/kubernetes_pod.py", line 227, in __init__
    super().__init__(resources=resources, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 764, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 210, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'example_task_kubernetes' has already been added to the DAG
[2023-02-15, 15:14:58 KST] {taskinstance.py:1407} INFO - Marking task as FAILED. dag_id=example_dag, task_id=example_task_kubernetes, execution_date=20230215T060954, start_date=20230215T061457, end_date=20230215T061458
[2023-02-15, 15:14:58 KST] {standard_task_runner.py:92} ERROR - Failed to execute job 141 for task example_task_kubernetes (Task id 'example_task_kubernetes' has already been added to the DAG; 14)
[2023-02-15, 15:14:58 KST] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-02-15, 15:14:58 KST] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
```

### Operating System

PRETTY_NAME="Debian GNU/Linux 11 (bullseye)" NAME="Debian GNU/Linux" VERSION_ID="11"

### Versions of Apache Airflow Providers

apache-airflow-providers-amazon==5.0.0
apache-airflow-providers-celery==3.0.0
apache-airflow-providers-cncf-kubernetes==4.3.0
apache-airflow-providers-common-sql==1.1.0
apache-airflow-providers-docker==3.1.0
apache-airflow-providers-elasticsearch==4.2.0
apache-airflow-providers-ftp==3.1.0
apache-airflow-providers-google==8.3.0
apache-airflow-providers-grpc==3.0.0
apache-airflow-providers-hashicorp==3.1.0
apache-airflow-providers-http==4.0.0
apache-airflow-providers-imap==3.0.0
apache-airflow-providers-microsoft-azure==4.2.0
apache-airflow-providers-mysql==3.2.0
apache-airflow-providers-odbc==3.1.1
apache-airflow-providers-postgres==5.2.0
apache-airflow-providers-redis==3.0.0
apache-airflow-providers-sendgrid==3.0.0
apache-airflow-providers-sftp==4.0.0
apache-airflow-providers-slack==5.1.0
apache-airflow-providers-sqlite==3.2.0
apache-airflow-providers-ssh==3.1.0

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

* helm chart
apiVersion: v2
name: airflow
version: 1.7.0-dev
appVersion: 2.3.4

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by hussein-awala** [comment]
Can you add your dag code?

**Comment by takersk** [comment]
@hussein-awala 

yes!!

```
import os
from datetime import datetime, timedelta

from airflow import DAG

from common.enum.enum import DagEnum, DatahubEnum
from common.operator.custom_dummy_operator import CustomDummyOperator
from common.options.trino_options import TrinoStringOptions
from common.utils.date import KST
from common.utils.date import (
    execution_date_fmt,
)
from common.utils.pod import (
    exec_trino_query_pod,
)
from common.utils.watchtower import WatchTower
from airflow.decorators import task


@task(queue="kubernetes")
def example_task_kubernetes(_dag):
    query_str = "select * from kudu.dw.dim_gift_brand limit 10"
    exec_trino_query_string_task = exec_trino_query_pod(
        dag=_dag,
        task_id="example_task_kubernetes",
        trino_options=TrinoStringOptions(
            query_string=query_str,
        )
    )

    return exec_trino_query_string_task


def example_task_celery(_dag):
    query_str = "select * from kudu.dw.dim_gift_brand limit 10"
    exec_trino_query_string_task = exec_trino_query_pod(
        dag=_dag,
        task_id="example_task_celery",
        trino_options=TrinoStringOptions(
            query_string=query_str,
        )
    )

    return exec_trino_query_string_task


default_args = {
    "owner": DagEnum.DE_OWNER.value,
    "depends_on_past": False,
    "start_date": datetime(2022, 10, 6, tzinfo=KST),
    "email_on_failure": False,
    "email_on_retry": False,
    "execution_timeout": timedelta(hours=int(DagEnum.EXECUTION_TIMEOUT_HOUR_MAX.value)),
    "retries": int(DagEnum.RETRIES_MID.value),
    # "on_failure_callback": WatchTower().fail,
    "retry_delay": timedelta(minutes=int(DagEnum.RETRY_DELAY_MIN.value)),
}

with DAG(
        dag_id=os.path.basename(__file__).replace(".py", ""),
        default_args=default_args,
        schedule_interval="*/10 * * * *",
        user_defined_macros={
            "execution_date_fmt": execution_date_fmt,
        },
        concurrency=int(DagEnum.CONCURRENCY_MID.value),
        max_active_runs=int(DagEnum.MAX_ACTIVE_RUNS_MIN.value),
        catchup=False,
        tags=[DatahubEnum.TAG_TRINO.value, DatahubEnum.TAG_SPARK.value, DatahubEnum.TAG_DISTCP.value],
) as dag:
    # dummy task
    start_task = CustomDummyOperator(task_id="start", dag=dag)
    end_task = CustomDummyOperator(task_id="end", dag=dag)

    # tasks
    # start_task >> example_task_kubernetes(dag) >> end_task
    start_task >> example_task_celery(dag) >> end_task
```

**Comment by tirkarthi** [comment]
`example_task_kubernetes` is the function name decorated by `@task` . You also seem to be passing the same value as task_id to `exec_trino_query_pod` where if you are trying to create another task with same task_id then it might result in error.

**Comment by takersk** [comment]
@tirkarthi cc: @hussein-awala 

Thank you for answer. I tested it after changing task_id, but another error is occurring. Can I check it?

dags code modiftyed
```
@task(queue="kubernetes")
def example_task_kubernetes(_dag):
    query_str = "select * from kudu.dw.dim_gift_brand limit 10"
    exec_trino_query_string_task = exec_trino_query_pod(
        dag=_dag,
        task_id="task_kubernetes",
        trino_options=TrinoStringOptions(
            query_string=query_str,
        )
    )

    return exec_trino_query_string_task


def example_task_celery(_dag):
    query_str = "select * from kudu.dw.dim_gift_brand limit 10"
    exec_trino_query_string_task = exec_trino_query_pod(
        dag=_dag,
        task_id="task_celery",
        trino_options=TrinoStringOptions(
            query_string=query_str,
        )
    )

    return exec_trino_query_string_task
```

error
<img width="435" alt="스크린샷 2023-02-20 오후 2 57 44" src="https://user-images.githubusercontent.com/3029712/220021608-92fd205d-f6ec-434d-b8c5-8ceecad2edf3.png">

```
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-20T05:53:47.226076+00:00
[2023-02-20, 14:57:38 KST] {python.py:173} INFO - Done. Returned value was: <Task(KubernetesPodOperator): task_kubernetes>
[2023-02-20, 14:57:38 KST] {xcom.py:585} ERROR - Could not serialize the XCom value into JSON. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your airflow config.
[2023-02-20, 14:57:38 KST] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2398, in xcom_push
    XCom.set(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom.py", line 192, in set
    value = cls.serialize_value(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom.py", line 583, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/local/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type KubernetesPodOperator is not JSON serializable
[2023-02-20, 14:57:38 KST] {taskinstance.py:1407} INFO - Marking task as FAILED. dag_id=example_dag, task_id=example_task_kubernetes, execution_date=20230220T055347, start_date=20230220T055738, end_date=20230220T055738
[2023-02-20, 14:57:38 KST] {standard_task_runner.py:92} ERROR - Failed to execute job 1776 for task example_task_kubernetes (Object of type KubernetesPodOperator is not JSON serializable; 14)
[2023-02-20, 14:57:38 KST] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-02-20, 14:57:38 KST] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
```

**Comment by tirkarthi** [comment]
Values returned by tasks should be JSON serializable. Please see comments https://github.com/apache/airflow/issues/28492#issuecomment-1359564322 and https://github.com/apache/airflow/discussions/27209#discussioncomment-3941845

**Comment by takersk** [comment]
@tirkarthi 
There is no value returned by task, exec_trino_query_pod task will run the actual
==>
return KubernetesPodOperator(
        name=task_id.replace("_", "-"),
        ...
        do_xcom_push=False,
    )


There is no problem with KubernetesExecutor , only CeleryKubernetesExecutor has issues. Will this make a difference?

**Comment by takersk** [comment]
@tirkarthi 
thank you I solved it.

**Comment by tirkarthi** [comment]
You're welcome @takersk
