### ISSUE TITLE
Cannot trigger the same dag_id within the same second

### ISSUE THREAD

**Issue by scastria** [apache/airflow#29582]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

Maybe similar to #15174

Trying to trigger the same dag_id  within the same second.  I get:

Traceback (most recent call last):
--
File "/usr/local/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
self.dialect.do_execute(
File "/usr/local/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 719, in do_execute
cursor.execute(statement, parameters)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "dag_run_dag_id_execution_date_key"
DETAIL:  Key (dag_id, execution_date)=(shawn-shotgun3-shotgun, 2023-02-16 22:47:21+00) already exists.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/local/airflow/.local/bin/airflow", line 8, in <module>
sys.exit(main())
File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/__main__.py", line 39, in main
args.func(args)
File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_parser.py", line 52, in command
return func(*args, **kwargs)
File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 103, in wrapper
return f(*args, **kwargs)
File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/dag_command.py", line 145, in dag_trigger
message = api_client.trigger_dag(
File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/api/client/local_client.py", line 32, in trigger_dag
dag_run = trigger_dag.trigger_dag(
File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/api/common/trigger_dag.py", line 124, in trigger_dag
triggers = _trigger_dag(
File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/api/common/trigger_dag.py", line 89, in _trigger_dag
dag_run = _dag.create_dagrun(
File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 75, in wrapper
return func(*args, session=session, **kwargs)
File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/models/dag.py", line 2540, in create_dagrun
session.flush()
File "/usr/local/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3345, in flush
self._flush(objects)
File "/usr/local/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3484, in _flush
with util.safe_reraise():
File "/usr/local/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
compat.raise_(
File "/usr/local/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
raise exception
File "/usr/local/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3445, in _flush
flush_context.execute()
File "/usr/local/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
rec.execute(self)
File "/usr/local/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
util.preloaded.orm_persistence.save_obj(
File "/usr/local/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 244, in save_obj
_emit_insert_statements(
File "/usr/local/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1221, in _emit_insert_statements
result = connection._execute_20(
File "/usr/local/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1614, in _execute_20
return meth(self, args_10style, kwargs_10style, execution_options)
File "/usr/local/airflow/.local/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
return connection._execute_clauseelement(
File "/usr/local/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1481, in _execute_clauseelement
ret = self._execute_context(
File "/usr/local/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1845, in _execute_context
self._handle_dbapi_exception(
File "/usr/local/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2026, in _handle_dbapi_exception
util.raise_(
File "/usr/local/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
raise exception
File "/usr/local/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
self.dialect.do_execute(
File "/usr/local/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 719, in do_execute
cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "dag_run_dag_id_execution_date_key"
DETAIL:  Key (dag_id, execution_date)=(shawn-shotgun3-shotgun, 2023-02-16 22:47:21+00) already exists.
[SQL: INSERT INTO dag_run (dag_id, queued_at, execution_date, start_date, end_date, state, run_id, creating_job_id, external_trigger, run_type, conf, data_interval_start, data_interval_end, last_scheduling_decision, dag_hash, log_template_id) VALUES (%(dag_id)s, %(queued_at)s, %(execution_date)s, %(start_date)s, %(end_date)s, %(state)s, %(run_id)s, %(creating_job_id)s, %(external_trigger)s, %(run_type)s, %(conf)s, %(data_interval_start)s, %(data_interval_end)s, %(last_scheduling_decision)s, %(dag_hash)s, (SELECT max(log_template.id) AS max_1
FROM log_template)) RETURNING dag_run.id]
[parameters: {'dag_id': 'shawn-shotgun3-shotgun', 'queued_at': datetime.datetime(2023, 2, 16, 22, 47, 22, 43099, tzinfo=Timezone('UTC')), 'execution_date': DateTime(2023, 2, 16, 22, 47, 21, tzinfo=Timezone('UTC')), 'start_date': None, 'end_date': None, 'state': <DagRunState.QUEUED: 'queued'>, 'run_id': 'shotgun3_20230216224703986721', 'creating_job_id': None, 'external_trigger': True, 'run_type': <DagRunType.MANUAL: 'manual'>, 'conf': <psycopg2.extensions.Binary object at 0x7fab34ddb840>, 'data_interval_start': DateTime(2023, 2, 16, 22, 47, 21, tzinfo=Timezone('UTC')), 'data_interval_end': DateTime(2023, 2, 16, 22, 47, 21, tzinfo=Timezone('UTC')), 'last_scheduling_decision': None, 'dag_hash': '7ab0e818c048cc52d84ba94f0df44258'}]
(Background on this error at: https://sqlalche.me/e/14/gkpj)

### What you think should happen instead

It should be allowed to run the same dag many times without any issue of how fast it is being run.  The error message above seems to suggest that there is a unique key constraint with columns:

dag_id, execution_date

which prevent this since the execution_date only has resolution to the second.  I would have thought dag_id and run_id should be the unique key constraint and leave it up to the caller to guarantee unique run_ids.

### Operating System

AWS MWAA 2.4.3

### Deployment

MWAA

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by hussein-awala** [comment]
> Cannot trigger the same dag_id within the same second

You cannot trigger the dag multiple time with the same execution date because there are two unique constraint on the table:
- ("dag_id", "execution_date")
- ("dag_id", "run_id")

> It should be allowed to run the same dag many times without any issue of how fast it is being run. The error message above seems to suggest that there is a unique key constraint with columns:
dag_id, execution_date
which prevent this since the execution_date only has resolution to the second. I would have thought dag_id and run_id should be the unique key constraint and leave it up to the caller to guarantee unique run_ids.

The execution_date is a timestamp with precision 6 (6 fractional digits in the seconds field), so it's almost impossible to get the same execution_date if you do 2 sequence trigger queries, unless if there is a problem in the API which you use to create the dag runs.

Can you precise how do you create these dag runs? Which one of Airflow apis (UI, CLI, REST API, Python API) are you using?

**Comment by scastria** [comment]
We are using MWAA managed Airflow in AWS.  They do not directly expose the Airflow REST API, but instead have their own REST API that, I think, calls the Airflow CLI??  Therefore, the MWAA REST API contains this Airflow CLI command:

dags trigger -c 'custom json stuff' -r <run_id> <dag_id>

The <dag_id> is, of course, the unique DAG we want to trigger.  The <run_id> is computed like this in Python:

run_id = f"shotgun3_{datetime.now().strftime('%Y%m%d%H%M%S%f')}"

Notice we included the %f to include the microseconds in the run_id.  The stack trace above shows the actual run_id as:

shotgun3_20230216224703986721

**Comment by hussein-awala** [comment]
Airflow `dags.trigger` removes the microseconds by default, if you want to keep them, you can add the argument `--no-replace-microseconds`. Can you test with this argument?

It seems like this argument is not added to Airflow CLI docs, I will fix this.

**Comment by hussein-awala** [comment]
Airflow `dags.trigger` removes the microseconds by default, #27640 added a new argument `--no-replace-microseconds` to support keeping them, unfortunately this feature will be available in 2.6.0.

If you want to fix this with your version 2.4.3, you can use another client (REST API, Python internal API) or even develop your own client module for CLI and configure Airflow to use it by setting the config [api_client](https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#api-client), you can simply extend the Client class and override the method [trigger_dag](https://github.com/apache/airflow/blob/main/airflow/api/client/local_client.py#L31-L31) to force a `False` value for the argument `replace_microseconds`.

I close the issue as fixed in #27640, if you think there is still a problem with this fix, we can re-open it.

**Comment by hussein-awala** [comment]
Fixed in #27640
