### ISSUE TITLE
SQLToGoogleSheetsOperator not executing properly

### ISSUE THREAD

**Issue by tegardp** [apache/airflow#29611]
### Apache Airflow version

2.5.1

### What happened

```
[2023-02-19 11:16:22,032] {dagrun.py:658} INFO - DagRun Finished: dag_id=xxxxxxx, execution_date=2022-09-23T00:00:00+00:00, run_id=manual__2022-09-23T00:00:00+00:00, run_start_date=2022-09-23T00:00:00+00:00, run_end_date=2023-02-19 11:16:21.900675+00:00, run_duration=12914181.900675, state=success, external_trigger=False, run_type=manual, data_interval_start=2022-09-23T00:00:00+00:00, data_interval_end=2022-09-23T00:00:00+00:00, dag_hash=None
```

DAG run successfully **but the data is not transferred.**

when I tried to execute it manually by using
```
testOps = SqlToGoogleSheetOperator(xxx,yyy,zzz)
testOps.execute()
```
 it said dag is missing
when I checked the UI. I receive this error
```
Broken DAG: [/opt/airflow/dags/core_data_brosur_kegiatan/core_data_brosur_kegiatan_v0_1.py] Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/core_data_brosur_kegiatan/core_data_brosur_kegiatan_v0_1.py", line 49, in <module>
    testOperator.execute()
TypeError: execute() missing 1 required positional argument: 'context'
```

Then I tried to pass some random parameter to fill the context. eg. 
`testOps.execute(1)`

Then the dag ran successfully and the data was transferred

### What you think should happen instead

I think it should always transfer the data successfully without adding .execute(context) in this operator.

### How to reproduce

testOperator = SQLToGoogleSheetsOperator(
        task_id="some id",
        sql="select * from your table",
        sql_conn_id="mysql_default_connection",
        gcp_conn_id="google_default_connection",
        spreadsheet_id=sheetId
    )

testOperator

### Operating System

macos

### Versions of Apache Airflow Providers

apache-airflow-providers-google==8.9.0

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

airflow:2.5.1
docker-compose

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by tegardp** [comment]
test execution date was earlier than start_date
