### ISSUE TITLE
ComputeEngineInsertInstanceFromTemplateOperator fails to parse SEV_SNP_CAPABLE in guestOsFeatures disk field

### ISSUE THREAD

**Issue by djpalm801** [apache/airflow#29844]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

Getting several exceptions when trying to use the ComputeEngineInsertInstanceFromTemplateOperator.  I'm using Cloud Composer and am on the latest version google offers: `composer 2.1.7 airflow 2.4.3`.  I'm using an instance template that uses the cos-cloud cos-stable-101-17162-127-8 image.  Using a pd-standard disk.

The VM instance gets created but the task throws these exceptions.  I'm also not able to delete the instance due to the same error.
### 

### What you think should happen instead

Here is the stack trace.

Traceback (most recent call last):
  File "/opt/python3.8/lib/python3.8/site-packages/airflow/providers/google/cloud/operators/compute.py", line 379, in execute
    existing_instance = hook.get_instance(
  File "/opt/python3.8/lib/python3.8/site-packages/airflow/providers/google/common/hooks/base_google.py", line 468, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/opt/python3.8/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/compute.py", line 349, in get_instance
    instance_obj = client.get(
  File "/opt/python3.8/lib/python3.8/site-packages/google/cloud/compute_v1/services/instances/client.py", line 1239, in get
    response = rpc(request, retry=retry, timeout=timeout, metadata=metadata,)
  File "/opt/python3.8/lib/python3.8/site-packages/google/api_core/gapic_v1/method.py", line 154, in __call__
    return wrapped_func(*args, **kwargs)
  File "/opt/python3.8/lib/python3.8/site-packages/google/api_core/grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/opt/python3.8/lib/python3.8/site-packages/google/cloud/compute_v1/services/instances/transports/rest.py", line 704, in get
    return compute.Instance.from_json(response.content, ignore_unknown_fields=True)
  File "/opt/python3.8/lib/python3.8/site-packages/proto/message.py", line 374, in from_json
    Parse(payload, instance._pb, ignore_unknown_fields=ignore_unknown_fields)
  File "/opt/python3.8/lib/python3.8/site-packages/google/protobuf/json_format.py", line 436, in Parse
    return ParseDict(js, message, ignore_unknown_fields, descriptor_pool,
  File "/opt/python3.8/lib/python3.8/site-packages/google/protobuf/json_format.py", line 461, in ParseDict
    parser.ConvertMessage(js_dict, message, '')
  File "/opt/python3.8/lib/python3.8/site-packages/google/protobuf/json_format.py", line 502, in ConvertMessage
    self._ConvertFieldValuePair(value, message, path)
  File "/opt/python3.8/lib/python3.8/site-packages/google/protobuf/json_format.py", line 627, in _ConvertFieldValuePair
    raise ParseError('Failed to parse {0} field: {1}.'.format(name, e))
google.protobuf.json_format.ParseError: Failed to parse disks field: Failed to parse guestOsFeatures field: Invalid enum value SEV_SNP_CAPABLE for enum type google.cloud.compute.v1.GuestOsFeature.Type at Instance.disks[0].guestOsFeatures[2].type..
[2023-03-01, 17:35:46 UTC] {taskinstance.py:1402} INFO - Marking task as FAILED. dag_id=mydag, task_id=create_vm, execution_date=20230301T173436, start_date=20230301T173545, end_date=20230301T173546
[2023-03-01, 17:35:46 UTC] {standard_task_runner.py:100} ERROR - Failed to execute job 359191 for task create_vm (Failed to parse disks field: Failed to parse guestOsFeatures field: Invalid enum value SEV_SNP_CAPABLE for enum type google.cloud.compute.v1.GuestOsFeature.Type at Instance.disks[0].guestOsFeatures[2].type..; 30327)
[2023-03-01, 17:35:46 UTC] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-03-01, 17:35:46 UTC] {taskinstance.py:2626} INFO - 0 downstream tasks scheduled from follow-on schedule check`

### How to reproduce

Create an instance template and then use the ComputeEngineInsertInstanceFromTemplateOperator to insert an instance from the template.

### Operating System

cos-cloud cos-stable-101-17162-127-8

### Versions of Apache Airflow Providers

apache-airflow-providers-google==8.9.0

### Deployment

Google Cloud Composer

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by SamWheating** [comment]
Could you run `pip list` and share your results? I suspect that this is due to an older version of the `google-cloud-compute` library.
