### ISSUE TITLE
To use CUDA with multiprocessing, you must use the 'spawn' start method

### ISSUE THREAD

**Issue by leoitcode** [apache/airflow#30061]
### Apache Airflow version

2.5.1

### What happened

I wasn't able to find a way to run CUDA application using torch libraries in Airflow due Gunicorn method of managing the parent and child processes with fork instead spawn.
I'd like to know if there is a way to run an application using GPU inside Apache airflow DAG.

What I've tried:
- Change configuration of execute_tasks_new_python_interpreter to True
- Reduce workes in Gunicorn settings.
- Set the torch.multiprocessing to spawn method:
mp.set_start_method('spawn', force=True)

### How to reproduce

To reproduce the problem is only try to load any kind of model into the CUDA device using torch.

```
with DAG(
    dag_id='dag_temp', 
    description='Dag temp',
    start_date=datetime(2022, 8, 18), 
    catchup=False
) as dag:

from transformers import AutoTokenizer, RobertaModel
import torch
@task()
def load_models():
   device = 'cuda' if torch.cuda.is_available() else 'cpu' # device = cuda

   tokenizer = AutoTokenizer.from_pretrained("roberta-base")
   model = RobertaModel.from_pretrained("roberta-base")
   model.to(device)
```

```
Traceback (most recent call last):
  File "/home/leobit/Development/mlfactory-pipeline/src/dags/med_reader_pipeline.py", line 34, in load_models
    model.to(device)
  File "/home/leobit/.cache/pypoetry/virtualenvs/mlfactory-pipeline-LOOcmODM-py3.10/lib/python3.10/site-packages/transformers/modeling_utils.py", line 1749, in to
    return super().to(*args, **kwargs)
  File "/home/leobit/.cache/pypoetry/virtualenvs/mlfactory-pipeline-LOOcmODM-py3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 989, in to
    return self._apply(convert)
  File "/home/leobit/.cache/pypoetry/virtualenvs/mlfactory-pipeline-LOOcmODM-py3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 641, in _apply
    module._apply(fn)
  File "/home/leobit/.cache/pypoetry/virtualenvs/mlfactory-pipeline-LOOcmODM-py3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 641, in _apply
    module._apply(fn)
  File "/home/leobit/.cache/pypoetry/virtualenvs/mlfactory-pipeline-LOOcmODM-py3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 641, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/home/leobit/.cache/pypoetry/virtualenvs/mlfactory-pipeline-LOOcmODM-py3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 664, in _apply
    param_applied = fn(param)
  File "/home/leobit/.cache/pypoetry/virtualenvs/mlfactory-pipeline-LOOcmODM-py3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 987, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "/home/leobit/.cache/pypoetry/virtualenvs/mlfactory-pipeline-LOOcmODM-py3.10/lib/python3.10/site-packages/torch/cuda/__init__.py", line 217, in _lazy_init
    raise RuntimeError(
RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method
```

I got the error:
RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the ‘spawn’ start method

### Operating System

Ubuntu 22.04

### Versions of Apache Airflow Providers

2.5.1, using through poetry installation.

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by hussein-awala** [comment]
Running this kind of processing in Airflow is a very bad idea, instead you can use `DockerOperator` or `KubernetesPodOperator` to run you processing inside an isolated environment outside Airflow.

You can check the [best practices doc](https://airflow.apache.org/docs/apache-airflow/stable/best-practices.html) and specially the mentionned operators [part](https://airflow.apache.org/docs/apache-airflow/stable/best-practices.html#using-dockeroperator-or-kubernetes-pod-operator).
