### ISSUE TITLE
Psql resolution and Redis connection issue

### ISSUE THREAD

**Issue by rahulkammili4** [apache/airflow#30437]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

Using Airflow 2.3.3 Version, facing issues on Psql and Redis(both psql and redis hosted on azure) and airflow(web, scheduler, worker) deployed on AKS and dag files azure storage account fileshare. 

**Psql error**

File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "psql-ml-we-prod-airflow.postgres.database.azure.com" to address: Temporary failure in name resolution

**Redis Error** 

[2023-03-30 01:44:08,413: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 332, in start
    blueprint.start(self)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 628, in start
    c.loop(*c.loop_args())
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/celery/worker/loops.py", line 97, in asynloop
    next(loop)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/kombu/asynchronous/hub.py", line 362, in create_loop
    cb(*cbargs)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/kombu/transport/redis.py", line 1326, in on_readable
    self.cycle.on_readable(fileno)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/kombu/transport/redis.py", line 562, in on_readable
    chan.handlers[type]()
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/kombu/transport/redis.py", line 955, in _brpop_read
    dest__item = self.client.parse_response(self.client.connection,
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/redis/client.py", line 1254, in parse_response
    response = connection.read_response()
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/redis/connection.py", line 824, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/redis/connection.py", line 318, in read_response
    raw = self._buffer.readline()
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/redis/connection.py", line 249, in readline
    self._read_from_socket()
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/redis/connection.py", line 195, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
[2023-03-30 01:44:08,416: WARNING/MainProcess] Restoring 3 unacknowledged message(s)
[2023-03-30 01:44:08,476: WARNING/MainProcess] /opt/bitnami/airflow/venv/lib/python3.8/site-packages/celery/worker/consumer/consumer.py:367: CPendingDeprecationWarning: 
In Celery 5.1 we introduced an optional breaking change which
on connection loss cancels all currently executed tasks with late acknowledgement enabled.
These tasks cannot be acknowledged as the connection is gone, and the tasks are automatically redelivered back to the queue.
You can enable this behavior using the worker_cancel_long_running_tasks_on_connection_loss setting.
In Celery 5.1 it is set to False by default. The setting will be set to True by default in Celery 6.0.

  warnings.warn(CANCEL_TASKS_BY_DEFAULT, CPendingDeprecationWarning)

[2023-03-30 01:44:08,503: INFO/MainProcess] Connected to redis://:**@10.156.150.68:6379/1
[2023-03-30 01:44:08,514: INFO/MainProcess] mingle: searching for neighbors
[2023-03-30 01:44:09,674: INFO/MainProcess] mingle: sync with 2 nodes
[2023-03-30 01:44:09,674: INFO/MainProcess] mingle: sync complete
[2023-03-30 01:44:39,742: INFO/MainProcess] Scaling down 2 processes.
[2023-03-30 01:45:09,743: INFO/MainProcess] Scaling down 1 processes.
[2023-03-30 01:45:39,745: INFO/MainProcess] Scaling down 1 processes.
[2023-03-30 01:46:09,747: INFO/MainProcess] Scaling down 1 processes.
[2023-03-30 01:46:39,749: INFO/MainProcess] Scaling down 1 processes.
[2023-03-30 01:47:09,750: INFO/MainProcess] Scaling down 1 processes.
[2023-03-30 01:47:39,752: INFO/MainProcess] Scaling down 1 processes.
[2023-03-30 01:48:09,754: INFO/MainProcess] Scaling down 1 processes.
[2023-03-30 01:48:39,756: INFO/MainProcess] Scaling down 1 processes.
[2023-03-30 01:49:09,757: INFO/MainProcess] Scaling down 1 processes.
[2023-03-30 01:49:39,760: INFO/MainProcess] Scaling down 1 processes.
[2023-03-30 01:50:09,762: INFO/MainProcess] Scaling down 1 processes.

### What you think should happen instead

No issues on psql name resolution and with any connection lost to the redis.

### How to reproduce

Deployed airflow 2.3.3 on AKS cluster using Azure DevOps and using Celery worker

### Operating System

Linux aks cluster 

### Deployment

Other 3rd-party Helm chart

### Deployment details

Bitnami aiflow helmchart 12.5.13

### Anything else

intermittent: daily some times 

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by hussein-awala** [comment]
Did you check if Psql and Redis are accessible from you AKS cluster? it can be a problem in the firewall or the network configurations.

**Comment by rahulkammili4** [comment]
Hi Hussein,
I have checked, I am able to do dns resolve  psql/redis from aks

**Comment by potiuk** [comment]
You have at best stability problem of getting name resolved from your host. There is absolutely nothing airflow can do about it and absolutely everything your network/deployment configuration can do about - but how, I thin you should address the question to the support of the system you are running it on.

This error means that basic fabric of your network does not work properly or that your naming resolution is misconfigurred - or maybe you have typo in your host name. nd again 

```
 could not translate host name "psql-ml-we-prod-airflow.postgres.database.azure.com" to address: Temporary failure in name resolution
```

Airflow cannot work, when network does not work, I hope this is clear :).
