### ISSUE TITLE
Error running `breeze setup regenerate-command-images`

### ISSUE THREAD

**Issue by rohan472000** [apache/airflow#30465]
after running `pre-commit run` , it asked me to run `breeze setup regenerate-command-images` but while running it I got below errors

PS C:\pycharm\codes\airflow-repo-clone\airflow> breeze setup regenerate-command-images
Traceback (most recent call last):
  File "C:\pycharm\codes\airflow-repo-clone\airflow\dev\breeze\src\airflow_breeze\commands\main_command.py", line 122, in check_for_python_emulation
    system_machine = subprocess.check_output(["uname", "-m"], text=True).strip()
  File "C:\python3.10\setup\lib\subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\python3.10\setup\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\python3.10\setup\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\python3.10\setup\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\python3.10\setup\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\python3.10\setup\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\users\anand\.local\bin\breeze.exe\__main__.py", line 7, in <module>
  File "C:\Users\anand\.local\pipx\venvs\apache-airflow-breeze\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\anand\.local\pipx\venvs\apache-airflow-breeze\lib\site-packages\rich_click\rich_group.py", line 21, in main
    rv = super().main(*args, standalone_mode=False, **kwargs)
  File "C:\Users\anand\.local\pipx\venvs\apache-airflow-breeze\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\anand\.local\pipx\venvs\apache-airflow-breeze\lib\site-packages\click\core.py", line 1654, in invoke
    super().invoke(ctx)
  File "C:\Users\anand\.local\pipx\venvs\apache-airflow-breeze\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\anand\.local\pipx\venvs\apache-airflow-breeze\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\anand\.local\pipx\venvs\apache-airflow-breeze\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\pycharm\codes\airflow-repo-clone\airflow\dev\breeze\src\airflow_breeze\commands\main_command.py", line 114, in main
    check_for_python_emulation()
  File "C:\pycharm\codes\airflow-repo-clone\airflow\dev\breeze\src\airflow_breeze\commands\main_command.py", line 146, in check_for_python_emulation
    except TimeoutOccurred:
UnboundLocalError: local variable 'TimeoutOccurred' referenced before assignment

_Originally posted by @rohan472000 in https://github.com/apache/airflow/issues/30405#issuecomment-1496414377_

**Comment by potiuk** [comment]
Fiz in #30464 . BTW, there will likely be more errors like that. Windows is our target (but not fully supported yet env, so if  you can report (or maybe even fix and make PRs) similar errors for windows, that would be cool. Fixing is best of course @rohan472000

**Comment by rohan472000** [comment]
Sure @potiuk I will try that definitely.

**Comment by potiuk** [comment]
Fix has been merged. It *should* work now natively

**Comment by rohan472000** [comment]
@potiuk well i m using wsl2, but I encountered some problems in Ubuntu distro whereas Ubuntu 22.0.4 is working fine with commands, also after any installation or any changes, I need to restart my terminal. Docs doesn't cover every step to install packages which I will try to add into my next PR.
