### ISSUE TITLE
ERROR - Exception when executing SchedulerJob._run_scheduler_loop 

### ISSUE THREAD

**Issue by rahulsinha07** [apache/airflow#30511]
### Apache Airflow version

2.5.3

### What happened

Getting  [Errno 12] Cannot allocate memory in logs 

there is lot of memory and only few DAG that to very simple running in the environment  

ERROR - Exception when executing SchedulerJob._run_scheduler_loop
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/jobs/scheduler_job.py", line 750, in _execute
    self.executor.start()
  File "/usr/local/lib/python3.7/site-packages/airflow/executors/local_executor.py", line 360, in start
    self.impl.start()
  File "/usr/local/lib/python3.7/site-packages/airflow/executors/local_executor.py", line 301, in start
    worker.start()
  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/usr/local/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/local/lib/python3.7/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/local/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/usr/local/lib/python3.7/multiprocessing/popen_fork.py", line 70, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory

### How to reproduce

ERROR - Exception when executing SchedulerJob._run_scheduler_loop
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/jobs/scheduler_job.py", line 750, in _execute
    self.executor.start()
  File "/usr/local/lib/python3.7/site-packages/airflow/executors/local_executor.py", line 360, in start
    self.impl.start()
  File "/usr/local/lib/python3.7/site-packages/airflow/executors/local_executor.py", line 301, in start
    worker.start()
  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/usr/local/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/local/lib/python3.7/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/local/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/usr/local/lib/python3.7/multiprocessing/popen_fork.py", line 70, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory

### Operating System

NAME="CentOS Linux" VERSION="7 (Core)" ID="centos" ID_LIKE="rhel fedora" VERSION_ID="7" PRETTY_NAME="CentOS Linux 7 (Core)"

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by rahulsinha07** [comment]
free -h
              total        used        free      shared  buff/cache   available
Mem:          8.0Gi        47Mi       8.0Gi          0B          0B       8.0Gi
Swap:          16Gi          0B        16Gi

**Comment by rahulsinha07** [comment]
Filesystem      Size  Used Avail Use% Mounted on
/dev/zfsds0      72G  1.5G   70G   3% /
devtmpfs         16G  108M   16G   1% /dev
tmpfs            16G  108M   16G   1% /dev/shm
/native/usr     433M  394M   40M  91% /native/usr

**Comment by hussein-awala** [comment]
This problem is not related to Airflow, it's a problem in your host.

If you are sure that you have enough memory, you can try the [always overcommit](https://www.kernel.org/doc/Documentation/vm/overcommit-accounting) mode:
```bash
echo 1 > /proc/sys/vm/overcommit_memory
```

I close the issue.
