### ISSUE TITLE
airflow db upgrade from 1.10.15 -> ValueError: No such constraint: 'dag_tag__fkey'

### ISSUE THREAD

**Issue by raphaelauv** [apache/airflow#30584]
### Apache Airflow version

2.5.3

### What happened

upgrade an empty sqlite 1.10.15 airflow database to 2.5.3 fail

### How to reproduce

```shell
export AIRFLOW_HOME=~/airflow
python3.7 -m venv venv
source venv/bin/activate
pip install apache-airflow==1.10.15 --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-1.10.15/constraints-3.7.txt"

airflow version
```
->
```log
1.10.15
```

-------

```shell
airflow db init
```
->
```log
INFO  [alembic.runtime.migration] Running upgrade 92c57b58940d -> 03afc6b6f902, Increase length of FAB ab_view_menu.name column
Done.
```

-------

```shell
deactivate
rm -rf venv
python3.10 -m venv venv
source venv/bin/activate
pip install "apache-airflow==2.5.3" --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.5.3/constraints-3.10.txt"

airflow version
```
->
```log
2.5.3
```

-------

```shell
airflow db upgrade
```
->
```log
INFO  [alembic.runtime.migration] Running upgrade 1de7bc13c950 -> 3c94c427fdf6, Add cascade to dag_tag foreign key
Traceback (most recent call last):
  File "/home/XX/venv/lib/python3.10/site-packages/alembic/operations/batch.py", line 689, in drop_constraint
    const = self.named_constraints.pop(const.name)
KeyError: 'dag_tag__fkey'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/XX/venv/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/home/XX/venv/lib/python3.10/site-packages/airflow/__main__.py", line 48, in main
    args.func(args)
  File "/home/XX/venv/lib/python3.10/site-packages/airflow/cli/cli_parser.py", line 52, in command
    return func(*args, **kwargs)
  File "/home/XX/venv/lib/python3.10/site-packages/airflow/utils/cli.py", line 108, in wrapper
    return f(*args, **kwargs)
  File "/home/XX/venv/lib/python3.10/site-packages/airflow/cli/commands/db_command.py", line 84, in upgradedb
    db.upgradedb(
  File "/home/XX/venv/lib/python3.10/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/XX/venv/lib/python3.10/site-packages/airflow/utils/db.py", line 1578, in upgradedb
    command.upgrade(config, revision=to_revision or "heads")
  File "/home/XX/venv/lib/python3.10/site-packages/alembic/command.py", line 378, in upgrade
    script.run_env()
  File "/home/XX/venv/lib/python3.10/site-packages/alembic/script/base.py", line 576, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/home/XX/venv/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/XX/venv/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/XX/venv/lib/python3.10/site-packages/airflow/migrations/env.py", line 117, in <module>
    run_migrations_online()
  File "/home/XX/venv/lib/python3.10/site-packages/airflow/migrations/env.py", line 111, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/home/XX/venv/lib/python3.10/site-packages/alembic/runtime/environment.py", line 867, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/home/XX/venv/lib/python3.10/site-packages/alembic/runtime/migration.py", line 624, in run_migrations
    step.migration_fn(**kw)
  File "/home/XX/venv/lib/python3.10/site-packages/airflow/migrations/versions/0110_2_3_2_add_cascade_to_dag_tag_foreignkey.py", line 46, in upgrade
    with op.batch_alter_table(
  File "/usr/lib/python3.10/contextlib.py", line 142, in __exit__
    next(self.gen)
  File "/home/XX/venv/lib/python3.10/site-packages/alembic/operations/base.py", line 383, in batch_alter_table
    impl.flush()
  File "/home/XX/venv/lib/python3.10/site-packages/alembic/operations/batch.py", line 159, in flush
    fn(*arg, **kw)
  File "/home/XX/venv/lib/python3.10/site-packages/alembic/operations/batch.py", line 700, in drop_constraint
    raise ValueError("No such constraint: '%s'" % const.name)
ValueError: No such constraint: 'dag_tag__fkey'
```

### Operating System

ubuntu 22.04

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
I think we had a few of those in the past. Sqlite upgradeability has never been a concern, because sqlite should only be used for development and you should never rely on the data there being "preservable". Do you know @raphaelauv if this is an sqlite-only problem? If so I think we should close it.

**Comment by raphaelauv** [comment]
No problem with postgres 

log -> 

```log
airflow db upgrade
Starting airflow bootstrap script with command: init_bd
DB: postgresql+psycopg2://airflow:***@airflow-db:5432/airflowdb
{db.py:919} INFO - Creating tables
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
/home/airflow/.local/lib/python3.8/site-packages/azure/storage/common/_connection.py:82 SyntaxWarning: "is" with a literal. Did you mean "=="?
INFO  [alembic.runtime.migration] Running upgrade 03afc6b6f902 -> cf5dc11e79ad, drop_user_and_chart
INFO  [alembic.runtime.migration] Running upgrade cf5dc11e79ad -> bbf4a7ad0465, Remove id column from xcom
INFO  [alembic.runtime.migration] Running upgrade bbf4a7ad0465 -> b25a55525161, Increase length of pool name
INFO  [alembic.runtime.migration] Running upgrade b25a55525161 -> 3c20cacc0044, Add DagRun run_type
INFO  [alembic.runtime.migration] Running upgrade 3c20cacc0044 -> 8f966b9c467a, Set conn_type as non-nullable
INFO  [alembic.runtime.migration] Running upgrade 8f966b9c467a -> 8d48763f6d53, add unique constraint to conn_id
INFO  [alembic.runtime.migration] Running upgrade 8d48763f6d53 -> e38be357a868, Add sensor_instance table
INFO  [alembic.runtime.migration] Running upgrade e38be357a868 -> b247b1e3d1ed, Add queued by Job ID to TI
INFO  [alembic.runtime.migration] Running upgrade b247b1e3d1ed -> e1a11ece99cc, Add external executor ID to TI
INFO  [alembic.runtime.migration] Running upgrade e1a11ece99cc -> bef4f3d11e8b, Drop KubeResourceVersion and KubeWorkerId
INFO  [alembic.runtime.migration] Running upgrade bef4f3d11e8b -> 98271e7606e2, Add scheduling_decision to DagRun and DAG
INFO  [alembic.runtime.migration] Running upgrade 98271e7606e2 -> 52d53670a240, fix_mssql_exec_date_rendered_task_instance_fields_for_MSSQL
INFO  [alembic.runtime.migration] Running upgrade 52d53670a240 -> 364159666cbd, Add creating_job_id to DagRun table
INFO  [alembic.runtime.migration] Running upgrade 364159666cbd -> 45ba3f1493b9, add-k8s-yaml-to-rendered-templates
INFO  [alembic.runtime.migration] Running upgrade 45ba3f1493b9 -> 849da589634d, Prefix DAG permissions.
INFO  [alembic.runtime.migration] Running upgrade 849da589634d -> 2c6edca13270, Resource based permissions.
{manager.py:245} INFO - Inserted Role: Admin
{manager.py:245} INFO - Inserted Role: Public
{manager.py:779} WARNING - No user yet created, use flask fab command to do it.
{manager.py:496} INFO - Created Permission View: can delete on Connections
{manager.py:496} INFO - Created Permission View: can read on Connections
{manager.py:496} INFO - Created Permission View: can edit on Connections
{manager.py:496} INFO - Created Permission View: can create on Connections
{manager.py:496} INFO - Created Permission View: can read on DAGs
{manager.py:496} INFO - Created Permission View: can edit on DAGs
{manager.py:496} INFO - Created Permission View: can delete on DAGs
{manager.py:496} INFO - Created Permission View: can read on DAG Runs
{manager.py:496} INFO - Created Permission View: can read on Task Instances
{manager.py:496} INFO - Created Permission View: can edit on Task Instances
{manager.py:496} INFO - Created Permission View: can delete on DAG Runs
{manager.py:496} INFO - Created Permission View: can create on DAG Runs
{manager.py:496} INFO - Created Permission View: can edit on DAG Runs
{manager.py:496} INFO - Created Permission View: can read on Audit Logs
{manager.py:496} INFO - Created Permission View: can read on ImportError
{manager.py:496} INFO - Created Permission View: can delete on Pools
{manager.py:496} INFO - Created Permission View: can read on Pools
{manager.py:496} INFO - Created Permission View: can edit on Pools
{manager.py:496} INFO - Created Permission View: can create on Pools
{manager.py:496} INFO - Created Permission View: can read on Providers
{manager.py:496} INFO - Created Permission View: can delete on Variables
{manager.py:496} INFO - Created Permission View: can read on Variables
{manager.py:496} INFO - Created Permission View: can edit on Variables
{manager.py:496} INFO - Created Permission View: can create on Variables
{manager.py:496} INFO - Created Permission View: can read on XComs
{manager.py:496} INFO - Created Permission View: can read on DAG Code
{manager.py:496} INFO - Created Permission View: can read on Configurations
{manager.py:496} INFO - Created Permission View: can read on Plugins
{manager.py:496} INFO - Created Permission View: can read on Roles
{manager.py:496} INFO - Created Permission View: can read on Permissions
{manager.py:496} INFO - Created Permission View: can delete on Roles
{manager.py:496} INFO - Created Permission View: can edit on Roles
{manager.py:496} INFO - Created Permission View: can create on Roles
{manager.py:496} INFO - Created Permission View: can read on Users
{manager.py:496} INFO - Created Permission View: can create on Users
{manager.py:496} INFO - Created Permission View: can edit on Users
{manager.py:496} INFO - Created Permission View: can delete on Users
{manager.py:245} INFO - Inserted Role: Viewer
{manager.py:558} INFO - Added Permission can read on Audit Logs to role Viewer
{manager.py:558} INFO - Added Permission can read on DAGs to role Viewer
{manager.py:496} INFO - Created Permission View: can read on DAG Dependencies
{manager.py:558} INFO - Added Permission can read on DAG Dependencies to role Viewer
{manager.py:558} INFO - Added Permission can read on DAG Code to role Viewer
{manager.py:558} INFO - Added Permission can read on DAG Runs to role Viewer
{manager.py:558} INFO - Added Permission can read on ImportError to role Viewer
{manager.py:496} INFO - Created Permission View: can read on Jobs
{manager.py:558} INFO - Added Permission can read on Jobs to role Viewer
{manager.py:496} INFO - Created Permission View: can read on My Password
{manager.py:558} INFO - Added Permission can read on My Password to role Viewer
{manager.py:496} INFO - Created Permission View: can edit on My Password
{manager.py:558} INFO - Added Permission can edit on My Password to role Viewer
{manager.py:496} INFO - Created Permission View: can read on My Profile
{manager.py:558} INFO - Added Permission can read on My Profile to role Viewer
{manager.py:496} INFO - Created Permission View: can edit on My Profile
{manager.py:558} INFO - Added Permission can edit on My Profile to role Viewer
{manager.py:558} INFO - Added Permission can read on Plugins to role Viewer
{manager.py:496} INFO - Created Permission View: can read on SLA Misses
{manager.py:558} INFO - Added Permission can read on SLA Misses to role Viewer
{manager.py:558} INFO - Added Permission can read on Task Instances to role Viewer
{manager.py:496} INFO - Created Permission View: can read on Task Logs
{manager.py:558} INFO - Added Permission can read on Task Logs to role Viewer
{manager.py:558} INFO - Added Permission can read on XComs to role Viewer
{manager.py:496} INFO - Created Permission View: can read on Website
{manager.py:558} INFO - Added Permission can read on Website to role Viewer
{manager.py:496} INFO - Created Permission View: menu access on Browse
{manager.py:558} INFO - Added Permission menu access on Browse to role Viewer
{manager.py:496} INFO - Created Permission View: menu access on DAG Dependencies
{manager.py:558} INFO - Added Permission menu access on DAG Dependencies to role Viewer
{manager.py:496} INFO - Created Permission View: menu access on DAG Runs
{manager.py:558} INFO - Added Permission menu access on DAG Runs to role Viewer
{manager.py:496} INFO - Created Permission View: menu access on Documentation
{manager.py:558} INFO - Added Permission menu access on Documentation to role Viewer
{manager.py:496} INFO - Created Permission View: menu access on Docs
{manager.py:558} INFO - Added Permission menu access on Docs to role Viewer
{manager.py:496} INFO - Created Permission View: menu access on Jobs
{manager.py:558} INFO - Added Permission menu access on Jobs to role Viewer
{manager.py:496} INFO - Created Permission View: menu access on Audit Logs
{manager.py:558} INFO - Added Permission menu access on Audit Logs to role Viewer
{manager.py:496} INFO - Created Permission View: menu access on Plugins
{manager.py:558} INFO - Added Permission menu access on Plugins to role Viewer
{manager.py:496} INFO - Created Permission View: menu access on SLA Misses
{manager.py:558} INFO - Added Permission menu access on SLA Misses to role Viewer
{manager.py:496} INFO - Created Permission View: menu access on Task Instances
{manager.py:558} INFO - Added Permission menu access on Task Instances to role Viewer
{manager.py:245} INFO - Inserted Role: User
{manager.py:558} INFO - Added Permission can read on Audit Logs to role User
{manager.py:558} INFO - Added Permission can read on DAGs to role User
{manager.py:558} INFO - Added Permission can read on DAG Dependencies to role User
{manager.py:558} INFO - Added Permission can read on DAG Code to role User
{manager.py:558} INFO - Added Permission can read on DAG Runs to role User
{manager.py:558} INFO - Added Permission can read on ImportError to role User
{manager.py:558} INFO - Added Permission can read on Jobs to role User
{manager.py:558} INFO - Added Permission can read on My Password to role User
{manager.py:558} INFO - Added Permission can edit on My Password to role User
{manager.py:558} INFO - Added Permission can read on My Profile to role User
{manager.py:558} INFO - Added Permission can edit on My Profile to role User
{manager.py:558} INFO - Added Permission can read on Plugins to role User
{manager.py:558} INFO - Added Permission can read on SLA Misses to role User
{manager.py:558} INFO - Added Permission can read on Task Instances to role User
{manager.py:558} INFO - Added Permission can read on Task Logs to role User
{manager.py:558} INFO - Added Permission can read on XComs to role User
{manager.py:558} INFO - Added Permission can read on Website to role User
{manager.py:558} INFO - Added Permission menu access on Browse to role User
{manager.py:558} INFO - Added Permission menu access on DAG Dependencies to role User
{manager.py:558} INFO - Added Permission menu access on DAG Runs to role User
{manager.py:558} INFO - Added Permission menu access on Documentation to role User
{manager.py:558} INFO - Added Permission menu access on Docs to role User
{manager.py:558} INFO - Added Permission menu access on Jobs to role User
{manager.py:558} INFO - Added Permission menu access on Audit Logs to role User
{manager.py:558} INFO - Added Permission menu access on Plugins to role User
{manager.py:558} INFO - Added Permission menu access on SLA Misses to role User
{manager.py:558} INFO - Added Permission menu access on Task Instances to role User
{manager.py:558} INFO - Added Permission can edit on DAGs to role User
{manager.py:558} INFO - Added Permission can delete on DAGs to role User
{manager.py:496} INFO - Created Permission View: can create on Task Instances
{manager.py:558} INFO - Added Permission can create on Task Instances to role User
{manager.py:558} INFO - Added Permission can edit on Task Instances to role User
{manager.py:496} INFO - Created Permission View: can delete on Task Instances
{manager.py:558} INFO - Added Permission can delete on Task Instances to role User
{manager.py:558} INFO - Added Permission can create on DAG Runs to role User
{manager.py:558} INFO - Added Permission can edit on DAG Runs to role User
{manager.py:558} INFO - Added Permission can delete on DAG Runs to role User
{manager.py:245} INFO - Inserted Role: Op
{manager.py:558} INFO - Added Permission can read on Audit Logs to role Op
{manager.py:558} INFO - Added Permission can read on DAGs to role Op
{manager.py:558} INFO - Added Permission can read on DAG Dependencies to role Op
{manager.py:558} INFO - Added Permission can read on DAG Code to role Op
{manager.py:558} INFO - Added Permission can read on DAG Runs to role Op
{manager.py:558} INFO - Added Permission can read on ImportError to role Op
{manager.py:558} INFO - Added Permission can read on Jobs to role Op
{manager.py:558} INFO - Added Permission can read on My Password to role Op
{manager.py:558} INFO - Added Permission can edit on My Password to role Op
{manager.py:558} INFO - Added Permission can read on My Profile to role Op
{manager.py:558} INFO - Added Permission can edit on My Profile to role Op
{manager.py:558} INFO - Added Permission can read on Plugins to role Op
{manager.py:558} INFO - Added Permission can read on SLA Misses to role Op
{manager.py:558} INFO - Added Permission can read on Task Instances to role Op
{manager.py:558} INFO - Added Permission can read on Task Logs to role Op
{manager.py:558} INFO - Added Permission can read on XComs to role Op
{manager.py:558} INFO - Added Permission can read on Website to role Op
{manager.py:558} INFO - Added Permission menu access on Browse to role Op
{manager.py:558} INFO - Added Permission menu access on DAG Dependencies to role Op
{manager.py:558} INFO - Added Permission menu access on DAG Runs to role Op
{manager.py:558} INFO - Added Permission menu access on Documentation to role Op
{manager.py:558} INFO - Added Permission menu access on Docs to role Op
{manager.py:558} INFO - Added Permission menu access on Jobs to role Op
{manager.py:558} INFO - Added Permission menu access on Audit Logs to role Op
{manager.py:558} INFO - Added Permission menu access on Plugins to role Op
{manager.py:558} INFO - Added Permission menu access on SLA Misses to role Op
{manager.py:558} INFO - Added Permission menu access on Task Instances to role Op
{manager.py:558} INFO - Added Permission can edit on DAGs to role Op
{manager.py:558} INFO - Added Permission can delete on DAGs to role Op
{manager.py:558} INFO - Added Permission can create on Task Instances to role Op
{manager.py:558} INFO - Added Permission can edit on Task Instances to role Op
{manager.py:558} INFO - Added Permission can delete on Task Instances to role Op
{manager.py:558} INFO - Added Permission can create on DAG Runs to role Op
{manager.py:558} INFO - Added Permission can edit on DAG Runs to role Op
{manager.py:558} INFO - Added Permission can delete on DAG Runs to role Op
{manager.py:558} INFO - Added Permission can read on Configurations to role Op
{manager.py:496} INFO - Created Permission View: menu access on Admin
{manager.py:558} INFO - Added Permission menu access on Admin to role Op
{manager.py:496} INFO - Created Permission View: menu access on Configurations
{manager.py:558} INFO - Added Permission menu access on Configurations to role Op
{manager.py:496} INFO - Created Permission View: menu access on Connections
{manager.py:558} INFO - Added Permission menu access on Connections to role Op
{manager.py:496} INFO - Created Permission View: menu access on Pools
{manager.py:558} INFO - Added Permission menu access on Pools to role Op
{manager.py:496} INFO - Created Permission View: menu access on Variables
{manager.py:558} INFO - Added Permission menu access on Variables to role Op
{manager.py:496} INFO - Created Permission View: menu access on XComs
{manager.py:558} INFO - Added Permission menu access on XComs to role Op
{manager.py:558} INFO - Added Permission can create on Connections to role Op
{manager.py:558} INFO - Added Permission can read on Connections to role Op
{manager.py:558} INFO - Added Permission can edit on Connections to role Op
{manager.py:558} INFO - Added Permission can delete on Connections to role Op
{manager.py:558} INFO - Added Permission can create on Pools to role Op
{manager.py:558} INFO - Added Permission can read on Pools to role Op
{manager.py:558} INFO - Added Permission can edit on Pools to role Op
{manager.py:558} INFO - Added Permission can delete on Pools to role Op
{manager.py:558} INFO - Added Permission can read on Providers to role Op
{manager.py:558} INFO - Added Permission can create on Variables to role Op
{manager.py:558} INFO - Added Permission can read on Variables to role Op
{manager.py:558} INFO - Added Permission can edit on Variables to role Op
{manager.py:558} INFO - Added Permission can delete on Variables to role Op
{manager.py:496} INFO - Created Permission View: can delete on XComs
{manager.py:558} INFO - Added Permission can delete on XComs to role Op
{manager.py:558} INFO - Added Permission can read on Audit Logs to role Admin
{manager.py:558} INFO - Added Permission can read on DAGs to role Admin
{manager.py:558} INFO - Added Permission can read on DAG Dependencies to role Admin
{manager.py:558} INFO - Added Permission can read on DAG Code to role Admin
{manager.py:558} INFO - Added Permission can read on DAG Runs to role Admin
{manager.py:558} INFO - Added Permission can read on ImportError to role Admin
{manager.py:558} INFO - Added Permission can read on Jobs to role Admin
{manager.py:558} INFO - Added Permission can read on My Password to role Admin
{manager.py:558} INFO - Added Permission can edit on My Password to role Admin
{manager.py:558} INFO - Added Permission can read on My Profile to role Admin
{manager.py:558} INFO - Added Permission can edit on My Profile to role Admin
{manager.py:558} INFO - Added Permission can read on Plugins to role Admin
{manager.py:558} INFO - Added Permission can read on SLA Misses to role Admin
{manager.py:558} INFO - Added Permission can read on Task Instances to role Admin
{manager.py:558} INFO - Added Permission can read on Task Logs to role Admin
{manager.py:558} INFO - Added Permission can read on XComs to role Admin
{manager.py:558} INFO - Added Permission can read on Website to role Admin
{manager.py:558} INFO - Added Permission menu access on Browse to role Admin
{manager.py:558} INFO - Added Permission menu access on DAG Dependencies to role Admin
{manager.py:558} INFO - Added Permission menu access on DAG Runs to role Admin
{manager.py:558} INFO - Added Permission menu access on Documentation to role Admin
{manager.py:558} INFO - Added Permission menu access on Docs to role Admin
{manager.py:558} INFO - Added Permission menu access on Jobs to role Admin
{manager.py:558} INFO - Added Permission menu access on Audit Logs to role Admin
{manager.py:558} INFO - Added Permission menu access on Plugins to role Admin
{manager.py:558} INFO - Added Permission menu access on SLA Misses to role Admin
{manager.py:558} INFO - Added Permission menu access on Task Instances to role Admin
{manager.py:558} INFO - Added Permission can edit on DAGs to role Admin
{manager.py:558} INFO - Added Permission can delete on DAGs to role Admin
{manager.py:558} INFO - Added Permission can create on Task Instances to role Admin
{manager.py:558} INFO - Added Permission can edit on Task Instances to role Admin
{manager.py:558} INFO - Added Permission can delete on Task Instances to role Admin
{manager.py:558} INFO - Added Permission can create on DAG Runs to role Admin
{manager.py:558} INFO - Added Permission can edit on DAG Runs to role Admin
{manager.py:558} INFO - Added Permission can delete on DAG Runs to role Admin
{manager.py:558} INFO - Added Permission can read on Configurations to role Admin
{manager.py:558} INFO - Added Permission menu access on Admin to role Admin
{manager.py:558} INFO - Added Permission menu access on Configurations to role Admin
{manager.py:558} INFO - Added Permission menu access on Connections to role Admin
{manager.py:558} INFO - Added Permission menu access on Pools to role Admin
{manager.py:558} INFO - Added Permission menu access on Variables to role Admin
{manager.py:558} INFO - Added Permission menu access on XComs to role Admin
{manager.py:558} INFO - Added Permission can create on Connections to role Admin
{manager.py:558} INFO - Added Permission can read on Connections to role Admin
{manager.py:558} INFO - Added Permission can edit on Connections to role Admin
{manager.py:558} INFO - Added Permission can delete on Connections to role Admin
{manager.py:558} INFO - Added Permission can create on Pools to role Admin
{manager.py:558} INFO - Added Permission can read on Pools to role Admin
{manager.py:558} INFO - Added Permission can edit on Pools to role Admin
{manager.py:558} INFO - Added Permission can delete on Pools to role Admin
{manager.py:558} INFO - Added Permission can read on Providers to role Admin
{manager.py:558} INFO - Added Permission can create on Variables to role Admin
{manager.py:558} INFO - Added Permission can read on Variables to role Admin
{manager.py:558} INFO - Added Permission can edit on Variables to role Admin
{manager.py:558} INFO - Added Permission can delete on Variables to role Admin
{manager.py:558} INFO - Added Permission can delete on XComs to role Admin
{manager.py:496} INFO - Created Permission View: can read on Task Reschedules
{manager.py:558} INFO - Added Permission can read on Task Reschedules to role Admin
{manager.py:496} INFO - Created Permission View: menu access on Task Reschedules
{manager.py:558} INFO - Added Permission menu access on Task Reschedules to role Admin
{manager.py:496} INFO - Created Permission View: can read on Triggers
{manager.py:558} INFO - Added Permission can read on Triggers to role Admin
{manager.py:496} INFO - Created Permission View: menu access on Triggers
{manager.py:558} INFO - Added Permission menu access on Triggers to role Admin
{manager.py:496} INFO - Created Permission View: can read on Passwords
{manager.py:558} INFO - Added Permission can read on Passwords to role Admin
{manager.py:496} INFO - Created Permission View: can edit on Passwords
{manager.py:558} INFO - Added Permission can edit on Passwords to role Admin
{manager.py:558} INFO - Added Permission can read on Roles to role Admin
{manager.py:558} INFO - Added Permission can edit on Roles to role Admin
INFO  [alembic.runtime.migration] Running upgrade 2c6edca13270 -> 61ec73d9401f, Add description field to connection
INFO  [alembic.runtime.migration] Running upgrade 61ec73d9401f -> 64a7d6477aae, fix description field in connection to be text
INFO  [alembic.runtime.migration] Running upgrade 64a7d6477aae -> e959f08ac86c, Change field in DagCode to MEDIUMTEXT for MySql
INFO  [alembic.runtime.migration] Running upgrade e959f08ac86c -> 82b7c48c147f, Remove can_read permission on config resource for User and Viewer role
{manager.py:779} WARNING - No user yet created, use flask fab command to do it.
INFO  [alembic.runtime.migration] Running upgrade 82b7c48c147f -> 449b4072c2da, Increase size of connection.extra field to handle multiple RSA keys
INFO  [alembic.runtime.migration] Running upgrade 449b4072c2da -> 8646922c8a04, Change default pool_slots to 1
INFO  [alembic.runtime.migration] Running upgrade 8646922c8a04 -> 2e42bb497a22, rename last_scheduler_run column
INFO  [alembic.runtime.migration] Running upgrade 2e42bb497a22 -> 90d1635d7b86, Increase pool name size in TaskInstance
INFO  [alembic.runtime.migration] Running upgrade 90d1635d7b86 -> e165e7455d70, add description field to variable
INFO  [alembic.runtime.migration] Running upgrade e165e7455d70 -> a13f7613ad25, Resource based permissions for default FAB views.
{manager.py:779} WARNING - No user yet created, use flask fab command to do it.
INFO  [alembic.runtime.migration] Running upgrade a13f7613ad25 -> 97cdd93827b8, Add queued_at column to dagrun table
INFO  [alembic.runtime.migration] Running upgrade 97cdd93827b8 -> 092435bf5d12, Add max_active_runs column to dagmodel table
INFO  [alembic.runtime.migration] Running upgrade 092435bf5d12 -> ccde3e26fe78, Add index on state, dag_id for queued dagrun
INFO  [alembic.runtime.migration] Running upgrade ccde3e26fe78 -> 83f031fd9f1c, improve mssql compatibility
INFO  [alembic.runtime.migration] Running upgrade 83f031fd9f1c -> e9304a3141f0, make xcom pkey columns non-nullable
INFO  [alembic.runtime.migration] Running upgrade e9304a3141f0 -> 30867afad44a, Rename concurrency column in dag table to max_active_tasks
INFO  [alembic.runtime.migration] Running upgrade 30867afad44a -> 54bebd308c5f, Add trigger table and task info
INFO  [alembic.runtime.migration] Running upgrade 54bebd308c5f -> 142555e44c17, Add data_interval_[start|end] to DagModel and DagRun.
INFO  [alembic.runtime.migration] Running upgrade 142555e44c17 -> 7b2661a43ba3, TaskInstance keyed to DagRun
INFO  [alembic.runtime.migration] Running upgrade 7b2661a43ba3 -> be2bfac3da23, Add has_import_errors column to DagModel
INFO  [alembic.runtime.migration] Running upgrade be2bfac3da23 -> c381b21cb7e4, add session table to db
INFO  [alembic.runtime.migration] Running upgrade c381b21cb7e4 -> 587bdf053233, adding index for dag_id in job
Upgrades done
```

it's only for sqlite then yes we can close 

thanks @potiuk :+1:
