### ISSUE TITLE
Could we support the PLAIN auth under use_beeline mode?

### ISSUE THREAD

**Issue by griffinqiu** [apache/airflow#306]
This is a create table hive operate. I have saw the command of airflow generated below
beeline -n user -p pwd -f /tmp/airflow_hiveop_aaHpS2/tmpZYKIxL -u jdbc:hive2://10.192.11.26:10000/default;auth=noSasl

However, the task is no response. It always show running. I could see there is a process always pending in my airflow server.

```
[kpiserv@localhost ~]$ ps aux | grep beeline
kpiserv   8797  0.3  4.2 1604120 168004 ?      Sl   07:23   0:01 /usr/java/jdk1.7.0_67-cloudera/bin/java -Xmx256m -Dhadoop.log.dir=/usr/lib/hadoop/logs -Dhadoop.log.file=hadoop.log -Dhadoop.home.dir=/usr/lib/hadoop -Dhadoop.id.str= -Dhadoop.root.logger=INFO,console -Djava.library.path=/usr/lib/hadoop/lib/native -Dhadoop.policy.file=hadoop-policy.xml -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Stack=true -Xms1073741824 -Xmx1073741824 -Djava.net.preferIPv4Stack=true -Dlog4j.configuration=beeline-log4j.properties -Dhadoop.security.logger=INFO,NullAppender org.apache.hadoop.util.RunJar /usr/lib/hive/lib/hive-beeline-1.1.0-cdh5.4.5.jar org.apache.hive.beeline.BeeLine -n user-p pwd-f /tmp/airflow_hiveop_FaJmDC/tmpFsFM4p -u jdbc:hive2://10.192.11.26:10000/default;auth=noSasl
```

The strange is that I  directly run the beeline command in airflow server terminal. It work. But it doese not work in airflow

**Comment by griffinqiu** [comment]
More error informations

```
[2015-08-25 07:22:31,042] {hive_hooks.py:83} INFO - beeline -n user -p pwd -f /tmp/airflow_hiveop_aaHpS2/tmpZYKIxL -u jdbc:hive2://10.192.11.26:10000/default;auth=noSasl
[2015-08-25 07:22:36,311] {hive_hooks.py:94} INFO - scan complete in 8ms
[2015-08-25 07:22:36,312] {hive_hooks.py:94} INFO - Connecting to jdbc:hive2://10.192.11.26:10000/default;auth=noSasl
[2015-08-25 07:43:41,743] {hive_hooks.py:94} INFO - 15/08/25 07:43:41 [main]: ERROR jdbc.HiveConnection: Error opening session
[2015-08-25 07:43:41,744] {hive_hooks.py:94} INFO - org.apache.thrift.transport.TTransportException
[2015-08-25 07:43:41,744] {hive_hooks.py:94} INFO - at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:132)
[2015-08-25 07:43:41,744] {hive_hooks.py:94} INFO - at org.apache.thrift.transport.TTransport.readAll(TTransport.java:86)
[2015-08-25 07:43:41,744] {hive_hooks.py:94} INFO - at org.apache.thrift.protocol.TBinaryProtocol.readStringBody(TBinaryProtocol.java:380)
[2015-08-25 07:43:41,744] {hive_hooks.py:94} INFO - at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:230)
[2015-08-25 07:43:41,745] {hive_hooks.py:94} INFO - at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:69)
[2015-08-25 07:43:41,745] {hive_hooks.py:94} INFO - at org.apache.hive.service.cli.thrift.TCLIService$Client.recv_OpenSession(TCLIService.java:156)
[2015-08-25 07:43:41,745] {hive_hooks.py:94} INFO - at org.apache.hive.service.cli.thrift.TCLIService$Client.OpenSession(TCLIService.java:143)
[2015-08-25 07:43:41,745] {hive_hooks.py:94} INFO - at org.apache.hive.jdbc.HiveConnection.openSession(HiveConnection.java:464)
[2015-08-25 07:43:41,745] {hive_hooks.py:94} INFO - at org.apache.hive.jdbc.HiveConnection.<init>(HiveConnection.java:181)
[2015-08-25 07:43:41,745] {hive_hooks.py:94} INFO - at org.apache.hive.jdbc.HiveDriver.connect(HiveDriver.java:105)
[2015-08-25 07:43:41,745] {hive_hooks.py:94} INFO - at java.sql.DriverManager.getConnection(DriverManager.java:571)
[2015-08-25 07:43:41,745] {hive_hooks.py:94} INFO - at java.sql.DriverManager.getConnection(DriverManager.java:187)
[2015-08-25 07:43:41,745] {hive_hooks.py:94} INFO - at org.apache.hive.beeline.DatabaseConnection.connect(DatabaseConnection.java:137)
[2015-08-25 07:43:41,746] {hive_hooks.py:94} INFO - at org.apache.hive.beeline.DatabaseConnection.getConnection(DatabaseConnection.java:178)
[2015-08-25 07:43:41,746] {hive_hooks.py:94} INFO - at org.apache.hive.beeline.Commands.connect(Commands.java:1115)
[2015-08-25 07:43:41,746] {hive_hooks.py:94} INFO - at org.apache.hive.beeline.Commands.connect(Commands.java:1036)
[2015-08-25 07:43:41,746] {hive_hooks.py:94} INFO - at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2015-08-25 07:43:41,746] {hive_hooks.py:94} INFO - at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[2015-08-25 07:43:41,746] {hive_hooks.py:94} INFO - at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2015-08-25 07:43:41,746] {hive_hooks.py:94} INFO - at java.lang.reflect.Method.invoke(Method.java:606)
[2015-08-25 07:43:41,746] {hive_hooks.py:94} INFO - at org.apache.hive.beeline.ReflectiveCommandHandler.execute(ReflectiveCommandHandler.java:52)
[2015-08-25 07:43:41,746] {hive_hooks.py:94} INFO - at org.apache.hive.beeline.BeeLine.dispatch(BeeLine.java:971)
[2015-08-25 07:43:41,746] {hive_hooks.py:94} INFO - at org.apache.hive.beeline.BeeLine.initArgs(BeeLine.java:703)
[2015-08-25 07:43:41,747] {hive_hooks.py:94} INFO - at org.apache.hive.beeline.BeeLine.begin(BeeLine.java:753)
[2015-08-25 07:43:41,747] {hive_hooks.py:94} INFO - at org.apache.hive.beeline.BeeLine.mainWithInputRedirection(BeeLine.java:480)
[2015-08-25 07:43:41,747] {hive_hooks.py:94} INFO - at org.apache.hive.beeline.BeeLine.main(BeeLine.java:463)
[2015-08-25 07:43:41,747] {hive_hooks.py:94} INFO - at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2015-08-25 07:43:41,747] {hive_hooks.py:94} INFO - at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[2015-08-25 07:43:41,747] {hive_hooks.py:94} INFO - at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2015-08-25 07:43:41,747] {hive_hooks.py:94} INFO - at java.lang.reflect.Method.invoke(Method.java:606)
[2015-08-25 07:43:41,747] {hive_hooks.py:94} INFO - at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
[2015-08-25 07:43:41,747] {hive_hooks.py:94} INFO - at org.apache.hadoop.util.RunJar.main(RunJar.java:136)
[2015-08-25 07:43:41,752] {hive_hooks.py:94} INFO - Error: Could not establish connection to jdbc:hive2://10.192.11.26:10000/default;auth=noSasl: null (state=08S01,code=0)
[2015-08-25 07:43:41,815] {hive_hooks.py:94} INFO - 0: jdbc:hive2://10.192.11.26 (closed)>
```

**Comment by mistercrunch** [comment]
This looks very specific to your environment. Airflow is upfront about the command it is running:
`beeline -n user -p pwd -f /tmp/airflow_hiveop_aaHpS2/tmpZYKIxL -u jdbc:hive2://10.192.11.26:10000/default;auth=noSasl`

I bet you if you run this in the same context (replace the tmp file by a simple file with a dummy hql statement in it) it won't work.

**Comment by griffinqiu** [comment]
That is the point, I had run the context. It work in terminal. But the same command not work in python code.

**Comment by griffinqiu** [comment]
It was very like the process was waiting for input in the python

**Comment by mistercrunch** [comment]
Well something has to be different between the context in your command line and the python `subprocess.Popen` call then. You'll understand that it's impossible for me to troubleshoot this remotely.

**Comment by griffinqiu** [comment]
I have found the reason. It is bcs the beeline mode do not support the PLAIN auth in Extra.

{"authMechanism": "PLAIN", "use_beeline": true}

**Comment by griffinqiu** [comment]
Could we support the PLAIN auth under use_beeline mode?

**Comment by mistercrunch** [comment]
Yes, but I can't develop it since I can't test it. It should be easy for you to add support for this.

**Comment by bolkedebruin** [comment]
You should be able to specify PLAIN with recent airflows. Please open Jira if this issue persists
