### ISSUE TITLE
Filter by try_number not working

### ISSUE THREAD

**Issue by erdos2n** [apache/airflow#30993]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

In Astro 7.3.0 (Airflow 2.5.1) when Browsing the `Task Instance` page and trying to filter by `try_number` (greater than) the web server throws an error - [Screen Shot 2023-05-01 at 10 46 26 AM](https://user-images.githubusercontent.com/26331746/235481057-99e8ba6f-9a43-4db5-a06c-e4d7bdc98f6b.png)

When checking the webserver logs the following error occurred

```
[2023-05-01T15:42:52.268+0000] {app.py:1741} ERROR - Exception on /taskinstance/list/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.9/site-packages/flask_appbuilder/security/decorators.py", line 133, in wraps
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/flask_appbuilder/views.py", line 554, in list
    widgets = self._list()
  File "/usr/local/lib/python3.9/site-packages/flask_appbuilder/baseviews.py", line 1164, in _list
    widgets = self._get_list_widget(
  File "/usr/local/lib/python3.9/site-packages/flask_appbuilder/baseviews.py", line 1063, in _get_list_widget
    count, lst = self.datamodel.query(
  File "/usr/local/lib/python3.9/site-packages/flask_appbuilder/models/sqla/interface.py", line 461, in query
    count = self.query_count(query, filters, select_columns)
  File "/usr/local/lib/python3.9/site-packages/flask_appbuilder/models/sqla/interface.py", line 382, in query_count
    return self._apply_inner_all(
  File "/usr/local/lib/python3.9/site-packages/flask_appbuilder/models/sqla/interface.py", line 368, in _apply_inner_all
    query = self.apply_filters(query, inner_filters)
  File "/usr/local/lib/python3.9/site-packages/flask_appbuilder/models/sqla/interface.py", line 223, in apply_filters
    return filters.apply_all(query)
  File "/usr/local/lib/python3.9/site-packages/flask_appbuilder/models/filters.py", line 300, in apply_all
    query = flt.apply(query, value)
  File "/usr/local/lib/python3.9/site-packages/flask_appbuilder/models/sqla/filters.py", line 169, in apply
    return query.filter(field > value)
TypeError: '>' not supported between instances of 'property' and 'int'
```

Things work with `try_number=2`.

### What you think should happen instead

Task Instances should be filtered by `try_number > 2`

### How to reproduce

Open Airflow
Browse by Task Instance
Filter by `try_number` greater than 2

### Operating System

Debian

### Versions of Apache Airflow Providers

N/A

### Deployment

Astronomer

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Assigned you.

**Comment by erdos2n** [comment]
After testing and reproducing, this issue is solved in later versions of Astro and Airflow.
Closing issue.

**Comment by potiuk** [comment]
cool. thanks for verifying and posting it here @erdos2n !
