### ISSUE TITLE
Passing 'execution_date' to 'TaskInstance.xcom_push()' is deprecated

### ISSUE THREAD

**Issue by chuxiangfeng** [apache/airflow#31052]
### Apache Airflow version

2.6.0

### What happened

after update airflow to 2.6.0,  when i manual  trigger task run, it always failed, i have no idea what happened

### How to reproduce

task will run success

### Operating System

PRETTY_NAME="Debian GNU/Linux 11 (bullseye)" NAME="Debian GNU/Linux" VERSION_ID="11" VERSION="11 (bullseye)" VERSION_CODENAME=bullseye ID=debian HOME_URL="https://www.debian.org/" SUPPORT_URL="https://www.debian.org/support" BUG_REPORT_URL="https://bugs.debian.org/"

### Versions of Apache Airflow Providers

apache-airflow==2.6.0
apache-airflow-providers-cncf-kubernetes==6.1.0
apache-airflow-providers-common-sql==1.4.0
apache-airflow-providers-dingding==3.1.0
apache-airflow-providers-elasticsearch==4.4.0
apache-airflow-providers-ftp==3.3.1
apache-airflow-providers-http==4.3.0
apache-airflow-providers-imap==3.1.1
apache-airflow-providers-mongo==3.1.1
apache-airflow-providers-mysql==5.0.0
apache-airflow-providers-postgres==5.4.0
apache-airflow-providers-redis==3.1.0
apache-airflow-providers-sqlite==3.3.2

### Deployment

Official Apache Airflow Helm Chart

### Anything else

logs：
[2023-05-04, 15:23:02 CST] {logging_mixin.py:149} WARNING - /home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py:1453 RemovedInAirflow3Warning: Passing 'execution_date' to 'TaskInstance.xcom_push()' is deprecated.
[2023-05-04, 15:23:02 CST] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1430, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1583, in _execute_task_with_callbacks
    self.task.post_execute(context=context, result=result)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/lineage/__init__.py", line 84, in wrapper
    context, key=PIPELINE_OUTLETS, value=outlets, execution_date=context["ti"].execution_date
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1453, in xcom_push
    context["ti"].xcom_push(key=key, value=value, execution_date=execution_date)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2384, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 73, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 243, in set
    map_index=map_index,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 632, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/local/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 104, in encode
    return super().encode(o)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 91, in default
    return serialize(o)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/serialization/serde.py", line 167, in serialize
    data = attr.asdict(cast(attr.AttrsInstance, o), recurse=True, filter=lambda a, v: a.init)
AttributeError: module 'attr' has no attribute 'AttrsInstance'
[2023-05-04, 15:23:02 CST] {taskinstance.py:1373} INFO - Marking task as UP_FOR_RETRY. dag_id=d_c_dwm_comphistory_text_item, task_id=t_c_dwm_comphistory_text_item_request, execution_date=20230504T072247, start_date=20230504T072249, end_date=20230504T072302
[2023-05-04, 15:23:02 CST] {standard_task_runner.py:109} ERROR - Failed to execute job 25828 for task t_c_dwm_comphistory_text_item_request (module 'attr' has no attribute 'AttrsInstance'; 46697)
[2023-05-04, 15:23:02 CST] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-05-04, 15:23:02 CST] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by chuxiangfeng** [comment]
update attrs dependency to resolve it
