### ISSUE TITLE
BigQueryInsertJobOperator marked successful incorrectly

### ISSUE THREAD

**Issue by set92** [apache/airflow#31147]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

It is true that the apache-airflow-providers-google version is 6.8.0 (apr 2022), and Airflow 2.4.2, so maybe updating the packages could fix the error.

The error happened with a long query (~ 3h), in which the task marked as successfully before the task really finished. In the logs we can see both started almost at the same time, but airflow thought it was already finished at 7:17 UTC, but Bigquery didn't really finish until 8:05 UTC. The query was the first step of a transactional query, in which it calculates some st_intersetcs and cross join between 2 tables.

The **log from the task** in Airflow:
```
*** Reading remote log from s3://.../dag_id=dag_name/run_id=manual__2023-05-03T14:36:11+00:00/task_id=task_1_name.insert_into_prod.insert_data_and_update_valid_dates/attempt=1.log.
[2023-05-04, 05:15:39 UTC] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_name.task_1_name.insert_into_prod.insert_data_and_update_valid_dates manual__2023-05-03T14:36:11+00:00 [queued]>
[2023-05-04, 05:15:40 UTC] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_name.task_1_name.insert_into_prod.insert_data_and_update_valid_dates manual__2023-05-03T14:36:11+00:00 [queued]>
[2023-05-04, 05:15:40 UTC] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-05-04, 05:15:40 UTC] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-05-04, 05:15:40 UTC] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-05-04, 05:15:40 UTC] {taskinstance.py:1383} INFO - Executing <Task(BigQueryInsertParametrizedJobOperator): task_1_name.insert_into_prod.insert_data_and_update_valid_dates> on 2023-05-03 14:36:11+00:00
[2023-05-04, 05:15:40 UTC] {standard_task_runner.py:55} INFO - Started process 23 to run task
[2023-05-04, 05:15:40 UTC] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_name', 'task_1_name.insert_into_prod.insert_data_and_update_valid_dates', 'manual__2023-05-03T14:36:11+00:00', '--job-id', '78337', '--raw', '--subdir', 'DAGS_FOLDER/master_dag_factory_dag_name.py', '--cfg-path', '/tmp/tmppm9tmkfj']
[2023-05-04, 05:15:40 UTC] {standard_task_runner.py:83} INFO - Job 78337: Subtask task_1_name.insert_into_prod.insert_data_and_update_valid_dates
[2023-05-04, 05:15:40 UTC] {task_command.py:376} INFO - Running <TaskInstance: dag_name.task_1_name.insert_into_prod.insert_data_and_update_valid_dates manual__2023-05-03T14:36:11+00:00 [running]> on host pod-c8ddc6bb711e4d1ab5f1a9feb9a16501
[2023-05-04, 05:15:40 UTC] {taskinstance.py:1590} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_ID=dag_name
AIRFLOW_CTX_TASK_ID=task_1_name.insert_into_prod.insert_data_and_update_valid_dates
AIRFLOW_CTX_EXECUTION_DATE=2023-05-03T14:36:11+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-03T14:36:11+00:00
[2023-05-04, 05:15:42 UTC] {base.py:71} INFO - Using connection ID 'default_conn' for task execution.
[2023-05-04, 05:15:42 UTC] {bigquery.py:1554} INFO - Inserting job ***_transaction_dag_name_task_1_name_insert_into_prod_generate_job_id_1683124743200_1_472eb3e9b7aabcbdab449fbf7ca0ca0b
[2023-05-04, 07:16:41 UTC] {taskinstance.py:1401} INFO - Marking task as SUCCESS. dag_id=dag_name, task_id=task_1_name.insert_into_prod.insert_data_and_update_valid_dates, execution_date=20230503T143611, start_date=20230504T051539, end_date=20230504T071641
[2023-05-04, 07:16:44 UTC] {local_task_job.py:164} INFO - Task exited with return code 0
```

**Bigquery Job information**
```
Job ID -- XXX
User -- XXX
Location -- EU
Creation time -- May 4, 2023, 7:15:44 AM UTC+2
Start time -- May 4, 2023, 7:15:45 AM UTC+2
End time -- May 4, 2023, 10:05:20 AM UTC+2
Duration -- 2 hr 49 min
Bytes processed -- 236.05 GB
Bytes billed -- 236.05 GB
Job priority -- INTERACTIVE
Use legacy SQL -- false
Destination table -- XXX
```

The code used to run the operator:
```python
        config = {
            "query": {
                "query": transaction_query,
                "useLegacySql": BigQueryToProdValues.USE_LEGACY_SQL,
                "allowLargeResults": BigQueryToProdValues.ALLOW_LARGE_RESULTS,
                "location": "eu",
            }
        }

        if self.query_params:
            config["query"]["queryParameters"] = self.query_params

        insert_data = BigQueryInsertParametrizedJobOperator(
            task_id=CommonTaskIds.INSERT_DATA_AND_UPDATE_VALID_DATES,
            task_group=self.task_group,
            gcp_conn_id=self.gcp_conn_id,
            force_rerun=False,
            reattach_states={"PENDING", "RUNNING", "DONE"},
            job_id=kwargs.pop("job_id"),
            configuration=config,
            pool=self.pool,
            trigger_rule=TriggerRule.NONE_FAILED_MIN_ONE_SUCCESS,
            **kwargs,
        )

        return insert_data, insert_data


class BigQueryInsertParametrizedJobOperator(BigQueryInsertJobOperator):
    def execute(self, context):
        query_params = self.configuration.get("query", {}).get("queryParameters", None)
        if query_params is not None:
            self.configuration["query"]["queryParameters"] = ast.literal_eval(query_params)
        super().execute(context)
```

### What you think should happen instead

I think the task should run until the task is finished, since in this version, there wasn't a deferrable parameter, but maybe it didn't work quite well, and it got detached at some moment, and thought it was completed because of something I'm not seeing.

### How to reproduce

Didn't try to test it because it took too long to run. My idea was to ask if you knew about this or had some theory to test it further, and if not, upgrade `apache-airflow-providers-google` to 10.0.0 and hope it doesn't happen more, or only happens in really long task runs.

### Operating System

Ubuntu 20.04

### Versions of Apache Airflow Providers

apache-airflow-providers-amazon==6.0.0
apache-airflow-providers-cncf-kubernetes==4.4.0
apache-airflow-providers-common-sql==1.2.0
apache-airflow-providers-ftp==3.1.0
apache-airflow-providers-google==6.8.0
apache-airflow-providers-http==4.0.0
apache-airflow-providers-imap==3.0.0
apache-airflow-providers-postgres==5.2.2
apache-airflow-providers-sendgrid==3.0.0
apache-airflow-providers-slack==6.0.0
apache-airflow-providers-sqlite==3.2.1

### Deployment

Other 3rd-party Helm chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by set92** [comment]
**Second time**
We have 4 DAGs almost identical, they use the same code, and only differs the ingested data. And the odd thing is that in the last complete run of each DAG, the error has only happened twice in one of them. Although we are uncertain if it could have happened in other partial runs since we don't have a check for it. In the complete run we noticed it because they were runs from zero, so the tables didn't exist, and when the step after the error tried to get the data said that the table was empty.

But well, the second time happened in a similar situation, calculate some areas, then aggregate them to different sources, and finally getting the latest of them. My hypothesis was that could be related to the run time of the task but in this case the error happened around 30 and 40 minutes, so probably is not the case.

So, the bug happened while aggregating, same as before, the log of it is:
```
*** Reading remote log from s3://.../dag_id=dag_name/run_id=manual__2023-05-03T14:36:11+00:00/task_id=task_2_name.insert_into_prod.insert_data_and_update_valid_dates/attempt=1.log.
[2023-05-06, 06:09:16 UTC] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_name.task_2_name.insert_into_prod.insert_data_and_update_valid_dates manual__2023-05-03T14:36:11+00:00 [queued]>
[2023-05-06, 06:09:16 UTC] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_name.task_2_name.insert_into_prod.insert_data_and_update_valid_dates manual__2023-05-03T14:36:11+00:00 [queued]>
[2023-05-06, 06:09:16 UTC] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-05-06, 06:09:16 UTC] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-05-06, 06:09:16 UTC] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-05-06, 06:09:16 UTC] {taskinstance.py:1383} INFO - Executing <Task(BigQueryInsertParametrizedJobOperator): task_2_name.insert_into_prod.insert_data_and_update_valid_dates> on 2023-05-03 14:36:11+00:00
[2023-05-06, 06:09:16 UTC] {standard_task_runner.py:55} INFO - Started process 23 to run task
[2023-05-06, 06:09:16 UTC] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_name', 'task_2_name.insert_into_prod.insert_data_and_update_valid_dates', 'manual__2023-05-03T14:36:11+00:00', '--job-id', '87667', '--raw', '--subdir', 'DAGS_FOLDER/master_dag_factory_dag_name.py', '--cfg-path', '/tmp/tmpauj2z6j9']
[2023-05-06, 06:09:16 UTC] {standard_task_runner.py:83} INFO - Job 87667: Subtask task_2_name.insert_into_prod.insert_data_and_update_valid_dates
[2023-05-06, 06:09:16 UTC] {task_command.py:376} INFO - Running <TaskInstance: dag_name.task_2_name.insert_into_prod.insert_data_and_update_valid_dates manual__2023-05-03T14:36:11+00:00 [running]> on host pod-179162d8c29a4248afac2116a5114436
[2023-05-06, 06:09:16 UTC] {taskinstance.py:1590} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_ID=dag_name
AIRFLOW_CTX_TASK_ID=task_2_name.insert_into_prod.insert_data_and_update_valid_dates
AIRFLOW_CTX_EXECUTION_DATE=2023-05-03T14:36:11+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-03T14:36:11+00:00
[2023-05-06, 06:09:16 UTC] {base.py:71} INFO - Using connection ID 'default_conn' for task execution.
[2023-05-06, 06:09:17 UTC] {bigquery.py:1554} INFO - Inserting job ***_transaction_dag_name_task_2_name_insert_into_prod_generate_job_id_1683124743200_1_33b432ee7e08c19795cea72799e8ab23
[2023-05-06, 06:33:11 UTC] {taskinstance.py:1401} INFO - Marking task as SUCCESS. dag_id=dag_name, task_id=task_2_name.insert_into_prod.insert_data_and_update_valid_dates, execution_date=20230503T143611, start_date=20230506T060916, end_date=20230506T063311
[2023-05-06, 06:33:13 UTC] {local_task_job.py:164} INFO - Task exited with return code 0
```

(Don't think is important, but just in case) And in the next task group it failed with the following log:
```
*** Reading remote log from s3://.../dag_id=dag_name/run_id=manual__2023-05-03T14:36:11+00:00/task_id=task_3_name.check_schema_and_input_exist_and_transfo_version/attempt=1.log.
[2023-05-06, 06:35:38 UTC] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_name.task_3_name.check_schema_and_input_exist_and_transfo_version manual__2023-05-03T14:36:11+00:00 [queued]>
[2023-05-06, 06:35:39 UTC] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_name.task_3_name.check_schema_and_input_exist_and_transfo_version manual__2023-05-03T14:36:11+00:00 [queued]>
[2023-05-06, 06:35:39 UTC] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-05-06, 06:35:39 UTC] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-05-06, 06:35:39 UTC] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-05-06, 06:35:39 UTC] {taskinstance.py:1383} INFO - Executing <Task(BranchPythonOperator): task_3_name.check_schema_and_input_exist_and_transfo_version> on 2023-05-03 14:36:11+00:00
[2023-05-06, 06:35:39 UTC] {standard_task_runner.py:55} INFO - Started process 23 to run task
[2023-05-06, 06:35:39 UTC] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_name', 'task_3_name.check_schema_and_input_exist_and_transfo_version', 'manual__2023-05-03T14:36:11+00:00', '--job-id', '87710', '--raw', '--subdir', 'DAGS_FOLDER/master_dag_factory_dag_name.py', '--cfg-path', '/tmp/tmpsjrb6rp_']
[2023-05-06, 06:35:39 UTC] {standard_task_runner.py:83} INFO - Job 87710: Subtask task_3_name.check_schema_and_input_exist_and_transfo_version
[2023-05-06, 06:35:39 UTC] {task_command.py:376} INFO - Running <TaskInstance: dag_name.task_3_name.check_schema_and_input_exist_and_transfo_version manual__2023-05-03T14:36:11+00:00 [running]> on host pod-b0e87574e38c49f0aa5a6fc402d02626
[2023-05-06, 06:35:39 UTC] {taskinstance.py:1590} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_ID=dag_name
AIRFLOW_CTX_TASK_ID=task_3_name.check_schema_and_input_exist_and_transfo_version
AIRFLOW_CTX_EXECUTION_DATE=2023-05-03T14:36:11+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-03T14:36:11+00:00
[2023-05-06, 06:35:39 UTC] {base.py:71} INFO - Using connection ID 'default_conn' for task execution.
[2023-05-06, 06:35:39 UTC] {logging_mixin.py:120} WARNING - /opt/company_name/project_name/.venv/lib/python3.9/site-packages/***/providers/google/cloud/hooks/bigquery.py:131 DeprecationWarning: This method will be deprecated. Please use `BigQueryHook.get_client` method
[2023-05-06, 06:35:40 UTC] {logging_mixin.py:120} WARNING - /opt/company_name/project_name/.venv/lib/python3.9/site-packages/***/providers/google/cloud/hooks/bigquery.py:2057 DeprecationWarning: This method is deprecated. Please use `BigQueryHook.insert_job` method.
[2023-05-06, 06:35:40 UTC] {bigquery.py:1554} INFO - Inserting job ***_1683354940069838_0d68b9a31335d5bf94fdaa02926ff943
[2023-05-06, 06:35:41 UTC] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/company_name/project_name/.venv/lib/python3.9/site-packages/airflow/operators/python.py", line 211, in execute
    branch = super().execute(context)
  File "/opt/company_name/project_name/.venv/lib/python3.9/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/opt/company_name/project_name/.venv/lib/python3.9/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/company_name/project_name/project_name/transformations/bq_run_query/actions.py", line 95, in branch_input_exist_and_more_recent
    is_new_data = bq_utils.check_input_exist_and_more_recent(input_tables=input_tables, output_table=output_table, bq_environment=bq_environment)
  File "/opt/company_name/project_name/project_name/externals/bq_utils.py", line 285, in check_input_exist_and_more_recent
    raise EmptyBqTable(f"All tables {input_tables} are empty")
project_name.exceptions.EmptyBqTable: All tables [...] are empty
[2023-05-06, 06:35:41 UTC] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=dag_name, task_id=task_3_name.check_schema_and_input_exist_and_transfo_version, execution_date=20230503T143611, start_date=20230506T063538, end_date=20230506T063541
```

And the same, in Bigquery the end timestamp is later than what Airflow logs says has finished.
**Bigquery Job information**
```
Job ID -- XXX
User -- XXX
Location -- EU
Creation time -- May 6, 2023, 8:09:17 AM UTC+2
Start time -- May 6, 2023, 8:09:17 AM UTC+2
End time -- May 6, 2023, 8:48:53 AM UTC+2
Duration -- 39 min 36 sec
Bytes processed -- 648.57 GB
Bytes billed -- 648.57 GB
Job priority -- INTERACTIVE
Use legacy SQL -- false
```

A coworker of mine was checking the Google logs to see if he could find something else, but he only saw that the last `method: jobservice.getqueryresults` was at the same time than Airflow marked the task as success.
log:
```
{
  "protoPayload": {
    "@type": "type.googleapis.com/google.cloud.audit.AuditLog",
    "status": {},
    "authenticationInfo": {
      "principalEmail": "account_name"
    },
    "requestMetadata": {
      "callerIp": "3.248.171.10",
      "callerSuppliedUserAgent": "gl-python/3.9.16 grpc/1.49.1 gax/1.33.2 gapic/2.34.4 gccl/2.34.4,gzip(gfe)",
      "requestAttributes": {},
      "destinationAttributes": {}
    },
    "serviceName": "bigquery.googleapis.com",
    "methodName": "jobservice.getqueryresults",
    "authorizationInfo": [
      {
        "resource": "projects/project_id_name",
        "permission": "bigquery.jobs.create",
        "granted": true,
        "resourceAttributes": {}
      }
    ],
    "resourceName": "projects/project_id_name/queries/airflow_transaction_dag_name_task_2_name_insert_into_prod_generate_job_id_1683124743200_1_33b432ee7e08c19795cea72799e8ab23",
    "serviceData": {
      "@type": "type.googleapis.com/google.cloud.bigquery.logging.v1.AuditData",
      "jobGetQueryResultsRequest": {},
      "jobGetQueryResultsResponse": {
        "job": {
          "jobName": {
            "projectId": "project_id_name",
            "jobId": "airflow_transaction_dag_name_task_2_name_insert_into_prod_generate_job_id_1683124743200_1_33b432ee7e08c19795cea72799e8ab23",
            "location": "EU"
          },
          "jobConfiguration": {
            "query": {
              "query": " XXX ",
              "destinationTable": {},
              "createDisposition": "CREATE_IF_NEEDED",
              "writeDisposition": "WRITE_EMPTY",
              "defaultDataset": {},
              "queryPriority": "QUERY_INTERACTIVE",
              "statementType": "SCRIPT"
            }
          },
          "jobStatus": {
            "state": "RUNNING",
            "error": {}
          },
          "jobStatistics": {
            "createTime": "2023-05-06T06:09:17.329Z",
            "startTime": "2023-05-06T06:09:17.445Z"
          }
        }
      }
    }
  },
  "insertId": "2s0ay2d16p2",
  "resource": {
    "type": "bigquery_resource",
    "labels": {
      "project_id": "project_id_name"
    }
  },
  "timestamp": "2023-05-06T06:33:11.276494Z",
  "severity": "INFO",
  "logName": "projects/project_id_name/logs/cloudaudit.googleapis.com%2Fdata_access",
  "receiveTimestamp": "2023-05-06T06:33:11.416461299Z"
}
```


And the next log I think is Bigquery moving the calculate data to the table, but then why in this specific case Airflow didn't wait for this log? Because I checked other tasks that didn't return errors, and they had the same logs.
```
{
  "protoPayload": {
    "@type": "type.googleapis.com/google.cloud.audit.AuditLog",
    "status": {},
    "authenticationInfo": {
      "principalEmail": "account_name"
    },
    "requestMetadata": {
      "callerIp": "3.248.171.10",
      "callerSuppliedUserAgent": "gl-python/3.9.16 grpc/1.49.1 gax/1.33.2 gapic/2.34.4 gccl/2.34.4,gzip(gfe)"
    },
    "serviceName": "bigquery.googleapis.com",
    "methodName": "google.cloud.bigquery.v2.JobService.InsertJob",
    "authorizationInfo": [
      {
        "resource": "projects/project_id_name",
        "permission": "bigquery.jobs.create",
        "granted": true
      }
    ],
    "resourceName": "projects/project_id_name/jobs/script_job_9a0f77016c0849a88e43481e139440f6_1",
    "metadata": {
      "jobChange": {
        "after": "DONE",
        "job": {
          "jobName": "projects/project_id_name/jobs/script_job_9a0f77016c0849a88e43481e139440f6_1",
          "jobConfig": {
            "type": "QUERY",
            "queryConfig": {
              "query": "XXX",
              "destinationTable": "projects/project_name/datasets/dataset/tables/table_name",
              "createDisposition": "CREATE_IF_NEEDED",
              "writeDisposition": "WRITE_EMPTY",
              "priority": "QUERY_INTERACTIVE",
              "statementType": "INSERT"
            }
          },
          "jobStatus": {
            "jobState": "DONE"
          },
          "jobStats": {
            "createTime": "2023-05-06T06:09:17.925Z",
            "startTime": "2023-05-06T06:09:18.092Z",
            "endTime": "2023-05-06T06:48:50.824Z",
            "queryStats": {
              "totalProcessedBytes": "695081952951",
              "totalBilledBytes": "695082156032",
              "billingTier": 1,
              "referencedTables": [
                "projects/project_name/datasets/dataset/tables/table_name1",
                "projects/project_name/datasets/dataset/tables/table_name2",
                "projects/project_name/datasets/dataset/tables/table_name3",
                "projects/project_name/datasets/dataset/tables/table_name4",
              ],
              "outputRowCount": "82170898"
            },
            "totalSlotMs": "1461958311",
            "parentJobName": "projects/project_id_name/jobs/airflow_transaction_dag_name_task_2_name_insert_into_prod_generate_job_id_1683124743200_1_33b432ee7e08c19795cea72799e8ab23"
          }
        }
      },
      "@type": "type.googleapis.com/google.cloud.audit.BigQueryAuditMetadata"
    }
  },
  "insertId": "bnrb0od7eea",
  "resource": {
    "type": "bigquery_project",
    "labels": {
      "project_id": "project_id_name",
      "location": "EU"
    }
  },
  "timestamp": "2023-05-06T06:48:50.876369Z",
  "severity": "INFO",
  "logName": "projects/project_id_name/logs/cloudaudit.googleapis.com%2Fdata_access",
  "operation": {
    "id": "1683353357925-project_id_name:script_job_9a0f77016c0849a88e43481e139440f6_1",
    "producer": "bigquery.googleapis.com",
    "last": true
  },
  "receiveTimestamp": "2023-05-06T06:48:51.692700328Z"
}
```

**Comment by phanikumv** [comment]
Hi @set92 - do you have a minimal reproducible example which we can try in order to test this behaviour?

cc @potiuk

**Comment by set92** [comment]
Regretfully no, that's why I decided to open [a discussion](https://github.com/apache/airflow/discussions/31055) before this issue. 

Since we had to merge some PRs in our company, we were going to try launching the same DAG that had the problems and hope for the problem to arise again. Also, we thought of having a task at the start of every task group that checks if the state of its parents is not DONE to stop the DAG.

**Comment by rohan472000** [comment]
One possible solution is to modify the operator to wait for the BigQuery job to complete before marking the task as successful. You can achieve this by checking the status of the BigQuery job periodically and only marking the task as successful when the job is done.

You can modify the `BigQueryInsertParametrizedJobOperator` to wait for the job to complete:

        from google.cloud import bigquery
        
        class BigQueryInsertParametrizedJobOperator(BigQueryInsertJobOperator):
            def execute(self, context):
                query_params = self.configuration.get("query", {}).get("queryParameters", None)
                if query_params is not None:
                    self.configuration["query"]["queryParameters"] = ast.literal_eval(query_params)
        
                job = super().execute(context)
        
                client = bigquery.Client()
                while job.state != "DONE":
                    job = client.get_job(job.job_id, location=self.configuration["query"]["location"])
                    time.sleep(5)  # Wait for 5 seconds before checking again or modify according to your need
        
                if job.errors:
                    raise Exception("BigQuery job failed with errors: {}".format(job.errors))
        
                return job

**Comment by hussein-awala** [comment]
By reading the task log, we can say that there there could be a default timeout of 2 hours in the BigQuery client, which is not mentioned in the client doc.
Since your job duration is less than 3 hours, can you try to set the result_timeout parameter to 3h?
```python
        insert_data = BigQueryInsertParametrizedJobOperator(
            task_id=CommonTaskIds.INSERT_DATA_AND_UPDATE_VALID_DATES,
            task_group=self.task_group,
            gcp_conn_id=self.gcp_conn_id,
            force_rerun=False,
            reattach_states={"PENDING", "RUNNING", "DONE"},
            job_id=kwargs.pop("job_id"),
            configuration=config,
            pool=self.pool,
            trigger_rule=TriggerRule.NONE_FAILED_MIN_ONE_SUCCESS,
            result_timeout=3*60*60,
            **kwargs,
        )
``` 
An alternative solution can be providing a retry strategy through the parameter `result_retry`, where the default strategy doesn't retry the query for timeout exception.
Source code from GCP doc:
```python
def _should_retry(exc):
    """Predicate for determining when to retry.

    We retry if and only if the 'reason' is 'backendError'
    or 'rateLimitExceeded'.
    """
    if not hasattr(exc, 'errors'):
        return False
    if len(exc.errors) == 0:
        return False
    reason = exc.errors[0]['reason']
    return reason == 'backendError' or reason == 'rateLimitExceeded'


DEFAULT_RETRY = retry.Retry(predicate=_should_retry)
```
