### ISSUE TITLE
Airflow migrations taking too long

### ISSUE THREAD

**Issue by arjunanan6** [apache/airflow#32674]
### Apache Airflow version

2.6.3

### What happened

Since version 2.6.0, I have noticed that the run-airflow-migrations job takes extremely long - in some cases 9 minutes when we rebuild our image and deploy.  In the worst of cases, the pod is restarted due to having hit our timeout of 10 min. 

It has taken about 2-3 minutes in the past, and our DAG bag has not grown by much (perhaps approx 30 DAGs since the 2-3 min deployment). 

I cannot see anything out of the usual from the logs that would be causing this too. This is the entire output from the most recent run that took about 8 minutes to complete. We are aware of the errors listed in here, but this has been the same even previously, and has not caused the migrations to take so long. 

```DB: postgresql://psqladmin%40airflow-ps-db-prod:***@airflow-prod-pgbouncer.airflow-prod-ns:6543/airflow-prod-metadata?sslmode=disable
Performing upgrade with database postgresql://psqladmin%40airflow-ps-db-prod:***@airflow-prod-pgbouncer.airflow-prod-ns:6543/airflow-prod-metadata?sslmode=disable
[2023-07-18T14:25:45.590+0000] {migration.py:213} INFO - Context impl PostgresqlImpl.
[2023-07-18T14:25:45.591+0000] {migration.py:216} INFO - Will assume transactional DDL.
[2023-07-18T14:25:45.938+0000] {db.py:1590} INFO - Creating tables
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
ERROR [airflow.models.dagbag.DagBag] Exception bagging dag: SAP_BANK_JPM_CAMT_D
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 500, in _bag_dag
    raise AirflowDagDuplicatedIdException(
airflow.exceptions.AirflowDagDuplicatedIdException: Ignoring DAG SAP_BANK_JPM_CAMT_D from /opt/airflow/dags/airflow-dags-sap/SAP_BANK/sap_bank_jpm_camt_d.py - also found in /opt/airflow/dags/airflow-dags-sap/SAP_BANK/sap_bank_jpm_camt_d_SIMU.py
ERROR [airflow.models.dagbag.DagBag] Failed to bag_dag: /opt/airflow/dags/airflow-dags-sap/SAP_BANK/sap_bank_jpm_camt_d.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 445, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 462, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 500, in _bag_dag
    raise AirflowDagDuplicatedIdException(
airflow.exceptions.AirflowDagDuplicatedIdException: Ignoring DAG SAP_BANK_JPM_CAMT_D from /opt/airflow/dags/airflow-dags-sap/SAP_BANK/sap_bank_jpm_camt_d.py - also found in /opt/airflow/dags/airflow-dags-sap/SAP_BANK/sap_bank_jpm_camt_d_SIMU.py
ERROR [airflow.models.dagbag.DagBag] Exception bagging dag: SAP_BANK_NOR_CAMT_D
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 500, in _bag_dag
    raise AirflowDagDuplicatedIdException(
airflow.exceptions.AirflowDagDuplicatedIdException: Ignoring DAG SAP_BANK_NOR_CAMT_D from /opt/airflow/dags/airflow-dags-sap/SAP_BANK/sap_bank_nor_camt_d.py - also found in /opt/airflow/dags/airflow-dags-sap/SAP_BANK/sap_bank_nor_camt_d_SIMU.py
ERROR [airflow.models.dagbag.DagBag] Failed to bag_dag: /opt/airflow/dags/airflow-dags-sap/SAP_BANK/sap_bank_nor_camt_d.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 445, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 462, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 500, in _bag_dag
    raise AirflowDagDuplicatedIdException(
airflow.exceptions.AirflowDagDuplicatedIdException: Ignoring DAG SAP_BANK_NOR_CAMT_D from /opt/airflow/dags/airflow-dags-sap/SAP_BANK/sap_bank_nor_camt_d.py - also found in /opt/airflow/dags/airflow-dags-sap/SAP_BANK/sap_bank_nor_camt_d_SIMU.py
ERROR [airflow.models.dagbag.DagBag] Exception bagging dag: SAP_BANK_DAB_CAMT_D
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 500, in _bag_dag
    raise AirflowDagDuplicatedIdException(
airflow.exceptions.AirflowDagDuplicatedIdException: Ignoring DAG SAP_BANK_DAB_CAMT_D from /opt/airflow/dags/airflow-dags-sap/SAP_BANK/sap_bank_dab_camt_d_SIMU.py - also found in /opt/airflow/dags/airflow-dags-sap/SAP_BANK/sap_bank_dab_camt_d.py
ERROR [airflow.models.dagbag.DagBag] Failed to bag_dag: /opt/airflow/dags/airflow-dags-sap/SAP_BANK/sap_bank_dab_camt_d_SIMU.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 445, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 462, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 500, in _bag_dag
    raise AirflowDagDuplicatedIdException(
airflow.exceptions.AirflowDagDuplicatedIdException: Ignoring DAG SAP_BANK_DAB_CAMT_D from /opt/airflow/dags/airflow-dags-sap/SAP_BANK/sap_bank_dab_camt_d_SIMU.py - also found in /opt/airflow/dags/airflow-dags-sap/SAP_BANK/sap_bank_dab_camt_d.py
/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/oracle/hooks/oracle.py:31 RemovedInAirflow3Warning: This module is deprecated. Please use `airflow.providers.common.sql.hooks.sql`.
ERROR [airflow.models.dagbag.DagBag] Exception bagging dag: ANALYTICS_B2B_A_faktura_all_power_automatic
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 500, in _bag_dag
    raise AirflowDagDuplicatedIdException(
airflow.exceptions.AirflowDagDuplicatedIdException: Ignoring DAG ANALYTICS_B2B_A_faktura_all_power_automatic from /opt/airflow/dags/airflow-dags-analytics/STANDALONE_DAGS/ANALYTICSP_B2B_A_faktura_all_power_automatic.py - also found in /opt/airflow/dags/airflow-dags-analytics/STANDALONE_DAGS/ANALYTICSP_B2B_Customer_data_til_Midas_daily_SE.py
ERROR [airflow.models.dagbag.DagBag] Failed to bag_dag: /opt/airflow/dags/airflow-dags-analytics/STANDALONE_DAGS/ANALYTICSP_B2B_A_faktura_all_power_automatic.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 445, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 462, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 500, in _bag_dag
    raise AirflowDagDuplicatedIdException(
airflow.exceptions.AirflowDagDuplicatedIdException: Ignoring DAG ANALYTICS_B2B_A_faktura_all_power_automatic from /opt/airflow/dags/airflow-dags-analytics/STANDALONE_DAGS/ANALYTICSP_B2B_A_faktura_all_power_automatic.py - also found in /opt/airflow/dags/airflow-dags-analytics/STANDALONE_DAGS/ANALYTICSP_B2B_Customer_data_til_Midas_daily_SE.py
ERROR [airflow.models.dagbag.DagBag] Failed to import: /opt/airflow/dags/airflow-dags-analytics/LINKED_DAGS/DELETE_DAG_ANALYTICSP_B2B_SAP_DATA_PO1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-dags-analytics/LINKED_DAGS/DELETE_DAG_ANALYTICSP_B2B_SAP_DATA_PO1.py", line 63, in <module>
    sap_data_dp1 >> [trigger_crm_tables_last_updated, trigger_b2b_customer_data_til_midas_daily_se, trigger_b2b_forbrug_eyc, trigger_gasdw_01_graddage]
NameError: name 'trigger_gasdw_01_graddage' is not defined
Upgrades done
```

Any idea what we can do to improve the migrations run time? We have not changed any parameters in regards to the migration, for example: migrationsWaitTimeout is still 60s. 

### How to reproduce

N/A

### Operating System

Debian GNU/Linux

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

We are using the official helm chart v1.9.0 deployed on AKS.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by hussein-awala** [comment]
> our DAG bag has not grown by much (perhaps approx 30 DAGs since the 2-3 min deployment).

What about the dag runs/tasks history? did you cleanup your database since the last time you used the upgrade command?

Do you have any worker/scheduler/triggerer running during the migration? if so, they could lock some rows in different tables which blocks the migration

**Comment by arjunanan6** [comment]
No, a cleanup has not been done since a while - mainly because we want to preserve the task run history. The task run history must be quite big now, I can check exactly what the state is shortly. 

>Do you have any worker/scheduler/triggerer running during the migration? if so, they could lock some rows in different tables which blocks the migration

Yes, we do. There is an active airflow deployment in place that is operating normally and a helm upgrade is only done in 2 situations: a) We introduce a new dag/fixes to existing DAGs, or b) An airflow version upgrade. I looked quickly at our pgbouncer logs to see if there was anything significant going on around the time of the upgrade but did not immediately spot anything. 

I suppose a bandaid fix would be to set these two to false:
webserver.waitForMigrations.enabled
scheduler.waitForMigrations.enabled

But this would only hide the problem.

**Comment by arjunanan6** [comment]
Just looked at the size of the tables. The biggest ones are:
log: 853MB
task_instance: 744MB
dag_run: 479MB
job: 232MB
session: 200MB

**Comment by arjunanan6** [comment]
@hussein-awala I think you are completely right that this could be down to the size of our tables. We have a 'dev' environment that's fairly recent, and out there, migrations take barely a minute. I'll do some cleanup and come back with the results.

**Comment by arjunanan6** [comment]
So, the cleanup is done and the tables have dropped to a reasonable size with data only from 30 days back. However, the migrations job is still taking over 8 minutes to complete. Any other ideas that I could try?

**Comment by arjunanan6** [comment]
I also tried running airflow db upgrade in verbose mode to see what is going on there, and it does not give much info apart from the fact that the pool to do the upgrades was set up at 2023-07-20T08:34 and the upgrades were done at 2023-07-20T08:42 (approx 8 min):

```
Performing upgrade with database postgresql://<redacted>
[2023-07-20T08:33:52.589+0000] {serde.py:319} DEBUG - registering decimal.Decimal for serialization
[2023-07-20T08:33:52.590+0000] {serde.py:326} DEBUG - registering decimal.Decimal for deserialization
[2023-07-20T08:33:52.590+0000] {serde.py:319} DEBUG - registering builtins.frozenset for serialization
[2023-07-20T08:33:52.590+0000] {serde.py:319} DEBUG - registering builtins.set for serialization
[2023-07-20T08:33:52.590+0000] {serde.py:319} DEBUG - registering builtins.tuple for serialization
[2023-07-20T08:33:52.590+0000] {serde.py:326} DEBUG - registering builtins.frozenset for deserialization
[2023-07-20T08:33:52.590+0000] {serde.py:326} DEBUG - registering builtins.set for deserialization
[2023-07-20T08:33:52.591+0000] {serde.py:326} DEBUG - registering builtins.tuple for deserialization
[2023-07-20T08:33:52.591+0000] {serde.py:334} DEBUG - registering builtins.frozenset for stringifying
[2023-07-20T08:33:52.591+0000] {serde.py:334} DEBUG - registering builtins.set for stringifying
[2023-07-20T08:33:52.591+0000] {serde.py:334} DEBUG - registering builtins.tuple for stringifying
[2023-07-20T08:33:52.591+0000] {serde.py:319} DEBUG - registering datetime.date for serialization
[2023-07-20T08:33:52.591+0000] {serde.py:319} DEBUG - registering datetime.datetime for serialization
[2023-07-20T08:33:52.591+0000] {serde.py:319} DEBUG - registering datetime.timedelta for serialization
[2023-07-20T08:33:52.591+0000] {serde.py:319} DEBUG - registering pendulum.datetime.DateTime for serialization
[2023-07-20T08:33:52.591+0000] {serde.py:326} DEBUG - registering datetime.date for deserialization
[2023-07-20T08:33:52.591+0000] {serde.py:326} DEBUG - registering datetime.datetime for deserialization
[2023-07-20T08:33:52.592+0000] {serde.py:326} DEBUG - registering datetime.timedelta for deserialization
[2023-07-20T08:33:52.592+0000] {serde.py:326} DEBUG - registering pendulum.datetime.DateTime for deserialization
[2023-07-20T08:33:52.592+0000] {serde.py:319} DEBUG - registering kubernetes.client.models.v1_resource_requirements.V1ResourceRequirements for serialization
[2023-07-20T08:33:52.592+0000] {serde.py:319} DEBUG - registering kubernetes.client.models.v1_pod.V1Pod for serialization
[2023-07-20T08:33:52.592+0000] {serde.py:319} DEBUG - registering numpy.int8 for serialization
[2023-07-20T08:33:52.592+0000] {serde.py:319} DEBUG - registering numpy.int16 for serialization
[2023-07-20T08:33:52.592+0000] {serde.py:319} DEBUG - registering numpy.int32 for serialization
[2023-07-20T08:33:52.592+0000] {serde.py:319} DEBUG - registering numpy.int64 for serialization
[2023-07-20T08:33:52.592+0000] {serde.py:319} DEBUG - registering numpy.uint8 for serialization
[2023-07-20T08:33:52.593+0000] {serde.py:319} DEBUG - registering numpy.uint16 for serialization
[2023-07-20T08:33:52.593+0000] {serde.py:319} DEBUG - registering numpy.uint32 for serialization
[2023-07-20T08:33:52.593+0000] {serde.py:319} DEBUG - registering numpy.uint64 for serialization
[2023-07-20T08:33:52.593+0000] {serde.py:319} DEBUG - registering numpy.bool_ for serialization
[2023-07-20T08:33:52.593+0000] {serde.py:319} DEBUG - registering numpy.float64 for serialization
[2023-07-20T08:33:52.593+0000] {serde.py:319} DEBUG - registering numpy.float16 for serialization
[2023-07-20T08:33:52.593+0000] {serde.py:319} DEBUG - registering numpy.complex128 for serialization
[2023-07-20T08:33:52.593+0000] {serde.py:319} DEBUG - registering numpy.complex64 for serialization
[2023-07-20T08:33:52.593+0000] {serde.py:326} DEBUG - registering numpy.int8 for deserialization
[2023-07-20T08:33:52.593+0000] {serde.py:326} DEBUG - registering numpy.int16 for deserialization
[2023-07-20T08:33:52.593+0000] {serde.py:326} DEBUG - registering numpy.int32 for deserialization
[2023-07-20T08:33:52.593+0000] {serde.py:326} DEBUG - registering numpy.int64 for deserialization
[2023-07-20T08:33:52.593+0000] {serde.py:326} DEBUG - registering numpy.uint8 for deserialization
[2023-07-20T08:33:52.593+0000] {serde.py:326} DEBUG - registering numpy.uint16 for deserialization
[2023-07-20T08:33:52.593+0000] {serde.py:326} DEBUG - registering numpy.uint32 for deserialization
[2023-07-20T08:33:52.593+0000] {serde.py:326} DEBUG - registering numpy.uint64 for deserialization
[2023-07-20T08:33:52.594+0000] {serde.py:326} DEBUG - registering numpy.bool_ for deserialization
[2023-07-20T08:33:52.594+0000] {serde.py:326} DEBUG - registering numpy.float64 for deserialization
[2023-07-20T08:33:52.594+0000] {serde.py:326} DEBUG - registering numpy.float16 for deserialization
[2023-07-20T08:33:52.594+0000] {serde.py:326} DEBUG - registering numpy.complex128 for deserialization
[2023-07-20T08:33:52.594+0000] {serde.py:326} DEBUG - registering numpy.complex64 for deserialization
[2023-07-20T08:33:52.594+0000] {serde.py:319} DEBUG - registering pandas.core.frame.DataFrame for serialization
[2023-07-20T08:33:52.594+0000] {serde.py:326} DEBUG - registering pandas.core.frame.DataFrame for deserialization
[2023-07-20T08:33:52.594+0000] {serde.py:319} DEBUG - registering pendulum.tz.timezone.FixedTimezone for serialization
[2023-07-20T08:33:52.594+0000] {serde.py:319} DEBUG - registering pendulum.tz.timezone.Timezone for serialization
[2023-07-20T08:33:52.594+0000] {serde.py:326} DEBUG - registering pendulum.tz.timezone.FixedTimezone for deserialization
[2023-07-20T08:33:52.595+0000] {serde.py:326} DEBUG - registering pendulum.tz.timezone.Timezone for deserialization
[2023-07-20T08:33:52.595+0000] {serde.py:337} DEBUG - loading serializers took 0.006 seconds
[2023-07-20T08:33:53.181+0000] {db.py:1456} DEBUG - running check function check_conn_id_duplicates
[2023-07-20T08:33:53.474+0000] {db.py:1456} DEBUG - running check function check_conn_type_null
[2023-07-20T08:33:53.840+0000] {db.py:1456} DEBUG - running check function check_run_id_null
[2023-07-20T08:33:55.582+0000] {db.py:1456} DEBUG - running check function check_bad_references
[2023-07-20T08:34:05.080+0000] {db.py:1402} DEBUG - checking model task_instance
[2023-07-20T08:34:05.081+0000] {db.py:1402} DEBUG - checking model task_reschedule
[2023-07-20T08:34:05.081+0000] {db.py:1402} DEBUG - checking model rendered_task_instance_fields
[2023-07-20T08:34:05.081+0000] {db.py:1402} DEBUG - checking model task_fail
[2023-07-20T08:34:05.081+0000] {db.py:1402} DEBUG - checking model xcom
[2023-07-20T08:34:05.081+0000] {db.py:1456} DEBUG - running check function check_username_duplicates
[2023-07-20T08:34:05.563+0000] {migration.py:213} INFO - Context impl PostgresqlImpl.
[2023-07-20T08:34:05.563+0000] {migration.py:216} INFO - Will assume transactional DDL.
[2023-07-20T08:34:06.084+0000] {db.py:1590} INFO - Creating tables
[2023-07-20T08:34:06.084+0000] {settings.py:353} DEBUG - Disposing DB connection pool (PID 61)
[2023-07-20T08:34:06.169+0000] {settings.py:212} DEBUG - Setting up DB connection pool (PID 61)
Upgrades done
```

**Comment by arjunanan6** [comment]
A little update. I have spent quite a bit of time debugging this and with good results. I have managed to get the migrations job (and scheduler startup - since it has to fillup the Dagbag from the database) to go under 5 min again. 

It was a combination of:
- Using 2 scheduler replicas.
- Updated schduler.parsing_processes: 15
- Updated scheduler.min_file_process_interval: 600

This is already a really good improvement, but I am open to any suggestions to improve this even more.

**Comment by arjunanan6** [comment]
Hey @hussein-awala, thank you for your input on this one, it helped me narrow down the investigation. For now, I've also disabled the `migrateDatabaseJob` as well as I understand it is only needed when upgrading versions. I'll close this now.
