### ISSUE TITLE
Dynamic task mapping error: can't map over value of type <class 'NoneType'>

### ISSUE THREAD

**Issue by alireza-salemi** [apache/airflow#32700]
### Apache Airflow version

2.6.2

### What happened

I am seeing the following error in the latest distribution of Airflow using dynamic task mapping. I have checked the input data  multiple times and it is never None.
The error is as followed:
```
[2023-06-21, 03:57:22 UTC] {{taskinstance.py:1824}} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1407, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1531, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2179, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/mappedoperator.py", line 691, in render_template_fields
    mapped_kwargs, seen_oids = self._expand_mapped_kwargs(context, session)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/decorators/base.py", line 512, in _expand_mapped_kwargs
    op_kwargs, resolved_oids = super()._expand_mapped_kwargs(context, session)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/mappedoperator.py", line 559, in _expand_mapped_kwargs
    return self._get_specified_expand_input().resolve(context, session)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/expandinput.py", line 200, in resolve
    data = {k: self._expand_mapped_field(k, v, context, session=session) for k, v in self.value.items()}
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/expandinput.py", line 200, in <dictcomp>
    data = {k: self._expand_mapped_field(k, v, context, session=session) for k, v in self.value.items()}
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/expandinput.py", line 186, in _expand_mapped_field
    raise TypeError(f"can't map over value of type {type(value)}")
TypeError: can't map over value of type <class 'NoneType'>
```

The code looks like following and we are executing 300 tasks in parallel and there are usually

```python
@dag(schedule_interval=None,
     dag_id="consumer",
     start_date=datetime(2022, 11, 11),
     dagrun_timeout=timedelta(minutes=45),
     catchup=False,
     max_active_runs=3)
def consumer():

    @task(
        task_id="validate",
        retries=1,
        retry_delay=timedelta(seconds=RETRY_DELAY_SEC),
        pool=FLIGHT_POOL,
        weight_rule=WeightRule.UPSTREAM
    )
    def validate(**kwargs) -> List[Dict]:
        payload: dict = {key: value for key, value in list(kwargs['dag_run'].conf.items())}

        # payload is a list of dicts
        # [ {"flight_id": 123},
        #   {"flight_id": 456}
        # ]
        if not payload or all(isinstance(x, dict) for x in payload):
            raise AirflowFailException(f"Bad Config Submitted: {kwargs['dag_run'].conf}")

        return payload["flights"]

    @task(
        task_id="calculate",
        retries=1,
        retry_delay=timedelta(seconds=30),
        pool=FLIGHT_POOL,
        weight_rule=WeightRule.UPSTREAM,
        show_return_value_in_logs=False
    )
    def calculate(flights: Dict, **kwargs):
        return sla_calculate([build(flights["flight_id"])])

    @task(
        task_id="merge",
        retries=2,
        retry_delay=timedelta(seconds=30),
        trigger_rule=TriggerRule.ALL_DONE,
        pool=FLIGHT_POOL,
        weight_rule=WeightRule.UPSTREAM
    )
    def merge(records, **kwargs):
        upsert_records(records, SNOWFLAKE_HOOK)

    merge(records=calculate.expand(flights=validate()))
```

### What you think should happen instead

We should not get an error since non of the map entries is NoneType

### How to reproduce

This issue happens intermittently when 300 task are scheduled!

### Operating System

airflow:2.6.1-python3.9

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by hussein-awala** [comment]
Could you provide the dag run conf for the failed dag run?

Also, could you try returning an empty list when the flights is None?
```python
    def validate(**kwargs) -> List[Dict]:
        payload: dict = {key: value for key, value in list(kwargs['dag_run'].conf.items())}

        # payload is a list of dicts
        # [ {"flight_id": 123},
        #   {"flight_id": 456}
        # ]
        if not payload or all(isinstance(x, dict) for x in payload):
            raise AirflowFailException(f"Bad Config Submitted: {kwargs['dag_run'].conf}")

        return payload["flights"] or []
```

**Comment by smalsale** [comment]
> Could you provide the dag run conf for the failed dag run?
> 
> Also, could you try returning an empty list when the flights is None?
> 
> ```python
>     def validate(**kwargs) -> List[Dict]:
>         payload: dict = {key: value for key, value in list(kwargs['dag_run'].conf.items())}
> 
>         # payload is a list of dicts
>         # [ {"flight_id": 123},
>         #   {"flight_id": 456}
>         # ]
>         if not payload or all(isinstance(x, dict) for x in payload):
>             raise AirflowFailException(f"Bad Config Submitted: {kwargs['dag_run'].conf}")
> 
>         return payload["flights"] or []
> ```
Here is a conf for the failed run
```
{
    "flights": [
        {
            "flight_id": 4478824448
        },
        {
            "flight_id": 4478824449
        },
        {
            "flight_id": 4478824451
        },
        {
            "flight_id": 4478824456
        },
        {
            "flight_id": 4478824457
        },
        {
            "flight_id": 4478824459
        },
        {
            "flight_id": 4478824460
        },
        {
            "flight_id": 4478685201
        },
        {
            "flight_id": 4478824466
        },
        {
            "flight_id": 4478824468
        },
        {
            "flight_id": 4478824469
        },
        {
            "flight_id": 4478824471
        },
        {
            "flight_id": 4478824481
        },
        {
            "flight_id": 4478683183
        },
        {
            "flight_id": 4478826547
        },
        {
            "flight_id": 4478685246
        },
        {
            "flight_id": 4478824516
        },
        {
            "flight_id": 4478826572
        },
        {
            "flight_id": 4478824528
        },
        {
            "flight_id": 4478826580
        },
        {
            "flight_id": 4478685270
        },
        {
            "flight_id": 4478824540
        },
        {
            "flight_id": 4478824554
        },
        {
            "flight_id": 4478683245
        },
        {
            "flight_id": 4478685294
        },
        {
            "flight_id": 4478824557
        },
        {
            "flight_id": 4478824559
        },
        {
            "flight_id": 4478824562
        },
        {
            "flight_id": 4478826614
        },
        {
            "flight_id": 4478685308
        },
        {
            "flight_id": 4478824574
        },
        {
            "flight_id": 4478599301
        },
        {
            "flight_id": 4478826631
        },
        {
            "flight_id": 4478824585
        },
        {
            "flight_id": 4478683285
        },
        {
            "flight_id": 4478824602
        },
        {
            "flight_id": 4478685341
        },
        {
            "flight_id": 4478824606
        },
        {
            "flight_id": 4478826654
        },
        {
            "flight_id": 4478824609
        },
        {
            "flight_id": 4478685347
        },
        {
            "flight_id": 4478824618
        },
        {
            "flight_id": 4478826667
        },
        {
            "flight_id": 4478685359
        },
        {
            "flight_id": 4478824624
        },
        {
            "flight_id": 4478824625
        },
        {
            "flight_id": 4478685364
        },
        {
            "flight_id": 4478824635
        },
        {
            "flight_id": 4478685376
        },
        {
            "flight_id": 4478824641
        },
        {
            "flight_id": 4478824649
        },
        {
            "flight_id": 4478824655
        },
        {
            "flight_id": 4478824656
        },
        {
            "flight_id": 4478824657
        },
        {
            "flight_id": 4478824658
        },
        {
            "flight_id": 4478685422
        },
        {
            "flight_id": 4478824691
        },
        {
            "flight_id": 4478824692
        },
        {
            "flight_id": 4478685437
        },
        {
            "flight_id": 4478685444
        },
        {
            "flight_id": 4478824709
        },
        {
            "flight_id": 4478683398
        },
        {
            "flight_id": 4478685448
        },
        {
            "flight_id": 4478685457
        },
        {
            "flight_id": 4478824724
        },
        {
            "flight_id": 4478824725
        },
        {
            "flight_id": 4478824728
        },
        {
            "flight_id": 4478685467
        },
        {
            "flight_id": 4478683423
        },
        {
            "flight_id": 4478800160
        },
        {
            "flight_id": 4478824738
        },
        {
            "flight_id": 4478826792
        },
        {
            "flight_id": 4478824750
        },
        {
            "flight_id": 4478824751
        },
        {
            "flight_id": 4478685489
        },
        {
            "flight_id": 4478824766
        },
        {
            "flight_id": 4478824769
        },
        {
            "flight_id": 4478685513
        },
        {
            "flight_id": 4478685515
        },
        {
            "flight_id": 4478685518
        },
        {
            "flight_id": 4478824784
        },
        {
            "flight_id": 4478685529
        },
        {
            "flight_id": 4478824796
        },
        {
            "flight_id": 4478685549
        },
        {
            "flight_id": 4478683507
        },
        {
            "flight_id": 4478683513
        },
        {
            "flight_id": 4478824827
        },
        {
            "flight_id": 4478685564
        },
        {
            "flight_id": 4478824829
        },
        {
            "flight_id": 4478685568
        },
        {
            "flight_id": 4478824840
        },
        {
            "flight_id": 4478824844
        },
        {
            "flight_id": 4478824847
        },
        {
            "flight_id": 4478826906
        },
        {
            "flight_id": 4478824871
        },
        {
            "flight_id": 4478683566
        },
        {
            "flight_id": 4478685615
        },
        {
            "flight_id": 4478720435
        },
        {
            "flight_id": 4478683574
        },
        {
            "flight_id": 4478685622
        },
        {
            "flight_id": 4478685629
        },
        {
            "flight_id": 4478824900
        },
        {
            "flight_id": 4478824901
        },
        {
            "flight_id": 4478423495
        },
        {
            "flight_id": 4478824908
        },
        {
            "flight_id": 4478826966
        },
        {
            "flight_id": 4478423512
        },
        {
            "flight_id": 4478824921
        },
        {
            "flight_id": 4478824922
        },
        {
            "flight_id": 4478685663
        },
        {
            "flight_id": 4478824934
        },
        {
            "flight_id": 4478824941
        },
        {
            "flight_id": 4478685680
        },
        {
            "flight_id": 4478824950
        },
        {
            "flight_id": 4478685697
        },
        {
            "flight_id": 4478824963
        },
        {
            "flight_id": 4478683653
        },
        {
            "flight_id": 4478824970
        },
        {
            "flight_id": 4478683666
        },
        {
            "flight_id": 4478685719
        },
        {
            "flight_id": 4478683672
        },
        {
            "flight_id": 4478685721
        },
        {
            "flight_id": 4478824984
        },
        {
            "flight_id": 4478824985
        },
        {
            "flight_id": 4478685741
        },
        {
            "flight_id": 4478685747
        },
        {
            "flight_id": 4478685749
        },
        {
            "flight_id": 4478825013
        },
        {
            "flight_id": 4478825032
        },
        {
            "flight_id": 4478825038
        },
        {
            "flight_id": 4478685783
        },
        {
            "flight_id": 4478825050
        },
        {
            "flight_id": 4478685790
        },
        {
            "flight_id": 4478825065
        },
        {
            "flight_id": 4478825071
        },
        {
            "flight_id": 4478683770
        },
        {
            "flight_id": 4478825083
        },
        {
            "flight_id": 4478825085
        },
        {
            "flight_id": 4478685825
        },
        {
            "flight_id": 4478825095
        },
        {
            "flight_id": 4478685836
        },
        {
            "flight_id": 4478685855
        },
        {
            "flight_id": 4478825127
        },
        {
            "flight_id": 4478685865
        },
        {
            "flight_id": 4478825130
        },
        {
            "flight_id": 4478685869
        },
        {
            "flight_id": 4478683833
        },
        {
            "flight_id": 4478825145
        },
        {
            "flight_id": 4478825149
        },
        {
            "flight_id": 4478685887
        },
        {
            "flight_id": 4478825152
        },
        {
            "flight_id": 4478825154
        },
        {
            "flight_id": 4478825160
        },
        {
            "flight_id": 4478825163
        },
        {
            "flight_id": 4478825164
        },
        {
            "flight_id": 4478821072
        },
        {
            "flight_id": 4478825170
        },
        {
            "flight_id": 4478556888
        },
        {
            "flight_id": 4478685913
        },
        {
            "flight_id": 4478685914
        },
        {
            "flight_id": 4478825177
        },
        {
            "flight_id": 4478827224
        },
        {
            "flight_id": 4478825184
        },
        {
            "flight_id": 4478765793
        },
        {
            "flight_id": 4478685927
        },
        {
            "flight_id": 4478421747
        },
        {
            "flight_id": 4478685953
        },
        {
            "flight_id": 4478421765
        },
        {
            "flight_id": 4478685959
        },
        {
            "flight_id": 4478825223
        },
        {
            "flight_id": 4478825225
        },
        {
            "flight_id": 4478825249
        },
        {
            "flight_id": 4478685987
        },
        {
            "flight_id": 4478825259
        },
        {
            "flight_id": 4478825267
        },
        {
            "flight_id": 4478825272
        },
        {
            "flight_id": 4478683976
        },
        {
            "flight_id": 4478683978
        },
        {
            "flight_id": 4478825290
        },
        {
            "flight_id": 4478686028
        },
        {
            "flight_id": 4478686029
        },
        {
            "flight_id": 4478686041
        },
        {
            "flight_id": 4478686042
        },
        {
            "flight_id": 4478686043
        },
        {
            "flight_id": 4478686044
        },
        {
            "flight_id": 4478825314
        },
        {
            "flight_id": 4478421863
        },
        {
            "flight_id": 4478686058
        },
        {
            "flight_id": 4478686059
        },
        {
            "flight_id": 4478557036
        },
        {
            "flight_id": 4478825327
        },
        {
            "flight_id": 4478686075
        },
        {
            "flight_id": 4478825342
        },
        {
            "flight_id": 4478686079
        },
        {
            "flight_id": 4478825346
        },
        {
            "flight_id": 4478686087
        },
        {
            "flight_id": 4478825352
        },
        {
            "flight_id": 4478827401
        },
        {
            "flight_id": 4478686096
        },
        {
            "flight_id": 4478686097
        },
        {
            "flight_id": 4478686099
        },
        {
            "flight_id": 4478686104
        },
        {
            "flight_id": 4478686107
        },
        {
            "flight_id": 4478686120
        },
        {
            "flight_id": 4478686124
        },
        {
            "flight_id": 4478825388
        },
        {
            "flight_id": 4478557103
        },
        {
            "flight_id": 4478686132
        },
        {
            "flight_id": 4478686134
        },
        {
            "flight_id": 4478825398
        },
        {
            "flight_id": 4478686137
        },
        {
            "flight_id": 4478825401
        },
        {
            "flight_id": 4478825404
        },
        {
            "flight_id": 4478686152
        },
        {
            "flight_id": 4478686157
        },
        {
            "flight_id": 4478825425
        },
        {
            "flight_id": 4478825434
        },
        {
            "flight_id": 4478684125
        },
        {
            "flight_id": 4478686173
        },
        {
            "flight_id": 4478686182
        },
        {
            "flight_id": 4478557167
        },
        {
            "flight_id": 4478825455
        },
        {
            "flight_id": 4478684146
        },
        {
            "flight_id": 4478684150
        },
        {
            "flight_id": 4478827511
        },
        {
            "flight_id": 4478686200
        },
        {
            "flight_id": 4478686211
        },
        {
            "flight_id": 4478686216
        },
        {
            "flight_id": 4478700554
        },
        {
            "flight_id": 4478700556
        },
        {
            "flight_id": 4478684174
        },
        {
            "flight_id": 4478825486
        },
        {
            "flight_id": 4478686228
        },
        {
            "flight_id": 4478825494
        },
        {
            "flight_id": 4478686235
        },
        {
            "flight_id": 4478686240
        },
        {
            "flight_id": 4478825507
        },
        {
            "flight_id": 4478825512
        },
        {
            "flight_id": 4478557226
        },
        {
            "flight_id": 4478684206
        },
        {
            "flight_id": 4478686254
        },
        {
            "flight_id": 4478686270
        },
        {
            "flight_id": 4478686271
        },
        {
            "flight_id": 4478684226
        },
        {
            "flight_id": 4478647368
        },
        {
            "flight_id": 4478647369
        },
        {
            "flight_id": 4478686281
        },
        {
            "flight_id": 4478825546
        },
        {
            "flight_id": 4478684243
        },
        {
            "flight_id": 4478692438
        },
        {
            "flight_id": 4478686295
        },
        {
            "flight_id": 4478686297
        },
        {
            "flight_id": 4478692441
        },
        {
            "flight_id": 4478686302
        },
        {
            "flight_id": 4478686303
        },
        {
            "flight_id": 4478686315
        },
        {
            "flight_id": 4478825582
        },
        {
            "flight_id": 4478686321
        },
        {
            "flight_id": 4478684285
        },
        {
            "flight_id": 4478686334
        },
        {
            "flight_id": 4478686338
        },
        {
            "flight_id": 4478825614
        },
        {
            "flight_id": 4478825615
        },
        {
            "flight_id": 4478686355
        },
        {
            "flight_id": 4478686356
        },
        {
            "flight_id": 4478686358
        },
        {
            "flight_id": 4478686363
        },
        {
            "flight_id": 4478825629
        },
        {
            "flight_id": 4478686366
        },
        {
            "flight_id": 4478825648
        },
        {
            "flight_id": 4478686388
        },
        {
            "flight_id": 4478825652
        },
        {
            "flight_id": 4478461111
        },
        {
            "flight_id": 4478825668
        },
        {
            "flight_id": 4478825680
        },
        {
            "flight_id": 4478684372
        },
        {
            "flight_id": 4478686424
        },
        {
            "flight_id": 4478686425
        },
        {
            "flight_id": 4478825692
        },
        {
            "flight_id": 4478684386
        },
        {
            "flight_id": 4478684389
        },
        {
            "flight_id": 4478790885
        },
        {
            "flight_id": 4478786800
        },
        {
            "flight_id": 4478825713
        },
        {
            "flight_id": 4478825715
        },
        {
            "flight_id": 4478686456
        },
        {
            "flight_id": 4478686457
        },
        {
            "flight_id": 4478686460
        },
        {
            "flight_id": 4478825727
        },
        {
            "flight_id": 4478825738
        },
        {
            "flight_id": 4478825740
        },
        {
            "flight_id": 4478825748
        },
        {
            "flight_id": 4478827796
        },
        {
            "flight_id": 4478686535
        },
        {
            "flight_id": 4478686638
        },
        {
            "flight_id": 4478825927
        },
        {
            "flight_id": 4478825993
        },
        {
            "flight_id": 4478825995
        },
        {
            "flight_id": 4478824002
        },
        {
            "flight_id": 4478824101
        }
    ]
}
```

**Comment by hussein-awala** [comment]
In your example, you are calling the task calculate from itself:
> @task(
        task_id="calculate",
        retries=1,
        retry_delay=timedelta(seconds=30),
        pool=FLIGHT_POOL,
        weight_rule=WeightRule.UPSTREAM,
        show_return_value_in_logs=False
    )
    def calculate(flights: Dict, **kwargs):
        return calculate([build(flights["flight_id"])])

Could you check your code or fix the example?

**Comment by smalsale** [comment]
> In your example, you are calling the task calculate from itself:
> 
> > @task(
> > task_id="calculate",
> > retries=1,
> > retry_delay=timedelta(seconds=30),
> > pool=FLIGHT_POOL,
> > weight_rule=WeightRule.UPSTREAM,
> > show_return_value_in_logs=False
> > )
> > def calculate(flights: Dict, **kwargs):
> > return calculate([build(flights["flight_id"])])
> 
> Could you check your code or fix the example?

No, I changed it to `return sla_calculate([build(flights["flight_id"])])`

**Comment by potiuk** [comment]
My guess is that the bug is in this code you have not revealed and it sometimes return None in some circumstances. there is literally no other way to see it happening.

I suggest you make an experiment and for example save results of your "internal_method" call in files somewhere in tmp directory and print the location of those files. That should not cause too much of an overhead and you should be able to correlate the return of that function with the failure and see where the "null" value comes from. For comparision you can also modify Airflow's source code just before ` self._expand_mapped_kwargs(context, session)` and also log the values that `expand` method receives. That would give even more understanding where it comes from and by narrowing it down to the case where you can correlate all of those you can provide more information.

We have no idea to investigate it otherwise, so there is no point in keeping that issue open, I am converting it into a discussion and if you have results of your experiment, we cam attempt to help again, but without those details there is no much help we can give to help to solve your problem - we cannot debug your code, I am afraid.
