### ISSUE TITLE
BUG foreign key associated with column 'ab_permission_view_role.permission_view_id' 

### ISSUE THREAD

**Issue by ebdavison** [apache/airflow#33260]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

Receiving an error starting webserver after upgrade to 2.4.0:

```
[airflow@airflow-dev ~]$ airflow webserver -D
  ____________       _____________
 ____    |__( )_________  __/__  /________      __
____  /| |_  /__  ___/_  /_ __  /_  __ \_ | /| / /
___  ___ |  / _  /   _  __/ _  / / /_/ /_ |/ |/ /
 _/_/  |_/_/  /_/    /_/    /_/  \____/____/|__/
Running the Gunicorn Server with:
Workers: 4 sync
Host: 0.0.0.0:443
Timeout: 600
Logfiles: /opt/airflow/logs/airflow-webserver-access.log /opt/airflow/logs/airflow-webserver-error.log
Access Logformat:
=================================================================
/home/airflow/.local/lib/python3.7/site-packages/airflow/www/app.py:111 DeprecationWarning: 'app.json_encoder' is deprecated and will be removed in Flask 2.3. Customize 'app.json_provider_class' or 'app.json' instead.
[2023-08-09 15:32:32,525] {dagbag.py:508} INFO - Filling up the DagBag from /dev/null
Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/__main__.py", line 38, in main
    args.func(args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 51, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 99, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/webserver_command.py", line 446, in webserver
    app = create_app(None)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/www/app.py", line 136, in create_app
    init_appbuilder(flask_app)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/www/extensions/init_appbuilder.py", line 643, in init_appbuilder
    update_perms=conf.getboolean('webserver', 'UPDATE_FAB_PERMS'),
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/www/extensions/init_appbuilder.py", line 162, in __init__
    self.init_app(app, session)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/www/extensions/init_appbuilder.py", line 208, in init_app
    self.sm = self.security_manager_class(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/www/security.py", line 189, in __init__
    super().__init__(appbuilder)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/www/fab_security/sqla/manager.py", line 69, in __init__
    user_datamodel = SQLAInterface(self.user_model)
  File "/home/airflow/.local/lib/python3.7/site-packages/flask_appbuilder/models/sqla/interface.py", line 68, in __init__
    for prop in class_mapper(obj).iterate_properties:
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/base.py", line 436, in class_mapper
    mapper = _inspect_mapped_class(class_, configure=configure)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/base.py", line 415, in _inspect_mapped_class
    mapper._check_configure()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/mapper.py", line 1874, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/mapper.py", line 3381, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/mapper.py", line 3420, in _do_configure_registries
    mapper._post_configure_properties()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/mapper.py", line 1891, in _post_configure_properties
    prop.init()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/interfaces.py", line 227, in init
    self.do_init()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py", line 2133, in do_init
    self._setup_join_conditions()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py", line 2245, in _setup_join_conditions
    can_be_synced_fn=self._columns_are_mapped,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py", line 2624, in __init__
    self._determine_joins()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py", line 2724, in _determine_joins
    consider_as_foreign_keys=consider_as_foreign_keys,
  File "<string>", line 2, in join_condition
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/selectable.py", line 1187, in _join_condition
    a, a_subset, b, consider_as_foreign_keys
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/selectable.py", line 1255, in _joincond_scan_left_right
    col = fk.get_referent(left)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 2232, in get_referent
    return table.corresponding_column(self.column)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 1095, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 2378, in column
    tablekey,
sqlalchemy.exc.NoReferencedTableError: Foreign key associated with column 'ab_permission_view_role.permission_view_id' could not find table 'ab_permission_view' with which to generate a foreign key to target column 'id'
```

### What you think should happen instead

after `airflow db upgrade` no errors in the DB are expected.  I upgraded from 2.2.0 -> 2.3.0 -> 2.3.4 -> 2.4.0.

### How to reproduce

Unknown

### Operating System

Amazon Linux 2

### Versions of Apache Airflow Providers

apache-airflow-providers-celery==3.0.0
apache-airflow-providers-common-sql==1.1.0
apache-airflow-providers-ftp==3.1.0
apache-airflow-providers-http==4.0.0
apache-airflow-providers-imap==3.0.0
apache-airflow-providers-postgres==2.0.0
apache-airflow-providers-sqlite==3.2.0
apache-airflow-providers-ssh==2.1.1

### Deployment

Other

### Deployment details

native install on base OS

### Anything else

every time airflow webserver is started

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by ebdavison** [comment]
Looks like this is a red herring.  If I install SQLAlchemy==1.4.49 then this error goes away.

**Comment by ebdavison** [comment]
rolling back to airflow 2.3.4 using a similar command as above fixes the problem as well.

**Comment by potiuk** [comment]
Can you try to upgrate to latest 2.6* version and see if it works?

**Comment by jens-scheffler-bosch** [comment]
+1 to comment from @potiuk - In 2.4.x/2.5.x we also had constraint problems, are after a few rounds for sure fixed in 2.6.x.

**Comment by ebdavison** [comment]
Trying an upgrade to 2.6.x now; I will post results.

**Comment by ebdavison** [comment]
2.6 seems to be working fine.

**Comment by potiuk** [comment]
Closing then.
