### ISSUE TITLE
Incorrect TimeOut Calculation for ExternalTaskSensor when mode=reschedule and retries>0 specified

### ISSUE THREAD

**Issue by vishal-m-patil-db** [apache/airflow#33866]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

2.2.5 and 2.5.3

### What you think should happen instead

Timeout should be calculated based on current run start_date and not start_date from previous runs which can range from any day

### How to reproduce

Create parent_dag with below task
`    task1= PythonOperator(
        task_id='task1',
        provide_context=True,
        python_callable=lambda: time.sleep(60),
    )`

Create child_dag with below default_args (retries=3) and task
`default_args = {'depends_on_past': False,
                'email_on_failure': False,
                'email_on_retry': False,
                'owner': 'Composer',
                'project_id': 'test',
                'region': 'europe-west3',
                'retries': 3}`
`    parent_sensor = ExternalTaskSensor(
        task_id='parent_sensor',
        external_dag_id='parent_dag',
        external_task_id='task1',
        mode='reschedule',
        timeout=300,
        execution_date_fn=lambda dt: dt
    )`

If these dags are ran/reran multiple times and then timeout is calculated as current_end_date - start_date of run attempt 3 times before.

For Ex. 1st child run is on 1-Aug, 2nd child run is on 5th Aug, 3rd child run is on 6th Aug, and if child dag is triggerred in 7th Aug, it calculates timeout as 7th Aug end_date -1st Aug start_date which is 518400 instead of calculating timeout as 7th Aug end_date of current run-7th AUg start_date of current run.

The problem seems to be in airflow code
https://github.com/apache/airflow/blob/main/airflow/sensors/base.py#L214

here its substracting self.retries from max tries and hence instead of current run start_date its going start_date for 3 runs back.

### Operating System

Cloud Composer

### Deployment

Google Cloud Composer

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by vishal-m-patil-db** [comment]
Error with 2.2.5 version
`[2023-08-10, 06:30:01 UTC] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/python3.8/lib/python3.8/site-packages/airflow/sensors/base.py", line 242, in execute
    raise AirflowSensorTimeout(f"Snap. Time is OUT. DAG id: {log_dag_id}")`

Error with 2.5.3 version
`Traceback (most recent call last):
  File "/opt/python3.8/lib/python3.8/site-packages/airflow/sensors/base.py", line 215, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 2111.128995 seconds exceeds the specified timeout of 300.`

**Comment by nathadfield** [comment]
@vishal-m-patil-db  As of Airflow v2.6.3, I cannot seem to replicate this problem.  I created a DAG with a task like the following:

```
wait_for_start = ExternalTaskSensor(
    task_id='wait_for_start',
    external_dag_id='parent_dag',
    external_task_id='parent_task',
    mode='reschedule',
    poke_interval=5,
    timeout=30,
    retries=3
)
```

With the console output looking like this.

```
[2023-09-11, 14:00:20 UTC] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/sensors/base.py", line 242, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 35.994384 seconds exceeds the specified timeout of 30.
```

Are you able to check against a newer version and, if still occurring, provide us with a clearer example that we can attempt to replicate.

**Comment by vishal-m-patil-db** [comment]
@nathadfield : Thanks for checking this. Did you clear this dag more than thrice? Can you try clearing dag today.
I did not have poke interval set in my dag.
Version which we checked in is 2.5.3.

**Comment by nathadfield** [comment]
@vishal-m-patil-db Yes, even if I use your exact same code and clear the task multiple times, the result is still the same.

```
[2023-09-12, 08:01:27 UTC] {taskinstance.py:1308} INFO - Starting attempt 4 of 6
[2023-09-12, 08:01:27 UTC] {taskinstance.py:1327} INFO - Executing <Task(ExternalTaskSensor): parent_sensor> on 2023-09-11 01:00:00+00:00
[2023-09-12, 08:01:27 UTC] {standard_task_runner.py:57} INFO - Started process 19708 to run task
[2023-09-12, 08:01:27 UTC] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'test-dag', 'parent_sensor', 'scheduled__2023-09-11T01:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/ab_fx_rates/ab_fx_rates.py', '--cfg-path', '/tmp/tmpn7zhc544']
[2023-09-12, 08:01:27 UTC] {standard_task_runner.py:85} INFO - Job 10: Subtask parent_sensor
[2023-09-12, 08:01:27 UTC] {task_command.py:410} INFO - Running <TaskInstance: test-dag.parent_sensor scheduled__2023-09-11T01:00:00+00:00 [running]> on host 2dc4acc0f8c2
[2023-09-12, 08:01:27 UTC] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_ID='test-dag' AIRFLOW_CTX_TASK_ID='parent_sensor' AIRFLOW_CTX_EXECUTION_DATE='2023-09-11T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-11T01:00:00+00:00'
[2023-09-12, 08:01:27 UTC] {external_task.py:232} INFO - Poking for tasks ['task1'] in dag parent_dag on 2023-09-11T01:00:00+00:00 ... 
[2023-09-12, 08:01:27 UTC] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/sensors/base.py", line 242, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 301.280239 seconds exceeds the specified timeout of 300.
```

Is there any chance you could try this on a new Airflow version?

**Comment by guhuajun** [comment]
Greetings,

I never had a success with `ExternalTaskSensor` with two DAGs. The error message is same in this issue.

May I know which documentation I can refer to understand following sentence.

```
[2024-05-22, 03:34:58 UTC] {external_task.py:258} INFO - Poking for tasks ['end'] in dag extract_tasks on 2024-05-22T02:34:54.207499+00:00 ... 
```
