### ISSUE TITLE
Jobs in Azure Containers restart infinitely if logger crashes, despite retries being set to off.

### ISSUE THREAD

**Issue by krisfur** [apache/airflow#34516]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

We are using Airflow 2.5.2 to deploy python scripts in Azure containers.

In cases where the logger breaks (in our case because someone used tqdm for progress bars which are known to break it), Airflow failing to find the log keeps re-provisioning the container and restarting the job infinitely, even if all is set to not retry in Airflow. This incurs costs on API calls for us and thus is an impactful problem.

The issue could be because of the handling in _monitor_logging() in [Azure cointainer_instances.py line 298](https://github.com/apache/airflow/blob/main/airflow/providers/microsoft/azure/operators/container_instances.py#L298) where it changes the state to provisioning, but then doesn't do anything with it when it continues to fail to get instance_view. Maybe some form of check like if state=="Provisioning" and last_state=="Running": return 1 if retries are off could help handle it? 

Any insight would be appreciated. I am happy to help write a fix, if you can help me understand this flow a bit better.

### What you think should happen instead

The job should fail/exit code 1 instead of reprovisioning/retrying.

### How to reproduce

Run an airflow job in which a script is run in an Azure container, which employs tqdm progress bars, or otherwise overwhelms the logger and makes it fail.

### Operating System

Ubuntu 20.04

### Versions of Apache Airflow Providers

apache-airflow-providers-common-sql==1.3.4
apache-airflow-providers-ftp==2.1.1
apache-airflow-providers-http==2.1.1
apache-airflow-providers-imap==2.2.2
apache-airflow-providers-microsoft-azure==3.7.2
apache-airflow-providers-postgres==4.0.1
apache-airflow-providers-sqlite==2.1.2
apache-airflow-providers-ssh==3.1.0

### Deployment

Virtualenv installation

### Deployment details

Airflow running on a VM hosted in Azure.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by krisfur** [comment]
A snippet of the log when this issue happens:

`[2023-09-21, 13:26:28 UTC] {container_instances.py:344} ERROR - Exception while getting container groups
Traceback (most recent call last):
  File "/home/azureuser/pyenv-airflow/lib/python3.8/site-packages/airflow/providers/microsoft/azure/operators/container_instances.py", line 316, in _monitor_logging
    logs = self._ci_hook.get_logs(resource_group, name)
  File "/home/azureuser/pyenv-airflow/lib/python3.8/site-packages/airflow/providers/microsoft/azure/hooks/container_instance.py", line 119, in get_logs
    return logs.content.splitlines(True)
AttributeError: 'NoneType' object has no attribute 'splitlines'
[2023-09-21, 13:26:29 UTC] {container_instances.py:344} ERROR - Exception while getting container groups
Traceback (most recent call last):
  File "/home/azureuser/pyenv-airflow/lib/python3.8/site-packages/airflow/providers/microsoft/azure/operators/container_instances.py", line 316, in _monitor_logging
    logs = self._ci_hook.get_logs(resource_group, name)
  File "/home/azureuser/pyenv-airflow/lib/python3.8/site-packages/airflow/providers/microsoft/azure/hooks/container_instance.py", line 119, in get_logs
    return logs.content.splitlines(True)
AttributeError: 'NoneType' object has no attribute 'splitlines'
[2023-09-21, 13:26:31 UTC] {container_instances.py:344} ERROR - Exception while getting container groups
Traceback (most recent call last):
  File "/home/azureuser/pyenv-airflow/lib/python3.8/site-packages/airflow/providers/microsoft/azure/operators/container_instances.py", line 316, in _monitor_logging
    logs = self._ci_hook.get_logs(resource_group, name)
  File "/home/azureuser/pyenv-airflow/lib/python3.8/site-packages/airflow/providers/microsoft/azure/hooks/container_instance.py", line 119, in get_logs
    return logs.content.splitlines(True)
AttributeError: 'NoneType' object has no attribute 'splitlines'
[2023-09-21, 13:26:32 UTC] {container_instances.py:344} ERROR - Exception while getting container groups
Traceback (most recent call last):
  File "/home/azureuser/pyenv-airflow/lib/python3.8/site-packages/airflow/providers/microsoft/azure/operators/container_instances.py", line 316, in _monitor_logging
    logs = self._ci_hook.get_logs(resource_group, name)
  File "/home/azureuser/pyenv-airflow/lib/python3.8/site-packages/airflow/providers/microsoft/azure/hooks/container_instance.py", line 119, in get_logs
    return logs.content.splitlines(True)
AttributeError: 'NoneType' object has no attribute 'splitlines'
[2023-09-21, 13:26:33 UTC] {container_instances.py:344} ERROR - Exception while getting container groups
Traceback (most recent call last):
  File "/home/azureuser/pyenv-airflow/lib/python3.8/site-packages/airflow/providers/microsoft/azure/operators/container_instances.py", line 316, in _monitor_logging
    logs = self._ci_hook.get_logs(resource_group, name)
  File "/home/azureuser/pyenv-airflow/lib/python3.8/site-packages/airflow/providers/microsoft/azure/hooks/container_instance.py", line 119, in get_logs
    return logs.content.splitlines(True)
AttributeError: 'NoneType' object has no attribute 'splitlines'
[2023-09-21, 13:26:35 UTC] {container_instances.py:344} ERROR - Exception while getting container groups
Traceback (most recent call last):
  File "/home/azureuser/pyenv-airflow/lib/python3.8/site-packages/airflow/providers/microsoft/azure/operators/container_instances.py", line 316, in _monitor_logging
    logs = self._ci_hook.get_logs(resource_group, name)
  File "/home/azureuser/pyenv-airflow/lib/python3.8/site-packages/airflow/providers/microsoft/azure/hooks/container_instance.py", line 119, in get_logs
    return logs.content.splitlines(True)
AttributeError: 'NoneType' object has no attribute 'splitlines'
[2023-09-21, 13:26:36 UTC] {container_instances.py:344} ERROR - Exception while getting container groups
Traceback (most recent call last):
  File "/home/azureuser/pyenv-airflow/lib/python3.8/site-packages/airflow/providers/microsoft/azure/operators/container_instances.py", line 316, in _monitor_logging
    logs = self._ci_hook.get_logs(resource_group, name)
  File "/home/azureuser/pyenv-airflow/lib/python3.8/site-packages/airflow/providers/microsoft/azure/hooks/container_instance.py", line 119, in get_logs
    return logs.content.splitlines(True)
AttributeError: 'NoneType' object has no attribute 'splitlines'
[2023-09-21, 13:26:37 UTC] {container_instances.py:344} ERROR - Exception while getting container groups
Traceback (most recent call last):
  File "/home/azureuser/pyenv-airflow/lib/python3.8/site-packages/airflow/providers/microsoft/azure/operators/container_instances.py", line 316, in _monitor_logging
    logs = self._ci_hook.get_logs(resource_group, name)
  File "/home/azureuser/pyenv-airflow/lib/python3.8/site-packages/airflow/providers/microsoft/azure/hooks/container_instance.py", line 119, in get_logs
    return logs.content.splitlines(True)
AttributeError: 'NoneType' object has no attribute 'splitlines'
[2023-09-21, 13:26:38 UTC] {container_instances.py:344} ERROR - Exception while getting container groups
Traceback (most recent call last):
  File "/home/azureuser/pyenv-airflow/lib/python3.8/site-packages/airflow/providers/microsoft/azure/operators/container_instances.py", line 316, in _monitor_logging
    logs = self._ci_hook.get_logs(resource_group, name)
  File "/home/azureuser/pyenv-airflow/lib/python3.8/site-packages/airflow/providers/microsoft/azure/hooks/container_instance.py", line 119, in get_logs
    return logs.content.splitlines(True)
AttributeError: 'NoneType' object has no attribute 'splitlines'
[2023-09-21, 13:26:40 UTC] {container_instances.py:344} ERROR - Exception while getting container groups
Traceback (most recent call last):
  File "/home/azureuser/pyenv-airflow/lib/python3.8/site-packages/airflow/providers/microsoft/azure/operators/container_instances.py", line 316, in _monitor_logging
    logs = self._ci_hook.get_logs(resource_group, name)
  File "/home/azureuser/pyenv-airflow/lib/python3.8/site-packages/airflow/providers/microsoft/azure/hooks/container_instance.py", line 119, in get_logs
    return logs.content.splitlines(True)
AttributeError: 'NoneType' object has no attribute 'splitlines'
[2023-09-21, 13:26:41 UTC] {container_instances.py:344} ERROR - Exception while getting container groups
Traceback (most recent call last):
  File "/home/azureuser/pyenv-airflow/lib/python3.8/site-packages/airflow/providers/microsoft/azure/operators/container_instances.py", line 316, in _monitor_logging
    logs = self._ci_hook.get_logs(resource_group, name)
  File "/home/azureuser/pyenv-airflow/lib/python3.8/site-packages/airflow/providers/microsoft/azure/hooks/container_instance.py", line 119, in get_logs
    return logs.content.splitlines(True)
AttributeError: 'NoneType' object has no attribute 'splitlines'
[2023-09-21, 13:26:42 UTC] {container_instances.py:344} ERROR - Exception while getting container groups
Traceback (most recent call last):
  File "/home/azureuser/pyenv-airflow/lib/python3.8/site-packages/airflow/providers/microsoft/azure/operators/container_instances.py", line 316, in _monitor_logging
    logs = self._ci_hook.get_logs(resource_group, name)
  File "/home/azureuser/pyenv-airflow/lib/python3.8/site-packages/airflow/providers/microsoft/azure/hooks/container_instance.py", line 119, in get_logs
    return logs.content.splitlines(True)
AttributeError: 'NoneType' object has no attribute 'splitlines'
[2023-09-21, 13:26:43 UTC] {container_instances.py:344} ERROR - Exception while getting container groups
Traceback (most recent call last):
  File "/home/azureuser/pyenv-airflow/lib/python3.8/site-packages/airflow/providers/microsoft/azure/operators/container_instances.py", line 316, in _monitor_logging
    logs = self._ci_hook.get_logs(resource_group, name)
  File "/home/azureuser/pyenv-airflow/lib/python3.8/site-packages/airflow/providers/microsoft/azure/hooks/container_instance.py", line 119, in get_logs
    return logs.content.splitlines(True)
AttributeError: 'NoneType' object has no attribute 'splitlines'
[2023-09-21, 13:26:45 UTC] {container_instances.py:344} ERROR - Exception while getting container groups
Traceback (most recent call last):
  File "/home/azureuser/pyenv-airflow/lib/python3.8/site-packages/airflow/providers/microsoft/azure/operators/container_instances.py", line 316, in _monitor_logging
    logs = self._ci_hook.get_logs(resource_group, name)
  File "/home/azureuser/pyenv-airflow/lib/python3.8/site-packages/airflow/providers/microsoft/azure/hooks/container_instance.py", line 119, in get_logs
    return logs.content.splitlines(True)
AttributeError: 'NoneType' object has no attribute 'splitlines'
[2023-09-21, 13:26:46 UTC] {container_instances.py:344} ERROR - Exception while getting container groups
Traceback (most recent call last):
  File "/home/azureuser/pyenv-airflow/lib/python3.8/site-packages/airflow/providers/microsoft/azure/operators/container_instances.py", line 316, in _monitor_logging
    logs = self._ci_hook.get_logs(resource_group, name)
  File "/home/azureuser/pyenv-airflow/lib/python3.8/site-packages/airflow/providers/microsoft/azure/hooks/container_instance.py", line 119, in get_logs
    return logs.content.splitlines(True)
AttributeError: 'NoneType' object has no attribute 'splitlines'
[2023-09-21, 13:26:47 UTC] {container_instances.py:344} ERROR - Exception while getting container groups
Traceback (most recent call last):
  File "/home/azureuser/pyenv-airflow/lib/python3.8/site-packages/airflow/providers/microsoft/azure/operators/container_instances.py", line 316, in _monitor_logging
    logs = self._ci_hook.get_logs(resource_group, name)
  File "/home/azureuser/pyenv-airflow/lib/python3.8/site-packages/airflow/providers/microsoft/azure/hooks/container_instance.py", line 119, in get_logs
    return logs.content.splitlines(True)
AttributeError: 'NoneType' object has no attribute 'splitlines'
[2023-09-21, 13:26:48 UTC] {container_instances.py:344} ERROR - Exception while getting container groups
Traceback (most recent call last):
  File "/home/azureuser/pyenv-airflow/lib/python3.8/site-packages/airflow/providers/microsoft/azure/operators/container_instances.py", line 316, in _monitor_logging
    logs = self._ci_hook.get_logs(resource_group, name)
  File "/home/azureuser/pyenv-airflow/lib/python3.8/site-packages/airflow/providers/microsoft/azure/hooks/container_instance.py", line 119, in get_logs
    return logs.content.splitlines(True)
AttributeError: 'NoneType' object has no attribute 'splitlines'
[2023-09-21, 13:27:10 UTC] {container_instances.py:344} ERROR - Exception while getting container groups
Traceback (most recent call last):
  File "/home/azureuser/pyenv-airflow/lib/python3.8/site-packages/airflow/providers/microsoft/azure/operators/container_instances.py", line 316, in _monitor_logging
    logs = self._ci_hook.get_logs(resource_group, name)
  File "/home/azureuser/pyenv-airflow/lib/python3.8/site-packages/airflow/providers/microsoft/azure/hooks/container_instance.py", line 119, in get_logs
    return logs.content.splitlines(True)
AttributeError: 'NoneType' object has no attribute 'splitlines'
[2023-09-21, 13:27:11 UTC] {container_instances.py:311} INFO - Container group state changed to Waiting
[2023-09-21, 13:27:13 UTC] {container_instances.py:311} INFO - Container group state changed to Running`

**Comment by liamalsopp** [comment]
Here's the code that's run inside the Azure Container instance that can replicate this issue.

`import re
import pandas as pd
import phonenumbers
import tldextract
from sentence_transformers import SentenceTransformer
from urlextract import URLExtract
import logging
from tqdm.auto import tqdm

tqdm.pandas()


def find_phone_numbers(text):
    uk_numbers = []
    numbers = []
    exclusive_uk = []
    exclusive_foreign = []
    for match in phonenumbers.PhoneNumberMatcher(text, "GB"):
        uk_numbers.append(
            phonenumbers.format_number(
                match.number, phonenumbers.PhoneNumberFormat.NATIONAL
            )
        )
    for match in phonenumbers.PhoneNumberMatcher(text, "US"):
        numbers.append(
            phonenumbers.format_number(
                match.number, phonenumbers.PhoneNumberFormat.NATIONAL
            )
        )
    for match in phonenumbers.PhoneNumberMatcher(text, "AU"):
        numbers.append(
            phonenumbers.format_number(
                match.number, phonenumbers.PhoneNumberFormat.NATIONAL
            )
        )
    for match in phonenumbers.PhoneNumberMatcher(text, "NZ"):
        numbers.append(
            phonenumbers.format_number(
                match.number, phonenumbers.PhoneNumberFormat.NATIONAL
            )
        )
    for match in phonenumbers.PhoneNumberMatcher(text, "CA"):
        numbers.append(
            phonenumbers.format_number(
                match.number, phonenumbers.PhoneNumberFormat.NATIONAL
            )
        )
    for match in phonenumbers.PhoneNumberMatcher(text, "ZA"):
        numbers.append(
            phonenumbers.format_number(
                match.number, phonenumbers.PhoneNumberFormat.NATIONAL
            )
        )

    exclusive_uk = [x for x in uk_numbers if x not in numbers]
    exclusive_foreign = [x for x in numbers if x not in uk_numbers]

    return pd.Series(
        [
            list(set(uk_numbers)),
            list(set(numbers)),
            list(set(exclusive_uk)),
            list(set(exclusive_foreign)),
        ]
    )


def find_urls(text):
    uk_urls = []
    foreign_urls = []
    extractor = URLExtract()
    links = list(set(extractor.find_urls(text)))

    for x in links:
        tld = tldextract.extract(x)
        suffix = tld.suffix
        if ".uk" in suffix:
            uk_urls.append(tld)
        if ".us" in suffix:
            foreign_urls.append(tld)
        if ".ca" in suffix:
            foreign_urls.append(tld)
        if ".nz" in suffix:
            foreign_urls.append(tld)
        if ".au" in suffix:
            foreign_urls.append(tld)
        if ".in" in suffix:
            foreign_urls.append(tld)
        if ".pk" in suffix:
            foreign_urls.append(tld)
    return pd.Series([uk_urls, foreign_urls])


df = pd.DataFrame()
datalist = [str(i) for i in range(int(10000))]
df["data"] = datalist

df[
    [
        "possible_uk_numbers",
        "possible_foreign_numbers",
        "definite_uk_numbers",
        "definite_foreign_numbers",
    ]
] = df.data.progress_apply(find_phone_numbers)
df[["uk_urls", "foreign_urls"]] = df.data.progress_apply(find_urls)
`

**Comment by liamalsopp** [comment]
To note, this seems to occur specifically when there is more than 1 progress bar.
