### ISSUE TITLE
AirflowException: Celery command failed on host: *** with celery_task_id ***

### ISSUE THREAD

**Issue by ekloos** [apache/airflow#34686]
### Apache Airflow version

2.7.1

### What happened

Hi Team,

**PROBLEM STATEMENT:**
===============================================================================
I am trying to install airflow 2.7.1 on ECS faregate with a CeleryExecutor. Every task that is being run returns as SUCCEEDED in the webserver (without logs) but in the flower UI I see that the tasks error with the following error traceback:

**Flower UI**
```
Traceback (most recent call last):   
File "/home/airflow/.local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task     
R = retval = fun(*args, **kwargs)                  
^^^^^^^^^^^^^^^^^^^^  
File "/home/airflow/.local/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__     
return self.run(*args, **kwargs)            
^^^^^^^^^^^^^^^^^^^^^^^^^   
File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/celery/executors/celery_executor_utils.py", line 123, in execute_command     
_execute_in_fork(command_to_exec, celery_task_id)  
 File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/celery/executors/celery_executor_utils.py", line 138, in _execute_in_fork     
raise AirflowException(msg) 
airflow.exceptions.AirflowException: Celery command failed on host: *** with celery_task_id 103a1a94-2654-4365-bfa0-b77bf1ae91b6
```

**Logs in the worker**
```
[2023-09-29 12:14:44,622: INFO/MainProcess] Task airflow.providers.celery.executors.celery_executor_utils.execute_command[2c4125a7-0e73-4a46-b6a9-e127fbdc15b7] received

2023-09-29T14:14:44.628+02:00	[2023-09-29 12:14:44,628: INFO/ForkPoolWorker-15] [2c4125a7-0e73-4a46-b6a9-e127fbdc15b7] Executing command in Celery: ['airflow', 'tasks', 'run', 'tutorial_dag', 'transform', 'manual__2023-09-29T12:13:50.456702+00:00', '--local', '--subdir', '/home/airflow/.local/lib/python3.11/site-packages/airflow/example_dags/tutorial_dag.py']

2023-09-29T14:14:44.860+02:00	[2023-09-29 12:14:44,858: INFO/ForkPoolWorker-15] Filling up the DagBag from /home/airflow/.local/lib/python3.11/site-packages/airflow/example_dags/tutorial_dag.py

2023-09-29T14:14:45.791+02:00	[2023-09-29 12:14:45,791: WARNING/ForkPoolWorker-15] Changing /opt/airflow/logs/dag_id=tutorial_dag/run_id=manual__2023-09-29T12:13:50.456702+00:00/task_id=transform permission to 509

2023-09-29T14:14:45.791+02:00	[2023-09-29 12:14:45,791: INFO/ForkPoolWorker-15] Running <TaskInstance: tutorial_dag.transform manual__2023-09-29T12:13:50.456702+00:00 [queued]> on host 10.0.3.243

2023-09-29T14:14:46.664+02:00	[2023-09-29 12:14:46,664: ERROR/ForkPoolWorker-15] Task airflow.providers.celery.executors.celery_executor_utils.execute_command[2c4125a7-0e73-4a46-b6a9-e127fbdc15b7] raised unexpected: AirflowException('Celery command failed on host: 10.0.3.243 with celery_task_id 2c4125a7-0e73-4a46-b6a9-e127fbdc15b7')

2023-09-29T14:14:46.664+02:00	Traceback (most recent call last):

2023-09-29T14:14:46.664+02:00	File "/home/airflow/.local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task

2023-09-29T14:14:46.664+02:00	R = retval = fun(*args, **kwargs)

2023-09-29T14:14:46.664+02:00	^^^^^^^^^^^^^^^^^^^^

2023-09-29T14:14:46.664+02:00	File "/home/airflow/.local/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__

2023-09-29T14:14:46.664+02:00	return self.run(*args, **kwargs)

2023-09-29T14:14:46.664+02:00	^^^^^^^^^^^^^^^^^^^^^^^^^

2023-09-29T14:14:46.664+02:00	File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/celery/executors/celery_executor_utils.py", line 123, in execute_command

2023-09-29T14:14:46.664+02:00	_execute_in_fork(command_to_exec, celery_task_id)

2023-09-29T14:14:46.664+02:00	File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/celery/executors/celery_executor_utils.py", line 138, in _execute_in_fork

2023-09-29T14:14:46.664+02:00	raise AirflowException(msg)

2023-09-29T14:14:46.664+02:00	airflow.exceptions.AirflowException: Celery command failed on host: 10.0.3.243 with celery_task_id 2c4125a7-0e73-4a46-b6a9-e127fbdc15b7
```

**Task in webserver UI:**
![image](https://github.com/apache/airflow/assets/146446190/d6f1cc40-63e9-4a6e-a6e6-df577ab614f6)

**Task in Flower:**
![image](https://github.com/apache/airflow/assets/146446190/263021e7-52a9-4158-aa04-b37b2fbfacb7)

**CONFIGURATIONS**
====================================================================
I have the following configuration on the ECS faregate services (seperate service for worker, scheduler, webserver and flower build on the same docker image).

**airflow.cfg**
```
[core]
executor = CeleryExecutor
parallelism = 64
max_active_tasks_per_dag = 16
dags_are_paused_at_creation = True
load_examples = True
load_default_connections = True


[logging]
remote_logging = True
remote_log_conn_id = aws_default
encrypt_s3_logs = False


[webserver]
dag_default_view = graph
expose_config = True


[scheduler]
dag_dir_list_interval = 300
catchup_by_default = False

[celery]
celery_app_name = airflow.providers.celery.executors.celery_executor
ssl_active = False
```

**Dockerfile**
```
FROM apache/airflow:2.7.1-python3.11

USER root
RUN apt-get update \
  && apt-get install -y --no-install-recommends gcc libc6-dev libcurl4-openssl-dev libssl-dev \ 
  && apt-get autoremove -yqq --purge \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

USER airflow
COPY --chown=airflow:airflow /dist/ /dist/
RUN pip install --upgrade pip
RUN pip install --no-cache-dir /dist/* -c "https://raw.githubusercontent.com/apache/airflow/constraints-2.7.1/constraints-3.11.txt"

COPY --chown=airflow:airflow airflow.cfg "${AIRFLOW_HOME}/airflow.cfg"
COPY --chown=airflow:airflow entrypoint.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
```

**Environment variables**
"AIRFLOW__WEBSERVER__BASE_URL" = "https://www.***.com"
"AIRFLOW__LOGGING__LOGGING_LEVEL" = "INFO"
"AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER" = "s3://<bucket_name>/logs/"
"AIRFLOW__DATABASE__SQL_ALCHEMY_CONN" = "postgresql+psycopg2://<user>}:<password>@<host>:<port>/<db_name>}"
"AIRFLOW__CORE__FERNET_KEY" = "<key>"
"AIRFLOW__CELERY__BROKER_URL" = "redis://<redis_host>:6379/0"
"AIRFLOW__CELERY__RESULT_BACKEND" = "db+postgresql://<user>:<password>@<host>:<port>/<db_name>"
"AIRFLOW__CELERY__FLOWER_URL_PREFIX" = "/flower"
"AIRFLOW__CORE__HOSTNAME_CALLABLE" = "airflow.utils.net.get_host_ip_address"
"AIRFLOW__WEBSERVER__SECRET_KEY" = "<key>"
"AIRFLOW__CORE__LOAD_EXAMPLES" = "True"
"AWS_DEFAULT_REGION" =  "eu-west-1"

### What you think should happen instead

I expecting the task to run on the worker correctly and and there to be logs visiable in the webserver UI of the task.

### How to reproduce

Create a docker image with the following defintion:

```
FROM apache/airflow:2.7.1-python3.11

USER root
RUN apt-get update \
  && apt-get install -y --no-install-recommends gcc libc6-dev libcurl4-openssl-dev libssl-dev \ 
  && apt-get autoremove -yqq --purge \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

USER airflow
COPY --chown=airflow:airflow /dist/ /dist/
RUN pip install --upgrade pip
RUN pip install --no-cache-dir /dist/* -c "https://raw.githubusercontent.com/apache/airflow/constraints-2.7.1/constraints-3.11.txt"

COPY --chown=airflow:airflow airflow.cfg "${AIRFLOW_HOME}/airflow.cfg"
COPY --chown=airflow:airflow entrypoint.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
```

with entrypoint.sh:
```
case "$1" in
  webserver)
    airflow db init
		sleep 5
    exec airflow webserver
    ;;
  *)
    echo "Sleeping 15 seconds before running: 'airflow $@'"
    sleep 15
    exec airflow "$@"
    ;;
esac
```

Deploy this image on ECS with the above mentioned environment variables with a postgres and redis backend.

### Operating System

Local: Ubuntu-20.04, On ECS: Lunix_X86_64

### Versions of Apache Airflow Providers

apache-airflow-providers-amazon==8.6.0
apache-airflow-providers-celery==3.3.3
apache-airflow-providers-common-sql==1.7.1
apache-airflow-providers-ftp==3.5.1
apache-airflow-providers-http==4.5.1
apache-airflow-providers-imap==3.3.1
apache-airflow-providers-sqlite==3.4.3

### Deployment

Other

### Deployment details

Deployed in ECS with terraform with following specs:

- 4 sepecate services (flower, webserver, scheduler, worker)
- All services run in same security group
- A ElastiCache redis cluster: engine 4.0.10 (with security group allowing airflow access to the cluster)
- A postgres SQL database: engine 13.12  (with security group allowing airflow access to the cluster)

### Anything else

This problem occurs on every task that is being run.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by ekloos** [comment]
After further investiagtion I found the problem. The worker was runnig out of memory once celery tried torun a subprocess on the container. After incrasing the amount of CPU's the problem was resolved.
