### ISSUE TITLE
Airflow web doesn't work when set sql_alchemy_pool_enabled to false

### ISSUE THREAD

**Issue by zhenghanyang** [apache/airflow#34950]
### Apache Airflow version

2.7.2

### What happened

When I set sql_alchemy_pool_enabled to false
https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#config-database-sql-alchemy-pool-enabled

The airflow web report following error:
```
TypeError: Invalid argument(s) 'pool_size' sent to create_engine(), using configuration AuroraMySQLDataAPIDialect/NullPool/Engine.  Please check that the keyword arguments are appropriate for this combination of components.
```

### What you think should happen instead

This is a known issue of flask-sqlalchemy before Flask-SQLAlchemy 3.0.0
https://github.com/pallets-eco/flask-sqlalchemy/issues/803

Already fixed at v3.0.0, can airflow upgrade the version of Flask-SQLAlchemy to 3.0.0 or higher?
https://flask-sqlalchemy.palletsprojects.com/en/3.0.x/changes/
```
MySQL engines do not set pool_size to 10.
MySQL engines don’t set a default for pool_recycle if not using a queue pool. [#803]
```

The lastest airflow is still using Flask-SQLAlchemy 2.5.1
https://raw.githubusercontent.com/apache/airflow/constraints-2.7.2/constraints-3.8.txt

I try to comment the three lines in flask-sqlalchemy, then airflow web works fine
```python
            # if sa_url.drivername != 'mysql+gaerdbms':
                # options.setdefault('pool_size', 10)
                # options.setdefault('pool_recycle', 7200)
```

### How to reproduce

Using mysql as airflow meta db, set set sql_alchemy_pool_enabled to false, then open airflow web page, it will report error

### Operating System

Redhat 8.4

### Versions of Apache Airflow Providers

https://raw.githubusercontent.com/apache/airflow/constraints-2.7.2/constraints-3.8.txt
Flask-SQLAlchemy==2.5.1

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
> Already fixed at v3.0.0, can airflow upgrade the version of Flask-SQLAlchemy to 3.0.0 or higher?

Until FAB (Flask-AppBuilder) won't support it we can't upgrade it.

```console
root@10edf5592a3c:/opt/airflow# pipdeptree --packages flask-sqlalchemy -r
Flask-SQLAlchemy==2.5.1
└── Flask-AppBuilder==4.3.6 [requires: Flask-SQLAlchemy>=2.4,<3]
    └── apache-airflow==2.8.0.dev0 [requires: Flask-AppBuilder==4.3.6
```

---

Unfortunetly, I can't reproduce on main branch:
- run in [breeze](https://github.com/apache/airflow/blob/main/BREEZE.rst)
- MySQL 8.0
- ARM (need to check on X86_64)

![image](https://github.com/apache/airflow/assets/3998685/0bed99cc-3dd2-4d3f-9dd8-743dfa3a7cd3)

Maybe some additional settings also should be set?

**Comment by Taragolis** [comment]
Check again on fresh installed airflow, and I've got an error

```console
[2023-10-19 22:57:46 +0000] [52] [ERROR] Error handling request /favicon.ico
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/_collections.py", line 1008, in __call__
    return self.registry[key]
KeyError: <greenlet.greenlet object at 0x7f08400744c0 (otid=0x7f083f68ab10) current active started main>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    ctx.push()
  File "/home/airflow/.local/lib/python3.8/site-packages/flask/ctx.py", line 375, in push
    self.session = session_interface.open_session(self.app, self.request)
  File "/home/airflow/.local/lib/python3.8/site-packages/flask_session/sessions.py", line 523, in open_session
    saved_session = self.sql_session_model.query.filter_by(
  File "/home/airflow/.local/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 552, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/scoping.py", line 47, in __call__
    sess = self.registry()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/_collections.py", line 1010, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 4279, in __call__
    return self.class_(**local_kw)
  File "/home/airflow/.local/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 176, in __init__
    bind = options.pop('bind', None) or db.engine
  File "/home/airflow/.local/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 998, in engine
    return self.get_engine()
  File "/home/airflow/.local/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 1017, in get_engine
    return connector.get_engine()
  File "/home/airflow/.local/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 594, in get_engine
    self._engine = rv = self._sa.create_engine(sa_url, options)
  File "/home/airflow/.local/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 1027, in create_engine
    return sqlalchemy.create_engine(sa_url, **engine_opts)
  File "<string>", line 2, in create_engine
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/deprecations.py", line 375, in warned
    return fn(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 632, in create_engine
    raise TypeError(
TypeError: Invalid argument(s) 'pool_size' sent to create_engine(), using configuration MySQLDialect_mysqldb/NullPool/Engine.  Please check that the keyword arguments are appropriate for this combination of components.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/airflow/.local/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 178, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/airflow/.local/lib/python3.8/site-packages/flask/app.py", line 2552, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/airflow/.local/lib/python3.8/site-packages/flask/app.py", line 2532, in wsgi_app
    response = self.handle_exception(e)
  File "/home/airflow/.local/lib/python3.8/site-packages/flask/app.py", line 1727, in handle_exception
    server_error = self.ensure_sync(handler)(server_error)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/www/views.py", line 658, in show_traceback
    is_logged_in = get_auth_manager().is_logged_in()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/auth/managers/fab/fab_auth_manager.py", line 58, in is_logged_in
    return not self.get_user().is_anonymous
  File "/home/airflow/.local/lib/python3.8/site-packages/werkzeug/local.py", line 316, in __get__
    obj = instance._get_current_object()
  File "/home/airflow/.local/lib/python3.8/site-packages/werkzeug/local.py", line 520, in _get_current_object
    return get_name(local())  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/flask_login/utils.py", line 25, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "/home/airflow/.local/lib/python3.8/site-packages/flask_login/utils.py", line 372, in _get_user
    current_app.login_manager._load_user()
  File "/home/airflow/.local/lib/python3.8/site-packages/flask_login/login_manager.py", line 362, in _load_user
    user_id = session.get("_user_id")
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by zhenghanyang** [comment]
Yes, then just comment following three lines in "/home/airflow/.local/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", webserver can work normally.
```python
# if sa_url.drivername != 'mysql+gaerdbms':
#    options.setdefault('pool_size', 10)
#    options.setdefault('pool_recycle', 7200)
```

**Comment by Taragolis** [comment]
Until [FAB](https://github.com/dpgaspar/Flask-AppBuilder/blob/master/setup.py#L55-L58) won't upgrade dependency nothing we could do here, Flask-SQLAlchemy is not an [Airflow dependancy](https://github.com/apache/airflow/blob/7d80b7d5e48bf9f289337135f8721e01fc98d694/setup.cfg#L68)

**Comment by potiuk** [comment]
Yes @zhenghanyang -> I suggest to open an issue to FAB for that one. It is more efficient if the person who has an interest in it directly follows up with the root dependency and explains the problem there.

**Comment by potiuk** [comment]
Marking it as "upstream-dependency"
