### ISSUE TITLE
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:pymssql

### ISSUE THREAD

**Issue by foylaou** [apache/airflow#35468]
### Apache Airflow version

2.7.2

### What happened

```console
user-airflow-worker-1     | BACKEND=redis
user-airflow-worker-1     | DB_HOST=redis
user-airflow-worker-1     | DB_PORT=6379
user-airflow-worker-1     |
user-airflow-worker-1     | Traceback (most recent call last):
user-airflow-worker-1     |   File "/home/airflow/.local/bin/airflow", line 8, in <module>
user-airflow-worker-1     |     sys.exit(main())
user-airflow-worker-1     |   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/__main__.py", line 59, in main
user-airflow-worker-1     |     args.func(args)
user-airflow-worker-1     |   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/cli_config.py", line 49, in command
user-airflow-worker-1     |     return func(*args, **kwargs)
user-airflow-worker-1     |   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/cli.py", line 113, in wrapper
user-airflow-worker-1     |     return f(*args, **kwargs)
user-airflow-worker-1     |   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/providers_configuration_loader.py", line 55, in wrapped_function
user-airflow-worker-1     |     return func(*args, **kwargs)
user-airflow-worker-1     |   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/celery_command.py", line 171, in worker
user-airflow-worker-1     |     session = celery_app.backend.ResultSession()
user-airflow-worker-1     |   File "/home/airflow/.local/lib/python3.8/site-packages/celery/backends/database/__init__.py", line 106, in ResultSession
user-airflow-worker-1     |     return session_manager.session_factory(
user-airflow-worker-1     |   File "/home/airflow/.local/lib/python3.8/site-packages/celery/backends/database/session.py", line 87, in session_factory
user-airflow-worker-1     |     engine, session = self.create_session(dburi, **kwargs)
user-airflow-worker-1     |   File "/home/airflow/.local/lib/python3.8/site-packages/celery/backends/database/session.py", line 56, in create_session
user-airflow-worker-1     |     engine = self.get_engine(dburi, **kwargs)
user-airflow-worker-1     |   File "/home/airflow/.local/lib/python3.8/site-packages/celery/backends/database/session.py", line 53, in get_engine
user-airflow-worker-1     |     return create_engine(dburi, poolclass=NullPool, **kwargs)
user-airflow-worker-1     |   File "<string>", line 2, in create_engine
user-airflow-worker-1     |   File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/deprecations.py", line 375, in warned
user-airflow-worker-1     |     return fn(*args, **kwargs)
user-airflow-worker-1     |   File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 518, in create_engine
user-airflow-worker-1     |     entrypoint = u._get_entrypoint()
user-airflow-worker-1     |   File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/url.py", line 662, in _get_entrypoint
user-airflow-worker-1     |     cls = registry.load(name)
user-airflow-worker-1     |   File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 343, in load
user-airflow-worker-1     |     raise exc.NoSuchModuleError(
user-airflow-worker-1     | sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:pymssql
```

### How to reproduce

AIRFLOW__CELERY__RESULT_BACKEND: db+pymssql://airflow:password@ip/airflow

### Operating System

windows-wsl-ubuntu22.04.2-docker-v24.0.7

### Deployment

Docker-Compose

### Deployment details

dockerfile:
```dockerfile
# Use the official Apache Airflow image as the base image
FROM apache/airflow:2.7.2
```

```console
# Install the required dependencies, including pymssql
RUN wget https://packages.microsoft.com/ubuntu/23.04/prod/pool/main/m/msodbcsql18/msodbcsql18_18.3.2.1-1_amd64.deb
RUN sudo dpkg -i msodbcsql18_18.3.2.1-1_arm64.deb
RUN python -m pip install --upgrade pip
RUN pip install pymssql
RUN pip install apache-airflow-providers-common-sql
RUN pip install sqlalchemy==2.0.23
RUN pip install pyodbc
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
There is quite a few different problem with installation and extending Airflow image in the one place

- Official Airflow image for 2.7.2 based on Debian Bullseye but you tried to install Ubuntu package. 
BTW, regular Airflow image already include ODBC Driver for Microsoft(R) SQL Server(R)

- Seems like you install python packages into the root userspace, however in the official image Airflow doesn't
use root user. You could follow [Building the image](https://airflow.apache.org/docs/docker-stack/build.html#building-the-image) guide.

> When adding packages via apt you should switch to the `root` user when running the apt commands, but do not forget to switch back to the `airflow` user after installation is complete.

- `sqlalchemy==2.0.23` - Airflow doesn't support SQLAlchemy 2 yet. The issue for tracking status: https://github.com/apache/airflow/issues/28723. But please note that this only related to the Airflow itself, other depenedncies might still required sqlalchemy<2

- Last but not least. Support of Microsoft SQL Server as DB backend for Airflow [will be discontinued soon](https://airflow.apache.org/docs/apache-airflow/2.7.2/howto/set-up-database.html#setting-up-a-mssql-database). It is not clear what kind of DB backend are you use but my assumption that is MsSQL
