### ISSUE TITLE
BUG: Scheduler falling during import

### ISSUE THREAD

**Issue by Arkoniak** [apache/airflow#357]
It's two bugs actually.
I am using airflow with postgres database for metadata, and import erroneous dags make scheduler stop. It can be reproduced as following:
1. in dags directory add bugged file div_zero.py 

``` python
from airflow import DAG

dag = DAG('div_zero_error')
1/0
```

Get next output in airflow scheduler command:

```
2015-09-03 17:21:30,322 - root - INFO - Starting the scheduler
2015-09-03 17:21:30,322 - root - INFO - Filling up the DagBag from /usr/local/opr/airflow/dags
2015-09-03 17:21:30,339 - root - INFO - Importing /usr/local/opr/airflow/dags/div_zero.py
2015-09-03 17:21:30,339 - root - ERROR - Failed to import: /usr/local/opr/airflow/dags/div_zero.py
2015-09-03 17:21:30,339 - root - ERROR - integer division or modulo by zero
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/airflow/models.py", line 175, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/opr/airflow/dags/div_zero.py", line 4, in <module>
    1/0
ZeroDivisionError: integer division or modulo by zero
2015-09-03 17:21:30,438 - root - INFO - Done queuing tasks, calling the executor's heartbeat
2015-09-03 17:21:30,439 - root - INFO - Loop took: 0.095398 seconds
2015-09-03 17:21:30,442 - root - ERROR - (psycopg2.ProgrammingError) can't adapt type 'exceptions.ZeroDivisionError' [SQL: 'INSERT INTO import_error (timestamp, filename, stacktrace) VALUES (%(timestamp)s, %(filename)s, %(stacktrace)s) RETURNING import_error.id'] [parameters: {'stacktrace': ZeroDivisionError('integer division or modulo by zero',), 'filename': u'/usr/local/opr/airflow/dags/div_zero.py', 'timestamp': None}]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/airflow/jobs.py", line 517, in _execute
    self.import_errors(dagbag)
  File "/usr/local/lib/python2.7/dist-packages/airflow/jobs.py", line 306, in import_errors
    session.commit()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 790, in commit
    self.transaction.commit()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 392, in commit
    self._prepare_impl()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 372, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2004, in flush
    self._flush(objects)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2122, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2086, in _flush
    flush_context.execute()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
    rec.execute(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
    uow
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 174, in save_obj
    mapper, table, insert)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 781, in _emit_insert_statements
    execute(statement, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
ProgrammingError: (psycopg2.ProgrammingError) can't adapt type 'exceptions.ZeroDivisionError' [SQL: 'INSERT INTO import_error (timestamp, filename, stacktrace) VALUES (%(timestamp)s, %(filename)s, %(stacktrace)s) RETURNING import_error.id'] [parameters: {'stacktrace': ZeroDivisionError('integer division or modulo by zero',), 'filename': u'/usr/local/opr/airflow/dags/div_zero.py', 'timestamp': None}]
2015-09-03 17:21:30,446 - root - ERROR - This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.ProgrammingError) can't adapt type 'exceptions.ZeroDivisionError' [SQL: 'INSERT INTO import_error (timestamp, filename, stacktrace) VALUES (%(timestamp)s, %(filename)s, %(stacktrace)s) RETURNING import_error.id'] [parameters: {'stacktrace': ZeroDivisionError('integer division or modulo by zero',), 'filename': u'/usr/local/opr/airflow/dags/div_zero.py', 'timestamp': None}]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/airflow/jobs.py", line 523, in _execute
    self.heartbeat()
  File "/usr/local/lib/python2.7/dist-packages/airflow/jobs.py", line 126, in heartbeat
    job = session.query(BaseJob).filter(BaseJob.id == self.id).first()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2445, in first
    ret = list(self[0:1])
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2281, in __getitem__
    return list(res)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2516, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2529, in _execute_and_instances
    close_with_result=True)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2520, in _connection_from_session
    **kw)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 882, in connection
    execution_options=execution_options)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 887, in _connection_for_bind
    engine, execution_options)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 313, in _connection_for_bind
    self._assert_active()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 214, in _assert_active
    % self._rollback_exception
InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.ProgrammingError) can't adapt type 'exceptions.ZeroDivisionError' [SQL: 'INSERT INTO import_error (timestamp, filename, stacktrace) VALUES (%(timestamp)s, %(filename)s, %(stacktrace)s) RETURNING import_error.id'] [parameters: {'stacktrace': ZeroDivisionError('integer division or modulo by zero',), 'filename': u'/usr/local/opr/airflow/dags/div_zero.py', 'timestamp': None}]
2015-09-03 17:21:30,447 - root - ERROR - Tachycardia!
2015-09-03 17:21:30,447 - root - ERROR - This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.ProgrammingError) can't adapt type 'exceptions.ZeroDivisionError' [SQL: 'INSERT INTO import_error (timestamp, filename, stacktrace) VALUES (%(timestamp)s, %(filename)s, %(stacktrace)s) RETURNING import_error.id'] [parameters: {'stacktrace': ZeroDivisionError('integer division or modulo by zero',), 'filename': u'/usr/local/opr/airflow/dags/div_zero.py', 'timestamp': None}]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/airflow/jobs.py", line 480, in _execute
    self.prioritize_queued(executor=executor, dagbag=dagbag)
  File "/usr/local/lib/python2.7/dist-packages/airflow/utils.py", line 292, in wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/airflow/jobs.py", line 420, in prioritize_queued
    pools = {p.pool: p for p in session.query(models.Pool).all()}
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2399, in all
    return list(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2516, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2529, in _execute_and_instances
    close_with_result=True)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2520, in _connection_from_session
    **kw)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 882, in connection
    execution_options=execution_options)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 887, in _connection_for_bind
    engine, execution_options)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 313, in _connection_for_bind
    self._assert_active()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 214, in _assert_active
    % self._rollback_exception
InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.ProgrammingError) can't adapt type 'exceptions.ZeroDivisionError' [SQL: 'INSERT INTO import_error (timestamp, filename, stacktrace) VALUES (%(timestamp)s, %(filename)s, %(stacktrace)s) RETURNING import_error.id'] [parameters: {'stacktrace': ZeroDivisionError('integer division or modulo by zero',), 'filename': u'/usr/local/opr/airflow/dags/div_zero.py', 'timestamp': None}]
```

1) It seems that for some reason psycopg2 unable to autoconvert Error to string. It can be fixed in jobs.py/import_errors function

``` python
    def import_errors(self, dagbag):
        session = settings.Session()
        session.query(models.ImportError).delete()
        for filename, stacktrace in list(dagbag.import_errors.items()):
            session.add(models.ImportError(
                filename=filename, stacktrace=str(stacktrace)))
        session.commit()
```

but i think it's not the best solution.

2) Also, scheduler is falling despite it should never ever stop. Nonetheless it can be fixed by wrapping body of while loop in additional try except block

``` python
while not self.num_runs or self.num_runs > i:
    try:
        <while body>
    except Exception e:
        pass
```

but once again, may be there is better solution.

**Comment by mistercrunch** [comment]
The problem is that there's a postgres specific bug (no exception autocast as str) in the except block...
https://github.com/airbnb/airflow/pull/376

I did add try catchall block. This should prevent even exceptions in underlying except blocks.
