### ISSUE TITLE
Inconsistent sensor timeout behaviour

### ISSUE THREAD

**Issue by nathadfield** [apache/airflow#36734]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### If "Other Airflow 2 version" selected, which one?

2.7.3

### What happened?

The behaviour of how sensors react to timeouts seems to be inconsistent when running in deferrable mode.  

In the [documentation](https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/tasks.html#timeouts) it states that, for sensors in `reschedule` mode, once the timeout is reached the task is failed and does not retry.  This is exactly what occurs when running an `S3KeySensor` and, in my opinion, is the correct behaviour for how we want to work with sensors.

```
[2024-01-11, 14:21:06 UTC] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='s3', conn_type='S3') credentials retrieved from login and password.
[2024-01-11, 14:21:07 UTC] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/providers/amazon/aws/sensors/s3.py", line 144, in execute
    super().execute(context)
  File "/usr/local/lib/python3.11/site-packages/airflow/sensors/base.py", line 274, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 10.264439 seconds exceeds the specified timeout of 10.0.
[2024-01-11, 14:21:07 UTC] {taskinstance.py:1400} INFO - Immediate failure requested. Marking task as FAILED. dag_id=sensor_timeout, task_id=sensor_test, execution_date=20240104T070000, start_date=20240111T142106, end_date=20240111T142107 
```

However, the same sensor running in deferrable mode sends the task into an `UP_FOR_RETRY` state.
```
[2024-01-11, 14:20:59 UTC] {base.py:73} INFO - Using connection ID 's3' for task execution.
[2024-01-11, 14:20:59 UTC] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='s3', conn_type='S3') credentials retrieved from login and password.
[2024-01-11, 14:21:16 UTC] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_timeout.sensor_test_defer scheduled__2024-01-04T07:00:00+00:00 [queued]>
[2024-01-11, 14:21:16 UTC] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_timeout.sensor_test_defer scheduled__2024-01-04T07:00:00+00:00 [queued]>
[2024-01-11, 14:21:16 UTC] {taskinstance.py:1359} INFO - Resuming after deferral
[2024-01-11, 14:21:16 UTC] {taskinstance.py:1382} INFO - Executing <Task(S3KeySensor): sensor_test_defer> on 2024-01-04 07:00:00+00:00
[2024-01-11, 14:21:16 UTC] {standard_task_runner.py:57} INFO - Started process 2301 to run task
[2024-01-11, 14:21:16 UTC] {standard_task_runner.py:85} INFO - Job 8: Subtask sensor_test_defer
[2024-01-11, 14:21:16 UTC] {task_command.py:416} INFO - Running <TaskInstance: sensor_timeout.sensor_test_defer scheduled__2024-01-04T07:00:00+00:00 [running]> on host 2403ea01d798
[2024-01-11, 14:21:16 UTC] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/sensors/base.py", line 292, in resume_execution
    return super().resume_execution(next_method, next_kwargs, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 1601, in resume_execution
    raise TaskDeferralError(next_kwargs.get("error", "Unknown"))
airflow.exceptions.TaskDeferralError: Trigger/execution timeout
[2024-01-11, 14:21:16 UTC] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=sensor_timeout, task_id=sensor_test_defer, execution_date=20240104T070000, start_date=20240111T142056, end_date=20240111T142116
```

### What you think should happen instead?

I believe that the behaviour of how sensors react to timeout should be consistent regardless of whether the task is deferred or not and, if the timeout is reached, the task should be failed and not put up for retry.

Please not, this is not specifically about the `S3KeySensor` I just used this as an example.  The same behaviour is true of any sensor that implements deferrable capabilities.

### How to reproduce

Here is an example DAG that will replicate the problem as I see it.

```
from datetime import datetime
from airflow import models
from airflow.providers.amazon.aws.sensors.s3 import S3KeySensor

with models.DAG(
    dag_id='sensor_timeout',
    start_date=datetime(2018, 10, 31),
    schedule='0 7 * * 4',
    catchup=False,
    max_active_runs=5,
):
    sensor = S3KeySensor(
        task_id='sensor_test',
        aws_conn_id='s3',
        bucket_name='my-s3-bucket',
        bucket_key='path/to/an/object',
        retries=3,
        wildcard_match=True,
        poke_interval=2,
        timeout=10,
        mode='reschedule',
        deferrable=False
    )

    sensor_defer = S3KeySensor(
        task_id='sensor_test_defer',
        aws_conn_id='s3,
        bucket_name='my-s3-bucket',
        bucket_key='path/to/an/object',
        retries=3,
        wildcard_match=True,
        timeout=10,
        deferrable=True,
    )
```

### Operating System

PRETTY_NAME="Debian GNU/Linux 11 (bullseye)" NAME="Debian GNU/Linux" VERSION_ID="11" VERSION="11 (bullseye)" VERSION_CODENAME=bullseye ID=debian HOME_URL="https://www.debian.org/" SUPPORT_URL="https://www.debian.org/support" BUG_REPORT_URL="https://bugs.debian.org/"

### Versions of Apache Airflow Providers

apache-airflow-providers-amazon==8.13.0

### Deployment

Astronomer

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by akshith-yalla** [comment]
Hi maintainers,

I’ve retested the behavior described in [this issue](https://github.com/apache/airflow/issues/36734) and observed that the inconsistent sensor timeout behavior persists. Specifically, while sensors in **reschedule mode correctly fail** when the timeout is reached, sensors running in **deferrable mode** are being marked as `UP_FOR_RETRY` instead of **failing immediately**.

For clarity, I’ve documented my observations, including reproduction steps, log outputs, and several solution approaches, below:

Bug: Inconsistent sensor timeout behavior

Reproducible(Yes/No): Yes

Below are the same steps that I followed to reproduce the issue, as mentioned in the PR description:

A sample DAG to replicate the issue:

```
from datetime import datetime
from airflow import models
from airflow.providers.amazon.aws.sensors.s3 import S3KeySensor

with models.DAG(
    dag_id='sensor_timeout',
    start_date=datetime(2018, 10, 31),
    schedule='0 7 * * 4',
    catchup=False,
    max_active_runs=5,
):
    sensor = S3KeySensor(
        task_id='sensor_test',
        aws_conn_id='s3',
        bucket_name='my-s3-bucket', // s3 bucket name
        bucket_key='path/to/an/object', // path to object
        retries=3,
        wildcard_match=True,
        poke_interval=2,
        timeout=10,
        mode='reschedule',
        deferrable=False
    )

    sensor_defer = S3KeySensor(
        task_id='sensor_test_defer',
        aws_conn_id ='s3',
        bucket_name='my-s3-bucket', // s3 bucket name
        bucket_key='path/to/an/object', // path to object
        retries=3,
        wildcard_match=True,
        timeout=10,
        deferrable=True,
    )
```


Status of the DAG runs:

![Image](https://github.com/user-attachments/assets/428dfcbb-d8d7-41ae-8d49-f9c130a37090)

Logs with deferred value set to false:

![Image](https://github.com/user-attachments/assets/85accdc6-334f-4282-9053-074c90d6c7b7)

Logs with deferred value set to true:

![Image](https://github.com/user-attachments/assets/6246c688-d794-4ed3-a7d7-de700bc40b1c)

Solution Approaches that I have tried:

1. I have adjusted the **timeout logic** to prevent further retries when the run duration exceeds the timeout.
```
if run_duration() > self.timeout:
    # If sensor is in soft fail mode but times out raise AirflowSkipException.
    message = (
        f"Sensor has timed out; run duration of {run_duration()} seconds exceeds "
        f"the specified timeout of {self.timeout}."
    )
    # Prevent further retries by setting max_tries equal to the current try number.
    context["ti"].max_tries = context["ti"].try_number
    if self.soft_fail:
        raise AirflowSkipException(message)
    else:
        raise AirflowSensorTimeout(message)
```
2. Modified `resume_execution` to convert deferral-related errors into sensor timeouts.
```
def resume_execution(self, next_method: str, next_kwargs: dict[str, Any] | None, context: Context):
   try:
       return super().resume_execution(next_method, next_kwargs, context)
   except TaskDeferralTimeout as e:
       raise AirflowSensorTimeout(*e.args) from e
   except (AirflowException, TaskDeferralError) as e:
       # Convert any deferral-related error into a sensor timeout to fail the task.
       raise AirflowSensorTimeout(str(e)) from e
```
3. Added a check in `base.py` to handle` trigger/execution` timeouts for all sensors.
```
def resume_execution(self, next_method: str, next_kwargs: dict[str, Any] | None, context: Context):
   try:
       return super().resume_execution(next_method, next_kwargs, context)
   except TaskDeferralTimeout as e:
       raise AirflowSensorTimeout(*e.args) from e
   except TaskDeferralError as e:
       # Handle cases where the trigger or execution times out
       if "timeout" in str(e).lower():
           message = f"Sensor has timed out: {e}"
           if self.soft_fail:
               raise AirflowSkipException(message) from e
           else:
               raise AirflowSensorTimeout(message) from e
       else:
           if self.soft_fail:
               raise AirflowSkipException(str(e)) from e
           raise
   except AirflowException as e:
       if self.soft_fail:
           raise AirflowSkipException(str(e)) from e
       raise
```
4.  Further refined `resume_execution` to ensure a non-retryable failure on deferral timeout.
```
def resume_execution(self, next_method: str, next_kwargs: dict[str, Any] | None, context: Context):
   try:
       return super().resume_execution(next_method, next_kwargs, context)
   except TaskDeferralTimeout as e:
       # Convert deferral timeout to a non-retryable failure
       message = f"Sensor has timed out: {e}"
       raise AirflowFailException(message) from e
   except TaskDeferralError as e:
       # Handle timeout-related deferral errors
       if "timeout" in str(e).lower():
           message = f"Sensor has timed out: {e}"
           raise AirflowFailException(message) from e
       else:
           # Handle other deferral errors based on configuration
           if self.soft_fail:
               raise AirflowSkipException(str(e)) from e
           raise
   except AirflowException as e:
       # Handle other Airflow exceptions
       if self.soft_fail:
           raise AirflowSkipException(str(e)) from e
       raise
```

**PS:** One thing that I observed was that it was eventually going to a `FAILED` state, but after some time and not immediately.

 Please find the screenshot and the logs below:

![Image](https://github.com/user-attachments/assets/81750619-83a8-4db6-8cb6-e5857989066e)

---
I believe that ensuring consistent failure behavior across both modes is crucial for reliable sensor operations. I’d appreciate any insights or suggestions on how to move forward with a fix.

Thank you for your attention to this matter.

---

**Comment by nathadfield** [comment]
@akshith-yalla Thanks for taking a look and confirming this is still an issue.  I am going to reopen this.

**Comment by Abhishek1559** [comment]
Hi maintainers,

Based on the discussion till now and testing, I have replicated the issue with FileSensor and S3 sensor DAGs. 
Following are the observations I had:
The issue no longer exists in version 3.x.x.
Tested for S3 as well as Filesensor to confirm the behavior for different sensor dags and found out that dags in standard as well as deferrable mode, fail as expected and do not go for retry. 
The DAGs in both the modes acted as expected and threw an ‘AirflowSensorTimeout’ as expected in both the cases.
The same helps me conclude that the issue no longer exists and this can be closed now.

Test 1.
While testing for the bug (Airflow 3.1.0) with FileSensor, I followed the following code snippet:
‘’’
from airflow import DAG
from airflow.sensors.filesystem import FileSensor
from datetime import datetime, timedelta

default_args = {
   'owner': 'you',
   'start_date': datetime(2025, 7, 1)
}

with DAG(
   dag_id="test_sensor_timeout_bug",
   default_args=default_args,
   catchup=False,
   tags=["sensor", "timeout"],
) as dag:

   # Poke mode sensor (normal blocking)
   poke_sensor = FileSensor(
       task_id="poke_sensor",
       filepath="/tmp/nonexistent_file.txt",
       retries=3,
       poke_interval=5,
       timeout=10,
       mode='reschedule',
       deferrable=False,
       fs_conn_id="fs_local",

   )

   #  Reschedule (deferrable) sensor — to reproduce the bug
   deferred_sensor = FileSensor(
       task_id="deferred_sensor",
       filepath="/tmp/nonexistent_file.txt",
       retries=3,
       timeout=10,
       deferrable=True,
       fs_conn_id="fs_local"
   )

‘’’


The DAGs in both the modes acted as expected and threw an ‘AirflowSensorTimeout’ as expected and failed immediately in both the cases as shown in the below logs.

Poke mode:

<img width="1854" height="964" alt="Image" src="https://github.com/user-attachments/assets/e362c65d-6a59-4bea-bb70-84cef05bc1c0" />


Deferrable mode:

<img width="1854" height="952" alt="Image" src="https://github.com/user-attachments/assets/743c26ef-9c6d-4033-9c24-88cba8efcb1f" />

Test 2:

While testing for the bug (Airflow 3.1.0) with S3, I followed the following code snippet:

‘’’
from datetime import datetime
from airflow import models
from airflow.providers.amazon.aws.sensors.s3 import S3KeySensor

with models.DAG(
   dag_id='sensor_timeout',
   start_date=datetime(2018, 10, 31),
   schedule='0 7 * * 4',
   catchup=False,
   max_active_runs=5,
):
   sensor = S3KeySensor(
       task_id='sensor_test',
       aws_conn_id='aks_aws',
       bucket_name='s3-bucket-name', # s3 bucket name
       bucket_key='path/to/an/object', #path to object
       retries=3,
       wildcard_match=True,
       poke_interval=2,
       timeout=10,
       mode='reschedule',
       deferrable=False
   )

   sensor_defer = S3KeySensor(
       task_id='sensor_test_defer',
       aws_conn_id='aks_aws',
       bucket_name='s3-bucket-name',  # s3 bucket name
       bucket_key='path/to/an/object', #path to object
       retries=3,
       wildcard_match=True,
       timeout=10,
       deferrable=True,
   )

‘’’

The DAGs in both the modes acted as expected and threw an ‘AirflowSensorTimeout’ as expected and failed immediately in both the cases as shown in the below logs.

Poke mode:

<img width="1854" height="960" alt="Image" src="https://github.com/user-attachments/assets/2d9dce71-f013-483a-8e5e-4a6de563e92d" />



Deferrable mode:

<img width="1854" height="964" alt="Image" src="https://github.com/user-attachments/assets/88616a58-92e9-407b-978c-6d49862bee6d" />




This confirms the consistent behavior for S3 Sensor Dags in both the modes. They are performing as expected and failing immediately.



The inconsistency does not exist as shown in the testing. If you find the research and testing relevant, we can close the issue.

Anything that I have missed/misunderstood or any suggestions or feedback is welcomed.

**Comment by pierrejeambrun** [comment]
Thanks @Abhishek1559 for testing this.

Since it has been fixed in AF3 I'm going to close the issue. Realistically I don't think it will ever get fixed in 2.x, it's not critical and nobody even tried to fix it in a 1.5 year span. The fix for this one will be 'upgrade your airflow' I guess.
