### ISSUE TITLE
 TypeError: SqlAlchemySessionInterface.__init__() missing 6 required positional arguments

### ISSUE THREAD

**Issue by habibutsu** [apache/airflow#36883]
### Apache Airflow version

2.8.0

### What happened?

airflow is not started

### How to reproduce

Install the latest version of Airflow. In the new release [Flask-Session==0.6.0](https://pypi.org/project/Flask-Session/0.6.0/) has introduced backward-incompatible [changes](https://github.com/pallets-eco/flask-session/blob/0.6.1rc1/src/flask_session/sessions.py#L559)

### Operating System

Linux/docker

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
We noticed that when if failed in our CI and this is fine when new version package breaks something.
- Temporary we upper bound limit it by https://github.com/apache/airflow/pull/36895
- The target solution could be tracked in: https://github.com/apache/airflow/issues/36897

For end users there the base recommendation is follow:
- [Installation of Airflow™](https://airflow.apache.org/docs/apache-airflow/stable/installation/index.html#using-pypi)
- [[Reminder] How to reproducibly install Airflow](https://lists.apache.org/thread/b8q1t3pvtky7y7mb2kjt4r2bz5bvz8qy)

**Comment by aiqc** [comment]
Ran into this on a fresh install today

I'm using 3.8 because that's what PyPI says: "Requires: Python <3.12, ~=3.8"
```
pip show apache-airflow
Name: apache-airflow
Version: 2.8.1

python --version
Python 3.8.18

lsb_release -a
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy

```

## Steps to reproduce

Setup
```bash
conda create -n pipeline python=3.8.18
conda activate pipeline

pip install apache-airflow

airflow db init
```

Produces the following output
```
/home/layne/anaconda3/envs/pipeline/lib/python3.8/site-packages/airflow/cli/commands/db_command.py:47 DeprecationWarning: `db init` is deprecated.  Use `db migrate` instead to migrate the db and/or airflow connections create-default-connections to create the default connections
DB: sqlite:////home/layne/airflow/airflow.db
[2024-02-22T09:57:42.303-0500] {migration.py:216} INFO - Context impl SQLiteImpl.
[2024-02-22T09:57:42.304-0500] {migration.py:219} INFO - Will assume non-transactional DDL.
Traceback (most recent call last):
  File "/home/layne/anaconda3/envs/pipeline/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/home/layne/anaconda3/envs/pipeline/lib/python3.8/site-packages/airflow/__main__.py", line 57, in main
    args.func(args)
  File "/home/layne/anaconda3/envs/pipeline/lib/python3.8/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/layne/anaconda3/envs/pipeline/lib/python3.8/site-packages/airflow/utils/providers_configuration_loader.py", line 55, in wrapped_function
    return func(*args, **kwargs)
  File "/home/layne/anaconda3/envs/pipeline/lib/python3.8/site-packages/airflow/cli/commands/db_command.py", line 53, in initdb
    db.initdb()
  File "/home/layne/anaconda3/envs/pipeline/lib/python3.8/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/layne/anaconda3/envs/pipeline/lib/python3.8/site-packages/airflow/utils/db.py", line 733, in initdb
    _create_db_from_orm(session=session)
  File "/home/layne/anaconda3/envs/pipeline/lib/python3.8/site-packages/airflow/utils/db.py", line 718, in _create_db_from_orm
    _create_flask_session_tbl(engine.url)
  File "/home/layne/anaconda3/envs/pipeline/lib/python3.8/site-packages/airflow/utils/db.py", line 711, in _create_flask_session_tbl
    db = _get_flask_db(sql_database_uri)
  File "/home/layne/anaconda3/envs/pipeline/lib/python3.8/site-packages/airflow/utils/db.py", line 700, in _get_flask_db
    AirflowDatabaseSessionInterface(app=flask_app, db=db, table="session", key_prefix="")
TypeError: __init__() missing 6 required positional arguments: 'sequence', 'schema', 'bind_key', 'use_signer', 'permanent', and 'sid_length'
```

**Comment by potiuk** [comment]
Use constaints to install airflow : https://airflow.apache.org/docs/apache-airflow/stable/installation/installing-from-pypi.html

**Comment by aiqc** [comment]
@potiuk thanks. couldn't the airflow and python versions be inferred at runtime instead of pushing that complexity onto the user? in situations where a constraint file(s) is not defined, couldn't an error be raised?

**Comment by potiuk** [comment]
@potiuk thanks. couldn't the airflow and python versions be inferred at runtime instead of pushing that complexity onto the user? in situations where a constraint file(s) is not defined, couldn't an error be raised?

No and No

**Comment by potiuk** [comment]
And the reason for both is explained in the link I posted. You can also watch my presentation from Airlfow Summit if you want to know all the technical details https://airflowsummit.org/sessions/2023/mastering-dependencies-the-airflow-way/

Those two sources go into deep dive why the answer for both your questions is no.
