### ISSUE TITLE
404 Pod not found can be seen often 

### ISSUE THREAD

**Issue by paramjeet01** [apache/airflow#37090]
### Apache Airflow Provider(s)

cncf-kubernetes

### Versions of Apache Airflow Providers

apache-airflow-providers-cncf-kubernetes==7.11.0

### Apache Airflow version

2.7.3

### Operating System

Amazon Linux 2

### Deployment

Official Apache Airflow Helm Chart

### What happened

The pod ran successfully but the airflow is checking the cluster bit later and couldn't find the pod since it was terminated after the process succeeded. Now , Airflow thinks the pod is failed (not found ) retries the task

Error message : 
>   File "/opt/airflow/plugins/operators/kubernetes_pod_operator.py", line 153, in execute
    final_state, remote_pod, result = self.create_new_pod_for_operator(labels, launcher)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/cncf/kubernetes/operators/kubernetes_pod.py", line 544, in create_new_pod_for_operator
    self.patch_already_checked(self.pod)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/cncf/kubernetes/operators/kubernetes_pod.py", line 551, in patch_already_checked
    self.client.patch_namespaced_pod(pod.metadata.name, pod.metadata.namespace, body)
  File "/home/airflow/.local/lib/python3.9/site-packages/kubernetes/client/api/core_v1_api.py", line 16004, in patch_namespaced_pod
    (data) = self.patch_namespaced_pod_with_http_info(name, namespace, body, **kwargs)  # noqa: E501
  File "/home/airflow/.local/lib/python3.9/site-packages/kubernetes/client/api/core_v1_api.py", line 16095, in patch_namespaced_pod_with_http_info
    return self.api_client.call_api(
  File "/home/airflow/.local/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 340, in call_api
    return self.__call_api(resource_path, method,
  File "/home/airflow/.local/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 172, in __call_api
    response_data = self.request(
  File "/home/airflow/.local/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 398, in request
    return self.rest_client.PATCH(url,
  File "/home/airflow/.local/lib/python3.9/site-packages/kubernetes/client/rest.py", line 292, in PATCH
    return self.request("PATCH", url,
  File "/home/airflow/.local/lib/python3.9/site-packages/kubernetes/client/rest.py", line 231, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Mon, 29 Jan 2024 10:50:19 GMT', 'Content-Length': '262'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \"mypod-7499eea656f744bf97b7c1682e68eaac\" not found","reason":"NotFound","details":{"name":"mypod-7499eea656f744bf97b7c1682e68eaac","kind":"pods"},"code":404}

### What you think should happen instead

Airflow should constantly check for pod status and update the task status. Or the task will be retries when the pod is succeeded and terminated

### How to reproduce

Have a long running multiple tasks ~20 minutes , do xcom push , and let the pod be destroyed by kubernetes. You'll notice airflow with kubernetes api throws 404 not found.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by paramjeet01** [comment]
@dirrao , are you suggesting to use apache-airflow-providers-cncf-kubernetes==7.14.0 ?

**Comment by dirrao** [comment]
@paramjeet01 
Have you tried upgrading the cncf-kubernetes provider to latest version? Does it helped?

**Comment by paramjeet01** [comment]
@dirrao , I tried the latest cncf-kubernetes version and we still have this issue intermittently .

**Comment by paramjeet01** [comment]
@dirrao , Can you please take a look into this issue.

**Comment by potiuk** [comment]
Generally speaking the issue will be looked at someone when they pick interest in fixing it - I think there is no reason to expect that particular person will take  a look at it even if they commented on it @paramjeet01 -> I marked it as `good first issue` and maybe somoene will take a look at it - or if you would like to make sure that it's taken care of either take a look at it or find/sponsor somoene who will take a look at it faster. This is how Open-Source development work. Issues are taken care of when someone does take care of them and since it's for free and everyone is volunteer, you cannot expect them to work on issues because you think they should .

**Comment by pankajastro** [comment]
The logs trace you've shared appear to be quite old, and this execution path no longer exists. I believe it would be beneficial if you could try again with the latest version and share the updated logs.

**Comment by AronsonDan** [comment]
I see that issue quite a lot in our implementation.
We experience that a lot when setting deferrable mode.

I think in that case the pod was evicted either by Karpenter or spot instance was taken beck by AWS.
But when deferrable mode was on, we saw that error quite a lot even though the pods were succesfull

example log:
```python 
[2024-03-13, 15:00:23 UTC] {pod_manager.py:607} INFO - Pod run-mongo-collection-sync-orchestrator-w5v994bv has phase Running
[2024-03-13, 15:00:31 UTC] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/cncf/kubernetes/operators/pod.py", line 608, in execute_sync
    self.remote_pod = self.pod_manager.await_pod_completion(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/cncf/kubernetes/utils/pod_manager.py", line 602, in await_pod_completion
    remote_pod = self.read_pod(pod)
                 ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/tenacity/__init__.py", line 325, in iter
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/tenacity/__init__.py", line 158, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.11/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/cncf/kubernetes/utils/pod_manager.py", line 704, in read_pod
    return self._client.read_namespaced_pod(pod.metadata.name, pod.metadata.namespace)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/kubernetes/client/api/core_v1_api.py", line 23483, in read_namespaced_pod
    return self.read_namespaced_pod_with_http_info(name, namespace, **kwargs)  # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/kubernetes/client/api/core_v1_api.py", line 23570, in read_namespaced_pod_with_http_info
    return self.api_client.call_api(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
    response_data = self.request(
                    ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/kubernetes/client/api_client.py", line 373, in request
    return self.rest_client.GET(url,
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/kubernetes/client/rest.py", line 240, in GET
    return self.request("GET", url,
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/kubernetes/client/rest.py", line 234, in request
    raise ApiException(http_resp=r)
kubernetes.client.exceptions.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Audit-Id': '26ba592d-8b61-4888-b9bf-5066232dd535', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Kubernetes-Pf-Flowschema-Uid': '15741541-3633-4f53-9ae5-bcb4592de0f4', 'X-Kubernetes-Pf-Prioritylevel-Uid': '675c191c-7b76-46bc-b12f-d1820e389768', 'Date': 'Wed, 13 Mar 2024 15:00:28 GMT', 'Content-Length': '262'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \"run-mongo-collection-sync-orchestrator-w5v994bv\" not found","reason":"NotFound","details":{"name":"run-mongo-collection-sync-orchestrator-w5v994bv","kind":"pods"},"code":404}
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/cncf/kubernetes/operators/pod.py", line 554, in execute
    return self.execute_sync(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/cncf/kubernetes/operators/pod.py", line 613, in execute_sync
    self.cleanup(
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/cncf/kubernetes/operators/pod.py", line 736, in cleanup
    istio_enabled = self.is_istio_enabled(remote_pod)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/cncf/kubernetes/operators/pod.py", line 798, in is_istio_enabled
    remote_pod = self.pod_manager.read_pod(pod)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/tenacity/__init__.py", line 325, in iter
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/tenacity/__init__.py", line 158, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.11/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/cncf/kubernetes/utils/pod_manager.py", line 704, in read_pod
    return self._client.read_namespaced_pod(pod.metadata.name, pod.metadata.namespace)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/kubernetes/client/api/core_v1_api.py", line 23483, in read_namespaced_pod
    return self.read_namespaced_pod_with_http_info(name, namespace, **kwargs)  # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/kubernetes/client/api/core_v1_api.py", line 23570, in read_namespaced_pod_with_http_info
    return self.api_client.call_api(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
    response_data = self.request(
                    ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/kubernetes/client/api_client.py", line 373, in request
    return self.rest_client.GET(url,
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/kubernetes/client/rest.py", line 240, in GET
    return self.request("GET", url,
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/kubernetes/client/rest.py", line 234, in request
    raise ApiException(http_resp=r)
kubernetes.client.exceptions.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Audit-Id': 'd1bbf3e7-1823-4bd0-bb3c-b77af1cde651', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Kubernetes-Pf-Flowschema-Uid': '15741541-3633-4f53-9ae5-bcb4592de0f4', 'X-Kubernetes-Pf-Prioritylevel-Uid': '675c191c-7b76-46bc-b12f-d1820e389768', 'Date': 'Wed, 13 Mar 2024 15:00:31 GMT', 'Content-Length': '262'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \"run-mongo-collection-sync-orchestrator-w5v994bv\" not found","reason":"NotFound","details":{"name":"run-mongo-collection-sync-orchestrator-w5v994bv","kind":"pods"},"code":404}
[2024-03-13, 15:00:31 UTC] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=dynamic_run_mongo_collection_sync_orchestrator_dag, task_id=kubernetes_pod_operator, execution_date=20240313T144000, start_date=20240313T150016, end_date=20240313T150031
[2024-03-13, 15:00:31 UTC] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.11/site-packages/airflow/utils/context.py:207 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2024-03-13, 15:00:31 UTC] {base.py:83} INFO - Using connection ID 'slack_default' for task execution.
[2024-03-13, 15:00:31 UTC] {standard_task_runner.py:107} ERROR - Failed to execute job 158458 for task kubernetes_pod_operator ((404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Audit-Id': 'd1bbf3e7-1823-4bd0-bb3c-b77af1cde651', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Kubernetes-Pf-Flowschema-Uid': '15741541-3633-4f53-9ae5-bcb4592de0f4', 'X-Kubernetes-Pf-Prioritylevel-Uid': '675c191c-7b76-46bc-b12f-d1820e389768', 'Date': 'Wed, 13 Mar 2024 15:00:31 GMT', 'Content-Length': '262'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \"run-mongo-collection-sync-orchestrator-w5v994bv\" not found","reason":"NotFound","details":{"name":"run-mongo-collection-sync-orchestrator-w5v994bv","kind":"pods"},"code":404}
; 20)
[2024-03-13, 15:00:31 UTC] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-13, 15:00:31 UTC] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
```

**Comment by paramjeet01** [comment]
@AronsonDan , In karpenter you can set the annotation `do-not-evict` to solve the issue and yeah , with spot instances we cannot do anything at this point.

**Comment by jelmerk** [comment]
this is still an issue

**Comment by marcdjohossou** [comment]
Hello,
We've started to see this issue after moving from Airflow 2.3.4 (apache-airflow-providers-cncf-kubernetes==5.0.0) to Airflow 2.5.3 (apache-airflow-providers-cncf-kubernetes==7.10.0)
Last seen on 2024-08-02
Sample log
--------------------------------------------
[2024-08-02, 13:33:09 UTC] {taskinstance.py:1778} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/python3.8/lib/python3.8/site-packages/airflow/providers/cncf/kubernetes/operators/pod.py", line 613, in execute_sync
    self.pod_manager.fetch_requested_container_logs(
  File "/opt/python3.8/lib/python3.8/site-packages/airflow/providers/cncf/kubernetes/utils/pod_manager.py", line 537, in fetch_requested_container_logs
    status = self.fetch_container_logs(pod=pod, container_name=c, follow=follow_logs)
  File "/opt/python3.8/lib/python3.8/site-packages/airflow/providers/cncf/kubernetes/utils/pod_manager.py", line 463, in fetch_container_logs
    if not self.container_is_running(pod, container_name=container_name):
  File "/opt/python3.8/lib/python3.8/site-packages/airflow/providers/cncf/kubernetes/utils/pod_manager.py", line 595, in container_is_running
    remote_pod = self.read_pod(pod)
  File "/opt/python3.8/lib/python3.8/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "/opt/python3.8/lib/python3.8/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "/opt/python3.8/lib/python3.8/site-packages/tenacity/__init__.py", line 325, in iter
    raise retry_exc.reraise()
  File "/opt/python3.8/lib/python3.8/site-packages/tenacity/__init__.py", line 158, in reraise
    raise self.last_attempt.result()
  File "/opt/python3.8/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/opt/python3.8/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/opt/python3.8/lib/python3.8/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "/opt/python3.8/lib/python3.8/site-packages/airflow/providers/cncf/kubernetes/utils/pod_manager.py", line 668, in read_pod
    return self._client.read_namespaced_pod(pod.metadata.name, pod.metadata.namespace)
  File "/opt/python3.8/lib/python3.8/site-packages/kubernetes/client/api/core_v1_api.py", line 23483, in read_namespaced_pod
    return self.read_namespaced_pod_with_http_info(name, namespace, **kwargs)  # noqa: E501
  File "/opt/python3.8/lib/python3.8/site-packages/kubernetes/client/api/core_v1_api.py", line 23570, in read_namespaced_pod_with_http_info
    return self.api_client.call_api(
  File "/opt/python3.8/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
  File "/opt/python3.8/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
    response_data = self.request(
  File "/opt/python3.8/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 373, in request
    return self.rest_client.GET(url,
  File "/opt/python3.8/lib/python3.8/site-packages/kubernetes/client/rest.py", line 240, in GET
    return self.request("GET", url,
  File "/opt/python3.8/lib/python3.8/site-packages/kubernetes/client/rest.py", line 234, in request
    raise ApiException(http_resp=r)
kubernetes.client.exceptions.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Audit-Id': '198ceff6-56c9-4388-bec9-66d259dae756', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Kubernetes-Pf-Flowschema-Uid': '77910e62-75bc-4bc0-a56a-46b99420f62d', 'X-Kubernetes-Pf-Prioritylevel-Uid': '7079822d-2a41-4448-88c8-b6faf19a3948', 'Date': 'Fri, 02 Aug 2024 13:33:06 GMT', 'Content-Length': '228'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \"run-dataflow-pipeline-i8f3gl7i\" not found","reason":"NotFound","details":{"name":"run-dataflow-pipeline-i8f3gl7i","kind":"pods"},"code":404}
