### ISSUE TITLE
Error on Search boxes - Meetup and Blog

### ISSUE THREAD

**Issue by Satoshi-Sh** [apache/airflow#37412]
### What do you see as an issue?

When I open [Meetups](https://airflow.apache.org/meetups/) and [blog](https://airflow.apache.org/blog/), I see errors `Uncaught (in promise) TypeError: Cannot read properties of null (reading 'length')
    at new z.QueryLexer (chunk-5.fcf34.js:51:5541)
    at new z.QueryParser (chunk-5.fcf34.js:51:8236)
    at z.Query.<anonymous> (chunk-5.fcf34.js:47:232)
    at z.Index.query (chunk-5.fcf34.js:47:509)
    at z.Index.search (chunk-5.fcf34.js:47:214)
    at chunk-3.fcf34.js:1:1054` in the terminal.

![Screenshot from 2024-02-13 20-32-32](https://github.com/apache/airflow/assets/73622805/0e56e100-5438-4289-a8a6-e918d35cd31e)

### Solving the problem

I researched about the error but couldn't find the root cause. Blog and Meetups pages have the same search box. It must cause the error.  This might have something to do with the lunr library. 

### Anything else

If someone can guide me through the repo to fix the issue, it would be great. But feel free to make a PR on your own as well.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
This one related to the [airflow-site](https://github.com/apache/airflow-site) repo
