### ISSUE TITLE
Airflow installation bugs on fresh conda env

### ISSUE THREAD

**Issue by aiqc** [apache/airflow#37625]
## Steps to reproduce

Setup
```bash
conda create -n pipeline python=3.8.18
conda activate pipeline

pip install apache-airflow

airflow db init
```

Produces the following output
```
/home/layne/anaconda3/envs/pipeline/lib/python3.8/site-packages/airflow/cli/commands/db_command.py:47 DeprecationWarning: `db init` is deprecated.  Use `db migrate` instead to migrate the db and/or airflow connections create-default-connections to create the default connections
DB: sqlite:////home/layne/airflow/airflow.db
[2024-02-22T09:57:42.303-0500] {migration.py:216} INFO - Context impl SQLiteImpl.
[2024-02-22T09:57:42.304-0500] {migration.py:219} INFO - Will assume non-transactional DDL.
Traceback (most recent call last):
  File "/home/layne/anaconda3/envs/pipeline/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/home/layne/anaconda3/envs/pipeline/lib/python3.8/site-packages/airflow/__main__.py", line 57, in main
    args.func(args)
  File "/home/layne/anaconda3/envs/pipeline/lib/python3.8/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/layne/anaconda3/envs/pipeline/lib/python3.8/site-packages/airflow/utils/providers_configuration_loader.py", line 55, in wrapped_function
    return func(*args, **kwargs)
  File "/home/layne/anaconda3/envs/pipeline/lib/python3.8/site-packages/airflow/cli/commands/db_command.py", line 53, in initdb
    db.initdb()
  File "/home/layne/anaconda3/envs/pipeline/lib/python3.8/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/layne/anaconda3/envs/pipeline/lib/python3.8/site-packages/airflow/utils/db.py", line 733, in initdb
    _create_db_from_orm(session=session)
  File "/home/layne/anaconda3/envs/pipeline/lib/python3.8/site-packages/airflow/utils/db.py", line 718, in _create_db_from_orm
    _create_flask_session_tbl(engine.url)
  File "/home/layne/anaconda3/envs/pipeline/lib/python3.8/site-packages/airflow/utils/db.py", line 711, in _create_flask_session_tbl
    db = _get_flask_db(sql_database_uri)
  File "/home/layne/anaconda3/envs/pipeline/lib/python3.8/site-packages/airflow/utils/db.py", line 700, in _get_flask_db
    AirflowDatabaseSessionInterface(app=flask_app, db=db, table="session", key_prefix="")
TypeError: __init__() missing 6 required positional arguments: 'sequence', 'schema', 'bind_key', 'use_signer', 'permanent', and 'sid_length'
```

## Conda package doesn't even install
```
$ conda install apache-airflow

Collecting package metadata (current_repodata.json): done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
Solving environment: unsuccessful attempt using repodata from current_repodata.json, retrying with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
```

### Versions of Apache Airflow Providers

None installed

### Deployment

I'm using 3.8 because that's what PyPI says: "Requires: Python <3.12, ~=3.8"
```
$ pip show apache-airflow
Name: apache-airflow
Version: 2.8.1

$ python --version
Python 3.8.18

$ lsb_release -a
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy

>>> sqlite3.sqlite_version
'3.41.2'
```

**Comment by potiuk** [comment]
Use pip and costraints to install airflow https://airflow.apache.org/docs/apache-airflow/stable/installation/installing-from-pypi.html
