### ISSUE TITLE
New connection through plugin problems with Postgres

### ISSUE THREAD

**Issue by sergiohgz** [apache/airflow#383]
Hello,

I started about two weeks ago with _Airflow_ and don't know if the following is the best way to do, if there are better ways, tell me please.

I made a Plugin with a hook to create new connections in the database because environment variables didn't work. This plugin worked well with _SQLite_ until I changed to _Postgres_. This occurs when installing database with next command:

> airflow initdb

Following the output I found that the program first load plugins (with my hook) and then create tables in database. To solve it I need to run the same command again (first time for creating tables and second time populate them).

I tried several times against _SQLite_ and _MySQL_ and it works fine (with only one execution of initdb command).

Too much thanks

Here is the output if you are too much curious:

```
ERROR:root:(psycopg2.ProgrammingError) relation "connection" does not exist
LINE 2: FROM connection 
             ^
 [SQL: 'SELECT connection.password AS connection_password, connection.id AS connection_id, connection.conn_id AS connection_conn_id, connection.conn_type AS connection_conn_type, connection.host AS connection_host, connection.schema AS connection_schema, connection.login AS connection_login, connection.port AS connection_port, connection.is_encrypted AS connection_is_encrypted, connection.extra AS connection_extra \nFROM connection \nWHERE connection.conn_id = %(conn_id_1)s \n LIMIT %(param_1)s'] [parameters: {'conn_id_1': 'schedule_pre', 'param_1': 1}]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/airflow/plugins_manager.py", line 48, in <module>
    m = imp.load_source(mod_name, filepath)
  File "~/airflow/plugins/connection_plugin.py", line 13, in <module>
    class ConnectionHook(BaseHook):
  File "~/airflow/plugins/connection_plugin.py", line 16, in ConnectionHook
    conn = session.query(C).filter(C.conn_id == 'schedule_pre').first()
  ...
ProgrammingError: (psycopg2.ProgrammingError) relation "connection" does not exist
LINE 2: FROM connection 
             ^
 [SQL: 'SELECT connection.password AS connection_password, connection.id AS connection_id, connection.conn_id AS connection_conn_id, connection.conn_type AS connection_conn_type, connection.host AS connection_host, connection.schema AS connection_schema, connection.login AS connection_login, connection.port AS connection_port, connection.is_encrypted AS connection_is_encrypted, connection.extra AS connection_extra \nFROM connection \nWHERE connection.conn_id = %(conn_id_1)s \n LIMIT %(param_1)s'] [parameters: {'conn_id_1': 'schedule_pre', 'param_1': 1}]
ERROR:root:Failed to import plugin /home/sergio/airflow/plugins/connection_plugin.py
DB: postgresql+psycopg2://cluster:cluster@localhost:5432/airflow
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> e3a246e0dc1, current schema
INFO  [alembic.runtime.migration] Running upgrade e3a246e0dc1 -> 1507a7289a2f, create is_encrypted
INFO  [alembic.runtime.migration] Running upgrade 1507a7289a2f -> 13eb55f81627, maintain history for compatibility with earlier migrations
INFO  [alembic.runtime.migration] Running upgrade 13eb55f81627 -> 338e90f54d61, More logging into task_isntance
   ...
sqlalchemy.exc.InternalError: (psycopg2.InternalError) current transaction is aborted, commands ignored until end of transaction block
```

**Comment by mistercrunch** [comment]
We now support using environment variables to define connections.

Do you think the solution is to somehow disregard plugins when running `initdb`?

**Comment by mistercrunch** [comment]
Also, what if your plugin would use a try statement to figure out that you are in a pre-init state and not do anything?

**Comment by sergiohgz** [comment]
I tried to set environment variables as shown at documentation with Postgres Master endoint and it didn't work. I  tested that with last version downloaded from git and the last version downloaded from pip. Could give examples of how define with environment variables HTTPs connections?

Thank you so much
