### ISSUE TITLE
Getting error(No module named 'airflow.auth.managers.fab.fab_auth_manager') when starting webserver

### ISSUE THREAD

**Issue by msoni1369** [apache/airflow#38322]
### Apache Airflow version

2.8.3

### What happened?

I have installed airflow for the first time. I have initialised the db and ran "airflow webserver" command to start the webserver. Also, this issue is coming even when running "airflow standalone" cmd.

Below are the commands I ran in the order.

airflow db init  
airflow users create --username "admin" --firstname "mayank" --lastname "Soni" --role "Admin" --email  admin@example.org 
airflow webserver 

Below is the error logs.

```
mayanksoni@Y9MXPQXVXQ airflow % airflow webserver
[2024-03-20T16:28:54.977+0530] {configuration.py:2066} INFO - Creating new FAB webserver config file in: /Users/mayanksoni/airflow/webserver_config.py
  ____________       _____________
 ____    |__( )_________  __/__  /________      __
____  /| |_  /__  ___/_  /_ __  /_  __ \_ | /| / /
___  ___ |  / _  /   _  __/ _  / / /_/ /_ |/ |/ /
 _/_/  |_/_/  /_/    /_/    /_/  \____/____/|__/
Running the Gunicorn Server with:
Workers: 4 sync
Host: 0.0.0.0:8080
Timeout: 120
Logfiles: - -
Access Logformat: 
=================================================================
Please make sure to build the frontend in static/ directory and restart the server
[2024-03-20T16:28:57.304+0530] {configuration.py:1213} WARNING - No module named 'airflow.auth.managers.fab.fab_auth_manager'
Traceback (most recent call last):
  File "/Users/mayanksoni/oss-airflow/airflow/airflow/configuration.py", line 1211, in getimport
    return import_string(full_qualified_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mayanksoni/oss-airflow/airflow/airflow/utils/module_loading.py", line 39, in import_string
    module = import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.auth.managers.fab.fab_auth_manager'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/homebrew/lib/python3.11/site-packages/gunicorn/__main__.py", line 7, in <module>
    run()
  File "/opt/homebrew/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/opt/homebrew/lib/python3.11/site-packages/gunicorn/app/base.py", line 236, in run
    super().run()
  File "/opt/homebrew/lib/python3.11/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
    ^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/gunicorn/arbiter.py", line 58, in __init__
    self.setup(app)
  File "/opt/homebrew/lib/python3.11/site-packages/gunicorn/arbiter.py", line 118, in setup
    self.app.wsgi()
  File "/opt/homebrew/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/gunicorn/util.py", line 424, in import_app
    app = app(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^
  File "/Users/mayanksoni/oss-airflow/airflow/airflow/www/app.py", line 183, in cached_app
    app = create_app(config=config, testing=testing)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mayanksoni/oss-airflow/airflow/airflow/www/app.py", line 155, in create_app
    init_appbuilder(flask_app)
  File "/Users/mayanksoni/oss-airflow/airflow/airflow/www/extensions/init_appbuilder.py", line 663, in init_appbuilder
    return AirflowAppBuilder(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/mayanksoni/oss-airflow/airflow/airflow/www/extensions/init_appbuilder.py", line 184, in __init__
    self.init_app(app, session)
  File "/Users/mayanksoni/oss-airflow/airflow/airflow/www/extensions/init_appbuilder.py", line 227, in init_app
    auth_manager = init_auth_manager(self)
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mayanksoni/oss-airflow/airflow/airflow/www/extensions/init_auth_manager.py", line 55, in init_auth_manager
    auth_manager_cls = get_auth_manager_cls()
                       ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mayanksoni/oss-airflow/airflow/airflow/www/extensions/init_auth_manager.py", line 37, in get_auth_manager_cls
    auth_manager_cls = conf.getimport(section="core", key="auth_manager")
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mayanksoni/oss-airflow/airflow/airflow/configuration.py", line 1214, in getimport
    raise AirflowConfigException(
airflow.exceptions.AirflowConfigException: The object could not be loaded. Please check "auth_manager" key in "core" section. Current value: "airflow.auth.managers.fab.fab_auth_manager.FabAuthManager".
[2024-03-20T16:30:55.280+0530] {webserver_command.py:222} ERROR - No response from gunicorn master within 120 seconds
[2024-03-20T16:30:55.282+0530] {webserver_command.py:223} ERROR - Shutting down webserver
```

### What you think should happen instead?

fab_auth_manager file is missing in airflow.auth.managers.fab

### How to reproduce

Install the airflow 
initialise the db 
run the web server

### Operating System

Mac

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by msoni1369** [comment]
If the used below to resolve the issue in airflow.cfg 
auth_manager = airflow.auth.managers.base_auth_manager.BaseAuthManager

**Comment by msoni1369** [comment]
@hussein-awala @potiuk Can you take a look at this issue?
