### ISSUE TITLE
triggerer : {serve_logs.py:103} WARNING - The signature of the request was wrong

### ISSUE THREAD

**Issue by raphaelauv** [apache/airflow#38352]
### Apache Airflow version

2.8.3

### What happened?

```
{serve_logs.py:103} WARNING - The signature of the request was wrong
Traceback (most recent call last):
File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/serve_logs.py", line 85, in validate_pre_signed_url
	payload = signer.verify_token(auth)
File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/jwt_signer.py", line 72, in verify_token
	payload = jwt.decode(
File "/home/airflow/.local/lib/python3.8/site-packages/jwt/api_jwt.py", line 210, in decode
	decoded = self.decode_complete(
File "/home/airflow/.local/lib/python3.8/site-packages/jwt/api_jwt.py", line 151, in decode_complete
	decoded = api_jws.decode_complete(
File "/home/airflow/.local/lib/python3.8/site-packages/jwt/api_jws.py", line 209, in decode_complete
	self._verify_signature(signing_input, header, signature, key, algorithms)
File "/home/airflow/.local/lib/python3.8/site-packages/jwt/api_jws.py", line 310, in _verify_signature
	raise InvalidSignatureError("Signature verification failed")
jwt.exceptions.InvalidSignatureError: Signature verification failed
```

### How to reproduce

```shell
curl -LfO 'https://airflow.apache.org/docs/apache-airflow/2.8.3/docker-compose.yaml'

mkdir -p ./dags ./logs ./plugins ./config

```
create file toto.py

```python
from airflow.operators.python import PythonOperator
from airflow.operators.trigger_dagrun import TriggerDagRunOperator
from pendulum import today
from airflow import DAG

dag_1 = DAG(
    dag_id="dag_1",
    schedule_interval=None,
    start_date=today("UTC").add(days=-1)
)

with dag_1:
    def toto():
        import time
        time.sleep(12)
        raise Exception()


    PythonOperator(
        task_id="task_2",
        python_callable=toto)

dag_2 = DAG(
    dag_id="dag_2",
    schedule_interval=None,
    start_date=today("UTC").add(days=-1)
)

with dag_2:
    TriggerDagRunOperator(
        task_id="task_1",
        trigger_dag_id="dag_1",
        reset_dag_run=True,
        wait_for_completion=True,
        poke_interval=5,
        deferrable=True,
        trigger_run_id="NAME_C"
    )

```

```shell
docker compose up -d 
```
then activate dag_1 and dag_2 then trigger a run of dag_2 , then check logs of the task

### Operating System

ubuntu 22.0.4

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
> jwt.exceptions.InvalidSignatureError: Signature verification failed

Did you set [`[webserver] secret_key`](https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#secret-key) ?

**Comment by raphaelauv** [comment]
yes , thanks
