### ISSUE TITLE
dag run successfully with eventlet.monkey_patch() warning!?

### ISSUE THREAD

**Issue by claude89757** [apache/airflow#38581]
### Apache Airflow version

2.8.4

### What happened?

my worker run dag with eventlet, it log some warnings, but dag run success!

### How to reproduce

FROM bitnami/airflow-worker:2.8.4

### Operating System

linux

### Deployment

Other Docker-based deployment

### Anything else?

airflow-2-worker-7686dcc964-qtpq2
*** Found local files:
***   * /opt/bitnami/airflow/logs/dag_id=设备在线状态巡检/run_id=scheduled__2024-03-28T10:01:00+00:00/task_id=扫描异常离线设备/attempt=1.log
[2024-03-28, 18:01:34 CST] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 设备在线状态巡检.扫描异常离线设备 scheduled__2024-03-28T10:01:00+00:00 [queued]>
[2024-03-28, 18:01:34 CST] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 设备在线状态巡检.扫描异常离线设备 scheduled__2024-03-28T10:01:00+00:00 [queued]>
[2024-03-28, 18:01:34 CST] {taskinstance.py:2193} INFO - Starting attempt 1 of 4
[2024-03-28, 18:01:34 CST] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): 扫描异常离线设备> on 2024-03-28 10:01:00+00:00
[2024-03-28, 18:01:34 CST] {standard_task_runner.py:60} INFO - Started process 21281 to run task
[2024-03-28, 18:01:34 CST] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', '设备在线状态巡检', '扫描异常离线设备', 'scheduled__2024-03-28T10:01:00+00:00', '--job-id', '6498269', '--raw', '--subdir', 'DAGS_FOLDER/cron_dags/alarm_watcher/offline_device_watcher.py', '--cfg-path', '/tmp/tmprwskezaw']
[2024-03-28, 18:01:34 CST] {standard_task_runner.py:88} INFO - Job 6498269: Subtask 扫描异常离线设备
[2024-03-28, 18:01:34 CST] {task_command.py:423} INFO - Running <TaskInstance: 设备在线状态巡检.扫描异常离线设备 scheduled__2024-03-28T10:01:00+00:00 [running]> on host airflow-2-worker-7686dcc964-qtpq2
[2024-03-28, 18:01:34 CST] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='claudexie' AIRFLOW_CTX_DAG_ID='设备在线状态巡检' AIRFLOW_CTX_TASK_ID='扫描异常离线设备' AIRFLOW_CTX_EXECUTION_DATE='2024-03-28T10:01:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-28T10:01:00+00:00'
[2024-03-28, 18:01:36 CST] {logging_mixin.py:188} INFO - region: xxx url: http://xxxxx
[2024-03-28, 18:01:36 CST] {warnings.py:110} WARNING - /opt/bitnami/airflow/venv/lib/python3.11/site-packages/airflow/utils/context.py:315: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))
[2024-03-28, 18:01:36 CST] {warnings.py:110} WARNING - /opt/bitnami/airflow/venv/lib/python3.11/site-packages/airflow/utils/context.py:315: AirflowContextDeprecationWarning: Accessing 'next_ds' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds }}' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))
[2024-03-28, 18:01:36 CST] {warnings.py:110} WARNING - /opt/bitnami/airflow/venv/lib/python3.11/site-packages/airflow/utils/context.py:315: AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))
[2024-03-28, 18:01:36 CST] {warnings.py:110} WARNING - /opt/bitnami/airflow/venv/lib/python3.11/site-packages/airflow/utils/context.py:315: AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))
[2024-03-28, 18:01:36 CST] {warnings.py:110} WARNING - /opt/bitnami/airflow/venv/lib/python3.11/site-packages/airflow/utils/context.py:315: AirflowContextDeprecationWarning: Accessing 'prev_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(k, replacements))
[2024-03-28, 18:01:36 CST] {warnings.py:110} WARNING - /opt/bitnami/airflow/venv/lib/python3.11/site-packages/airflow/utils/context.py:315: AirflowContextDeprecationWarning: Accessing 'prev_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(k, replacements))
[2024-03-28, 18:01:36 CST] {warnings.py:110} WARNING - /opt/bitnami/airflow/venv/lib/python3.11/site-packages/airflow/utils/context.py:315: AirflowContextDeprecationWarning: Accessing 'prev_execution_date' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(k, replacements))
[2024-03-28, 18:01:36 CST] {warnings.py:110} WARNING - /opt/bitnami/airflow/venv/lib/python3.11/site-packages/airflow/utils/context.py:315: AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))
[2024-03-28, 18:01:36 CST] {warnings.py:110} WARNING - /opt/bitnami/airflow/venv/lib/python3.11/site-packages/airflow/utils/context.py:315: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(k, replacements))
[2024-03-28, 18:01:36 CST] {warnings.py:110} WARNING - /opt/bitnami/airflow/venv/lib/python3.11/site-packages/airflow/utils/context.py:315: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(k, replacements))
[2024-03-28, 18:01:36 CST] {warnings.py:110} WARNING - /opt/bitnami/airflow/venv/lib/python3.11/site-packages/airflow/utils/context.py:315: AirflowContextDeprecationWarning: Accessing 'yesterday_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(k, replacements))
[2024-03-28, 18:01:36 CST] {warnings.py:110} WARNING - /opt/bitnami/airflow/venv/lib/python3.11/site-packages/airflow/utils/context.py:315: AirflowContextDeprecationWarning: Accessing 'yesterday_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(k, replacements))
[2024-03-28, 18:01:36 CST] {logging_mixin.py:188} WARNING - An exception was thrown while monkey_patching for eventlet. to fix this error make sure you run eventlet.monkey_patch() before importing any other modules.
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.11/site-packages/eventlet/patcher.py", line 473, in _upgrade_instances
    new = upgrade_or_traverse(v)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.11/site-packages/eventlet/patcher.py", line 450, in upgrade_or_traverse
    _upgrade_instances(obj, klass, upgrade, visited, old_to_new)
  File "/opt/bitnami/airflow/venv/lib/python3.11/site-packages/eventlet/patcher.py", line 464, in _upgrade_instances
    container_vars = vars(container)
                     ^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.11/site-packages/werkzeug/local.py", line 316, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.11/site-packages/werkzeug/local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.
This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
[2024-03-28, 18:01:36 CST] {logging_mixin.py:188} WARNING - An exception was thrown while monkey_patching for eventlet. to fix this error make sure you run eventlet.monkey_patch() before importing any other modules.
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.11/site-packages/eventlet/patcher.py", line 473, in _upgrade_instances
    new = upgrade_or_traverse(v)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.11/site-packages/eventlet/patcher.py", line 450, in upgrade_or_traverse
    _upgrade_instances(obj, klass, upgrade, visited, old_to_new)
  File "/opt/bitnami/airflow/venv/lib/python3.11/site-packages/eventlet/patcher.py", line 464, in _upgrade_instances
    container_vars = vars(container)
                     ^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.11/site-packages/werkzeug/local.py", line 316, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.11/site-packages/werkzeug/local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of request context.
This typically means that you attempted to use functionality that needed
an active HTTP request. Consult the documentation on testing for
information about how to avoid this problem.
[2024-03-28, 18:01:36 CST] {logging_mixin.py:188} WARNING - An exception was thrown while monkey_patching for eventlet. to fix this error make sure you run eventlet.monkey_patch() before importing any other modules.
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.11/site-packages/eventlet/patcher.py", line 473, in _upgrade_instances
    new = upgrade_or_traverse(v)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.11/site-packages/eventlet/patcher.py", line 450, in upgrade_or_traverse
    _upgrade_instances(obj, klass, upgrade, visited, old_to_new)
  File "/opt/bitnami/airflow/venv/lib/python3.11/site-packages/eventlet/patcher.py", line 464, in _upgrade_instances
    container_vars = vars(container)
                     ^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.11/site-packages/werkzeug/local.py", line 316, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.11/site-packages/werkzeug/local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of request context.
This typically means that you attempted to use functionality that needed
an active HTTP request. Consult the documentation on testing for
information about how to avoid this problem.
[2024-03-28, 18:01:36 CST] {logging_mixin.py:188} WARNING - An exception was thrown while monkey_patching for eventlet. to fix this error make sure you run eventlet.monkey_patch() before importing any other modules.
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.11/site-packages/eventlet/patcher.py", line 473, in _upgrade_instances
    new = upgrade_or_traverse(v)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.11/site-packages/eventlet/patcher.py", line 450, in upgrade_or_traverse
    _upgrade_instances(obj, klass, upgrade, visited, old_to_new)
  File "/opt/bitnami/airflow/venv/lib/python3.11/site-packages/eventlet/patcher.py", line 464, in _upgrade_instances
    container_vars = vars(container)
                     ^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.11/site-packages/werkzeug/local.py", line 316, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.11/site-packages/werkzeug/local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.
This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
[2024-03-28, 18:01:36 CST] {logging_mixin.py:188} WARNING - An exception was thrown while monkey_patching for eventlet. to fix this error make sure you run eventlet.monkey_patch() before importing any other modules.
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.11/site-packages/eventlet/patcher.py", line 473, in _upgrade_instances
    new = upgrade_or_traverse(v)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.11/site-packages/eventlet/patcher.py", line 450, in upgrade_or_traverse
    _upgrade_instances(obj, klass, upgrade, visited, old_to_new)
  File "/opt/bitnami/airflow/venv/lib/python3.11/site-packages/eventlet/patcher.py", line 464, in _upgrade_instances
    container_vars = vars(container)
                     ^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.11/site-packages/werkzeug/local.py", line 316, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.11/site-packages/werkzeug/local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.
This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
[2024-03-28, 18:01:36 CST] {logging_mixin.py:188} WARNING - An exception was thrown while monkey_patching for eventlet. to fix this error make sure you run eventlet.monkey_patch() before importing any other modules.
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.11/site-packages/eventlet/patcher.py", line 473, in _upgrade_instances
    new = upgrade_or_traverse(v)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.11/site-packages/eventlet/patcher.py", line 450, in upgrade_or_traverse
    _upgrade_instances(obj, klass, upgrade, visited, old_to_new)
  File "/opt/bitnami/airflow/venv/lib/python3.11/site-packages/eventlet/patcher.py", line 464, in _upgrade_instances
    container_vars = vars(container)
                     ^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.11/site-packages/werkzeug/local.py", line 316, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.11/site-packages/werkzeug/local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of request context.
This typically means that you attempted to use functionality that needed
an active HTTP request. Consult the documentation on testing for
information about how to avoid this problem.
[2024-03-28, 18:01:36 CST] {logging_mixin.py:188} WARNING - An exception was thrown while monkey_patching for eventlet. to fix this error make sure you run eventlet.monkey_patch() before importing any other modules.
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.11/site-packages/eventlet/patcher.py", line 473, in _upgrade_instances
    new = upgrade_or_traverse(v)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.11/site-packages/eventlet/patcher.py", line 450, in upgrade_or_traverse
    _upgrade_instances(obj, klass, upgrade, visited, old_to_new)
  File "/opt/bitnami/airflow/venv/lib/python3.11/site-packages/eventlet/patcher.py", line 464, in _upgrade_instances
    container_vars = vars(container)
                     ^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.11/site-packages/werkzeug/local.py", line 316, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.11/site-packages/werkzeug/local.py", line 520, in _get_current_object
    return get_name(local())  # type: ignore
                    ^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.11/site-packages/flask_jwt_extended/utils.py", line 15, in <lambda>
    current_user: Any = LocalProxy(lambda: get_current_user())
                                           ^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.11/site-packages/flask_jwt_extended/utils.py", line 94, in get_current_user
    get_jwt()  # Raise an error if not in a decorated context
    ^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.11/site-packages/flask_jwt_extended/utils.py", line 27, in get_jwt
    decoded_jwt = g.get("_jwt_extended_jwt", None)
                  ^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.11/site-packages/werkzeug/local.py", line 316, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.11/site-packages/werkzeug/local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.
This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
[2024-03-28, 18:01:37 CST] {logging_mixin.py:188} WARNING - 47 RLock(s) were not greened, to fix this error make sure you run eventlet.monkey_patch() before importing any other modules.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment]
https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#worker-class

**Comment by claude89757** [comment]
> https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#worker-class

it is not webserver‘s worker with warnings， it is the worker to run dags！！！
