### ISSUE TITLE
cannot start 'airflow standalone'; pendulum.tz.timezone(tz) -> TypeError

### ISSUE THREAD

**Issue by JamesKunstle** [apache/airflow#38714]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### If "Other Airflow 2 version" selected, which one?

2.7.2

### What happened?

In a fresh virtual environment, ran 'airflow standalone'. Airflow emitted following error:

```
airflow standalone
Traceback (most recent call last):
  File "/Users/jkunstle/airflow/venv/lib/python3.12/site-packages/airflow/settings.py", line 55, in <module>
    TIMEZONE = pendulum.tz.timezone(tz)
               ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'module' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jkunstle/airflow/venv/bin/airflow", line 5, in <module>
    from airflow.__main__ import main
  File "/Users/jkunstle/airflow/venv/lib/python3.12/site-packages/airflow/__init__.py", line 52, in <module>
    from airflow import configuration, settings
  File "/Users/jkunstle/airflow/venv/lib/python3.12/site-packages/airflow/configuration.py", line 2340, in <module>
    secrets_backend_list = initialize_secrets_backends()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jkunstle/airflow/venv/lib/python3.12/site-packages/airflow/configuration.py", line 2254, in initialize_secrets_backends
    secrets_backend_cls = import_string(class_name)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jkunstle/airflow/venv/lib/python3.12/site-packages/airflow/utils/module_loading.py", line 37, in import_string
    module = import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jkunstle/airflow/venv/lib/python3.12/site-packages/airflow/secrets/metastore.py", line 29, in <module>
    from airflow.utils.session import NEW_SESSION, provide_session
  File "/Users/jkunstle/airflow/venv/lib/python3.12/site-packages/airflow/utils/session.py", line 24, in <module>
    from airflow import settings
  File "/Users/jkunstle/airflow/venv/lib/python3.12/site-packages/airflow/settings.py", line 57, in <module>
    TIMEZONE = pendulum.tz.timezone("UTC")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'module' object is not callable
```

Current 'pip3 freeze': 

```
a2wsgi==1.10.4
aiohttp==3.9.3
aiosignal==1.3.1
alembic==1.13.1
annotated-types==0.6.0
anyio==4.3.0
apache-airflow==2.7.2
apache-airflow-providers-common-sql==1.11.1
apache-airflow-providers-ftp==3.7.0
apache-airflow-providers-http==4.10.0
apache-airflow-providers-imap==3.5.0
apache-airflow-providers-sqlite==3.7.1
apispec==6.6.0
argcomplete==3.2.3
asgiref==3.8.1
attrs==23.2.0
Babel==2.14.0
blinker==1.7.0
cachelib==0.9.0
cattrs==23.2.3
certifi==2024.2.2
cffi==1.16.0
charset-normalizer==3.3.2
click==8.1.7
colorama==0.4.6
colorlog==4.8.0
ConfigUpdater==3.2
connexion==3.0.6
cron-descriptor==1.4.3
croniter==2.0.3
cryptography==42.0.5
Deprecated==1.2.14
dill==0.3.8
dnspython==2.6.1
docutils==0.20.1
email-validator==1.3.1
Flask==2.2.5
Flask-AppBuilder==4.3.6
Flask-Babel==2.0.0
Flask-Caching==2.1.0
Flask-JWT-Extended==4.6.0
Flask-Limiter==3.5.1
Flask-Login==0.6.3
Flask-Session==0.8.0
Flask-SQLAlchemy==2.5.1
Flask-WTF==1.2.1
frozenlist==1.4.1
google-re2==1.1
googleapis-common-protos==1.63.0
graphviz==0.20.3
grpcio==1.62.1
gunicorn==21.2.0
h11==0.14.0
httpcore==1.0.5
httpx==0.27.0
idna==3.6
importlib-metadata==7.0.0
importlib_resources==6.4.0
inflection==0.5.1
itsdangerous==2.1.2
Jinja2==3.1.3
jsonschema==4.21.1
jsonschema-specifications==2023.12.1
lazy-object-proxy==1.10.0
limits==3.10.1
linkify-it-py==2.0.3
lockfile==0.12.2
Mako==1.3.2
Markdown==3.6
markdown-it-py==3.0.0
MarkupSafe==2.1.5
marshmallow==3.21.1
marshmallow-oneofschema==3.1.1
marshmallow-sqlalchemy==0.26.1
mdit-py-plugins==0.4.0
mdurl==0.1.2
more-itertools==10.2.0
msgspec==0.18.6
multidict==6.0.5
opentelemetry-api==1.24.0
opentelemetry-exporter-otlp==1.24.0
opentelemetry-exporter-otlp-proto-common==1.24.0
opentelemetry-exporter-otlp-proto-grpc==1.24.0
opentelemetry-exporter-otlp-proto-http==1.24.0
opentelemetry-proto==1.24.0
opentelemetry-sdk==1.24.0
opentelemetry-semantic-conventions==0.45b0
ordered-set==4.1.0
packaging==24.0
pathspec==0.12.1
pendulum==3.0.0
pluggy==1.4.0
prison==0.2.1
protobuf==4.25.3
psutil==5.9.8
pycparser==2.22
pydantic==2.6.4
pydantic_core==2.16.3
Pygments==2.17.2
PyJWT==2.8.0
python-daemon==3.0.1
python-dateutil==2.9.0.post0
python-multipart==0.0.9
python-nvd3==0.15.0
python-slugify==8.0.4
pytz==2024.1
PyYAML==6.0.1
referencing==0.34.0
requests==2.31.0
requests-toolbelt==1.0.0
rfc3339-validator==0.1.4
rich==13.7.1
rich-argparse==1.4.0
rpds-py==0.18.0
setproctitle==1.3.3
setuptools==69.2.0
six==1.16.0
sniffio==1.3.1
SQLAlchemy==1.4.52
SQLAlchemy-JSONField==1.0.2
SQLAlchemy-Utils==0.41.2
sqlparse==0.4.4
starlette==0.37.2
tabulate==0.9.0
tenacity==8.2.3
termcolor==2.4.0
text-unidecode==1.3
time-machine==2.14.1
typing_extensions==4.10.0
tzdata==2024.1
uc-micro-py==1.0.3
unicodecsv==0.14.1
urllib3==2.2.1
Werkzeug==3.0.2
wrapt==1.16.0
WTForms==3.1.2
yarl==1.9.4
zipp==3.18.1
```

### What you think should happen instead?

Should start local process.

### How to reproduce

Very minimal requirements to reproduce, should be clear from "What happened?"

### Operating System

14.4.1 (23E224) MacOS

### Versions of Apache Airflow Providers

```
apache-airflow==2.7.2
apache-airflow-providers-common-sql==1.11.1
apache-airflow-providers-ftp==3.7.0
apache-airflow-providers-http==4.10.0
apache-airflow-providers-imap==3.5.0
apache-airflow-providers-sqlite==3.7.1
```

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jscheffl** [comment]
Can you make a re-test with 2.8.4?

Can you ost the commands which you used to install in your fresh venv as well?

**Comment by Taragolis** [comment]
> pendulum==3.0.0

Airflow before 2.8.1 doesn't support pendulum 3

Please consider to use provided constraints for appropriate version of Airflow(see [Installation from PyPI](https://airflow.apache.org/docs/apache-airflow/stable/installation/installing-from-pypi.html#constraints-files)) and/or add explicit `pendulum<3` into your `pip install` command

**Comment by dhshah13** [comment]
and degrade python version to 3.11- it is more stable.
