### ISSUE TITLE
Cannot retrieve config from alternative secrets backend

### ISSUE THREAD

**Issue by imishchuk-tsgs** [apache/airflow#39071]
### Apache Airflow Provider(s)

amazon

### Versions of Apache Airflow Providers

apache-airflow-providers-amazon==8.18.0
apache-airflow-providers-celery==3.6.0
apache-airflow-providers-cncf-kubernetes==8.0.0
apache-airflow-providers-common-io==1.3.0
apache-airflow-providers-common-sql==1.11.0
apache-airflow-providers-docker==3.9.1
apache-airflow-providers-elasticsearch==5.3.3
apache-airflow-providers-ftp==3.7.0
apache-airflow-providers-google==10.15.0
apache-airflow-providers-grpc==3.4.1
apache-airflow-providers-hashicorp==3.6.3
apache-airflow-providers-http==4.9.1
apache-airflow-providers-imap==3.5.0
apache-airflow-providers-microsoft-azure==9.0.0
apache-airflow-providers-mysql==5.5.3
apache-airflow-providers-odbc==4.4.1
apache-airflow-providers-openlineage==1.5.0
apache-airflow-providers-postgres==5.10.1
apache-airflow-providers-redis==3.6.0
apache-airflow-providers-sendgrid==3.4.0
apache-airflow-providers-sftp==4.9.0
apache-airflow-providers-slack==8.6.1
apache-airflow-providers-snowflake==5.3.1
apache-airflow-providers-sqlite==3.7.1
apache-airflow-providers-ssh==3.10.1

### Apache Airflow version

2.8.2

### Operating System

Debian GNU/Linux 12 (bookworm)

### Deployment

Other Docker-based deployment

### Deployment details

Deployment is done on AWS ECS on Fargate

### What happened

Any airflow command, e.g. `airflow info` results in following error

```
....................
ERROR! Maximum number of retries (20) reached.

Last check result:
$ airflow db check
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/configuration.py", line 131, in _get_config_value_from_secret_backend
    return secrets_client.get_config(config_key)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/amazon/aws/secrets/systems_manager.py", line 167, in get_config
    return self._get_secret(self.config_prefix, key, self.config_lookup_pattern)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/amazon/aws/secrets/systems_manager.py", line 185, in _get_secret
    response = self.client.get_parameter(Name=ssm_path, WithDecryption=True)
  File "/home/airflow/.local/lib/python3.10/site-packages/botocore/client.py", line 553, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/botocore/client.py", line 1009, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the GetParameter operation: Parameter name: can't be prefixed with "ssm" (case-insensitive). If formed as a path, it can consist of sub-paths divided by slash symbol; each sub-path can be formed as a mix of letters, numbers and the following 3 symbols .-_

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/bin/airflow", line 5, in <module>
    from airflow.__main__ import main
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/__init__.py", line 52, in <module>
    from airflow import configuration, settings
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/configuration.py", line 2327, in <module>
    conf.validate()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/configuration.py", line 718, in validate
    self._validate_sqlite3_version()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/configuration.py", line 812, in _validate_sqlite3_version
    if "sqlite" not in self.get("database", "sql_alchemy_conn"):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/configuration.py", line 989, in get
    option = self._get_environment_variables(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/configuration.py", line 1123, in _get_environment_variables
    option = self._get_env_var_option(section, key)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/configuration.py", line 865, in _get_env_var_option
    return _get_config_value_from_secret_backend(os.environ[env_var_secret_path])
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/configuration.py", line 133, in _get_config_value_from_secret_backend
    raise AirflowConfigException(
airflow.exceptions.AirflowConfigException: Cannot retrieve config from alternative secrets backend. Make sure it is configured properly and that the Backend is accessible.
An error occurred (ValidationException) when calling the GetParameter operation: Parameter name: can't be prefixed with "ssm" (case-insensitive). If formed as a path, it can consist of sub-paths divided by slash symbol; each sub-path can be formed as a mix of letters, numbers and the following 3 symbols .-_
```

### What you think should happen instead

Command works as expected

### How to reproduce

Use apache/airflow:2.8.2-python3.10 image and have following content in `airflow.cfg`

```
backend = airflow.providers.amazon.aws.secrets.systems_manager.SystemsManagerParameterStoreBackend
backend_kwargs = {"connections_prefix": "/airflow/prod/connections", "variables_prefix": "/airflow/prod/variables"}
```

Try to launch ECS Task

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by imishchuk-tsgs** [comment]
Hey,team.

I can confirm that SSM parameters by path `/airflow/prod/variables/*` and `/airflow/prod/connections/*` exist and I can fetch them from container via `aws ssm get-parameters-by-path --path /airflow/prod/variables --recursive --no-cli-pager`

Thank you.

**Comment by imishchuk-tsgs** [comment]
After some digging around in Cloudtrail, I noticed that airflow was trying to read SSM `/ariflow/config/postgresql+psycopg2://...` and that operation was failing. And the cause was a mistake in configuration, where I used `AIRFLOW__DATABASE__SQL_ALCHEMY_CONN_SECRET` instead of `AIRFLOW__DATABASE__SQL_ALCHEMY_CONN`. Now that env var is fixed and commands work as expected.
Closing the issue.
