### ISSUE TITLE
Unable to access Airflow home after authentication.

### ISSUE THREAD

**Issue by DEUserAI** [apache/airflow#39170]
### Apache Airflow version

2.9.0

### What happened?

Using Astro CLI to launch Airflow. I can enter User ID and PW at the authentication page but after credential is submitted it throws an error.

"
Ooops!
Something bad has happened. For security reasons detailed information about the error is not logged.

"

### What you think should happen instead?

Take user to the home page.

### How to reproduce

All I did is starting Airflow using Astro CLI then submitting credentials. It was working fine until last Friday morning. Below is the actual error log received.

***

2024-04-22 10:17:38 webserver-1  | [2024-04-22T15:17:38.495+0000] {app.py:1744} ERROR - Exception on /home [GET]
2024-04-22 10:17:38 webserver-1  | Traceback (most recent call last):
2024-04-22 10:17:38 webserver-1  |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2529, in wsgi_app
2024-04-22 10:17:38 webserver-1  |     response = self.full_dispatch_request()
2024-04-22 10:17:38 webserver-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-22 10:17:38 webserver-1  |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1825, in full_dispatch_request
2024-04-22 10:17:38 webserver-1  |     rv = self.handle_user_exception(e)
2024-04-22 10:17:38 webserver-1  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-22 10:17:38 webserver-1  |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1823, in full_dispatch_request
2024-04-22 10:17:38 webserver-1  |     rv = self.dispatch_request()
2024-04-22 10:17:38 webserver-1  |          ^^^^^^^^^^^^^^^^^^^^^^^
2024-04-22 10:17:38 webserver-1  |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1799, in dispatch_request
2024-04-22 10:17:38 webserver-1  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2024-04-22 10:17:38 webserver-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-22 10:17:38 webserver-1  |   File "/usr/local/lib/python3.11/site-packages/airflow/www/auth.py", line 139, in decorated
2024-04-22 10:17:38 webserver-1  |     return _has_access(
2024-04-22 10:17:38 webserver-1  |            ^^^^^^^^^^^^
2024-04-22 10:17:38 webserver-1  |   File "/usr/local/lib/python3.11/site-packages/airflow/www/auth.py", line 163, in _has_access
2024-04-22 10:17:38 webserver-1  |     return func(*args, **kwargs)
2024-04-22 10:17:38 webserver-1  |            ^^^^^^^^^^^^^^^^^^^^^
2024-04-22 10:17:38 webserver-1  |   File "/usr/local/lib/python3.11/site-packages/airflow/www/views.py", line 1038, in index
2024-04-22 10:17:38 webserver-1  |     return self.render_template(
2024-04-22 10:17:38 webserver-1  |            ^^^^^^^^^^^^^^^^^^^^^
2024-04-22 10:17:38 webserver-1  |   File "/usr/local/lib/python3.11/site-packages/airflow/www/views.py", line 714, in render_template
2024-04-22 10:17:38 webserver-1  |     return super().render_template(
2024-04-22 10:17:38 webserver-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-22 10:17:38 webserver-1  |   File "/usr/local/lib/python3.11/site-packages/flask_appbuilder/baseviews.py", line 342, in render_template
2024-04-22 10:17:38 webserver-1  |     return render_template(
2024-04-22 10:17:38 webserver-1  |            ^^^^^^^^^^^^^^^^
2024-04-22 10:17:38 webserver-1  |   File "/usr/local/lib/python3.11/site-packages/flask/templating.py", line 147, in render_template
2024-04-22 10:17:38 webserver-1  |     return _render(app, template, context)
2024-04-22 10:17:38 webserver-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-22 10:17:38 webserver-1  |   File "/usr/local/lib/python3.11/site-packages/flask/templating.py", line 130, in _render
2024-04-22 10:17:38 webserver-1  |     rv = template.render(context)
2024-04-22 10:17:38 webserver-1  |          ^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-22 10:17:38 webserver-1  |   File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
2024-04-22 10:17:38 webserver-1  |     self.environment.handle_exception()
2024-04-22 10:17:38 webserver-1  |   File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
2024-04-22 10:17:38 webserver-1  |     raise rewrite_traceback_stack(source=source)
2024-04-22 10:17:38 webserver-1  |   File "/usr/local/lib/python3.11/site-packages/airflow/www/templates/airflow/dags.html", line 44, in top-level template code
2024-04-22 10:17:38 webserver-1  |     {% elif curr_ordering_direction == 'asc' and request.args.get('sorting_key') == attribute_name %}
2024-04-22 10:17:38 webserver-1  |     ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-22 10:17:38 webserver-1  |   File "/usr/local/lib/python3.11/site-packages/astronomer/runtime/templates/runtime_base.html", line 1, in top-level template code
2024-04-22 10:17:38 webserver-1  |     {% extends original_base_template %}
2024-04-22 10:17:38 webserver-1  |     ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-22 10:17:38 webserver-1  |   File "/usr/local/lib/python3.11/site-packages/astronomer/airflow/version_check/templates/astro-baselayout.html", line 1, in top-level template code
2024-04-22 10:17:38 webserver-1  |     {% extends airflow_base_template %}
2024-04-22 10:17:38 webserver-1  |     ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-22 10:17:38 webserver-1  |   File "/usr/local/lib/python3.11/site-packages/airflow/www/templates/airflow/main.html", line 21, in top-level template code
2024-04-22 10:17:38 webserver-1  |     {% from 'airflow/_messages.html' import show_message %}
2024-04-22 10:17:38 webserver-1  |     ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-22 10:17:38 webserver-1  |   File "/usr/local/lib/python3.11/site-packages/flask_appbuilder/templates/appbuilder/baselayout.html", line 2, in top-level template code
2024-04-22 10:17:38 webserver-1  |     {% import 'appbuilder/baselib.html' as baselib %}
2024-04-22 10:17:38 webserver-1  |     ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-22 10:17:38 webserver-1  |   File "/usr/local/lib/python3.11/site-packages/flask_appbuilder/templates/appbuilder/init.html", line 42, in top-level template code
2024-04-22 10:17:38 webserver-1  |     {% block body %}
2024-04-22 10:17:38 webserver-1  |   File "/usr/local/lib/python3.11/site-packages/flask_appbuilder/templates/appbuilder/baselayout.html", line 16, in block 'body'
2024-04-22 10:17:38 webserver-1  |     {% block messages %}
2024-04-22 10:17:38 webserver-1  |   File "/usr/local/lib/python3.11/site-packages/airflow/www/templates/airflow/dags.html", line 108, in block 'messages'
2024-04-22 10:17:38 webserver-1  |     {{ super() }}
2024-04-22 10:17:38 webserver-1  |   File "/usr/local/lib/python3.11/site-packages/astronomer/airflow/version_check/templates/astro-baselayout.html", line 3, in block 'messages'
2024-04-22 10:17:38 webserver-1  |     {% include "update-available.html" %}
2024-04-22 10:17:38 webserver-1  |     ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-22 10:17:38 webserver-1  |   File "/usr/local/lib/python3.11/site-packages/astronomer/airflow/version_check/templates/update-available.html", line 4, in top-level template code
2024-04-22 10:17:38 webserver-1  |     {% if "can_dismiss" | is_item_visible("UpdateAvailable") %}
2024-04-22 10:17:38 webserver-1  |     ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-22 10:17:38 webserver-1  |   File "/usr/local/lib/python3.11/site-packages/flask_appbuilder/filters.py", line 171, in is_item_visible
2024-04-22 10:17:38 webserver-1  |     return self.security_manager.has_access(permission_name, item)
2024-04-22 10:17:38 webserver-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-22 10:17:38 webserver-1  |   File "/usr/local/lib/python3.11/site-packages/airflow/www/security_manager.py", line 142, in has_access
2024-04-22 10:17:38 webserver-1  |     return is_authorized_method(action_name, resource_pk, user)
2024-04-22 10:17:38 webserver-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-22 10:17:38 webserver-1  |   File "/usr/local/lib/python3.11/site-packages/airflow/www/security_manager.py", line 340, in <lambda>
2024-04-22 10:17:38 webserver-1  |     method=get_method_from_fab_action_map()[action],
2024-04-22 10:17:38 webserver-1  |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
2024-04-22 10:17:38 webserver-1  | KeyError: 'can_dismiss'

### Operating System

Windows 10

### Deployment

Astronomer

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by RNHTTR** [comment]
This seems to be unique to the Astro CLI. Would you mind raising an issue in the [Astro CLI repo](https://github.com/astronomer/astro-cli/issues)?

**Comment by FrikadelleHelle** [comment]
For posterity, for me it worked to restart Docker and kill the local deployment, and then restart it again.

**Comment by SRITEJA-MOLLETI** [comment]
@DEUserAI How is this issue resloved?

**Comment by RNHTTR** [comment]
If you're issue is with using the Astro CLI, upgrade Astro Runtime to 11.3.0. If this is occurring outside of the Astro CLI, upgrade Airflow to 2.9.1.
