### ISSUE TITLE
EksPodOperator error with deferrable=True

### ISSUE THREAD

**Issue by nicolasgibaud** [apache/airflow#39685]
### Apache Airflow Provider(s)

amazon

### Versions of Apache Airflow Providers

apache-airflow-providers-amazon==8.16.0

### Apache Airflow version

2.8.1

### Operating System

MWAA's OS 

### Deployment

Amazon (AWS) MWAA

### What happened

I am not able to run EksPodOperator with param deferrable=True, the DAG fails in error. 
The DAG run without error with param deferrable=False. 

My EksPodOperator applies a trivial task using the aws cli docker image (https://hub.docker.com/r/amazon/aws-cli), and I got exactly the same error on attempts with other docker images, so it seems to be a problem with the EksPodOperator itself.

This is a duplicate of this issue: https://github.com/apache/airflow/issues/38280
However since this one is closed and the problem still persists on higher versions of Airflow and apache-airflow-providers-amazon I re-open the ticket. 
 
Final error in stack trace is 

```
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/kubernetes/config/kube_config.py", line 767, in _get_kube_config_loader
    raise ConfigException(
kubernetes.config.config_exception.ConfigException: Invalid kube-config file. No configuration found.
```

Full logs in "Anything else" section. 

### What you think should happen instead

The DAG should run without error and produce the same result as with deferrable=False

### How to reproduce

Run any EksPodOperator with deferrable=True

### Anything else

```console
content-type;host;x-amz-date;x-amz-security-token;x-amz-target
ed0a66facc5d11f21f1673d559ae47610eccc44488ef4bce5816471fe2712851
[2024-05-17, 10:03:47 UTC] {{auth.py:428}} DEBUG - StringToSign:
AWS4-HMAC-SHA256
20240517T100347Z
20240517/eu-west-1/logs/aws4_request
dbd39dc01e3f6b1a289cc0cc9c53a767cbbe72eecb64a8a183427f4f676bcb56
[2024-05-17, 10:03:47 UTC] {{auth.py:430}} DEBUG - Signature:
954155e1323c759697534fffabe4884507486257c1fa4431de20677233591b5e
[2024-05-17, 10:03:47 UTC] {{httpsession.py:97}} DEBUG - Certificate path: /usr/local/airflow/.local/lib/python3.11/site-packages/certifi/cacert.pem
[2024-05-17, 10:03:47 UTC] {{parsers.py:240}} DEBUG - Response headers: {'x-amzn-RequestId': '8ce9828f-62fc-4516-b7ee-e3d040139969', 'Content-Type': 'application/x-amz-json-1.1', 'Content-Length': '80', 'Date': 'Fri, 17 May 2024 10:03:47 GMT'}
[2024-05-17, 10:03:47 UTC] {{parsers.py:241}} DEBUG - Response body:
b'{"nextSequenceToken":"49645339292837365377931268746884745014674415981042861026"}'
[2024-05-17, 10:03:47 UTC] {{retryhandler.py:211}} DEBUG - No retry needed.
[2024-05-17, 10:03:49 UTC] {{pod.py:145}} INFO - Checking pod 'pod-example-with-xcom-push-dev-xir2rd2h' in namespace 'dps-mwaa-computing-dev'.
[2024-05-17, 10:03:49 UTC] {{base.py:83}} INFO - Using connection ID 'kubernetes_default' for task execution.
[2024-05-17, 10:03:49 UTC] {{kube_config.py:482}} WARNING - Config not found: /tmp/tmp795wial1
[2024-05-17, 10:03:49 UTC] {{pod.py:227}} ERROR - Exception occurred while checking pod phase:
Traceback (most recent call last):
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/providers/cncf/kubernetes/triggers/pod.py", line 148, in run
    pod = await self.hook.get_pod(
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/providers/cncf/kubernetes/hooks/kubernetes.py", line 564, in get_pod
    async with self.get_conn() as connection:
  File "/usr/local/lib/python3.11/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/providers/cncf/kubernetes/hooks/kubernetes.py", line 551, in get_conn
    kube_client = await self._load_config() or async_client.ApiClient()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/providers/cncf/kubernetes/hooks/kubernetes.py", line 498, in _load_config
    await async_config.load_kube_config(
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/kubernetes_asyncio/config/kube_config.py", line 566, in load_kube_config
    loader = _get_kube_config_loader_for_yaml_file(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/kubernetes_asyncio/config/kube_config.py", line 530, in _get_kube_config_loader_for_yaml_file
    return KubeConfigLoader(
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/kubernetes_asyncio/config/kube_config.py", line 148, in __init__
    self.set_active_context(active_context)
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/kubernetes_asyncio/config/kube_config.py", line 159, in set_active_context
    context_name = self._config['current-context']
                   ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/kubernetes_asyncio/config/kube_config.py", line 415, in __getitem__
    raise ConfigException(
kubernetes_asyncio.config.config_exception.ConfigException: Invalid kube-config file. Expected key current-context in kube-config
[2024-05-17, 10:03:49 UTC] {{triggerer_job_runner.py:602}} INFO - Trigger dps_example-dags_k8s_xcom_push/manual__2024-05-17T10:03:24+00:00/execute_pod/-1/1 (ID 34) fired: TriggerEvent<{'name': 'pod-example-with-xcom-push-dev-xir2rd2h', 'namespace': 'dps-mwaa-computing-dev', 'status': 'error', 'message': 'Invalid kube-config file. Expected key current-context in kube-config', 'stack_trace': 'Traceback (most recent call last):\n  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/providers/cncf/kubernetes/triggers/pod.py", line 148, in run\n    pod = await self.hook.get_pod(\n          ^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/providers/cncf/kubernetes/hooks/kubernetes.py", line 564, in get_pod\n    async with self.get_conn() as connection:\n  File "/usr/local/lib/python3.11/contextlib.py", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/providers/cncf/kubernetes/hooks/kubernetes.py", line 551, in get_conn\n    kube_client = await self._load_config() or async_client.ApiClient()\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/providers/cncf/kubernetes/hooks/kubernetes.py", line 498, in _load_config\n    await async_config.load_kube_config(\n  File "/usr/local/airflow/.local/lib/python3.11/site-packages/kubernetes_asyncio/config/kube_config.py", line 566, in load_kube_config\n    loader = _get_kube_config_loader_for_yaml_file(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/airflow/.local/lib/python3.11/site-packages/kubernetes_asyncio/config/kube_config.py", line 530, in _get_kube_config_loader_for_yaml_file\n    return KubeConfigLoader(\n           ^^^^^^^^^^^^^^^^^\n  File "/usr/local/airflow/.local/lib/python3.11/site-packages/kubernetes_asyncio/config/kube_config.py", line 148, in __init__\n    self.set_active_context(active_context)\n  File "/usr/local/airflow/.local/lib/python3.11/site-packages/kubernetes_asyncio/config/kube_config.py", line 159, in set_active_context\n    context_name = self._config[\'current-context\']\n                   ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/airflow/.local/lib/python3.11/site-packages/kubernetes_asyncio/config/kube_config.py", line 415, in __getitem__\n    raise ConfigException(\nkubernetes_asyncio.config.config_exception.ConfigException: Invalid kube-config file. Expected key current-context in kube-config\n'}>
[2024-05-17, 10:03:55 UTC] {{__init__.py:54}} DEBUG - Loading core task runner: StandardTaskRunner
[2024-05-17, 10:03:55 UTC] {{base_task_runner.py:72}} DEBUG - Planning to run as the  user
[2024-05-17, 10:03:56 UTC] {{taskinstance.py:1965}} DEBUG - <TaskInstance: dps_example-dags_k8s_xcom_push.execute_pod manual__2024-05-17T10:03:24+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-05-17, 10:03:56 UTC] {{taskinstance.py:1965}} DEBUG - <TaskInstance: dps_example-dags_k8s_xcom_push.execute_pod manual__2024-05-17T10:03:24+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-05-17, 10:03:56 UTC] {{taskinstance.py:1965}} DEBUG - <TaskInstance: dps_example-dags_k8s_xcom_push.execute_pod manual__2024-05-17T10:03:24+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2024-05-17, 10:03:56 UTC] {{taskinstance.py:1965}} DEBUG - <TaskInstance: dps_example-dags_k8s_xcom_push.execute_pod manual__2024-05-17T10:03:24+00:00 [queued]> dependency 'Trigger Rule' PASSED: True, The task instance did not have any upstream tasks.
[2024-05-17, 10:03:56 UTC] {{taskinstance.py:1965}} DEBUG - <TaskInstance: dps_example-dags_k8s_xcom_push.execute_pod manual__2024-05-17T10:03:24+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2024-05-17, 10:03:56 UTC] {{taskinstance.py:1956}} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dps_example-dags_k8s_xcom_push.execute_pod manual__2024-05-17T10:03:24+00:00 [queued]>
[2024-05-17, 10:03:56 UTC] {{taskinstance.py:1965}} DEBUG - <TaskInstance: dps_example-dags_k8s_xcom_push.execute_pod manual__2024-05-17T10:03:24+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2024-05-17, 10:03:56 UTC] {{taskinstance.py:1965}} DEBUG - <TaskInstance: dps_example-dags_k8s_xcom_push.execute_pod manual__2024-05-17T10:03:24+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-05-17, 10:03:56 UTC] {{taskinstance.py:1965}} DEBUG - <TaskInstance: dps_example-dags_k8s_xcom_push.execute_pod manual__2024-05-17T10:03:24+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-05-17, 10:03:56 UTC] {{taskinstance.py:1965}} DEBUG - <TaskInstance: dps_example-dags_k8s_xcom_push.execute_pod manual__2024-05-17T10:03:24+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2024-05-17, 10:03:56 UTC] {{taskinstance.py:1965}} DEBUG - <TaskInstance: dps_example-dags_k8s_xcom_push.execute_pod manual__2024-05-17T10:03:24+00:00 [queued]> dependency 'Trigger Rule' PASSED: True, The task instance did not have any upstream tasks.
[2024-05-17, 10:03:56 UTC] {{taskinstance.py:1956}} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dps_example-dags_k8s_xcom_push.execute_pod manual__2024-05-17T10:03:24+00:00 [queued]>
[2024-05-17, 10:03:56 UTC] {{taskinstance.py:2168}} INFO - Resuming after deferral
[2024-05-17, 10:03:56 UTC] {{taskinstance.py:2191}} INFO - Executing <Task(EksPodOperator): execute_pod> on 2024-05-17 10:03:24+00:00
[2024-05-17, 10:03:56 UTC] {{standard_task_runner.py:60}} INFO - Started process 11776 to run task
[2024-05-17, 10:03:56 UTC] {{standard_task_runner.py:87}} INFO - Running: ['airflow', 'tasks', 'run', 'dps_example-dags_k8s_xcom_push', 'execute_pod', 'manual__2024-05-17T10:03:24+00:00', '--job-id', '100630', '--raw', '--subdir', 'DAGS_FOLDER/dps/example_dags/k8s_xcom_push.py', '--cfg-path', '/tmp/tmpnojwnjsy']
[2024-05-17, 10:03:56 UTC] {{standard_task_runner.py:88}} INFO - Job 100630: Subtask execute_pod
[2024-05-17, 10:03:56 UTC] {{cli_action_loggers.py:67}} DEBUG - Calling callbacks: [<function default_action_log at 0x7f724b5caa20>]
[2024-05-17, 10:03:56 UTC] {{retries.py:93}} DEBUG - Running RenderedTaskInstanceFields.write with retries. Try 1 of 3
[2024-05-17, 10:03:56 UTC] {{retries.py:93}} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2024-05-17, 10:03:56 UTC] {{__init__.py:115}} DEBUG - Preparing lineage inlets and outlets
[2024-05-17, 10:03:56 UTC] {{__init__.py:154}} DEBUG - inlets: [], outlets: []
[2024-05-17, 10:03:56 UTC] {{pod.py:616}} DEBUG - Triggered with event: {'name': 'pod-example-with-xcom-push-dev-xir2rd2h', 'namespace': 'dps-mwaa-computing-dev', 'status': 'error', 'message': 'Invalid kube-config file. Expected key current-context in kube-config', 'stack_trace': 'Traceback (most recent call last):\n  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/providers/cncf/kubernetes/triggers/pod.py", line 148, in run\n    pod = await self.hook.get_pod(\n          ^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/providers/cncf/kubernetes/hooks/kubernetes.py", line 564, in get_pod\n    async with self.get_conn() as connection:\n  File "/usr/local/lib/python3.11/contextlib.py", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/providers/cncf/kubernetes/hooks/kubernetes.py", line 551, in get_conn\n    kube_client = await self._load_config() or async_client.ApiClient()\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/providers/cncf/kubernetes/hooks/kubernetes.py", line 498, in _load_config\n    await async_config.load_kube_config(\n  File "/usr/local/airflow/.local/lib/python3.11/site-packages/kubernetes_asyncio/config/kube_config.py", line 566, in load_kube_config\n    loader = _get_kube_config_loader_for_yaml_file(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/airflow/.local/lib/python3.11/site-packages/kubernetes_asyncio/config/kube_config.py", line 530, in _get_kube_config_loader_for_yaml_file\n    return KubeConfigLoader(\n           ^^^^^^^^^^^^^^^^^\n  File "/usr/local/airflow/.local/lib/python3.11/site-packages/kubernetes_asyncio/config/kube_config.py", line 148, in __init__\n    self.set_active_context(active_context)\n  File "/usr/local/airflow/.local/lib/python3.11/site-packages/kubernetes_asyncio/config/kube_config.py", line 159, in set_active_context\n    context_name = self._config[\'current-context\']\n                   ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/airflow/.local/lib/python3.11/site-packages/kubernetes_asyncio/config/kube_config.py", line 415, in __getitem__\n    raise ConfigException(\nkubernetes_asyncio.config.config_exception.ConfigException: Invalid kube-config file. Expected key current-context in kube-config\n'}
[2024-05-17, 10:03:56 UTC] {{kubernetes.py:258}} DEBUG - loading kube_config from: default file
[2024-05-17, 10:03:56 UTC] {{kubernetes.py:258}} DEBUG - loading kube_config from: default file
[2024-05-17, 10:03:56 UTC] {{taskinstance.py:2698}} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/providers/cncf/kubernetes/hooks/kubernetes.py", line 255, in _get_default_client
    config.load_incluster_config(client_configuration=self.client_configuration)
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/kubernetes/config/incluster_config.py", line 121, in load_incluster_config
    try_refresh_token=try_refresh_token).load_and_set(client_configuration)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/kubernetes/config/incluster_config.py", line 54, in load_and_set
    self._load_config()
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/kubernetes/config/incluster_config.py", line 62, in _load_config
    raise ConfigException("Service host/port is not set.")
kubernetes.config.config_exception.ConfigException: Service host/port is not set.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/providers/cncf/kubernetes/operators/pod.py", line 619, in execute_complete
    pod = self.hook.get_pod(
          ^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/providers/cncf/kubernetes/hooks/kubernetes.py", line 426, in get_pod
    return self.core_v1_client.read_namespaced_pod(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/functools.py", line 1001, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/providers/cncf/kubernetes/hooks/kubernetes.py", line 283, in core_v1_client
    return client.CoreV1Api(api_client=self.api_client)
                                       ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/functools.py", line 1001, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/providers/cncf/kubernetes/hooks/kubernetes.py", line 279, in api_client
    return self.get_conn()
           ^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/providers/cncf/kubernetes/hooks/kubernetes.py", line 247, in get_conn
    return self._get_default_client(cluster_context=cluster_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/providers/cncf/kubernetes/hooks/kubernetes.py", line 260, in _get_default_client
    config.load_kube_config(
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/kubernetes/config/kube_config.py", line 808, in load_kube_config
    loader = _get_kube_config_loader(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/kubernetes/config/kube_config.py", line 767, in _get_kube_config_loader
    raise ConfigException(
kubernetes.config.config_exception.ConfigException: Invalid kube-config file. No configuration found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/providers/cncf/kubernetes/hooks/kubernetes.py", line 255, in _get_default_client
    config.load_incluster_config(client_configuration=self.client_configuration)
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/kubernetes/config/incluster_config.py", line 121, in load_incluster_config
    try_refresh_token=try_refresh_token).load_and_set(client_configuration)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/kubernetes/config/incluster_config.py", line 54, in load_and_set
    self._load_config()
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/kubernetes/config/incluster_config.py", line 62, in _load_config
    raise ConfigException("Service host/port is not set.")
kubernetes.config.config_exception.ConfigException: Service host/port is not set.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 1604, in resume_execution
    return execute_callable(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/providers/cncf/kubernetes/operators/pod.py", line 645, in execute_complete
    pod = self.pod_manager.await_pod_completion(pod, istio_enabled, self.base_container_name)
          ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/functools.py", line 1001, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/providers/cncf/kubernetes/operators/pod.py", line 460, in pod_manager
    return PodManager(kube_client=self.client, progress_callback=self._progress_callback)
                                  ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/functools.py", line 1001, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/providers/cncf/kubernetes/operators/pod.py", line 474, in client
    return self.hook.core_v1_client
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/functools.py", line 1001, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/providers/cncf/kubernetes/hooks/kubernetes.py", line 283, in core_v1_client
    return client.CoreV1Api(api_client=self.api_client)
                                       ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/functools.py", line 1001, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/providers/cncf/kubernetes/hooks/kubernetes.py", line 279, in api_client
    return self.get_conn()
           ^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/providers/cncf/kubernetes/hooks/kubernetes.py", line 247, in get_conn
    return self._get_default_client(cluster_context=cluster_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/providers/cncf/kubernetes/hooks/kubernetes.py", line 260, in _get_default_client
    config.load_kube_config(
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/kubernetes/config/kube_config.py", line 808, in load_kube_config
    loader = _get_kube_config_loader(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/kubernetes/config/kube_config.py", line 767, in _get_kube_config_loader
    raise ConfigException(
kubernetes.config.config_exception.ConfigException: Invalid kube-config file. No configuration found.
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jx2lee** [comment]
Hi! If this doesn't start, can I take it?

**Comment by o-nikolas** [comment]
@vincbeck I think your recent changes fix this?

**Comment by vincbeck** [comment]
Yes, https://github.com/apache/airflow/pull/51255 should fix it
