### ISSUE TITLE
DagProcessor - UPDATE statement on table 'serialized_dag' expected to update 1 row(s); 0 were matched.

### ISSUE THREAD

**Issue by raphaelauv** [apache/airflow#42105]
### Apache Airflow version

2.10.1

### What happened?

I have regularly this error in the logs of the DagProcessor ( with a Postgres 15 ) : 

```log
[2024-09-08T22:04:31.184+0000] {__init__.py:216} ERROR - Failed to export batch code: 400, reason: proto: illegal wireType 6
Process DagFileProcessor222516-Process:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 207, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 188, in _handle_dag_file_processing
    result: tuple[int, int, int] = dag_file_processor.process_file(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 942, in process_file
    serialize_errors = DagFileProcessor.save_dag_to_db(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 139, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 982, in save_dag_to_db
    import_errors = DagBag._sync_to_db(dags=dags, processor_subdir=dag_directory, session=session)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 707, in _sync_to_db
    for attempt in run_with_db_retries(logger=log):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 443, in __iter__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 398, in <lambda>
    self._add_action_func(lambda rs: rs.outcome.result())
                                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 723, in _sync_to_db
    DAG.bulk_write_to_db(dags.values(), processor_subdir=processor_subdir, session=session)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 3414, in bulk_write_to_db
    dataset_manager.create_datasets(dataset_models=new_datasets, session=session)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/datasets/manager.py", line 65, in create_datasets
    session.flush()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 3449, in flush
    self._flush(objects)
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 3588, in _flush
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 3549, in _flush
    flush_context.execute()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 237, in save_obj
    _emit_update_statements(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 1035, in _emit_update_statements
    raise orm_exc.StaleDataError(
sqlalchemy.orm.exc.StaleDataError: UPDATE statement on table 'serialized_dag' expected to update 1 row(s); 0 were matched.

```

### Versions of Apache Airflow Providers

apache-airflow-providers-postgres==5.12.0

### Deployment

Official Apache Airflow Helm Chart

CeleryExecutor

with gitsync

2 scheduler , 1 triggerer , N workers

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by AlexMTX** [comment]
I encountered the same problem.
It looks like a race condition within the dag processor process.
Do you have more than 1 DAG defined in 1 python file?

Try to limit the number of processes to 1 with this variable:
https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#parsing-processes

In the helm chart:
`  dagProcessor:
    enabled: true

    env:
      - name: AIRFLOW__SCHEDULER__PARSING_PROCESSES
        value: "1"`

**Comment by dw7o** [comment]
We also face this problem - although we've set the corresponding setting and have only one DAG per file.
The DAG processor runs as stand-alone process.
As a result, it happens that DAGs suddenly vanish and re-appear after the next processor run. Unfortunately, this happens often during our batch loads causing ExternalDagSensors to fail.
(Setup: Docker Swarm, dedicated PostgreSQL database)

**Comment by dw7o** [comment]
> It might be worth it to try with 2.10.5 [@dw7o](https://github.com/dw7o)

We are currently running 2.10.4 and I did not spot anything around that issue in the 2.10.5 changelog. Which change do you have in mind, @ephraimbuddy?

**Comment by ephraimbuddy** [comment]
> > It might be worth it to try with 2.10.5 [@dw7o](https://github.com/dw7o)
> 
> We are currently running 2.10.4 and I did not spot anything around that issue in the 2.10.5 changelog. Which change do you have in mind, [@ephraimbuddy](https://github.com/ephraimbuddy)?

No change in mind. I asked because the issue was reported in Airflow 2.10.1, which is a bit old. Good to know you are in a recent version. Do you have a way to reproduce it?

**Comment by dw7o** [comment]
> Do you have a way to reproduce it?

Unfortunately, not that I am aware of. :-( It seems to affect random DAGs at random times (even when the affected DAGs were already done for today, not while running).
Some of our config settings:
```
standalone_dag_processor = True
dag_dir_list_interval = 300
print_stats_interval = 1200
parsing_processes = 1
file_parsing_sort_mode = modified_time
```

**Comment by AlexMTX** [comment]
@dw7o please, check that you don't have more than 1 simultaneously running container for dag processor in docker swarm.
My thought is that it can be a concurrency on the containers level, rather than inside the one container level.

**Comment by DjVinnii** [comment]
I noticed this issue is also happening at our environment (Airflow 2.10.5). I'm curious if there is any update on this and if this is also happening in 2.11 and/or 3.0

**Comment by Lothnic** [comment]
One potential solution can be a pessimistic lock using the database's SELECT ... FOR UPDATE feature, this would explicitly lock the relevant rows in the serialized dag table before an update is attempted this serializes access to the dag records during the critical update phase, preventing the race condition and the resulting stale data error, i am open to discussing any performance implications

**Comment by raphaelauv** [comment]
airflow 2.10 is EOL ( deprecated ) , so I'm closing
