### ISSUE TITLE
TableauOperator fails to trigger Tableau Task

### ISSUE THREAD

**Issue by farrukh-t** [apache/airflow#42248]
### Apache Airflow Provider(s)

tableau

### Versions of Apache Airflow Providers

apache-airflow-providers-tableau==4.5.0

### Apache Airflow version

v2.9.0

### Operating System

ubuntu

### Deployment

Docker-Compose

### What happened

TableauOperator fails with `resource="tasks"` and `method="run"` arguments with the following traceback:
```txt
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/tableau/operators/tableau.py", line 118, in execute
    response = method(resource_id)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tableauserverclient/server/endpoint/endpoint.py", line 258, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tableauserverclient/server/endpoint/tasks_endpoint.py", line 73, in run
    if not task_item.id:
           ^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'id'
```

### What you think should happen instead

I believe the issue is that `Tasks.run` method [expects](https://github.com/tableau/server-client-python/blob/257cf616f35cc36b24a73e9e102886a52ead1853/tableauserverclient/server/endpoint/tasks_endpoint.py#L72) a `task_item` argument  of type `TaskItem` and `TableauOperator` [passes](https://github.com/apache/airflow/blob/a5d0a63d8784d7f4100a4770748c783261968e3c/airflow/providers/tableau/operators/tableau.py#L118) the task's id as a `str` instead. 

### How to reproduce

Execute `TableauOperator` with `resource="tasks"` and `method="run"` arguments

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by rawwar** [comment]
@KS0107 , assigning this to you

**Comment by aarochuk** [comment]
Can I work on this?

**Comment by aarochuk** [comment]
I have been working on this and I think that this issue is that you are using resource="tasks" instead of resource="task" and I am not sure resource="tasks" is a valid resource. Are you sure you mean to use resource="tasks"? In addition @farrukh-t can you provide the full command you used to create the TableauOperator

**Comment by farrukh-t** [comment]
> I have been working on this and I think that this issue is that you are using resource="tasks" instead of resource="task" and I am not sure resource="tasks" is a valid resource. Are you sure you mean to use resource="tasks"?

@aarochuk I'm pretty sure it should be `"tasks"`, not `"task"`. There is a dictionary `RESOURCE_METHODS` defined on [line 32](https://github.com/apache/airflow/blob/a5d0a63d8784d7f4100a4770748c783261968e3c/airflow/providers/tableau/operators/tableau.py#L32C1-L32C18):

<img width="367" alt="Image" src="https://github.com/user-attachments/assets/eec0f592-ed1c-4054-89d9-6fb327002036" />

Keys from this dictionary are used to validate the value of `resource` passed to `TableauOperator`:

<img width="842" alt="Image" src="https://github.com/user-attachments/assets/bc43519c-411a-4f18-8d78-fbd9988de247" />

If you do pass `resource="task"` instead, Airflow will raise an error:
```log
airflow.exceptions.AirflowException: Resource not found! Available Resources: dict_keys(['datasources', 'groups', 'projects', 'schedule', 'sites', 'subscriptions', 'tasks', 'users', 'workbooks'])
```

> In addition can you provide the full command you used to create the TableauOperator

Sure, this should be enough to reproduce the bug, just make sure you replace the placeholders with an actual task uuid and a Tableau connection id:

```python
from airflow import DAG
from airflow.providers.tableau.operators.tableau import TableauOperator

with DAG(dag_id="debug_tableau") as dag:
    TableauOperator(
        task_id="run_tableau_task",
        resource="tasks",
        method="run",
        find="<replace_with_your_tableau_task_uuid>",
        tableau_conn_id="<replace_with_your_tableau_connection_id>",
    )
```
Failed task's logs:
```log
[2025-03-17, 20:41:20 UTC] {base.py:84} INFO - Using connection ID 'tableau_conn' for task execution.
[2025-03-17, 20:41:20 UTC] {server.py:246} INFO - versions: 3.21, 2.4
[2025-03-17, 20:41:20 UTC] {auth_endpoint.py:91} INFO - Signed into https://REDACTED/ as user with id REDACTED
[2025-03-17, 20:41:20 UTC] {auth_endpoint.py:115} INFO - Signed out
[2025-03-17, 20:41:20 UTC] {taskinstance.py:441} ▼ Post task execution logs
[2025-03-17, 20:41:20 UTC] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/tableau/operators/tableau.py", line 118, in execute
    response = method(resource_id)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tableauserverclient/server/endpoint/endpoint.py", line 274, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tableauserverclient/server/endpoint/tasks_endpoint.py", line 134, in run
    if not task_item.id:
           ^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'id'
[2025-03-17, 20:41:20 UTC] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=debug_tableau, task_id=run_tableau_task, execution_date=20250317T204115, start_date=20250317T204119, end_date=20250317T204120
[2025-03-17, 20:41:20 UTC] {standard_task_runner.py:110} ERROR - Failed to execute job 3 for task run_tableau_task ('str' object has no attribute 'id'; 20498)
[2025-03-17, 20:41:20 UTC] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-03-17, 20:41:20 UTC] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
```

**Comment by potiuk** [comment]
@aarochuk We are unassigning you from this issue as part of our updated [assignment policy](https://github.com/apache/airflow/blob/main/contributing-docs/04_how_to_contribute.rst#contribute-code-changes).

This is not meant to discourage your contribution — quite the opposite! You are still very welcome to work on this issue and submit a PR for it. Simply comment that you are working on it and open a PR when ready.

We found that formal assignments were not working well, as they often prevented others from contributing when the assignee was not actively working on the issue.
