### ISSUE TITLE
DAG Param incorrectly convert enum objects to strings

### ISSUE THREAD

**Issue by cdabella** [apache/airflow#42524]
### Apache Airflow version

2.10.1

### What happened?

Using a DAG Param with a type of `object` and `enum` set to a list of possible objects is reflected as a string in Trigger DAG UI, both in the selector and in the underlying JSON.
![image](https://github.com/user-attachments/assets/23f4c62b-6bc7-4e4d-bb8e-eadb322e8a54)

When attempting to run the DAG using the value, the DAG will fail to run
![image](https://github.com/user-attachments/assets/191486b2-2ef5-4eaf-9523-482a6377204a)

### What you think should happen instead?

JSON schemas support enums of any type 

> Elements in the array might be of any type, including null.

(source: https://json-schema.org/draft/2020-12/json-schema-validation#section-6.1.2-3) . They should be configurable and supported by DAG Parameters, and should allow for successful selection and execution of the DAG from the Trigger DAG UI.

### How to reproduce

Create the following DAG
```python
from airflow.decorators import dag, task
from pendulum import datetime
from airflow.models.param import Param

keys = ["a", "b", "c"]
values_display_list = [{"key": key, "value": key.upper()} for key in keys]


@dag(
    start_date=datetime(2024, 1, 1),
    schedule=None,
    catchup=False,
    params={
        "x": Param(
            values_display_list[0],
            type=["object"],
            enum=values_display_list,
        ),
    },
    tags=["example"],
)
def example_params():
    @task
    def example_params_task(*, params, **kwargs) -> None:
        if params:
            print(f"Params: {params}")
        else:
            print("No Params")

    example_params_task()


# Instantiate the DAG
example_params()
```

### Operating System

Debian 12 (Bookworm)

### Versions of Apache Airflow Providers

apache-airflow==2.10.1+astro.1

### Deployment

Other Docker-based deployment

### Deployment details

Astro CLI running Astro Runtime 12.1.0

### Anything else?

I think this issue might be caused by the the trigger templating at https://github.com/apache/airflow/blob/2.10.2/airflow/www/templates/airflow/trigger.html#L77-L86

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jscheffl** [comment]
Yes, this described problem is a limitatio of the trigger UI form. Object element enums are not support as nobody implemented / requested this feature.

Objects are currently only supported in the UI as JSON entry field. Enums only with strings.

Nevertheless if you trigger via API or manually adjust the generated JSON in the trigger form, JSON validation will work.

Are you willing to supply an improvement?

**Comment by cdabella** [comment]
I'm willing to try, though front-end work is definitely not my strength.

From a persona perspective, the primary use case for this is when the DAG Author and DAG operator are different users, and the DAG author explicitly is controlling the available actions for their downstream DAG operator users. In this scenario, the DAG operator may not be aware of the underlying DAG code.

I've been playing around with how the `trigger.html` and `trigger.js` interact, and specifically the user experience for complex objects that should be considered read-only or selectable from an finite list. This has raised some questions for me.

## How to select values?
For standard object params, a CodeMirror text block is added in the parameter form.

![image](https://github.com/user-attachments/assets/ab47b1fc-a9bd-4dd8-befe-b9af13d50ef5)

Conceptually this doesn't align with our goal of an enum, as the textbox should be read-only, but the question becomes how to select from many read-only text boxes.

Providing a key seems a appropriate. This would need to be the inverse of the existing [`values_display`](https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/params.html#json-schema-validation) where the key is actually the parameter value and the value is the UX to be displayed, as complex objects may not be easily serializable into dict keys. I have a working example by adding a `keys_display` parameter to the Param object, but this could probably be renamed to `enum_keys` or similar for simplicity.

## How to inform users of the selection?
If we are using keyed selection, what is the appropriate way to inform a user of the actual reflection of that selection in the parameters? There is the `Generated Configuration JSON` view, but this is:

1. Collapsed by default
2. Mutable

We could add a CodeMirror textarea with `readOnly` set below the enum selector, but this has the potential to greatly expand the form size. Should a view like this always be visible? Collapsable?

It feels like there should maybe be a requirement with the `enum` param to have an `enum_keys`  param (or autogenerate one).

## How to store the values?
Today the values for enums are stored as value attributes on the `option` tag. For complex JSON objects this leads either to malformed HTML or JSON parse errors because of single quotes. The object could be stored as a child of the option in a script tag, something like the following? 

```html
<script id="element_x_option_1" type="text/json">{"key":"a","value":"a"}</script>
```

## Is there a better UX that achieves similar results?
From the use case I'm basing this functionality off of, it feels like there is a more complex ask here around have a Parameter Group where parameters are inter-linked, and must be set as a group. This is beyond my skillset today but I just want to callout that another option is possibly viable for the future.

**Comment by jscheffl** [comment]
Thanks for the write-up. I assume this level of complexity might also be the reason why this feature was not initially contributed (by me).

Note that the UI is currently under re-work. The current Airflow 2.10-line will not receive additional features. A new ReactJS based UI with a new trigger form is to be developed. So most probably it makes sense to focus on Airflow 3 for this limitation.

Have you considered the alternative to abstract the problem away in the UI such that the parameter selection is a "simple" drop-down, even with values-display which gives an abstract selection in human readable manner to the user. Based on the selection a first task in the DAG resolves the "simple string" into a more complex dictionary with a lookup? That would not need UI complexity and you can hide all technical details in the DAG code.

Something like:
```
@dag(
    schedule=None,
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
    params={
        "pick_with_label": Param(
            3,
            type="number",
            title="Select one Number",
            description="With drop down selections you can also have nice display labels for the values.",
            enum=[*range(1, 10)],
            values_display={
                1: "One",
                2: "Two",
                3: "Three",
                4: "Four - is like you take three and get one for free!",
                5: "Five",
                6: "Six",
                7: "Seven",
                8: "Eight",
                9: "Nine",
            },
        ),
    },
)
def example_python_decorator():
    @task
    def select_config_details(**kwargs):
        """Select further config parameters depending on user selection."""
        params: ParamsDict = kwargs["params"]
        pick_with_label = params["pick_with_label"]
        my_complex_config = {
            1: {
                "foo": "bar",
            },
            ...
        }
        return my_complex_config[pick_with_label]
```

Besides all the options... from UX Perspective it might be best to have a MD per option and a complex JSON object and render a radio box selection per option in the enum? Would you expect the user wanting to see/understand the object really or would a description be more appropriate?

**Comment by leoperegrino** [comment]
@jscheffl maybe this is related if not I can open a separate issue. I'm running `apache/airflow:2.8.1-python3.11` container and working with `Enum` and `StrEnum` to help me with the type system. The main difference between these two enum types is that `StrEnum` when cast to string (`f'{MyStrEnum.A}'` or `str(MyStrEnum.A)`) will auto use the `.value` attribute.

When passing a `StrEnum` to a `tasks` decorated function, `StrEnum` arguments will be cast to string. Calls to `StrEnum` methods then raise `AttributeError`. Normal enums work as usual. 


```python
from enum import Enum
from enum import StrEnum

from airflow.decorators import dag
from airflow.decorators import task


class MyEnum(Enum):
    A = 'A'


class MyStrEnum(StrEnum):
    A = 'A'


@dag(schedule_interval=None)
def enum_dag():

    @task(task_id='test_enum')
    def test_enum(enum: MyEnum):
        return enum.name

    @task(task_id='test_str_enum')
    def test_str_enum(str_enum: MyStrEnum):
        return str_enum.name

    test_enum(enum=MyEnum.A)
    test_str_enum(str_enum=MyStrEnum.A)


enum_dag()

```

`test_enum`

```log
f063d55d4244
*** Found local files:
***   * /opt/airflow/logs/dag_id=enum_dag/run_id=manual__2025-02-11T16:58:48.370587+00:00/task_id=test_enum/attempt=1.log
[2025-02-11, 16:58:50 UTC] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: enum_dag.test_enum manual__2025-02-11T16:58:48.370587+00:00 [queued]>
[2025-02-11, 16:58:50 UTC] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: enum_dag.test_enum manual__2025-02-11T16:58:48.370587+00:00 [queued]>
[2025-02-11, 16:58:50 UTC] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-02-11, 16:58:50 UTC] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): test_enum> on 2025-02-11 16:58:48.370587+00:00
[2025-02-11, 16:58:50 UTC] {standard_task_runner.py:60} INFO - Started process 2879665 to run task
[2025-02-11, 16:58:50 UTC] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'enum_dag', 'test_enum', 'manual__2025-02-11T16:58:48.370587+00:00', '--job-id', '6650', '--raw', '--subdir', 'DAGS_FOLDER/enum_dag.py', '--cfg-path', '/tmp/tmppaapxvvf']
[2025-02-11, 16:58:50 UTC] {standard_task_runner.py:88} INFO - Job 6650: Subtask test_enum
[2025-02-11, 16:58:50 UTC] {task_command.py:423} INFO - Running <TaskInstance: enum_dag.test_enum manual__2025-02-11T16:58:48.370587+00:00 [running]> on host f063d55d4244
[2025-02-11, 16:58:50 UTC] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='enum_dag' AIRFLOW_CTX_TASK_ID='test_enum' AIRFLOW_CTX_EXECUTION_DATE='2025-02-11T16:58:48.370587+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-11T16:58:48.370587+00:00'
[2025-02-11, 16:58:50 UTC] {python.py:201} INFO - Done. Returned value was: A
[2025-02-11, 16:58:50 UTC] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=enum_dag, task_id=test_enum, execution_date=20250211T165848, start_date=20250211T165850, end_date=20250211T165850
[2025-02-11, 16:58:50 UTC] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-02-11, 16:58:50 UTC] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
```

`test_str_enum`

```log
f063d55d4244
*** Found local files:
***   * /opt/airflow/logs/dag_id=enum_dag/run_id=manual__2025-02-11T16:58:48.370587+00:00/task_id=test_str_enum/attempt=1.log
[2025-02-11, 16:58:50 UTC] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: enum_dag.test_str_enum manual__2025-02-11T16:58:48.370587+00:00 [queued]>
[2025-02-11, 16:58:50 UTC] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: enum_dag.test_str_enum manual__2025-02-11T16:58:48.370587+00:00 [queued]>
[2025-02-11, 16:58:50 UTC] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-02-11, 16:58:50 UTC] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): test_str_enum> on 2025-02-11 16:58:48.370587+00:00
[2025-02-11, 16:58:50 UTC] {standard_task_runner.py:60} INFO - Started process 2879664 to run task
[2025-02-11, 16:58:50 UTC] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'enum_dag', 'test_str_enum', 'manual__2025-02-11T16:58:48.370587+00:00', '--job-id', '6649', '--raw', '--subdir', 'DAGS_FOLDER/enum_dag.py', '--cfg-path', '/tmp/tmp5lou4idb']
[2025-02-11, 16:58:50 UTC] {standard_task_runner.py:88} INFO - Job 6649: Subtask test_str_enum
[2025-02-11, 16:58:50 UTC] {task_command.py:423} INFO - Running <TaskInstance: enum_dag.test_str_enum manual__2025-02-11T16:58:48.370587+00:00 [running]> on host f063d55d4244
[2025-02-11, 16:58:50 UTC] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='enum_dag' AIRFLOW_CTX_TASK_ID='test_str_enum' AIRFLOW_CTX_EXECUTION_DATE='2025-02-11T16:58:48.370587+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-11T16:58:48.370587+00:00'
[2025-02-11, 16:58:50 UTC] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/enum_dag.py", line 27, in test_str_enum
    return str_enum.name
           ^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'name'
[2025-02-11, 16:58:50 UTC] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=enum_dag, task_id=test_str_enum, execution_date=20250211T165848, start_date=20250211T165850, end_date=20250211T165850
[2025-02-11, 16:58:50 UTC] {standard_task_runner.py:107} ERROR - Failed to execute job 6649 for task test_str_enum ('str' object has no attribute 'name'; 2879664)
[2025-02-11, 16:58:50 UTC] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-02-11, 16:58:50 UTC] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
```

**Comment by jscheffl** [comment]
> [@jscheffl](https://github.com/jscheffl) maybe this is related if not I can open a separate issue. I'm running `apache/airflow:2.8.1-python3.11` container and working with `Enum` and `StrEnum` to help me with the type system. The main difference between these two enum types is that `StrEnum` when cast to string (`f'{MyStrEnum.A}'` or `str(MyStrEnum.A)`) will auto use the `.value` attribute.

@leoperegrino No this is a totally different issue. It might even be a discussion not an issue.
