### ISSUE TITLE
500 on any admin pages

### ISSUE THREAD

**Issue by eliskovets** [apache/airflow#43270]
### Apache Airflow version

2.10.2

### What happened?

Getting 500 on any of the admin pages: pools, connections, users, etc.

### What you think should happen instead?

No 500 thrown

### How to reproduce

Not sure if it's specific to our authentication configuration as we just switched to authentication through Google OAuth, but here's the trace from the webserver(we also upgraded from 2.9.3 to 2.10.2): 
```

[2024-10-22T15:15:37.443+0000] {app.py:1744} ERROR - Exception on /users/list/ [GET]
-- | -- | --
22 October 2024 at 11:15 (UTC-4:00) | Traceback (most recent call last):
22 October 2024 at 11:15 (UTC-4:00) | File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2529, in wsgi_app
22 October 2024 at 11:15 (UTC-4:00) | response = self.full_dispatch_request()
22 October 2024 at 11:15 (UTC-4:00) | File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
22 October 2024 at 11:15 (UTC-4:00) | rv = self.handle_user_exception(e)
22 October 2024 at 11:15 (UTC-4:00) | File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
22 October 2024 at 11:15 (UTC-4:00) | rv = self.dispatch_request()
22 October 2024 at 11:15 (UTC-4:00) | File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
22 October 2024 at 11:15 (UTC-4:00) | return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
22 October 2024 at 11:15 (UTC-4:00) | File "/usr/local/lib/python3.10/site-packages/flask_appbuilder/security/decorators.py", line 137, in wraps
22 October 2024 at 11:15 (UTC-4:00) | return f(self, *args, **kwargs)
22 October 2024 at 11:15 (UTC-4:00) | File "/usr/local/lib/python3.10/site-packages/flask_appbuilder/views.py", line 550, in list
22 October 2024 at 11:15 (UTC-4:00) | widgets = self._list()
22 October 2024 at 11:15 (UTC-4:00) | File "/usr/local/lib/python3.10/site-packages/flask_appbuilder/baseviews.py", line 1186, in _list
22 October 2024 at 11:15 (UTC-4:00) | form = self.search_form.refresh()
22 October 2024 at 11:15 (UTC-4:00) | File "/usr/local/lib/python3.10/site-packages/flask_appbuilder/forms.py", line 327, in refresh
22 October 2024 at 11:15 (UTC-4:00) | form = self(obj=obj)
22 October 2024 at 11:15 (UTC-4:00) | File "/usr/local/lib/python3.10/site-packages/wtforms/form.py", line 209, in __call__
22 October 2024 at 11:15 (UTC-4:00) | return type.__call__(cls, *args, **kwargs)
22 October 2024 at 11:15 (UTC-4:00) | File "/usr/local/lib/python3.10/site-packages/flask_wtf/form.py", line 73, in __init__
22 October 2024 at 11:15 (UTC-4:00) | super().__init__(formdata=formdata, **kwargs)
22 October 2024 at 11:15 (UTC-4:00) | File "/usr/local/lib/python3.10/site-packages/wtforms/form.py", line 281, in __init__
22 October 2024 at 11:15 (UTC-4:00) | super().__init__(self._unbound_fields, meta=meta_obj, prefix=prefix)
22 October 2024 at 11:15 (UTC-4:00) | File "/usr/local/lib/python3.10/site-packages/wtforms/form.py", line 49, in __init__
22 October 2024 at 11:15 (UTC-4:00) | field = meta.bind_field(self, unbound_field, options)
22 October 2024 at 11:15 (UTC-4:00) | File "/usr/local/lib/python3.10/site-packages/wtforms/meta.py", line 28, in bind_field
22 October 2024 at 11:15 (UTC-4:00) | return unbound_field.bind(form=form, **options)
22 October 2024 at 11:15 (UTC-4:00) | File "/usr/local/lib/python3.10/site-packages/wtforms/fields/core.py", line 387, in bind
22 October 2024 at 11:15 (UTC-4:00) | return self.field_class(*self.args, **kw)
22 October 2024 at 11:15 (UTC-4:00) | File "/usr/local/lib/python3.10/site-packages/wtforms/fields/core.py", line 133, in __init__
22 October 2024 at 11:15 (UTC-4:00) | for k, v in flags.items():
22 October 2024 at 11:15 (UTC-4:00) | AttributeError: 'tuple' object has no attribute 'items'

```

### Operating System

Amazon Linux release 2023.6.20241010 (Amazon Linux)

### Versions of Apache Airflow Providers

```
apache-airflow-providers-amazon==8.28.0
apache-airflow-providers-asana==2.6.0
apache-airflow-providers-celery==3.8.3
apache-airflow-providers-common-compat==1.2.1
apache-airflow-providers-common-io==1.4.2
apache-airflow-providers-common-sql==1.18.0
apache-airflow-providers-databricks==6.9.0
apache-airflow-providers-datadog==3.7.1
apache-airflow-providers-elasticsearch==4.4.0
apache-airflow-providers-fab==1.4.1
apache-airflow-providers-ftp==3.11.1
apache-airflow-providers-http==4.13.0
apache-airflow-providers-imap==3.7.0
apache-airflow-providers-postgres==5.12.0
apache-airflow-providers-slack==8.9.0
apache-airflow-providers-smtp==1.8.0
apache-airflow-providers-sqlite==3.9.0
```

### Deployment

Other Docker-based deployment

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eliskovets** [comment]
Closing, looks like it's caused by wtforms=3.2.1.

**Comment by CorentinLimier** [comment]
@eliskovets we have the same issue after having deployed on airflow 2.10.2 

Before we were with airflow==2.10.1 and already with wtforms=3.2.1 and we could use the admin pages correctly. 

Did you fix this issue ? By using another wtforms version maybe ?

**Comment by eliskovets** [comment]
Yes, I've switched back to wtforms 3.1.2 and it fixed the issue. 
We have our own docker image and I noticed that we didn't use --constraint when installing with pip. After it's been added, the issue with admin pages is fixed.

**Comment by CorentinLimier** [comment]
Indeed @eliskovets ! Thank you very much, it solved also our issue.
