### ISSUE TITLE
param object do not accept array 

### ISSUE THREAD

**Issue by raphaelauv** [apache/airflow#43433]
### Apache Airflow version

2.10.2

### What happened?

I can't trigger a dag with `[ ]` or `[{"toto": 5}]` ( that are valid JSON )

```python

with DAG(
        dag_id="a",
        params={
            "x": Param(None, type="object"),
        })
```

it log

```log
Invalid input for param batch: [{'toto': 5}] is not of type 'object' Failed validating 'type' in schema: {'type': 'object'} On instance: [{'toto': 5}]
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jscheffl** [comment]
I assume this is correct.

The term "object" in the JSON schema validation we run refers to "dict" object types. See: https://json-schema.org/understanding-json-schema/reference/object.

So in your case you need to define it as array. Note that empty arrays in the UI form are always triggered with `none` value... there was also a ticket open for this to discuss how the form shall handle empty fields...

**Comment by jscheffl** [comment]
Yea... and no. Please check the details in https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/params.html#use-params-to-provide-a-trigger-ui-form -might not be obvious but exactly for this case a feature was added:

> If you add the attribute items with a
dictionary that contains a field type
with a value other than “string”, a JSON entry
field will be generated for more array types and
additional type validation as described in
[JSON Schema Array Items](https://json-schema.org/understanding-json-schema/reference/array.html#items).

...means in case you want to have non-string items be added define an item type and then a JSON style input box will be added just not validating to an object.

One example is contained in the example DAGs: https://github.com/apache/airflow/blob/main/airflow/example_dags/example_params_ui_tutorial.py#L136 - just using numbers and not dict's.

**Comment by raphaelauv** [comment]
thanks for your help , but I don't want to trigger the dag with an array of string or integer, but an array of dict/map

`[{"toto": 5,"tata":"hello"}]`

I tried 
```python
"x": Param(None, type="array",items={"type": "object"}),
```

but the front fail with

```
An invalid form control with name='element_x' is not focusable.
<textarea class="form-control" name="element_x" id="element_x" valuetype="advancedarray" rows="6" required="" style="display: none;"></textarea>
```

**Comment by raphaelauv** [comment]
so with `type=["none", "array"]` dag parsing is failing

```log
Broken DAG: [/opt/airflow/dags/dags/aaaa.py] Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/jsonschema/validators.py", line 1328, in validate
    cls.check_schema(schema)
  File "/home/airflow/.local/lib/python3.12/site-packages/jsonschema/validators.py", line 317, in check_schema
    raise exceptions.SchemaError.create_from(error)
jsonschema.exceptions.SchemaError: ['none', 'array'] is not valid under any of the given schemas

```
----

but using a not none default value is working

```python
params={
            "x": Param([{}], type="array", items={"type": "object"}),
        }
```

it let me trigger the dag with the argument `[{"toto": 5,"tata":"hello"}]`

**Comment by jscheffl** [comment]
> so with `type=["none", "array"]` dag parsing is failing

aaah, sorry RTFM.... https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/params.html --> `type=["null", "array"]` is the right typing in JSON schema...

**Comment by raphaelauv** [comment]
yeah it work

```python
params={
    "x": Param(None, type=["null", "array"], items={"type": "object"}),
}
```

so conclusion it's not obvious, if we decide to not let accept array in the type `object`
than I will add a little example in the doc

**Comment by jscheffl** [comment]
Yeah - a small hint/clarificatio nin the docs would be good - there might be others running into the same pitfall.

Also if the default is None as you initially had... might be a small bug. For DAGs that are not scheduled "non valid defaults" are possible for all other fields. So is a small bug in the form generation.

**Comment by JuliaBars** [comment]
Dear all, i have almost the same issue i am passing [{"toto": 5}] from UI and DAG fails when does data = json.loads() for params

Ive checked that it convert [{"toto": 5}] to "[{"toto": 5}]" and later cant parse it from {"my_param": 1, "my_list_param": "[{"toto": 5}]"} exactly because this double quotes which airflow added by itself

If you will locally try  json.loads('{"my_param": 1, "my_list_param": "[{"toto": 5}]"}') it will fails 
and once you remove double quotes around list it will work json.loads('{"my_param": 1, "my_list_param": [{"toto": 5}]}')

So dont know how to prevent this behaviur or to fix on my side, using exactly what @raphaelauv  "x": Param("", type=["array"], items={"type": "object"}),
