### ISSUE TITLE
Updating to latest release fails with db migration

### ISSUE THREAD

**Issue by prutheus** [apache/airflow#43806]
### Apache Airflow version

main (development)

### What happened?

Updating to latest `ghcr.io/apache/airflow/main/prod/python3.11:latest` version, a db migration is required which fails:

```
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedObject) constraint "dsdar_dag_id_fkey" of relation "dag_schedule_asset_alias_reference" does not exist

[SQL: ALTER TABLE dag_schedule_asset_alias_reference DROP CONSTRAINT dsdar_dag_id_fkey]
```

### What you think should happen instead?

Expected behaviour is a successful database migration.

### How to reproduce

Update to latest docker image.

### Operating System

Debian GNU/Linux 12 (bookworm)

### Deployment

Docker-Compose

### Deployment details

ghcr.io/apache/airflow/main/prod/python3.11:latest

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by rawwar** [comment]
Can you please give info on your earlier airflow version ?

**Comment by prutheus** [comment]
> Can you please give info on your earlier airflow version ?

@rawwar the earlier version I was using was based on commit #4323b1dd7d3a6603b7cc15056f06f5bf2de0569d

**Comment by rawwar** [comment]
I tried to replicate this issue. When I ran `docker compose up airflow-init`, it gave the following error:

```
airflow-init-1  | DB: postgresql+psycopg2://airflow:***@postgres/airflow
airflow-init-1  | Performing upgrade to the metadata database postgresql+psycopg2://airflow:***@postgres/airflow
airflow-init-1  | [2024-11-11T11:44:17.511+0000] {migration.py:207} INFO - Context impl PostgresqlImpl.
airflow-init-1  | [2024-11-11T11:44:17.513+0000] {migration.py:210} INFO - Will assume transactional DDL.
airflow-init-1  | [2024-11-11T11:44:17.516+0000] {migration.py:207} INFO - Context impl PostgresqlImpl.
airflow-init-1  | [2024-11-11T11:44:17.517+0000] {migration.py:210} INFO - Will assume transactional DDL.
airflow-init-1  | [2024-11-11T11:44:17.517+0000] {db.py:1174} INFO - Migrating the Airflow database
airflow-init-1  | [2024-11-11T11:44:17.525+0000] {migration.py:207} INFO - Context impl PostgresqlImpl.
airflow-init-1  | [2024-11-11T11:44:17.525+0000] {migration.py:210} INFO - Will assume transactional DDL.
airflow-init-1  | [2024-11-11T11:44:17.544+0000] {migration.py:618} INFO - Running upgrade 1cdc775ca98f -> 522625f6d606, Add tables for backfill.
airflow-init-1  | [2024-11-11T11:44:17.558+0000] {migration.py:618} INFO - Running upgrade 522625f6d606 -> 16cbcb1c8c36, Remove redundant index.
airflow-init-1  | [2024-11-11T11:44:17.560+0000] {migration.py:618} INFO - Running upgrade 16cbcb1c8c36 -> 44eabb1904b4, Update dag_run_note.user_id and task_instance_note.user_id columns to String.
airflow-init-1  | [2024-11-11T11:44:17.585+0000] {migration.py:618} INFO - Running upgrade 44eabb1904b4 -> 0d9e73a75ee4, Add name and group fields to DatasetModel.
airflow-init-1  | [2024-11-11T11:44:17.611+0000] {migration.py:618} INFO - Running upgrade 0d9e73a75ee4 -> c3389cd7793f, Add backfill to dag run model.
airflow-init-1  | [2024-11-11T11:44:17.615+0000] {migration.py:618} INFO - Running upgrade c3389cd7793f -> 5a5d66100783, Add AssetActive to track orphaning instead of a flag.
airflow-init-1  | [2024-11-11T11:44:17.625+0000] {migration.py:618} INFO - Running upgrade 5a5d66100783 -> fb2d4922cd79, Tweak AssetAliasModel to match AssetModel after AIP-76.
airflow-init-1  | Traceback (most recent call last):
airflow-init-1  |   File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
airflow-init-1  |     self.dialect.do_execute(
airflow-init-1  |   File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
airflow-init-1  |     cursor.execute(statement, parameters)
airflow-init-1  | psycopg2.errors.NotNullViolation: column "group" of relation "dataset_alias" contains null values
airflow-init-1  | 
airflow-init-1  | 
airflow-init-1  | The above exception was the direct cause of the following exception:
airflow-init-1  | 
airflow-init-1  | Traceback (most recent call last):
airflow-init-1  |   File "/home/airflow/.local/bin/airflow", line 8, in <module>
airflow-init-1  |     sys.exit(main())
airflow-init-1  |              ^^^^^^
airflow-init-1  |   File "/home/airflow/.local/lib/python3.11/site-packages/airflow/__main__.py", line 62, in main
airflow-init-1  |     args.func(args)
airflow-init-1  |   File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
airflow-init-1  |     return func(*args, **kwargs)
airflow-init-1  |            ^^^^^^^^^^^^^^^^^^^^^
airflow-init-1  |   File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/cli.py", line 112, in wrapper
airflow-init-1  |     return f(*args, **kwargs)
airflow-init-1  |            ^^^^^^^^^^^^^^^^^^
airflow-init-1  |   File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/providers_configuration_loader.py", line 55, in wrapped_function
airflow-init-1  |     return func(*args, **kwargs)
airflow-init-1  |            ^^^^^^^^^^^^^^^^^^^^^
airflow-init-1  |   File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/db_command.py", line 227, in migratedb
airflow-init-1  |     run_db_migrate_command(args, db.upgradedb, _REVISION_HEADS_MAP, reserialize_dags=True)
airflow-init-1  |   File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/db_command.py", line 148, in run_db_migrate_command
airflow-init-1  |     command(
airflow-init-1  |   File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
airflow-init-1  |     return func(*args, session=session, **kwargs)
airflow-init-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
airflow-init-1  |   File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/db.py", line 1181, in upgradedb
airflow-init-1  |     command.upgrade(config, revision=to_revision or "heads")
airflow-init-1  |   File "/home/airflow/.local/lib/python3.11/site-packages/alembic/command.py", line 406, in upgrade
airflow-init-1  |     script.run_env()
airflow-init-1  |   File "/home/airflow/.local/lib/python3.11/site-packages/alembic/script/base.py", line 586, in run_env
airflow-init-1  |     util.load_python_file(self.dir, "env.py")
airflow-init-1  |   File "/home/airflow/.local/lib/python3.11/site-packages/alembic/util/pyfiles.py", line 95, in load_python_file
airflow-init-1  |     module = load_module_py(module_id, path)
airflow-init-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
airflow-init-1  |   File "/home/airflow/.local/lib/python3.11/site-packages/alembic/util/pyfiles.py", line 113, in load_module_py
airflow-init-1  |     spec.loader.exec_module(module)  # type: ignore
airflow-init-1  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
airflow-init-1  |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
airflow-init-1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
airflow-init-1  |   File "/home/airflow/.local/lib/python3.11/site-packages/airflow/migrations/env.py", line 139, in <module>
airflow-init-1  |     run_migrations_online()
airflow-init-1  |   File "/home/airflow/.local/lib/python3.11/site-packages/airflow/migrations/env.py", line 133, in run_migrations_online
airflow-init-1  |     context.run_migrations()
airflow-init-1  |   File "<string>", line 8, in run_migrations
airflow-init-1  |   File "/home/airflow/.local/lib/python3.11/site-packages/alembic/runtime/environment.py", line 946, in run_migrations
airflow-init-1  |     self.get_context().run_migrations(**kw)
airflow-init-1  |   File "/home/airflow/.local/lib/python3.11/site-packages/alembic/runtime/migration.py", line 623, in run_migrations
airflow-init-1  |     step.migration_fn(**kw)
airflow-init-1  |   File "/home/airflow/.local/lib/python3.11/site-packages/airflow/migrations/versions/0039_3_0_0_tweak_assetaliasmodel_to_match_asset.py", line 60, in upgrade
airflow-init-1  |     with op.batch_alter_table("dataset_alias", schema=None) as batch_op:
airflow-init-1  |   File "/usr/local/lib/python3.11/contextlib.py", line 144, in __exit__
airflow-init-1  |     next(self.gen)
airflow-init-1  |   File "/home/airflow/.local/lib/python3.11/site-packages/alembic/operations/base.py", line 398, in batch_alter_table
airflow-init-1  |     impl.flush()
airflow-init-1  |   File "/home/airflow/.local/lib/python3.11/site-packages/alembic/operations/batch.py", line 116, in flush
airflow-init-1  |     fn(*arg, **kw)
airflow-init-1  |   File "/home/airflow/.local/lib/python3.11/site-packages/alembic/ddl/impl.py", line 374, in add_column
airflow-init-1  |     self._exec(base.AddColumn(table_name, column, schema=schema))
airflow-init-1  |   File "/home/airflow/.local/lib/python3.11/site-packages/alembic/ddl/impl.py", line 247, in _exec
airflow-init-1  |     return conn.execute(construct, params)
airflow-init-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
airflow-init-1  |   File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/future/engine.py", line 286, in execute
airflow-init-1  |     return self._execute_20(
airflow-init-1  |            ^^^^^^^^^^^^^^^^^
airflow-init-1  |   File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1710, in _execute_20
airflow-init-1  |     return meth(self, args_10style, kwargs_10style, execution_options)
airflow-init-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
airflow-init-1  |   File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/sql/ddl.py", line 80, in _execute_on_connection
airflow-init-1  |     return connection._execute_ddl(
airflow-init-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^
airflow-init-1  |   File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1477, in _execute_ddl
airflow-init-1  |     ret = self._execute_context(
airflow-init-1  |           ^^^^^^^^^^^^^^^^^^^^^^
airflow-init-1  |   File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
airflow-init-1  |     self._handle_dbapi_exception(
airflow-init-1  |   File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
airflow-init-1  |     util.raise_(
airflow-init-1  |   File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
airflow-init-1  |     raise exception
airflow-init-1  |   File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
airflow-init-1  |     self.dialect.do_execute(
airflow-init-1  |   File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
airflow-init-1  |     cursor.execute(statement, parameters)
airflow-init-1  | sqlalchemy.exc.IntegrityError: (psycopg2.errors.NotNullViolation) column "group" of relation "dataset_alias" contains null values
airflow-init-1  | 
airflow-init-1  | [SQL: ALTER TABLE dataset_alias ADD COLUMN "group" VARCHAR(1500) NOT NULL]
airflow-init-1  | (Background on this error at: https://sqlalche.me/e/14/gkpj)
airflow-init-1  | ERROR: You need to migrate the database. Please run `airflow db migrate`. Make sure the command is run using Airflow version 3.0.0.dev0.
airflow-init-1  | 3.0.0.dev0
airflow-init-1 exited with code 0
```

**Comment by rawwar** [comment]
@prutheus , can we go ahead and close this issue? As migrations between main can be broken and these aren't fixed as stability is maintained between released versions.
