### ISSUE TITLE
BUG `./scripts/tools/initialize_virtualenv.py`

### ISSUE THREAD

**Issue by SuccessMoses** [apache/airflow#44078]
### Apache Airflow version

main (development)

### What happened?

I have breeze installed then I ran this script 
```
python3.9 ./scripts/tools/initialise_virtualenv.py
``` 
to create a virtual env with `airflow` present in `/bin`. I activated the virtual env 
```
airflow version
``` 
in terminal and got this error message:

```
(apache-airflow) success@success-HP-Laptop-14-cf3xxx:~/Desktop/airflow$ airflow version
Unable to load the config, contains a configuration error.
Traceback (most recent call last):
  File "/usr/lib/python3.9/logging/config.py", line 389, in resolve
    found = getattr(found, frag)
AttributeError: module 'airflow.utils.log' has no attribute 'file_processor_handler'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/logging/config.py", line 391, in resolve
    self.importer(used)
  File "/home/success/Desktop/airflow/airflow/utils/log/file_processor_handler.py", line 27, in <module>
    from airflow.utils.helpers import parse_template_string
  File "/home/success/Desktop/airflow/airflow/utils/helpers.py", line 32, in <module>
    from airflow.utils.types import NOTSET
  File "/home/success/Desktop/airflow/airflow/utils/types.py", line 22, in <module>
    import airflow.sdk.types
ModuleNotFoundError: No module named 'airflow.sdk'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.9/logging/config.py", line 564, in configure
    handler = self.configure_handler(handlers[name])
  File "/usr/lib/python3.9/logging/config.py", line 722, in configure_handler
    klass = self.resolve(cname)
  File "/usr/lib/python3.9/logging/config.py", line 398, in resolve
    raise v
  File "/usr/lib/python3.9/logging/config.py", line 391, in resolve
    self.importer(used)
  File "/home/success/Desktop/airflow/airflow/utils/log/file_processor_handler.py", line 27, in <module>
    from airflow.utils.helpers import parse_template_string
  File "/home/success/Desktop/airflow/airflow/utils/helpers.py", line 32, in <module>
    from airflow.utils.types import NOTSET
  File "/home/success/Desktop/airflow/airflow/utils/types.py", line 22, in <module>
    import airflow.sdk.types
ValueError: Cannot resolve 'airflow.utils.log.file_processor_handler.FileProcessorHandler': No module named 'airflow.sdk'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/success/Desktop/airflow/.venv/bin/airflow", line 5, in <module>
    from airflow.__main__ import main
  File "/home/success/Desktop/airflow/airflow/__init__.py", line 78, in <module>
    settings.initialize()
  File "/home/success/Desktop/airflow/airflow/settings.py", line 750, in initialize
    LOGGING_CLASS_PATH = configure_logging()
  File "/home/success/Desktop/airflow/airflow/logging_config.py", line 74, in configure_logging
    raise e
  File "/home/success/Desktop/airflow/airflow/logging_config.py", line 69, in configure_logging
    dictConfig(logging_config)
  File "/usr/lib/python3.9/logging/config.py", line 809, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib/python3.9/logging/config.py", line 571, in configure
    raise ValueError('Unable to configure handler '
ValueError: Unable to configure handler 'processor'
```

### What you think should happen instead?

3.0.dev0

### How to reproduce

Clone the source code from guthub
```
git clone https://github.com/apache/airflow.git
cd airflow
```

Install breeze
```
uv tool install -e ./dev/breeze
```
Create virtual env
```
python3.9 -m venv .venv
python3.9 ./scripts/tools/initialise_virtualenv.py
```
This should print out the version
```
airflow version
```

### Operating System

ubuntu

### Deployment

Virtualenv installation

### Anything else?

No

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Yes. `pip install -e .` effectively run inside should be replaced with `uv venv` followed with appropriate `uv sync`. This is a left-over after `uv` becoming recommended tool and adding `provider` and `task_sdk`. 

Should be a nice first-time issue.

**Comment by SuccessMoses** [comment]
I will attempt a fix,

**Comment by SuccessMoses** [comment]
I will attempt a fix

**Comment by SuccessMoses** [comment]
I will attempt a fix

**Comment by SuccessMoses** [comment]
I will attempt a fix,
