### ISSUE TITLE
Scheduler stuck when "too old resource version" error is thrown

### ISSUE THREAD

**Issue by anon-airflow** [apache/airflow#44127]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### If "Other Airflow 2 version" selected, which one?

2.8.2

### What happened?

I get the following error a lot on my airflow scheduler pods:

```
{kubernetes_executor_utils.py:121} ERROR - Unknown error in KubernetesJobWatcher. Failing
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/cncf/kubernetes/executors/kubernetes_executor_utils.py", line 112, in run
    self.resource_version = self._run(
                            ^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/cncf/kubernetes/executors/kubernetes_executor_utils.py", line 168, in _run
    for event in self._pod_events(kube_client=kube_client, query_kwargs=kwargs):
  File "/home/airflow/.local/lib/python3.8/site-packages/kubernetes/watch/watch.py", line 182, in stream
    raise client.rest.ApiException(
kubernetes.client.exceptions.ApiException: (410)
Reason: Expired: too old resource version: 725263658 (725300129)

Process KubernetesJobWatcher-8:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/cncf/kubernetes/executors/kubernetes_executor_utils.py", line 112, in run
    self.resource_version = self._run(
                            ^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/cncf/kubernetes/executors/kubernetes_executor_utils.py", line 168, in _run
    for event in self._pod_events(kube_client=kube_client, query_kwargs=kwargs):
  File "/home/airflow/.local/lib/python3.8/site-packages/kubernetes/watch/watch.py", line 182, in stream
    raise client.rest.ApiException(
kubernetes.client.exceptions.ApiException: (410)
Reason: Expired: too old resource version: 725263658 (725300129)
```

When this error appears relatively many times on my airflow scheduler pods, All my DAG runs become very slow- This is expressed in the fact that the amount of my "scheduled" slots is very high and in contrast the amount of my "'queued" and "running" slots is very low (about 15 slots together) even though I have defined 128 slots.

Also my resource utilization in my namespace is very low (20% cpu and memory usage) so the problem is not resources either.

NOTE: I use the package "apache-airflow-providers-cncf-kubernetes" on version 8.0.0 as required for Airflow 2.8.2 according to the constraints.

### What you think should happen instead?

I think Airflow should know how to handle this error so that even when the error is thrown, the scheduler should continue to work  properly and not "freeze".

### How to reproduce

I think it would happen on any deployment in this version of Airflow with running DAGs. 

### Operating System

rhel 8

### Versions of Apache Airflow Providers

apache-airflow-providers-cncf-kubernetes==8.0.0

### Deployment

Other

### Deployment details

We are in a private cloud with constraints, we took the most of the chart but handled the constraints ourselves.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
I think there were some recent changes in Kubernetes Provider to address similar issues: https://airflow.apache.org/docs/apache-airflow-providers-cncf-kubernetes/stable/changelog.html -> look it up and best - upgrade Airflow to the latest version (or only K8S provider)

https://airflow.apache.org/docs/apache-airflow/stable/installation/installing-from-pypi.html#installation-and-upgrade-scenarios

**Comment by potiuk** [comment]
Please come-back to us with results after upgrade .

BTW.

> NOTE: I use the package "apache-airflow-providers-cncf-kubernetes" on version 8.0.0 as required for Airflow 2.8.2 according to the constraints.

No. You understand it backwards. Constraints are NOT requirements - you are free to upgrade stuff after initial installation. Constraints are there EXCLUSIVELY to give you reproducible installation and non-conflicting requirements - 
see detailed description why we need constraints and how you are supposed to use them https://airflow.apache.org/docs/apache-airflow/stable/installation/installing-from-pypi.html#constraints-files

Also you can see my talk from Airlfow Summit 2023 https://www.youtube.com/watch?v=zPjIQjjjyHI describing how to manage dependencies for Airlfow.

**Comment by anon-airflow** [comment]
I upgrade my airflow environment to use in the latest version of "apache-airflow-provider-cncf-kubernetes" package (10.0.1) and the problem didn't solved - the error is still thrown.

**Comment by potiuk** [comment]
Possibly then somoene who follows k8s part can help.
