### ISSUE TITLE
/airflow/settings.py raises TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by SuccessMoses** [apache/airflow#44933]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### If "Other Airflow 2 version" selected, which one?

2.6.3

### What happened?

In pendulum 2 `pendulum.tz.timezone` refers to the function, in pendulum 3 refers to the module

```
Traceback (most recent call last):
  File "/home/success/Desktop/airflow/.venv/2.6/bin/airflow", line 5, in <module>
    from airflow.__main__ import main
  File "/home/success/Desktop/airflow/airflow/__main__.py", line 35, in <module>
    from airflow import configuration
  File "/home/success/Desktop/airflow/airflow/configuration.py", line 1814, in <module>
    secrets_backend_list = initialize_secrets_backends()
  File "/home/success/Desktop/airflow/airflow/configuration.py", line 1742, in initialize_secrets_backends
    secrets_backend_cls = import_string(class_name)
  File "/home/success/Desktop/airflow/airflow/utils/module_loading.py", line 36, in import_string
    module = import_module(module_path)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/success/Desktop/airflow/airflow/secrets/metastore.py", line 28, in <module>
    from airflow.utils.session import NEW_SESSION, provide_session
  File "/home/success/Desktop/airflow/airflow/utils/session.py", line 24, in <module>
    from airflow import settings
  File "/home/success/Desktop/airflow/airflow/settings.py", line 51, in <module>
    TIMEZONE = pendulum.tz.timezone("UTC")
TypeError: 'module' object is not callable
```

### How to reproduce

Install airflow
```
pip install -e .
```
`pip` requires pendulum>=2.0.0

### Operating System

ubuntu

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by tirkarthi** [comment]
Related https://github.com/apache/airflow/issues/38714 . As noted in the linked issue please use proper constraints to install compatible versions of the dependencies .
