### ISSUE TITLE
Broken Tree View

### ISSUE THREAD

**Issue by kerzhner** [apache/airflow#453]
We are using version 1.5.1 of Airflow.

I am seeing the following issue with Tree View. Steps:
1. Go to http://my-airflow-instance.com/admin/
2. Click on Tree View for any DAG.
3. In the Tree View, click on `Go` button in the Tree form.
4. 500 page with this stack trace:

```
2015-09-22_23:19:02.61708 2015-09-22 23:19:02,616 - tornado.access - ERROR - 500 GET /admin/airflow/tree?base_date=2015-09-23+17%3A00%3A00&num_runs=25&root=None&dag_id=summarize_hourly (172.17.42.1) 15.79ms
2015-09-22_23:24:43.09539 2015-09-22 23:24:43,095 - airflow.www.app - ERROR - Exception on /admin/airflow/tree [GET]
2015-09-22_23:24:43.09552 Traceback (most recent call last):
2015-09-22_23:24:43.09557   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
2015-09-22_23:24:43.09561     response = self.full_dispatch_request()
2015-09-22_23:24:43.09565   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
2015-09-22_23:24:43.09568     rv = self.handle_user_exception(e)
2015-09-22_23:24:43.09570   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
2015-09-22_23:24:43.09570     reraise(exc_type, exc_value, tb)
2015-09-22_23:24:43.09570   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
2015-09-22_23:24:43.09571     rv = self.dispatch_request()
2015-09-22_23:24:43.09571   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
2015-09-22_23:24:43.09572     return self.view_functions[rule.endpoint](**req.view_args)
2015-09-22_23:24:43.09575   File "/usr/local/lib/python2.7/dist-packages/flask_admin/base.py", line 68, in inner
2015-09-22_23:24:43.09576     return self._run_view(f, *args, **kwargs)
2015-09-22_23:24:43.09578   File "/usr/local/lib/python2.7/dist-packages/flask_admin/base.py", line 359, in _run_view
2015-09-22_23:24:43.09579     return fn(self, *args, **kwargs)
2015-09-22_23:24:43.09581   File "/usr/local/lib/python2.7/dist-packages/airflow/www/utils.py", line 96, in view_func
2015-09-22_23:24:43.09583     return f(*args, **kwargs)
2015-09-22_23:24:43.09584   File "/usr/local/lib/python2.7/dist-packages/airflow/www/app.py", line 1070, in tree
2015-09-22_23:24:43.09585     node_limit = 5000 / len(dag.roots)
2015-09-22_23:24:43.09587 ZeroDivisionError: division by zero
```

**Comment by kerzhner** [comment]
Woot thanks for the quick fix @jlowin!
