### ISSUE TITLE
airflow worker does not work 

### ISSUE THREAD

**Issue by griffinqiu** [apache/airflow#47]
$ airflow worker
Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 10, in <module>
    args.func(args)
  File "/usr/local/lib/python2.7/site-packages/airflow/bin/cli.py", line 299, in worker
    worker.run(**options)
  File "/usr/local/lib/python2.7/site-packages/celery/bin/worker.py", line 212, in run
    state_db=self.node_format(state_db, hostname), **kwargs
  File "/usr/local/lib/python2.7/site-packages/celery/worker/**init**.py", line 100, in **init**
    self.setup_instance(**self.prepare_args(**kwargs))
  File "/usr/local/lib/python2.7/site-packages/celery/worker/**init**.py", line 124, in setup_instance
    self._conninfo = self.app.connection()
  File "/usr/local/lib/python2.7/site-packages/celery/app/base.py", line 385, in connection
    'BROKER_CONNECTION_TIMEOUT', connect_timeout
  File "/usr/local/lib/python2.7/site-packages/kombu/connection.py", line 165, in __init__
    if not get_transport_cls(transport).can_parse_url:
  File "/usr/local/lib/python2.7/site-packages/kombu/transport/**init**.py", line 109, in get_transport_cls
    _transport_cache[transport] = resolve_transport(transport)
  File "/usr/local/lib/python2.7/site-packages/kombu/transport/__init__.py", line 89, in resolve_transport
    raise KeyError('No such transport: {0}'.format(transport))
KeyError: 'No such transport: '

**Comment by mistercrunch** [comment]
Can you connect directly with celery to that broker?
`celery inspect -b {BROKER_URI}`

Where BROKER_URI is `celery->broker_url` from your `airflow.cfg`

**Comment by griffinqiu** [comment]
It is bcs my configure issue. ;(
