### ISSUE TITLE
Syntax error with mariadb

### ISSUE THREAD

**Issue by kapil-malik** [apache/airflow#473]
Hi,

I am trying to install latest airflow by doing `git clone` + `sudo pip install -e '<airflow repo path>'`
I have a mariadb installation locally and sql_alchemy_conn as
`mysql+pymysql://root:password@host:port/airflow`

I created database by name airflow, set `load_examples = False` and did `airflow initdb` it works fine and tables are created with no dags.

Then I add tutorial.py in dags folder and run airflow scheduler, it gives me error which I can trace up to line -

```
...
  File "/home/centos/git/airflow/airflow/models.py", line 272, in deactivate_inactive_dags
    DagModel).filter(~DagModel.dag_id.in_(active_dag_ids)).all():
...
```

The sql alchemy exception is as follows -

```
sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (ProgrammingError) (1064, u"You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''', 'airflow')' at line 1") u'INSERT INTO dag (dag_id, is_paused, is_subdag, is_active, last_scheduler_run, last_pickled, last_expired, scheduler_lock, pickle_id, fileloc, owners) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)' ('tutorial', 0, 0, 1, None, None, None, None, None, '/home/centos/airflow/dags/tutorial.py', 'airflow')
```

Interestingly, if I use only sqlite, things work perfectly fine.

Any suggestions ?

Server version: 5.5.44-MariaDB MariaDB Server
CentOS Linux release 7.0.1406 (Core)

**Comment by kapil-malik** [comment]
Full logs for reference -

```
2015-09-29 18:21:52,706 - root - INFO - Importing /home/centos/airflow/dags/tutorial.py
Traceback (most recent call last):
  File "/usr/bin/airflow", line 8, in <module>
    execfile(__file__)
  File "/home/centos/git/airflow/airflow/bin/airflow", line 10, in <module>
    args.func(args)
  File "/home/centos/git/airflow/airflow/bin/cli.py", line 278, in scheduler
    job.run()
  File "/home/centos/git/airflow/airflow/jobs.py", line 159, in run
    self._execute()
  File "/home/centos/git/airflow/airflow/jobs.py", line 490, in _execute
    dagbag = models.DagBag(self.subdir, sync_to_db=True)
  File "/home/centos/git/airflow/airflow/models.py", line 121, in __init__
    self.deactivate_inactive_dags()
  File "/home/centos/git/airflow/airflow/models.py", line 272, in deactivate_inactive_dags
    DagModel).filter(~DagModel.dag_id.in_(active_dag_ids)).all():
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 2307, in all
    return list(self)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 2425, in __iter__
    return self._execute_and_instances(context)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 2438, in _execute_and_instances
    close_with_result=True)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 2429, in _connection_from_session
    **kw)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 881, in connection
    execution_options=execution_options)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 886, in _connection_for_bind
    engine, execution_options)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 306, in _connection_for_bind
    self._assert_active()
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 214, in _assert_active
    % self._rollback_exception
sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (ProgrammingError) (1064, u"You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''', 'airflow')' at line 1") u'INSERT INTO dag (dag_id, is_paused, is_subdag, is_active, last_scheduler_run, last_pickled, last_expired, scheduler_lock, pickle_id, fileloc, owners) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)' ('tutorial', 0, 0, 1, None, None, None, None, None, '/home/centos/airflow/dags/tutorial.py', 'airflow')
```

**Comment by kapil-malik** [comment]
I'd reproduced this error on 3 fresh installations atleast.
Not observing it any more, 
sql_alchemy_conn is `mysql://root:aether@10.0.0.97:3306/airflow`
I installed mariadb-devel explicitly this time, probably that helped.
