### ISSUE TITLE
No schema supplied error when using an environment variable connection

### ISSUE THREAD

**Issue by dbarbar** [apache/airflow#490]
Hi, I'm trying to provide a connection string through an environment variable and I'm getting an error about not having a schema. Here's a simplified version of the PythonOperator task I'm working on.

```
def do_stuff(*args, **kwargs):
    import os
    from airflow.hooks.base_hook import CONN_ENV_PREFIX
    from airflow.hooks.http_hook import HttpHook

    os.environ[CONN_ENV_PREFIX + 'TEST'] = 'https://www.google.com/'
    h = HttpHook(method='GET', http_conn_id='test')
    h.run('/search')
```

When I run airflow test with this I get the following error.

```
2015-10-07 14:49:44,553 - root - INFO - Executing <Task(PythonOperator): stuff> on 2015-10-01 00:00:00
2015-10-07 14:49:44,554 - root - INFO - Using connection to: www.google.com
2015-10-07 14:49:44,555 - root - ERROR - Invalid URL 'www.google.com/search': No schema supplied. Perhaps you meant http://www.google.com/search?
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/airflow/models.py", line 928, in run
    result = task_copy.execute(context=context)
  File "/usr/lib/python2.7/dist-packages/airflow/operators/python_operator.py", line 51, in execute
    return_value = self.python_callable(*self.op_args, **self.op_kwargs)
  File "/datadive/dags/junk.py", line 13, in do_stuff
    h.run('/search')
  File "/usr/lib/python2.7/dist-packages/airflow/hooks/http_hook.py", line 58, in run
    prepped_request = session.prepare_request(req)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 382, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 304, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 362, in prepare_url
    to_native_string(url, 'utf8')))
MissingSchema: Invalid URL 'www.google.com/search': No schema supplied. Perhaps you meant http://www.google.com/search?
2015-10-07 14:49:44,559 - root - ERROR - Invalid URL 'www.google.com/search': No schema supplied. Perhaps you meant http://www.google.com/search?
Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 10, in <module>
    args.func(args)
  File "/usr/lib/python2.7/dist-packages/airflow/bin/cli.py", line 204, in test
2015-10-07 15:02:25,901 - root - ERROR - Invalid URL 'www.google.com/search': No schema supplied. Perhaps you meant http://www.google.com/search?
Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 10, in <module>
    args.func(args)
  File "/usr/lib/python2.7/dist-packages/airflow/bin/cli.py", line 204, in test
    ti.run(force=True, ignore_dependencies=True, test_mode=True)
  File "/usr/lib/python2.7/dist-packages/airflow/models.py", line 928, in run
    result = task_copy.execute(context=context)
  File "/usr/lib/python2.7/dist-packages/airflow/operators/python_operator.py", line 51, in execute
    return_value = self.python_callable(*self.op_args, **self.op_kwargs)
  File "/datadive/dags/junk.py", line 13, in do_stuff
    h.run('/search')
  File "/usr/lib/python2.7/dist-packages/airflow/hooks/http_hook.py", line 58, in run
    prepped_request = session.prepare_request(req)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 382, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 304, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 362, in prepare_url
    to_native_string(url, 'utf8')))
requests.exceptions.MissingSchema: Invalid URL 'www.google.com/search': No schema supplied. Perhaps you meant http://www.google.com/search?
```

I think this has something to do with the parse_from_url method on the Connection, around line 344 in models.py.

```
        self.schema = temp_uri.path[1:]
```

But I'm not sure what should go in its place in order to get the schema showing up.

I'm using the version of airflow from [this docker container](https://hub.docker.com/r/puckel/docker-airflow/), which I think is 1.5.1

**Comment by turtlemonvh** [comment]
Looks like a bug to me.

The `ParseResult` object returned by `urlparse` stores the schema (https) portion of the uri in the `scheme` property, but this field isn't grabbed [in `models.Connection`](https://github.com/airbnb/airflow/blob/1.5.1/airflow/models.py#L338).

The [`HttpHook` class](https://github.com/airbnb/airflow/blob/1.5.1/airflow/hooks/http_hook.py#L26) builds the url using only the host and the port, including the username and password for basic auth if they were passed.

To fix this, `models.Connection` needs to store the scheme and make that available to `HttpHook` for building the url.

**Comment by bolkedebruin** [comment]
if this is still an issue please create a Jira issue for it
