### ISSUE TITLE
xcom sqlalchemy deadlock

### ISSUE THREAD

**Issue by portah** [apache/airflow#511]
One of my job has failed because of deadlock, please see log attached.
Is there some limits or workarounds to avoid this in the future?

```
[2015-10-12 23:03:05,636] {models.py:973} ERROR - OperationalError: (OperationalError) (1213, 'Deadlock found when trying to get lock; try restarting transaction') 'INSERT INTO xcom (`key`, value, timestamp, execution_date, task_id, dag_id) VALUES (%
s, %s, now(), %s, %s, %s)' ('return_value', '...', datetime.datetime(2015, 10, 11, 0, 0), 'read', u'ED98A1DA-AAD1-0149-23BC-EEA1C0AA20EB_bam2bigwig')  
Traceback (most recent call last):                                                                                                                                                                      
  File "/usr/local/lib/python2.7/dist-packages/airflow-1.5.1-py2.7.egg/airflow/models.py", line 937, in run                                                                                             
    self.xcom_push(key=XCOM_RETURN_KEY, value=result)                                                                                                                                                   
  File "/usr/local/lib/python2.7/dist-packages/airflow-1.5.1-py2.7.egg/airflow/models.py", line 1129, in xcom_push                                                                                      
    execution_date=execution_date or self.execution_date)                                                                                                                                               
  File "/usr/local/lib/python2.7/dist-packages/airflow-1.5.1-py2.7.egg/airflow/utils.py", line 314, in wrapper                                                                                          
    result = func(*args, **kwargs)                                                                                                                                                                      
  File "/usr/local/lib/python2.7/dist-packages/airflow-1.5.1-py2.7.egg/airflow/models.py", line 2382, in set                                                                                            
    session.commit()                                                                                                                                                                                    
  File "/usr/local/lib/python2.7/dist-packages/SQLAlchemy-0.9.10-py2.7-linux-x86_64.egg/sqlalchemy/orm/session.py", line 789, in commit                                                                 
    self.transaction.commit()                                   
```

**Comment by mistercrunch** [comment]
I've never seen a deadlock on Airflow. Which database are you using? How many tasks do you have running? What kind of interval? How big are your payloads?

**Comment by portah** [comment]
I'm using MariaDB 10.0.20 on ubuntu 15.04. I've had one script that made 10 DAGs(different IDes but the same structure, with 4 tasks) and it was the first task that fails than everything was smooth.

**Comment by artwr** [comment]
MariaDB offers pooled connections with threads, which is something that MySQL-python does not. I wonder what could have happened...
