### ISSUE TITLE
How to gracefully stop airflow scheduler? Database is locked due to key interrupt airflow scheduler.

### ISSUE THREAD

**Issue by Yongyiw** [apache/airflow#518]
For now, I am pressing `ctrl+c` crazily to interrupt the airflow scheduler process. But then I met with some database locking problem when I relaunched scheduler,  the error message is like:

```
Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 10, in <module>
    args.func(args)
  File "/usr/local/lib/python2.7/dist-packages/airflow/bin/cli.py", line 277, in scheduler
    job.run()
  File "/usr/local/lib/python2.7/dist-packages/airflow/jobs.py", line 153, in run
    session.commit()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 790, in commit
    self.transaction.commit()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 396, in commit
    t[1].commit()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1574, in commit
    self._do_commit()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1605, in _do_commit
    self.connection._commit_impl()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 690, in _commit_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 688, in _commit_impl
    self.engine.dialect.do_commit(self.connection)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 423, in do_commit
    dbapi_connection.commit()
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
```

Is it possible to make the scheduler finish all the database access before it terminates after receiving keyboard-interrupts? 

Just curious about how everyone test dags with scheduler? Is there suggested workflow for us to test dags with scheduler running?

**Comment by bolkedebruin** [comment]
Don't use sqlite for production usage. It is only there for trying airflow.
