### ISSUE TITLE
"Python 'newstr' cannot be converted to a MySQL type" with MySQL backend

### ISSUE THREAD

**Issue by Yongyiw** [apache/airflow#536]
I met with this problem when I change backend from SQLite to MySQL and run `airflow initdb`

```
DB: mysql+mysqlconnector://airflow:password@localhost/airflow
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 10, in <module>
    args.func(args)
  File "/usr/local/lib/python2.7/dist-packages/airflow/bin/cli.py", line 324, in initdb
    utils.initdb()
  File "/usr/local/lib/python2.7/dist-packages/airflow/utils.py", line 215, in initdb
    models.DagBag(sync_to_db=True)
  File "/usr/local/lib/python2.7/dist-packages/airflow/models.py", line 121, in __init__
    self.deactivate_inactive_dags()
  File "/usr/local/lib/python2.7/dist-packages/airflow/models.py", line 272, in deactivate_inactive_dags
    DagModel).filter(~DagModel.dag_id.in_(active_dag_ids)).all():
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2399, in all
    return list(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2516, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2529, in _execute_and_instances
    close_with_result=True)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2520, in _connection_from_session
    **kw)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 882, in connection
    execution_options=execution_options)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 887, in _connection_for_bind
    engine, execution_options)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 313, in _connection_for_bind
    self._assert_active()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 214, in _assert_active
    % self._rollback_exception
sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.ProgrammingError) Failed processing pyformat-parameters; Python 'newstr' cannot be converted to a MySQL type [SQL: u'INSERT INTO dag (dag_id, is_pau
sed, is_subdag, is_active, last_scheduler_run, last_pickled, last_expired, scheduler_lock, pickle_id, fileloc, owners) VALUES (%(dag_id)s, %(is_paused)s, %(is_subdag)s, %(is_active)s, %(last_scheduler_run)s, %(last_pickled)s, %(last_expired)s, %(scheduler_lock)s, %(pickle_id)s, %(fileloc)s, %(owners)s)'] [parameters: {'is_paused': 0, 'owners': 'airflow', 'pickle_id': None, 'fileloc': '/usr/local/airflow/dags/dag1.py', 'is_subdag': 0, 'is_active': 1, 'last_expired': None, 'last_scheduler_run': None, 'scheduler_lock': None, 'last_pickled': None, 'dag_id': 'dag_id'}]
```

I am guessing it is because `MySQLdb.converters` do not support `__future__.newstr`. Just curious how everyone else deal with this. 

and it is `fileloc = Column(String(2000))` field in `DagModel` causing this error. Still looking for details

**Comment by bolkedebruin** [comment]
You might want to try the most recent version from git and try with "mysqlclient" (now part of the requirements) instead of python-mysqldb/mysqlconnector.

**Comment by Yongyiw** [comment]
Thank you so much @bolkedebruin You saved my day!
