### ISSUE TITLE
Incompatible with Python 3.4 ConfigParser

### ISSUE THREAD

**Issue by lentinj** [apache/airflow#537]
So if I start afresh with Python 3.4...

```
$ virtualenv --python=python3.4 .env
$ . .env/bin/activate
$ pip install airflow
$ AIRFLOW_HOME=~/airflow airflow 
Traceback (most recent call last):
  File "/srv/devel/temp/airflow/.env/bin/airflow", line 3, in <module>
    from airflow.bin.cli import get_parser
  File "/srv/devel/temp/airflow/.env/lib/python3.4/site-packages/airflow/__init__.py", line 14, in <module>
    from airflow.models import DAG
  File "/srv/devel/temp/airflow/.env/lib/python3.4/site-packages/airflow/models.py", line 31, in <module>
    from airflow import settings, utils
  File "/srv/devel/temp/airflow/.env/lib/python3.4/site-packages/airflow/settings.py", line 19, in <module>
    AIRFLOW_HOME = os.path.expanduser(conf.get('core', 'AIRFLOW_HOME'))
  File "/srv/devel/temp/airflow/.env/lib/python3.4/site-packages/airflow/configuration.py", line 246, in get
    return ConfigParser.get(self, section, key)
  File "/usr/lib/python3.4/configparser.py", line 772, in get
    d)
  File "/usr/lib/python3.4/configparser.py", line 371, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/usr/lib/python3.4/configparser.py", line 384, in _interpolate_some
    rawval = parser.get(section, option, raw=True, fallback=rest)
TypeError: get() got an unexpected keyword argument 'raw'
```

I can bodge my way through with:

```
diff --git a/airflow/configuration.py b/airflow/configuration.py
index 99efbeb..6a6383f 100644
--- a/airflow/configuration.py
+++ b/airflow/configuration.py
@@ -291,7 +291,9 @@ class ConfigParserWithDefaults(ConfigParser):
         self.defaults = defaults
         ConfigParser.__init__(self, *args, **kwargs)

-    def get(self, section, key):
+    def get(self, section, key, raw=None, fallback=None):
+        if fallback:
+            return fallback
         section = str(section).lower()
         key = str(key).lower()
         d = self.defaults
```

...but I'm sure there's something more sensible to do. Is airflow supposed to work okay with Python3.4 at this stage?

**Comment by mistercrunch** [comment]
Python 3.4 is on the roadmap but can't be guaranteed at the moment. We're actively working on it though.

**Comment by lentinj** [comment]
@mistercrunch Fair do's, thanks. Would a pull request attempting to fix the above be accepted, or would you not be interested at this stage?

**Comment by mistercrunch** [comment]
PR are always welcomed!
