### ISSUE TITLE
Returning 65kb vs 21kb value from an operator results in EOFError

### ISSUE THREAD

**Issue by praveev** [apache/airflow#578]
When I return a slightly large array of values from the first operator to the next. I receive an EOFError. If I pass in a smaller array, then everything works as expected. 

```
[2015-10-29 15:46:27,939] {models.py:959} ERROR - 
Traceback (most recent call last):
  File "/home/y/lib/python2.7/site-packages/airflow/models.py", line 916, in run
    self.render_templates()
  File "/home/y/lib/python2.7/site-packages/airflow/models.py", line 1049, in render_templates
    result = rt(content, jinja_context)
  File "/home/y/lib/python2.7/site-packages/airflow/models.py", line 1497, in render_template
    return template.render(**context)
  File "/home/y/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/y/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 1, in top-level template code
  File "/home/y/lib/python2.7/site-packages/airflow/models.py", line 1169, in xcom_pull
    return pull_fn(task_id=task_ids)
  File "/home/y/lib/python2.7/site-packages/airflow/utils.py", line 301, in wrapper
    result = func(*args, **kwargs)
  File "/home/y/lib/python2.7/site-packages/airflow/models.py", line 2360, in get_one
    result = query.first()
  File "/home/y/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2469, in first
    ret = list(self[0:1])
  File "/home/y/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2292, in __getitem__
    return list(res)
  File "/home/y/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 86, in instances
    util.raise_from_cause(err)
  File "/home/y/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/home/y/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 74, in instances
    for row in fetch]
  File "/home/y/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py", line 1258, in process
    return loads(value)
  File "/home/y/lib/python2.7/site-packages/dill/dill.py", line 209, in loads
    return load(file)
  File "/home/y/lib/python2.7/site-packages/dill/dill.py", line 199, in load
    obj = pik.load()
  File "/home/y/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/home/y/lib/python2.7/pickle.py", line 880, in load_eof
    raise EOFError
EOFError
```

**Comment by mistercrunch** [comment]
How much data is that? Xcoms should only be used for metadata only. It gets serialized into a field in the metadata database.

**Comment by praveev** [comment]
65535 bytes. I am storing only metadata - passing an array of items to process for the next operator.
For the one that works, the data size is 21272 bytes. How large is big enough? Is 65Kb a large enough value to fail? @mistercrunch

**Comment by jlowin** [comment]
Can you post an example of the data?

**Comment by mistercrunch** [comment]
Looks like BLOB type in MySQL limits to 65KB
https://philihp.com/blog/2011/maximum-sizes-of-mysql-blob-fields/

For now you can probably just ALTER TABLE and set that value column to MEDIUMBLOB or LONGBLOB. 

MEDIUMBLOB seems like a better default for Airflow, though I'm unclear on whether SqlAlchemy will allow a cross platform way to set this.

**Comment by mistercrunch** [comment]
So the solution here is for people to ALTER their DB if they want support for larger blobs than SqlAlchemy allocates for when translating.
