### ISSUE TITLE
airflow resetdb hanging

### ISSUE THREAD

**Issue by KevYuen** [apache/airflow#601]
Your operating system name and version:
ubuntu 14.04
python 2.7.6

Any details about your local setup that might be helpful in troubleshooting.
Docker container running airflow 1.5.2 pulled from pypi. 

Detailed steps to reproduce the bug.
In v1.5.2, `airflow resetdb` fails with the following error

```
docker exec -it dockerdevenv_webserver_1 airflow resetdb
# basically airflow resetdb

This hangs at : 
DB: mysql://username:pass@mysql/airflow
This will drop existing tables if they exist. Proceed? (y/n)y
2015-11-05 20:55:13,909 INFO - Dropping tables that exist

```

When interrupted:

```
ERROR - Exception during reset or similar
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 636, in _finalize_fairy
    fairy._reset(pool)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 776, in _reset
    pool._dialect.do_rollback(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/dialects/mysql/base.py", line 2519, in do_rollback
    dbapi_connection.rollback()
OperationalError: (2006, 'MySQL server has gone away')
Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 17, in <module>
    args.func(args)
  File "/usr/local/lib/python2.7/dist-packages/airflow/bin/cli.py", line 335, in resetdb
    utils.resetdb()
  File "/usr/local/lib/python2.7/dist-packages/airflow/utils.py", line 276, in resetdb
    models.Base.metadata.drop_all(settings.engine)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/schema.py", line 3714, in drop_all
    tables=tables)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1856, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1481, in _run_visitor
    **kwargs).traverse_single(element)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/ddl.py", line 871, in visit_metadata
    table, drop_ok=True, _is_metadata_operation=True)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/ddl.py", line 918, in visit_table
    self.connection.execute(DropTable(table))
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 968, in _execute_ddl
    compiled
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 190, in execute
    r = self._query(query)
KeyboardInterrupt
```

In my airflow database:

show processlist;
![screen shot 2015-11-05 at 4 17 40 pm](https://cloud.githubusercontent.com/assets/4744103/10982048/17c4fc60-83d9-11e5-87e0-3d8b3f5c47e3.png)

This is after trying to resetdb a couple of times.

**Comment by KevYuen** [comment]
so looks like the answer is here: 

http://stackoverflow.com/questions/13882407/sqlalchemy-blocked-on-dropping-tables

Will PR a fix soon which involves: `settings.Session.close()`

**Comment by mistercrunch** [comment]
Yeah I've seen a few lingering locks here and there.  The first thing is to make sure you don't have any airflow related processes running. You can also kill blocking processes in the DB. I'm not sure if you could just go and drop the db either or if the lock would prevent that as well.

**Comment by KevYuen** [comment]
Initdb and resetdb themselves works fine after the killing the initial sets of process that hanged. 

Each Gunicorn worker thread that I add to the server seems to create another process in the database that locks the metadata table(or attempt to). I suspect Gunicorn is the cult-pit of this. 6 gunicorn thread = 6 processes to kill. 

On a side note, the lock also prevents dropping the db. I can kill the blocking processes in the DB tho.
