### ISSUE TITLE
Problem reading DAGs that are in .py files that are in `utf-8`

### ISSUE THREAD

**Issue by ziky90** [apache/airflow#721]
I am trying to search for DAGs in the .py file that is encoded as `utf-8` and which probably contains some specific characters.

And I am getting the following error:

```
Traceback (most recent call last):
  File "/Users/.virtualenvs/pipeline/bin/airflow", line 17, in <module>
    args.func(args)
  File "/Users/.virtualenvs/pipeline/lib/python2.7/site-packages/airflow/bin/cli.py", line 55, in backfill
    dagbag = DagBag(process_subdir(args.subdir))
  File "/Users/.virtualenvs/pipeline/lib/python2.7/site-packages/airflow/models.py", line 134, in __init__
    self.collect_dags(dag_folder)
  File "/Users/.virtualenvs/pipeline/lib/python2.7/site-packages/airflow/models.py", line 292, in collect_dags
    self.process_file(dag_folder, only_if_updated=only_if_updated)
  File "/Users/.virtualenvs/pipeline/lib/python2.7/site-packages/airflow/models.py", line 181, in process_file
    if not all([s in content for s in ('DAG', 'airflow')]):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 1515: ordinal not in range(128)
```

My questions are: 

Does anyone else has this problem? Should I try to do a fix with PR? Or why there is assumed that all the scripts are ascii or `utf-8` without special characters?

**Comment by r39132** [comment]
#770
