### ISSUE TITLE
Error connecting to metadata DB

### ISSUE THREAD

**Issue by 005f** [apache/airflow#731]
I'm getting an error whilst trying to connect an airflow docker container running in ECS with a postgres metadata DB:

```
Traceback (most recent call last):
File "/usr/local/bin/airflow", line 17, in <module>
args.func(args)
File "/usr/local/lib/python2.7/dist-packages/airflow/bin/cli.py", line 323, in webserver
app = cached_app(configuration)
File "/usr/local/lib/python2.7/dist-packages/airflow/www/app.py", line 119, in cached_app
app = create_app(config)
File "/usr/local/lib/python2.7/dist-packages/airflow/www/app.py", line 39, in create_app
from airflow.www import views
File "/usr/local/lib/python2.7/dist-packages/airflow/www/views.py", line 1663, in <module>
class ChartModelView(wwwutils.DataProfilingMixin, AirflowModelView):
File "/usr/local/lib/python2.7/dist-packages/airflow/www/views.py", line 1747, in ChartModelView
.group_by(models.Connection.conn_id)
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2571, in __iter__
return self._execute_and_instances(context)
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2584, in _execute_and_instances
close_with_result=True)
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2575, in _connection_from_session
**kw)
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 893, in connection
execution_options=execution_options)
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 898, in _connection_for_bind
engine, execution_options)
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 334, in _connection_for_bind
conn = bind.contextual_connect()
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 2039, in contextual_connect
self._wrap_pool_connect(self.pool.connect, None),
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 2074, in _wrap_pool_connect
return fn()
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 376, in connect
return _ConnectionFairy._checkout(self)
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 713, in _checkout
fairy = _ConnectionRecord.checkout(pool)
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 480, in checkout
rec = pool._do_get()
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 1060, in _do_get
self._dec_overflow()
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
compat.reraise(exc_type, exc_value, exc_tb)
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 1057, in _do_get
return self._create_connection()
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 323, in _create_connection
return _ConnectionRecord(self)
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 449, in __init__
self.connection = self.__connect()
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 607, in __connect
connection = self.__pool._invoke_creator(self)
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/strategies.py", line 97, in connect
return dialect.connect(*cargs, **cparams)
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 385, in connect
return self.dbapi.connect(*cargs, **cparams)
File "/usr/local/lib/python2.7/dist-packages/psycopg2/__init__.py", line 162, in connect
for (k, v) in items])
UnicodeEncodeError: 'ascii' codec can't encode character u'\x98' in position 27: ordinal not in range(128)
```

Any idea what could be causing the issue?

**Comment by mistercrunch** [comment]
What version of python?

**Comment by 005f** [comment]
2.7

**Comment by mistercrunch** [comment]
what driver are you using, what does your sqlalchemy connection string look like? (careful not to paste passwords here!)

**Comment by r39132** [comment]
The exception `UnicodeEncodeError: 'ascii' codec can't encode character u'\x98' in position 27: ordinal not in range(128)` may point the way? Perhaps you have garbage in your connect string.

**Comment by 005f** [comment]
Connection string: `postgresql+psycopg2://airflow:My!Secret&%password@my-domain.com:5432/airflow`, so using psycopg2. The error is for a start of string character so I don't think its a problem with bad stuff in the string.

**Comment by 005f** [comment]
OK, so I switched the metadata DB to mysql and discovered that the DB was not being initialised properly during the build process. Could be that this was the problem with postgres as well and it was just giving a rather obscure error message?

**Comment by r39132** [comment]
Hmn.. we (Agari) use postgresql for the metadataDB.Do you always run upgradeDB? I'm pulling HEAD master, though the last time I did such a pull was 2 weeks ago. What version of the code are you running?

**Comment by 005f** [comment]
1.6.1. Had not been running upgradeDB. We switched to mySQL and it works fine. I suspect that the DB was not initialised properly and that it was just a weird error message.
