### ISSUE TITLE
Using airflow as daemon on init.d

### ISSUE THREAD

**Issue by pedrorjbr** [apache/airflow#744]
I am trying to configure airflow webserver and scheduler to run.
I am using "python setup install" and then using the shell comand:
start-stop-daemon --start --quiet --exec airflow webserver
when i execute it under my user from shell, everything works ok.

But when I create a daemon script, on init.d i am getting:

```
2015-12-09 13:41:29,808 - root - INFO - Filling up the DagBag from /home/pedro/airflow/dags
2015-12-09 13:41:29,810 - root - INFO - Importing /home/pedro/airflow/dags/simple_ecs_dag.py
2015-12-09 13:41:29,830 - root - INFO - Loaded DAG <DAG: test-ecs>
Running the Gunicorn server with 4 syncworkers on host 0.0.0.0 and port 8080...
Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 4, in <module>
    __import__('pkg_resources').run_script('airflow==1.6.1', 'airflow')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 742, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1667, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/airflow-1.6.1-py2.7.egg/EGG-INFO/scripts/airflow", line 17, in <module>
    args.func(args)
  File "/usr/local/lib/python2.7/dist-packages/airflow-1.6.1-py2.7.egg/airflow/bin/cli.py", line 338, in webserver
    'airflow.www.app:cached_app()'])
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

I imagine that the start-stop-daemon running as a root user instead of my instalation user...

Does anyone can help me?

**Comment by pedrorjbr** [comment]
Now I change the user to the installation user:
start-stop-daemon --start --chuid ubuntu --quiet --exec /usr/local/bin/airflow webserver

But facing the same problem.. it is driving me crazy...

**Comment by bolkedebruin** [comment]
See #717. You're missing stuff in your path
