### ISSUE TITLE
Tutorial and default install on Ubuntu 14.4 give `SQLite DateTime type only accepts Python` error when running pipelines

### ISSUE THREAD

**Issue by gallamine** [apache/airflow#753]
Hello, I instaled Airflow 1.6.1 on Ubuntu 14.4, running Python 2.7. I can start the AirFlow server, visit the web UI, however if I try and "run" any of the example DAGs via the UI I get the following error:

```
raise TypeError("SQLite DateTime type only accepts Python "
StatementError: (exceptions.TypeError) SQLite DateTime type only accepts Python datetime and date objects as input. [SQL: u'INSERT INTO log (dttm, dag_id, task_id, event, execution_date, owner, extra) VALUES (?, ?, ?, ?, ?, ?, ?)'] [parameters: [{'task_id': u'runme_0', 'extra': "[('origin', u'http://localhost:8080/admin/airflow/graph?root=&dag_id=example_bash_operator'), ('force', u'false'), ('deps', u'false'), ('task_id', u'runme_0'), ('execution_date', u'2015-01-01T00:00:00'), ('dag_id', u'example_bash_operator')]", 'execution_date': u'2015-01-01T00:00:00', 'event': 'run', 'owner': 'anonymous', 'dttm': datetime.datetime(2015, 12, 10, 22, 31, 22, 996435), 'dag_id': u'example_bash_operator'}]]
```

The error also happened when the scheduler tried to run the tasks. 
I can, however, from the terminal run the command `airflow backfill tutorial -s 2015-06-01 -e 2015-06-07` and the code executes without errors.

**Comment by mistercrunch** [comment]
Good catch, looks like a legit bug. Can you please paste the full stacktrace? 

Looks like we just need to cast to datetime somewhere in that view.

**Comment by gallamine** [comment]
``````
                          ____/ (  (    )   )  \___
                         /( (  (  )   _    ))  )   )\
                       ((     (   )(    )  )   (   )  )
                     ((/  ( _(   )   (   _) ) (  () )  )
                    ( (  ( (_)   ((    (   )  .((_ ) .  )_
                   ( (  )    (      (  )    )   ) . ) (   )
                  (  (   (  (   ) (  _  ( _) ).  ) . ) ) ( )
                  ( (  (   ) (  )   (  ))     ) _)(   )  )  )
                 ( (  ( \ ) (    (_  ( ) ( )  )   ) )  )) ( )
                  (  (   (  (   (_ ( ) ( _    )  ) (  )  )   )
                 ( (  ( (  (  )     (_  )  ) )  _)   ) _( ( )
                  ((  (   )(    (     _    )   _) _(_ (  (_ )
                   (_((__(_(__(( ( ( |  ) ) ) )_))__))_)___)
                   ((__)        \\||lll|l||///          \_))
                            (   /(/ (  )  ) )\   )
                          (    ( ( ( | | ) ) )\   )
                           (   /(| / ( )) ) ) )) )
                         (     ( ((((_(|)_)))))     )
                          (      ||\(|(|)|/||     )
                        (        |(||(||)||||        )
                          (     //|/l|||)|\\ \     )
                        (/ / //  /|//||||\\  \ \  \ _)
-------------------------------------------------------------------------------
Node: airflow-test
-------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/flask_admin/base.py", line 68, in inner
    return self._run_view(f, *args, **kwargs)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/flask_admin/base.py", line 359, in _run_view
    return fn(self, *args, **kwargs)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/flask_login.py", line 755, in decorated_view
    return func(*args, **kwargs)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/airflow/www/utils.py", line 95, in wrapper
    session.commit()
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 801, in commit
    self.transaction.commit()
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 392, in commit
    self._prepare_impl()
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 372, in _prepare_impl
    self.session.flush()
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2015, in flush
    self._flush(objects)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2133, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2097, in _flush
    flush_context.execute()
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
    rec.execute(self)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
    uow
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 174, in save_obj
    mapper, table, insert)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 785, in _emit_insert_statements
    execute(statement, params)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1078, in _execute_context
    None, None)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1073, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 582, in _init_compiled
    param.append(processors[key](compiled_params[key]))
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/base.py", line 601, in process
    raise TypeError("SQLite DateTime type only accepts Python "
StatementError: (exceptions.TypeError) SQLite DateTime type only accepts Python datetime and date objects as input. [SQL: u'INSERT INTO log (dttm, dag_id, task_id, event, execution_date, owner, extra) VALUES (?, ?, ?, ?, ?, ?, ?)'] [parameters: [{'task_id': u'print_date', 'extra': "[('origin', u'http://localhost:8080/admin/airflow/graph?dag_id=tutorial'), ('force', u'false'), ('deps', u'false'), ('task_id', u'print_date'), ('execution_date', u'2015-06-07T00:00:00'), ('dag_id', u'tutorial')]", 'execution_date': u'2015-06-07T00:00:00', 'event': 'run', 'owner': 'anonymous', 'dttm': datetime.datetime(2015, 12, 11, 19, 7, 44, 43123), 'dag_id': u'tutorial'}]]```
``````

**Comment by gallamine** [comment]
Looks like this commit fixed the problem: https://github.com/airbnb/airflow/commit/c4d0fe93ed8185114364984e5eafa1b1fc404a0c#diff-6ff6b61554e53188d97c129ed40256cd
However it's not part of the package that `pip install` picks up (code still lists itself as v. 1.6.1).

**Comment by gallamine** [comment]
I did a `pip install -U git+https://github.com/airbnb/airflow@master`. Restarted the webserver and the scheduler, but now the scheduler fails with:

``````
[2015-12-11 21:26:25,114] {jobs.py:633} INFO - Done queuing tasks, calling the executor's heartbeat
[2015-12-11 21:26:25,114] {jobs.py:636} INFO - Loop took: 0.136741 seconds
[2015-12-11 21:26:25,182] {models.py:222} INFO - Finding 'running' jobs without a recent heartbeat
[2015-12-11 21:26:25,183] {models.py:228} INFO - Failing jobs without heartbeat after 2015-12-11 21:24:10.183023
[2015-12-11 21:26:25,183] {jobs.py:644} ERROR - Could not find a FROM clause to join from.  Tried joining to <class 'airflow.jobs.LocalTaskJob'>, but got: Can't find any foreign key relationships between 'task_instance' and 'job'.
Traceback (most recent call last):
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/airflow/jobs.py", line 642, in _execute
    dagbag.kill_zombies()
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/airflow/utils.py", line 132, in wrapper
    result = func(*args, **kwargs)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/airflow/models.py", line 232, in kill_zombies
    .join(LJ)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 1942, in join
    from_joinpoint=from_joinpoint)
  File "<string>", line 2, in _join
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/sqlalchemy/orm/base.py", line 201, in generate
    fn(self, *args[1:], **kw)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2085, in _join
    outerjoin, create_aliases, prop)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2153, in _join_left_to_right
    self._join_to_left(l_info, left, right, onclause, outerjoin)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2281, in _join_to_left
    "Tried joining to %s, but got: %s" % (right, ae))
InvalidRequestError: Could not find a FROM clause to join from.  Tried joining to <class 'airflow.jobs.LocalTaskJob'>, but got: Can't find any foreign key relationships between 'task_instance' and 'job'.```
``````

**Comment by gallamine** [comment]
Tried `airflow resetdb` but still get the error above. However now the scheduler does run, but the error shows up occasionally.

**Comment by gallamine** [comment]
Also `airflow upgradedb` didn't change anything.

**Comment by mistercrunch** [comment]
Time is probably ripe for 1.6.2

**Comment by daefresh** [comment]
out of the box i'm having the same problem

**Comment by timseries** [comment]
Same here...
