### ISSUE TITLE
 Can't find any foreign key relationships between 'task_instance' and 'job'.

### ISSUE THREAD

**Issue by thomastanmin93** [apache/airflow#760]
After I upgrade it to 1.6.1,I met some problems,when I just run the example DAG by the command

``` bash
airflow scheduler -d example_bash_operator
```

,I get this error ：
![image](https://cloud.githubusercontent.com/assets/8220811/11778580/4051be72-a290-11e5-9367-41dc1cf52aa2.png)

I didn't make any change about tables 'task_instance' and 'job',so I don't know where's wrong with these table.

**Comment by gallamine** [comment]
I also get these errors after installing 1.6.1 from the github master branch:

Running `airflow scheduler`:

```
[2015-12-14 14:19:59,008] {jobs.py:455} INFO - Getting list of tasks to skip for active runs.
[2015-12-14 14:19:59,015] {jobs.py:470} INFO - Checking dependencies on 54 tasks instances, minus 14 skippable ones
[2015-12-14 14:19:59,858] {jobs.py:633} INFO - Done queuing tasks, calling the executor's heartbeat
[2015-12-14 14:19:59,858] {jobs.py:636} INFO - Loop took: 5.754575 seconds
[2015-12-14 14:19:59,921] {models.py:222} INFO - Finding 'running' jobs without a recent heartbeat
[2015-12-14 14:19:59,921] {models.py:228} INFO - Failing jobs without heartbeat after 2015-12-14 14:17:44.921535
[2015-12-14 14:19:59,921] {jobs.py:644} ERROR - Could not find a FROM clause to join from.  Tried joining to <class 'airflow.jobs.LocalTaskJob'>, but got: Can't find any foreign key relationships between 'task_instance' and 'job'.
Traceback (most recent call last):
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/airflow/jobs.py", line 642, in _execute
    dagbag.kill_zombies()
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/airflow/utils.py", line 132, in wrapper
    result = func(*args, **kwargs)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/airflow/models.py", line 232, in kill_zombies
    .join(LJ)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 1942, in join
    from_joinpoint=from_joinpoint)
  File "<string>", line 2, in _join
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/sqlalchemy/orm/base.py", line 201, in generate
    fn(self, *args[1:], **kw)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2085, in _join
    outerjoin, create_aliases, prop)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2153, in _join_left_to_right
    self._join_to_left(l_info, left, right, onclause, outerjoin)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2281, in _join_to_left
    "Tried joining to %s, but got: %s" % (right, ae))
InvalidRequestError: Could not find a FROM clause to join from.  Tried joining to <class 'airflow.jobs.LocalTaskJob'>, but got: Can't find any foreign key relationships between 'task_instance' and 'job'.
[2015-12-14 14:19:59,922] {sequential_executor.py:27} INFO - Executing command: airflow run example_branch_operator run_this_first 2015-12-13T00:00:00 --local -sd DAGS_FOLDER/example_dags/example_branch_operator.py 
```

**Comment by yiqingj** [comment]
yeah this is a little bit annoying, but it seems only to be used to try "kill zombies" so doesn't impact major functions . 
adding a ForeignKey in class TaskInstance solves it.
created a PR to fix it:  https://github.com/airbnb/airflow/pull/762

**Comment by mistercrunch** [comment]
Sorry I thought I tested this properly, what about `.join(LJ, TI.job_id == LJ.id)` while removing the curent `.filter` line?

I'm afraid your current solution will generate a foreign key constraint when running alembic and I'd rather not create the constraint since both these tables are large and get a log of transactions.

**Comment by bolkedebruin** [comment]
Is this still an issue? @yiqingj @gallamine @Thomasmisfit ? If so please create a jira issue for it. Closing for now.
