### ISSUE TITLE
Exception on running Airflow webserver

### ISSUE THREAD

**Issue by pranjal-tworoads** [apache/airflow#764]
Hi,
I have setup Airflow on linux redhat machine.I am getting an exception "OSError: [Errno 2] No such file or directory" on running 'airflow webserver -p 8080' and not able to identify its cause. 
The log on running airflow webserver is as follows:

```
  ____________       _____________
 ____    |__( )_________  __/__  /________      __
____  /| |_  /__  ___/_  /_ __  /_  __ \_ | /| / /
___  ___ |  / _  /   _  __/ _  / / /_/ /_ |/ |/ /
 _/_/  |_/_/  /_/    /_/    /_/  \____/____/|__/

2015-12-15 16:47:24,907 - root - INFO - Filling up the DagBag from /home/dvcinfra/airflow/dags
2015-12-15 16:47:24,907 - root - INFO - Importing /apps/python2.7/lib/python2.7/site-packages/airflow/example_dags/example_xcom.py
2015-12-15 16:47:24,908 - root - INFO - Loaded DAG <DAG: example_xcom>
2015-12-15 16:47:24,908 - root - INFO - Importing /apps/python2.7/lib/python2.7/site-packages/airflow/example_dags/example_short_circuit_operator.py
2015-12-15 16:47:24,909 - root - INFO - Loaded DAG <DAG: example_short_circuit_operator>
2015-12-15 16:47:24,909 - root - INFO - Importing /apps/python2.7/lib/python2.7/site-packages/airflow/example_dags/example_python_operator.py
2015-12-15 16:47:24,911 - root - INFO - Loaded DAG <DAG: example_python_operator>
2015-12-15 16:47:24,911 - root - INFO - Importing /apps/python2.7/lib/python2.7/site-packages/airflow/example_dags/example_branch_operator.py
2015-12-15 16:47:24,912 - root - INFO - Loaded DAG <DAG: example_branch_operator>
2015-12-15 16:47:24,912 - root - INFO - Importing /apps/python2.7/lib/python2.7/site-packages/airflow/example_dags/example_bash_operator.py
2015-12-15 16:47:24,913 - root - INFO - Loaded DAG <DAG: example_bash_operator>
2015-12-15 16:47:24,914 - root - INFO - Importing /apps/python2.7/lib/python2.7/site-packages/airflow/example_dags/tutorial.py
2015-12-15 16:47:24,914 - root - INFO - Loaded DAG <DAG: tutorial>
2015-12-15 16:47:24,914 - root - INFO - Importing /apps/python2.7/lib/python2.7/site-packages/airflow/example_dags/example_http_operator.py
2015-12-15 16:47:24,915 - root - INFO - Loaded DAG <DAG: example_http_operator>
Running the Gunicorn server with 4 syncworkers on host 0.0.0.0 and port 8080...
Traceback (most recent call last):
  File "/apps/python2.7/lib/python2.7/site-packages/airflow/bin/airflow", line 19, in <module>
    args.func(args)
  File "/apps/python2.7/lib/python2.7/site-packages/airflow/bin/cli.py", line 342, in webserver
    'airflow.www.app:cached_app()'])
  File "/apps/python2.7/lib/python2.7/subprocess.py", line 682, in __init__
    errread, errwrite)
  File "/apps/python2.7/lib/python2.7/subprocess.py", line 1253, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by lukun2010** [comment]
I met the same issue. I found that some execution files was placed in `/usr/local/bin`, after `export PATH=/usr/local/bin:$PATH`, everything is fine, you could have a try.

**Comment by mistercrunch** [comment]
thanks for jumping in @lukun2010 !

**Comment by n1tk** [comment]
@lukun2010 Thank you for solution. Works for me (rhel and mac).

**Comment by pranjal-tworoads** [comment]
@lukun2010 Thanks for your help. Worked for me.
