### ISSUE TITLE
UnicodeDecodeError in bash_operator.py

### ISSUE THREAD

**Issue by trivoallan** [apache/airflow#770]
Hi,

I see a lot of these errors when running `airflow backfill` : 

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 851, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 724, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 467, in format
    s = self._fmt % record.__dict__
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 13: ordinal not in range(128)
Logged from file bash_operator.py, line 72
```

**Comment by aRe00t** [comment]
I encountered the same problem. I have hacked the [line#73 in airflow/operators/bash_operator.py](https://github.com/airbnb/airflow/blob/master/airflow/operators/bash_operator.py#L73) to 
`line = line.decode('utf-8').strip()` to fix my problem.

error log

```
[2015-12-22 18:17:51,354] {bash_operator.py:70} INFO - Output:
[2015-12-22 18:17:51,359] {models.py:1041} ERROR - 'ascii' codec can't decode byte 0xe5 in position 4: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/airflow/models.py", line 1000, in run
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python2.7/dist-packages/airflow/operators/bash_operator.py", line 73, in execute
    line = line.decode().strip()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 4: ordinal not in range(128)
[2015-12-22 18:17:51,388] {models.py:1077} ERROR - 'ascii' codec can't decode byte 0xe5 in position 4: ordinal not in range(128)
```

**Comment by r39132** [comment]
There is already a `help-wanted` tag posted on #721

**Comment by haitaoyao** [comment]
@GeiliCode How about submit a pull request for this? I think it's a common problem. thx

**Comment by aRe00t** [comment]
@haitaoyao I am not familiar with encoding, so I don't know how to deal with encoding which is not  `ascii` nor `utf-8`.
