### ISSUE TITLE
This DAG crashes my scheduler very quickly (with explanation)

### ISSUE THREAD

**Issue by boxysean** [apache/airflow#784]
## Environment
- OS: Debian Wheezy (via [docker-airflow](https://github.com/puckel/docker-airflow))
- [Configuration](https://gist.github.com/boxysean/5b5d73f4fc3541d63c4b#file-airflow-cfg) (trimmed)
- python 2.7.9, Airflow 1.6.1 from pypi, [my project's requirements.txt](https://gist.github.com/boxysean/5b5d73f4fc3541d63c4b#file-requirements-txt) (trimmed)
## How to replicate and explanation

[This DAG](https://gist.github.com/boxysean/5b5d73f4fc3541d63c4b#file-dag_that_crashes_scheduler-py) crashes my scheduler very quickly when manually (externally) triggered. I'm going to guess it will crash for everyone running Airflow 1.6.1 and up to master.

I find my DAGs start to be scheduled only after manually / externally triggering them. (Not sure why.) The manual trigger generates this DagRun:

```
<DagRun crash_dag @ 2015-12-17 16:28:34: test, externally triggered: True>
```

Then the subsequent scheduler heartbeats generates new scheduled DagRuns one at a time (one for each of the four previous minutes):

```
<DagRun crash_dag @ 2015-12-17 16:24:34: scheduled__2015-12-17T16:24:34, externally triggered: False>
<DagRun crash_dag @ 2015-12-17 16:25:34: scheduled__2015-12-17T16:25:34, externally triggered: False>
<DagRun crash_dag @ 2015-12-17 16:26:34: scheduled__2015-12-17T16:26:34, externally triggered: False>
<DagRun crash_dag @ 2015-12-17 16:27:34: scheduled__2015-12-17T16:27:34, externally triggered: False>
```

One minute passes, then it tries to schedule the next DagRun, but it crashes with this exception:

```
2015-12-17 16:29:35,097 - root - ERROR - (_mysql_exceptions.IntegrityError) (1062, "Duplicate entry 'crash_dag-2015-12-17 16:28:34' for key 'dag_id'") [SQL: u'INSERT INTO dag_run (dag_id, execution_date, state, run_id, external_trigger, conf) VALUES (%s, %s, %s, %s, %s, %s)'] [parameters: ('crash_dag', datetime.datetime(2015, 12, 17, 16, 28, 34), u'running', u'scheduled__2015-12-17T16:28:34', 0, None)]
Traceback (most recent call last):
   File "/usr/local/lib/python2.7/dist-packages/airflow/jobs.py", line 608, in _execute
     self.schedule_dag(dag)
   File "/usr/local/lib/python2.7/dist-packages/airflow/jobs.py", line 398, in schedule_dag
     session.commit()
   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 801, in commit
     self.transaction.commit()
<snip>
```

The reason is my Airflow database (tested on both MySQL and Postgres) has a unique key definition in the `dag_run` table on `(dag_id, execution_date)`. Indeed, the DagRun attempting to be scheduled with ID `scheduled__2015-12-17T16:28:34` is colliding with my DagRun with ID `test`.

After this collision and exception, the scheduler remains alive, and for each scheduler heartbeat, I get the following SQLA rollback message, preventing all future scheduling:

```
2015-12-17 16:29:35,115 - root - ERROR - This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.IntegrityError) (1062, "Duplicate entry 'crash_dag-2015-12-17 16:28:34' for key 'dag_id'") [SQL: u'INSERT INTO dag_run (dag_id, execution_date, state, run_id, external_trigger, conf) VALUES (%s, %s, %s, %s, %s, %s)'] [parameters: ('crash_dag', datetime.datetime(2015, 12, 17, 16, 28, 34), u'running', u'scheduled__2015-12-17T16:28:34', 0, None)]
 Traceback (most recent call last):
   File "/usr/local/lib/python2.7/dist-packages/airflow/jobs.py", line 618, in _execute
     self.import_errors(dagbag)
   File "/usr/local/lib/python2.7/dist-packages/airflow/jobs.py", line 340, in import_errors
     session.query(models.ImportError).delete()
   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2883, in delete
     delete_op.exec_()
<snip>
```

Looking into the Airflow codebase, I see that [the DagRun model has a single unique index](https://github.com/airbnb/airflow/blob/master/airflow/models.py#L2721-L2723) that is _not_ the unique index causing this issue. There is, however, [a migration that adds the unique DagRun index](https://github.com/airbnb/airflow/blob/master/airflow/migrations/versions/1b38cef5b76e_add_dagrun.py#L29) causing this issue.
## How to fix

I'm going to try to work-around by manually deleting the unique constraint on the `dag_run.(dag_id, execution_date)` index. I'm guessing it will work okay for now.

I think the root cause is an inconsistency between the DagRun model and the list of migrations that needs to be resolved in such a way there isn't index collisions.

**Comment by mistercrunch** [comment]
Thanks for the detailed report, this seem to be an edge case. That unique index is important as the pk of the task instances are dag_id/task_id/execution_date. If 2 dag runs had the same timestamp there would be collisions in the task_instance table. 

To me normally DAGs are either scheduled or externally triggered by nature, I'm not sure if I understand the hybrid use case and infer how to deal with collisions.

**Comment by boxysean** [comment]
From a technical perspective, I still believe there is an inconsistency between the DagRun migration scripts and the DagRun model which needs to be addressed / clarified. This index `dag_run.(dag_id, execution_date)` does not exist in the model but does exist in the migrations.

From a usability perspective, my DAG (referenced above) will not be scheduled without first manually externally triggering the initial run, even with my DAG flipped in the "ON" position. It is my desire to have my DAGs work on a schedule exclusively, but they would be scheduled only after the initial external trigger. Maybe the hybrid use case may not make sense, but it is a necessary starting point for this DAG.

**Comment by bolkedebruin** [comment]
@boxysean it should be addressed as part of AIRFLOW-20, please keep an eye on it and create a Jira issue if it doesn't. Closing this here for now
