### ISSUE TITLE
Debug Executor: 'dict' object has no attribute 'remove'

### ISSUE THREAD

**Issue by ghostbody** [apache/airflow#8238]
**Apache Airflow version**: v1.10.9

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): ubuntu 18.04
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:
**What happened**:

Error ocurs when using `DebugExecutor`

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/some-path/.virtualenv/lib/python3.7/site-packages/airflow/jobs/scheduler_job.py", line 1380, in _execute
    self._execute_helper()
  File "/some-path/.virtualenv/lib/python3.7/site-packages/airflow/jobs/scheduler_job.py", line 1441, in _execute_helper
    if not self._validate_and_run_task_instances(simple_dag_bag=simple_dag_bag):
  File "/some-path/.virtualenv/lib/python3.7/site-packages/airflow/jobs/scheduler_job.py", line 1503, in _validate_and_run_task_instances
    self.executor.heartbeat()
  File "/some-path/.virtualenv/lib/python3.7/site-packages/airflow/executors/base_executor.py", line 134, in heartbeat
    self.sync()
  File "/some-path/.virtualenv/lib/python3.7/site-packages/airflow/executors/debug_executor.py", line 71, in sync
    task_succeeded = self._run_task(ti)
  File "/some-path/.virtualenv/lib/python3.7/site-packages/airflow/executors/debug_executor.py", line 84, in _run_task
    self.change_state(key, State.FAILED)
  File "/some-path/.virtualenv/lib/python3.7/site-packages/airflow/executors/debug_executor.py", line 148, in change_state
    self.running.remove(key)
AttributeError: 'dict' object has no attribute 'remove'
```

**What you expected to happen**:

This error shoud not happen.

**How to reproduce it**:

1. use `CeleryExecutor` to run some dags. 
2. switch to `DebugExecutor`
3. this error happens

**Anything else we need to know**:

I am sure that some of the logic in `DebugExecutor` is not correct

in `BaseExecutor`, there is a instance variable named `running`, which is initialized with a `{}` notation.

`airflow/executors/base_executor.py:46`
```python
class BaseExecutor(LoggingMixin):

    def __init__(self, parallelism=PARALLELISM):
        """
        Class to derive in order to interface with executor-type systems
        like Celery, Mesos, Yarn and the likes.

        :param parallelism: how many jobs should run at one time. Set to
            ``0`` for infinity
        :type parallelism: int
        """
        self.parallelism = parallelism
        self.queued_tasks = OrderedDict()
        self.running = {}                                   # here
        self.event_buffer = {}
```

**However** in the `DebugExector` class, it use the variable as both `Set` and `Dict`.

`airflow/executors/debug_executor.py:130`
```python
    def trigger_tasks(self, open_slots):
        """
        Triggers tasks. Instead of calling exec_async we just
        add task instance to tasks_to_run queue.

        :param open_slots: Number of open slots
        """
        sorted_queue = sorted(
            [(k, v) for k, v in self.queued_tasks.items()],
            key=lambda x: x[1][1],
            reverse=True,
        )
        for _ in range(min((open_slots, len(self.queued_tasks)))):
            key, (_, _, _, ti) = sorted_queue.pop(0)
            self.queued_tasks.pop(key)
            self.running[key] = ti                                               # here, use as a dict
            self.tasks_to_run.append(ti)  # type: ignore
```

but here, `airflow/executors/debug_executor.py:146`
```python
    def change_state(self, key, state):
        self.log.debug("Popping %s from executor task queue.", key)
        self.running.remove(key)                                             # here, use a set. And there is no `remove` method for a dict.
        self.event_buffer[key] = state
```

**Comment by turbaszek** [comment]
Fixed in 1.10.10
https://github.com/apache/airflow/issues/8060
