### ISSUE TITLE
Unable to delete task instance from UI

### ISSUE THREAD

**Issue by seancron** [apache/airflow#849]
Whenever I try to delete a task instance from `/admin/taskinstance/` I get the following traceback:

``` python
Traceback (most recent call last):
  File "/home/sean/.virtualenvs/airflow_test/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sean/.virtualenvs/airflow_test/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sean/.virtualenvs/airflow_test/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sean/.virtualenvs/airflow_test/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sean/.virtualenvs/airflow_test/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/sean/.virtualenvs/airflow_test/local/lib/python2.7/site-packages/flask_admin/base.py", line 68, in inner
    return self._run_view(f, *args, **kwargs)
  File "/home/sean/.virtualenvs/airflow_test/local/lib/python2.7/site-packages/flask_admin/base.py", line 359, in _run_view
    return fn(self, *args, **kwargs)
  File "/home/sean/.virtualenvs/airflow_test/local/lib/python2.7/site-packages/flask_admin/model/base.py", line 1668, in delete_view
    model = self.get_one(id)
  File "/home/sean/.virtualenvs/airflow_test/local/lib/python2.7/site-packages/flask_admin/contrib/sqla/view.py", line 959, in get_one
    return self.session.query(self.model).get(tools.iterdecode(id))
  File "/home/sean/.virtualenvs/airflow_test/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 831, in get
    return self._get_impl(ident, loading.load_on_ident)
  File "/home/sean/.virtualenvs/airflow_test/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 864, in _get_impl
    return fallback_fn(self, key)
  File "/home/sean/.virtualenvs/airflow_test/local/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 219, in load_on_ident
    return q.one()
  File "/home/sean/.virtualenvs/airflow_test/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2693, in one
    ret = list(self)
  File "/home/sean/.virtualenvs/airflow_test/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2736, in __iter__
    return self._execute_and_instances(context)
  File "/home/sean/.virtualenvs/airflow_test/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2751, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/sean/.virtualenvs/airflow_test/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/home/sean/.virtualenvs/airflow_test/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/sean/.virtualenvs/airflow_test/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/sean/.virtualenvs/airflow_test/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1078, in _execute_context
    None, None)
  File "/home/sean/.virtualenvs/airflow_test/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/home/sean/.virtualenvs/airflow_test/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/home/sean/.virtualenvs/airflow_test/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1073, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "/home/sean/.virtualenvs/airflow_test/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 582, in _init_compiled
    param.append(processors[key](compiled_params[key]))
  File "/home/sean/.virtualenvs/airflow_test/local/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/base.py", line 601, in process
    raise TypeError("SQLite DateTime type only accepts Python "
StatementError: (exceptions.TypeError) SQLite DateTime type only accepts Python datetime and date objects as input. [SQL: u'SELECT task_instance.task_id AS task_instance_task_id, task_instance.dag_id AS task_instance_dag_id, task_instance.execution_date AS task_instance_execution_date, task_instance.start_date AS task_instance_start_date, task_instance.end_date AS task_instance_end_date, task_instance.duration AS task_instance_duration, task_instance.state AS task_instance_state, task_instance.try_number AS task_instance_try_number, task_instance.hostname AS task_instance_hostname, task_instance.unixname AS task_instance_unixname, task_instance.job_id AS task_instance_job_id, task_instance.pool AS task_instance_pool, task_instance.queue AS task_instance_queue, task_instance.priority_weight AS task_instance_priority_weight, task_instance.operator AS task_instance_operator, task_instance.queued_dttm AS task_instance_queued_dttm \nFROM task_instance \nWHERE task_instance.task_id = ? AND task_instance.dag_id = ? AND task_instance.execution_date = ?'] [parameters: [{'%(66160016 param)s': u'sleep', '%(66159632 param)s': u'tutorial2', '%(66162064 param)s': u'2015-06-09 07:00:00'}]]
```

**Environment:**
- airflow==1.6.2
- OS: Ubuntu 12.04 64-bit
- CeleryExecutor
- SQLite database
- Python 2.7.3

**Comment by camilb** [comment]
Never encountered this issue. 
- airflow 1.6.2, 
- Debian Jessie (docker),
- Python 2.7.10

**Comment by seancron** [comment]
Confirms that it works when switching to Postgres. Seems to be specific to the SQLite database.

**Comment by jerrygillespie** [comment]
I had a similar issue when I upgraded from 1.6.1. I did an airflow upgradedb and then I think a resetdb.

**Comment by r39132** [comment]
Reported and now being tracked in https://github.com/airbnb/airflow/issues/955. Closing this one as a duplicate.
