### ISSUE TITLE
TriggerDagOperator sometimes causes database to trigger UniqueViolation constraint

### ISSUE THREAD

**Issue by kyle-hamlin** [apache/airflow#8494]
**Apache Airflow version**: 1.10.10

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-23T14:21:54Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-502bfb", GitCommit:"502bfb383169b124d87848f89e17a04b9fc1f6f0", GitTreeState:"clean", BuildDate:"2020-02-07T01:31:02Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

**Environment**: EKS - KubernetesExecutor

- **Cloud provider or hardware configuration**: AWS EKS
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**: Docker image
- **Others**:

**What happened**:

Sometimes the TriggerDagOperator will fail with the following error, when, in fact, it was successful in triggering the target DAG.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1228, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 857, in do_executemany
    cursor.executemany(statement, parameters)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "task_instance_pkey"
DETAIL:  Key (task_id, dag_id, execution_date)=(<task_id>, <dag_id>, 2020-04-20 17:00:00+00) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/dagrun_operator.py", line 95, in execute
    replace_microseconds=False)
  File "/usr/local/lib/python3.7/site-packages/airflow/api/common/experimental/trigger_dag.py", line 141, in trigger_dag
    replace_microseconds=replace_microseconds,
  File "/usr/local/lib/python3.7/site-packages/airflow/api/common/experimental/trigger_dag.py", line 98, in _trigger_dag
    external_trigger=True,
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/db.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dag.py", line 1469, in create_dagrun
    run.verify_integrity(session=session)
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/db.py", line 70, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagrun.py", line 400, in verify_integrity
    session.commit()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1036, in commit
    self.transaction.commit()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 503, in commit
    self._prepare_impl()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 482, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2496, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2637, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2597, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    insert,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 1083, in _emit_insert_statements
    c = cached_connections[connection].execute(statement, multiparams)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 984, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1103, in _execute_clauseelement
    distilled_params,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1288, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1482, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1228, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 857, in do_executemany
    cursor.executemany(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "task_instance_pkey"
DETAIL:  Key (task_id, dag_id, execution_date)=(<task_id>, <dag_id>, 2020-04-20 17:00:00+00) already exists.
```

**What you expected to happen**:

 It seems like this could by some kind of race condition or perhaps an issue with rescheduling? I expect this to not happen or for there to be a check before attempting to triggering the DAG so as to not have a false positive.

**How to reproduce it**:

Really not sure how to reproduce, its a pretty strange bug.

**Anything else we need to know**:

It happens maybe 3-4 times a month.

**Comment by BigCheeze45** [comment]
I'm also seeing the same error in my environment. We can reproduce it consistently with a manual trigger (`schedule_interval=None`)
Executor: LocalExecutor
Backend: MSSQL
Airflow version: 1.10.10
Python: v3.6

**Comment by Lyalpha** [comment]
Also finding this, apparently due to triggering same dag in same second (https://issues.apache.org/jira/browse/AIRFLOW-699 - apparently resolved?)

```
from airflow.api.client.local_client import Client
client = Client(None, None)
client.trigger_dag(dag_id="my_dag", run_id="one"); client.trigger_dag(dag_id="mydag", run_id="two") 
```
reproduces for me on `1.10.10`.

Being able to trigger the same dag multiple times a seconds is a deal-breaker - happy to help out if pointed in the right direction for this one.

**Comment by MNic** [comment]
We're having the same issue when trying to trigger the same DAG twice in a second.  We're using the CLI to trigger but it doesn't expose the `replace_microseconds` param.

Would be nice to have `replace_microseconds` exposed at all of the available `trigger_dag` interfaces.

**Comment by takunnithan** [comment]
Ran into the same issue with REST API, We were trying to trigger a dag via experimental API (sometimes more than 30 DAG runs at a time). 
Tried setting the `replace_microseconds`  flag to `False` in the API, It doesn't solve the issue in my case. It just reduces the frequency of the issue. 

I have a solution/Hack in mind, 

Does it make sense to add a bool param in the experimental API, say `handle_duplicate_execution_date`. if set as true, it will handle the duplicate execution_date issue by increasing the `execution_date` , a few microseconds. 

For eg: 


 id   |      dag_id      |        execution_date         
-----+------------------+-------------------------------
 171 | TEST_DAG 	| 2020-06-19 12:56:06.171041+00


if we encounter a unique constraint issue, we will simply increase the execution time by a few microseconds.

 id   |      dag_id      |        execution_date         
-----+------------------+-------------------------------
 171 | TEST_DAG 	| 2020-06-19 12:56:06.171041+00
 172 | TEST_DAG 	| 2020-06-19 12:56:06.171051+00


This can be done by adding `try... except` block here : https://github.com/apache/airflow/blob/05ea88869be6a62d312598b5b01095e16f0a16f8/airflow/api/common/experimental/trigger_dag.py#L86

**Comment by Lyalpha** [comment]
I handled it with the following wrapper. Rather than changing the `execution_date`, just try again in a microsecond. (The micro-sleep is probably superfluous given there is an overhead with the call, but it just ensures >1ms passes between tries)
```
def safe_trigger_dag(
    dag_id, run_id=None, conf=None, execution_date=None, replace_microseconds=False,
):
    """
    A wrapper for airflow's trigger_dag, which will micro-sleep if the dag fails to start
    due to a unique key violation on `dag_id` and `execution_time`

    Also, by default, will not replace microseconds - this allows for dag scheduling on
    microsecond intervals
    """
    while True:
        try:
            trigger_dag(
                dag_id=dag_id,
                run_id=run_id,
                conf=conf,
                execution_date=execution_date,
                replace_microseconds=replace_microseconds,
            )
        except IntegrityError as e:
            assert isinstance(e.orig, UniqueViolation)
            logging.warning("UniqueViolation detected when triggering dag, starting micro-sleep")
            time.sleep(1e-6)
        else:
            break
```

**Comment by takunnithan** [comment]
@Lyalpha This is a better approach. 👍

**Comment by MatteoMart1994** [comment]
Issue still met in composer-1-15-0-airflow-1-10-12

**Comment by uranusjr** [comment]
1.10 has reached end of line, so I’m going to close this unless someone reproduces this on the 2.x series.

**Comment by Lyalpha** [comment]
There has been no fix of this, so I expect it is the same in 2.x, although I don't have a MWE to check.
* The CLI does not expose a way to trigger the same dag >1/second
* Even via lower-level `trigger_dag()` calls, running a dag in the same microsecond causes an error.

**Comment by potiuk** [comment]
There has been a bit overhaul of DAG triggering in Airflow 2 and there is a different primary index on DagRun and we are also preparing for making "out-of-band" triggering a DagRun which is not connected with particular interval. So I think this issue is either gone entirely already in Airflow 2, or when we release "AIP-39 - Richer scheduler interval" I think it will be the final step to consider that non-issue. So I agree with @uranusjr that this one should be closed.

BTW. If you have not yet migrated to 1.10, do it now. It wont receive any fixes any more (including critical security fixes). In fact there are already known security problems which have not been patched in 1.10 - you can get more insight by watching our talk from the Airflow Summit: "Keep your Airflow Secure" https://www.crowdcast.io/e/airflowsummit2021/3

**Comment by Lyalpha** [comment]
OK thanks, I am already on 2.x but indeed I don't know if any DB changes may have alleviated this as the fix I posted has meant I never saw it again for the remainder of 1.x (or now, in 2.x).

**Comment by uranusjr** [comment]
Also iirc the metadatabase is currently running on sub-millisecond precision, so even if this is still an issue (and I am not sure about that), it’s probably significantly more difficult to trigger. And AIP-39 would definitely be the last step to eliminate that last theoratical possibility.
