### ISSUE TITLE
Verify DAG locally fails when using DAG Variable

### ISSUE THREAD

**Issue by CodingJonas** [apache/airflow#8538]
**Apache Airflow version**:1.10.10

- **OS** (e.g. from /etc/os-release): Ubuntu 18.04
- **Install tools**: Pipenv

**What happened**:

I want to verify DAGs locally through `python dag.py` (on a different machine than the one running my complete Airflow setup). This does not work when using airflow.models.Variable, since these don't exist on my local machine.

**How to reproduce it**:

This code:
```
from datetime import datetime

from airflow import DAG
from airflow.models import Variable
from airflow.operators.bash_operator import BashOperator


dag_params = dict(
    dag_id='test',
    schedule_interval=None,
    start_date=datetime(2020, 4, 1),
)

with DAG(**dag_params) as dag:
    t = BashOperator(
        task_id='sleep',
        bash_command='sleep 5',
        params={'my_param': Variable.get("var")},
        dag=dag,
    )

    t
```
Run with this command `python src/dags/test.py`

I receive this error:
```
Traceback (most recent call last):
  File "<PATH>/.local/share/virtualenvs/airflow-test-setup-ZQDOsgN6/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "<PATH>/.local/share/virtualenvs/airflow-test-setup-ZQDOsgN6/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: variable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "src/dags/test.py", line 18, in <module>
    params={'my_param': Variable.get("var")},
  File "<PATH>/.local/share/virtualenvs/airflow-test-setup-ZQDOsgN6/lib/python3.6/site-packages/airflow/models/variable.py", line 113, in get
    var_val = get_variable(key=key)
  File "<PATH>/.local/share/virtualenvs/airflow-test-setup-ZQDOsgN6/lib/python3.6/site-packages/airflow/secrets/__init__.py", line 68, in get_variable
    var_val = secrets_backend.get_variable(key=key)
  File "<PATH>/.local/share/virtualenvs/airflow-test-setup-ZQDOsgN6/lib/python3.6/site-packages/airflow/utils/db.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "<PATH>/.local/share/virtualenvs/airflow-test-setup-ZQDOsgN6/lib/python3.6/site-packages/airflow/secrets/metastore.py", line 53, in get_variable
    var_value = session.query(Variable).filter(Variable.key == key).first()
  File "<PATH>/.local/share/virtualenvs/airflow-test-setup-ZQDOsgN6/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3300, in first
    ret = list(self[0:1])
  File "<PATH>/.local/share/virtualenvs/airflow-test-setup-ZQDOsgN6/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3078, in __getitem__
    return list(res)
  File "<PATH>/.local/share/virtualenvs/airflow-test-setup-ZQDOsgN6/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3405, in __iter__
    return self._execute_and_instances(context)
  File "<PATH>/.local/share/virtualenvs/airflow-test-setup-ZQDOsgN6/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3430, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "<PATH>/.local/share/virtualenvs/airflow-test-setup-ZQDOsgN6/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 984, in execute
    return meth(self, multiparams, params)
  File "<PATH>/.local/share/virtualenvs/airflow-test-setup-ZQDOsgN6/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "<PATH>/.local/share/virtualenvs/airflow-test-setup-ZQDOsgN6/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1103, in _execute_clauseelement
    distilled_params,
  File "<PATH>/.local/share/virtualenvs/airflow-test-setup-ZQDOsgN6/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1288, in _execute_context
    e, statement, parameters, cursor, context
  File "<PATH>/.local/share/virtualenvs/airflow-test-setup-ZQDOsgN6/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1482, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "<PATH>/.local/share/virtualenvs/airflow-test-setup-ZQDOsgN6/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "<PATH>/.local/share/virtualenvs/airflow-test-setup-ZQDOsgN6/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "<PATH>/.local/share/virtualenvs/airflow-test-setup-ZQDOsgN6/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: variable
[SQL: SELECT variable.val AS variable_val, variable.id AS variable_id, variable."key" AS variable_key, variable.is_encrypted AS variable_is_encrypted 
FROM variable 
WHERE variable."key" = ?
 LIMIT ? OFFSET ?]
[parameters: ('var', 1, 0)]
(Background on this error at: http://sqlalche.me/e/e3q8)
```
If I create an empty airflow setup locally with `airflow initdb`, I can still not test it until I define my variables. This takes a lot of flexibility during development, since I need to maintain the same configuration in two places.

Is it possible to maintain some default values, or set some kind of flag that will ignore such errors?

**Comment by kaxil** [comment]
From Airflow 1.10.10 you can set Environment Variables to be used as Airflow Variables.

Docs: https://airflow.apache.org/docs/stable/concepts.html?highlight=variable#storing-variables-in-environment-variables

which is what you can use for development.

**Comment by mik-laj** [comment]
You can use fallback when retrieving variables. I am also working on a feature that allows you to store variables in a JSON file.
https://github.com/apache/airflow/pull/8436

After all, I don't recommend trying to load DAG files directly as scripts.This in some cases can be problematic in Airflow 2.0.  I recommend that you always load files using Airflow. 
```
airflow dags list --subdir airflow/providers/google/cloud/example_dags/example_gcs.py
```

**Comment by CodingJonas** [comment]
Thank you for your help! @mik-laj, your new feature is exactly what I was looking for!
