### ISSUE TITLE
Throw an error or warning when CeleryExecutor is defined in airflow.cfg, but cannot be imported

### ISSUE THREAD

**Issue by seancron** [apache/airflow#856]
Minor issue, but one that makes it more user friendly.

When `CeleryExecutor` is set in `airflow.cfg`, but the dependencies for the `CeleryExecutor` are not installed, you get the following traceback when trying to run `airflow list_dags`:

``` python
Traceback (most recent call last):
  File "/home/scronin/.venvs/airflow_test/bin/airflow", line 4, in <module>
    from airflow import configuration
  File "/home/scronin/.venvs/airflow_test/lib/python2.7/site-packages/airflow/__init__.py", line 16, in <module>
    from airflow.models import DAG
  File "/home/scronin/.venvs/airflow_test/lib/python2.7/site-packages/airflow/models.py", line 39, in <module>
    from airflow.executors import DEFAULT_EXECUTOR, LocalExecutor
  File "/home/scronin/.venvs/airflow_test/lib/python2.7/site-packages/airflow/executors/__init__.py", line 20, in <module>
    DEFAULT_EXECUTOR = CeleryExecutor()
NameError: name 'CeleryExecutor' is not defined
```

An error or warning should be thrown prompting the user to install the missing dependencies.

**Comment by samson-wang** [comment]
I have the same problem.
After some debug, I found these

```
try:
    from airflow.executors.celery_executor import CeleryExecutor
except:
    pass
```

 in 'airflow/executors/**init**.py'

Add a raise instead of pass, error messages give a clue as 

```
Traceback (most recent call last):
  File "/data/home/samson/.local/bin/airflow", line 4, in <module>
    from airflow import configuration
  File "/data/home/samson/.local/lib/python2.7/site-packages/airflow/__init__.py", line 16, in <module>
    from airflow.models import DAG
  File "/data/home/samson/.local/lib/python2.7/site-packages/airflow/models.py", line 39, in <module>
    from airflow.executors import DEFAULT_EXECUTOR, LocalExecutor
  File "/data/home/samson/.local/lib/python2.7/site-packages/airflow/executors/__init__.py", line 9, in <module>
    from airflow.executors.celery_executor import CeleryExecutor
  File "/data/home/samson/.local/lib/python2.7/site-packages/airflow/executors/celery_executor.py", line 6, in <module>
    from celery import Celery
ImportError: No module named celery
```

So just `pip install celery`can fix it.
