### ISSUE TITLE
AttributeError in S3TaskHandler on Airflow 1.10.10

### ISSUE THREAD

**Issue by webster-chainalysis** [apache/airflow#8825]
Hello.  I upgraded to Airflow 1.10.10 and encounter the following error when the scheduler attempts to configure remote logging using the `S3TaskHandler`:

```
Unable to load the config, contains a configuration error.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/logging/config.py", line 563, in configure
    handler = self.configure_handler(handlers[name])
  File "/usr/local/lib/python3.7/logging/config.py", line 736, in configure_handler
    result = factory(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/log/s3_task_handler.py", line 35, in __init__
    super(S3TaskHandler, self).__init__(base_log_folder, filename_template)
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/log/file_task_handler.py", line 47, in __init__
    parse_template_string(filename_template)
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 355, in parse_template_string
    return None, Template(template_string)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 945, in __new__
    return env.from_string(source, template_class=cls)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 880, in from_string
    return cls.from_code(self, self.compile(source), globals, None)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<unknown>", line 1, in template
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/usr/local/lib/python3.7/site-packages/jinja2/parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/usr/local/lib/python3.7/site-packages/jinja2/parser.py", line 875, in subparse
    add_data(self.parse_tuple(with_condexpr=True))
  File "/usr/local/lib/python3.7/site-packages/jinja2/parser.py", line 620, in parse_tuple
    args.append(parse())
  File "/usr/local/lib/python3.7/site-packages/jinja2/parser.py", line 432, in parse_expression
    return self.parse_condexpr()
  File "/usr/local/lib/python3.7/site-packages/jinja2/parser.py", line 437, in parse_condexpr
    expr1 = self.parse_or()
  File "/usr/local/lib/python3.7/site-packages/jinja2/parser.py", line 450, in parse_or
    left = self.parse_and()
  File "/usr/local/lib/python3.7/site-packages/jinja2/parser.py", line 459, in parse_and
    left = self.parse_not()
  File "/usr/local/lib/python3.7/site-packages/jinja2/parser.py", line 470, in parse_not
    return self.parse_compare()
  File "/usr/local/lib/python3.7/site-packages/jinja2/parser.py", line 474, in parse_compare
    expr = self.parse_math1()
  File "/usr/local/lib/python3.7/site-packages/jinja2/parser.py", line 496, in parse_math1
    left = self.parse_concat()
  File "/usr/local/lib/python3.7/site-packages/jinja2/parser.py", line 507, in parse_concat
    args = [self.parse_math2()]
  File "/usr/local/lib/python3.7/site-packages/jinja2/parser.py", line 517, in parse_math2
    left = self.parse_pow()
  File "/usr/local/lib/python3.7/site-packages/jinja2/parser.py", line 528, in parse_pow
    left = self.parse_unary()
  File "/usr/local/lib/python3.7/site-packages/jinja2/parser.py", line 546, in parse_unary
    node = self.parse_primary()
  File "/usr/local/lib/python3.7/site-packages/jinja2/parser.py", line 581, in parse_primary
    node = self.parse_dict()
  File "/usr/local/lib/python3.7/site-packages/jinja2/parser.py", line 661, in parse_dict
    key = self.parse_expression()
  File "/usr/local/lib/python3.7/site-packages/jinja2/parser.py", line 432, in parse_expression
    return self.parse_condexpr()
  File "/usr/local/lib/python3.7/site-packages/jinja2/parser.py", line 437, in parse_condexpr
    expr1 = self.parse_or()
  File "/usr/local/lib/python3.7/site-packages/jinja2/parser.py", line 450, in parse_or
    left = self.parse_and()
  File "/usr/local/lib/python3.7/site-packages/jinja2/parser.py", line 459, in parse_and
    left = self.parse_not()
  File "/usr/local/lib/python3.7/site-packages/jinja2/parser.py", line 470, in parse_not
    return self.parse_compare()
  File "/usr/local/lib/python3.7/site-packages/jinja2/parser.py", line 474, in parse_compare
    expr = self.parse_math1()
  File "/usr/local/lib/python3.7/site-packages/jinja2/parser.py", line 496, in parse_math1
    left = self.parse_concat()
  File "/usr/local/lib/python3.7/site-packages/jinja2/parser.py", line 507, in parse_concat
    args = [self.parse_math2()]
  File "/usr/local/lib/python3.7/site-packages/jinja2/parser.py", line 517, in parse_math2
    left = self.parse_pow()
  File "/usr/local/lib/python3.7/site-packages/jinja2/parser.py", line 528, in parse_pow
    left = self.parse_unary()
  File "/usr/local/lib/python3.7/site-packages/jinja2/parser.py", line 546, in parse_unary
    node = self.parse_primary()
  File "/usr/local/lib/python3.7/site-packages/jinja2/parser.py", line 581, in parse_primary
    node = self.parse_dict()
  File "/usr/local/lib/python3.7/site-packages/jinja2/parser.py", line 662, in parse_dict
    self.stream.expect('colon')
  File "/usr/local/lib/python3.7/site-packages/jinja2/lexer.py", line 384, in expect
    self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: expected token ':', got '}'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 25, in <module>
    from airflow.configuration import conf
  File "/usr/local/lib/python3.7/site-packages/airflow/__init__.py", line 47, in <module>
    settings.initialize()
  File "/usr/local/lib/python3.7/site-packages/airflow/settings.py", line 374, in initialize
    LOGGING_CLASS_PATH = configure_logging()
  File "/usr/local/lib/python3.7/site-packages/airflow/logging_config.py", line 68, in configure_logging
    raise e
  File "/usr/local/lib/python3.7/site-packages/airflow/logging_config.py", line 63, in configure_logging
    dictConfig(logging_config)
  File "/usr/local/lib/python3.7/logging/config.py", line 800, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/local/lib/python3.7/logging/config.py", line 571, in configure
    '%r' % name) from e
ValueError: Unable to configure handler 'task'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/logging/__init__.py", line 2034, in shutdown
    h.close()
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/log/s3_task_handler.py", line 76, in close
    if self.closed:
AttributeError: 'S3TaskHandler' object has no attribute 'closed'
ERROR: Scheduler exited with exit code 0.
```

It appears this is due to the changes made in AIRFLOW-1611:

https://github.com/apache/airflow/commit/3c3a65a3fe2edbd7eee1d736735194a1ca14962a
https://issues.apache.org/jira/browse/AIRFLOW-1611

The expectation set forth in the changelog is that anyone using S3 or GCS remote logging should now setup a custom logging config.  This seems like an unrealistic expectation for using such a fundamental feature that many have relied on for at least a couple years.

Apache Airflow version: 1.10.10
Kubernetes version: 1.15

Environment:

Cloud provider or hardware configuration: AWS
OS (e.g. from /etc/os-release): python:3.7.6-buster docker image

What happened:  Running the scheduler fails and produces the AttributeError in the log message above.

What you expected to happen:

The logging configuration handler to run successfully.

**Comment by kaxil** [comment]
Which version did you upgrade it from ?

**Comment by webster-chainalysis** [comment]
I don't think I will be able to provide proper information for others to reproduce this.  It may have been related to the custom logging config.  So maybe just close it.  

But it's worth noting that this probably isn't the error message end users should see.  Furthermore, we have no desire to do any custom logging configuration and are just trying keep the standard S3 remote logging working on the new releases.

**Comment by webster-chainalysis** [comment]
Which we failed at.  And are now rolling back several minor versions to avoid those changes for now.

**Comment by ashb** [comment]
This does appear to be a problem in your custom logging config, or the logging file template. Without seeing that section of your config we can't debug this.

Airflow could probably validate this error earlier/at start up as part of validating the config to prevent "runtime" issues like this.

I'm closing this ticket now, but please feel free to re-open it with more info (the custom logging set up + config) and we can get to the bottom of this.
