### ISSUE TITLE
Airflow error in SQLLite - sqlite3.IntegrityError: columns dag_id, run_id are not unique

### ISSUE THREAD

**Issue by apps123** [apache/airflow#8851]
**Apache Airflow version**: 1.10.7

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): N/A

**Environment**: RHEL7

- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): Red Hat Enterprise Linux Server 7.8 (Maipo)
- **Kernel** (e.g. `uname -a`): Linux ip-XXXXXXXXX.internal 3.10.0-1127.el7.x86_64 #1 SMP Tue Feb 18 16:39:12 EST 2020 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**:
- **Others**:

**What happened**:

Receiving following error when running DAGs consistently
<details>
<summary>sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) columns dag_id, run_id are not unique
[SQL: INSERT INTO dag_run (dag_id, execution_date, start_date, end_date, state, run_id, external_trigger, conf) VALUES (?, ?, ?, ?, ?, ?, ?, ?)]</summary>
[2020-05-13 06:28:15,202] {taskinstance.py:1088} ERROR - (sqlite3.IntegrityError) columns dag_id, run_id are not unique
[SQL: INSERT INTO dag_run (dag_id, execution_date, start_date, end_date, state, run_id, external_trigger, conf) VALUES (?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('run_e2e.test3.verify_step_1', '2020-05-13 06:28:15.117141', '2020-05-13 06:28:15.201394', None, 'running', 'trig__2020-05-13T06:28:15.003626+00:00', 1, None)]
(Background on this error at: http://sqlalche.me/e/gkpj)
Traceback (most recent call last):
  File "/var/lib/virtualenvs/vto_e2e_0.0.10534704/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "/var/lib/virtualenvs/vto_e2e_0.0.10534704/lib64/python3.6/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: columns dag_id, run_id are not unique

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/virtualenvs/vto_e2e_0.0.10534704/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 955, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/var/lib/virtualenvs/vto_e2e_0.0.10534704/lib/python3.6/site-packages/airflow/operators/dagrun_operator.py", line 95, in execute
    replace_microseconds=False)
  File "/var/lib/virtualenvs/vto_e2e_0.0.10534704/lib/python3.6/site-packages/airflow/api/common/experimental/trigger_dag.py", line 126, in trigger_dag
    replace_microseconds=replace_microseconds,
  File "/var/lib/virtualenvs/vto_e2e_0.0.10534704/lib/python3.6/site-packages/airflow/api/common/experimental/trigger_dag.py", line 90, in _trigger_dag
    external_trigger=True,
  File "/var/lib/virtualenvs/vto_e2e_0.0.10534704/lib/python3.6/site-packages/airflow/utils/db.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/var/lib/virtualenvs/vto_e2e_0.0.10534704/lib/python3.6/site-packages/airflow/models/dag.py", line 1338, in create_dagrun
    session.commit()
  File "/var/lib/virtualenvs/vto_e2e_0.0.10534704/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 1036, in commit
    self.transaction.commit()
  File "/var/lib/virtualenvs/vto_e2e_0.0.10534704/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 503, in commit
    self._prepare_impl()
  File "/var/lib/virtualenvs/vto_e2e_0.0.10534704/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 482, in _prepare_impl
    self.session.flush()
  File "/var/lib/virtualenvs/vto_e2e_0.0.10534704/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 2496, in flush
    self._flush(objects)
  File "/var/lib/virtualenvs/vto_e2e_0.0.10534704/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 2637, in _flush
    transaction.rollback(_capture_exception=True)
  File "/var/lib/virtualenvs/vto_e2e_0.0.10534704/lib64/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/var/lib/virtualenvs/vto_e2e_0.0.10534704/lib64/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/var/lib/virtualenvs/vto_e2e_0.0.10534704/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 2597, in _flush
    flush_context.execute()
  File "/var/lib/virtualenvs/vto_e2e_0.0.10534704/lib64/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/var/lib/virtualenvs/vto_e2e_0.0.10534704/lib64/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/var/lib/virtualenvs/vto_e2e_0.0.10534704/lib64/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    insert,
  File "/var/lib/virtualenvs/vto_e2e_0.0.10534704/lib64/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 1136, in _emit_insert_statements
    statement, params
  File "/var/lib/virtualenvs/vto_e2e_0.0.10534704/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 984, in execute
    return meth(self, multiparams, params)
  File "/var/lib/virtualenvs/vto_e2e_0.0.10534704/lib64/python3.6/site-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/var/lib/virtualenvs/vto_e2e_0.0.10534704/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1103, in _execute_clauseelement
    distilled_params,
  File "/var/lib/virtualenvs/vto_e2e_0.0.10534704/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1288, in _execute_context
    e, statement, parameters, cursor, context
  File "/var/lib/virtualenvs/vto_e2e_0.0.10534704/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1482, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/var/lib/virtualenvs/vto_e2e_0.0.10534704/lib64/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/var/lib/virtualenvs/vto_e2e_0.0.10534704/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "/var/lib/virtualenvs/vto_e2e_0.0.10534704/lib64/python3.6/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) columns dag_id, run_id are not unique
[SQL: INSERT INTO dag_run (dag_id, execution_date, start_date, end_date, state, run_id, external_trigger, conf) VALUES (?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('run_e2e.test3.verify_step_1', '2020-05-13 06:28:15.117141', '2020-05-13 06:28:15.201394', None, 'running', 'trig__2020-05-13T06:28:15.003626+00:00', 1, None)]
(Background on this error at: http://sqlalche.me/e/gkpj)
[2020-05-13 06:28:15,205] {taskinstance.py:1119} INFO - Marking task as FAILED.
</details>

**What you expected to happen**: DAG to run 

**How to reproduce it**:

**Anything else we need to know**:
Happens all the time

**Comment by ashb** [comment]
This looks like it was caused by attempting to trigger the same dag twice in one second.

This commit should fix it in 1.10.7 https://github.com/apache/airflow/commit/7b4d9338a6564d2dc70c9933bc14353c2c423f7c -- please pass `replace_microseconds=false`.

(Sorry for taking any absolute age to respond to this issue.
