### ISSUE TITLE
LDAP : cannot import name LEVEL

### ISSUE THREAD

**Issue by trivoallan** [apache/airflow#966]
Hi,

I configured Airflow 1.6.2 webserver as documented in https://github.com/airbnb/airflow/blob/master/docs/security.rst#ldap

I get this error when starting the webserver:

```
webserver_1 | [2016-02-08 11:10:17,128] {__init__.py:46} CRITICAL - Cannot import authentication module airflow.contrib.auth.backends.ldap_auth. Please correct your authentication backend or disable authentication: cannot import name LEVEL
webserver_1 | Traceback (most recent call last):
webserver_1 |   File "/usr/local/bin/airflow", line 15, in <module>
webserver_1 |     args.func(args)
webserver_1 |   File "/usr/local/lib/python2.7/dist-packages/airflow/bin/cli.py", line 314, in webserver
webserver_1 |     app = cached_app(configuration)
webserver_1 |   File "/usr/local/lib/python2.7/dist-packages/airflow/www/app.py", line 119, in cached_app
webserver_1 |     app = create_app(config)
webserver_1 |   File "/usr/local/lib/python2.7/dist-packages/airflow/www/app.py", line 28, in create_app
webserver_1 |     airflow.load_login()
webserver_1 |   File "/usr/local/lib/python2.7/dist-packages/airflow/__init__.py", line 49, in load_login
webserver_1 |     raise AirflowException("Failed to import authentication backend")
webserver_1 | airflow.utils.AirflowException: Failed to import authentication backend
```

Here are relevant parts of configuration: 

```
[webserver]
# Set to true to turn on authentication : http://pythonhosted.org/airflow/installation.html#web-authentication
authenticate = True
auth_backend = airflow.contrib.auth.backends.ldap_auth
# Filter the list of dags by owner name (requires authentication to be enabled)
filter_by_owner = False

[ldap]
uri = "ldaps://xxxx:3389"
user_filter = objectClass=*
user_name_attr = sAMAccountName
superuser_filter = memberOf=CN=GRP-Git-Super-User,OU=IT,OU=Groupes,OU=Siège,OU=Aramis AUTO,DC=aramisauto,DC=local
data_profiler_filter = memberOf=CN=GRP-Git-Profiler,OU=IT,OU=Groupes,OU=Siège,OU=Aramis AUTO,DC=aramisauto,DC=local
bind_user = CN=Sync Git,OU=Utilisateurs,OU=Siège,OU=Aramis AUTO,DC=aramisauto,DC=local
bind_password = "xxx"
basedn = dc=aramsiauto,dc=local
cacert = /etc/ca/ldap_ca.crt
search_scope = LEVEL # Set this to SUBTREE if using Active Directory, and not specifying an Organizational Unit
```

The webserver runs on Debian Jessie.

**Comment by bolkedebruin** [comment]
@trivoallan is this still an issue for you? Can you please open a Jira issue if so?
