### ISSUE TITLE
airflow backfill dryrun fails with BashOperator

### ISSUE THREAD

**Issue by kretes** [apache/airflow#972]
airflow backfill MY_DAG -l -t bash_sqm -s 2016-01-05 -e 2016-01-14 -dr
fails with

```
Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 15, in <module>
    args.func(args)
  File "/usr/lib/python2.7/dist-packages/airflow/bin/cli.py", line 69, in backfill
    ti.dry_run()
  File "/usr/lib/python2.7/dist-packages/airflow/models.py", line 1037, in dry_run
    self.render_templates()
  File "/usr/lib/python2.7/dist-packages/airflow/models.py", line 1141, in render_templates
    jinja_context = self.get_template_context()
  File "/usr/lib/python2.7/dist-packages/airflow/utils.py", line 132, in wrapper
    result = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/airflow/models.py", line 1084, in get_template_context
    if 'tables' in task.params:
AttributeError: 'BashOperator' object has no attribute 'params'
```

while running this command without -dr works ok

**Comment by r39132** [comment]
Hi @kretes 
Thanks for reporting this error. I just reproduced it myself. For Future reference, please provide enough context to make it easy to reproduce. 

Here's an example : 

A.  Version of Code

```
sid-as-mbp:dags siddharth$ git log | head
commit 50002fa91830b0ad6afa1f16b023cb42447720db
Merge: 1dec1fe c4e4b06
Author: Maxime Beauchemin <maximebeauchemin@gmail.com>
Date:   Sun Feb 7 13:21:19 2016 -0800

    Merge pull request #965 from airbnb/add_mock

    Adding mock lib to devel extras_require

commit 1dec1fe076c8dbd9510f72710afaad4e18c4ae38
```

B.   Sample Code 

```
from airflow.operators import *
from airflow import DAG
from datetime import datetime, timedelta
import random

default_args = {
    'owner': 'test',
    'depends_on_past': False,
    'pool': 'test_pool',
    'start_date': datetime(2016, 1, 26, 12, 0, 0),
    'email': ['sanand@agari.com'],
    'email_on_failure': True,
    'email_on_retry': False,
    'retries': 3,
    'retry_delay': timedelta(seconds=1),
    'queue': 'default'}

dag = DAG('sid_test_4', default_args=default_args, schedule_interval='@hourly')

rand_day = datetime(2016, 2, random.randint(1, 28))
day_of_week = rand_day.weekday()

foo  = BashOperator(
    task_id='foo',
    bash_command='ls -lart .',
    dag=dag)
```

C. Sample run that fails with stack (this you did and thx for it): 

```
sid-as-mbp:dags siddharth$ airflow backfill sid_test_4 -l -t foo -s 2016-01-05 -e 2016-01-14 -dr
[2016-02-08 19:05:20,991] {__init__.py:36} INFO - Using executor SequentialExecutor
[2016-02-08 19:05:21,502] {models.py:126} INFO - Filling up the DagBag from /Users/siddharth/Projects/airflow/dags
[2016-02-08 19:05:21,503] {models.py:204} INFO - Importing /Users/siddharth/Projects/airflow/dags/sid_test_1.py
[2016-02-08 19:05:21,504] {models.py:295} INFO - Loaded DAG <DAG: sid_test_branching_1>
[2016-02-08 19:05:21,504] {models.py:204} INFO - Importing /Users/siddharth/Projects/airflow/dags/sid_test_4.py
[2016-02-08 19:05:21,504] {models.py:295} INFO - Loaded DAG <DAG: sid_test_4>
[2016-02-08 19:05:21,504] {models.py:204} INFO - Importing /Users/siddharth/Projects/airflow/dags/testdruid.py
[2016-02-08 19:05:21,505] {models.py:295} INFO - Loaded DAG <DAG: test_druid>
Dry run of DAG sid_test_4 on 2016-01-05 00:00:00
Task foo
Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/siddharth/Projects/airflow/airflow/bin/airflow", line 15, in <module>
    args.func(args)
  File "/Users/siddharth/Projects/airflow/airflow/bin/cli.py", line 70, in backfill
    ti.dry_run()
  File "/Users/siddharth/Projects/airflow/airflow/models.py", line 1091, in dry_run
    self.render_templates()
  File "/Users/siddharth/Projects/airflow/airflow/models.py", line 1195, in render_templates
    jinja_context = self.get_template_context()
  File "/Users/siddharth/Projects/airflow/airflow/utils.py", line 141, in wrapper
    result = func(*args, **kwargs)
  File "/Users/siddharth/Projects/airflow/airflow/models.py", line 1138, in get_template_context
    if 'tables' in task.params:
AttributeError: 'BashOperator' object has no attribute 'params'
```

D. Sample that works (this you did and thanks for it):

```
airflow backfill sid_test_4 -l -t foo -s 2016-01-05 -e 2016-01-14
```

**Comment by r39132** [comment]
I'm guessing the problem here is that dry_run does a shallow copy of the task object - hence, the params are not copied over. Seems easy to fix. Proceeding...

```
    def dry_run(self):
        task = self.task
        task_copy = copy.copy(task)
        self.task = task_copy

        self.render_templates()
        task_copy.dry_run()
```

**Comment by r39132** [comment]
Ok. I'm working on a fix for this now.

**Comment by r39132** [comment]
Refer to comments in the submitted PR! This is specific to task_regex and dry-run in backfill. If you remove either of dry_run or task_regex, it will work. Still, I have submitted a fix for review.
