### ISSUE TITLE
Permission denied when enabling SSL from `airflow/bin/cli.py`

### ISSUE THREAD

**Issue by pat-s** [apache/airflow#9912]
**Apache Airflow version**: 1.10.11

**Environment**:

- **Cloud provider or hardware configuration**: Exoscale
- **OS** (e.g. from /etc/os-release): bionic
- **Kernel** (e.g. `uname -a`): 4.15.0-112-generic 
- **Install tools**: Ansible
- **Others**: python 3.7

**What happened**:

Getting a permission error when trying to enable SSL.

``` 
Start airflow webserver...

Jul 21 11:51:13 airflow airflow-webserver[21377]: [2020-07-21 11:51:13,731] {__init__.py:50} INFO - Using executor SequentialExecutor
Jul 21 11:51:13 airflow airflow-webserver[21377]: [2020-07-21 11:51:13,732] {dagbag.py:396} INFO - Filling up the DagBag from /var/lib/airflow/airflow/dags
Jul 21 11:51:13 airflow airflow-webserver[21377]:  * Serving Flask app "airflow.www.app" (lazy loading)
Jul 21 11:51:13 airflow airflow-webserver[21377]:  * Environment: production
Jul 21 11:51:13 airflow airflow-webserver[21377]:    WARNING: This is a development server. Do not use it in a production deployment.
Jul 21 11:51:13 airflow airflow-webserver[21377]:    Use a production WSGI server instead.
Jul 21 11:51:13 airflow airflow-webserver[21377]:  * Debug mode: on
Jul 21 11:51:13 airflow airflow-webserver[21377]: Traceback (most recent call last):
Jul 21 11:51:13 airflow airflow-webserver[21377]:   File "/var/lib/airflow/venv/bin/airflow", line 37, in <module>
Jul 21 11:51:13 airflow airflow-webserver[21377]:     args.func(args)
Jul 21 11:51:13 airflow airflow-webserver[21377]:   File "/var/lib/airflow/venv/lib/python3.7/site-packages/airflow/utils/cli.py", line 76, in wrapper
Jul 21 11:51:13 airflow airflow-webserver[21377]:     return f(*args, **kwargs)
Jul 21 11:51:13 airflow airflow-webserver[21377]:   File "/var/lib/airflow/venv/lib/python3.7/site-packages/airflow/bin/cli.py", line 1073, in webserver
Jul 21 11:51:13 airflow airflow-webserver[21377]:     ssl_context=(ssl_cert, ssl_key) if ssl_cert and ssl_key else None)
Jul 21 11:51:13 airflow airflow-webserver[21377]:   File "/var/lib/airflow/venv/lib/python3.7/site-packages/flask/app.py", line 990, in run
Jul 21 11:51:13 airflow airflow-webserver[21377]:     run_simple(host, port, self, **options)
Jul 21 11:51:13 airflow airflow-webserver[21377]:   File "/var/lib/airflow/venv/lib/python3.7/site-packages/werkzeug/serving.py", line 990, in run_simple
Jul 21 11:51:13 airflow airflow-webserver[21377]:     s.bind(server_address)
Jul 21 11:51:13 airflow airflow-webserver[21377]: PermissionError: [Errno 13] Permission denied
Jul 21 11:51:14 airflow airflow-webserver[21377]:    ...fail!
```

**What you expected to happen**:

Normal startup.

**What do you think went wrong?**

I don't know.
SSL seems to be correctly configured in `airflow.cfg`:

```
[webserver]
web_server_port = 443
web_server_ssl_key = /etc/letsencrypt/live/<domain>/privkey.pem
web_server_ssl_cert = /etc/letsencrypt/live/<domain>/fullchain.pem
base_url = https://<domain>:443
```

Without SSL configuration, everything works on localhost:8080.

**Comment by mik-laj** [comment]
I recommend configuring SSL on the proxy server e.g. Traefik, Nginx. It is not safe to have an SSL certificate, because Airflow executes the user code and this code can steal the certificates.

**Comment by pat-s** [comment]
Thanks. I'll take a look if I can set up nginx quickly.

Do you know if this could be a possible solution to the issue I faced above?

**Comment by mik-laj** [comment]
I suspect that you are trying to run Airflow on a low port(<1024) and that requires high privileges on Linux.
https://www.w3.org/Daemon/User/Installation/PrivilegedPorts.html

**Comment by pat-s** [comment]
Ah yeah, that makes sense. Mapped it to 443 to have direct SSL access via the domain.
I should better make use of nginx probably.

After mapping it to one > 1024, I am getting some different errors. So I'll guess your hint applies here 👍 Closing here.

Thanks, learned something new today.
